*** 「長野・軽井沢のスキーバス転落事故」の報道を見ながら考えた金沢市内の運送会社市場急配センターの犯罪性と被告訴人法律家5人の関与の所業
**** 2016年から再構築する本書の構造スタイルと引用ツイートの参考資料としての取り扱いについて

2016-01-18　月曜日　20：31　＞＞ ［［　←これからの記述範囲の開始時刻］］＞＞

　実質的な記述は今年つまり2016年になって初めてかと思います。いろいろと準備をしながら開始の時期と機会をうかがっていたのですが、「長野・軽井沢のスキーバス転落事故」というテーマは、スタートに相応しく、多岐にわたる問題性とともに犠牲者と遺族に哀悼の意をもって臨みたいと思います。

　夕方、外もすっかり暗くなってから気がついたことですが、本日1月18日は、平成9年の1月18日に福井刑務所を出所した日であり、今は廃線となった「のと鉄道」の旧宇出津駅に最終の22時10分頃着の電車で母親と二人で戻った夜でした。まさに「さらば弁護士鉄道の夜」からの始まりです。

　つい先程のモトケンこと矢部善朗弁護士（京都弁護士会）の最新ツイートとしてのリツイートですが、これもなかなか問題性を考えさせてくれるものです。次のツイートになります。

R：motoken_tw（モトケン）＞2016/01/18 20:13＞ https://twitter.com/motoken_tw/status/689044922813448193 ＞ legalnews_jp （Legal News（リーガルニュース））＞ https://twitter.com/legalnews_jp/status/689042921371258880 ＞ 弁護士は説得業です。裁判所では裁判官を、交渉であれば相手方を説得します。依頼者も説得の対象です。法律は、その説得の一つのツールに過ぎません。それも、利害得失、社会的意味、人生観、社会観などに比べれば、大して説得力を持つツールではありません。（安原幸彦弁護士）

＞motoken_tw（モトケン）のリツイート＞このリツイートの日時＞2016/01/18 20:13＞ URL＞ https://twitter.com/motoken_tw/status/689044922813448193 ＞
＞motoken_tw（モトケン）がリツイートしたlegalnews_jp（Legal News（リーガルニュース））のツイートの内容＞
弁護士は説得業です。裁判所では裁判官を、交渉であれば相手方を説得します。依頼者も説得の対象です。法律は、その説得の一つのツールに過ぎません。それも、利害得失、社会的意味、人生観、社会観などに比べれば、大して説得力を持つツールではありません。（安原幸彦弁護士）
＞元のツイートの投稿日時＞2016/01/18 20:13＞元のツイートのURL＞ https://twitter.com/legalnews_jp/status/689042921371258880
＞ TwitterAPIによるデータ取得日時：　2016/01/18 20:50:34 ＞

motoken_tw/status/689044922813448193のツイート　→　Legal News（リーガルニュース）さんはTwitterを使っています: "弁護士は説得業です。裁判所では裁判官を、交渉であれば相手方を説得します。依頼者も説得の対象です。法律は、その説得の一つのツールに過ぎません。それも、利害得失、社会的意味、人生観、社会観などに比べれば、大して説得力を持つツールではありません。（安原幸彦弁護士）"

　同じ３つのツイートを3つの表示形式で掲載しました。中程のものは従来のスタイルかと思いますが、前後のものは年末年始に機能強化したスクリプトでの表示形式というか書式フォーマットの適用スタイルになります。

　これからという直前のタイミングで、たまたま目についたモトケンこと矢部善朗弁護士（京都弁護士会）のリツイートですが、これはこれから書く対象の参考として、私自身も深く考えさせられるものであり、冒頭に掲げる意味でご紹介をしました。

2016-01-19　火曜日　03：50　＜＜ ［［　←これまでの記述範囲の終了時刻］］＜＜


2016-01-19　火曜日　03：58　＞＞ ［［　←これからの記述範囲の開始時刻］］＞＞

　食事をしたあと横になって眠ってしまい、起きたのは0時30分ぐらいだったように思います。目が冴えて眠れそうにないので、弁護士のツイートの収集整理など作業を続行していました。

　まだ確定的に決めてはいないのですが、今年つまり2016年からの本書の記述のみを本文とし、昨年までに作成した分はデジタルデータとしてDVDに収録する参考資料という扱いにすることを考えています。

　また、文書の記載方法や構造のスタイルも、昨年までとは違ったものにしようと考えています。基本的に一つのファイルでのみ本文の編集作業をすることにしました。

　Emacsのorg-modeで作業をしていることは同じですが、年末年始の頃から従来とは違い、引用するツイートを参考資料として別ファイルに保存することにしました。そのファイルも現在は2つ目です。

　もう2週間ほど前になるかと思いますが、最初のファイルをEmacsで開いた時、ファイルのサイズが10MBを超えているという確認メッセージが出てきました。こういうメッセージは見たのも聞いたのも初めてでしたが、動作に不満もなく扱えていました。

　それでも今後、ファイルの取り扱いで支障が出ることも考えられるので、分割して作成することにしました。ファイル名も現段階では仮のものです。現在、最初のファイルは11MB、2つ目が7.1MB となっています。

　細かい説明は、いずれ専用の項目を作って書いておきたいと考えているのですが、この参考資料はデータベースに登録したツイートの引用で、テキストとHTMLを併記しています。そして同じ内容のものを、ブログの方に記事として投稿しています。

　HTMLで記載したものは、インターネットでブログの記事として閲覧する際、Twitterのサービスである埋め込みコードのスタイルが適用されて、とても読みやすいものになっています。

　基本的にツイートが投稿者によって削除された場合、埋め込みコードのスタイルは適用されなくなるのですが、最初の頃は私のデータベースの登録の仕方に問題があって、スタイルがまったく適用されない記事もありました。

　見つけながら修正などしたのですが、修正されないまま残っているものもあるかもしれません。問題の原因は、データベースへの登録の際、ツイートとリツイートの判別に不十分さがあったことです。

　極端な非公式RTの場合、本人のツイートをリツイートとして判別してしまい、リツイートしての処理をプログラムで行っていたので、必要な情報が読み込めず、エラーを起こしていたのです。

　記事の一ページに沢山のツイートがあって、そのうちの一つでも問題があると、JavaScriptによる埋め込みコードのスタイルが適用されなくなっていました。初めは問題のツイート一つだけの不適用だったようにも思うのですが、原因が分かるまで時間もかかりました。

　この埋め込みコードの問題は1月の7日頃の記事の投稿から問題が解決されていると思いますが、その後に少し記述方法の変更をしているので、問題性のない最終的な書式スタイルになっているのは1月9日以降の投稿ではないかと思います。

　とにかくツイートの詳細は出来るだけ本文から切り離すようにしました。詳細はブログの記事のURLとしてご紹介するとともに、最低限の投稿者と本文の内容という情報を、本文に記載するようにします。

　再掲のツイートですが、本文での要約の書式スタイルは、2つ用意しました。一つは次のスタイルです。

R：motoken_tw（モトケン）＞2016/01/18 20:13＞ https://twitter.com/motoken_tw/status/689044922813448193 ＞ legalnews_jp （Legal News（リーガルニュース））＞ https://twitter.com/legalnews_jp/status/689042921371258880 ＞ 弁護士は説得業です。裁判所では裁判官を、交渉であれば相手方を説得します。依頼者も説得の対象です。法律は、その説得の一つのツールに過ぎません。それも、利害得失、社会的意味、人生観、社会観などに比べれば、大して説得力を持つツールではありません。（安原幸彦弁護士）

　モトケンこと矢部善朗弁護士（京都弁護士会）のリツイートですが、投稿者のアカウント名、リツイートの日時、リツイートのURL、リツイートされたアカウント名、リツイートされたツイートのURL、そしてリツイートの本文という情報です。

　次はより簡易にした要約スタイルです。

motoken_tw/status/689044922813448193のツイート　→　Legal News（リーガルニュース）さんはTwitterを使っています: "弁護士は説得業です。裁判所では裁判官を、交渉であれば相手方を説得します。依頼者も説得の対象です。法律は、その説得の一つのツールに過ぎません。それも、利害得失、社会的意味、人生観、社会観などに比べれば、大して説得力を持つツールではありません。（安原幸彦弁護士）"

　「motoken_tw/status/689044922813448193のツイート」という部分はリツイートの一意の情報であるURLの一部を使っています。桁数の大きな数値の部分はツイートのIDです。

　以前にも書いたことがあるかと思いますが、私の経験では、このツイートのIDはアカウント毎の固有のものではなく、Twitter全体として固有のIDとなっているようです。

　アカウントの部分を変えて、 https://twitter.com/hirono_hideki/status/689044922813448193 としても同じようにモトケンこと矢部善朗弁護士（京都弁護士会）にリツイートされたツイートが表示されます。

　ややこしいですが、リツイートのURLそのものを開くことは出来ず、リツイートされたURLにリダイレクトされます。リツイートのURLというものが、通常の方法では取得できません。TwitterのAPIを使って取得するのも方法の一つです。

　リツイートがあとで取り消されてリンク切れになるという場合もありますし、深澤諭史弁護士などは、過去のリツイートをいったん取り消してから、リツイートをやり直すということもやっているようです。他に見たことはないです。

　また、上記のデータは最も取り扱いが容易でトラブルが起きにくい一行のデータにしています。ツイートの中に改行が交じる場合がありますが、「＜改行＞」という文字列に置き換えています。難を言えば一行が長くなるのでTwitterへの投稿はほとんど出来ません。

　改行の変換はプログラムのなかで「#{tweet.text}".gsub(/\n/, '＜改行＞')」というような処理を加えているだけです。なお、Windowsパソコンとは改行コードが異なっています。UNIXの改行コードです。

　Twitterの引用については一通りのご説明が書けたかと思いますが、今年から改めるつもりでいた悪い癖が出てしまい、見出しのタイトルとは異なることを沢山書いてしましました。

　これからはキビキビと切り替えもやっていく方針です。事後のご説明になることもあるかもしれません。また、出来るだけ、ブログの記事のURLの掲載などで、書いている道筋をわかりやすくしたいと考えています。

　予定とは違った方向に流れてしまったので、これまでに書いた内容に応じた見出しをつけ直したいと思います。

2016-01-19　火曜日　05：16　＜＜ ［［　←これまでの記述範囲の終了時刻］］＜＜







**** モトケンこと矢部善朗弁護士（京都弁護士会）と落合洋司弁護士（東京弁護士会）の主としてSMAP解散騒動謝罪に関するツイート・リツイートを読んでバス会社の問題ともに感じたこと。

2016-01-19　火曜日　05：38　＞＞ ［［　←これからの記述範囲の開始時刻］］＞＞

＞＞＞　2016年から再構築する本書の構造スタイルと引用ツイートの参考資料としての取り扱いについて http://hirono-hideki.cocolog-nifty.com/blog/2016/01/2016-ca10.html

　これからの記述は上記ブログ記事の続きになります。

　予め用意していたものですが、次が引用ツイートの簡易要約版です。このデータはデータベースの情報ではなく、ツイートのURLを使ってWebページのタイトル名としての情報を取得したものです。

yjochi/status/689049880514281473のツイート　→　落合洋司（オンラインチャット相談対応可）さんはTwitterを使っています: "愛の勝利。→アイドル交際禁止「行き過ぎ」　地裁、会社側の請求棄却：朝日新聞デジタル https://t.co/bGT2pj4PRn"

yjochi/status/689054840735961089のツイート　→　落合洋司（オンラインチャット相談対応可）さんはTwitterを使っています: "平成の2.26事件みたいになってきたな。雪は汚れていた。"

yjochi/status/689059532513787904のツイート　→　落合洋司（オンラインチャット相談対応可）さんはTwitterを使っています: "利を捨て義に生きた真田幸村にはなかなかなれない。それが人生だろう。"

motoken_tw/status/689096537327165446のツイート　→　モトケンさんはTwitterを使っています: "謝罪するべきはＳＭＡＰのメンバーだったのか？＞ＳＭＡＰ、存続へ　テレビ番組でメンバーが騒動を謝罪：朝日新聞デジタル https://t.co/jlcSrWE53i"

motoken_tw/status/689097782716674049のツイート　→　モトケンさんはTwitterを使っています: "彼らが社会にどんな迷惑をかけたのでしょう？少なくとも私はなんの迷惑もかけられていません。 https://t.co/xb4uv0ob8h"

motoken_tw/status/689099514725183488のツイート　→　モトケンさんはTwitterを使っています: "事務所の観点で言えば、事務所のマネージメントが救い難いほど下手というふうに見えます。彼らは十二分に事務所に利益をもたらしているでしょう。所属タレントは一生事務所の奴隷というわけでもないでしょうし。 https://t.co/ILm3y5slpm"

motoken_tw/status/689102388133756928のツイート　→　モトケンさんはTwitterを使っています: "マスコミが勝手に騒いでるだけだもんな。この文脈ではマスゴミと言いたい気分。 https://t.co/SSUX0hwvsD"

motoken_tw/status/689107154377281536のツイート　→　モトケンさんはTwitterを使っています: "普段テレビ見ない人だから、どうでもいいんだけど。"

motoken_tw/status/689108028713496578のツイート　→　こたんせ~メンタルリセットさんはTwitterを使っています: "しかし、今回の謝罪は、副社長的には溜飲を下げることができたかもしれないけど、誰も得していないよね？事務所のブラックさが出たし、キムタクの位置も賛否が分かれるしその他のメンバーも同じ…抑えきれなかったんだなぁって思う"

yjochi/status/689124963408719872のツイート　→　落合洋司（オンラインチャット相談対応可）さんはTwitterを使っています: "反乱軍が投降、帰順してきました、お騒がせしました、みたいな展開になりつつあるが、大義はどこに、という点は極めて曖昧なままという感じ。"

yjochi/status/689126689272549376のツイート　→　落合洋司（オンラインチャット相談対応可）さんはTwitterを使っています: "前近代的な芸者置屋みたいな芸能プロダクション、血縁最優先、実力で盛り上げてきた番頭排除、やり手ババアの勝利、高笑い、みたいな構図では、げんなりするなというのが無理だろうな。"

yjochi/status/689128990213193730のツイート　→　落合洋司（オンラインチャット相談対応可）さんはTwitterを使っています: "お客様は神様と言いながら実は神様は特定芸能プロのやり手ババア、国民が主権者と言いながら牛耳っているのは特定のアメ公、みたいなネジレの中に自分たちがいて、それで良いのかという視点も必要だろう。"

　プログラムの処理に使ったのと同じTwitterのURLの一覧を基に、テキストとHTMLとしてのTwitterの埋め込みコードを使った詳細情報は次のブログ記事です。

本文引用：モトケンこと矢部善朗弁護士（京都弁護士会）と落合洋司弁護士（東京弁護士会）の主としてSMAP解散騒動謝罪に関するツイート・リツイートのまとめ（2アカウント、12件、2016-01-19 03:04） http://hirono-hideki.cocolog-nifty.com/blog/2016/01/smap2122016-01-.html

　長野・軽井沢のスキーバス事故の報道やバス会社の対応について書くつもりでいたところ、0時半ころか夜中に目がさめてから目についたのが、上記のモトケンこと矢部善朗弁護士（京都弁護士会）と落合洋司弁護士（東京弁護士会）のツイートです。

　ほぼ同じタイミングで、同じSMAPの解散騒動謝罪の問題に関するツイートをしていたので、それも珍しいことかと思いました。

　私の問題意識のなかで弁護士として東西の横綱のような存在の発言の揃い踏みだったので、バス会社の問題とともに色々と感慨が頭をよぎりました。情報の共有としても参考にしていただきたいところです。

　私自身、芸能ニュースには関心も低くSMAPのCDも一枚も買ったことはないのですが、ある程度のことはテレビの報道で知っています。謝罪会見については、まだ他に情報はほとんど見ていない状況です。スポーツ新聞の売上が1.5倍になったことも知っています。

　スポーツ新聞の売上が1.5倍になったり、解散を阻止するための活動で過去のCDの売上が伸びてオリコンの9位になったというような情報も見ていますが、5年後の東京オリンピックの関係者となっていることは明らかに社会的影響が大きいのではと考えていました。次のニュースです。

www.fnn-news.com: SMAP「解散可能性... http://www.fnn-news.com/news/headlines/articles/CONN00313494.html

　Webページのタイトルからは十分な情報が得られませんでしたが、記事の見出しは「SMAP「解散可能性」　五輪担当相「引き続き応援してほしい」」となっています。

　さきほど「簡易要約版」と書いたように思いますが、ツイートの本文は改行以外そのままなので、要約というのは正しくないと思い直しました。「簡易版」に訂正します。

　モトケンこと矢部善朗弁護士（京都弁護士会）のツイートも落合洋司弁護士（東京弁護士会）のツイートもどちらも、らしさがよく現れていると思いました。モトケンこと矢部善朗弁護士（京都弁護士会）の場合、それは「寛容さ」というものですが、一貫した理念や態度とは、到底思えないものです。

　ここでもその反射効のようなかたちで現れていますが、「motoken_tw/status/689102388133756928のツイート」では、「マスゴミ」という表現まで使っています。厳しいというのか、そんな単純なものではないと思いますがまさに、らしさの一事例かと思います。

　このマスコミに対する姿勢というのは他の弁護士にも共通して見られることの多い特徴の一つで、それがわかりやすく現れているのが、次に取り上げる予定のバス事故の報道に関する問題です。昨年の3月頃だったように思いますが、川崎の少年殺害事件の空気感を思い起こさせるものがあります。

　落合洋司弁護士（東京弁護士会）の方が、バス事故の事故の状況に関するツイートが多かったものの、他の弁護士やそれに類いした法クラのツイートでも、バス会社の対応に関する反応というのは、今のところほとんど見ていないように思います。

　眈々とした様子見段階かとも思えるのですが、そういう意味でも「SMAPの解散騒動謝罪会見」に関する反応は、異例の速さを感じさせるとともに、断定的な評価にも特異なものを感じているところです。

　私自身、SMAPや芸能関係の話題は関心も薄いので、たまたま見たテレビの報道以外に情報は得ておらず、事情もわからないので決めつけたことも言えないのですが、「やり手ババア」というほどの醜聞なのかと、疑問に感じています。

　また、ここ最近の落合洋司弁護士（東京弁護士会）は、オンライン有料相談を始めたとかで、控えめのツイートが多くなったような印象を持っていただけに、過激さを余計に感じるのかもしれないですが、ご本人にはそれほど憤る問題が含まれているのかもしれません。かっての検察批判も彷彿と感じました。

2016-01-19　火曜日　06：55　＜＜ ［［　←これまでの記述範囲の終了時刻］］＜＜


**** 法クラ各位には釈迦に説法、といいながらバス事故のSNSの写真転載報道を問題視する深澤諭史弁護士のツイート・リツイートのについて

****  「福岡高裁宮崎支部のDNA鑑定・逆転無罪判決」関連のツイート・リツイートのまとめ（17アカウント、27件、2016-01-14 16:56）

TAKEDAmasahiro/status/686778082544373760のツイート　→　竹田昌弘さんはTwitterを使っています: "「福岡高裁宮崎支部…は…強姦罪に問われた…被告（23）の控訴審判決で、懲役4年とした一審判決を破棄し、無罪を言い渡した。控訴審で裁判所が…実施したDNA鑑定で、被害女性の体内から…別人のDNA型が検出され…た…」 https://t.co/GwLIjiYaVV (-`_-´#)"

kotadon/status/686779032923279360のツイート　→　こたんせ~メンタルリセットさんはTwitterを使っています: "メモ廃棄ってありえんわ…【＜鹿児島・強姦事件＞２３歳被告に逆転無罪　高裁宮崎支部（毎日新聞） - Yahoo!ニュース】 https://t.co/YMwo214tke #Yahooニュース"

1961kumachin/status/686779355079426048のツイート　→　中村元弥さんはTwitterを使っています: "＜鹿児島・強姦事件＞２３歳被告に逆転無罪　高裁宮崎支部（毎日新聞） - Yahoo!ニュース https://t.co/C5q3Lux3pV #Yahooニュース"

yjochi/status/686797660741742592のツイート　→　落合洋司（オンラインチャット相談対応可）さんはTwitterを使っています: "＜鹿児島・強姦事件＞２３歳被告に逆転無罪　高裁宮崎支部 https://t.co/IkSE26nOHh"

theokinawatimes/status/686809871954542593のツイート　→　沖縄タイムスさんはTwitterを使っています: "強姦事件で逆転無罪、別人ＤＮＡ　福岡高裁宮崎支部　https://t.co/c0skP5CNca"

amneris84/status/686822836141309952のツイート　→　Shoko EgawaさんはTwitterを使っています: "強姦の事実に関しては、客観的な裏付けがなく、あるのは被害者の証言のみ。高裁判決は、その被害者... - 強姦事件で逆転無罪＝DNA鑑定で別人の型―福岡高裁支部（時事通信） https://t.co/QXoEOtoWsK #YJnewsComment"

okumuraosaka/status/686843800099008513のツイート　→　TORU OKUMURAさんはTwitterを使っています: "控訴審で行われた日本大学の押田茂實名誉教授（法医学）による再鑑定では、鹿児島・強姦事件：２３歳被告に逆転無罪　高裁宮崎支部 - 毎日新聞 https://t.co/nJWQp3jU6z"

okaguchik/status/686850129857413121のツイート　→　岡口基一さんはTwitterを使っています: "ＤＮＡ鑑定は，警察から切り離した独立の組織が、弁護人や被疑者、被告人からの（再審事件を含む）嘱託に基づく鑑定等を行う、という仕組みはどうでしょう＜改行＞https://t.co/eAV890VcUg＜改行＞（こういう表現にすると，表現の自由が「過度に広汎に」制約されている俺でもつぶやける）"

nakanori930/status/686852226556403712のツイート　→　弁護士 中村憲昭さんはTwitterを使っています: "今の刑事裁判では、無罪推定なんか働かず、被告人がほぼ無罪であることを立証しないと無罪にならない。弁護士も証拠評価を学んでるのに、刑事と国賠に勝てないのは、もはや弁護士の能力ではなく、裁判官の問題としか考えられないと常々思ってる。"

taniyama/status/686865083369000960のツイート　→　弁護士 谷山智光さんはTwitterを使っています: "高裁がよく鑑定を行ったなという感想。いい判決。 RT @nhk_news: “女性に乱暴”の罪 実刑取り消し無罪判決 https://t.co/uaKq1MVaX9 #nhk_news"

manna2010able/status/686873572908732416のツイート　→　島岡まなさんはTwitterを使っています: "逆転無罪報道で、冤罪の主要因である捜査の杜撰さや裁判官の事実認定の誤りこそが問われるべきなのに、性犯罪では特に「被害者供述の信用性に問題があった」とまるで被害者が嘘つきかのように言うのは絶対におかしい！国側(強者)の誤りを被害者(弱者)に押し付ける構造こそが差別であり人権侵害！"

motoken_tw/status/686896968954597376のツイート　→　モトケンさんはTwitterを使っています: "こういうニュースを読んで、寺澤氏 @Yu_TERASAWA や藤原監督 @toshi_fujiwara は、司法に対する信頼を感じるのか不信を感じるのかどっちだろう？＞強姦罪に問われ一審判決で懲役4年とされた男性 逆転無罪に https://t.co/YBwPzpABEa"

maedatsunehiko/status/687031397337460737のツイート　→　前田恒彦　－元特捜部主任検事のつぶやき－さんはTwitterを使っています: "精液から別人のDNA型が検出され、控訴審で逆転無罪となった鹿児島強姦事件。県警で不可能とされた鑑定をしたのがこの本の著者。DNA型鑑定の問題点や落とし穴を分かりやすく解説しており、オススメ。→押田茂實『法医学者が見た再審無罪の真相』https://t.co/b8dGyNqFQQ"

1961kumachin/status/687040702404935680のツイート　→　中村元弥さんはTwitterを使っています: "鹿児島・強姦事件：逆転無罪　「証拠を都合良く評価」　弁護側、ずさん捜査を批判 - 毎日新聞 https://t.co/xmlVjwGMxG  　「かつての交際相手とは今も付き合いはあるが、「交際相手ではなく友達」だ。県警の捜査によって描いた夢はゆがめられた。」"

uwaaaa/status/687054922861314048のツイート　→　サイ太さんはTwitterを使っています: "被害者全般が嘘つきだとは言ってないような…"

uwaaaa/status/687056121215848448のツイート　→　サイ太さんはTwitterを使っています: "むしろ「性犯罪の被害者が嘘をつくはずがない」という思い込みが冤罪の温床なのでは。"

1961kumachin/status/687056594874437632のツイート　→　中村元弥さんはTwitterを使っています: "東京新聞:鹿児島・強姦事件　「県警の証拠隠し」言及　福岡高裁支部、被告に逆転無罪:社会(TOKYO Web) https://t.co/PspSPjPSFr"

terayasan/status/687058512338259968のツイート　→　てらやさん☆さんはTwitterを使っています: "岡田裁判官は当職の刑裁修習の配属部の部長でした。修習生に自分が無罪にした記録を使って起案させる（事前に結論は教えない）方です。さすがですね。＜改行＞＜改行＞＜強姦事件＞証拠を都合良く評価…弁護側、ずさん捜査を批判 - Yahoo!ニュース https://t.co/CEntHM9y4f"

terayasan/status/687061859380236288のツイート　→　てらやさん☆さんはTwitterを使っています: "実務修習最終日の歓送会で岡田裁判官にご挨拶した際、「君が修習で起案していった事件、よくできていたので私も君と同じ結論に傾いていたんだけれど、弁護人の弁論を聞いて考えを変えて、一部無罪にしたよ。さすがはプロの弁論の説得力だね。」とおっしゃっていたのが印象的です。"

kotadon/status/687075353924247552のツイート　→　こたんせ~メンタルリセットさんはTwitterを使っています: "第一審の裁判官について事実認定能力がないとして、それを全裁判官に広げる人もいるけど、無罪判決を出したのも裁判官…【＜強姦事件＞証拠を都合良く評価…弁護側、ずさん捜査を批判（毎日新聞） - Yahoo!ニュース】 https://t.co/ns6ewIebwz #Yahooニュース"

lawkus/status/687080507398426626のツイート　→　ystkさんはTwitterを使っています: "冤罪事件について「(自称も含む)被害者」が非難されるべきか否かは、事案によるとしか。故意に虚偽供述をしたような事案であれば文句なしに悪い。一方、勘違いから別人を犯人と名指ししてしまったような場合は、捜査機関や裁判所が見抜くべきであって、悪気のない被害者を責めるのも酷だと思う。"

terayasan/status/687081280228347904のツイート　→　てらやさん☆さんはTwitterを使っています: "判例秘書で岡田部長のお名前をキーワードにして検索すると無罪判決がたくさん出てくるなぁｗ もちろん，希有な無罪判決だからこそ判例秘書に載っているんだけど。"

motoken_tw/status/687085471919292416のツイート　→　モトケンさんはTwitterを使っています: "酷い捜査と酷い一審判決。鹿児島県警は志布志事件の前科があるので推して知るべしだが、鹿児島地検にもバカ検事しか集まらないのか？＞東京新聞:鹿児島・強姦事件　「県警の証拠隠し」言及　福岡高裁支部、被告に逆転無罪:社会 https://t.co/pJ8i0t7SOz"

sakamotomasayuk/status/687190734550634496のツイート　→　坂本正幸さんはTwitterを使っています: "九州の検察は鹿児島県警を守る義務でもあるのか？"

okumuraosaka/status/687395448928141312のツイート　→　TORU OKUMURAさんはTwitterを使っています: "鹿児島・強姦事件：被告に逆転無罪判決　被告、弁護士と一問一答　／鹿児島 - 毎日新聞 https://t.co/WLIV9GjZc1"

uwaaaa/status/687425647275315200のツイート　→　サイ太さんはTwitterを使っています: "鑑定試料を全量消費しちゃうのも問題ですよねー。保管場所どうするんだっていう話もありますが…"

maedatsunehiko/status/687469280745635841のツイート　→　前田恒彦　－元特捜部主任検事のつぶやき－さんはTwitterを使っています: "精液から別人のDNA型が検出され、控訴審で逆転無罪となった鹿児島強姦事件。不都合な鑑定結果を隠そうとした可能性にまで言及する高裁支部の警察・検察批判も図星を突いた感がある。→https://t.co/cBwY1XWUfp"

TAKEDAmasahiro/status/686778082544373760のツイート　→　竹田昌弘さんはTwitterを使っています: "「福岡高裁宮崎支部…は…強姦罪に問われた…被告（23）の控訴審判決で、懲役4年とした一審判決を破棄し、無罪を言い渡した。控訴審で裁判所が…実施したDNA鑑定で、被害女性の体内から…別人のDNA型が検出され…た…」 https://t.co/GwLIjiYaVV (-`_-´#)"

kotadon/status/686779032923279360のツイート　→　こたんせ~メンタルリセットさんはTwitterを使っています: "メモ廃棄ってありえんわ…【＜鹿児島・強姦事件＞２３歳被告に逆転無罪　高裁宮崎支部（毎日新聞） - Yahoo!ニュース】 https://t.co/YMwo214tke #Yahooニュース"

1961kumachin/status/686779355079426048のツイート　→　中村元弥さんはTwitterを使っています: "＜鹿児島・強姦事件＞２３歳被告に逆転無罪　高裁宮崎支部（毎日新聞） - Yahoo!ニュース https://t.co/C5q3Lux3pV #Yahooニュース"

yjochi/status/686797660741742592のツイート　→　落合洋司（オンラインチャット相談対応可）さんはTwitterを使っています: "＜鹿児島・強姦事件＞２３歳被告に逆転無罪　高裁宮崎支部 https://t.co/IkSE26nOHh"

theokinawatimes/status/686809871954542593のツイート　→　沖縄タイムスさんはTwitterを使っています: "強姦事件で逆転無罪、別人ＤＮＡ　福岡高裁宮崎支部　https://t.co/c0skP5CNca"

amneris84/status/686822836141309952のツイート　→　Shoko EgawaさんはTwitterを使っています: "強姦の事実に関しては、客観的な裏付けがなく、あるのは被害者の証言のみ。高裁判決は、その被害者... - 強姦事件で逆転無罪＝DNA鑑定で別人の型―福岡高裁支部（時事通信） https://t.co/QXoEOtoWsK #YJnewsComment"

okumuraosaka/status/686843800099008513のツイート　→　TORU OKUMURAさんはTwitterを使っています: "控訴審で行われた日本大学の押田茂實名誉教授（法医学）による再鑑定では、鹿児島・強姦事件：２３歳被告に逆転無罪　高裁宮崎支部 - 毎日新聞 https://t.co/nJWQp3jU6z"

okaguchik/status/686850129857413121のツイート　→　岡口基一さんはTwitterを使っています: "ＤＮＡ鑑定は，警察から切り離した独立の組織が、弁護人や被疑者、被告人からの（再審事件を含む）嘱託に基づく鑑定等を行う、という仕組みはどうでしょう＜改行＞https://t.co/eAV890VcUg＜改行＞（こういう表現にすると，表現の自由が「過度に広汎に」制約されている俺でもつぶやける）"

nakanori930/status/686852226556403712のツイート　→　弁護士 中村憲昭さんはTwitterを使っています: "今の刑事裁判では、無罪推定なんか働かず、被告人がほぼ無罪であることを立証しないと無罪にならない。弁護士も証拠評価を学んでるのに、刑事と国賠に勝てないのは、もはや弁護士の能力ではなく、裁判官の問題としか考えられないと常々思ってる。"

taniyama/status/686865083369000960のツイート　→　弁護士 谷山智光さんはTwitterを使っています: "高裁がよく鑑定を行ったなという感想。いい判決。 RT @nhk_news: “女性に乱暴”の罪 実刑取り消し無罪判決 https://t.co/uaKq1MVaX9 #nhk_news"

manna2010able/status/686873572908732416のツイート　→　島岡まなさんはTwitterを使っています: "逆転無罪報道で、冤罪の主要因である捜査の杜撰さや裁判官の事実認定の誤りこそが問われるべきなのに、性犯罪では特に「被害者供述の信用性に問題があった」とまるで被害者が嘘つきかのように言うのは絶対におかしい！国側(強者)の誤りを被害者(弱者)に押し付ける構造こそが差別であり人権侵害！"

motoken_tw/status/686896968954597376のツイート　→　モトケンさんはTwitterを使っています: "こういうニュースを読んで、寺澤氏 @Yu_TERASAWA や藤原監督 @toshi_fujiwara は、司法に対する信頼を感じるのか不信を感じるのかどっちだろう？＞強姦罪に問われ一審判決で懲役4年とされた男性 逆転無罪に https://t.co/YBwPzpABEa"

maedatsunehiko/status/687031397337460737のツイート　→　前田恒彦　－元特捜部主任検事のつぶやき－さんはTwitterを使っています: "精液から別人のDNA型が検出され、控訴審で逆転無罪となった鹿児島強姦事件。県警で不可能とされた鑑定をしたのがこの本の著者。DNA型鑑定の問題点や落とし穴を分かりやすく解説しており、オススメ。→押田茂實『法医学者が見た再審無罪の真相』https://t.co/b8dGyNqFQQ"

1961kumachin/status/687040702404935680のツイート　→　中村元弥さんはTwitterを使っています: "鹿児島・強姦事件：逆転無罪　「証拠を都合良く評価」　弁護側、ずさん捜査を批判 - 毎日新聞 https://t.co/xmlVjwGMxG  　「かつての交際相手とは今も付き合いはあるが、「交際相手ではなく友達」だ。県警の捜査によって描いた夢はゆがめられた。」"

uwaaaa/status/687054922861314048のツイート　→　サイ太さんはTwitterを使っています: "被害者全般が嘘つきだとは言ってないような…"

uwaaaa/status/687056121215848448のツイート　→　サイ太さんはTwitterを使っています: "むしろ「性犯罪の被害者が嘘をつくはずがない」という思い込みが冤罪の温床なのでは。"

1961kumachin/status/687056594874437632のツイート　→　中村元弥さんはTwitterを使っています: "東京新聞:鹿児島・強姦事件　「県警の証拠隠し」言及　福岡高裁支部、被告に逆転無罪:社会(TOKYO Web) https://t.co/PspSPjPSFr"

terayasan/status/687058512338259968のツイート　→　てらやさん☆さんはTwitterを使っています: "岡田裁判官は当職の刑裁修習の配属部の部長でした。修習生に自分が無罪にした記録を使って起案させる（事前に結論は教えない）方です。さすがですね。＜改行＞＜改行＞＜強姦事件＞証拠を都合良く評価…弁護側、ずさん捜査を批判 - Yahoo!ニュース https://t.co/CEntHM9y4f"

terayasan/status/687061859380236288のツイート　→　てらやさん☆さんはTwitterを使っています: "実務修習最終日の歓送会で岡田裁判官にご挨拶した際、「君が修習で起案していった事件、よくできていたので私も君と同じ結論に傾いていたんだけれど、弁護人の弁論を聞いて考えを変えて、一部無罪にしたよ。さすがはプロの弁論の説得力だね。」とおっしゃっていたのが印象的です。"

kotadon/status/687075353924247552のツイート　→　こたんせ~メンタルリセットさんはTwitterを使っています: "第一審の裁判官について事実認定能力がないとして、それを全裁判官に広げる人もいるけど、無罪判決を出したのも裁判官…【＜強姦事件＞証拠を都合良く評価…弁護側、ずさん捜査を批判（毎日新聞） - Yahoo!ニュース】 https://t.co/ns6ewIebwz #Yahooニュース"

lawkus/status/687080507398426626のツイート　→　ystkさんはTwitterを使っています: "冤罪事件について「(自称も含む)被害者」が非難されるべきか否かは、事案によるとしか。故意に虚偽供述をしたような事案であれば文句なしに悪い。一方、勘違いから別人を犯人と名指ししてしまったような場合は、捜査機関や裁判所が見抜くべきであって、悪気のない被害者を責めるのも酷だと思う。"

terayasan/status/687081280228347904のツイート　→　てらやさん☆さんはTwitterを使っています: "判例秘書で岡田部長のお名前をキーワードにして検索すると無罪判決がたくさん出てくるなぁｗ もちろん，希有な無罪判決だからこそ判例秘書に載っているんだけど。"

motoken_tw/status/687085471919292416のツイート　→　モトケンさんはTwitterを使っています: "酷い捜査と酷い一審判決。鹿児島県警は志布志事件の前科があるので推して知るべしだが、鹿児島地検にもバカ検事しか集まらないのか？＞東京新聞:鹿児島・強姦事件　「県警の証拠隠し」言及　福岡高裁支部、被告に逆転無罪:社会 https://t.co/pJ8i0t7SOz"

sakamotomasayuk/status/687190734550634496のツイート　→　坂本正幸さんはTwitterを使っています: "九州の検察は鹿児島県警を守る義務でもあるのか？"

okumuraosaka/status/687395448928141312のツイート　→　TORU OKUMURAさんはTwitterを使っています: "鹿児島・強姦事件：被告に逆転無罪判決　被告、弁護士と一問一答　／鹿児島 - 毎日新聞 https://t.co/WLIV9GjZc1"

uwaaaa/status/687425647275315200のツイート　→　サイ太さんはTwitterを使っています: "鑑定試料を全量消費しちゃうのも問題ですよねー。保管場所どうするんだっていう話もありますが…"

maedatsunehiko/status/687469280745635841のツイート　→　前田恒彦　－元特捜部主任検事のつぶやき－さんはTwitterを使っています: "精液から別人のDNA型が検出され、控訴審で逆転無罪となった鹿児島強姦事件。不都合な鑑定結果を隠そうとした可能性にまで言及する高裁支部の警察・検察批判も図星を突いた感がある。→https://t.co/cBwY1XWUfp"

**** モトケンこと矢部善朗弁護士（@motoken_tw）と落合洋司弁護士のジャニーズ事務所を暴力団や女郎屋などとも酷評する

motoken_tw/status/689227041216987138のツイート　→　坂本正幸さんはTwitterを使っています: "俺に逆らったら商売できねぇぞ！＜改行＞という社会が当たり前だと思っている人たちがいるというだけで、日本はまだまだだと思う"

motoken_tw/status/689227405752283136のツイート　→　あさいろくさんはTwitterを使っています: "SMAPを公衆の面前で謝罪させ恥をかかせた、ジャニーズ・メリー副社長の横暴（Business Journal） - Yahoo!ニュース https://t.co/etx2D7ahWm　ジャニーズ事務所が四人に謝罪するべき。"

motoken_tw/status/689228417263337473のツイート　→　モトケンさんはTwitterを使っています: "日本最大の暴力団だって、マネージメントに失敗すると分裂する。上層部は権力にあぐらをかいてるから自分たちが失敗していることを自覚できない。そのうち本当に崩壊するだろうな、あの事務所。"

yjochi/status/689238398578503680のツイート　→　土曜日さんはTwitterを使っています: "朝から会社で上司とか先輩と＜改行＞「ただの人質だった」＜改行＞「俺らなんかよりよっぽど社畜だよ」＜改行＞「とんだブラック企業だ」＜改行＞「もうSMAPを解放してあげたい…」って仕事の話より真剣なミーティングになってる"

yjochi/status/689239343521648640のツイート　→　ライブドアニュースさんはTwitterを使っています: "【SMAP生会見】めざましテレビが感想を募集→炎上状態に＜改行＞https://t.co/JhekVasGX7＜改行＞＜改行＞「（独立が報じられた）4人を晒し者にした」「意味不明な内容」「感想を募るという配慮の無さ」など批判ツイートが殺到している。 https://t.co/EOORpFXFJD"

yjochi/status/689240237155864576のツイート　→　落合洋司（オンラインチャット相談対応可）さんはTwitterを使っています: "世界に一つだけの花は、実は日本によくいる社畜でした、がオチかな。悲しい結末。"

yjochi/status/689242750663839744のツイート　→　真実を探すブログさんはTwitterを使っています: "SMAPの謝罪会見を見ていると、分裂した山口組の方が民主的な気がしてきたｗ"

yjochi/status/689243360201060352のツイート　→　落合洋司（オンラインチャット相談対応可）さんはTwitterを使っています: "あなたや私や日本の中にある北朝鮮、みたいな話でもあるのだろう。"

motoken_tw/status/689244841016885248のツイート　→　弁護士　星　正秀@tokyoさんはTwitterを使っています: "古舘さんも体制側ですね。＜改行＞ 「報ステ」裏番組スマスマ報じる！古舘「事務所あってのタレントですから」 https://t.co/MZ7JRO2vrl #スマートニュース"

motoken_tw/status/689245873595744256のツイート　→　モトケンさんはTwitterを使っています: "古舘の本質が表れてる。問題の本質を見ないで表層的なコメントに終始する。＞「報ステ」裏番組スマスマ報じる！古舘「事務所あってのタレントですから」 : スポーツ報知 https://t.co/670U7NxRs3"

motoken_tw/status/689246182858571776のツイート　→　nobu akiyamaさんはTwitterを使っています: "昨日のSMAPの生コメントよりも星の撮影を選んだ僕ですが、今朝ワイドショーで見ました。テレビのコメントは大団円を強調しますが、すればするほど彼らの表情が雄弁に何かを語っているように見えてしまいますね。それにしても、経営陣の内紛をなぜ社員が謝罪するんでしょう？（続）"

yjochi/status/689246332993683456のツイート　→　落合洋司（オンラインチャット相談対応可）さんはTwitterを使っています: "自爆、炎上みたいなものか。 https://t.co/iUcDqOK0bL"

yjochi/status/689247795224559616のツイート　→　大森望さんはTwitterを使っています: "しかしスマスマ生放送パートでいちばん驚いたのは西山喜久恵アナの原稿を持つ手が震えていたこと（おまけに噛んだ）。あんなベテランの局アナがそこまで緊張するとは。おそろしい世界ですね。"

yjochi/status/689251166459281408のツイート　→　朝比さんはTwitterを使っています: "フジ　めざましテレビがSMAP生会見の感想を放送するも縦読みに気付かず放送「はやく逃げて」 - NAVER まとめ https://t.co/zw7D4uHwBH"

yjochi/status/689258887095037952のツイート　→　落合洋司（オンラインチャット相談対応可）さんはTwitterを使っています: "SMAPファンは、今後、SMAPの抜け殻を見ながら楽しいんかな。"

**** 「借金踏み倒した航空会社と過去を踏み倒せない人々。」という落合洋司弁護士（東京弁護士会）のツイートと、これから始める「さらば弁護士鉄道＼泥棒神社の物語」

2016-01-20　水曜日　10：49　＞＞ ［［　←これからの記述範囲の開始時刻］］＞＞

＞＞＞　モトケンこと矢部善朗弁護士（京都弁護士会）と落合洋司弁護士（東京弁護士会）の主としてSMAP解散騒動謝罪に関するツイート・リツイートを読んでバス会社の問題ともに感じたこと。 http://hirono-hideki.cocolog-nifty.com/blog/2016/01/smap-ccaa.html


　そろそろ本書において被告訴人らの関与の事実関係についての記述に取り掛かろうと思っていたところ、目に入ったのが文言をタイトルに含めた落合洋司弁護士（東京弁護士会）のツイートです。

％yjochi（落合洋司（オンラインチャット相談対応可））のツイート％投稿日時％2016-01-20 09:23:00％ツイートのURL％ https://twitter.com/yjochi/status/689604111331815424 ％
％yjochi（落合洋司（オンラインチャット相談対応可））のツイートの内容％
借金踏み倒した航空会社と過去を踏み倒せない人々。→Reading:日航機事故で長男など亡くした父の半生 次男が出版　NHKニュース  https://t.co/n3tQ57eKl1
％データベースへの登録日時％2016-01-20 10:14:26％

　上記はコマンドの実行で自動登録したtw_user_timelineというテーブルのデータになりますが、私がツイートを目にした直後に個別手動のコマンド実行で登録したテーブルtw_user_tweetのデータは次になります。

％yjochi（落合洋司（オンラインチャット相談対応可））のツイート％投稿日時％2016-01-20 09:23:00％ツイートのURL％ https://twitter.com/yjochi/status/689604111331815424 ％
％yjochi（落合洋司（オンラインチャット相談対応可））のツイートの内容％
借金踏み倒した航空会社と過去を踏み倒せない人々。→Reading:日航機事故で長男など亡くした父の半生 次男が出版　NHKニュース  https://t.co/n3tQ57eKl1
％データベースへの登録日時％2016-01-20 10:14:26％

　些細なことかもしれませんが、今回はちょっとこだわって記録しておきたいと思いました。また、リンクのニュース記事を読んだ後のtw_user_tweetへの投稿であったのかは、はっきり思い出せないですが、投稿の方が先立ったと思います。

　日航というのは日本航空のことだと思いますが、落合洋司弁護士（東京弁護士会）が批判的に酷評しているのは、ずい分前からちょくちょくと目にしていました。気になったのは「過去を踏み倒せない」という部分です。

　気になったツイートをデータベースに登録しても、リンクの記事を開かなかったり、後回しにすることもちょいちょいあるのですが、今回は記事の内容も気になったので、すぐに開いて読んだように思います。

　本文に引用するような内容でもないのですが、参考資料としてまとめブログの記事として投稿しました。次の記事です。

参考資料：　「日航」または「日本航空」をキーワードに含む「落合洋司弁護士（東京弁護士会）（@yjochi）」のツイート・リツイート「78」件　（2016年01月20日のデータ記録） http://hirono-hideki.cocolog-nifty.com/blog/2016/01/yjochi782016012.html

　このブログ記事のAPIからの投稿は問題なかったので一安心できたのですが、今朝その前の投稿では、HTMLのコードがただの文字として表示されていたので、ブログサービスの仕様が変わったのかと、少々あせりました。

　HTMLが反映されないので、ブラウザの編集画面でコピペのやり直しなどやったのですが、これまでで最も有用な情報のまとめとすら思っていたので、うまく表示されなかったときは衝撃でした。今朝のまとめですが、次のブログ記事になります。

本文引用：関西大学法学部永田憲史教授と鹿児島大学准教授坂本正幸弁護士のバス事故報道と道徳教育の法的責任に関するツイート・リツイートのまとめ（2アカウント、25件、2016-01-20 08:44） http://hirono-hideki.cocolog-nifty.com/blog/2016/01/2252016-01-20-1.html

　「@penology_nagata（関西大学法学部　永田憲史）」と「@sakamotomasayuk（坂本正幸）」という2つのアカウントのツイートとリツイートをまとめた記事です。あえて＠をつけていますが、坂本正幸弁護士にはかなり前から3つともブロックされています。

　「長野・軽井沢のスキーバス15人死亡事故」の報道に対する批判的なもののみをまとめるつもりでいたのですが、たまたま目についたツイートがきっかけで、ひと括りに「組体操の事故」の問題のツイートを含めたという経緯がありました。

　「組体操の事故」の問題は一時期、モトケンこと矢部善朗弁護士（京都弁護士会）のツイートでもちょくちょく見かける時期がありましたが、さほど関心のある問題ではありませんでした。しかし、先日のバス事故の報道で運転手の技量が問われたことで問題に対する意識が変わりました。

　永田憲史関西大学法学部教授のツイートかリツイートを見ていると、組体操は道徳教育というものがあって、これも意外に思いましたが、バス会社の運転手の教育にも通じるところがあり、組体操の問題についても関心がにわかに高まった折でした。

　大事な参考資料のブログの記事がきちんと表示されるようになったので、いよいよ引用資料をテーマに新規記事の作成に取り掛かろうと思ったところ、その前にTwitterのタイムラインをチェックしておこうと思ったところ、初めの方に目に入ったのが未読で読み込んだ落合弁護士のツイートでした。

　「借金踏み倒した航空会社と過去を踏み倒せない人々。→Reading:日航機事故で長男など亡くした父の半生 次男が出版　NHKニュース」というのが、記事のURLリンク以外のツイートの内容です。

　「借金踏み倒した航空会社と過去を踏み倒せない人々。」という部分が落合洋司弁護士（東京弁護士会）のコメントらしく、前半の航空会社までの部分は理解と察しが出来ましたが、後半の「過去を踏み倒せない人々。」という部分は意味不明でした。

　ネット記事のどこをどう読んだら、そのような感想が頭から出てくるのか気になり、リンクを開いて興味深く記事を読みました。すると先ほどの教育問題にも通じる部分があり、何かの縁か導きのようなものを感じましたが、割とよくあることかと思っています。

　いずれリンク切れになりそうな記事ですが、そうなると影も形もなるなるので、一部を引用してご紹介しておきたいと思います。落合洋司弁護士（東京弁護士会）の法律家として弁護士として、ネットで肩書を前面に打ち出す元検事の論理思考という意味でも参考にして頂きたいです。

／********************（引用開始）********************
引用URL＞＞＞＞：http://www3.nhk.or.jp/news/html/20160120/k10010378631000.html 日航機事故で長男など亡くした父の半生 次男が出版　NHKニュース

事故から３０年がたち、父の半生を記録に残したいと、次男の橋本毅さん（６１）が出版を決めました。
栗原さんは大正１２年生まれで、戦後はシベリア抑留ののち、ふるさとの栃木県に戻り、教師として体育を教えました。手記には「狭い校庭ながら子どもたちの心にふれることができた」など、希望に満ちた記述が目立ちます。
しかし、定年後の６２歳のとき、事故で長男らを失ってからは、墜落現場の御巣鷹の尾根を繰り返し訪れ、「逃げるすべもなく死んでいった子どもたちに対して『安らかに眠れ』とはどうしても言えなかった」「心の中で『帰ってこい、帰ってこい』と叫びながら山を下りた」などとつづっています。

********************（引用終了）********************／

　本件告訴事件と密接不可分の関係である私の平成4年の傷害・準強姦被告事件発生当時も、被害者AAさんの父親AKさんは定年退職をした直後で、これからのんびり出来ると思った矢先と思っていた、というような話を金沢西警察署の取り調べで谷内孝志警部補から聞いていたことと重なります。

2016-01-20　水曜日　15：08　＜＜ ［［　←これまでの記述範囲の終了時刻］］＜＜

*** ネット上でモトケンこと矢部善朗弁護士（京都弁護士会）に受けた影響と名誉毀損での珠洲警察署への刑事告訴について
**** 「弁護人が苦労してそうだな。＞元県議の野々村被告、起訴内容を否認　強制出廷で初公判」というモトケンこと矢部善朗弁護士（京都弁護士会）ツイートから検証する被告訴人ら弁護士、裁判官の罪責
**** 「モトケン氏、放送法の濫用に危惧する」というTogetterのまとめ記事を巡るモトケンこと矢部善朗弁護士（京都弁護士会）のツイートについて考えたこと

2016-02-14　日曜日　10：27　＞＞ ［［　←これからの記述範囲の開始時刻］］＞＞

　昨夜になりますが、関連した一連のモトケンこと矢部善朗弁護士（京都弁護士会）のツイートを遡って資料としてまとめました。資料としてのツイートのまとめは、ココログのブログに記事として投稿していますので、そちらのURLとしてご紹介します。

参考資料：　「モトケン氏、放送法の濫用に危惧する」の関連ツイート／（@motoken_tw）（257件、 2016-02-08 22:14〜2016-02-13 17:17：2016-02-13の記録）「1-100／257」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/02/motoken_tw257-2.html
参考資料：　「モトケン氏、放送法の濫用に危惧する」の関連ツイート／（@motoken_tw）（257件、 2016-02-08 22:14〜2016-02-13 17:17：2016-02-13の記録）「101-200／257」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/02/motoken_tw257-1.html
参考資料：　「モトケン氏、放送法の濫用に危惧する」の関連ツイート／（@motoken_tw）（257件、 2016-02-08 22:14〜2016-02-13 17:17：2016-02-13の記録）「201-257／257」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/02/motoken_tw257-3.html

　「2016-02-08 22:14〜2016-02-13 17:17」となっている日付はどちらもツイートの投稿日時です。プログラムの処理で、最初と最後のツイートから投稿日時の抜き出し、その値を使っています。

％motoken_tw（モトケン）のツイート％投稿日時％2016-02-08 22:14:00％ツイートのURL％ https://twitter.com/motoken_tw/status/696683605964161024 ％
％motoken_tw（モトケン）のツイートの内容％
要するに、自民党に不利益な放送を繰り返すと電波を止めるぞということ。野党がだらしないから、こういう傲慢で無神経なことを平気で言うようになる。＞高市早苗総務相 放送局の電波停止命じる可能性に言及 #ldnews https://t.co/W4dUjfOTBA
％データベースへの登録日時％2016-02-09 15:59:49％

％motoken_tw（モトケン）のツイート％投稿日時％2016-02-13 17:17:00％ツイートのURL％ https://twitter.com/motoken_tw/status/698420724218789888 ％
％motoken_tw（モトケン）のツイートの内容％
放送法４条に基づく停波を認めるべきではない、という意見と、およそ放送局に対する停波処分は認めるべきではない、という意見は、全く別物である、ということを理解している人がどれだけいるか、とて..「モ
トケン氏、放送法の濫用に危惧する」 https://t.co/DokW8EahNX
％データベースへの登録日時％2016-02-13 17:25:44％

　上記が、スタートとエンドのツイートになります。まとめを作るために、モトケンこと矢部善朗弁護士（京都弁護士会）のタイムラインを遡り、始まりと思われるものを独自に判断しました。ツイートの数が多いので、見落としがある可能性もあります。

　資料にも記述を自動入力するようにしておりますが、データは次のような操作でデータベースから取得したものです。

（データベースへの問い合わせSQL）
SELECT * FROM tw_user_tweet WHERE tw_date BETWEEN '2016/02/08 22:14' AND '2016-02-14 16:08' AND (user LIKE "motoken_tw") ORDER BY tw_date ASC;

　データベースの操作言語である実行したSQL文の内容をそのまま記載しています。これは自分自身の確認としても大事な情報と考えています。

　ORDER BYはデータの並び順の指定でtw_dateというカラムの値を基準にしASCで照準にしています。これがDESCだと降順になります。データ型はdetatimeなので昇順だと値の小さい古い投稿日時から並ぶことになります。

　SQL文を使ったコマンドは昨日の時点で実行したと思います。2016-02-14 16:08というのは終了範囲の指定ですが、現在も14日の11時を過ぎたところなので、まだ迎えていない日時の指定をしていることになります。

　実際の処理では、時間の範囲の指定で最後に取得したデータの値を取得しそれを使っているので、手動での登録操作が伴いますが、最終的なツイートの日時を取得することになり、次回の処理では、それをスタートの指定として使うことが多いです。

　すべてではないですが、データベースから取得したデータは100件という単位でまとめるようにしています。ブログでの記事の読み込みの負担を軽減するという目的もありますが、数が多くなり過ぎるとTwitterのJavaScriptの適用がされないという不具合を確認しています。

　コマンドは次のように実行しています。自作のプログラムです。これまでに何度も修正や機能の追加を行っています。

bin/tw_user_tweet-sql-search-make-text-html.rb --full_sql="SELECT * FROM tw_user_tweet WHERE tw_date BETWEEN '2016-02-13 17:17' AND '2016-03-01' AND (user LIKE \"motoken_tw\") ORDER BY tw_date ASC"

　コマンドは相対パスとして実行しています。SQL文をそのまま実行させて書式を適用させた結果を得ています。条件は特定のユーザを指定し、投稿日時の範囲を指定しているだけです。

　テーブルを「tw_user_tweet」に指定しているので、基本的には目視で確認しながら手動でデータベースに登録したツイートになりますが、数が多いと、半自動化でまとめて登録することもあります。深澤諭史弁護士のツイートがほとんどですが。

　モトケンこと矢部善朗弁護士（京都弁護士会）と小倉秀夫弁護士のツイートは、内容を確認しながら手動で登録するようにしています。前後の関連性として不要と思えるツイートも、モトケンこと矢部善朗弁護士（京都弁護士会）の場合は登録するようにしています。

　時刻は2月15日5時51分になっています。記述範囲の開始時刻の記入を忘れていたので、告発-金沢地方検察庁御中_ツイッター（@kk_hirono）のツイートで投稿時刻を確認し、それに近い時間に編集しておきました。

　3時過ぎに目が覚めていました。目が覚めていると、次々と考え事が頭に浮かび、眠れないので少しでも記述を先に進めたいと思います。書きたいことは山ほどあるのですが、繰り返し何度も考えてきたことですが、未だに整理がつかない状態ではあります。

　先程も、落合洋司弁護士（東京弁護士会）の心をかき乱されるようなツイートを目にしたところです。ここで落合洋司弁護士（東京弁護士会）について記述を切り替えるわけにもいかないのですが、ツイートだけご紹介しておきたいと思います。

％yjochi（落合洋司（オンラインチャット相談対応可））のツイート％投稿日時％2016-02-15 00:12:00％ツイートのURL％ https://twitter.com/yjochi/status/698887566427172864 ％
％yjochi（落合洋司（オンラインチャット相談対応可））のツイートの内容％
政治方面に進む予定はないが、状況がどうなるかわからず、出ざるを得ない事態もまったくないとは言えないので、出ない、やらないということは、もう言わないことにした。笑
％データベースへの登録日時％2016-02-15 04:38:49％

2016-02-15　月曜日　07：14　＜＜ ［［　←これまでの記述範囲の終了時刻］］＜＜
**** モトケンこと矢部善朗弁護士（京都弁護士会）と落合洋司弁護士（東京弁護士会）に共通して感じる社会不安の煽りと萎縮的効果

2016-02-16　火曜日　18：41　＞＞ ［［　←これからの記述範囲の開始時刻］］＞＞

「モトケン氏、放送法の濫用に危惧する」というTogetterのまとめ記事を巡るモトケンこと矢部善朗弁護士（京都弁護士会）のツイートについて考えたこと http://hirono-hideki.cocolog-nifty.com/blog/2016/02/togetter-c8db.html

　記述の内容は上記ブログ記事の続きになります。

2016-02-22　月曜日　11：43　＜＜ ［［　←これまでの記述範囲の終了時刻］］＜＜

2016-02-22　月曜日　11：44　＞＞ ［［　←これからの記述範囲の開始時刻］］＞＞

　実質的には15日の未明からの中断になるかと思います。その15日ですが、急なことで日帰りで金沢市に行ってきました。平成21年の1月以来、7年ぶりの金沢でした。

　今ちょうどテレビで、高市総務大臣の停波発言に対する世論調査で、56％が問題がある、という調査結果を取り上げていました。今後の方針の検討と様子見を兼ねた中断でしたが、その問題に対するモトケンこと矢部善朗弁護士（京都弁護士会）のツイートを記録としてまとめていました。

参考資料：　「モトケン氏、放送法の濫用に危惧する」の関連ツイート／（@motoken_tw）（257件、 2016-02-08 22:14〜2016-02-13 17:17：2016-02-13の記録）「1-100／257」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/02/motoken_tw257-2.html
参考資料：　「モトケン氏、放送法の濫用に危惧する」の関連ツイート／（@motoken_tw）（257件、 2016-02-08 22:14〜2016-02-13 17:17：2016-02-13の記録）「101-200／257」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/02/motoken_tw257-1.html
参考資料：　「モトケン氏、放送法の濫用に危惧する」の関連ツイート／（@motoken_tw）（257件、 2016-02-08 22:14〜2016-02-13 17:17：2016-02-13の記録）「201-257／257」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/02/motoken_tw257-3.html
参考資料：　「モトケン氏、放送法の濫用に危惧する」の関連ツイート／（@motoken_tw）（22件、 2016-02-13 17:17〜2016-02-13 23:58：2016-02-14の記録）「22」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/02/motoken_tw22-20.html
参考資料：　「モトケン氏、放送法の濫用に危惧する」の関連ツイート／（@motoken_tw）（16件、 2016-02-13 23:58〜2016-02-14 10:32：2016-02-14の記録）「16」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/02/motoken_tw16--1.html
参考資料：　「モトケン氏、放送法の濫用に危惧する」の関連ツイート／（@motoken_tw）（56件、 2016-02-14 10:32〜2016-02-14 16:51：2016-02-14の記録）「56」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/02/motoken_tw56--1.html
参考資料：　「モトケン氏、放送法の濫用に危惧する」の関連ツイート／（@motoken_tw）（47件、 2016-02-14 16:51〜2016-02-16 17:53：2016-02-16の記録）「47」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/02/motoken_tw47-20.html
参考資料：　「モトケン氏、放送法の濫用に危惧する」の関連ツイート／（@motoken_tw）（55件、 2016-02-16 17:53〜2016-02-18 14:38：2016-02-18の記録）「55」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/02/motoken_tw55-20.html
参考資料：　「モトケン氏、放送法の濫用に危惧する」の関連ツイート／（@motoken_tw）（62件、 2016-02-18 14:38〜2016-02-19 00:51：2016-02-19の記録）「62」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/02/motoken_tw62-20.html
参考資料：　「モトケン氏、放送法の濫用に危惧する」の関連ツイート／（@motoken_tw）（26件、 2016-02-19 00:51〜2016-02-19 16:17：2016-02-20の記録）「26」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/02/motoken_tw26-20.html

　ブログの記事としては上記10件の記録となっています。2月の8日から始まり、19日まで関連ツイートが続いたことになりますが、まだまだ再燃する可能性もあるかと思います。

　記事のタイトルとなると文字数の制限もあるので、なにかと難しく不十分なものとならざるえないのですが、「モトケンこと矢部善朗弁護士（京都弁護士会）の放送法の濫用に関する議論」とでも、以降称して取り扱いをしたいと思います。

　これに続けて、モトケンこと矢部善朗弁護士（京都弁護士会）と小倉秀夫弁護士の間でレイシストという差別問題に関する議論の再燃がありました。これは、モトケンこと矢部善朗弁護士（京都弁護士会）のツイートと小倉秀夫弁護士のツイートを別にして記録しました。

参考資料：　小倉秀夫弁護士との「差別」や「理解」を巡る議論の関連ツイート（@motoken_tw）（37件、 2016-02-21 00:26〜2016-02-21 03:16：2016-02-21の記録） http://hirono-hideki.cocolog-nifty.com/blog/2016/02/motoken_tw37-20.html
参考資料：　モトケンこと矢部善朗弁護士（京都弁護士会）との「差別」や「理解」を巡る議論の関連ツイート（@Hideo_Ogura）（43件、 2016-02-21 01:05〜2016-02-21 09:13：2016-02-21の記録） http://hirono-hideki.cocolog-nifty.com/blog/2016/02/hideo_ogura43-2.html
参考資料：　モトケンこと矢部善朗弁護士（京都弁護士会）との「差別」や「理解」を巡る議論の関連ツイート（@Hideo_Ogura）（41件、 2016-02-21 09:13〜2016-02-21 16:01：2016-02-21の記録） http://hirono-hideki.cocolog-nifty.com/blog/2016/02/hideo_ogura41-2.html
参考資料：　小倉秀夫弁護士との「差別」や「理解」を巡る議論の関連ツイート（@motoken_tw）（32件、 2016-02-21 03:16〜2016-02-21 14:11：2016-02-21の記録）「32」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/02/motoken_tw32-20.html

　「「差別」や「理解」を巡る議論の関連ツイート」としておきましたが、また始まったかというモトケンこと矢部善朗弁護士（京都弁護士会）と小倉秀夫弁護士の間の議論と称する罵倒合戦のような応酬です。見え方も変わってきたので、いずれ言及として取り上げたいと記録にしました。

　小倉秀夫弁護士のことより先に取り上げておきたいのは落合洋司弁護士（東京弁護士会）のことです。

　「モトケンこと矢部善朗弁護士（京都弁護士会）と落合洋司弁護士（東京弁護士会）に共通して感じる社会不安の煽りと萎縮的効果」というタイトルを決めたのは16日のことになるようですが、この時に落合洋司弁護士（東京弁護士会）の気になるツイートをいくつか目にしていました。

2016-02-29　月曜日　14：00　＜＜ ［［　←これまでの記述範囲の終了時刻］］＜＜



2016-02-29　月曜日　14：00　＞＞ ［［　←これからの記述範囲の開始時刻］］＞＞

　予定外の中断をしていたので記述範囲の仕切り直しをしました。

T：kk_hirono（告発-金沢地方検察庁御中_ツイッター）：2016/02/22 12:13： https://twitter.com/kk_hirono/status/701605624505720832 ： 「モトケンこと矢部善朗弁護士（京都弁護士会）と落合洋司弁護士（東京弁護士会）に共通して感じる社会不安の煽りと萎縮的効果」というタイトルを決めたのは16日のことになるようですが、この時に落合洋司弁護士（東京弁護士会）の気になるツイートをいくつか目にしていました。

　確認すると上記のツイート以来の再開になりそうです。この内容だと2月16日に目にした落合洋司弁護士（東京弁護士会）のツイートに触発され、本項目のタイトルを決めたということになりそうです。やや記憶があいまいになっていますが、今月分としてツイートのまとめを作成しておきたいと思います。

参考資料：　落合洋司弁護士（東京弁護士会）（@yjochi）のツイート・リツイート（177件、 2016-02-01 17:54〜2016-02-28 12:22：2016-02-29の記録）「1-100／177」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/02/yjochi177-2016-.html
参考資料：　落合洋司弁護士（東京弁護士会）（@yjochi）のツイート・リツイート（177件、 2016-02-01 17:54〜2016-02-28 12:22：2016-02-29の記録）「101-177／177」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/02/yjochi177-201-1.html

　50件程度かとも思っていたのですが177件もあって驚きました。ブログの記事も上記の2つになっています。

　タイトル決定に結びついたツイートを次にいくつかピックアップしたいと思います。上記のブログの記事を見ながらの作業であり、そのページからのコピペでの掲載です。

［yjochi__20160229_1445_102／177のツイート］
％yjochi（落合洋司（オンラインチャット相談対応可））のツイート％投稿日時％2016-02-15 22:11:00％ツイートのURL％ https://twitter.com/yjochi/status/699219584981729280 ％
％yjochi（落合洋司（オンラインチャット相談対応可））のツイートの内容％
安倍ちゃんに憲法って、馬の耳に念仏って奴では。笑
％データベースへの登録日時％2016-02-16 08:48:02％

［yjochi__20160229_1445_105／177のツイート］
％yjochi（落合洋司（オンラインチャット相談対応可））のツイート％投稿日時％2016-02-16 10:30:00％ツイートのURL％ https://twitter.com/yjochi/status/699405388655931392 ％
％yjochi（落合洋司（オンラインチャット相談対応可））のツイートの内容％
ワイマール体制がナチスを生み、チープでプアな民主党政権が安倍政権を生んだ。歴史は繰り返す。 https://t.co/ECxIg2YGMq
％データベースへの登録日時％2016-02-16 17:43:55％

［yjochi__20160229_1445_106／177のツイート］
％yjochi（落合洋司（オンラインチャット相談対応可））のツイート％投稿日時％2016-02-16 11:59:00％ツイートのURL％ https://twitter.com/yjochi/status/699427834842861568 ％
％yjochi（落合洋司（オンラインチャット相談対応可））のツイートの内容％
萎縮しているかどうかではなく、萎縮する恐れがあるかどうかが問題、ということがわからんかな。 https://t.co/4twK1WVj9o
％データベースへの登録日時％2016-02-16 17:41:56％

［yjochi__20160229_1445_111／177のツイート］
％yjochi（落合洋司（オンラインチャット相談対応可））のツイート％投稿日時％2016-02-17 11:31:00％ツイートのURL％ https://twitter.com/yjochi/status/699783283194798080 ％
％yjochi（落合洋司（オンラインチャット相談対応可））のツイートの内容％
表現の自由で、萎縮してしまった人、組織は表に出てこなくなるわけで、闇の中に埋没する。萎縮していない人や組織の存在は萎縮的効果が生じていない根拠にはならない。問題は、その恐れがあるか。成蹊大学は、今後はそういうことも学生に教えるべきだな。将来、首相になる人がまた出るかもしれないし。
％データベースへの登録日時％2016-02-17 12:52:06％

［yjochi__20160229_1445_112／177のツイート］
％yjochi（落合洋司（オンラインチャット相談対応可））のツイート％投稿日時％2016-02-17 11:51:00％ツイートのURL％ https://twitter.com/yjochi/status/699788278774370305 ％
％yjochi（落合洋司（オンラインチャット相談対応可））のツイートの内容％
表現の自由が萎縮すれば民主政の過程への活発な議論がなされなくなり、民主政は次第に形骸化して、回復できなくなる。萎縮してからでは遅いからこそ、恐れが問題になる。表現の自由が損なわれれば民主主義は死滅する。そこに優越的地位が語られる意味がある。クイズじゃないんだよ、安倍ちゃん。
％データベースへの登録日時％2016-02-17 12:50:23％

［yjochi__20160229_1445_117／177のツイート］
％yjochi（落合洋司（オンラインチャット相談対応可））のツイート％投稿日時％2016-02-17 21:25:00％ツイートのURL％ https://twitter.com/yjochi/status/699932590107590657 ％
％yjochi（落合洋司（オンラインチャット相談対応可））のツイートの内容％
今週末は、積み上げて1メートル近くある、刑事事件の記録を読まねば。
％データベースへの登録日時％2016-02-18 10:13:19％

　2月17日のツイートをいくつかピックアップしましたが、16日の時点で印象的だったツイートは見当たりませんでした、16日以前に遡って、同じ作業をしたいと思います。

［yjochi__20160229_1445_91／177のツイート］
％yjochi（落合洋司（オンラインチャット相談対応可））のツイート％投稿日時％2016-02-15 00:12:00％ツイートのURL％ https://twitter.com/yjochi/status/698887566427172864 ％
％yjochi（落合洋司（オンラインチャット相談対応可））のツイートの内容％
政治方面に進む予定はないが、状況がどうなるかわからず、出ざるを得ない事態もまったくないとは言えないので、出ない、やらないということは、もう言わないことにした。笑
％データベースへの登録日時％2016-02-15 04:38:49％

［yjochi__20160229_1445_92／177のツイート］
％yjochi（落合洋司（オンラインチャット相談対応可））のツイート％投稿日時％2016-02-15 00:49:00％ツイートのURL％ https://twitter.com/yjochi/status/698896961856909312 ％
％yjochi（落合洋司（オンラインチャット相談対応可））のツイートの内容％
田中角栄が保釈された際、当時のNHK会長は目白御殿にお見舞いに馳せ参じた。表向きは公共放送でも、裏では政権や政権党とがっちりつながっているのは昔からだと思うよ。
％データベースへの登録日時％2016-02-15 04:38:30％

［yjochi__20160229_1445_93／177のツイート］
％yjochi（落合洋司（オンラインチャット相談対応可））のツイート％投稿日時％2016-02-15 00:56:00％ツイートのURL％ https://twitter.com/yjochi/status/698898665566408704 ％
％yjochi（落合洋司（オンラインチャット相談対応可））のツイートの内容％
ありもしない公共放送 の看板は外して、 日本中央通信とかに名前変えて、全部税金で運営して政府のプロパガンダ放送局になったほうが、すっきりするし受信料のトラブルもなくなる。小郷アナも国家公務員。
％データベースへの登録日時％2016-02-15 04:38:16％

［yjochi__20160229_1445_94／177のツイート］
％yjochi（落合洋司（オンラインチャット相談対応可））のツイート％投稿日時％2016-02-15 01:04:00％ツイートのURL％ https://twitter.com/yjochi/status/698900611429838848 ％
％yjochi（落合洋司（オンラインチャット相談対応可））のツイートの内容％
国民からちまちまと受信料をむしり取って、公共放送を装いながら実は国営放送という、そういう欺瞞に満ちた存在はないほうが良い。
％データベースへの登録日時％2016-02-15 04:38:00％

［yjochi__20160229_1445_95／177のツイート］
％yjochi（落合洋司（オンラインチャット相談対応可））のツイート％投稿日時％2016-02-15 01:08:00％ツイートのURL％ https://twitter.com/yjochi/status/698901608864681984 ％
％yjochi（落合洋司（オンラインチャット相談対応可））のツイートの内容％
名実ともに国営放送になっても、バラエティとか歌番組とか大河ドラマとか、大半の番組は影響受けず、時事関係とかニュースとかが名実ともに政府のプロパガンダ放送になって、それらは、朝鮮中央放送みたいに見られるだけだから、誰も困らないだろう。
％データベースへの登録日時％2016-02-15 04:37:35％

［yjochi__20160229_1445_98／177のツイート］
％yjochi（落合洋司（オンラインチャット相談対応可））のツイート％投稿日時％2016-02-15 17:37:00％ツイートのURL％ https://twitter.com/yjochi/status/699150629638254592 ％
％yjochi（落合洋司（オンラインチャット相談対応可））のツイートの内容％
1989年から検事、2000年から弁護士（東京弁護士会）です。弁護士になった後、6年7か月、ヤフー株式会社でも働いていました（ネットトラブル全般担当）。刑事事件全般（被害者支援含む）のほか、一般民事事件、インターネット紛争、コンプライアンス（法令遵守）等の案件を取り扱っています。
％データベースへの登録日時％2016-02-15 18:27:02％

　落合洋司弁護士（東京弁護士会）のNHK批判は、これまでも繰り返されてきたことの一つですが、今回の作業まで忘れていました。NHKを批判しながらも、NHKのニュース番組に出てときたまコメントをしているのも落合洋司弁護士（東京弁護士会）です。

　だんだんと思い出してきましたが、同じ頃のモトケンこと矢部善朗弁護士（京都弁護士会）のツイートなかでもマスコミ批判などと重なるところがあり、他のこともありましたが、それまでになく落合洋司弁護士（東京弁護士会）とモトケンこと矢部善朗弁護士（京都弁護士会）の共通性を感じた時期でした。

　ここ最近、落合洋司弁護士（東京弁護士会）のツイートで目を引くものは少なく、ここ数日はツイートの数自体が少なくなっているという印象ですが、郷原信郎弁護士に言及したツイートがあって、これは準備段階の集大成の一つとしてまたとない機会だと思いました。

　モトケンこと矢部善朗弁護士（京都弁護士会）の方は、想像を越えた活発化があって、本日はひさしぶりに沈静化をみせているところであります。小倉秀夫弁護士とのコラボでもありましたが、何かに取り憑かれているのでは考えてしまうほど尋常ならざるものが感じられました。

　ひとまずブログの記事としてまとめたものを次にご紹介しておきたいと思います。見ての通りずいぶんな数となっているので、どれをどの範囲どの程度、取り上げるべきか大いに迷うところであって、迷走しないためにもうかつには手を出せない状態です。

　すでに掲載済みのものもあるかと思いますが、「モトケン氏、放送法の濫用に危惧する」の関連ツイート、とひと括りにした記事です。

参考資料：　「モトケン氏、放送法の濫用に危惧する」の関連ツイート／（@motoken_tw）（257件、 2016-02-08 22:14〜2016-02-13 17:17：2016-02-13の記録）「1-100／257」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/02/motoken_tw257-2.html
参考資料：　「モトケン氏、放送法の濫用に危惧する」の関連ツイート／（@motoken_tw）（257件、 2016-02-08 22:14〜2016-02-13 17:17：2016-02-13の記録）「101-200／257」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/02/motoken_tw257-1.html
参考資料：　「モトケン氏、放送法の濫用に危惧する」の関連ツイート／（@motoken_tw）（257件、 2016-02-08 22:14〜2016-02-13 17:17：2016-02-13の記録）「201-257／257」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/02/motoken_tw257-3.html
参考資料：　「モトケン氏、放送法の濫用に危惧する」の関連ツイート／（@motoken_tw）（22件、 2016-02-13 17:17〜2016-02-13 23:58：2016-02-14の記録）「22」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/02/motoken_tw22-20.html
参考資料：　「モトケン氏、放送法の濫用に危惧する」の関連ツイート／（@motoken_tw）（16件、 2016-02-13 23:58〜2016-02-14 10:32：2016-02-14の記録）「16」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/02/motoken_tw16--1.html
参考資料：　「モトケン氏、放送法の濫用に危惧する」の関連ツイート／（@motoken_tw）（56件、 2016-02-14 10:32〜2016-02-14 16:51：2016-02-14の記録）「56」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/02/motoken_tw56--1.html
参考資料：　「モトケン氏、放送法の濫用に危惧する」の関連ツイート／（@motoken_tw）（47件、 2016-02-14 16:51〜2016-02-16 17:53：2016-02-16の記録）「47」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/02/motoken_tw47-20.html
参考資料：　「モトケン氏、放送法の濫用に危惧する」の関連ツイート／（@motoken_tw）（55件、 2016-02-16 17:53〜2016-02-18 14:38：2016-02-18の記録）「55」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/02/motoken_tw55-20.html
参考資料：　「モトケン氏、放送法の濫用に危惧する」の関連ツイート／（@motoken_tw）（62件、 2016-02-18 14:38〜2016-02-19 00:51：2016-02-19の記録）「62」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/02/motoken_tw62-20.html
参考資料：　「モトケン氏、放送法の濫用に危惧する」の関連ツイート／（@motoken_tw）（26件、 2016-02-19 00:51〜2016-02-19 16:17：2016-02-20の記録）「26」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/02/motoken_tw26-20.html

　次が、「小倉秀夫弁護士との「差別」や「理解」を巡る議論の関連ツイート」という括りを入れたものです。

参考資料：　小倉秀夫弁護士との「差別」や「理解」を巡る議論の関連ツイート（@motoken_tw）（37件、 2016-02-21 00:26〜2016-02-21 03:16：2016-02-21の記録） http://hirono-hideki.cocolog-nifty.com/blog/2016/02/motoken_tw37-20.html
参考資料：　小倉秀夫弁護士との「差別」や「理解」を巡る議論の関連ツイート（@motoken_tw）（32件、 2016-02-21 03:16〜2016-02-21 14:11：2016-02-21の記録）「32」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/02/motoken_tw32-20.html
参考資料：　小倉秀夫弁護士との「差別」や「理解」を巡る議論の関連ツイート（@motoken_tw）（43件、 2016-02-21 14:11〜2016-02-23 10:35：2016-02-23の記録） http://hirono-hideki.cocolog-nifty.com/blog/2016/02/motoken_tw43--1.html
参考資料：　小倉秀夫弁護士との「差別」や「理解」を巡る議論の関連ツイート（@motoken_tw）（81件、 2016-02-23 10:35〜2016-02-23 19:41：2016-02-23の記録） http://hirono-hideki.cocolog-nifty.com/blog/2016/02/motoken_tw81-20.html
参考資料：　小倉秀夫弁護士との「差別」や「理解」を巡る議論の関連ツイート（@motoken_tw）（70件、 2016-02-23 19:41〜2016-02-24 01:16：2016-02-24の記録）「70」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/02/motoken_tw70-20.html
参考資料：　小倉秀夫弁護士との「差別」や「理解」を巡る議論の関連ツイート（@motoken_tw）（57件、 2016-02-24 01:16〜2016-02-24 11:36：2016-02-24の記録）「57」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/02/motoken_tw57-20.html
参考資料：　小倉秀夫弁護士との「差別」や「理解」を巡る議論の関連ツイート（@motoken_tw）（73件、 2016-02-24 11:36〜2016-02-25 22:40：2016-02-25の記録）「73」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/02/motoken_tw73-20.html
参考資料：　小倉秀夫弁護士との「差別」や「理解」を巡る議論の関連ツイート（@motoken_tw）（11件、 2016-02-25 22:40〜2016-02-27 08:29：2016-02-27の記録）「11」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/02/motoken_tw11-20.html

　内容的に「小倉秀夫弁護士との「差別」や「理解」を巡る議論の関連ツイート」の続きとなるものもあるのですが、終息と再燃を繰り返してきりがないので、テーマを除外したのが次のツイートのまとめです。

参考資料：　モトケンこと矢部善朗弁護士（京都弁護士会）（@motoken_tw）のツイート・リツイート（153件、 2016-02-27 08:29〜2016-02-28 21:58：2016-02-28の記録）「1-100／153」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/02/motoken_tw153-2.html
参考資料：　モトケンこと矢部善朗弁護士（京都弁護士会）（@motoken_tw）のツイート・リツイート（153件、 2016-02-27 08:29〜2016-02-28 21:58：2016-02-28の記録）「101-153／153」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/02/motoken_tw153-1.html

　小倉秀夫弁護士のツイートは別のものとしてまとめてあります。

参考資料：　「遠隔操作事件」をキーワードに含む「小倉秀夫弁護士（@Hideo_Ogura）」のツイート・リツイート（2012-12-05 17:33〜2015-12-15 10:15）「8」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/02/hideo_ogura2012.html
参考資料：　モトケンこと矢部善朗弁護士（京都弁護士会）との「差別」や「理解」を巡る議論の関連ツイート（@Hideo_Ogura）（43件、 2016-02-21 01:05〜2016-02-21 09:13：2016-02-21の記録） http://hirono-hideki.cocolog-nifty.com/blog/2016/02/hideo_ogura43-2.html
参考資料：　モトケンこと矢部善朗弁護士（京都弁護士会）との「差別」や「理解」を巡る議論の関連ツイート（@Hideo_Ogura）（41件、 2016-02-21 09:13〜2016-02-21 16:01：2016-02-21の記録） http://hirono-hideki.cocolog-nifty.com/blog/2016/02/hideo_ogura41-2.html
参考資料：　「黙秘」をキーワードに含む「小倉秀夫弁護士（@Hideo_Ogura）」のツイート・リツイート（2010-12-26 00:47〜2015-03-02 01:27）「11」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/02/hideo_ogura2-42.html
参考資料：　モトケンこと矢部善朗弁護士（京都弁護士会）との「差別」や「理解」を巡る議論の関連ツイート（@Hideo_Ogura）（95件、 2016-02-21 16:01〜2016-02-23 10:30：2016-02-23の記録） http://hirono-hideki.cocolog-nifty.com/blog/2016/02/hideo_ogura95-1.html
参考資料：　モトケンこと矢部善朗弁護士（京都弁護士会）との「差別」や「理解」を巡る議論の関連ツイート（@Hideo_Ogura）（43件、 2016-02-23 10:30〜2016-02-23 19:40：2016-02-23の記録） http://hirono-hideki.cocolog-nifty.com/blog/2016/02/43-2016-02-23-1.html
参考資料：　モトケンこと矢部善朗弁護士（京都弁護士会）との「差別」や「理解」を巡る議論の関連ツイート（@Hideo_Ogura）（51件、 2016-02-23 19:40〜2016-02-24 12:17：2016-02-24の記録） http://hirono-hideki.cocolog-nifty.com/blog/2016/02/hideo_ogura51-2.html
参考資料：　モトケンこと矢部善朗弁護士（京都弁護士会）との「差別」や「理解」を巡る議論の関連ツイート（@Hideo_Ogura）（64件、 2016-02-24 12:17〜2016-02-25 23:03：2016-02-25の記録） http://hirono-hideki.cocolog-nifty.com/blog/2016/02/hideo_ogura64-2.html
参考資料：　モトケンこと矢部善朗弁護士（京都弁護士会）との「差別」や「理解」を巡る議論の関連ツイート（@Hideo_Ogura）（9件、 2016-02-25 23:03〜2016-02-26 10:32：2016-02-27の記録） http://hirono-hideki.cocolog-nifty.com/blog/2016/02/hideo_ogura9-20.html
参考資料：　「優秀な人材」をキーワードに含む「小倉秀夫弁護士（@Hideo_Ogura）」のツイート・リツイート（2010-04-13 12:45〜2016-02-28 11:17）「61」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/02/hideo_ogura2-43.html
参考資料：　小倉秀夫弁護士（@Hideo_Ogura）のツイート・リツイート（86件、 2016-02-27 10:59〜2016-02-28 23:06：2016-02-28の記録）「86」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/02/hideo_ogura86-2.html

　同一期間内ということで、別のテーマとしてのまとめも一緒に掲載しました。

　モトケンこと矢部善朗弁護士（京都弁護士会）と小倉秀夫弁護士のツイートに関しては、個々のツイートを引き合いに出して言及するのも手に余り、また理解のための効果も期待しがたいので、ここはこれで記録を兼ねた参考資料として、別のアプローチから問題点の指摘などやっていく予定です。

　モトケンこと矢部善朗弁護士（京都弁護士会）と落合洋司弁護士（東京弁護士会）に共通して感じられるのは、このところ検察、警察に対する批判を見かけなくなったということですが、批判の態様というのは政治、マスコミに共通するものであり、具体的根拠の乏しさもしばしば感じてきました。

　モトケンこと矢部善朗弁護士（京都弁護士会）の特定個人に対する批判にも似たようなところがあって、つい最近になってみかけた香山リカという精神科医の女性に対する批判もたちの悪さを感じさせるもので、ジャーナリストの江川紹子さんに対しても過去に似たようなことがありました。

　モトケンこと矢部善朗弁護士（京都弁護士会）はここでも香山リカさんに対する批判の正当性として人権という価値を最大限に強調していました。半月ほど前の政府やマスコミに対する批判の時は、憲法を振りかざしていたように憶えています。人権と憲法の関係性についても独自の理論を披瀝していました。

　具体的な問題の経過について、長い中断もあり説明が不十分な点もあるかと思いますが、本項目はこのあたりで切り上げ、モトケンこと矢部善朗弁護士（京都弁護士会）と落合洋司弁護士（東京弁護士会）の憲法観をざっくりと整理し、俯瞰しておきたいと思います。

2016-02-29　月曜日　17：08　＜＜ ［［　←これまでの記述範囲の終了時刻］］＜＜
**** モトケンこと矢部善朗弁護士（京都弁護士会）と落合洋司弁護士（東京弁護士会）の憲法観、主にツイートでのこれまでの発言

＞＞＞モトケンこと矢部善朗弁護士（京都弁護士会）と落合洋司弁護士（東京弁護士会）に共通して感じる社会不安の煽りと萎縮的効果 http://hirono-hideki.cocolog-nifty.com/blog/2016/02/post-c5f3.html

2016-02-29　月曜日　17：10　＞＞ ［［　←これからの記述範囲の開始時刻］］＞＞

　まずはモトケンこと矢部善朗弁護士（京都弁護士会）について以前まとめたブログ記事です。

参考資料：　「憲法」をキーワードに含む「モトケンこと矢部善朗弁護士（京都弁護士会）（@motoken_tw）」のツイート・リツイート（2010-04-06 18:38〜2016-02-12 13:40）「1-100／296」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/02/motoken_tw20-12.html
参考資料：　「憲法」をキーワードに含む「モトケンこと矢部善朗弁護士（京都弁護士会）（@motoken_tw）」のツイート・リツイート（2010-04-06 18:38〜2016-02-12 13:40）「101-200／296」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/02/motoken_tw20-13.html
参考資料：　「憲法」をキーワードに含む「モトケンこと矢部善朗弁護士（京都弁護士会）（@motoken_tw）」のツイート・リツイート（2010-04-06 18:38〜2016-02-12 13:40）「201-296／296」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/02/motoken_tw20-14.html

　落合洋司弁護士（東京弁護士会）のツイートは憲法をキーワードにしたまとめがまだありませんでした。Twitterの検索から145件のツイートを取得したので、これをスクリプトでデータベースに登録しているところです。

　これまでに書いていますが、Twitterの検索は結果の精度に疑問があるので、既に登録済みのツイートを含め、145件を超える可能性があり、また、Twitterの検索では対象者のリツイートは取得できないので、既に登録済みのリツイートを含めて結果の数が変わってくる可能性があります。

参考資料：　「憲法」をキーワードに含む「落合洋司弁護士（東京弁護士会）（@yjochi）」のツイート・リツイート（2010-06-06 13:36〜2016-02-19 12:15）「1-100／157」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/02/yjochi2010-06-0.html
参考資料：　「憲法」をキーワードに含む「落合洋司弁護士（東京弁護士会）（@yjochi）」のツイート・リツイート（2010-06-06 13:36〜2016-02-19 12:15）「101-157／157」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/02/yjochi2010-06-1.html

　「憲法」をキーワードに含む「落合洋司弁護士（東京弁護士会）（@yjochi）」のツイート・リツイート、は157件でした。これは思ったより少ない数でした。モトケンこと矢部善朗弁護士（京都弁護士会）の方も追加のまとめを記録しておきたいと思います。

参考資料：　「憲法」をキーワードに含む「モトケンこと矢部善朗弁護士（京都弁護士会）（@motoken_tw）」のツイート・リツイート（2016-02-12 13:40〜2016-02-28 22:23）「33」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/02/motoken_tw2016-.html

　モトケンこと矢部善朗弁護士（京都弁護士会）の追加分は今月12日からで33件でした。今月と言っても今日が月末で、それも4年に一度という2月29日です。

　個々のツイートの内容についてはここでも踏み込まないことにしておきたいと思います。順序としていち早く取り上げ、言及をしておきたいのは「証拠の目的外使用」の問題であって、私はこれを非常上告の問題と絡めて憲法問題と位置づけています。

2016-02-29　月曜日　17：50　＜＜ ［［　←これまでの記述範囲の終了時刻］］＜＜
**** 非常上告と証拠の目的外使用について／2006年の落合洋司弁護士（東京弁護士会）のブログ記事の思い出

2016-02-29　月曜日　18：39　＞＞ ［［　←これからの記述範囲の開始時刻］］＞＞

　落合洋司弁護士（東京弁護士会）のブログ記事を探し出すのに少々手間取りました。これまでに何度か同じ経験をしていて、初めの頃は探しまわっても見つけることが出来なかったということもあったかと思います。

2016-03-03　木曜日　10：37　＜＜ ［［　←これまでの記述範囲の終了時刻］］＜＜



2016-03-03　木曜日　10：37　＞＞ ［［　←これからの記述範囲の開始時刻］］＞＞

　一行書いてから中断をしていたので記述範囲の仕切り直しをしました。今日は他に大事なことを書きたいと思っているので、この項目は手早く切り上げないと思います。

2006-11-05 - 弁護士 落合洋司　（東京弁護士会）　の 日々是好日 http://d.hatena.ne.jp/yjochi/20061105#1162656125

　上記がそれと思われる落合洋司弁護士（東京弁護士会）のブログの記事のタイトルとURLです。普通に取得されるページのタイトルは上記のものですが、本来は「■[話題][法曹養成]調書の講義使用は「不可」　検察庁と法科大学院が対立」です。

　他のブログサービスでは見かけることのないHatena::Diary独自の仕様ですが、設定で「ブログ形式」とかにしておけば、普通に記事のタイトルがページのタイトルとなるはずなのですが、本人が「日記形式」にしているため、こうなっているのだと思います。

　他にもHatena::Diaryには他のブログサービスとは異なる仕様やクセのようなものがあります。正確に言えばHatena::Diaryはブログではないとも言えそうです。後発になりますが「はてなブログ」というようなサービスもあります。

　私もHatena::Diaryを使っていて、2005年の12月から初めて2009年の9月ころまでは、情報発信のメインとして使っていました。それ以降、非公開のプライベートモードにしていたのですが、今年に入ってから公開モードに切り替えています。

　Hatena::DiaryはURLにも日付の情報が入るので、何時の記事かわかりやすく、日記という機能に特化している感じです。上記の落合洋司弁護士（東京弁護士会）の記事も2006年11月5日のものということがわかりやすく確認できています。

　細かい話は省きますが、この記事を探し出すのにこれまで何度も苦労をしたことがあり、労力とともに時間も無駄にしてきました。記憶自体が曖昧になっていますが、この記事以外に該当は見つかっていません。記憶にあるのは刑訴法の条文の羅列があったことと、それらしい内容です。

　2006年といえば平成18年かと思いますが、当時私は、この落合洋司弁護士（東京弁護士会）のブログと、モトケンこと矢部善朗弁護士（京都弁護士会）のブログをほぼ毎日のように閲覧していました。記事の投稿と閲覧に時間差はあっても一日程度であったと思います。

　その時、私は食事の支度や買い物に出掛けるために慌ただしくしていたように思います。その記事はざっと目を通しただけで終わったのですが、条文の羅列で刑訴法の改正があったらしいなど、その場のことは印象的に記憶しました。

T：s_hirono（非常上告-最高検察庁御中_ツイッター）：2016/03/03 11:14： https://twitter.com/s_hirono/status/705214837396099074 ： 2016-03-03-111449_■[話題][法曹養成]調書の講義使用は「不可」　検察庁と法科大学院が対立.jpg https://t.co/silLv69T8J

T：s_hirono（非常上告-最高検察庁御中_ツイッター）：2016/03/03 11:14： https://twitter.com/s_hirono/status/705214679191138304 ： 2016-03-03-111412_■[話題][法曹養成]調書の講義使用は「不可」　検察庁と法科大学院が対立.jpg https://t.co/hnOqOux27U

T：s_hirono（非常上告-最高検察庁御中_ツイッター）：2016/03/03 11:13： https://twitter.com/s_hirono/status/705214503764434944 ： 2016-03-03-111330_■[話題][法曹養成]調書の講義使用は「不可」　検察庁と法科大学院が対立.jpg https://t.co/FrLEeTfE2w

T：s_hirono（非常上告-最高検察庁御中_ツイッター）：2016/03/03 11:12： https://twitter.com/s_hirono/status/705214252273938432 ： 2016-03-03-111229_■[話題][法曹養成]調書の講義使用は「不可」　検察庁と法科大学院が対立.jpg https://t.co/aVZw0lmtWa

　記事の内容自体は特に重要ではないのですが、説明の必要と存在自体に意味もあるので、スクリーンショットを撮りました。上記がTwitterに画像付きツイートにしたものです。

　今初めて気がついたのですが、私自身のコメントを発見しました。確か、Hatena::Diaryでは個々の記事ではなく、特定の日付の記事全体に対するコメント欄、という仕様になっていたかと思います。次の日のページも確認しましたが、間違いなさそうです。

　私のコメント投稿もスクリーンショットを撮りました。

T：s_hirono（非常上告-最高検察庁御中_ツイッター）：2016/03/03 11:23： https://twitter.com/s_hirono/status/705217102987169792 ： 2016-03-03-112350_hirono_hideki　2006／11／05　01：54.jpg https://t.co/bJG60HcHFL

　夜中の1時54分という遅い時間になっています。「cal 11 2006」というコマンドで調べたのですが、2006年11月5日は日曜日でした。仕事が休みなので夜ふかしをしていたのだと思いますが、仕事のある平日でも2時、3時まで起きていることはよくありました。

　当時は慢性的に寝不足で0時前に寝ることはほとんどなかったと思います。2006年といえばリーマン・ショックによる大不況のだいぶん前なので、仕事は毎日3時間の残業で20時まで、鋳物工場で汚れがひどい仕事だったので工場で風呂に入ってから帰り、アパートに戻るのは21時に近い時間でした。

　鋳物というのは粒子の細かい砂を大量に使ってする仕事なので、仕事中はずっとガスマスクのような防じんマスクを着用していました。体力的にもきつい仕事でしたが、2006年の11月という時期であれば、仕事の方はすっかり慣れていたように思います。

スマトラ島沖地震 (2004年) - Wikipedia http://bit.ly/1SjHU8v

　上記のページで確認をしたのですが、インドネシアで大津波があったのは2004年でした。12月の終わり頃のことで、12月一杯で、羽咋郡志賀町のサンケンという工場での仕事が終わりになり、インドネシアの若者の研修生とも一緒に仕事をしていたので、この時期だけははっきりと特定できるのです。

　ついでにちょっとだけ書いておきますが、志賀町のサンケンでの派遣の仕事が終わりになることは、2,3日前になって突然知らされました。次の派遣先が見つかるまで自宅待機することになり、主に宇出津の実家に戻って、連絡を待つ生活になりました。

　次の派遣先が決まったのは翌年の2005年2月の中頃だったように思います。あるいは2月の下旬だったのかもしれませんが、とにかく長く感じる期間で生活に危機的不安を募らせる日々でした。派遣の仕事がない間、給料はもらえないばかりか、保険料が天引きされて明細は5万円以上のマイナスでした。

　派遣会社からの連絡を待っていてもだめだと考え始めていた頃に、ようやく連絡があり、次の派遣先に決まったのが羽咋市内の鋳物工場でした。平成14年の11月の下旬から住んでいた派遣会社のアパートから近い場所で、車を使えずに歩いて通勤したこともあるぐらいです。

　羽咋市のアパートには平成21年（2009年）の3月15日まで住んでいました。この3月15日というのは自分の軽四の車検が切れる日に合わせたもので、残りの就業軌間は有給休暇扱いにしてもらえました。

　これもついでにちょっとだけ触れておきますが、羽咋市には5年3ヶ月ほど住んでいたものの、期間内の時期というのは記憶で特定しづらいものが多く、その一つが被告訴人OKNから電話があった年のことです、7月か8月の20日頃ということはよく憶えているのですが、年が特定出来ません。

　そういうことも含めて、Hatena::Diaryの記事を読み返せば、思い出すことや特定できることも多いはずですが、公開設定にしてからも目を通した記事は一つだけです。そのたまたま選択することになった記事が、特別な内容と発見で取り上げることを予定していましたが、それも手付かずです。

　あれもこれもと取り上げるのは現実的でないので、割愛と言いますか切り捨てることが多くなるとも思います。広く薄く関連性を書くという方法もありますが、そこで悩ましいのがタイトルというか見出しとの関連性です。

　今、この項目で取り上げているメインのテーマは「証拠の目的外使用」です。これはとてもわかり易い言葉ですが、上記の落合洋司弁護士（東京弁護士会）のブログ記事には、そのまま当てはまる文字列がなく、Hatena::Diaryの検索機能で見つけ出すことも出来ませんでした。

　とにかく、2006年11月5日の落合洋司弁護士（東京弁護士会）のブログ記事で、「証拠の目的外使用」のことを初めて知った可能性が高いのですが、夜中の2時ころという時間帯で眠くなっていたのか、後になると考えられないぐらい、自分のことでの重要性を理解できていませんでした。

　非常上告というのは福井刑務所にいた平成7,8年ころから繰り返し勉強をして知っていた知識の一つでしたが、自分の事件と結びつけて考えることはなかったと思います。

　今書いていて数カ月ぶり、たぶん今年になって初めて思い出したことですが、昨年の7月1日ころに見つけた再審と非常上告に関する文献のような資料を読みかけのまま先送りにしていました。宇出津のあばれ祭りの前日か前々日のことです。

　「証拠の目的外使用」という言葉を頻繁に目にするようになったのは、クローズアップ現代というNHKの番組の問題がでた頃のことです。私自身、Twitterでこの「証拠の目的外使用」という言葉を引用なり使った最初というのをTwilogで調べてみたいと思います。

T：s_hirono（非常上告-最高検察庁御中_ツイッター）：2016/03/03 12:41： https://twitter.com/s_hirono/status/705236685127192576 ： 2016-03-03-124138_廣野秀樹＼さらば弁護士鉄道・泥棒神社の夜（@hirono_hideki）／「証拠の目的外使用」の検索結果　-　Twilog.jpg https://t.co/RyTNG38k59

　調べ方や作業のご紹介もかねて上記のスクリーンショットにしました。最初に該当したのが2013年05月28日のツイートでした。その内容にも意外性を感じ、すっかり忘れていたことに気がついたのですが、日弁連が証拠の目的外使用の廃止を求めた声明をだしていたという事実です。

廣野秀樹＼さらば弁護士鉄道・泥棒神社の夜さんはTwitterを使っています: "刑訴法改正法案から証拠の目的外使用条項の削除を求める会長声明／日本弁護士連合会 at 告発-金沢地方検察庁御中_2013-WordPress http://t.co/TMKKBb3Ea3 ぜんぜん知らなかったので驚いたです。全面実名で公開していた時期にも重なりそうですが・・・・。" https://twitter.com/hirono_hideki/status/339145035482271744

　上記が最初のツイートのURLですが、ツイートのページのタイトルは、上記のように投稿アカウント名とツイートの本文という組み合わせになっています。当然ですが、このページタイトルだけだと投稿日時の情報はわかりようもありません。実際にリンクを開いて閲覧するしか術はないです。

　久しぶりに「証拠の目的外使用」のことで調べたのですが、すっかり忘れていたことや新たな発見がありました。とにかくもっとも問題の提起に活発だったのがジャーナリストの江川紹子さんだったという印象が記憶に残っている問題です。

　「証拠の目的外使用」についてツイートの情報をまとめておこうと、追加の作業をしていたのですが、その過程で意外な発見がありました。次の記事になります。

なぜ栃木女児殺害事件の裁判で「Nシステム」を証拠として使うことが異例中の異例の事態なのか(前田恒彦) - 個人 - Yahoo!ニュース http://bylines.news.yahoo.co.jp/maedatsunehiko/20160302-00054952/

　時刻は22時55分です。夕方前からになると思いますが中断していました。ひな祭り、ということでチラシ寿司でも食べたくなって寒い中、買い物に出掛けたのですが、宇出津新港のどんたく宇出津店では早い時間から全部売り切れの様子でした。

　宇出津新港の町に戻ってから、角田ストアとAコープ能都店にも立ち寄ったのですが、チラシ寿司はありませんでした。

　家に戻ってから、おでんを作りました。数日前に安売りで買ったおでんの袋が今日の賞味期限で、5個の生卵の今日が消費期限になっていました。大根を切ったり茹でたりしたので、それでも時間がかかりました。

　炊飯器のスイッチを入れてから銭湯に行きました。入っている間ずっと貸切状態だったのは久しぶりでした。細かい時間は見ていなかったですが、家に戻ったのは21時半を過ぎていたように思います。

　買い物に出掛ける前になると思いますが、非常上告をキーワードにTwitterの検索をやったところ、初めて見る意外なツイートを発見しました。他にも気になる報道など、情報の整理を兼ねて書いておきたいことが色々あるのですが、本来、本日予定していたことは、まだ手付かずです。

　「証拠の目的外使用」について、言及したいこと取り上げたいことがまだまだ沢山あるのですが、それは別の機会にしたいと思います。予定していた次の作業に移ります。

2016-03-03　木曜日　23：09　＜＜ ［［　←これまでの記述範囲の終了時刻］］＜＜
** 被害者AAさんとの関係
*** 被告訴人弁護士らの関与
**** 健やかな成長と幸せを願う、というひな祭りに思いを馳せる被害者AAさんとその家族の生活と人生と被告訴人弁護士らの犯罪性

2016-03-03　木曜日　23：20　＞＞ ［［　←これからの記述範囲の開始時刻］］＞＞

　本日3月3日のひな祭りも残すところ40分足らずになりました。かなり予定が狂って土壇場の本日もスタートが遅れましたが、なんとか出港の運びとなった心持ちです。銀河鉄道のような時を超えた宇宙空間への旅立ちのようなものもイメージしています。それが「さらば弁護士鉄道」です。

　数日前の2月26日、テレビから世に言う226事件から80年目だという声が聴こえていました。226事件といえば昭和11年、それは平成4年の事件を起こしたことで知った被害者AAさんの父親AKさんの生まれた年です。誕生日は12月25日だったように思います、その日を迎えると80歳です。

　男性の平均寿命はすでに越えられているのではないかと思います。私は生存すらわかりません。最近になって特にテレビで見かけるようになった高齢者の認知症の問題もあります。

　私が平成11年の事件を起こした時、起訴状か何かの書面には64歳という記載があったように思います。平成4年の事件で情状証人になった私の母親の年齢も書面の記載は同じ64歳だったような気がします。月日の流れというものをあらためて感じました。

　なお、本項目は、次のブログ記事の内容の続きになります。

非常上告と証拠の目的外使用について／2006年の落合洋司弁護士（東京弁護士会）のブログ記事の思い出: 金沢地方検察庁御中 http://hirono-hideki.cocolog-nifty.com/blog/2016/03/2006-e88b.html

　この項目から告訴事件の事実関係についても記載を始めたいと思います。振り返ると、私自身の認識も長い時間を掛けて大きな変遷を辿ってきました。とりわけて弁護士という職業、社会的立場に対する認識の変化が大きく、それは弁護士らが批判を常套手段とする警察検察と連動してきました。

2016-03-04　金曜日　00：00　＜＜ ［［　←これまでの記述範囲の終了時刻］］＜＜



2016-03-04　金曜日　14：19　＞＞ ［［　←これからの記述範囲の開始時刻］］＞＞

　この項目では被害者AAさんとその家族の立場を優先して事実や経緯の概要を描くつもりだったのですが、色々とありすぎて、いとぐちがなかなか見つけられないような状態です。

　私と被害者AAさんの関係についてはこれまでにも事実関係の記載をしてきましたが、そのほとんどは本書つまりこの告訴状には取り込まず、DVDに添付するデジタルデータとして参考資料とする扱いにしました。情報量が膨大になりすぎるというのが一番の理由です。

　デジタルデータであり、そのほとんどはインターネット上で公開されている情報です。必要に応じて検索などで調べて頂ければと思いますし、さらに必要があれば直接、私に聴取するなどの手続きを進めてください。

　今、テレビを見ながらパソコンで記述をしていますが、ミヤネ屋という番組で「異例裁判　三鷹ストーカー殺人事件　弁護側”リベンジポルノ”違法主張」というのをやっています。被害者家族との関係性についても説明のナレーションがありました。

　今日は天気も良いので午前中に母親のいる病院に行ってきました。家に戻ったのは12時40分ぐらいなっていたと思います。出かける前に録画予約していたワイドスクランブルとひるおび！という番組を、主に早送りで視聴し、消去をしました。

　この三鷹ストーカーの裁判のことは録画していた他の番組でも、少し取り上げられていいたように思いますが、今やっているミヤネ屋ではずいぶんと重点的に時間を割いて取り上げているようです。

　この三鷹ストーカー事件のやり直し裁判のことは、あるいは昨日にもテレビで少し見て知っていたのですが、さほど注目することも強い関心を持つこともありませんでした。今強い関心があり、そのために情報番組を録画していたのも栃木女児殺害事件の裁判が目的でした。

　今、三鷹ストーカー事件の報道をみながら感じたことは、栃木女児殺害の裁判と共通したもので、とても手厚い刑事弁護を受けているということです。被害者家族の立場や心情が後退させられているような印象も受けます。

　ミヤネ屋の三鷹ストーカー事件の報道は14時47分ころに終わったようです。テレビに余り集中していなかったので理解も不十分ですが、弁護側は懲役15年が妥当という主張をしているようです。

　三鷹ストーカー事件と呼ばれる事件のことは事件発生当時から集中的な報道があったので記憶に残っていますが、ずいぶんと執拗な犯行という報道の印象が残っています。たしか被害者の自宅に忍び込み、待ち伏せをしたうえでの犯行で、他に例を見ないぐらい強固な殺意を感じる事件でした。

　ミヤネ屋のコメンテータには行列のできる法律相談所の元検事の女性弁護士が出て解説をしていました。住田弁護士という名前であったように思いますが、確認はしていません。

　住田弁護士に関して私がもっとも強い関心を持つのは、過去に検察官として少年の殺害事件に関与したという事実です。関東地方の地名が事件名として報道されていたと思いますが、ちょっと正確に思い出せない状態です。

　一月半ぐらい前という気がしますが、思うところがあって貝塚事件について調べていたところ、その関東地方の少年事件のことが出てきて、住田弁護士が過去に関与していたという情報に触れ、そういえば前にも見たと想い出したのです。

　貝塚事件について調べたきっかけは、鹿児島のDNAが問題になった事件のことだったと思います。私のTwilogで検索をすれば、より正確なことと流れがわかるかと思います。

廣野秀樹＼さらば弁護士鉄道・泥棒神社の夜さんはTwitterを使っています: "@amneris84 なかには後に冤罪が発覚したものの、全然不服を述べないで服役していた人もいるそうですね。貝塚事件とかいう事件で、グループで捕まったらしいですが、冤罪を訴えた人と何もしなかった人がいるみたいです。強姦事件で血液型が違っていたというような事件だったと思います。" https://twitter.com/hirono_hideki/status/18249109984

　ヒットしたのは上記のツイート1件だけでした。2010年7月11日のツイートです。あとで探しだすいようにキーワードを含めておいたつもりでいたのですが、そうはなっておらず、取っ掛かりが一つ失われました。

　同じ頃、山形マット死事件についても調べなおした記憶があります。ただ、山形マット死事件については、血液型などが争点になる事情はいっさいなかったはずかと思います。

　Googleで「住田弁護士　少年事件」で検索をしたところ、次のページがみつかりました。「草加事件」でしたが、違った地名の事件かと思っていました。立川事件は公安事件だったような記憶があるのですが、そのあたりも記憶が混同していました。

　三鷹事件というのも昭和の時代の著名な事件であったと記憶しています。三鷹ストーカー事件はストーカーとつくので容易に識別できますが、関東地方の地名を冠した事件というのは、過去にいくつかあって、地名だけでは記憶も混同しがちです。

　比較的最近のツイートだったのでTwitterAPIのtimelineメソッドからツイートの情報を得ることが出来ました。個別のツイートを指定する他のメソッドもあるのですが、3200件程度までしか遡ることが出来ないようです。

　個別のツイートで取得するスクリプトもあったはずなのですが、使っていないうちに存在を忘れてしまい、作り直すのも考えたのですがまだやっておらず、大抵は3200件以内で対処できるので、そちらのスクリプトを使って得た情報を利用します。前後に関連性のありそうなツイートです。

T：hirono_hideki（廣野秀樹＼さらば弁護士鉄道・泥棒神社の夜）：2016/02/04 04:45： https://twitter.com/hirono_hideki/status/694970056275525632 ： NHKドキュメンタリー - ハートネットＴＶ「最新ＤＮＡ型鑑定　防げなかった冤（えん）罪」 https://t.co/DEkiIDrJyl

　まず上記のツイートから「2月4日（木）午後8時00分～午後8時30分」という放送時間であったことを確認できました。NHKのEテレです。この放送のことは前々日ぐらいに、旭川市の中村元弥弁護士のツイートを見かけて知ることが出来たと記憶しています。

　さかのぼると次のツイートの問題がきっかけだったようです。

T：hirono_hideki（廣野秀樹＼さらば弁護士鉄道・泥棒神社の夜）：2016/02/04 08:11： https://twitter.com/hirono_hideki/status/695021733833641984 ： 山大生死亡:損賠訴訟　山形市長「適正な業務の範囲内」　救急車不出動で　／山形 - 弁護士 落合洋司　（東京弁護士会）　の 日々是好日 (id:yjochi / @yjochi) https://t.co/Qoki3qDVmy

　他にも引用したいものが沢山あるのですが、数が多すぎるのでTwilogのURLでご紹介しておきます。また、「貝塚事件」で検索に失敗したのは「貝塚ビニールハウス殺人事件」となっていたためです。

廣野秀樹＼さらば弁護士鉄道・泥棒神社の夜(@hirono_hideki)/2016年02月04日 - Twilog http://twilog.org/hirono_hideki/date-160204/asc

　なお、次のように「貝塚　事件」とやると意図通りの検索結果を得ることが出来ました。全角スペースを使っていますが、半角スペースの方が本来正しいのかもしれません。URLの前後に全角スペースを使うと対処される場合と、文字列がつながってエラーになる場合があります。

廣野秀樹＼さらば弁護士鉄道・泥棒神社の夜(@hirono_hideki)/「貝塚 事件」の検索結果 - Twilog http://bit.ly/1ppUEz6

　どうもTwilogでは入力された全角スペースを半角スペースに置き換えているようです。置き換えさせたくない場合は「'貝塚　事件'」とシングルクォートで囲めばよいようです。結果は「ツイートはみつかりません」ということにはなりました。

T：hirono_hideki（廣野秀樹＼さらば弁護士鉄道・泥棒神社の夜）：2016/02/04 05:30： https://twitter.com/hirono_hideki/status/694981280279109632 ： “貝塚ビニールハウス殺人事件との 比較から見た本件えん罪の明確性 弁護士” / “souka jiken ikensyo” https://t.co/p0YQRyJY9q

T：hirono_hideki（廣野秀樹＼さらば弁護士鉄道・泥棒神社の夜）：2016/02/04 05:21： https://twitter.com/hirono_hideki/status/694978977140727809 ： 貝塚ビニールハウス殺人事件 - Wikipedia https://t.co/3Fh3zjctL8

R：hirono_hideki（廣野秀樹＼さらば弁護士鉄道・泥棒神社の夜）＞2016/01/25 11:04＞ https://twitter.com/hirono_hideki/status/694972459699695617 ＞ bengo4topics （弁護士ドットコムニュース）＞ https://twitter.com/bengo4topics/status/691441545287852033 ＞ 鹿児島市で女性を暴行したとして、強姦罪に問われた男性被告人の控訴審判決で、逆転無罪が言い渡されました。萩原弁護士は「DNA鑑定を誤れば、冤罪の危険性が高まる」と警鐘を鳴らしています。https://t.co/kwafEalKZT https://t.co/CeoUCaDZbf

　上記2件のツイートをみてもわかると思いますが、私は勘違いをしていたようです。山形の救急車の問題は夜に読んだという記憶でいたのですが、先ほどのツイートは8時11分という朝のもので、貝塚ビニールハウス殺人事件のツイートは5時21分という早朝のようです。

　Twitterの場合、ログインしていないとツイートの投稿時刻がアメリカ時間として表示されるのですが、Twilogだと今のところ時差の問題は確認したことがありません。この時間を信じる外はなさそうですが、自分の記憶では夜に集中して調べていたという気がします。

　今、問題に気がついたのでスクリプトを修正しました。リツイートの時刻が元のツイートの時刻になっていたのです、わかりづらいので併記するように修正しました。修正後は次のようになります。

R：hirono_hideki（廣野秀樹＼さらば弁護士鉄道・泥棒神社の夜）＞2016/02/04 04:55／2016/01/25 11:04＞ https://twitter.com/hirono_hideki/status/694972459699695617 ＞ bengo4topics （弁護士ドットコムニュース）＞ https://twitter.com/bengo4topics/status/691441545287852033 ＞ 鹿児島市で女性を暴行したとして、強姦罪に問われた男性被告人の控訴審判決で、逆転無罪が言い渡されました。萩原弁護士は「DNA鑑定を誤れば、冤罪の危険性が高まる」と警鐘を鳴らしています。https://t.co/kwafEalKZT https://t.co/CeoUCaDZbf

　「2016/02/04 04:55／2016/01/25 11:04」という部分が修正箇所です。左がリツイートの時刻、右が元のツイートの投稿時刻です。リツイートの時刻が元のツイートの時刻より早くなることはありえないはずです。

　今テレビをみながら書いていますが、「白い巨塔」かと思います。たまたま観ているます。見応えのあるドラマです。どうも医療事故がテーマで、さきほどは引き払う事務所の弁護士のような場面もありました。主人公はヨーロッパにいるようです。

T：hirono_hideki（廣野秀樹＼さらば弁護士鉄道・泥棒神社の夜）：2016/03/04 16:45： https://twitter.com/hirono_hideki/status/705660384410214401 ： 山崎豊子の代表作をドラマ化。原作の持つ圧倒的なエネルギーはそのままに徹底した取材をもってリアリティを追求しつつ、人間の業を深く掘り下げる。 https://t.co/8wwMlezowV

T：hirono_hideki（廣野秀樹＼さらば弁護士鉄道・泥棒神社の夜）：2016/03/04 16:43： https://twitter.com/hirono_hideki/status/705659793986469888 ： ごご☆プレ・白い巨塔【天国と地獄(後編)】＜改行＞2016年3月4日（金）  15時53分～16時50分  の放送内容 https://t.co/H5LjFO9hYi

　メモ代わりに上記2件の番組情報をツイートに記録しました。そういえば「山崎豊子」という有名作家の作品だったということを想い出しました。

　山崎豊子氏は故人になられているように思います。「大地の子」も代表作ですが、著作というのはほとんど読んだ記憶がありません。ただ、その作品を作るための下調べや作業が緻密で入念で人並み外れていた、ということは何かの本で読んで知った記憶があります。

　「白い巨塔」というドラマは小学生の頃、テレビでやっていて大きな社会問題のように注目されていたという記憶があります。母親が観ていたので一緒に観ていたような記憶もあるのですが、さっぱり理解できない難しいないようだったような思い出となっています。

　同じ頃に山口百恵が主演の赤いシリーズというドラマがあって、それに大学の助教授が出てきて、ものすごい偉い人という権威の象徴のような印象を受けていたのですが、教授というもっと上の人がいるとも聞いて、まるで雲の上の世界だと思っていました。昭和40年代の終わり頃かと思います。

　「白い巨塔」は金沢刑務所の拘置所にいる時に、本を読んだ憶えもあります。数冊あるうちの一冊だけ読んだのかもしれません。強く印象に残ったのは、大学教授が背後に人を引き連れて巡回する場面で、大名行列とも表現されていたように思います。

　その「白い巨塔」のただひとつ印象に残る場面を、現実に目の当たりにしたのは、金沢大学附属病院での山口成良金沢大学教授の巡回でした。

　今、夕方16時ころにやっているテレビの「白い巨塔」ですが、数日前にも一度だけ見て、調べると2回目か3回目の放送で、録画予約することも考えたのですが、それっきり今日まで忘れていました。その前回に見た時、巡回のような場面を見たように思います。

　先ほど見たドラマは印象的でした。患者が電気ショックを受けたり組成措置を受けるまでは、まともに見ておらず筋もまったく理解できていませんでした。

　遺族となった妻と息子がいて、司法解剖を拒否するのですが、計算された誘導によるもので、そのあと妻と息子を乗せた車の運転手が、あれほどの地位の人が見送りに来ることは珍しいことで医療ミスの可能性があると、親切心で教えたことで、火葬場行きから司法解剖の手術を受ける場面になりました。

　そういえば医療事故の裁判というのも、最近では滅多に報道を見かけなくなりました。特に関心がなくてもやたらと目や耳に入る時期があったことを記憶にしていますが、平成の初めころに集中していたような気もします。

　医療問題で他に記憶に強く残っているのは、金沢刑務所の拘置所にいるとき週刊誌の記事で見たインフォームドコンセントのことです。読みやすい記事で革命的な転換点のようなことが書いてあったと記憶しています。

　法律の勉強をしていたときも、医療問題に関するものは読む機会がけっこうあったように思います。

　初めにモトケンこと矢部善朗弁護士（京都弁護士会）のブログを見た時も、中心的な話題になっていたのが福島県の大野病院事件でした。冤罪事件として著名になった鹿児島県の志布志事件は、その少し前だったように思います。

　金沢刑務所の拘置所の生活といえば、出来るのは読書とラジオ放送を聴くことぐらいでした。平成4年の事件で拘置所にいた頃は、長距離トラック運転手をしていた頃の習慣が続いていた頃もあり、よく週刊誌を購入して読んでいました。

　特に強く印象に残っているのは山形マット死事件の報道の記事のことです。モトケンこと矢部善朗弁護士（京都弁護士会）がその事件の担当検事であったことは、割と早い段階で本人のブログの記事として知っていましたが、強く意識するようになったのはここ数年になってのことです。

　廣野秀樹＼さらば弁護士鉄道・泥棒神社の夜(@hirono_hideki)/2016年02月04日 - Twilog http://twilog.org/hirono_hideki/date-160204/asc 、のツイートには時系列に納得出来ない点があります。

　時系列に納得できないところがありますが、同日に投稿した内容については、記憶違いと感じるところはありません。

　そういえば「山形　弁護士」などとTwitter検索をした状態で、ツイートのリンクのページを開いたりしていたように思います。同じキーワードで更新があれば定期的に更新数の通知が入ります。

T：hirono_hideki（廣野秀樹＼さらば弁護士鉄道・泥棒神社の夜）：2016/02/04 06:42： https://twitter.com/hirono_hideki/status/694999338804596736 ： “植田裕弁護士（６３）を業務停止６カ月の懲戒処分にしたと発表した。発効は６日付。” / “賠償請求、無断で取り下げ　山形の弁護士懲戒処分 - 産経ニュース” https://t.co/viOquSyJ4z

T：hirono_hideki（廣野秀樹＼さらば弁護士鉄道・泥棒神社の夜）：2016/02/04 06:39： https://twitter.com/hirono_hideki/status/694998678826831873 ： 賠償請求、無断で取り下げ　山形の植田裕弁護士・業務停止6月懲戒処分 - 弁護士自治を考える会 https://t.co/iVxlMaN90G

T：hirono_hideki（廣野秀樹＼さらば弁護士鉄道・泥棒神社の夜）：2016/02/04 06:36： https://twitter.com/hirono_hideki/status/694997939333140481 ： “【社会】山形マット死事件：「捜査は不十分だった」　検事が心情明かす | ログ速@２ちゃんねる(net)” https://t.co/m9p34ImwjQ #モトケン弁護士

T：hirono_hideki（廣野秀樹＼さらば弁護士鉄道・泥棒神社の夜）：2016/02/04 06:28： https://twitter.com/hirono_hideki/status/694995956777943041 ： https://t.co/ej4zVtAMCn

T：hirono_hideki（廣野秀樹＼さらば弁護士鉄道・泥棒神社の夜）：2016/02/04 06:28： https://twitter.com/hirono_hideki/status/694995881234292736 ： 年収70万円以下？ 客の金に手を出す貧乏弁護士の懐事情 https://t.co/IBamC4qInb

T：hirono_hideki（廣野秀樹＼さらば弁護士鉄道・泥棒神社の夜）：2016/02/04 06:26： https://twitter.com/hirono_hideki/status/694995329301622784 ： “＜山形マット死事件＞「捜査は不十分だった」　検事が心情明かす（毎日新聞）[3月4日6時37分更新] まさちゃん” https://t.co/OzTWSzI2OE #モトケン弁護士

T：hirono_hideki（廣野秀樹＼さらば弁護士鉄道・泥棒神社の夜）：2016/02/04 06:22： https://twitter.com/hirono_hideki/status/694994411919425536 ： 想いのままに。。。。  山形マット死事件　再審請求 https://t.co/0vlesukpiy

T：hirono_hideki（廣野秀樹＼さらば弁護士鉄道・泥棒神社の夜）：2016/02/04 06:20： https://twitter.com/hirono_hideki/status/694994007357808640 ： 誰のための「再審請求」か？ 山形マット死事件で人権派弁護士が暗躍中。 - この際、言いたい放題！＜旧館＞ https://t.co/uxm4vausk5

T：hirono_hideki（廣野秀樹＼さらば弁護士鉄道・泥棒神社の夜）：2016/02/04 06:17： https://twitter.com/hirono_hideki/status/694993208858800128 ： 《閲覧注意》"山形マット死事件" 7人の少年の親たちは被害家族のもとに誰一人未だに謝罪に訪れていない https://t.co/sZlvh9aHjr

T：hirono_hideki（廣野秀樹＼さらば弁護士鉄道・泥棒神社の夜）：2016/02/04 06:06： https://twitter.com/hirono_hideki/status/694990259755577345 ： お天気お姉さん号泣で再注目? 山形マット死事件で露呈した"村八分" - エキサイトニュース https://t.co/6CLWWT7As6

　上記は一定期間内の連続したツイートを取得したものです。時系列は後のものから先に並んでいるようです。データベースのSQL文だとDESCということになりそうです。

　「山形の植田裕弁護士・業務停止6月懲戒処分」というニュースは、この時初めて知ったものではなく、思い出して再度検索したものかと思います。見落としがちのニュースでしたが、確か小倉秀夫弁護士のツイートで山形マット死の事件との関連を知ることが出来、調べるきっかけになったと思います。

％Hideo_Ogura（小倉秀夫）のツイート％投稿日時％2015-08-17 17:51:00％ツイートのURL％ https://twitter.com/Hideo_Ogura/status/633199534810660864 ％
％Hideo_Ogura（小倉秀夫）のツイートの内容％
不思議な事件ですね。http://t.co/YXhD2APal9 この人は、山形マット死事件で元生徒側の弁護団長を努めていたっぽいのだけど。
％データベースへの登録日時％2015-09-25 18:02:28％

　データベースの登録が昨年の9月25日となっていて、けっこう前だなと思いました。小倉秀夫弁護士のツイートの投稿時刻はさらに一月以上前で8月17日ということになるようです。タイムラインで見つけたツイートという可能性は低そうな気がします。

　中断していました。時刻は21時06分です。19時から能登町役場に用事の集まりがあって出かけていました。家に戻ったのは20時20分ぐらいだったと思います。これからのことについてもっと真剣に考えるべきだと考えさせられた機会でもありましたが、思った以上に忙しくもなりそうです。

　たまたま旭川市の中村元弥弁護士のTwitterのタイムラインを開いていたことがきっかけですが、思いがけない発見もあって、取り上げたいことが次々に増えていくので、ますます悩ましくもなります。中村弁護士は元裁判官であるだけに注目していますが、タイムラインを開くことは少ないです。

　その前にモトケンこと矢部善朗弁護士（京都弁護士会）の気になる、これは記録しておくべきかと思うツイートがあって、それとの関連でも注目した中村元弥弁護士のリツイートです。ちょうどモトケンこと矢部善朗弁護士（京都弁護士会）のツイートを登録と考えていたところでした。

　今からモトケンこと矢部善朗弁護士（京都弁護士会）の最新ツイートをデータベースに記録する作業に取り掛かります。180件がAPIのリミッターなのですが、一度で登録できるか微妙だと、役場に出かける時に考えていたことでした。

　TwitterのAPIはメソッドによって違いはあるようですが、ここで登録するのに使っているメソッドでは一度に180件というリミッターの制限があって、15分でリミッターの解除という仕様になっているようです。リミッターの制限に掛かるとスクリプトの実行でエラーが発生します。

　ちょっと勘違いしていました。データベースへの登録は役場に出掛ける前後の数時間前に実行済みでした。3日ぐらい前だったと思いますが、ツイートの内容で、モトケンこと矢部善朗弁護士（京都弁護士会）と小倉秀夫弁護士のツイートを全件、データベースに記録することにしました。

　一週間から10日ほど前に同じくツイートの内容を見て、深澤諭史弁護士のツイートとリツイートを全件、データベースに登録することにしました。パソコンのディスク容量など気にしていたのですが、プログラムの処理としては全件登録が全く手間が掛かりません。

　2,3日前まではモトケンこと矢部善朗弁護士（京都弁護士会）と小倉秀夫弁護士のツイートを一つずつ目を通して確認しながら登録するようにしていました。どちらもツイートの数が多すぎて時間がかかり、時間の有効利用も考えて、全件記録に切り替えました。

　作業に取り掛かります。たびたびやっていることです。

　まずは「% k-blog-opt-cocolog.rb |grep motoken_tw」というコマンドの実行で、最終記録の状況を確認しました。次が該当するデータです。

参考資料：　モトケンこと矢部善朗弁護士（京都弁護士会）（@motoken_tw）のツイート・リツイート（105件、 2016-02-28 21:58〜2016-03-02 09:53：2016-03-02の記録）「101-105／105」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/03/motoken_tw105-1.html

　「2016-02-28 21:58〜2016-03-02 09:53：2016-03-02の記録」という部分から「2016-03-02 09:53」という部分のテキストを使って、次の作業に掛かります。

% bin/tw_user_tweet-sql-search-make-text-html.rb --full_sql="SELECT * FROM tw_user_tweet WHERE tw_date BETWEEN '2016-03-02 09:53' AND '3016-02-24 10:32' AND (user LIKE \"motoken_tw\") ORDER BY tw_date ASC" > w

　上記のコマンドを実行しました。自作のスクリプトなので仕様というかルールはすべて私自身が決めたものです。「> ｗ」という部分はリダイレクトといって、本来の画面（端末）へのテキストの出力をｗというファイル名のファイルへの保存に切り替えています。

　「> x」の部分を「| xsel -b」に置き換えると、出力結果が丸ごとクリップボードに保存されるのですが、たまにクリップボードの内容がコマンドの実行後にも更新されないことがあって、ファイルの保存にしておいた方が確実かと思い件数が多い時はそうすることが多いです。

　特定のファイルの内容を編集中のファイルのカーソルの位置に読み込むことはwordのようなワープロソフトでもお馴染みの機能かと思いますが、私が使っているEmacsというエディタではキーボードでの「C-x i」がそのコマンドの実行になります。

　Emacsのorg-modeでｗのファイルからのテキストの読み込みまたはクリップボードからの貼り付けで追加したテキストデータは他に割り当てたコマンドとスクリプトで一発にブログへ投稿するようにプログラムを組んでおります。

　ブログの一つの記事でツイートの数が多すぎると、TwitterのJavaScriptのスタイルの適用がなされないということを実体験にしていますので、最近のスクリプトでは自動で100件ずつorg-modeの項目とブログへの記事を分けて投稿するようにしています。

　ブログの記事とURLのデータベースへの登録は「h-cocolog-add.rb」という自作のコマンドでやっています。このスクリプトの内容はRSSでのブログからのデータの取得となるので、ココログの場合、最新の20件分しかデータが取得できないことになります。

　言い換えれば、20件以上未登録のデータを貯めない段階で、コマンドを実行してデータベースへの登録をするように自前の管理が必要になる訳です。ブログの過去の記事の取得というのは簡単そうに思えて、なかなか難しい物があります。

　以前はRSSを使わなくても過去の記事の一覧データを取得していたこともあるのですが、ブログサービスごとの違いもあって、簡単そうで実に厄介なところがあります。その点でもAPIの充実した機能が提供されているTwitterは、ものすごくありがたいのです。

　そういえば昨夜辺りに、Twitterの仕様変更のようなものを実体験していて、あとで確認したことですが、Twitterにアカウントでログインした状態ではTwitterの高度な検索でブロックされているアカウントのツイートが習得できない、という事態に遭遇しました。

　これまではそういう不具合をまったく経験していなかったので、2,3日前の仕様の変更だったと考えられ、APIを含めTwitterの仕様変更というのは常にあり得ることで、英語でのアナウンスが基本なので、仕様変更の情報を事前に知ることは困難であり、事前に知ったことは一度もありません。

　Twitterの仕様の変更というのはユーザというか利用者からの苦情によるところが大きいと考えられ、その影響力の大きさで考えても弁護士によるものが想定されます。私の行動で苦情が入り、不自由にされたならば、責任も感じるところであって検察庁にも実態の把握と対処を希望したいところです。

　私こと廣野秀樹は、弁護士らの自由な正義によって、取り返しのつかない権利侵害を受けてきたと考えており、弁護士らが折りにふれて振りかざす「公権力の監視」以上に、弁護士の監視を社会的に重要事項だと考えています。その実践の一環としてTwitterのAPIの活用をやっています。

　ここ数日、弁護士らの自由な正義と独自の論理について考えさせられる問題が多く、危険性も感じています。そのすべてを書き尽くせないことも残念ですが、出来る限りのことを一人でも多くの人に伝えられたい、歴史的に伝承したいと心掛けています。弁護士がますます魔性の化物に見えています。

　別の表現をすれば、弁護士こそが真に深刻な社会汚染の原因だと考えています。大きな犠牲をともなった実体験に裏打ちされ、長い年月を掛けて到達した総括的結論です。

　人間界と弁護士界の区別が理解の前提として必要とも考えています。妖怪にも近いところがありますが、同列に置くことは妖怪の方に非礼と迷惑が考えられるところであって、補充のご説明もその都度、適宜必要かと考えているところです。

　さて、今からさきほど記録の必要だと判断したモトケンこと矢部善朗弁護士（京都弁護士会）のツイートを、投稿したブログの記事から探しだし、特定・符合する部分をコピペで記載しておきたいと思います。

［motoken_tw__20160304_2132_173／173のツイート］
％motoken_tw（モトケン）のツイート％投稿日時％2016-03-04 20:18:00％ツイートのURL％ https://twitter.com/motoken_tw/status/705713917863923712 ％
％motoken_tw（モトケン）のツイートの内容％
.@Hideo_Ogura コメントの内容を検討せずに、保守速報のコメント欄投稿者のコメントであるというだけで普通でないと評価するのは、もろに偏見そのものなんだけど、小倉弁護士にはそういう自覚が全くない。小倉弁護士の差別体質が顕著であると言う理由です。
％データベースへの登録日時％2016-03-04 20:30:15％

　上記のモトケンこと矢部善朗弁護士（京都弁護士会）のツイートですが、意外なことに記録した最後のツイートになっていました。これに負けないぐらい記録しておきたいという衝動に駆られるモトケンこと矢部善朗弁護士（京都弁護士会）のツイートはたびたび見かけています。

　偶然目にした関連性もあって取り上げましたが、対とも言える中村元弥弁護士のリツイートは次のツイートになります。

T：KTets（（:]ミ（:]ミ（:]ミ）：2016/03/04 18:19： https://twitter.com/KTets/status/705684087780978688 ： 今、ふと、ブログのアクセス解析を見たら、「丸顔 法律事務員 西天満」でキーワード検索して来た人がいるのだが、何を探したいのであろうか。

　スクリーンショットを含めた記録は非常上告-最高検察庁御中_ツイッター（@s_hirono）の方でもやったかと思いますが、あらためてこのアカウントにブロックされていることを確認しました。

　秋葉原の無差別殺傷事件が発生した頃になりますが、モトケンこと矢部善朗弁護士（京都弁護士会）のブログの常連コメンテータであった可能性のあるアカウントです。ブログの方のハンドル名は「みみみ」であったように記憶しています。

　このTwitterアカウントもだいぶん前から存在を確認していますが、タイムラインを開いてツイートを見ることはまれです。弁護士らしいことはツイートの内容で承知していましたが、ブログをやっているらしいことは、今回のツイートで初めて知りました。

　ツイートの内容でブログをやっているらしいことはわかりますが、プロフィールをみてもブログの存在は特定できません。今回、プロフィールの情報をみて私が新たに確認できたことは、大阪で弁護士をやっているらしいということです。

　私が見落としていただけかもしれませんが、「OSAKA JAPAN」という記載で、それに気が付きました。スクリーンショットはこれまでに何度か記録しているはずです。簡易になりますが、私のパソコンのシステムで、それを確認したいと思います。

　「% locate KTets」というコマンドの実行で確認しました事前に「sudo updatedb」という最新状態にするコマンドは実行しています。思ったより件数が少なく、私自身、これまではさほど重視していなかったこともうかがわれます。

/home/a66/git/kk_hirono_2016/a_資料/a_スクリーンショット/2016-03-04-205809_ブロックされているため、@KTetsさんのフォローや@KTetsさんのツイートの表示はできません。詳細はこちら.jpg
/home/a66/git/kk_hirono_2016/a_資料/a_スクリーンショット/2016-01/2016-01-16-211627_ブロックされているため、@KTetsさんのフォローや@KTetsさんのツイートの表示はできません。詳細はこちら.jpg
/home/a66/kk_hirono/告訴状の内容に関連したスクリーンショット/2015年12月分/2015-12-07-110557_ブロックされているため、@KTetsさんをフォローしたり、@KTetsさんのツイートを見ることができません。詳しくはこちら.jpg
/home/a66/kk_hirono/告訴状の内容に関連したスクリーンショット/2015年2月分/2015-02-05-064518_ブロックされているため、@KTetsさんをフォローしたり、@KTetsさんのツイートを見ることができません。詳しくはこちら.jpg

　この程度だと目視で十分かと思いますが該当したファイルは4件でした。もっとも古いもので「2015-02-05-064518」という日付情報を含むファイルがあります。少なくとも1年ちょっと前からブロックされていることを確認できました。

　これまで以上に私の反応が強くなり、常にセーブしがちの本書の取り上げに至ったのは、昨日あたりに思いがけず見つけた同じく、匿名の弁護士アカウントのツイートのことがあったからです。

　「非常上告」をキーワードに法クラらのツイートをデータベースにまとめておこうと思い立ったのがきっかけでした。特殊なキーワードなので、キーワードのみからの検索も可能なのですが、そのツイートを見てから予定した作業は中断しています。

　追加でTwitter検索から探しだしたツイートを追加する予定でいたのですが、現段階でデータベースに登録済みのものから、「非常上告」をキーワードに含む法クラらのツイートをまとめておきたいと思います。

　ここでも一つの作業の様子をご紹介しておきたいと思います。

% bin/usertimeline-tw_user_tweet-sql-search-make-text-html.rb --search=非常上告 > t

　よい機会だと上記のコマンドを実行したのですが該当はゼロでした。これはtw_user_timelineというテーブルから該当するツイートのデータを探しだしています。本当はその結果からtw_user_tweetというテーブルにデータを登録する作業を行うところでした。

　追加の情報はなかったですが、tw_user_tweetというテーブルの情報から、まとめの作成を行い、先ほどと同じようにブログの記事として投稿します。これからの実行ですが、私の予想では10件に見たないぐらいだと思います。あると思うのは小倉秀夫弁護士のツイートです。

[9989]  % bin/tw_user_tweet-sql-search-make-text-html.rb n 非常上告 --word_stime=a |xsel -b

　上記のコマンドというかスクリプトを実行しました。取得できたデータは12件のようです。ポップアップのメッセージとして、処理の件数を表示するようにしているので、それで確認しました。

　「% k-blog-opt-cocolog.rb」という自作のコマンドでデータベースに登録済みのココログフリーの記事の一覧情報を取得しました。現在のところ676件の登録数となっているようですが、長い放置状態以前の記事は含まれていないはずかと思います。

　次が最新の3件のデータになります。先の2件はさきほどのモトケンこと矢部善朗弁護士（京都弁護士会）のツイートのまとめになります。

参考資料：　モトケンこと矢部善朗弁護士（京都弁護士会）（@motoken_tw）のツイート・リツイート（173件、 2016-03-02 09:53〜2016-03-04 20:18：2016-03-04の記録）「1-100／173」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/03/motoken_tw173-2.html
参考資料：　モトケンこと矢部善朗弁護士（京都弁護士会）（@motoken_tw）のツイート・リツイート（173件、 2016-03-02 09:53〜2016-03-04 20:18：2016-03-04の記録）「101-173／173」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/03/motoken_tw173-1.html
参考資料：　「非常上告」をキーワードに含む（法クラ・弁護士・ジャーナリスト関連）のツイート・リツイート（5アカウント、12件、 2015-03-02 20:04〜2015-09-09 21:00） http://hirono-hideki.cocolog-nifty.com/blog/2016/03/512-2015-03-02-.html

　「非常上告」のまとめでは、最初にジャーナリストの江川紹子さんのツイートがあって意外でした。ジャーナリストの江川紹子さんのツイートはタイムラインからの自動登録をやっていないので、私が手動で登録したはずですが、ちょっと見覚えのないツイートです。

　このツイートのまとめは、初期の頃は別にして、投稿の日付が古い順に並ぶようにしています。データベースの処理としては日付の数値がが若い順にならぶことになります。

　実行するデータベース操作言語SQL文の「ORDER BY tw_date ASC」という部分が、その指定になります。tw_dateというフイールド（カラム）の内容を基準に、昇順での並び替えの指定になります。先ほども触れましたがDESCだと降順になります。

　フィールド（カラム）のデータ型が数値だと数値が基準になるのでわかりやすいですが、文字列だと文字コードの順番で並ぶことになり、英数字だとまだ意味がありますが、日本語の文字コードだと順序の把握が不可能に近いので並び替えの意味がなくなってしまいます。

　リツイートのツイートも元のツイートの投稿時刻ではなく、リツイートしたアカウントのリツイートの時刻を基準にしているので、そのあたりも留意しておいて頂いた方が誤解の原因にもならないかと、余計かもしれない説明をさせていただきました。

　問題のツイートは次のものです。こちらは最新の投稿日時になっていて、ブログの記事での並び順も最後に位置しています。

［leplusallez__20160304_2302_12／12のツイート］
％leplusallez（浜木綿弁右衛門）のツイート％投稿日時％2015-09-09 21:00:00％ツイートのURL％ https://twitter.com/leplusallez/status/641581934439600128 ％
％leplusallez（浜木綿弁右衛門）のツイートの内容％
手合いなとど素人に評されるいわれはないのでブロック、非常上告だかしらんけど一生やってろどうせ何も得られないから
％データベースへの登録日時％2016-03-03 17:27:56％

　@leplusallezというTwitterアカウントの情報も、これまでの経緯としてパソコンからデータを取得し、次に掲載をしておきたいと思います。

[9998]  % locate leplusallez
/home/a66/git/kk_hirono_2016/a_資料/a_スクリーンショット/2016-03-03-173002_ブロックされているため、@leplusallezさんのフォローや@leplusallezさんのツイートの表示はできません。詳細はこちら.jpg
/home/a66/git/kk_hirono_2016/a_資料/a_スクリーンショット/2016-03-04-082209_from：leplusallez　-　Twitter検索.jpg
/home/a66/git/kk_hirono_2016/a_資料/a_スクリーンショット/2016-01/2016-01-11-052035_ブロックされているため、@leplusallezさんをフォローしたり、@leplusallezさんのツイートを見ることができません。詳しくは.jpg
/home/a66/git/kk_hirono_2016/a_資料/a_スクリーンショット/2016-01/2016-01-16-212049_ブロックされているため、@leplusallezさんのフォローや@leplusallezさんのツイートの表示はできません。詳細はこちら.jpg
/home/a66/kk_hirono/告訴状の内容に関連したスクリーンショット/2014年11月分/2014-11-17-221831_浜木綿弁右衛門（@leplusallez）さん　｜　Twitter.jpg
/home/a66/kk_hirono/告訴状の内容に関連したスクリーンショット/2015年10月分/2015-10-03-001541_浜木綿弁右衛門（@leplusallez）さん　｜　Twitter.jpg
/home/a66/kk_hirono/告訴状の内容に関連したスクリーンショット/2015年11月分/2015-11-26-234448_浜木綿弁右衛門（@leplusallez）さん　｜　Twitter.jpg
/home/a66/kk_hirono/告訴状の内容に関連したスクリーンショット/2015年3月分/2015-03-03-145626_ブロックされているため、@leplusallezさんをフォローしたり、@leplusallezさんのツイートを見ることがで.jpg
/home/a66/kk_hirono/告訴状の内容に関連したスクリーンショット/2015年7月分/2015-07-23-175612_ブロックされているため、@leplusallezさんをフォローしたり、@leplusallezさんのツイートを見ることができません。詳しくは.jpg
/home/a66/kk_hirono/告訴状の内容に関連したスクリーンショット/2015年7月分/2015-07-23-182426_浜木綿弁右衛門@leplusallez恨まれ稼業のテーマ.jpg
/home/a66/kk_hirono/告訴状の内容に関連したスクリーンショット/2015年8月分/2015-08-21-224552_浜木綿弁右衛門　@leplusallez　　4時間前　まーた業際拡大の既成事実作りかゲスだな.jpg
/home/a66/kk_hirono/告訴状の内容に関連したスクリーンショット/2015年8月分/2015-08-21-224621_浜木綿弁右衛門　@leplusallez　　4時間前　まーた業際拡大の既成事実作りかゲスだな.jpg
/home/a66/kk_hirono/告訴状の内容に関連したスクリーンショット/2015年8月分/2015-08-21-224649_浜木綿弁右衛門　@leplusallez　　4時間前　まーた業際拡大の既成事実作りかゲスだな.jpg

　私の目視で13件の該当ファイルの所在が確認されました。期間としても取り扱う対象範囲が広すぎるということもありますが、正確を期することが、ミスや誤解によるご迷惑を避ける責任とも考え、プログラムによる機械的処理をしていますが、機械的処理は別の意味で誤りの出る可能性もあります。

　今もそうなのですが、パソコンで複雑な処理を繰り返し実行していると、パソコンの機械的能力不足を痛感することがあります。処理に時間がかかりすぎる場合はパソコンの再起動をするという対処もしていますが、経済的事情もあって満足のゆくスペックのパソコンは使えていません。

　現在のデータベースの登録状況ですが、次のようになっています。数が増えるほどに処理に時間がかかり、パソコンの負担も感じています。データ量が増えるにつれ、その傾向は必然的に高まるところでしょう。耐久テストのような未知の部分を含めた試みという状況でもあります。

2016-03-04 23:43
timeline,221435
tweet,44730
cocolog,773
hatena,404
wp,20383

　tw_user_timelineのテーブルでは登録データが22万を超えています。データベースならでは扱えるデータ量かもしれません。MySQLでは100万件程度だとなんなく扱えると数年前に情報を見たことがありますが、検索だけは多少時間が掛かるようになっています。

　時間がかかると言っても今のところ一分は掛かっていないように思います。とにかく収集しているデータが膨大で対象が広いということは、管理や状態の把握にも無理や限界があるということであり、想定外の事態に備えた蓄積であるという目的をご理解いただきたいところです。

　データベースのデータ自体はバイナリーになっていて、それ故に高速な処理が可能と数年前に情報を見たことがありますが、MySQLのデータは目に見えるテクストファイルというかたちで、エクスポートやインポートが可能なものです。ダンプ、リストアと呼ばれるものです。

　最終的にダンプしたSQLを添付のDVDに収録して提出する予定でいます。22万件になっているテーブルのデータでも、最新の状態の確認はしていませんが、まだ100MBは行っていないぐらいかと。４Gつまり4000MB程度は一枚のDVDに記録出来るはずで、40分の1と見ることも出来ます。

　非常上告の参考としての資料です。私の非常上告への試みは、法律のど素人ながら史上初のものだと考えています。それだけの広範囲な資料をご用意しているものであって、とりわけ重要と考えているのが深澤諭史弁護士のツイートとリツイートでもあります。

　今、テレビを見ると日付が変わっていることに気が付きました。記述範囲の仕切り直しをしておきたいと思います。今日とか昨日という記述もしにくくなるので、それも配慮しています。

2016-03-05　土曜日　00：07　＜＜ ［［　←これまでの記述範囲の終了時刻］］＜＜



2016-03-05　土曜日　00：10　＞＞ ［［　←これからの記述範囲の開始時刻］］＞＞

　MySQLはプログラム言語に対応したドライバーなどのライブリーを使わなくても、次のように直接、データベースの操作でデータの取得が出来ます。\Gという部分は私も最近になって知ったものですが、出力結果を見やすく整形してくれるものです。通常は;でした。

mysql -u root benngosi_twitter -e 'SELECT * FROM tw_user_tweet WHERE tweet LIKE "%社労士%" AND tweet LIKE "%ブログ%" ORDER BY tw_date ASC\G'

　他の計算式と同じですが、演算子には優先順位があるので（）で囲む必要が出る場合があります。ちょっとした手違いで、目的の検索がうまく行かない場合があり、私はこれまで何度か経験してきました。

　SQL文はオーソドックスなものでクセはあるものの他のプログラム言語に比べれば比較的単純と思えるのですが、弁護士のツイートやブログで、SQLという言葉を見たことは今のところ一度もありません。最近はないですが、Emacsは見かけることがありました。

　有能とか無能を問題にする趣味はありません。私がこれまで有用性を見出し独学で培ってきた知識や経験を、それ以上のもの、成果として活用して頂くことが私の望みであり、期待であります。

　私の場合、時間だけは贅沢に自分のために使うことが出来てきました。そのことは数時間前の能登町役場での会合でも痛感しました。ただ、それも私が他のことの人間らしい生活を犠牲にしてやったきた選択です。趣味といえばアジ釣りとイカ釣りぐらいです。

　初めは拘置所で被害者AAさんに対するできうる限りの償いとして取り組んできたことです。調書に被害者AAさんの仕事がコンピューター操作と見たこと、被害者AAさんの父親AKさんに電話で、コンピュータの勉強をしていると話した時、唯一うれしそうな反応を受けたことも原動力となってきました。

　時刻は15時04分になっています。2時間ぐらい前になりますか昼食前に考えて決めたのですが、次は「被害者AAさんの父親AKさんの立場で考える刑事再審制度における弁護士に対する不信感と悪魔性＼墓場へ向かう弁護士鉄道・社会的告発」というタイトルで続きを書きたいと思います。

　この項目では被害者AAさんのことを中心に具体的な事実を交えて概要を描くつもりでいましたが、気になることもあって、そちらの方向には集中できそうにありません。

　3日ほど前の再審開始というニュースを見てから、改めて再審という制度について考えるようになり、当初は非常上告との関係性と違いについて書くつもりでいたのですが、被害者AAさんの父親AKさんとの関係性と事実経過からこれまでの経過を振り返り、今後の方向性を示したいと思います。

2016-03-05　土曜日　15：13　＜＜ ［［　←これまでの記述範囲の終了時刻］］＜＜
**** 被害者AAさんの父親AKさんの立場で考える刑事再審制度における弁護士に対する不信感と悪魔性＼墓場へ向かう弁護士鉄道・社会的告発

:CATEGORIES: 被害者AAさんの父親AKさん
:TAGS: 神山啓史弁護士,東電OL殺害事件,山口治夫弁護士,山口成良金沢大学教授

2016-03-05　土曜日　15：21　＞＞ ［［　←これからの記述範囲の開始時刻］］＞＞

健やかな成長と幸せを願う、というひな祭りに思いを馳せる被害者AAさんとその家族の生活と人生と被告訴人弁護士らの犯罪性 http://hirono-hideki.cocolog-nifty.com/blog/2016/03/aa-e881.html

　内容は上記ブログ記事の続きになります。ここ数日の流れの一つとして、まずは少し上流に位置するニュース記事を引用を交えてご紹介しておきたいと思います。弁護士の怪物性、社会汚染について深刻に考える要素の一つであります。

／ ********************（引用開始）********************
引用URL＞＞＞＞：http://headlines.yahoo.co.jp/hl?a=20160229-00000054-jij-soci 検察官役に敏腕弁護士＝記録膨大、準備7カ月―福島原発 （時事通信） - Yahoo!ニュース

東電旧経営陣の責任を追及する検察官役の指定弁護士には、刑事弁護に精通した弁護士らが就任した。
　これまでで最も多い5人が選任されたが、事件が複雑で記録も多いことから準備は難航。検察審査会の起訴議決公表から強制起訴まで7カ月を要した。
　指定弁護士に選任されたのは、再審で無罪が確定した東電女性社員殺害事件で弁護人を務めた石田省三郎（69）、神山啓史両弁護士（60）ら。当初は両弁護士と山内久光弁護士（52）の3人だったが、後に2人が追加された。

 ********************（引用終了）********************／

　神山弁護士は再審無罪となった東電OL殺害事件の主任弁護人ともこの記事には書いてあります。3人だったように思いますが弁護団の一人だったことは知っていて、それだけに注目度の高い弁護士でしたが、主任弁護人であったことは、これまで知らないか不十分な認識でいました。

　これまで幾度かTwitterで取り上げてきた記事があるのですが、それをまず念頭の資料としてご紹介しておきたいと思います。

／ ********************（引用開始）********************
引用URL＞＞＞＞：http://gendai.ismedia.jp/articles/-/34136 東電OL殺人事件　テレビにも出ないしカネももらわない　ゴビンダさんの弁護団　15年間の冤罪法廷で勝ち取ったもの　 | 経済の死角 | 現代ビジネス [講談社]

「私はいまでもゴビンダは真っクロだと思ってます。無罪判決は司法が世論におもねった結果だ。マスコミはゴビンダの好青年の部分ばかりを報じているが、彼には裏の顔もある。バイト先の店主が『あれは不良外人だ』と言っていた。捜査員は死に物狂いで捜査して、他にも容疑者がいる可能性を二重三重に検証した末に逮捕した。部下に辛い捜査をさせた私が、ゴビンダはクロ、という持論を捨て去るわけにはいかない」

 これは平田氏個人の見解ではない。警視庁はゴビンダさんの無罪が確定すると、龍一文・捜査一課長名でこんな声明を出した。

「司法の判断にコメントする立場ではないが、無罪判決が出たことは真摯に受け止め、今後の捜査にいかしていきたい」

 司法の判断に納得していない、という本音が行間から伝わってくる。

「あの事件では弁護人にものすごく捜査妨害された。ゴビンダを逮捕した晩、弁護人が接見した途端に完全黙秘になった。留置場から(取り調べに)出てこないこともあったが、それも弁護人の入れ知恵。神山、神田、佃の『カンカンツク』ですよ」(平田氏)

 当時、捜査一課の刑事たちはゴビンダについた神山啓史、神田安積、佃克彦の三弁護士を「カンカンツク」と呼んで忌み嫌っていた。このエピソードを聞き、「それはむしろ名誉なことですね」と語るのは、カンカンツクの一角をなした佃克彦弁護士(48歳)だ。

 ********************（引用終了）********************／

　上記のネット記事は次のようにGoogleで検索しました。他との関連もあるので、スクリーンショットでご紹介したいと思います。検索結果の1ページ目ですが、３つのスクリーンショットになっています。　

投稿者：s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2016-03-05 15:37  ツイート： https://twitter.com/s_hirono/status/706005772077916160
2016-03-05-153743_神山弁護士　-　Google　検索.jpg https://t.co/TCV9wCCMcR

投稿者：s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2016-03-05 15:37  ツイート： https://twitter.com/s_hirono/status/706005650464083968
2016-03-05-153714_神山弁護士　-　Google　検索.jpg https://t.co/NuDtqxX8PB

投稿者：s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2016-03-05 15:36  ツイート： https://twitter.com/s_hirono/status/706005370280370176
2016-03-05-153607_神山弁護士　-　Google　検索.jpg https://t.co/8CMgypNOA9

　この検索でまた一つ新たに思い出したのですが、神山啓史弁護士は桜丘法律事務所の所属のようです。「参考資料扱いにした告訴状の下書き」には説明を書いていると思いますが、同じ渋谷の法律事務所ということで着目した経緯もあります。

　名前が思い出せず、なぜか忘れやすい弁護士名なのですが、「手紙」をキーワードにlocate検索をすれば情報が見つかるはずです。locateはシステム管理者の権限がないと更新が出来なかったり、管理者以外には使えない対策をされることがあると聞いているので、findコマンドを使います。

NS:~/kk_hirono
[9955]  % find . -name '*手紙*'
./資料写真/2015年8月14日に見つけた裁判資料/2015-08-14_11.04.11＿福井刑務所への母親の手紙.jpg
./資料写真/2015年8月14日に見つけた裁判資料/2015-08-14_11.02.46＿福井刑務所への母親の手紙.jpg
./資料写真/2015年8月14日に見つけた裁判資料/2015-08-14_11.05.50＿福井刑務所への母親の手紙.jpg
./資料写真/2015年8月14日に見つけた裁判資料/2015-08-14_11.04.28＿福井刑務所への母親の手紙.jpg
./資料写真/2015年8月14日に見つけた裁判資料/2015-08-14_11.02.59＿福井刑務所への母親の手紙.jpg
./資料写真/2015年8月14日に見つけた裁判資料/2015-08-14_11.03.26＿福井刑務所への母親の手紙.jpg
./一件記録・写真/H12-07-31_山口治夫弁護士からの手紙
./一件記録・写真/H12-07-31_山口治夫弁護士からの手紙/H12-07-31_山口治夫弁護士からの手紙_01.jpg
./一件記録・写真/H12-07-31_山口治夫弁護士からの手紙/H12-07-31_山口治夫弁護士からの手紙_03.jpg
./一件記録・写真/H12-07-31_山口治夫弁護士からの手紙/H12-07-31_山口治夫弁護士からの手紙_04.jpg
./一件記録・写真/H12-07-31_山口治夫弁護士からの手紙/H12-07-31_山口治夫弁護士からの手紙_02.jpg
./一件記録・写真/H12-05-22_上告審国選弁護人山口治夫の手紙
./一件記録・写真/H12-05-22_上告審国選弁護人山口治夫の手紙/H12-05-22_上告審国選弁護人山口治夫の手紙_01.jpg
./一件記録・写真/H12-05-22_上告審国選弁護人山口治夫の手紙/H12-05-22_上告審国選弁護人山口治夫の手紙_03.jpg
./一件記録・写真/H12-05-22_上告審国選弁護人山口治夫の手紙/H12-05-22_上告審国選弁護人山口治夫の手紙_02.jpg
./告訴状の内容に関連したスクリーンショット/2014年7月分/2014-07-03-232435_手紙は接見した国選弁護人が郵送しており、地検はこの男性弁護士について在宅のまま調べを進める。.jpg
./告訴状の内容に関連したスクリーンショット/2015年6月分/2015-06-26-202430_弁護士からの手紙や電話に対応するの，やめましょう。いろいろと，あとで，取り返し付かないことになります。（･∀･；）.jpg

　「山口治夫弁護士」だと確認出来ました。私の被害者AAさんの父親AKさんに対する平成11年の傷害事件の上告審で、国選弁護人となった弁護士です。

　先ほどと同じく今度は「山口治夫弁護士」でGoogle検索し、３つのスクリーンショットとして画像を保存しました。同じくTwitterに画像付きツイートとして投稿したものをご紹介します。

投稿者：s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2016-03-05 16:00  ツイート： https://twitter.com/s_hirono/status/706011539287908352
2016-03-05-160038_山口治夫弁護士　-　Google　検索.jpg https://t.co/MABMQW0wyC

投稿者：s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2016-03-05 16:00  ツイート： https://twitter.com/s_hirono/status/706011427106983938
2016-03-05-160011_山口治夫弁護士　-　Google　検索.jpg https://t.co/fazFb4YwZH

投稿者：s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2016-03-05 15:59  ツイート： https://twitter.com/s_hirono/status/706011268209987584
2016-03-05-155933_山口治夫弁護士　-　Google　検索.jpg https://t.co/FWrExUm1yv

　今回の検索で新たな発見がありました。共著で刑事弁護の書籍を出していたようです。わりとありがちな名前とも思えるので、同じ弁護士として同姓同名の別人という可能性も排除はできないと思いますが、本人である可能性は高いと思います。

　ずい分前で1年以上は経過していると思いますが、これまでにも同じ検索はやっており、めぼしい情報は見た覚えがありません。書籍の情報は青林書院（2003/06発売）となっています。検索結果に見つけた次のページです。

刑事弁護の手続と技法 / 庭山 英雄/山口 治夫【編】 - 紀伊國屋書店ウェブストア https://www.kinokuniya.co.jp/f/dsg-01-9784417013211

アルバム - Google+ https://plus.google.com/photos/117003214470411118615/album/5676958252778613761/5676958307861890114

　同じ検索結果のページから以前、私が公開した写真のページなど見ていました。あるはずと思っているものが見つからないのですが、上記の公開写真には記憶に残っていなかった文言の記載がありました。

　「手紙の中にーさんの理解と協力が必要条件であるとかいてありますが、ーあんは貴殿に対し厳罰にして下さいということを述べていることをご理解下さい。」という部分が新たな発見です。

　私の記憶に最も印象的に残っているのは、「それは国選弁護の範囲外です」というような文言で、示談交渉的な被害者AAさんの父親AKさんとの接触を断る内容のものでした。

　パソコンのシステム内の写真ファイルで確認をしてみたいと思います。ただでさえ読みづらい手書きの文字なので、鮮明に拡大して見る必要があります。

　確認が出来ました。思っていたよりずいぶんとひどい内容に思いましたが、それは客観的な感覚と思います。以前は他の弁護士に比べ、好意的であるとすら印象を受けていた覚えがあります。理解を得るための努力を続けていた時期ですが、弁護士幻覚という魔法にかけられていた気分です。

平成12年7月31日_山口治夫弁護士（東京弁護士会）からの手紙 http://s-hirono.blogspot.jp/2011/11/12731.html

　上記のページある写真の手紙に間違いありませんでした。赤い色で被害者AAさんの父親AKさんの名前をマーキングしているため、私自身、今回初めに見た時は内容が理解できなかったようです。ここには次のように書いてあります。

「貴殿より（１）ーさんに送付して下さいということと（２）母親にお金の送金をして下さるよう依頼して下さいという２つのことを頼まれました。」

「しかしながら（１）については要請に応じかねますので送付されてきた書面をお返し致します。貴殿においてーさんに送ってよいかどうか判断して行って下さい。」

「（２）についてはこれもご要望に応じ兼ねます。いずれにしても国選弁護人としての活動範囲を越えるものであることをご了承下さい。」

　被害者AAさんの父親AKさんに同封した手紙を転送してくれと頼んだようですが、こんなのはすっかり忘れていましたし、前に写真を公開するのにマスキング等の作業をした時も、気に留めずにいました。他の考え事が多すぎて気の回らない状態だったものと考えられます。

　私はこれまで山口治夫弁護士に対して余り批判的なことを書いてはいないように思います。手紙で連絡をくれ見通しを示してくれただけでも、ずいぶんましな弁護士に見えていたからです。

　写真を貼り付けた上記ブログの記事は2011年11月21日の段階で公開されていたようです。他にも同じような公開をしたような憶えもあるのですが、定期的にまとめてそのような作業をやってきたので、何時頃どこでやったのかは、正直よく憶えていません。

　弁護士といえども送られてきた手紙を無断で公開することは批判の目を向けられることは覚悟のことでした。申し入れがあれば重大な必要性を指摘し対応するつもりでの公開でした。そのような申し入れを受けたことはこれまで一度もありません。小倉秀夫弁護士から少しあったぐらいです。

　平成11年の事件については「参考資料扱いにした過去の告訴状の下書き」で詳しいことは書いていないように思います。リアルタイムに近い事実関係は、先ごろプライベートモードから公開モードに切り替えたはてなダイアリーのブログに記事としていくつも書いてあるはずです。

　上告審の国選弁護人になった山口治夫弁護士のことを余り批判は出来ないと思いますが、そこにも刑事弁護の欺瞞性と有害性を深刻に感じるところです。平成11年の事件の基礎になっているのは平成4年の事件であり、一貫した共通性があります。

　被害者の言葉を額面通りにしか受け取らず、弁護士として都合のよい事実だけを漁るように選り分け、他は一切無視するという姿勢です。それと表裏の関係になるのが、再審や否認事件における弁護士の異常に熱心な取り組みと主張です。

　忘れていたように思いますが、本項目の冒頭に掲載した東電の強制起訴のネットニュースは、「事通信 2月29日(月)12時27分配信」となっています。

　他に支流の一つとしてご紹介しておきたい裁判のことがあるので、配信時間を明示しました。配信時間と投稿時間が同じかどうかはわかりませんが、そう時間差のあるものとは考えられません。

　その前に、被害者AAさんの父親AKさんとの関係と手紙のことで少し書いておきたいと思います。記憶も薄らいでいるので、だいたいのことしか書けませんが、平成4年4月1日に出頭逮捕された事件で、初公判が同年6月18日、次回公判が6月30日だったと思います。

　本人尋問というのか裁判らしい審理があったのは6月30日の公判だけで、それで結審とされ、その場で同年8月3日の公判が判決だと裁判長に言われたように記憶しています。

　衝撃的だったのは6月30日の公判が始まってすぐ、江村正之検察官から意識不明の状態だった被害者AAさんの意識が回復したという話を聞かされたことです。絶望的な状態だったので、この時はじめて希望と精神的活力を取り戻したのですが、その日のうちに裁判の審理は終わってしまいました。

　刑事裁判の仕組みや流れなど全く知りませんでしたが、裁判のことより被害者AAさんの容体の回復と被害者AAさんの父親AKさんら家族の理解を得ることが重要で、その関門さえ突破できれば、道は開けるという思いがありました。

　それで被害者AAさんの自宅に手紙を送るようになったと記憶しています。数回、手紙を送ったところで、刑務官から「受取人拒絶」あるいは「受取人拒否」と大書きされた送った封筒を渡されるようになりました。

　その拒絶で返信された封筒は20通から30通になっていたかもしれません。かなりまとまった数になっていました。私はその全部を、金沢大学附属病院精神科の閉鎖病棟の通路にある一般家庭にあるのと同じ大型サイズのゴミ箱に捨てたことを憶えています。

　金沢大学附属病院での鑑定留置の精神鑑定は平成5年の3月1日から同月31日までの一ヶ月間でした。控訴審の私選弁護人となった木梨松嗣弁護士が初めて接見に来たのが平成4年の8月の18日頃。9月の下旬か10月に入ってから控訴審の初公判があったはずです。

　次回の公判は初公判の一月ぐらい後だったと思いますが、裁判長が濱田武律というような名前の裁判官から小島裕史裁判長に代わりました。初めて傍聴席で被害者AAさんの父親AKさんの姿を見たのも、この裁判長が交代した2回目の公判の時であったと思います。

　傍聴席でなくても被害者AAさんの父親AKさんの姿を見たのは初めてでしたが、被害者AAさんと顔立ちが似ていて、こちらを見る目も尋常ではなかったので、すぐに父親だとわかりました。その時は隣に被害者AAさんの兄と思える若者の姿もありました。

　公判が終わって、裏手の通路の方に連行されているとき、その兄が「本当に反省しとるんか」というような声を上げ、飛びかかってくるような行動に出たので、私はすぐに刑務官らの抱えられるように足早に外に出されたのです。

　兄の姿を見たのはその時だけでしたが、その後の公判にも被害者AAさんの父親AKさんの姿があって、全部ではなかったようにも思うのですが、平成5年9月7日の判決より前の最後の審理となった公判には、被害者AAさんの父親AKさんとともに母親と思われる人の姿がありました。

　裁判官の席から見ると当時の金沢地方裁判所の法廷は右側が庁舎の通路で、左側が一階の被告人の待機室のような部屋に通じる通路になっていました。他の法廷は見たこともないので比較も出来ませんが、よくある学校の通路のような広さがありました。

　裁判長の席から見て右手の奥が、傍聴席の出入り口でしたが、被害者AAさんの父親AKさんが母親と一緒に来た時は、その出入り口に近い一番奥の端の方の席に座っていました。なぜそんな場所を選んだのかも、私は気になっていましたが、答えはわかりません。

　被害者AAさんの父親AKさんが兄と一緒に来た時は、中央に近い、最前列ではなかったように思いますが、2つ目か3つ目の列に座っていたという場面が記憶にあります。

　言うまでもなく、一審の金沢地方裁判所の公判に被害者AAさんの父親AKさんの姿はありませんでした。被害者の家族が傍聴に来るかもしれないということも、当時の私には知識としてありませんでしたし、傍聴席があるとか傍聴人がいるということも考えが及びませんでした。

　どの公判の時も傍聴席の人の数はまばらだったと思いますが、被害者AAさんの父親AKさんが母親と来た控訴審の公判の時だけは、いくらか人の数が多いように感じたことを憶えています。

　9月7日の判決前の最後の公判ですが、日付が確認できずにいます。6月中であったように思うのですが、7月の20日頃だったような気もしないではありません。山口成良金沢大学教授が精神鑑定の証人として出たときの公判だったと思います。

　その時の公判以外には考えられないのですが、映画の場面のような印象的なシーンがありました。法廷内に時計があったかどうかも記憶にないですが、法廷に入った時点で小島裕史裁判長ら3人の裁判官が席に座っていたようにも思います。

　裁判官の大きな机にはうず高く積み上げられた書面が置いてありました。私が郵送で提出してきた上申書だと思いました。30センチから40センチ近くあったのかもしれません。ずいぶんと目立っていたことははっきりしています。

　小島裕史裁判長は自分の席の左手に書面を置いていたと記憶にあります。外の通路の窓側の位置で、ちょうどその書面をめがけるように、颯爽な姿で木梨松嗣弁護士が入ってきて弁護人の席に座りました。特別な演出をやっているようにしか見えませんでした。

　普通でなかったことは木梨松嗣弁護士が後ろに白衣を着た医師らしい人物を従えていたことです。法廷は私が入った時から和やかな雰囲気で、被害者AAさんの父親AKさんの母親は俯いてすすり泣く様子でしたが、それも殺伐としたものではなく、父親もそれまでになく落ち着いて見えました。

　小島裕史裁判長の態度が和やかで上機嫌に見えていたので、法廷全体の空気がそのように見えていたのだと思います。遅刻かどうかは時計も見ていないのでわかりませんが、その時だけは少し遅れて木梨松嗣弁護士が入ってきたのです。

　木梨松嗣弁護士が従えた白衣の人物は、拘置所や刑務所内の医務の刑務官の姿とよく見ていました。背が高くマサイ族のような体型であったような印象もあるのですが、病院で見る医師の姿とはどこか違いがあるように感じました。

　異様に映ったのは、小島裕史裁判長がやたらと上機嫌で、申し訳程度に木梨松嗣弁護士に声を掛けて、白衣の同行者のことを尋ねていましたが、木梨松嗣弁護士だけはやたらと緊張したような面持ちで、体調が優れないので、というような手短な返事をしていました。

　そのときの小島裕史裁判長の姿が忘れられないのですが、上機嫌というより満足そうに見えるぐらいで、私はなにがどうなっているのか気になって仕方がありませんでしたが、拘束中の身でもあるので、真相は知りようもないと諦めました。

　木梨松嗣弁護士が被害者AAさんの父親AKさんと打ち合わせをして何かやっているのかとも考えましたが、話し相手もいないので、どれもこれも自分の頭の中だけでの堂々巡りでした。そういう注意を引きつけられたことで、見逃すことになった部分もありそうです。

　平成5年9月7日の判決公判に被害者AAさんの父親AKさんの姿はありませんでした。普通に考えれば判決こそ関心が強いはずですし、裁判そのものに無関心であれば、それまでの傍聴もなかったと考えるのが自然です。

　私は法廷の外からそのような立場になったことがないのでわかりませんが、公判の期日というのは検察官の方から被害者の家族に知らせることがある、ということは何かの本で見かけた憶えがあります。

　私は今までずっと、被害者AAさんの父親AKさんはアドバイスを受けたにせよ、納得した自らの意思で判決公判に姿を見せなかったと考えていました。

　何度も書きますが控訴審の判決公判は平成5年9月7日で、その期日の指定は、不意打ちのように拘置所にいる私に舞い込んだものでした。それで刑務官らとももめることになり、怒鳴りつけられることにもなったのです。

　「参考資料扱いにした告訴状の下書き」の部分になると思いますが、大掛かりな上申書を作成途中であったこと、手紙や電報で何度も頼んでも、木梨松嗣弁護士は接見に来ず、連絡を一切返さなかったことなどのより詳しい経過を書いていると思います。

　残念なことにこの点を私が重視するようになったのも比較的最近のことです。以前は他のことに意識が向きがちで十分な検証をすることが出来ませんでした。

　今、あらためて考えると被害者AAさんの父親AKさんは控訴審の判決期日を知らないで過ごしていたのかもしれません。そういうことすら確認することの出来ない、被害者AAさんの父親AKさんとの関係だったのです。

　被害者AAさんの父親AKさんが事件や裁判に無関心だったとは考えられず、平成9年1月18日に私が福井刑務所を出所してからは、部長職である再就職の仕事先に電話連絡することを許してもらい、平成11年の6月ころには、PHSの電話番号まで教えられて、連絡をするようになったのです。

　言うまでもなく、そういう事実、事情の一切は、どの弁護士にも無視されました。かすりもさせないほどの対応でした。

　平成9年の8月ぐらいから月に一度、あるいは2,3回は連絡を入れていました。電話での連絡でしたが、被害者AAさんの父親AKさんはずいぶんと私との間に距離を置き、慎重にことを進めようとする意思を感じていました。

　電話だけではなく平成9年の9月の20日ころには、一度、直接あっています。金沢市内の中心部、香林坊のアトリオと言いましたか旧大和デパートですが、その前で待ち合わせをして、歩いてすぐ近くの中央公園の中のベンチで話をしました。

　石川県庁や石川県警察本部の建物のあったすぐ近くでもありますが、鞍月への移転前であったかどうかも、私には思い出せません。調べればすぐにわかることで、鞍月への移転の時期は前にもネットの検索で調べたことがありますが、すっかり忘れています。

石川県庁舎 - Wikipedia https://ja.wikipedia.org/wiki/%E7%9F%B3%E5%B7%9D%E7%9C%8C%E5%BA%81%E8%88%8E

　上記のページで確認しましたが、新庁舎の着工が平成11年11月で開庁が平成15年1月となっていました。建設中の鞍月の庁舎の建物を見た記憶がなかったのですが、平成11年8月12日に金沢中警察署に逮捕されているので、それもそうかと思いました。

　以上、ある程度のご理解に必要な程度の、私と被害者AAさんの父親AKさんの関係及び事実の経過は記述することが出来たと思います。大事なポイントは他にもいくつかありますし、一通りをなぞったわけでもありません。別の機会に書きたいと思います。

　23時56分です。買い物、夕食、銭湯と中断をしていました。Aコープ能都店では九州物語という半額になった駅弁と、580円だった輪島港というズワイガニを買ってきました。今まで見てきた中で一番安い値段とも思いましたが、カニはまだ少し動いている鮮度でした。

2016-03-05　土曜日　23：59　＜＜ ［［　←これまでの記述範囲の終了時刻］］＜＜



2016-03-06　日曜日　00：16　＞＞ ［［　←これからの記述範囲の開始時刻］］＞＞

　今、銭湯の脱衣場と家に戻ってから見た新・情報７daysニュースキャスターという番組を録画の早送りや巻き戻しをして確認したのですが、ニュースワードランキングというお馴染みのコーナーで1位が「認知症JR事故訴訟」となっています。

　何を基準にしたデータなのか今のところわかっていないのですが、「189万6262」というずいぶん大きな数字で1位になっています。

　先ほど2倍速ぐらいで録画を再生していましたが、認知症患者の家族に有利な最高裁判決が出て、ホッとしたという同じ問題を抱える人のとてもうれしそうな姿と声を紹介する場面がありました。1位の割に番組で取り上げた時間は短い感じでした。

　帰る前に銭湯の脱衣場で見た、水族館のラッコでラッコの生態などを紹介したコーナーの方が、ずいぶんと念入りで放送の時間も割いているように感じられました。なかなか特徴というかクセのある番組ではあります。

　弁護士の大々的な宣伝効果という意味では、久々のビッグニュースという今週の話題でした。最高裁判決なのでそれも当然かとは思っていましたが、同じ理屈の判断が適用されるケースがそれほど多いのかという疑問は感じていました。

　それと実に対照的な対極とも思える報道が今週にありました。日付が30分ほど前に変わって日曜日になっていますが、土日を週末、月曜日を週の初めということで、今週という言葉を使っています。

　3,4日前になると思いますが、曜日も思い出せないので、Twilogで調べる必要があります。その日は夜中の2時ぐらいという時間に目がさめて眠れないことになりました。コタツで寝ていて熱くなって目が覚めたのですが、明け方にはずいぶんと冷え込んできました。

　眠るのもあきらめて5時過ぎぐらいにテレビをつけたように思います。そのニュースを見たのは5時半ぐらいだったと思います。その後も6時台、7時台とテレビをつけてニュースの報道を見ていたのですが、何故か同じ報道はありませんでした。

　その報道のことはすぐにネットで調べて確認とTwitterでの記録をしています。2件ほどのネットのニュース記事でしたが、その後はテレビでもネットでも情報は一切、まったく目にしていません。

　怪奇現象と言っては大袈裟ですが、実に不可思議な体験でした。ネットのニュース記事で確認出来たのが精神的な安堵ですらありました。そうでなければ寝ぼけていたのかと自分自身の精神状態を疑いたくなるほどで、拘置所の独房で何度も経験させられた体験に似たものでした。

　調べて確認するのはこれからの作業です。私には検索でネットのニュースを調べて、それをツイートとして記録したという記憶しかありません。また、テレビの報道とネットの報道には違いがありました。それは前回に知った同じ問題の場面に連結するような偶然性があるものです。

　刑事裁判として歴史的と思える内容の報道でしたが、その報道については、少しだけ後回しにして、同じく偶然目にして知ることが出来た「認知症JR事故訴訟」に関する情報をご紹介しておきたいと思います。リツイートとして目にしましたが、リツイートのアカウントは思い出せません。

　元のツイートのアカウントの印象と注目度が強すぎたために、リツイートのアカウントのことが霞んでしまい、記憶に残らなかったのだと思います。元のツイートは「参考資料扱いにした過去の告訴状の下書き」で何度か取り上げた刑裁サイ太という匿名弁護士アカウントです。

　ブロックされていますが、深澤諭史弁護士と同じく参考となる有用な情報を得ることが多いアカウントです。刑事弁護の弁護士として独自の価値観や信念をお持ちの弁護士です。私とすれば病的な思考を有する存在で社会的害悪性も軽視できないと考えているのですが、病者の光学のような発見もあります。

　忘れかけていたコマンドを探しだして使い、次のように調べました。思ったより件数は多かったです。

NS:~/git/kk_hirono_2016
[9979]  % h-benngosi_tweet-mysql-opt.rb --clipboard_search
％uwaaaa（サイ太）のツイート％投稿日時％2016-03-03 00:04:00％ツイートのURL％ https://twitter.com/uwaaaa/status/705046174198181888 ％
％uwaaaa（サイ太）のツイートの内容％
認知症ＪＲ訴訟の第１審で「被害者の遺産は預貯金だけで５０００万円を下らなかった」という事実が認定されてるんですが、ここらへんが本件の陰のポイントですね。これがなければＪＲも提訴してなかったろうし、第１審からあさひ法律事務所もつかなかっただろうし。
％データベースへの登録日時％2016-03-03 08:22:38％

＞1961kumachin（中村元弥）のリツイート＞このリツイートの日時＞2016-03-03 05:22:00＞ URL＞ https://twitter.com/1961kumachin/status/705126050431283200 ＞
＞1961kumachin（中村元弥）＞のツイートとしてのリツイートの内容＞
RT @uwaaaa: 認知症ＪＲ訴訟の第１審で「被害者の遺産は預貯金だけで５０００万円を下らなかった」という事実が認定されてるんですが、ここらへんが本件の陰のポイントですね。これがなければＪＲも提訴してなかったろうし、第１審からあさひ法律事務所もつかなかっただろうし。
＞元のツイートの投稿日時＞2016-03-03 00:04:00＞元のツイートのURL＞ https://twitter.com/uwaaaa/status/705046174198181888
＞データベースへの登録日時＞2016-03-03 08:24:03＞

＞keita_adachi（弁護士あだちけいた）のリツイート＞このリツイートの日時＞2016-03-03 05:24:00＞ URL＞ https://twitter.com/keita_adachi/status/705126558814482432 ＞
＞keita_adachi（弁護士あだちけいた）＞のツイートとしてのリツイートの内容＞
RT @uwaaaa: 認知症ＪＲ訴訟の第１審で「被害者の遺産は預貯金だけで５０００万円を下らなかった」という事実が認定されてるんですが、ここらへんが本件の陰のポイントですね。これがなければＪＲも提訴してなかったろうし、第１審からあさひ法律事務所もつかなかっただろうし。
＞元のツイートの投稿日時＞2016-03-03 00:04:00＞元のツイートのURL＞ https://twitter.com/uwaaaa/status/705046174198181888
＞データベースへの登録日時＞2016-03-03 08:21:42＞

＞satoshihamada（弁護士　浜ちゃん）のリツイート＞このリツイートの日時＞2016-03-03 20:11:00＞ URL＞ https://twitter.com/satoshihamada/status/705349992706236416 ＞
＞satoshihamada（弁護士　浜ちゃん）＞のツイートとしてのリツイートの内容＞
RT @uwaaaa: 認知症ＪＲ訴訟の第１審で「被害者の遺産は預貯金だけで５０００万円を下らなかった」という事実が認定されてるんですが、ここらへんが本件の陰のポイントですね。これがなければＪＲも提訴してなかったろうし、第１審からあさひ法律事務所もつかなかっただろうし。
＞元のツイートの投稿日時＞2016-03-03 00:04:00＞元のツイートのURL＞ https://twitter.com/uwaaaa/status/705046174198181888
＞データベースへの登録日時＞2016-03-03 21:46:05＞

SELECT * FROM tw_user_timeline WHERE  `tweet` LIKE '%「被害者の遺産は預貯金だけで５０００万円を下らなかった」%' ORDER BY tw_date ASC ;

　上記の通り、弁護士アカウントのリツイートは3件ですが、ブロックされていることを確認しておらず、今のところブロックの可能性は低いと考えているのは、元裁判官でもある旭川の中村元弥弁護士だけです。

　ブロックされていない弁護士アカウントは注目度が低くなるということもあるのですが、中村元弥弁護士のTwitterのタイムラインを開くことは少ないです。それでも時たま見ることがあって、ツイート数も多いほうだと思いますが、いわゆるリア充で愛妻家という印象が強い弁護士です。

　実際、他の弁護士とは違って、生活面でも余裕のある状態で悠々自適のような、弁護士活動をなされているという珍しく特異な存在とも思える弁護士です。とりわけて北海道の過疎地を例にした娘の売春や身売りにまで言及した小倉秀夫弁護士の一連のツイートとは極めて対蹠的です。

　おそらくは常人の想像を絶する理解困難な小倉秀夫弁護士の発言ツイートです。小倉秀夫弁護士の特異性に慣れている人には、またかという感じかとも思いますが、ちょっと探して一例を挙げておきたいと思います。

　関連するキーワードは「過疎地」や「離島」です。初めてになるかと思いますが、「売春」をキーワードに小倉秀夫弁護士のツイートをまとめておきたいと思います。

　「売春」をキーワードにしてデータベースに追加の作業をしましたが、ざっとみたところ9割ぐらいは新規の追加でした。弁護士での組み合わせでも新規の追加がいくつかあって、思った以上の取りこぼしというか見落としが記録の作業にあったことを確認しました。

　作業を完了し、次のブログ記事としてまとめました。

参考資料：　「売春」をキーワードに含む「小倉秀夫弁護士（@Hideo_Ogura）」のツイート・リツイート（2010-04-19 16:11〜2016-01-22 10:21）「100」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/03/hideo_ogura2010.html

　ちょうど100件というのは驚きましたが、たぶんまとめの作業として初めてのことだと思います。とりあえず1件だけ適当にみつくろって掲載し、ご紹介しておきます。もっと重要な論点や事実経過がある事柄なので、別途独立した項目して後日取り上げたいと思います。

［Hideo_Ogura__20160306_0130_34／100のツイート］
％Hideo_Ogura（小倉秀夫）のツイート％投稿日時％2013-11-04 00:59:00％ツイートのURL％ https://twitter.com/Hideo_Ogura/status/397030256625737728 ％
％Hideo_Ogura（小倉秀夫）のツイートの内容％
つまり、北海道の過疎地に赴任することを義務づけられた弁護士は、おとなしく餓死すればいいと言うことでしょ？RT @rocket_bean: @Hideo_Ogura そこじゃないから問題点は。あなたが「娘を売春させる」と言った事が信用を失墜させたと言っているんです。
％データベースへの登録日時％2016-03-06 01:25:49％

　売春に関わる問題は韓国の慰安婦問題を含めた小倉秀夫弁護士独自の歴史認識に関連したテーマでもあります。弁護士にありがちな傾向性を、小倉秀夫弁護士がクローズアップしてくれているという一面もあって、小倉秀夫弁護士がまるで神様のお使いと見えることさえあるぐらいです。

2016-03-07　月曜日　11：25　＜＜ ［［　←これまでの記述範囲の終了時刻］］＜＜



2016-03-07　月曜日　11：26　＞＞ ［［　←これからの記述範囲の開始時刻］］＞＞

　しばらく中断をしていましたが、中断する前から決めていた内容で再開したいと思います。それは「舞鶴女子高校生殺害事件」のことです。

　事前の用意というのはほぼ毎日やっている作業です。Twitterのまとめとしてブログの記事にしていることがその一つですが、次のブログ記事から2つのツイートをご紹介します。

参考資料：　「舞鶴」をキーワードに含む（法クラ・弁護士・ジャーナリスト関連）のツイート・リツイート（16アカウント、30件、 2014-08-14 19:58〜2016-03-01 06:33）「30」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/03/1630-2014-08-14.html

［hirono_hideki__20160303_1600_29／30のツイート］
％hirono_hideki（廣野秀樹＼さらば弁護士鉄道・泥棒神社の夜）のツイート％投稿日時％2016-03-01 06:33:00％ツイートのURL％ https://twitter.com/hirono_hideki/status/704419266104262656 ％
％hirono_hideki（廣野秀樹＼さらば弁護士鉄道・泥棒神社の夜）のツイートの内容％
殺人未遂で懲役２５年求刑、大阪　舞鶴事件無罪確定の男 https://t.co/gHYWU7SRpP
％データベースへの登録日時％2016-03-03 15:59:22％

［hirono_hideki__20160303_1600_30／30のツイート］
％hirono_hideki（廣野秀樹＼さらば弁護士鉄道・泥棒神社の夜）のツイート％投稿日時％2016-03-01 06:35:00％ツイートのURL％ https://twitter.com/hirono_hideki/status/704419658250715137 ％
％hirono_hideki（廣野秀樹＼さらば弁護士鉄道・泥棒神社の夜）のツイートの内容％
知人女性殺人未遂で懲役２５年求刑　舞鶴事件無罪確定の中被告 https://t.co/CKfYI6AgZS
％データベースへの登録日時％2016-03-03 15:59:12％

　懲役25年の求刑というニュースは、弁護士や法クラで取り上げたものを確認していません。珍しいことではないのですが、そんな時でも大阪でわいせつ事件の刑事弁護を専門的に取り扱っているという奥村徹弁護士だけは、データベース的にツイートしていることが多かったです。

　法クラからの情報を得られなかったので私自身のツイートを登録し、ネットニュースのリンクを探し出せるようにしました。私のツイートは3月1日の朝6時半ころになっていますが、データベースへの登録時刻は3月3日の15時59分になっています。

　今、奥村徹弁護士のTwitterのタイムラインを遡って、舞鶴女子高校生殺害事件に関するものがないか調べていたのですが、まったくそれらしいものは見つからず、2月29日の見覚えのある次のツイートまで到達しました。

％okumuraosaka（TORU OKUMURA）のツイート％投稿日時％2016-03-01 05:10:00％ツイートのURL％ https://twitter.com/okumuraosaka/status/704398286073901057 ％
％okumuraosaka（TORU OKUMURA）のツイートの内容％
海渡雄一弁護士は同日昼、指定弁護士の石田省三郎弁護士から起訴状を受け取り、「すごい証拠がある。（有罪で）いけると思う」東電強制起訴：告訴団「公正な判決を信じている」 - 毎日新聞 https://t.co/FZ1EQvMIoP
％データベースへの登録日時％2016-03-01 13:53:03％

　念を入れて2月27日の次のツイートのあたりまでタイムラインを遡りました。

T：okumuraosaka（TORU OKUMURA）：2016/02/27 18:23： https://twitter.com/okumuraosaka/status/703510711939387393 ： 悪徳弁護士続々　必要な資質や矜持をベテラン弁護士が語る|ガジェット通信  https://t.co/k5oPj9z1Il @getnewsfeedさんから

T：okumuraosaka（TORU OKUMURA）：2016/02/27 18:17： https://twitter.com/okumuraosaka/status/703509215613030401 ： 逮捕歴「忘れられる権利」認める　ネットの検索結果削除、国内初 | 2016/2/27 - 共同通信 47NEWS https://t.co/wle1KqrQIG

　上記のツイートの情報は「k-line--api-twitter.rb」というスクリプトを使っています。-cというオプションを使うとクリップボードに保存したツイートのURLから遡って10件のツイートを上記の書式を適用して取得します。

　-uオプションを指定するとツイートのURLからアカウント名を取り出し、そのアカウントの最新のツイート10件を取得します。--countというオプションも作ってあって1から200件まで指定できるかと思います。

　ほとんど使っていませんがオフセットの指定も出来たかと思います。TwitterのAPIの仕様では16のオフセットを使えるという情報もあったのですが、当初は16で問題なかったものの最近は14ぐらいにしておかないとツイートが取得できないことがあります。

　一度で取得できるツイートが200件で指定できるオフセットが16だと最大3200件ということになります。別のスクリプトでこれをよく使っていたことがあるのですが、3200件というのはなく、3000から3100台で不定の数の取得数になっていました。

　これはTwitterAPIのtimelineというメソッドを使ったツイートの取得方法です。searchのような検索用のメソッドもあったかと思いますが、取得できる範囲に同じような制限があって、実用的でもないので最近は使っていません。

　奥村徹弁護士のTwitterアカウントは、昔、岡口基一裁判官がやっていた「ボツネタ」というブログにかなり似ています。事件事故裁判の速報リンク集のような運営スタイルです。

　見つかりにくいような情報も多数含まれています。今回もたくさんの発見がありました。有用な情報源でもありますが、私が奥村徹弁護士のタイムラインを開くことは多くありません。忘れた頃に開いたり、ブラウザのタブとして開いているときは観ているという感じでした。

　今日は朝早くというか夜中に近い事件に暑くて目がさめ、眠れずに起きていました。その早朝の時間帯に次のツイートのまとめを作成しました。ブログの記事としてのご紹介ですが、同じ内容はテキストファイルとして添付するDVDの記憶媒体に収録する予定です。

参考資料：　深澤諭史弁護士（@fukazawas）のツイート・リツイート（146件、 2016-03-01 18:52〜2016-03-07 00:04：2016-03-07の記録）「1-100／146」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/03/fukazawas146-20.html
参考資料：　深澤諭史弁護士（@fukazawas）のツイート・リツイート（146件、 2016-03-01 18:52〜2016-03-07 00:04：2016-03-07の記録）「101-146／146」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/03/fukazawas146--1.html
参考資料：　モトケンこと矢部善朗弁護士（京都弁護士会）（@motoken_tw）のツイート・リツイート（123件、 2016-03-04 20:18〜2016-03-07 00:16：2016-03-07の記録）「1-100／123」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/03/motoken_tw123-2.html
参考資料：　モトケンこと矢部善朗弁護士（京都弁護士会）（@motoken_tw）のツイート・リツイート（123件、 2016-03-04 20:18〜2016-03-07 00:16：2016-03-07の記録）「101-123／123」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/03/motoken_tw123-1.html
参考資料：　小倉秀夫弁護士（@Hideo_Ogura）のツイート・リツイート（302件、 2016-03-02 10:35〜2016-03-07 02:24：2016-03-07の記録）「1-100／302」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/03/hideo_ogura302-.html
参考資料：　小倉秀夫弁護士（@Hideo_Ogura）のツイート・リツイート（302件、 2016-03-02 10:35〜2016-03-07 02:24：2016-03-07の記録）「101-200／302」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/03/hideo_ogura30-1.html
参考資料：　小倉秀夫弁護士（@Hideo_Ogura）のツイート・リツイート（302件、 2016-03-02 10:35〜2016-03-07 02:24：2016-03-07の記録）「201-300／302」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/03/hideo_ogura30-2.html
参考資料：　小倉秀夫弁護士（@Hideo_Ogura）のツイート・リツイート（302件、 2016-03-02 10:35〜2016-03-07 02:24：2016-03-07の記録）「301-302／302」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/03/hideo_ogura30-3.html
参考資料：　刑裁サイ太（匿名弁護士）（@uwaaaa）のツイート・リツイート（988件、 2010-02-24 13:52〜2016-03-04 21:04：2016-03-07の記録）「1-100／988」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/03/uwaaaa988-2010-.html
参考資料：　刑裁サイ太（匿名弁護士）（@uwaaaa）のツイート・リツイート（988件、 2010-02-24 13:52〜2016-03-04 21:04：2016-03-07の記録）「101-200／988」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/03/uwaaaa988-201-1.html
参考資料：　刑裁サイ太（匿名弁護士）（@uwaaaa）のツイート・リツイート（988件、 2010-02-24 13:52〜2016-03-04 21:04：2016-03-07の記録）「201-300／988」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/03/uwaaaa988-201-2.html
参考資料：　刑裁サイ太（匿名弁護士）（@uwaaaa）のツイート・リツイート（988件、 2010-02-24 13:52〜2016-03-04 21:04：2016-03-07の記録）「301-400／988」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/03/uwaaaa988-201-3.html
参考資料：　刑裁サイ太（匿名弁護士）（@uwaaaa）のツイート・リツイート（988件、 2010-02-24 13:52〜2016-03-04 21:04：2016-03-07の記録）「401-500／988」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/03/uwaaaa988-201-4.html
参考資料：　刑裁サイ太（匿名弁護士）（@uwaaaa）のツイート・リツイート（988件、 2010-02-24 13:52〜2016-03-04 21:04：2016-03-07の記録）「501-600／988」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/03/uwaaaa988-201-5.html
参考資料：　刑裁サイ太（匿名弁護士）（@uwaaaa）のツイート・リツイート（988件、 2010-02-24 13:52〜2016-03-04 21:04：2016-03-07の記録）「601-600／988」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/03/uwaaaa988-201-6.html
参考資料：　刑裁サイ太（匿名弁護士）（@uwaaaa）のツイート・リツイート（988件、 2010-02-24 13:52〜2016-03-04 21:04：2016-03-07の記録）「701-800／988」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/03/uwaaaa988-201-7.html
参考資料：　刑裁サイ太（匿名弁護士）（@uwaaaa）のツイート・リツイート（988件、 2010-02-24 13:52〜2016-03-04 21:04：2016-03-07の記録）「801-900／988」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/03/uwaaaa988-201-8.html
参考資料：　刑裁サイ太（匿名弁護士）（@uwaaaa）のツイート・リツイート（988件、 2010-02-24 13:52〜2016-03-04 21:04：2016-03-07の記録）「901-988／988」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/03/uwaaaa988-201-9.html

　刑裁サイ太についてまとめておこうと思ったのは小倉秀夫弁護士と共通していますが、「国選弁護」の制度の現状に対する資料としての価値が高いということです。肯定的な意味での価値ではなく、客観的な資料としての価値です。

　作業の終盤でしょうか「旗幟鮮明」という言葉を想い出しました。それはTwitterのプロフィールの名前やカバー写真の画像に文字情報を含めて表明しております。

　奥村徹弁護士のことで久しぶりに思い出したのですが、データベース登録済みか今から調べてみたいと思います。

精神鑑定ってさあ、とっぽどおかしい場合じゃないと採用されない。／（TORU OKUMURA） | 告発-金沢地方検察庁御中_2015 http://bit.ly/1TCSPMa

　上記の検索で見つけたページからツイートのURLを得て調べたところ、すでに登録済みのようでした。

　次のようにデータベースで奥村徹弁護士のついて調べてみました。

[9958]  % mysql -u root benngosi_twitter -e 'SELECT user FROM tw_user_timeline ORDER BY user ASC\G'|grep okumuraosaka|wc -l
9279

　上記は自動登録用のtw_user_timelineというテーブルのデータです。9279件となっています。最初は先ほどご説明に触れたオフセットを使って3200件に近いツイートを登録したように思います。

　次はtw_user_tweetというテーブルで同じように調べてみました。702件となっていて、これだと取り扱いに問題のない数かと思います。

[9959]  % mysql -u root benngosi_twitter -e 'SELECT user FROM tw_user_tweet ORDER BY user ASC\G'|grep okumuraosaka|wc -l
702

　昨年中の「参考資料扱いにした過去の告訴状の下書き」には何度かご説明を書いていると思いますが、 tw_user_tweetというテーブルは基本的に、内容を読んだ上で記録の必要を判断し登録したツイートです。

　昨日あたりにもご説明を書いたように思いますが、最近はこの原則が崩れつつあります。深澤諭史弁護士とモトケンこと矢部善朗弁護士（京都弁護士会）、小倉秀夫弁護士のツイートは全件を記録するようにしました。

　作業としてはアカウント名（例：motoken_tw）を含んだツイートのURLをクリップボードに保存してから次のコマンドを実行しています。元は3つのコマンドを一つずつ実行していましたが、コマンドをつなげて一つのコマンドで実行するようになりました。

[9952]  % k-line--api-twitter.rb -u --count=40 > t && cat t |sed -ne 's%^[T：|R：].*[：|＞][0-9]\{4\}/../.. ..:..[：|＞] \(https://twitter\.com[^ ]\+\) [：|＞].*%\1%p' > l && for i in `cat l`; do k4-tweet-add-mysql-uniq-argv.rb $i; done

　元となるのはk-line--api-twitter.rb -u --count=40 > tというコマンドです。先ほどご説明したところ思いますが、ここでは40件の取得件数を指定しています。

　スクリプトではTwitterAPIからデータ取得する前に、データベースにツイートのURLが存在しないか確認しています。存在した場合は「既にデータが存在します。」というメッセージを出してAPIの処理をスキップするようにしています。

　奥村徹弁護士は性犯罪事件での被害者やその家族との示談交渉も多く手がけている様子で、過去にはとても考えさせられたり、衝撃的な内容の発言をツイートとしてやっていました。最近はそういう主観的な考えを述べるツイートは減っているような印象も受けています。

　昼食もまだですが、奥村徹弁護士のツイートも参考資料としての正確性を担保するため記録保存をしておこうと思います。

[9958]  % bin/tw_user_tweet-sql-search-make-text-html.rb --full_sql="SELECT * FROM tw_user_tweet WHERE tw_date BETWEEN '1016-03-02 10:35' AND '3016-02-24' AND (user LIKE \"okumuraosaka\") ORDER BY tw_date ASC"|xsel -b

　上記のコマンドを実行しました。1016年から3016年というありえない期間を指定していますが、全件取得するための指定です。

　ブログに投稿してから一つずつ記事を開き、ページを開いた状態ではてなブックマークに登録していました。Twitterへの投稿を設定していて、長すぎる文字列をツイートの文字数の制限内にまとめてくれるので重宝しています。そのツイートとして掲載します。

T：hirono_hideki（廣野秀樹＼さらば弁護士鉄道・泥棒神社の夜）：2016/03/07 13:56： https://twitter.com/hirono_hideki/status/706705021681799169 ： “参考資料：　TORU OKUMURA（@okumuraosaka）のツイート・リツイート（702件、 2009-09-04 17:55〜2016-03-06 23:31：2016-03-07の記録）「70…” https://t.co/ojQXpGjjI6 #ココログ／金沢地検

T：hirono_hideki（廣野秀樹＼さらば弁護士鉄道・泥棒神社の夜）：2016/03/07 13:55： https://twitter.com/hirono_hideki/status/706704830006325249 ： “参考資料：　TORU OKUMURA（@okumuraosaka）のツイート・リツイート（702件、 2009-09-04 17:55〜2016-03-06 23:31：2016-03-07の記録）「60…” https://t.co/nojbiQBoCH #ココログ／金沢地検

T：hirono_hideki（廣野秀樹＼さらば弁護士鉄道・泥棒神社の夜）：2016/03/07 13:54： https://twitter.com/hirono_hideki/status/706704640264372225 ： “参考資料：　TORU OKUMURA（@okumuraosaka）のツイート・リツイート（702件、 2009-09-04 17:55〜2016-03-06 23:31：2016-03-07の記録）「50…” https://t.co/R6iQUAyiFl #ココログ／金沢地検

T：hirono_hideki（廣野秀樹＼さらば弁護士鉄道・泥棒神社の夜）：2016/03/07 13:53： https://twitter.com/hirono_hideki/status/706704388539068416 ： “参考資料：　TORU OKUMURA（@okumuraosaka）のツイート・リツイート（702件、 2009-09-04 17:55〜2016-03-06 23:31：2016-03-07の記録）「40…” https://t.co/wNa4259Xhr #ココログ／金沢地検

T：hirono_hideki（廣野秀樹＼さらば弁護士鉄道・泥棒神社の夜）：2016/03/07 13:52： https://twitter.com/hirono_hideki/status/706704155268616192 ： “参考資料：　TORU OKUMURA（@okumuraosaka）のツイート・リツイート（702件、 2009-09-04 17:55〜2016-03-06 23:31：2016-03-07の記録）「30…” https://t.co/pkHalWXP0J #ココログ／金沢地検

T：hirono_hideki（廣野秀樹＼さらば弁護士鉄道・泥棒神社の夜）：2016/03/07 13:52： https://twitter.com/hirono_hideki/status/706704039904284673 ： “参考資料：　TORU OKUMURA（@okumuraosaka）のツイート・リツイート（702件、 2009-09-04 17:55〜2016-03-06 23:31：2016-03-07の記録）「20…” https://t.co/9nSLGdoW2m #ココログ／金沢地検

T：hirono_hideki（廣野秀樹＼さらば弁護士鉄道・泥棒神社の夜）：2016/03/07 13:51： https://twitter.com/hirono_hideki/status/706703912183529473 ： “参考資料：　TORU OKUMURA（@okumuraosaka）のツイート・リツイート（702件、 2009-09-04 17:55〜2016-03-06 23:31：2016-03-07の記録）「10…” https://t.co/89eq8JdIVK #ココログ／金沢地検

T：hirono_hideki（廣野秀樹＼さらば弁護士鉄道・泥棒神社の夜）：2016/03/07 13:51： https://twitter.com/hirono_hideki/status/706703741714497536 ： “参考資料：　TORU OKUMURA（@okumuraosaka）のツイート・リツイート（702件、 2009-09-04 17:55〜2016-03-06 23:31：2016-03-07の記録）「1-…” https://t.co/90zHuoilWy #ココログ／金沢地検

　これではわかりづらくもあるので、やはりこれまでどおり、ブログのタイトルとURLを掲載しておきます。

参考資料：　TORU OKUMURA（@okumuraosaka）のツイート・リツイート（702件、 2009-09-04 17:55〜2016-03-06 23:31：2016-03-07の記録）「1-100／702」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/03/toru-okumuraoku.html
参考資料：　TORU OKUMURA（@okumuraosaka）のツイート・リツイート（702件、 2009-09-04 17:55〜2016-03-06 23:31：2016-03-07の記録）「101-200／702」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/03/toru-okumurao-1.html
参考資料：　TORU OKUMURA（@okumuraosaka）のツイート・リツイート（702件、 2009-09-04 17:55〜2016-03-06 23:31：2016-03-07の記録）「201-300／702」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/03/toru-okumurao-2.html
参考資料：　TORU OKUMURA（@okumuraosaka）のツイート・リツイート（702件、 2009-09-04 17:55〜2016-03-06 23:31：2016-03-07の記録）「301-400／702」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/03/toru-okumurao-3.html
参考資料：　TORU OKUMURA（@okumuraosaka）のツイート・リツイート（702件、 2009-09-04 17:55〜2016-03-06 23:31：2016-03-07の記録）「401-500／702」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/03/toru-okumurao-4.html
参考資料：　TORU OKUMURA（@okumuraosaka）のツイート・リツイート（702件、 2009-09-04 17:55〜2016-03-06 23:31：2016-03-07の記録）「501-600／702」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/03/toru-okumurao-5.html
参考資料：　TORU OKUMURA（@okumuraosaka）のツイート・リツイート（702件、 2009-09-04 17:55〜2016-03-06 23:31：2016-03-07の記録）「601-600／702」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/03/toru-okumurao-6.html
参考資料：　TORU OKUMURA（@okumuraosaka）のツイート・リツイート（702件、 2009-09-04 17:55〜2016-03-06 23:31：2016-03-07の記録）「701-702／702」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/03/toru-okumurao-7.html

　ちょっと迷ったのですがTORU OKUMURAという奥村徹弁護士のTwitterのプロフィールの名前をそのまま使いました。重要度の高いアカウントはスクリプトの処理で、もっとわかりやすい特定した名前に変換しています。

　次がスクリプトというかプログラムで処理をしている部分です。

    $sname = u.screen_name
    case $sname
    when "motoken_tw" then
        $name = "モトケンこと矢部善朗弁護士（京都弁護士会）"
    when "yjochi" then
        $name = "落合洋司弁護士（東京弁護士会）"
    when "fukazawas" then
        $name = "深澤諭史弁護士"
    when "Hideo_Ogura" then
        $name = "小倉秀夫弁護士"
    when "uwaaaa" then
        $name = "刑裁サイ太（匿名弁護士）"
    when "lawkus" then
        $name = "ローカスこと実質実名弁護士"
    when "amneris84" then
        $name = "ジャーナリストの江川紹子さん"
    when "nobuogohara" then
        $name = "郷原信郎弁護士"
    end

　それでは次に、奥村徹弁護士の精神鑑定に関するツイートを探しだしてご紹介したいと思います。たぶん、というか余り記憶に自信は持てないですが、「参考資料扱いにした過去の告訴状の下書き」には取り上げているかもしれません。それを探してみるのも目的です。

［okumuraosaka__20160307_1340_69／702のツイート］
％okumuraosaka（TORU OKUMURA）のツイート％投稿日時％2011-05-28 14:15:00％ツイートのURL％ https://twitter.com/okumuraosaka/status/74342961147674624 ％
％okumuraosaka（TORU OKUMURA）のツイートの内容％
精神鑑定ってさあ、とっぽどおかしい場合じゃないと採用されない。
％データベースへの登録日時％2015-10-07 20:59:43％

　DVDに収録予定のディレクトリ（ファルダ）は、今年つまり2016年になってからkk_hirono_2016というものにしました。それ以前は「kk_hirono」です。まずは現在の作業環境で調べてみます。

[9968]  % grep -r 'とっぽどおかしい' ./*
./kokuso_2016.org:精神鑑定ってさあ、とっぽどおかしい場合じゃないと採用されない。／（TORU OKUMURA） | 告発-金沢地方検察庁御中_2015 http://bit.ly/1TCSPMa
./kokuso_2016.org:精神鑑定ってさあ、とっぽどおかしい場合じゃないと採用されない。
./tweet-text_html_6.org:精神鑑定ってさあ、とっぽどおかしい場合じゃないと採用されない。
./tweet-text_html_6.org:<blockquote class="twitter-tweet" lang="ja"><p>精神鑑定ってさあ、とっぽどおかしい場合じゃないと採用されない。</p>&mdash; TORU OKUMURA（okumuraosaka）<a href="https://twitter.com/okumuraosaka/status/74342961147674624">2011-05-28 14:15:00</a></blockquote>

　次は過去の作業環境にディレクトリを移動して同じコマンドを実行しました。

[9971]  % grep -r 'とっぽどおかしい' ./*.org
./index.org:RT @okumuraosaka: 精神鑑定ってさあ、とっぽどおかしい場合じゃないと採用されない。
./index.org:これは貴重なご意見です。再審請求の資料として援用させてもらいます。http://ow.ly/54Zy3 こちらが対象です。→http://ow.ly/i/caaq 四苦八苦です。  RT @okumuraosaka: 精神鑑定ってさあ、とっぽどおかしい場合じゃないと採用されない。
./index.org:精神鑑定ってさあ、とっぽどおかしい場合じゃないと採用されない。 http://s-hirono.blogspot.jp/2011/11/blog-post_5883.html
./index.org:さきほどご紹介した奥村徹弁護士の「精神鑑定ってさあ、とっぽどおかしい場合じゃないと採用されない。」という発言に通じるところがありますが、それが弁護士の刑事裁判の専門家としての見方なのでしょう。

　拡張子がorgというファイル名に対象を限定しました。すべてのファイルを対象にするとものすごい数のヒットで、端末の画面が文字列で埋め尽くされました。

　grepコマンドはUNIX環境でスタンダードな文字列検索のコマンドです。定番なのでオプションも豊富です。普通に使うとマッチした文字列がある一行だけが表示されます。前後の行数も合わせて表示するオプションがあります。たまにしか使わないので、ちょっと調べます。

　「grep --help」で調べました。普通は「-h」でもいけるはずですが、--helpにしてくれとメッセージが出ていました。この手のコマンドのヘルプオプションは英語表記が多いのですが、日本語になっていました。アップデートで変わったのかもしれません。

前後の表示に関する制御:
  -B, --before-context=NUM  一致した前の NUM 行を表示する
  -A, --after-context=NUM   一致した後の NUM 行を表示する
  -C, --context=NUM         一致した前後 NUM 行を表示する

　-Cというオプションは初めて見たもので使ったことがない気がします。コマンドのオプションは、これまでネット検索で調べることが多く、理由は英語ばかりだとわかりづらく探しにくかったからです。

　さっそくですが、-Cオプションを使ってみたいと思います。

　検索結果をテキストで貼り付けても、何をやっているかわかりづらくなっているので、コマンドを実行した端末の画面をスクリーンショットとしてご紹介したいと思います。

投稿者：s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2016-03-07 14:48  ツイート： https://twitter.com/s_hirono/status/706718113014788097
2016-03-07-144817_％　grep　-r　-C　2　’とっぽどおかしい’　。／＊。org.jpg https://t.co/IGYe0nXqit

　簡単に昼食を済ませていましたが、その間に「懲役25年 舞鶴」でTwitter検索をやってみることが頭に浮かんできました。実行したものをスクリーンショットにしたところですが、思ったより数が少なく、3枚のスクリーンショットで事足りました。

投稿者：s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2016-03-07 15:17  ツイート： https://twitter.com/s_hirono/status/706725495962906625
2016-03-07-151738_懲役25年　舞鶴　-　Twitter検索.jpg https://t.co/2WRLUybB9z

投稿者：s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2016-03-07 15:17  ツイート： https://twitter.com/s_hirono/status/706725422126333952
2016-03-07-151721_懲役25年　舞鶴　-　Twitter検索.jpg https://t.co/MbXJ8KMMyw

投稿者：s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2016-03-07 15:17  ツイート： https://twitter.com/s_hirono/status/706725345232195584
2016-03-07-151702_懲役25年　舞鶴　-　Twitter検索.jpg https://t.co/o65K4aQLXZ

　次は舞鶴女子高校生殺害事件に関する奥村徹弁護士のツイートのスクリーンショットです。

投稿者：s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2016-03-07 15:26  ツイート： https://twitter.com/s_hirono/status/706727800720347136
2016-03-07-152648_TORU　OKUMURAさんはTwitterを使っています：　”最高裁第一小法廷平26。7。8決定　舞鶴女子高校生殺害事件　女子高校生に強い.jpg https://t.co/PtzgUcHETJ

　ツイートはWebページのタイトルとして取得したものを次に掲載します。

TORU OKUMURAさんはTwitterを使っています: "最高裁第一小法廷平26.7.8決定 舞鶴女子高校生殺害事件 女子高校生に強いてわいせつな行為をして殺害したとして起訴された事案につき" https://twitter.com/okumuraosaka/status/558404561950347265

　このツイートもデータベースへの登録を忘れていました。さきほど登録を実行したところ登録に成功したので、新規の登録だったことになります。

　この奥村徹弁護士のツイートはその内容より登録日時に注目したいです。スクリーンショットで確認できると思いますが「15:23 - 2015年1月22日」となっています。

　上記の奥村徹のツイートは私の見当違いでした。私のTwilogで符合する情報のツイートを探したところ一致するものがなく、別の日付のツイートして見つけることができました。次のツイートです。

廣野秀樹＼さらば弁護士鉄道・泥棒神社の夜さんはTwitterを使っています: "東京新聞:大阪、わいせつ致傷罪に変更へ　女性刺傷事件:社会(TOKYO Web) http://t.co/DVyu3tukB5 中被告は京都府舞鶴市の女子高生殺害事件で逮捕、起訴され、今年７月に無罪が確定した。" https://twitter.com/hirono_hideki/status/542309283531325440

　ニュース記事はリンク切れになっていました。

　再び「"舞鶴" from:okumuraosaka - Twitter検索 http://bit.ly/1OXe82S 」で調べたのですが、「5:26 - 2014年12月9日」に近接するツイートはありませんでした。

　私の記憶では奥村徹弁護士のTwitterのタイムラインで舞鶴女子高校生殺害事件の過去の判例情報のようなツイートが目に入り、気になって舞鶴女子高校生殺害事件をGoogle検索で調べたところ、「わいせつ」で追起訴されたような情報を発見したのです。

　スクリプトを修正というか機能を追加しました。

[9956]  % k-line--api-twitter.rb -y
ツイート：hirono_hideki（廣野秀樹＼さらば弁護士鉄道・泥棒神社の夜）：2014/12/09 22:26： https://twitter.com/hirono_hideki/status/542309283531325440 ： 東京新聞:大阪、わいせつ致傷罪に変更へ　女性刺傷事件:社会(TOKYO Web) http://t.co/DVyu3tukB5 中被告は京都府舞鶴市の女子高生殺害事件で逮捕、起訴され、今年７月に無罪が確定した。

　これで3200件より前の過去のツイートも投稿日を含めた情報でツイートの取得が出来るようになりました。2014年12月9日の投稿日になっています。

　16時23分になっていますが、今になってテレビのドラマ「白い巨塔」のことを思い出してチャンネルを変えました。録画予約を入れておくことも考えていたのですが、すっかりと忘れていました。

　テレビに「大阪市医師会館」というような看板が出てきました。「白い巨塔」のドラマの舞台が大阪だったとは意外で、大阪弁というのも聴いていない気がします。

　リメイクされた唐沢さんが財前教授役の白い巨塔の撮影、放映時期についてまだ医師と弁護士が最高峰のようなステータスの時代であったかもしれないと考えていたのですが、唐沢さんが携帯電話を手にする場面が出てきました。

　そういえば西田敏行のやっている役柄は大阪弁でした。もう一人の地位の高そうな人物も大阪弁でした。料亭の座敷のような場面でした。その後は、法律事務所での相談の場面で、無理だと軽く言われながら1万円の請求を受けていました。

　財前教授の総回診という場面が出てきました。1回や2回の場面ではなかったのかもしれません。訴訟委任状が出てきました。「関口」という弁護士の名前が見えました。

　リメイクされた白い巨塔について、ちょっと調べておきたいと思います。医療裁判のことはモトケンこと矢部善朗弁護士（京都弁護士会）と小倉秀夫弁護士の間でも論争のようになっていたことがあり、深澤諭史弁護士の医療に対する見方、考え方にも特異なものを感じています。

／ ********************（引用開始）********************
引用URL＞＞＞＞：http://bit.ly/1nqGWu4 白い巨塔 (2003年のテレビドラマ) - Wikipedia

山崎豊子原作の同名小説4度目のテレビドラマ化。近年のプライム枠の連続ドラマとしては珍しい半年間放送の大河ドラマ形式で、2003年10月9日から12月11日まで第一部が放送され、2004年1月8日から3月18日までは第二部が放送された。全21回（第一部全10回、第二部全11回）。本編総時間は約18時間45分で、DVDおよびVHSソフト化されている。

最終回の翌週の3月25日には特別編として、これまでのダイジェストと柳原弘のその後が描かれた。

また、2004年12月17日、12月24日、12月30日には3週連続で白い巨塔アンコール（総集編）が放送された。 その後BSフジやフジテレビCSHD、地上波「チャンネルα」（2009年10月-11月）、同「ドラマチックα」（2014年1月）で本来の姿といえるハイビジョン放送が行われた。また、フジテレビ721でも16：9レターボックス（画角情報は4：3）で再放送された。

原作での時代設定は1960年代となっているが、本作での時代設定では現代（放送当時の2003年）に置き換えている。

 ********************（引用終了）********************／

／ ********************（引用開始）********************
引用URL＞＞＞＞：http://bit.ly/1nqGWu4 白い巨塔 (2003年のテレビドラマ) - Wikipedia

各回、軒並み20%を超える高視聴率を記録し、最終回の視聴率は多くの地域で30%を超えるなど反響を呼んだドラマであった。

また、最終回の視聴率32.1%は、1978年の田宮二郎版の最終回31.4%を上回り、記録でも連続ドラマの歴史に名を残すことになった。

背景として、放送開始の数年前より次々と表沙汰となった医療過誤問題を取り扱っていることもあり、山崎自身も、執筆当時はフィクションとして書いたことが、現実として起こっている状況に驚きをもっていた（ただし執筆当時、山崎は医療過誤よりも大学病院医局内の封建制にも似た師弟関係や権力闘争に主眼を置いていた）。

また、原作に即して大阪の浪速大学を舞台にしているが、大阪でのロケは初回のわずかなシーンだけで、関西弁を話す登場人物も、財前又一（義父）や岩田重吉（医師会長）など極僅かである。

 ********************（引用終了）********************／

　2箇所を部分引用しました。知らなかったことばかりですが、思っていた以上に人気というか反響のあったドラマのようです。「最終回の視聴率32.1%は、1978年の田宮二郎版の最終回31.4%を上回り」とあります。自分としては1978年のドラマしか記憶にありません。

　リメイクがあったことだけ知っていました。2003年10月から2004年3月18日といえば、平成15年から平成16年で羽咋市のアパートに住んでいた頃です。当時、テレビのドラマというのはほとんど見たことがなく、情報番組か報道番組ぐらいでした。

　そういえばここ一月ぐらいの間に、モトケンこと矢部善朗弁護士（京都弁護士会）が家にテレビがないというツイートをしていました。鹿児島大学で准教授をやっているという坂本正幸弁護士は、かなり前から何度かテレビを持っていないというツイートはしていました。

　モトケンこと矢部善朗弁護士（京都弁護士会）が法科大学院の特任教授であったことは、昨日あたりの小倉秀夫弁護士のツイートでも見かけていました。確認はしていませんが、2004年当時であればすでに特任教授であったという可能性もありそうです。

　私は大学どころか高校も卒業しておらず、大学とはまったく無縁で想像もつかない世界ですが、一つだけ縁があったといえば、平成9年の秋頃に受験した宅地建物取引主任の試験会場が石川郡野々市町（現在は野々市市）の金沢工業大学で、校舎のような教室に入ったことでした。

　奥村徹弁護士の話に戻します。2014年12月9日のツイートを奥村徹弁護士のTwilogから調べました。判例情報のことなど別の事件のことなど私に記憶の混同があったのかもしれません。それと思われるツイートを一つ発見することが出来ました。

ツイート：okumuraosaka（TORU OKUMURA）：2014/12/09 23:42： https://twitter.com/okumuraosaka/status/542328430155407360 ： 殺意はどこいったんや・・・・   大阪の殺人未遂事件、わいせつ致傷に変更 http://t.co/b4hFHZUo5c @nikkansportscomさんから

　これもリンクのニュース記事がリンク切れになっているので確認できませんが、舞鶴女子高校生殺害事件で無罪になった元被告人のことだと思われます。ここでは訴因変更となっていますが、先日の求刑は殺人未遂も含められていたものと考えられます。

／ ********************（引用開始）********************
引用URL＞＞＞＞：http://www.nishinippon.co.jp/nnp/national/article/227629 殺人未遂で懲役２５年求刑、大阪　舞鶴事件無罪確定の男 - 西日本新聞

殺人未遂や強制わいせつ致傷などの罪に問われた無職中勝美被告（６７）の裁判員裁判の論告求刑公判が２９日、大阪地裁（長瀬敬昭裁判長）で開かれ、検察側は懲役２５年を求刑した。弁護側は無罪を主張して結審した。判決は３月４日。

 ********************（引用終了）********************／

　確認のためもう一度調べたのですが、ここで驚く発見がありました。上記に引用した部分ですが、判決が3月4日となっています。今日は3月7日の月曜日なので、先週のうちに判決が出ていることになります。テレビでも情報でもこの裁判の情報はまったく目にしていません。

／ ********************（引用開始）********************
引用URL＞＞＞＞：http://www.news24.jp/articles/2016/03/04/07324007.html 無罪確定の中勝美被告　別事件で懲役１６年｜日テレNEWS24

これまでの裁判員裁判で中被告は正当防衛だとして無罪を主張していたが、４日の判決で大阪地裁は、中被告の供述が「不自然、不合理で信用できない」として、正当防衛は成立せず、殺意があったと認定した。

　その上で「女性の人格を無視した身勝手極まりない犯行で全く反省がうかがえない」として中被告に懲役１６年を言い渡した。

 ********************（引用終了）********************／

　どうも上記のニュース記事には求刑のことは書いていないようです。懲役25年の求刑が懲役16年の判決になったというのも珍しい気がしますが、9年も減った理由が書いてなく「全く反省がうかがえない」としています。

　求刑のニュースを見た2,3日後に、すでに取り上げている三鷹ストーカー事件の差し戻し審の報道があって、ミヤネ屋という14時ころからの情報番組で、住田弁護士が求刑が異常に重すぎたとか、弁護側は懲役16年が妥当と主張しているとか解説をしていました。

　録画していたので油断してあまりよく見ていなかったのですが、録画した内容のことを忘れて他の番組と一緒にまとめて削除してしまいました。住田弁護士は法律の専門家として、被害者が一人の殺人では重すぎるとか異例とか言っていました。確認できなくなったのが残念です。

　今、手を休めて神戸の女児殺害事件の初公判の報道を見ていたのですが、殺人と死体遺棄を認めながらわいせつ目的を否認していると、これは他の番組でも見ていたのですが、弁護側はというようなアナウンスと同時にカメラを向けられた席が満席に近い状態でした。

　カメラが向けられたのは傍聴席から向かって左側で、これは通常、検察官の席が多いはずです。仮に検察官の席だとしてもあり得ないぐらいの人の数でした。まるで雛壇に並ぶようになっていて、刑事裁判でそれだけの数を見たのは、光市母子殺害事件の差し戻し審以来かと思いました。

　ちょうど弁護士というのはまるで死者の墓場をあさり食い物にする地獄絵図のようなものかとぼんやりと考えていたところなので、余計に驚きました。「仲良くなりたかっただけ」という主張は、今日になって何度も繰り返しテレビで見ていました。

　Googleで「神戸　初公判」で検索しました。リンクを開いた2つ目が次の記事です。初公判前の報道のようですが、遺族の心情など書いてあったので一部引用しておきたいと思います。

／ ********************（引用開始）********************
引用URL＞＞＞＞：http://www3.nhk.or.jp/news/html/20160307/k10010433931000.html 神戸 女児誘拐殺人事件 きょう初公判　NHKニュース

初公判を前に、殺害された女の子の母親が報道機関に談話を寄せました。
この中では「私たち遺族は、いまだに娘の死を受け入れることはできていません。娘が着ていた洋服、娘が気に入っていた人形は、そのまま置いてあります。何も悪いことをしていない娘がなぜ殺されなければならなかったのか、全く納得できていません」とつづっています。
そのうえで、遺族として裁判に参加することについて「裁判に参加するのは、何よりも真実が知りたいからです。娘がなぜ殺されなければならなかったのか、被告がなぜこのようなひどいことをしたのかを知りたいからです。被告には、自分のことばで真実を語ってほしいと思います」としています。

 ********************（引用終了）********************／

　次が初公判後の報道です。

／ ********************（引用開始）********************
引用URL＞＞＞＞：http://www.nikkei.com/article/DGXLASDG07H26_X00C16A3CC0000/ 被告、わいせつ目的を否認　神戸女児殺害初公判　　：日本経済新聞

冒頭陳述で検察側は、君野被告は犯行直前まで「幼い女児が登場するアダルトサイトなどを昼夜問わず見続けていた」と指摘。犯行時に飲酒していたとされる点については、「（飲酒が事件に）大きな影響は与えなかった」と述べた。

　一方、弁護側は「女児に声を掛けたのは、話し相手や友達になってほしかったからだ」と反論。「誘拐した時点でわいせつ目的があったと考えるのは無理がある」として未成年者誘拐罪にとどまると主張した。その上で「被告は当日朝から飲酒していた。犯行は計画的でなかった」と述べた。

 ********************（引用終了）********************／

　「誘拐した時点でわいせつ目的があったと考えるのは無理がある」という弁護士の主張内容はテレビで見ていないと思います。この事件も被疑者が逮捕された頃は、連日の報道がありました。かなり猟奇的な事件で、同じ兵庫県で校門に被害者の生首を置いたという事件のことなど思い出した記憶があります。

　今日のテレビの報道といくつか見た主要ニュースでは記憶が喚起できず、確認のため調べて見つけたのが次に引用する部分です。

／ ********************（引用開始）********************
引用URL＞＞＞＞：http://headlines.yahoo.co.jp/hl?a=20160307-00000528-san-soci 神戸小１女児殺害初公判　「わいせつ目的の記憶ありません」起訴内容の一部否認　神戸地裁 （産経新聞） - Yahoo!ニュース

起訴状によると、君野被告は２６年９月１１日午後３時半ごろ、長田区の路上で女児に「絵のモデルになってほしい」などと声をかけて自宅に連れ込んだ後、首をロープで絞め、包丁で刺して殺害。同月１６日までに女児の遺体を損壊し、ポリ袋に小分けして自宅近くの草むらに遺棄したとしている。

 ********************（引用終了）********************／

　いわゆるバラバラ殺人で、どの程度かわかりませんが遺体を切り刻んだと考えられます。わいせつ行為の痕跡を立証するなど不可能に近いのかもしれません。無期刑と有期刑の分かれ目として少しでも言い逃れをしたい気持ちは理解できなくはないですが、弁護団らしき数の多さに圧倒されました。

　動画配信のネットニュースもありそうなので、それを探して法廷の様子を確認したいと思います。さきほどのテレビの報道では、傍聴席からみた右側の状況が確認できませんでした。

　とても短い時間で、一時停止ボタンを使うことで確認が出来ましたが、次のニュース記事のページにある動画の再生52秒あたりの場面です。右側は一列の机で全て空席という状況です。3人の裁判官も着席しているのに、これもなかなか異様な光景です。

「神戸・小１女児殺害 初公判、わいせつ目的は否認」　News i - TBSの動画ニュースサイト http://news.tbs.co.jp/newseye/tbs_newseye2720055.html

　ざっと数えたところ傍聴席から向かって左側の席は9人いるようです。さきほどテレビで見たものとは角度が違って、より正面に近い角度からの撮影でしたが、机が3壇になっていて、ギュウギュウ詰めではなかったですが、埋め尽くしに近い感じに見えました。

　次に見つけたニュース動画も短い時間ですが、再生41秒あたりで左側の席には一人しかいないことがわかりました。傍聴席の後ろから法廷全体を撮影した映像で、起立してから礼をした状況で始まり、着席したところまで映されています。人が重なって見える部分があるので、人数の確認は難しい。

　2,3日前に平成4年の事件の控訴審の法廷の状況のご説明をしたかと思います。控訴審なので名古屋高裁金沢支部ですが、法廷も含め金沢地方裁判所と同じ並びとつくりの法廷だったと思います。それと同じく、この神戸の法廷でも裁判官の席に向かって左側に出入り口が見えます。

　右側には出入り口が見当たりません。昔の金沢地方裁判所の庁舎では、右側がテニスコートのある中庭になっていて、そちらに面した法廷の右側は壁ではなく、被告人の連行用の通路との間もガラス窓のようになっていて、天気のよい日は、木漏れ日も入って法廷内が明るかったという記憶です。

　全体的にも古い西洋風のつくりの内装だったように思います。短編アニメ「ダム・キーパー」で、ブタの少年が放課後に一人で机に座る教室の場面があって、iTunes‎で購入したカバーにもなっていましたが、よく似た雰囲気のある窓だと思っています。

　法廷における検察官と弁護人の席は、2,3年ぐらい前にも法クラの間で議論になっていました。こたんせ、のツイートだけ記憶に残っています。それとは別に自分で何度か調べたことがあるのですが、唯一それらしいと納得出来る理由が、傍聴人の出入りする通路の側が検察官の席というものでした。

　それを私が細かく調べたのは理由があって、平成11年の被害者AAさんの父親AKさんの傷害事件での控訴審の公判において、国選弁護人だった小堀秀行弁護士が通路側の普通、検察官のいる席に座り、名前は忘れ声もほとんど記憶のない肩幅の広い立派な体格の検察官が窓側の席にいたのです。

　弁護人と検察官が示し合わせをしたとしか考えられない光景でした。どちらから持ちかけた話なのか、それも私にはわかりようがありません。

　小堀秀行弁護士に関しては「参考資料扱いにした過去の告訴状の下書き」に記憶にある一通りのことを書いたと思います。事件を起こす前に、法律相談に行った弁護士で相談料を支払ったのもその時だけで、30分の延長だったと思いますが、税込みで1万500円だったと思います。

　再審請求の相談をしたのですが、受任してもよいと言ったのも小堀秀行弁護士だけで、条件として着手金だけで100万円。その上で、土地の境界争いの話をされ、こだわりを捨てきれないモノ好きが世の中にはいるものだというような話をされたので、まともに相手にされたとは思えませんでした。

　時刻は19時49分になっています。テレビのチャンネルを変えるとオレオレ詐欺事件の公開捜査をやっていました。今日はテレビ欄の確認もやっておらず、夕食もまだです。お米を研いで炊飯の準備をし、昼食の洗い物を済ませて戻ったところです。

　改めて考えてみると、国選弁護人だった小堀秀行弁護士から席を変わろうともちかけるはずなどなく、名古屋高検金沢支部の検察官からの持ちかけであったと考えるのが自然です。

　高検の検察官は胸板の厚いごつい体型の人でした。名前は知らないというか憶えられないですが、北海道出身の年配の俳優で最近ではケンミンショーに北海道代表として見ることの多い人に体つきが似ていると思います。昔は、時代劇の殿様役で見ていた憶えのある俳優です。

　「ケンミンショー　北海道」で画像検索すれば、名前を見つけることが出来そうです。

　画像検索で食べ物ばかりが出てきたので、「俳優」をキーワードに追加しました。それでかろうじて見つかったという感じです。

伊吹吾郎 - Wikipedia https://ja.wikipedia.org/wiki/%E4%BC%8A%E5%90%B9%E5%90%BE%E9%83%8E

　昔の時代劇で立派な服装の殿様役で見ていたという印象が強かったのですが、上記のページによると水戸黄門の角さん役を長くやっていたようです。

　その俳優の人と体格はよく似ていましたが、見た目の印象はまるで違っていました。フレームの厚い黒縁メガネで、体を丸めがちでいつも俯いていて、声も聞き取りにくい小声で言葉も少なかったという印象です。冴えない感じに見えたのですが、それが不自然な演出にも思えました。

　控訴審なので平成12年になっていたかと思いますが、当時の名古屋高裁金沢支部の法廷は、前原捷一郎裁判長の容姿が特徴的過ぎて、そちらに気を取られ、他に集中しづらかったということもあり、公判の内容はほとんど記憶になく、平成4年の事件と違って資料もほとんど残っていません。

　人の容姿をとにかく言うことはよくないことだとわかっていますが、それにしても強烈に印象的でした。前にも見た覚えがあるのと同じですが、次のページに前原捷一郎裁判長の写真があります。テレビの静止画のようです。

理不尽スクープ　　　　 : 前原捷一郎裁判長 http://bit.ly/1r7JnjD

　真正面からの撮影なのでそれほど奇抜には見えませんが、法廷で見ていた時はまるで七福神に出てくる置物のような頭のかたちに見えました。仙人にも見える人で、現実離れしている夢の世界に自分が迷い込んでいるような錯覚をおぼえる気分にもなったのです。

　頭の形の前原捷一郎裁判長の容姿だけではなく、法廷における態度を含めて私には理解に苦しむものがあったと記憶に刻まれています。裁判長の方が、私のことをすごく不思議な人間として見ているようにも思えました。

　Googleで検索をすると「七福神　頭が長い」とサジェストが出てきました。日本の神様と思い、どうかと思ったのですが仙人のようです。仙人といえば中国の昔話というイメージが個人的に強かったからです。

／ ********************（引用開始）********************
引用URL＞＞＞＞：http://detail.chiebukuro.yahoo.co.jp/qa/question_detail/q1299569507 七福神の一人は何故頭が長いんですか？http://im... - 一般教養 | Yahoo!知恵袋

福禄寿ですか。中国伝説の仙人です。無数の知恵を積み重ねていくうちに頭が大きくなったとか

 ********************（引用終了）********************／

　私の公判の時、前原捷一郎裁判長は頭が混乱し、動揺しているように見えることもありました。同じ名古屋高裁金沢支部の裁判長であった小島裕史裁判長は、威圧や余裕の印象しか受けず、迷いのようなものは微塵も感じられなかったので、同じ高裁の裁判長でも対蹠的でした。

　小島裕史裁判長の年齢がわからないのですが、80代になってボケている可能性もあるのかと考えていましたが、まだ70代で見当識もしっかりしているのかもしれないと考えるようになってきました。本告訴状で殺人未遂の被告訴人にします。

／ ********************（引用開始）********************
引用URL＞＞＞＞：http://www.e-hoki.com/judge/1094.html?hb=1 裁判官検索：小島裕史　|　法律情報サイト e-hoki

所属

	

定年退官

異動履歴

	
H.14. 3. 9　定年退官
　　　　　　～　H.14. 3. 8　　名古屋高裁 

 ********************（引用終了）********************／

　他に例のない中途半端な経歴になっていました。平成14年に名古屋高裁を退官したように読めますが、神奈川県で簡易裁判所の裁判官になったという情報を見た覚えがあります。あえて簡裁の判事になるのは定年を先延ばしにするのが目的とも、読んだ情報には書いてありました。

　久しぶりの検索で結果をちょっとだけ見たところですが、確か三菱トラックの大型車のタイヤが走行中にはずれて起きた死傷事故の裁判で、ネットに取り上げられていたと思います。

　古い情報ですが見つかりました。全部は読まなかったですが、具体的で詳しいことが書いてあります。死傷事故で簡裁というのも変だと思ったのですが、事故に関連した別の裁判だったようです。

／ ********************（引用開始）********************
引用URL＞＞＞＞：http://sokonisonnzaisuru.blog23.fc2.com/?no=230&m Because It's Ｔhere 三菱ふそう元会長らに無罪判決（横浜簡裁平成１８年１２月１３日判決）

　「三菱ふそう元会長ら無罪　虚偽報告踏み込まず　横浜簡裁
2006年12月13日13時23分

　三菱自動車製大型車の欠陥をめぐる道路運送車両法違反事件の１３日の横浜簡裁判決で、小島裕史裁判官は、元三菱ふそうトラック・バス会長（当時、三菱自副社長）宇佐美隆被告（６６）ら３人と法人としての三菱自をいずれも無罪とした理由について、同法に基づく国土交通相の報告要求が存在せず、犯罪は成立しないと説明した。検察側は控訴する方針。

　三菱自側の報告が虚偽の内容だったかどうかが焦点だったが、小島裁判官はこの部分の認定には踏み込まなかった。 

 ********************（引用終了）********************／

　2006年12月の記事と書いてあります。簡裁の裁判官の定年は65歳と前に見た情報には書いてあったような気がします。仮に2006年の時点で65歳だったとしても、今は2016年で75歳。実際は、それより2,3歳は若い可能性がありそうなので、これは真実追求の期待も幾分高まる朗報です。

　時刻は20時57分です。まだ炊飯器のスイッチも入れていません。夕食が遅くなりそうです。気がついてモトケンこと矢部善朗弁護士（京都弁護士会）と小倉秀夫弁護士のタイムラインを見たのですが、どちらも今日は更新の数がずいぶん少なそうです。

　時刻は23時10分になっています。さきほどつけたテレビでは「#保育園落ちたの私だ」という特集をやっていて、ちょうど今終わったところです。NEWS23という番組です。Twitterのハッシュタグで匿名に反発した人が声を上げ始めたとのことです。

　テレビで保育所問題の特集を見ているのと同じ時間、パソコンで落合洋司弁護士（東京弁護士会）のブログの記事を読んでいて、これも考えさせられました。落合洋司弁護士（東京弁護士会）のコメント部分を全て次に引用します。

／ ********************（引用開始）********************
引用URL＞＞＞＞：http://d.hatena.ne.jp/yjochi/20160304#p2 2016-03-04 - 弁護士 落合洋司　（東京弁護士会）　の 日々是好日

私は検事として被疑者、被告人を見た後に、弁護士として見るようになって、両面から見てきているのですが、勾留中で取り調べを受けている被疑者は、通常ではない心理状態になっていることが多く、自責の念が、「犯行に及んだこと」以外の面から出てくることもかなりあると感じるものがあります。捜査機関、取調官は、都合良く、表面的に、「犯行に及んだこと」から謝罪したり反省したりしたと捉えがちですが、そこは裁判所が慎重に見て、真にそうであるのかを見極める必要があるでしょう。

かつて接したことがある被疑者、被告人を思い出しながら、記事を読みそういったことを感じました。

 ********************（引用終了）********************／

　2,3日前にもご説明を書いたように思いますが、はてなダイアリーの設定はちょっと変わっていて「ブログモード」に設定していないと、Webページから記事のタイトルを取得できません。

　落合洋司弁護士（東京弁護士会）の上記引用した記事のタイトルは「[刑事事件]「殺害認めたものじゃない」＝母への謝罪の手紙めぐり―栃木女児殺害公判」となっています。刑事事件とカギ括弧に括られている文字列は、これも独自の仕様でカテゴリの指定になっています。

　銭湯から戻ったのは10時57分ぐらいでした。テレビを観ていたので20分ぐらい遅れました。浴場から脱衣場に入ったところで、テレビに神社で二人の女性が深刻な話し合いをする場面を見て、それがきっかけで見入ったので、最後まで銭湯で観てきました。

　高台の神社の境内で、若い女性が受け取った一千万円の小切手を破り捨て、気が変わった一週間後に3千万円と条件を変え、それも破り捨てて、わかった自分の欲しかったのはお金じゃなかった、という台詞が印象的でした。兄と一緒に10年間辛酸を舐めてきたという話もしていました。

　途中からいきなり見たのでドラマの筋はさっぱりわかりませんでしたが、その後に大金の小切手を渡した若く見える年配の女性と揉みあいというか引っ張り合いになり、若い女性が神社の階段から転落して死亡したようです。

　その後、事件が解決して、夫婦が自宅のキッチンで手料理をこれから食べようとした時に、悪い予感があたって仕事の呼び出しがありましたが、夫婦はどちらも警察の刑事でした。キッチンの場面に変わって、漸く女優が誰かわかったのですが、NHK連続テレビ小説まれ、の一子の母親役でした。

　刑事夫婦の夫役は石黒という見覚えのある俳優で、どちらも脇役でしか見てこなかったと思ったので、そういう意味でも新鮮に思えたドラマでしたが、いつ呼び出しが掛かるかわからない警察官の仕事と生活の大変さと、弁護士のふっかける負担増にも改めて考える機会になりました。

　夕食はまだですが、落合洋司弁護士（東京弁護士会）のツイートからブログの記事を読む前に、深澤諭史弁護士のタイムラインの更新をやったように思います。そこにもこれはと思う深澤諭史弁護士のリツイートを発見しました。こたんせ、という匿名弁護士のツイートです。

　夕食がまだなので手早く、ご紹介をしたいと思います。

　思い出しましたが、深澤諭史弁護士のTwitterのタイムラインは開いておらず、開いていたブラウザのタグに深澤諭史弁護士のタイムラインはなく、新たに深澤諭史弁護士のタイムラインをブックマークから読み込んだところで、目にしたツイートでした。

　手早く済ませるつもりでいましたが、テキストのコピペがしづらいので、ブログの記事として投稿しました。

参考資料：　深澤諭史弁護士（@fukazawas）のツイート・リツイート（15件、 2016-03-07 00:04〜2016-03-07 23:27：2016-03-07の記録）「15」件: 金沢地方検察庁御中 http://hirono-hideki.cocolog-nifty.com/blog/2016/03/fukazawas15-201.html

　ブラウザで開いている上記のブログ記事のページからコピペで掲載します。

［fukazawas__20160307_2344_4／15のリツイート］
＞fukazawas（深澤諭史）のリツイート＞このリツイートの日時＞2016-03-07 11:57:00＞ URL＞ https://twitter.com/fukazawas/status/706675175916326913 ＞
＞fukazawas（深澤諭史）がリツイートしたnakanori930（弁護士 中村憲昭）のツイートの内容＞
こういう人は、ツイッターで呟いていればどこかの誰か、それも野党以外の人が要望をすくい取ってくれると思っているのだろうか。#保育園落ちたけど政治利用されるのはごめんだ - Togetterまとめ https://t.co/ms2EvJEIIS @togetter\_jpさんから
＞元のツイートの投稿日時＞2016-03-07 11:57:00＞元のツイートのURL＞ https://twitter.com/nakanori930/status/706674985603993600
＞データベースへの登録日時＞2016-03-07 23:39:42＞

［fukazawas__20160307_2344_6／15のリツイート］
＞fukazawas（深澤諭史）のリツイート＞このリツイートの日時＞2016-03-07 15:19:00＞ URL＞ https://twitter.com/fukazawas/status/706725821914832896 ＞
＞fukazawas（深澤諭史）がリツイートしたchildren_ymlaw（弁護士山下敏雅 : 子どもの法律ブログ）のツイートの内容＞
今１０代の皆さんには，最初からスマホとネットがありました。大人達が，その世界に子ども達を無防備に巻き込んでおきながら，トラブルが起きた途端，「撮らせたあなたが悪い」とその大人達が言うのは，フェアではない，卑怯だと，私は思います。https://t.co/0P4kokyHNX
＞元のツイートの投稿日時＞2016-03-07 15:11:00＞元のツイートのURL＞ https://twitter.com/children_ymlaw/status/706723805419302912
＞データベースへの登録日時＞2016-03-07 23:39:39＞

［fukazawas__20160307_2344_7／15のリツイート］
＞fukazawas（深澤諭史）のリツイート＞このリツイートの日時＞2016-03-07 19:27:00＞ URL＞ https://twitter.com/fukazawas/status/706788465933885440 ＞
＞fukazawas（深澤諭史）がリツイートしたkotadon（こたんせ~メンタルリセット）のツイートの内容＞
何が真実であるかを弁護人が勝手に判断して対応することは冤罪を産みます。あなたの主張は、弁護人の役割を誤解しています。 https://t.co/FlcNNaXKEo
＞元のツイートの投稿日時＞2016-03-07 19:08:00＞元のツイートのURL＞ https://twitter.com/kotadon/status/706783484484792320
＞データベースへの登録日時＞2016-03-07 23:39:37＞

［fukazawas__20160307_2344_8／15のリツイート］
＞fukazawas（深澤諭史）のリツイート＞このリツイートの日時＞2016-03-07 19:28:00＞ URL＞ https://twitter.com/fukazawas/status/706788645294907392 ＞
＞fukazawas（深澤諭史）がリツイートしたkotadon（こたんせ~メンタルリセット）のツイートの内容＞
弁護士に敵意を持っている人は、弁護士が無罪主張するのが気に食わないという傾向にあるけど、無罪主張するなら責任を取れというなら、刑事弁護やる人なんていなくなりますわな
＞元のツイートの投稿日時＞2016-03-07 19:11:00＞元のツイートのURL＞ https://twitter.com/kotadon/status/706784231691714560
＞データベースへの登録日時＞2016-03-07 23:39:35＞

［fukazawas__20160307_2344_9／15のリツイート］
＞fukazawas（深澤諭史）のリツイート＞このリツイートの日時＞2016-03-07 20:47:00＞ URL＞ https://twitter.com/fukazawas/status/706808390467452928 ＞
＞fukazawas（深澤諭史）がリツイートしたHideo_Ogura（小倉秀夫）のツイートの内容＞
育ちこそ大事だという考えの人が多かったので、法科大学院制度誕生。RT @bwpotato: イマドキ言われる薄っぺらい「コミュ力」なんかより、知性の方が100万倍大切。育ちも本当に重要。
＞元のツイートの投稿日時＞2016-02-13 00:40:00＞元のツイートのURL＞ https://twitter.com/Hideo_Ogura/status/698169826317963267
＞データベースへの登録日時＞2016-03-07 23:39:34＞

［fukazawas__20160307_2344_11／15のリツイート］
＞fukazawas（深澤諭史）のリツイート＞このリツイートの日時＞2016-03-07 21:36:00＞ URL＞ https://twitter.com/fukazawas/status/706820778197544960 ＞
＞fukazawas（深澤諭史）がリツイートしたjuns76（eternalwind）のツイートの内容＞
例えば、アメリカでうつ病やADHDに対する研究が盛んで、膨大な国費が投じられてるのも、鬱病の人って、うつ病治れば意外と労働力で優秀だからだよね。
日本のばあい、健康な人をブラック労働でうつ病にして、うつ病になったら、福祉も与えず自殺に追い込んでるんだからそりゃ消耗するよ
＞元のツイートの投稿日時＞2016-03-07 20:57:00＞元のツイートのURL＞ https://twitter.com/juns76/status/706810925211193346
＞データベースへの登録日時＞2016-03-07 23:39:30＞

　午前中は深澤諭史弁護士のツイートも少なくてこれまでと違うと思っていたのですが、更新した15件のツイートも深澤諭史弁護士本人のツイートというのは1件もなく、全てリツイートのようです。

2016-03-08　火曜日　01：28　＜＜ ［［　←これまでの記述範囲の終了時刻］］＜＜



2016-03-08　火曜日　12：06　＞＞ ［［　←これからの記述範囲の開始時刻］］＞＞

　朝8時半ぐらいからテレビをつけ、チャンネルを変えたりしていましたが、どのチャンネルでも神戸の事件の初公判のことは取り上げているのは見ませんでした。同じ年頃の子どもを持つ母親など世間的に関心の高そうな事件だけに、どうなのだろうかと気になります。

　10時からのワイドスクランブルでも取り上げておらず、今見ている、ひるおび！という番組でも取り上げているのはテニスのシャラポワ選手のドーピング問題です。

　昨日、書き忘れていたことを思い出したのですが、朝の5時半ぐらいに一回だけみた懲役25年求刑の殺人未遂事件のことですが、テレビでは、わいせつ容疑について全く触れてはいなかったと思います。

　そればかりか被害者の女性の話として、被疑者がドアをこじ開けるように入ってきて、いきなり顔に刃物を切りつけた、という話を司会者のような男性が解説をしていました。5時半という時間帯にテレビを見ることは少なく、どのチャンネルの番組かも確認はしませんでした。

　被害者に対して、わいせつ行為を行っていたという報道は、たまたまネットで見たニュース記事で、その事件のテレビでの報道がすっかり終息したあとのことでした。

　昨日、掲載でご紹介した奥村徹弁護士のツイートも、ツイートの内容だけ見れば、舞鶴女子高校生殺害事件の関連などわかりようもないものでした。次に再掲します。

ツイート：okumuraosaka（TORU OKUMURA）：2014/12/09 23:42： https://twitter.com/okumuraosaka/status/542328430155407360 ： 殺意はどこいったんや・・・・   大阪の殺人未遂事件、わいせつ致傷に変更 http://t.co/b4hFHZUo5c @nikkansportscomさんから

　朝になって目にしたものと思いますが、深澤諭史弁護士のTwitterのタイムラインに奥村徹弁護士のツイートのリツイートがあって、それが最新になっていました。今、見ると2件の更新があって、それも読み込むと2件ともリツートでした。

R：fukazawas（深澤諭史）＞2016/03/08 10:48＞ https://twitter.com/fukazawas/status/707020755624538112 ＞ okumuraosaka （TORU OKUMURA）＞ https://twitter.com/okumuraosaka/status/707020113824776192 ＞ いただきました ありがとうございます https://t.co/diGJqqAWTe

　上記がそのリツイートです。そのあと奥村徹弁護士のTwitterのタイムラインにも同じツイートがあって、不適切な画像を含む可能性などと警告の画像を開くと、刑裁サイ太のコミケの雑誌の写真でした。大嘘判例とかいうものです。

　言葉では十分なご説明が出来ないのでスクリーンショットを撮っておきました。

投稿者：s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2016-03-08 11:37  ツイート： https://twitter.com/s_hirono/status/707032439919497216
2016-03-08-113719_これらの警告を表示したくない場合は、ログインして画像／動画の設定を変更してください。アカウントはこちらから登録できます。.jpg https://t.co/pjdTn7EJnL

投稿者：s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2016-03-08 11:36  ツイート： https://twitter.com/s_hirono/status/707032319480057856
2016-03-08-113651_この画像／動画は不適切な内容を含んでいる可能性があります。.jpg https://t.co/DXSqzEOFlx

投稿者：s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2016-03-07 21:05  ツイート： https://twitter.com/s_hirono/status/706813127640248320
2016-03-07-210551_金の話をするのと，依頼者のことを考えるのとは料率しますよね.jpg https://t.co/exGShdb9EN

投稿者：s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2016-03-07 21:04  ツイート： https://twitter.com/s_hirono/status/706812820541669376
2016-03-07-210438_「金の話じゃないんです！」と意気込む人に高めの着手金を伝えるの，ほんとに有効なんですね.jpg https://t.co/7gDn8pwTMC

投稿者：s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2016-03-07 15:26  ツイート： https://twitter.com/s_hirono/status/706727800720347136
2016-03-07-152648_TORU　OKUMURAさんはTwitterを使っています：　”最高裁第一小法廷平26。7。8決定　舞鶴女子高校生殺害事件　女子高校生に強い.jpg https://t.co/PtzgUcHETJ

投稿者：s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2016-03-07 15:17  ツイート： https://twitter.com/s_hirono/status/706725495962906625
2016-03-07-151738_懲役25年　舞鶴　-　Twitter検索.jpg https://t.co/2WRLUybB9z

　他のものを含めて最新の6件を掲載しました。これは「h-api-twitter-user_timeline-format.rb s_hirono 6」という自作のコマンドを実行してEmacsにテキストを読み込んでいます。内容がはっきりわからなかったので、適当に6件にしたのです。

　「いただきました ありがとうございます」という奥村徹弁護士のツイートは、名宛をしていませんが、フォロー関係があって相手に伝わることを確信しつつ、関係を他にはしられたくないという配慮なのでしょう。

　深澤諭史弁護士が何を考えてリツートしたのかは不明ですが、あえてリツイートするということは、少なくとも深澤諭史弁護士から奥村徹弁護士への歩み寄りや関心を持っていることがうかがえるかと思います。

　6件の読み込みをやってから気がついたのですが、昨夜21時ころにやっていたスクリーンショットも刑裁サイ太のTwitterのタイムラインのスクリーンショットでした。

　確か2件の刑裁サイ太のツイートをデータベースに登録しようとしたところ2件ともエラーが出たので、スクリーンショットで記録をしたのです。ページの再読み込みをするとツイートは消えていました。20件ほどの更新を読み込んだ直後のことでした。

　削除されたツイートを記録するというのは非常識だとわかっていますが、私は現状の刑事弁護や弁護士の資質に致命的な欠陥や問題性を強く感じており、その問題性を検察庁や法務省に出来るだけ正確に伝え、記録する必要性を感じております。

　ツイートを削除したからと言って、削除する前は不特定多数の人の目に触れる機会があり、それが法律の素人を含め一般人に与える影響というのも軽視出来ないと考えています。プロフィールの情報を含め、日頃のツイートやリツイートも総合的な資料としています。

　例えば、奥村徹弁護士の次のツイートなどいかがなものでしょうか？

ツイート：okumuraosaka（TORU OKUMURA）：2016/03/07 18:05： https://twitter.com/okumuraosaka/status/706767755106656256 ： 他の弁護士が「バレないから自首しなくていい」と言って自首しなかった事件について、留置場から相談の手紙が来ていますよ。弁護士のせいにすんなよ

　深澤諭史弁護士のストーカーに対するツイートなどもそうなのですが、実質的な被疑者や犯罪者の社会的評価を実際以上に貶め、立場を悪くし、犯罪や社会不安そのものを助長しているように思えることがあるのです。その私の認識の根拠を示す資料でもあります。

　例外を大きく取り上げるという意味もありますが、深澤諭史弁護士や奥村徹弁護士より、テレビで法廷などに出ている弁護士の方が、より積極的に被疑者や被告人を都合よく利用しているように思えることもあるのです。まるで泥棒神社の神事のお供え物に見えることもありました。

2016-03-08　火曜日　23：52　＜＜ ［［　←これまでの記述範囲の終了時刻］］＜＜



2016-03-09　水曜日　21：24　＞＞ ［［　←これからの記述範囲の開始時刻］］＞＞

　夕食もまだです。昨日になりますが、久しぶりに小木港の隣の九十九湾まで行きアジ釣りをやってきましたが、記録的なぐらい釣れずに３匹だけの釣果でした。25、21、18センチです。25センチのアジも尻尾が大きくて美味そうには思えなかったので全部、干物にしました。

　九十九湾から家に戻ったのは21時半ぐらいになっていたかと思います。コンビニに昼前ぐらいに注文していたアマゾンの代金を支払いに行き、夕食も遅くなりました。0時ぐらいから録画をして出掛けたテレビドラマの白い巨塔を再生して視聴しました。

　今日もいろいろとあって、いやあり過ぎて何をどう取り上げるべきかと悩みました。一つは、アジ釣りに出かけている間に、更新されていた深澤諭史弁護士のツイートとリツイートのことです。

　昼過ぎにはミヤネ屋という情報番組だったと思いますが、何度目かの東京オリンピックの聖火台のことでの話題を見るにつけ、落合洋司弁護士（東京弁護士会）のこれまでの東京オリンピックに関するツイートを思い出し、それをまとめました。

　その落合洋司弁護士（東京弁護士会）の東京オリンピックに関連したツイートのまとめの作業をしているときに、東電に関するツイートが気になったり、テレビの速報では滋賀県大津の裁判所での高浜原発の稼働差し止めの仮処分の報道見たりで、同じように東電についてもまとめを作成しました。

　ミヤネ屋が終わってからは録画をしながらドラマ「白い巨塔」を視聴しました。改めて感じたことですが、裁判や医療事故がテーマになっていたとは、不思議なぐらいつい先日までまるで知らないでいました。

　田宮という白い巨塔の主演俳優のことは記憶にあって自殺したことも知ってはいたのですが、最終回の放送前で、自殺の報道の後に関心が高まり、視聴率が跳ね上がったことも初めて知りました。

　田宮という主演俳優の白い巨塔について調べたところ、どうも自分の記憶とはテレビ放送の時期が違っていました。自分の記憶の中で同じ頃に放送されていたのが「喜びも悲しみも幾歳月」という灯台守のドラマで、そのことからネットで検索をして調べたところ、新たな発見がありました。

　灯台守ということで私がテレビの放送と同時代ということで思い浮かべるのは能登半島の猿山岬の灯台です。昨年の10月に舳倉島に行った帰路のフェリーからもそれと思われる岬の景色が見えたことを思い出しました。

　舳倉島へは事前にインターネットで下調べをして出掛けましたが、益谷秀次の銅像があることは、舳倉島から帰って数日後に知りました。

　そんなこともあり宇出津出身の政治家、益谷秀次について改めて調べてみました。Googleで画像検索もやりましたが、本人の写真のようなものは一つだけ見つかり、記憶が定かではありませんが、顔写真は初めて見たような気がしました。

　さらに裁判官から弁護士になって、そのあとに政治家になったということを今夜初めて知り、とても意外に思いました。まずは今夜まで気が付かずに、あるいは情報を見落としていたことに驚いたのです。

　別の写真では同じ能登町出身の哲学者と取り違えそうになったことも、注意点として考えさせられました。少し若い頃の写真かとも思ったのですが、説明があったので、別人らしいとわかりました。

　今日はいろいろとあったのですが、次につなげるには選択と順序に迷うところもあります。とりあえずは、はてなダイアリーにメモのように記録した記事を一覧としてご紹介しておきたいと思います。

検察にとって「泥沼」と化した美濃加茂市長事件控訴審 | 郷原信郎が斬る http://d.hatena.ne.jp/hirono_hideki/20160305/1457154745
2016-03-05 - 弁護士 落合洋司　（東京弁護士会）　の 日々是好日／被告「刑軽くなると言われ」　栃木女児殺害、供述変遷の理由 http://d.hatena.ne.jp/hirono_hideki/20160305/1457188053
2016-03-03 - 弁護士 落合洋司　（東京弁護士会）　の 日々是好日／ロシア人男性の拳銃所持　札幌地裁が再審決定　「おとり捜査は違法」 http://d.hatena.ne.jp/hirono_hideki/20160305/1457188335
2016-03-02 - 弁護士 落合洋司　（東京弁護士会）　の 日々是好日／ＧＰＳ捜査、初の高裁判断「違法とは言えない」 http://d.hatena.ne.jp/hirono_hideki/20160305/1457188505
[Twitterのまとめ]2016年03月05日の「廣野秀樹＼さらば弁護士鉄道・泥棒神社の夜」ツイート http://d.hatena.ne.jp/hirono_hideki/20160306/1457190175
[Twitterのまとめ]2016年03月06日の「廣野秀樹＼さらば弁護士鉄道・泥棒神社の夜」ツイート http://d.hatena.ne.jp/hirono_hideki/20160307/1457276763
[Twitterのまとめ]2016年03月07日の「廣野秀樹＼さらば弁護士鉄道・泥棒神社の夜」ツイート http://d.hatena.ne.jp/hirono_hideki/20160308/1457363217
主任弁護人の岸田洋輔弁護士は「驚きを隠せず、残念な気持ちでいっぱい。請求人の一刻も早い名誉回復を目指したい」／札幌地検が即時抗告　ロシア人男性の再審開始決定受け http://d.hatena.ne.jp/hirono_hideki/20160308/1457405036
勾留中で取り調べを受けている被疑者は、通常ではない心理状態になっていることが多く／2016-03-04 - 弁護士 落合洋司　（東京弁護士会）　の 日々是好日 http://d.hatena.ne.jp/hirono_hideki/20160308/1457405134
京都府舞鶴市で起きた女子高校生殺人事件で、無罪が確定した／無罪確定の中勝美被告　別事件で懲役１６年(日本テレビ系（NNN）) http://d.hatena.ne.jp/hirono_hideki/20160308/1457405500
捜査機関の思いこみによって真犯人を逃がしてしまったのです。これでは被害者も浮かばれませんし、ご遺族もたまりません。／東電ＯＬ殺害事件　再審前にさらに無罪ダメ押しの新証拠 http://d.hatena.ne.jp/hirono_hideki/20160308/1457405928
警察は高層マンションから投げ落とされたとみて、軽犯罪法違反の疑いで捜査しています。／高層マンションから金網投下か - NHK 首都圏 http://d.hatena.ne.jp/hirono_hideki/20160308/1457416710
前年度まで勤務していた市内の別の小学校でＰＴＡ役員をしていた女性保護者とメールのやりとりをする中で、画像を送った。／校長、保護者に男性器画像…送ったことを認め退職の意向 愛知県 http://d.hatena.ne.jp/hirono_hideki/20160308/1457448878
[Twitterのまとめ]2016年03月08日の「廣野秀樹＼さらば弁護士鉄道・泥棒神社の夜」ツイート http://d.hatena.ne.jp/hirono_hideki/20160309/1457449328
遺体解剖の教授「殺害と遺棄現場、絶対違う」　自白との矛盾指摘　今市事件裁判(下野新聞) - goo ニュース http://d.hatena.ne.jp/hirono_hideki/20160309/1457490735
 取材に対し弁護士は「守秘義務があり、答えられない」と／内部告発者名、市に伝える　京都、通報窓口の弁護士 : 京都新聞 http://d.hatena.ne.jp/hirono_hideki/20160309/1457490879
城戸浩正弁護士は「3人が7人を代表し、無実を訴える。これが主張のメーン」／明倫中訴訟、遺族「事実は確定」強調　山形地裁口頭弁論｜山形新聞 http://d.hatena.ne.jp/hirono_hideki/20160309/1457501283
 「無実を証明するまで闘っていきたい」。被告の元少年（36）は口を開いた。事件発生から23年／明倫中訴訟、遺族「事実は確定」強調　山形地裁口頭弁論｜山形新聞 http://d.hatena.ne.jp/hirono_hideki/20160309/1457501405
被告人Ｙが鹿児島市内の路上で被害者を強姦したとする強姦被告事件につき／2016-03-05 - 奥村徹弁護士の見解 http://d.hatena.ne.jp/hirono_hideki/20160309/1457502607
簡単に言うと２ちゃんねらーと、彼らに玩具にされた弁護士との戦いである／悪ふざけの”恒心教騒動”が一転、児童ポルノ禁止法の問題点を浮き彫りに http://d.hatena.ne.jp/hirono_hideki/20160309/1457502868
元検察官の落合洋司弁護士は、「これを検察庁が扱うとして、私が公判部長なら少なくとも3人の検事を専従にする。それくらい難しい事件」という／原発事故で東電元会長ら強制起訴　だが本当に法廷で真相解明できるのか？ http://d.hatena.ne.jp/hirono_hideki/20160309/1457504903
刑事司法に関する報道で、被害者らの口を借りて「真相」「真実」という言葉を多用し、人々の期待を煽るのは、日本のマスメディアのよくないクセである。／原発事故で東電元会長ら強制起訴　だが本当に法廷で真相解明できるのか？ http://d.hatena.ne.jp/hirono_hideki/20160309/1457505133
そのためには、指定弁護士の報酬の限度額を大幅に増額するとか、検察事務官を派遣するとか、緊急に公的なバックアップを図らないとまずいのではないか。／原発事故で東電元会長ら強制起訴　だが本当に法廷で真相解明できるのか？ http://d.hatena.ne.jp/hirono_hideki/20160309/1457505514
（文＝江川紹子／ジャーナリスト）／(3ページ目)原発事故で東電元会長ら強制起訴　だが本当に法廷で真相解明できるのか？ | ビジネスジャーナル http://d.hatena.ne.jp/hirono_hideki/20160309/1457505847
山崎さんは４０の取材から1を生かすといわれる膨大な取材と資料をもとに作品が書かれているといわれる。／2013-10-01 山崎豊子 ドラマ 木村拓哉 盗作 大地の子 10月1日密葬 http://d.hatena.ne.jp/hirono_hideki/20160309/1457506622
参考とした資料をほとんど脚色せず作品に反映させたため、盗作との指摘を資料の執筆者から何度も指摘を受けている。／山崎豊子 - Wikipedia http://d.hatena.ne.jp/hirono_hideki/20160309/1457510230
海を渡る福島ブランド　向山製作所の「生キャラメル」 パリのスイーツの祭典に初出品　｜みんなの経済・企業｜福島 http://d.hatena.ne.jp/hirono_hideki/20160309/1457511666
益谷秀次とは - goo Wikipedia (ウィキペディア) http://d.hatena.ne.jp/hirono_hideki/20160309/1457524106

　どのあたりから初めようか迷いもありましたが、上記の掲載はここ数日のものばかりです。「検察にとって「泥沼」と化した美濃加茂市長事件控訴審 | 郷原信郎が斬る」をとりあえず切り出しとしておきました。政治や行政と裁判という関係でも考えさせられるところがあります。

　時刻は22時04分になっています。夕食もまだでテレビもつけていないのですが、22時を過ぎていてちょっと驚きました。ここ2,3日ツイート数が少なくなっていると気になっていたモトケンこと矢部善朗弁護士（京都弁護士会）のタイムラインの更新ツイートを読み込みました。

　モトケンこと矢部善朗弁護士（京都弁護士会）が私のタイムラインのツイートを見ているのかどうか確認は出来ませんが、ちょっと気になるツイートがありました。

ツイート：motoken_tw（モトケン）：2016/03/09 21:27： https://twitter.com/motoken_tw/status/707543270730047488 ： 大野病院事件の裁判官は起訴された医師に無罪判決をしてるんだけど。 https://t.co/6iBCZcNdQL

　考えてみると、白い巨塔の再放送は全国一律ではないのかもしれません。モトケンこと矢部善朗弁護士（京都弁護士会）が今頃、大野病院事件のツイートをしたのかわかりませんが、考えさせられるとともに、追求するための時間的労力的な限界も改めて感じました。

　一時停止で視聴を中断してから1時間以上は経つと思いますが、インターネットの発達の恩恵もあって、画質はよくないですが、次の動画の視聴をやっていました。今も一時停止中です。

昭和ドラマ▼田宮二郎TV版白い巨塔 01話rt低画質ノイズCM有 - YouTube https://www.youtube.com/watch?v=4QeocBPsfbk

　事前に調べたいた情報で知っていたのですが、ドラマの開腹手術の映像は、手術を受けた人などの同意を得た上での実際の映像ということで驚きというか衝撃すらありました。人体の内部に関してはこれまで目を背ける傾向が強かっただけに、幸い不鮮明な映像ではありますが、向き合いました。

　真っ先に思い出したのは落合洋司弁護士（東京弁護士会）のツイートのことです。焼き肉と検索すれば見つかりそうですので、調べます。

ツイート：yjochi（落合洋司（オンラインチャット相談対応可））：2010/08/07 00:47： https://twitter.com/yjochi/status/20478788968 ： 横浜地裁の裁判員は、死体写真見て吐いたそうだが、私は、若手検事の時、解剖の後、焼肉弁当食べていた。

　上記のツイートが見つかりました。落合洋司弁護士（東京弁護士会）は以前ブログで、本に埋もれて死ぬのなら本望とコメントしていたことがあったかと思います。実際にあった事故に対するコメントで、札幌市の書店で起った事故であったように記憶しています。

　旺盛な知的好奇心だともその時は考えましたが、その時に思い出したのが刑務所か拘置所の官本で見た司馬遼太郎の「胡蝶の夢」という本のことでした。江戸時代の末期の死体解剖のことなどが書いてありました。4巻ぐらいになっていたと思いますが、全ての取り揃えはなかったと思います。

　今日は、「オリンピック」と「東電」をキーワードに、落合洋司弁護士（東京弁護士会）という人物について、改めて考えた一日でもありました。

　ココログフリーのブログ記事としてのまとめの方も、ここ数日分を次に掲載してご紹介しておきたいと思います。

参考資料：　深澤諭史弁護士（@fukazawas）のツイート・リツイート（15件、 2016-03-07 00:04〜2016-03-07 23:27：2016-03-07の記録）「15」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/03/fukazawas15-201.html
参考資料：　こたんせ~メンタルリセット（@kotadon）のツイート・リツイート（23件、 2016-03-07 08:25〜2016-03-09 08:13：2016-03-09の記録）「23」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/03/kotadon23-2016-.html
参考資料：　深澤諭史弁護士（@fukazawas）のツイート・リツイート（53件、 2016-03-07 00:00〜2016-03-09 11:07：2016-03-09の記録）「53」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/03/fukazawas53-201.html
参考資料：　「@hirono_hideki」をキーワードに含む「こたんせ~メンタルリセット（@kotadon）」のツイート・リツイート（2014-02-16 15:59〜2014-02-16 20:57）「2」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/03/hirono_hidekiko.html
参考資料：　「@hirono_hideki」をキーワードに含む「モトケンこと矢部善朗弁護士（京都弁護士会）（@motoken_tw）」のツイート・リツイート（2010-10-25 14:40〜2015-12-20 20:55）「54」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/03/hirono_hidekimo.html
参考資料：　「@hirono_hideki」をキーワードに含む「小倉秀夫弁護士（@Hideo_Ogura）」のツイート・リツイート（2010-05-06 13:48〜2015-12-24 20:30）「80」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/03/hirono_hidekihi.html

　落合洋司弁護士（東京弁護士会）は政治に関する発言も多く、政治に対する関心の薄い私ですが、落合洋司弁護士（東京弁護士会）を通して政治について考えさせられることは大きいです。

2016-03-15　火曜日　22：55　＜＜ ［［　←これまでの記述範囲の終了時刻］］＜＜



2016-03-15　火曜日　22：55　＞＞ ［［　←これからの記述範囲の開始時刻］］＞＞

ツイート：kk_hirono（告発-金沢地方検察庁御中_ツイッター）：2016/03/09 22:37： https://twitter.com/kk_hirono/status/707560951159984128 ： 落合洋司弁護士（東京弁護士会）は政治に関する発言も多く、政治に対する関心の薄い私ですが、落合洋司弁護士（東京弁護士会）を通して政治について考えさせられることは大きいです。

　上記ツイート投稿からの再開になるかと思います。3月9日9時22分ころからの中断でした。あらためて確認をしてみると、思っていたより長い中断になっていました。

告訴状2016年／金沢地方検察庁御中 https://hirono2016k.wordpress.com/

　本日つまり2016年3月15日のことですが、上記のWordPressのブログを新規に作成しました。ブログの作成は簡単ですが、ツイートをAPIで投稿してデータベースに登録するというスクリプトを新規に作成していて、これは思った以上に手間取りました。それでも本日中に概ね完成しました。

　本日は、テレビでも関心の強いニュースがいくつかありました。夕方暗くなってから宇出津新港のどんたく宇出津店に買い物に行ってきました。かなり寒かったというか、寒さを感じました。

　昨日のことになりますが、16時ころからテレビ金沢で始まる「となりのテレ金ちゃん」という番組で新たな発見がありました。テレビに出ていたのは輪島市の名舟の御陣乗太鼓、曽々木海岸での岩のり採りでした。

　番組を見ていて気になるところがあって調べたのですが、輪島市名舟の神社の名前は白山神社だと知り、それが名舟大祭とともに舳倉島の奥津比咩神社と歴史的な関連があると知りました。調べているうちに明治の頃は宇出津と輪島市が同じ鳳至郡だったと初めて知りました。

　細かいことはメモと記録を兼ねて廣野秀樹＼さらば弁護士鉄道・泥棒神社の夜（@hirono_hideki）にツイートを投稿してあります。Twilogでもよりわかりやすく確認できると思います。

　昨日の3月14日は、夕方暗くなってからAコープ能都店に買い物に行ってきました。2割引きになった「ひなあられ」が売っていったので、それも買ってきました。3月3日の雛祭りの日には見当たらなかったので、思いがけない発見で迷わず買いました。

再生される前には弁護士が裁判員に対し、話の内容そのものではなく、あくまで被告が自分の意思で話しているかどうかを判断するためのものだと映像を流す目的について注意を促しました／今市事件 ７時間以上の取り調べの録音録画 再生始 http://d.hatena.ne.jp/hirono_hideki/20160315/1458049181
元検事の落合洋司弁護士は「検察は自白に頼った立証をせざるをえない状況になっていて、裁判官や裁判員に被告が任意で供述したと印象づけたいのではないか」と指摘しています／今市事件 ７時間以上の取り調べの録音録画 再生始まる　NHKニュース http://d.hatena.ne.jp/hirono_hideki/20160315/1458049365
 被告「優秀な弁護士だから、何とか無罪にしてくれるという思いが強かった」／栃木女児殺害公判　「抱えて刺した」「５回くらい」…勝又被告が殺害状況を供述する、検事取り調べ映像詳報 （産経新聞） http://d.hatena.ne.jp/hirono_hideki/20160315/1458052097
 被告「後は弁護士と話した後でいいか。弁護士に本当のことを話していないから。これ以上は話したくない」／被告「人の道の方が楽だと思った。もう逃げたくないと思った」／検事取り調べ映像詳報 （産経新聞） http://d.hatena.ne.jp/hirono_hideki/20160315/1458052305

　上記4件は、これから引用記事に特化した運用を考えているはてなダイアリーに投稿したエントリです。後の2件は、テレビのニュースZEROの報道を見てから、ネットで調べエントリーとして記録しました。女児が安らかに成仏して頂くために弁護士泥棒神社に奉納したいです。

　あらためて弁護士に対して、魂が震えるような憤りと強烈かつ鮮明な危機感・不信感を、この今市女児殺害事件で確認することが出来たと考えています。中断も無駄ではない、記録として絶妙なシャッターチャンスを得ることが出来たとも考えています。プラスマイナスのバランスを図った上で。

2016-03-17　木曜日　10：38　＜＜ ［［　←これまでの記述範囲の終了時刻］］＜＜



2016-03-18　金曜日　16：04　＞＞ ［［　←これからの記述範囲の開始時刻］］＞＞

　この項目のタイトルを「被害者AAさんの父親AKさんの立場で考える刑事再審制度における弁護士に対する不信感と悪魔性＼墓場へ向かう弁護士鉄道・社会的告発」だと確認したところです。

　テーマを幅広く設定しすぎたと思います。本来メインに書くつもりでいた東電強制起訴のことも不十分で、再審の問題についてはまだ手を付けていないかもしれません。本当は札幌でのロシア人元船員の再審開始決定を軸に論旨を展開する予定でいました。

　再審制度に関する問題はここ最近になってニュースも増えておりますが、その他の事件や出来事においても考えさせられることが多く、情報を読みこんだり、ブログなどの記事として頭と作業の整理するだけでも時間と手間を取られていました。

2016-03-27　日曜日　14：05　＜＜ ［［　←これまでの記述範囲の終了時刻］］＜＜



2016-03-27　日曜日　14：06　＞＞ ［［　←これからの記述範囲の開始時刻］］＞＞

　3月18日以来の再開ということになりそうです。告訴状作成の方針、書面としての体系や構造など詰めの段階でいろいろと考えてきたのですが、取り扱う事実や問題の分量と時系列としての範囲も広すぎるので、散文調ではありますが、有機的関連をもたせる形でまとめていきたいと考えました。

　これから独立した項目の数が多くなりますが、脈絡や関連といったものはさほど重視せず、全体像との関係性や簡潔な結論を示しながら作り上げていきたいと思います。

2016-03-27　日曜日　14：24　＜＜ ［［　←これまでの記述範囲の終了時刻］］＜＜
**** 成仏理論と弁護士鉄道／弁護士による被害者AAさんの父親AKさんの奪われ、狂わされた人生・北斗の拳と泥棒神社

:CATEGORIES: 被害者AAさんの父親AKさん,金沢地方検察庁提出告訴状の下書き
:TAGS: 告訴状の下書き／2016年,山口治夫弁護士

2016-03-27　日曜日　14：34　＞＞ ［［　←これからの記述範囲の開始時刻］］＞＞

　何日か前、北斗の拳について調べて、まとめの資料も作成したのですが、このあたりを出発点にしたいと思います。裁判の資料で知ったことですが、昭和11年12月生まれの被害者AAさんの父親AKさんは今年の12月の誕生日で80歳になるはずです。あらためて月日の流れを感じております。

　すでに男性としての日本人の平均寿命を超えているとも考えますが、私には生存を確認することも出来ません。石川県警察の刑事の人から「絶対に連絡をするな。」と言われたことを覚えておりますが、それも4,5年前になるように思います。

　はっきり言われたことを憶えているのは、能登警察署の刑事だった大家警部補で、2009年の秋のことでした。その後、同じ石川県警察にいるはずなので、大家警部補に連絡を取りたいと他の警察の人に頼んだこともあったのですが、聞き入れられることはありませんでした。

　私自身の意識の変化が大きいのですが、私は弁護士より警察や検察の責任が大きいと考えていて、少なくとも20年はその魔法にかかったような状態が続いていました。平成4年4月1日を起点とする事件ですが、あと5日ほどで24年目ということになりそうです。

　被害者AAさんに対する傷害・準強姦事件を起こしたのがその平成4年4月1日のことで、記憶が少し曖昧になっていますが、20時23分が金沢西警察署への出頭の時刻であったと、翌日からの取り調べ担当者になった谷内孝志警部補に聞かされたました。

　取調室での会話ですが、他に被害者AAさんの父親AKさんについては、定年退職したばかりの矢先に起った娘の事件だと。

　他に「犯人のことを憎いとは思わない。ただ、事件のことを思うとはらわたが煮えくり返る。」と被害者AAさんの父親AKさんが話していたとも、谷内孝志警部補には聞かされましたが、今にして思えば、取り調べを有利にすすめるための作り話であったことも可能性としてはありそうな気がします。

　「参考資料扱いにした過去の告訴状の下書き」ではなく本告訴状においても既に書いたと思いますが、一審の金沢地方裁判所の公判には一切姿を見せなかったとか、被害者AAさんの父親AKさんの言動には不可解なところがあり、事件の真相の解明のために全てを犠牲にしているとも考えられたのです。

　79歳から24年前を単純に逆算すると、平成4年当時55歳ということになります。55歳から25年後に80歳だと考えると、この24年が何だったのかと感慨もひとしおです。

　平成4年当時27歳だった私も、今年の11月には52歳になるようです。あと3,4年ほどで平成4年当時の被害者AAさんの父親AKさんの年齢にならぶことになりそうです。

　今気がついたのですが、被害者AAさんは兄二人の3人兄弟の一人娘で、長男は私より2つ年上、被告訴人安田敏と同じ年だと聞いていました。平成4年当時、被告訴人安田敏は29歳だと言っていました。誕生日が被害者AAさんの父親AKさんと同じ12月25日頃というのも印象に残っています。

　なお、平成3年の12月25日ころには被告訴人安田敏の長女が誕生していて、出産予定日から自分と同じ誕生日になるかもしれないと被告訴人安田敏は話していました。

　被告訴人安田敏の妻の妊娠中と出産前後の不審な行動については、「参考資料扱いにした過去の告訴状の下書き」のみの記載となっているかもしれません。

　そういえば久しぶりに思い出しましたが、金沢西警察署での取り調べの時、谷内孝志警部補が被告訴人安田敏について、「あんな男の話をするな。お前の男が下がるだけや。」と吐き捨てるように言って、私の供述を遮ったことがありました。

　被告訴人安田敏は汚れ役として演技をしていた可能性が高いので、警察官の規範意識の高さがより一層、被告訴人安田敏を下劣な男だと思わせたことも取り調べの時は考えていましたが、これも今考えると余計な話はさせずに、有罪の調書を作成することを狙っていたとも考えることが出来そうです。

　谷内孝志警部補は取り調べの時、自分の年齢についてもうすぐ40歳になる、というような言い方をしていました。輪島の出身とも話していましたが、能登や輪島の訛りがあるとは全く感じられませんでした。

　輪島のどのあたりとも私は聞きませんでしたが、当時はまだ鳳至郡だった門前町との合併もなかったので、輪島の範囲は今よりも狭いものになります。同じ能登でも輪島の方は、方言が似ているものの、発音やイントネーションには違いが大きいので、敏感に感じるところがありました。

　その当時は私も知らなかったと思いますが、定年まで務めても警部補になれない警察官が多いと聞いたことがあるので、40歳前後で警部補になっていたというのは、能力とともに野心も旺盛であったのかと考えられ、先走った独善性もあったような気はします。

　何より印象的だったのは「参考資料扱いにした過去の告訴状の下書き」で何度か取り上げているはずの、拘置所への移管当日、最後の取り調べて「わっしゃ、ウィスキーが好きや。」と言っていた言葉です。

　「参考資料扱いにした過去の告訴状の下書き」で最後に取り上げた時に初めて気がついたと思いますが、当日、谷内孝志警部補が作成した平成4年5月28日付の供述調書は、江村正之検察官から証拠としての提出に含まれてはいなかったようです。

　平成4年当時と平成28年の現在とでは、警察の取り調べもずいぶんと変わっているものと考えますが、私が受けた金沢西警察署での取り調べというのは、谷内孝志警部補の独占状態でした。他の捜査員が取調室に入ったのもほとんど記憶にないぐらいです。

　例外は自首出頭した直後の取り調べて、これは標題も「自首調書」とか他の供述調書とは違ったものになっていましたが、その時だけは別の取調官で、取調官も二名でした。

　いまでは見かけませんが、昭和の頃から平成のはじめころは「ワンマン」という札のようなものをつけたバスが多かったように思います。独善的な人柄のことを今でもワンマンということがあるかと思いますが、谷内孝志警部補の振る舞いによる刑事手続は実にワンマンという印象でした。

　その谷内孝志警部補運転のワンマンバスからの乗り継ぎとなったのが、「弁護士鉄道」であったと言えます。このワンマンバスと弁護士鉄道の関連性についても、記憶を手繰りながら正確なことを記録し伝えていきたいと考えておりますし、物語のような表現としても探求を試みたいと考えています。

　先日、少年ジャンプに連載されていた「北斗の拳」について調べたのですが、昭和58年からの連載とWikipediaにありました。連載開始の月日や季節を確認したいのですが、その先の調べはまだやっていません。

／ ********************（引用開始）********************
引用URL＞＞＞＞：http://raoh.info/diary.cgi?mode=comment&no=287 北斗の拳 蒼天の拳 > NEWS >『北斗の拳』連載開始 - 『北斗の拳』連載開始 - 北斗の拳 蒼天の拳 DFS 北斗の庭園

    1983.09/13,09:00 北斗の拳 蒼天の拳/NEWS 

　雑誌『週刊少年ジャンプ 1983年9月26日号』で『北斗の拳』が巨弾新連載開始になった日です。 

 ********************（引用終了）********************／

　ちょっと難しいかなと思い始めたところ、上記の情報が見つかりました。大ヒット作だけに情報の取得も期待できたのですが、昭和58年9月26号とは意外でした。実際の発売日とは数日のズレがあるとも考えられますし、宇出津では週刊少年ジャンプの発売曜日も一日遅れだった憶えがあります。

　昭和58年の9月の終わりか10月の初めということですが、これはちょうど金沢市観音堂の被告訴人安田敏のアパートに居候をしながら、被告訴人安田敏と仕事もせずに遊びまわっていた時期です。

　被告訴人安田敏とは金沢で、輪島の暴走族のたまり場に顔を出したり、集団暴走の集会にも参加していた時期でした。10月中になると思いますが、私がきっかけで被告訴人安田敏が消火器の訪問販売をするようになった会社の社長も、確か当時27歳で、輪島の大きな会社の息子という人物でした。

　その前から余り読まなくなっていたとも思いますが、北斗の拳の連載が始まってしばらくすると、少年ジャンプや少年マガジンという雑誌を私は全くと言って手にしなくなりました。子どもの頃は漫画好きだったので、北斗の拳の始まりが漫画からの事実上の卒業のものになったという感じです。

　長距離トラックの仕事をするようになってからは、コンビニの立ち読みでも時間を潰すことが多くなり、週刊誌もよく買っていたのですが、ビックコミックスピリッツとか週刊誌のような漫画はよく読んでいたのですが、少年向けの漫画のようなものは全く手にしなくなりました。それは今も同じです。

　最近になって北斗の拳のことを度々意識するようになったのは、法クラのツイートの内容がきっかけでした。先日、まとめたものがあるので、そちらのブログの記事をご紹介します。

参考資料：　「死刑」をキーワードに含む「高島章（弁護士）（@BarlKarth）」のツイート・リツイート（2008-09-25 18:50〜2016-02-10 14:18）「59」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/03/barlkarth2008-0.html
参考資料：　「金玉神社」をキーワードに含む「高島章（弁護士）（@BarlKarth）」のツイート・リツイート（2010-02-04 23:07〜2012-11-15 22:31）「18」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/03/barlkarth2010-0.html
参考資料：　「金玉踊り」をキーワードに含む「高島章（弁護士）（@BarlKarth）」のツイート・リツイート（2010-05-20 21:54〜2010-12-21 23:21）「9」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/03/barlkarth2010-1.html
参考資料：　「成仏」をキーワードに含む（法クラ・弁護士・ジャーナリスト関連）のツイート・リツイート（79アカウント、689件、 2011-12-19 23:30〜2016-03-17 18:19）「1-100／689」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/03/79689-2011-12-1.html
参考資料：　「成仏」をキーワードに含む（法クラ・弁護士・ジャーナリスト関連）のツイート・リツイート（79アカウント、689件、 2011-12-19 23:30〜2016-03-17 18:19）「101-200／689」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/03/79689-2011-12-2.html
参考資料：　「成仏」をキーワードに含む（法クラ・弁護士・ジャーナリスト関連）のツイート・リツイート（79アカウント、689件、 2011-12-19 23:30〜2016-03-17 18:19）「201-300／689」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/03/79689-2011-12-3.html
参考資料：　「成仏」をキーワードに含む（法クラ・弁護士・ジャーナリスト関連）のツイート・リツイート（79アカウント、689件、 2011-12-19 23:30〜2016-03-17 18:19）「301-400／689」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/03/79689-2011-12-4.html
参考資料：　「成仏」をキーワードに含む（法クラ・弁護士・ジャーナリスト関連）のツイート・リツイート（79アカウント、689件、 2011-12-19 23:30〜2016-03-17 18:19）「401-500／689」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/03/79689-2011-12-5.html
参考資料：　「成仏」をキーワードに含む（法クラ・弁護士・ジャーナリスト関連）のツイート・リツイート（79アカウント、689件、 2011-12-19 23:30〜2016-03-17 18:19）「501-600／689」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/03/79689-2011-12-6.html
参考資料：　「成仏」をキーワードに含む（法クラ・弁護士・ジャーナリスト関連）のツイート・リツイート（79アカウント、689件、 2011-12-19 23:30〜2016-03-17 18:19）「601-689／689」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/03/79689-2011-12-7.html
参考資料：　「ハナホジ」をキーワードに含む（法クラ・弁護士・ジャーナリスト関連）のツイート・リツイート（5アカウント、5件、 2015-09-19 21:29〜2016-02-19 10:19）「5」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/03/55-2015-09-19-2.html
参考資料：　「北斗の拳」または「消毒」をキーワードに含む（法クラ・弁護士・ジャーナリスト関連）のツイート・リツイート（12アカウント、23件、 2010-05-12 07:28〜2016-03-15 15:21） http://hirono-hideki.cocolog-nifty.com/blog/2016/03/1223-2010-05-12.html
参考資料：　「ピロシ（成仏理論の提唱者といわれる人物）」をキーワードに含む（法クラ・弁護士・ジャーナリスト関連）のツイート・リツイート（26アカウント、44件、 2009-04-15 11:12〜2016-03-14 20:35） http://hirono-hideki.cocolog-nifty.com/blog/2016/03/2644-2009-04-15.html
参考資料：　「ﾋﾟﾛｼ（成仏理論の提唱者といわれる人物）」をキーワードに含む（法クラ・弁護士・ジャーナリスト関連）のツイート・リツイート（2アカウント、4件、 2011-01-16 23:12〜2016-02-16 22:21） http://hirono-hideki.cocolog-nifty.com/blog/2016/03/24-2011-01-16-2.html
参考資料：　「高橋宏志（成仏理論の提唱者といわれる人物）」をキーワードに含む（法クラ・弁護士・ジャーナリスト関連）のツイート・リツイート（101アカウント、206件、 2009-08-20 10:11〜2016-03-17 20:36）「1-100／206」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/03/101206-2009-08-.html
参考資料：　「高橋宏志（成仏理論の提唱者といわれる人物）」をキーワードに含む（法クラ・弁護士・ジャーナリスト関連）のツイート・リツイート（101アカウント、206件、 2009-08-20 10:11〜2016-03-17 20:36）「101-200／206」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/03/101206-2009-0-1.html
参考資料：　「高橋宏志（成仏理論の提唱者といわれる人物）」をキーワードに含む（法クラ・弁護士・ジャーナリスト関連）のツイート・リツイート（101アカウント、206件、 2009-08-20 10:11〜2016-03-17 20:36）「201-206／206」件 http://hirono-hideki.cocolog-nifty.com/blog/2016/03/101206-2009-0-2.html

　関連性もあるので、前後のものを含めてまとめて掲載しました。

　参考資料：　「北斗の拳」または「消毒」をキーワードに含む（法クラ・弁護士・ジャーナリスト関連）のツイート・リツイート（12アカウント、23件、 2010-05-12 07:28〜2016-03-15 15:21）、というタイトルの記事からピックアップします。

［motoken_tw__20160321_0705_2／23のツイート］
％motoken_tw（モトケン）のツイート％投稿日時％2011-07-27 08:06:00％ツイートのURL％ https://twitter.com/motoken_tw/status/95993476579213312 ％
％motoken_tw（モトケン）のツイートの内容％
なくせという人はいないが、秩序維持機能が弱くなってもいいという人はいくらでもいる。自覚の無い人を含めて。RT @jisaburo: @motoken_tw 先生は秩序崩壊を”北斗の拳の世界”って言うけど、冤罪防止のために警察や司法を無くせという人は居ないと思うし、…
％データベースへの登録日時％2015-10-07 20:59:43％

　上記のモトケンこと矢部善朗弁護士（京都弁護士会）のツイートもまとめの作業に取り掛かるまで、すっかり忘れていたものでした。モトケンこと矢部善朗弁護士（京都弁護士会）らしい説教色の色濃い世界観がよく現れていると思います。

　モトケンこと矢部善朗弁護士（京都弁護士会）のツイートは2011年7月27に付けになっていて、私のデータベースの登録日時は2015年10月7日です。

　次は私のツイートで、小倉秀夫弁護士に向けたメンションを含んでいます。

［hirono_hideki__20160321_0705_3／23のツイート］
％hirono_hideki（廣野秀樹＼さらば弁護士鉄道・泥棒神社の夜）のツイート％投稿日時％2013-08-05 01:50:00％ツイートのURL％ https://twitter.com/hirono_hideki/status/364065716796141569 ％
％hirono_hideki（廣野秀樹＼さらば弁護士鉄道・泥棒神社の夜）のツイートの内容％
@hideo_ogura 余り見ていないので余り知らないのですが、漫画の北斗の拳にも流派があったと思いますね。一子相伝だったような気もしますが、小倉流の継承者らしい人も全く見かけたことがないです。歴史に対する侮辱にもなりそうですが、百万人といえども我いかん、ですか？
％データベースへの登録日時％2016-01-07 13:34:05％

　上記のツイートは今年つまり2016年1月7日のデータベースへの登録ですが、ツイートの日付が2013年8月5日になっていて、ずい分前だと意外に思いました。2年半以上前になりそうですが、私はすでに刑事弁護における「一子相伝」を意識していたようです。

　刑事弁護の師弟関係については、次のアカウントのことがきっかけで、深く考えた時期があったのですが、もうずいぶん前から非公開設定になっているはずです。「参考資料扱いにした過去の告訴状の下書き」でも重点的に取り上げた時期があるはずです。

碁を打って　一人佇む　風の精(@windspiritroula)さん | Twitter https://twitter.com/windspiritroula/

　囲碁といえばつい最近も人工知能との対決で話題になっていましたが、囲碁と聞いて私がまっさきに思い出すのは、元裁判官でもある木谷明弁護士のことです。比較的最近になって知ったように思いますが、囲碁の世界の名門の家柄という情報を見かけました。確認のため調べてみます。

／ ********************（引用開始）********************
引用URL＞＞＞＞：https://ja.wikipedia.org/wiki/%E6%9C%A8%E8%B0%B7%E6%98%8E 木谷明 - Wikipedia

棋士の木谷實の次男として生まれる。妹に毎日放送元アナウンサーでフリーアナウンサーの吉田智子がいる。

東京大学法学部在学中に司法試験合格し、1961年3月卒業。同年4月、司法研修所入所。司法研修終了後、1963年に判事補任官（東京地方裁判所）。その後浦和地方裁判所判事部総括や最高裁判所調査官などを歴任した後、東京高裁部総括判事となる。

2000年5月に退官、同年6月、公証人（霞ヶ関公証役場）となる。2004年4月より、法政大学法科大学院教授（2012年、定年退職）。2008年瑞宝重光章受章。2012年より弁護士。

刑事裁判の有罪判決が99.9%以上を占めると言われる日本の裁判所にあって珍しく人権派の裁判官として知られ、現役中に約30件の無罪判決を確定させた実績を持つ。彼は、日本の裁判官のほとんどが検察の言いなりに動いて有罪判決ばかりを出し、大量の冤罪判決を生み出し続けている現状について、「私はかなり多くの無罪判決を出しましたが、1件だけしか控訴されませんでした。でも、無罪判決にはたいてい検察官が控訴します。控訴されると無罪判決が破棄されることが多いのも事実です。控訴されない無罪判決を書くには技術が要ります。いろいろな事件で苦労してはじめて一人前の裁判官になると思うのですが、無罪判決を書く苦労をしていない裁判官が多いのは残念なことです。その結果、検察に物申すような裁判官が私の現役時代と比べて減ってしまいました。皆さん天下の大秀才なのでしょうが、腹の据わった裁判官はどこにいってしまったのでしょうね。この国の刑事司法の先行きが本当に心配です」と苦言を呈している[1]。

 ********************（引用終了）********************／

　長めの引用をしました。ここでは「棋士の木谷實の次男として生まれる」とだけ書いてあるので、私の知識と経験では将棋の棋士と完全に勘違いしそうでした。名前の部分がリンクになっていて、そちらで囲碁の棋士であることを確認するとともに、思っていた以上の大物のようです。

／ ********************（引用開始）********************
引用URL＞＞＞＞：https://ja.wikipedia.org/wiki/%E6%9C%A8%E8%B0%B7%E5%AF%A6 木谷實 - Wikipedia

木谷 實[注釈 1]（きたに みのる、1909年1月25日 - 1975年12月19日）は、囲碁の棋士。兵庫県神戸市出身、鈴木為次郎門下、九段。木谷道場主催。紫綬褒章受章。従四位勲二等瑞宝章。日本棋院囲碁殿堂入り。大倉喜七郎賞。

20世紀の棋士の中でも指折りの存在とされており呉清源と共に大正時代から活躍。また、自宅を木谷道場として内弟子をとりタイトルを争うトップ棋士から普及に専念する地方棋士まで多くの棋士を育てた。

弟子たちは1970年代初頭から1990年代半ば頃までタイトル戦線を席巻し、現在孫弟子まで含めた一門のプロ棋士は50人以上、段位の合計は500段を突破している。

 ********************（引用終了）********************／

　囲碁といえば他に、平成3年ころには知っていた「昭和維新（青年日本の歌）」に「世は一局の碁なりけり」という歌詞を思い出すことも多いです。福井刑務所にいるとき、囲碁を覺えたいと思ったのですが、五目並べではない碁はルールが難しすぎると聞いて断念したこともありました。

　雑居房にいた時のことで、居房には娯楽として将棋と囲碁がおいてありました。私は将棋も弱かったですが、囲碁はもっと難しいと聞いていたので、囲碁の達人というのはよほど頭がよく、先々の局面の見極めや判断の出来る自分とは頭の構造が違う人なのだろうと漠然と考えていました。

　最近では木谷明弁護士の名前をネットでも見かける機会がめっきり少なくなりましたが、もっとも注目したのがPC遠隔操作事件で佐藤博史弁護士と弁護団を組んだ時期のことです。佐藤博史弁護士については、本書で取り上げておく必要を感じておりますので、その機会にでもまた触れたいと思います。

　次がもう一つの「一子相伝」のツイートと並ぶ、衝撃的な出会いだったツイートです。深澤諭史弁護士のリツイートとして見たのが最初だったように思いますが、このノースライムというアカウントにもだいぶん前からブロックをされています。

［Noooooooorth__20160321_0705_5／23のツイート］
％Noooooooorth（ノースッラー）のツイート％投稿日時％2015-08-06 08:43:00％ツイートのURL％ https://twitter.com/Noooooooorth/status/629075216698703872 ％
％Noooooooorth（ノースッラー）のツイートの内容％
弁護士会にも「非弁は消毒だー！ ヒャッハー！！」くらいの気概が欲しいところである。
％データベースへの登録日時％2016-03-21 06:47:39％

　ツイートの内容は同じになりますが、次が深澤諭史弁護士のリツイートとしての登録情報です。

［fukazawas__20160321_0705_7／23のリツイート］
＞fukazawas（深澤諭史）のリツイート＞このリツイートの日時＞2015-08-06 10:30:00＞ URL＞ https://twitter.com/fukazawas/status/629102151365562368 ＞
＞fukazawas（深澤諭史）がリツイートしたNoooooooorth（ノースッラー）のツイートの内容＞
弁護士会にも「非弁は消毒だー！ ヒャッハー！！」くらいの気概が欲しいところである。
＞元のツイートの投稿日時＞2015-08-06 08:43:00＞元のツイートのURL＞ https://twitter.com/Noooooooorth/status/629075216698703872
＞データベースへの登録日時＞2016-03-21 06:47:02＞

　［fukazawas__20160321_0705_7／23のリツイート］の部分ですがまとめのスクリプトの実行時にプログラムとして生成した情報です。スクリプトの実行処理の時刻と全部で23件中7番目のものだということを記録と識別の情報として表しています。

　次が「一子相伝」をキーワードに含む、こたんせの衝撃的なツイートです。あるかと思ったまとめがなかったので、先ほど作成したところです。

［kotadon__20160327_1750_3／4のツイート］
％kotadon（こたんせ~メンタルリセット）のツイート％投稿日時％2015-07-16 13:13:00％ツイートのURL％ https://twitter.com/kotadon/status/621533092981817345 ％
％kotadon（こたんせ~メンタルリセット）のツイートの内容％
刑事弁護技術は一子相伝となり、師匠越えの儀式で、師を殺害した苦しみから、刑事弁護人は愛を捨てることになるのですね。分かります。 https://t.co/cnIHU0PHEV
％データベースへの登録日時％2016-02-07 23:56:24％

　上記のツイートは他の弁護士のツイートのURLを含んでいます。このURLのツイートのことは、ほとんど憶えていなかったのですが、言及の対象にもなっているので、簡易版で次に掲載しておきます。

T：yasumasa218（新谷泰真）：2015/07/16 12:10： https://twitter.com/yasumasa218/status/621517234037370881 ： 刑事事件，特に裁判員対象事件の減少と，弁護士人口増加に伴う一人頭の国選刑事事件の割り当て件数の減少によって，刑事弁護技術の伝承が危機に瀕して行く時代が来るのではないかと，密かに危惧している。

　これまでも深澤諭史弁護士のリツイートとしてちょくちょく見かけた来た弁護士アカウントですが、タイムラインを開くことは殆どなく、確認はしていませんが、ブックマークにも登録していないかもしれません。

　今、Twitterのプロフィールを確認したところ「元宮古ひまわり基金法律事務所所長。現在は渋谷区の桜丘法律事務所で執務しています。第二東京弁護士会所属。」とありました、見覚えのあるプロフの内容ですが、私の中で弁護士名と一致していませんでした。

　渋谷区の桜丘法律事務所、については「参考資料扱いにした過去の告訴状の下書き」から本書でも何度か取り上げてきたと思います。最近でも「上告審国選弁護人山口治夫の手紙」のことで取り上げているかと思います。

　その桜丘法律事務所の所長弁護士のTwitterアカウントですが、プロフィールの写真を見たところ、師匠や達人という風格を感じさせる人物です。最近は見かけませんが、こたんせ、が一緒に船釣りに行っているようなツイートをしていることもありました。

　さきほどのノースライムという匿名弁護士アカウントは、実名と顔写真を掲載したホームページのリンクをツイートに載せていたことがあり、記憶にないですが一度は名前を確認しました。こたんせは、実在が不明である上に、性別に疑問を抱かせるようなツイートも目にしています。

　記憶違いや勘違いで書いてはまずいので、確認のために調べてみましたが、普段、ツイートの更新が少ないと思っていた所長弁護士の、こたんせ、のメンションを含むツイートの数がずいぶんと多く、ツイートのURLの抜き出しを実行したところ、129件もありました。

from:okinahimeji @kotadon - Twitter検索 https://twitter.com/search?q=from%3Aokinahimeji%20%40kotadon&src=typd

　所長弁護士の最新のツイートを次のように記録しました。ブログへの投稿用に作成した最近のスクリプトの一つです。

% h-tweet-entry-hirono2016kwpcom-20160315.rb
％投稿者：okinahimeji（櫻井光政） 投稿日時：2016/03/27 14:09  ツイートのURL： https://twitter.com/okinahimeji/status/713956139294044160 ％
助平根性いなされて逆切れは爺百態の中で最も見苦しいが，幸せなことに本人に自覚はないのだな。 https://t.co/wdGWCoefhl
％ TwitterAPIによるデータ取得日時：　2016/03/27 18:34:09 ％

<blockquote class="twitter-tweet" lang="ja"><p>助平根性いなされて逆切れは爺百態の中で最も見苦しいが，幸せなことに本人に自覚はないのだな。 https://t.co/wdGWCoefhl</p>&mdash; 櫻井光政}（okinahimeji）<a href="https://twitter.com/okinahimeji/status/713956139294044160">2016/03/27 14:09</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

===========================================================
このツイートの投稿ユーザのプロフィール情報（2016年03月27日18時34分10秒頃の取得）：
-----------------------------------------------------------
-----------------------------------------------------------
[name]ユーザ名称：櫻井光政
[screen_name]ユーザ名：okinahimeji
位置情報：
ユーザ説明：
渋谷・桜丘法律事務所の所長弁護士。認証保育所「きらきら保育園」理事長。会計人コース/中央経済社と季刊刑事弁護/現代人文社にコラムを連載中。季刊刑事弁護のコラムをまとめた単行本「刑事弁護プラクティス」，好評発売中。
ユーザのフォロワー数：2780
ユーザのフォロー数：127
ユーザがTwitterに登録した日時：2012-03-18 12:51:54 +0900
ユーザの投稿ツイート数：7407

===========================================================
===========================================================

https://hirono2016k.wordpress.com?p=1185
追加しました。　＞＞＞ 櫻井光政さんはTwitterを使っています: "助平根性いなされて逆切れは爺百態の中で最も見苦しいが，幸せなことに本人に自覚はないのだな。 https://t.co/wdGWCoefhl"
NS:~

　ツイートの本文だけ読んでも意味がわからなかったのですが、ここでもURLが引用されている他のツイートの内容を見て、2,3日前からの巫女つながりの政治家の失言問題だとわかりました。

　「参考資料扱いにした過去の告訴状の下書き」に書いたと思いますが、櫻井光政弁護士の一つのツイートを見たことがきっかけで、NHK連続テレビ小説あまちゃん、を視聴するようになり、以降各方面に渡って影響を受けたという経緯もありました。

　時刻は19時57分になっています。宇出津新港まで買い物に行き、さきほど帰ってきたところです。今夜は少しましかと思いましたが、夜と朝は寒い日が続いています。寒いといっても部屋の中でキーボードを打つ指が寒さでかじかむことはまずないので、ほどほどの寒さです。

　今回の冬は、外でも手袋をほとんど使わずバイクにより、カイロは一度も使いませんでした。水道の水の冷たさも余り気にならなかったので、暖冬とは言え、体が慣れた面もありそうな気がしています。

　家にはずっと前から給湯器がなく、羽咋市のアパートから戻った頃は、洗い物の水の冷たさが冬場は気になってなりませんでした。母親の指がずいぶんとごつごつしていたことを思い出し、同じようになるのかと考えていましたが、指はきれいな状態のままです。

　思い出すのは刑務所にいる頃は、冬になるとよくしもやけになっていたことです。魚釣りに行くとそれ以上に指先の感覚がなくなるぐらい冷たく感じることが多いのですが、不思議としもやけになることはないです。クリームのたぐいもここ数年使うことがなくなりました。

　慣れといえば、モトケンこと矢部善朗弁護士（京都弁護士会）のこともありますが、羽咋市に生活していた頃は、モトケンこと矢部善朗弁護士（京都弁護士会）のことを脅威にも感じていたし、理解を求めるための努力もしていたつもりです。

　同じ能都町出身の被告訴人らに対しても危機感を常に持っていて、買い物に行った時も、顔を合わせないか気にいていたものです。羽咋市には5年ちょっと生活をしていましたが、宇出津のあばれ祭りにも一度も帰りませんでした。

　2009年の3月15日に羽咋市から宇出津に戻って、その年の8月31日の早朝に母親が脳出血を起こし、半身不随の寝たきり状態になり、今も入院中ですが、それ以来家に戻ったこともありません。精神的な変調はまだ羽咋市に住んでいた頃から聞いていました。

　統合失調症のような診断ではなかったかと思います。近所の人に迷惑を掛けたような話も役場の担当の人から聞いていました。能登町役場と行っても、松波庁舎の人でした。名前の方も忘れましたが、以前は夕方の遅い時間に、Aコープ能都店で買い物している姿を見かけることがありました。

　私の場合、自分自身が起こした事件だったので、誰よりも納得できることやよく知る事実関係も多かったのですが、母親の立場だと不安と絶望だけが大きくなって、精神も壊れていったのだと思います。

　母親のことで印象的に憶えているのは、まだ倒れる前の2009年6月頃のことで、その時は名前も知らなかった能登警察署の大家警部補が自宅に訪ねてきて、私は珠洲市の職業訓練から戻ったところで、訪問のあったことを母親から聞かされたのですが、その時は本当にうれしそうな顔で話していました。

　その後で、しばらくしてから大家警部補の再度の訪問があって、その時に初めて顔を合わせました。同行者の刑事がもう一人いて二人で来ていましたが、もう一人の刑事の顔は、その後見かけることがなかったように思います。同じような年頃に見えましたが、大家警部補の方が立場が上のように見えました。

／ ********************（引用開始）********************
引用URL＞＞＞＞：https://ja.wikipedia.org/wiki/%E8%83%BD%E7%99%BB%E8%AD%A6%E5%AF%9F%E7%BD%B2 能登警察署 - Wikipedia

能登警察署（のとけいさつしょ）は、石川県警察がかつて管轄していた警察署の一つである。

2012年4月1日に珠洲警察署と統合し廃止。現在は、珠洲警察署能登庁舎となっている。

 ********************（引用終了）********************／

　たびたびネットで調べて確認をしないと正確な年を忘れてしまうのですが、2012年の4月1日にそれまでの能登警察署は廃止になり、珠洲警察署に統合されました。建物自体は今も残っていて一階だけは交通関係の警察官が何人か常駐しているようです。免許証の更新にもそちらでやりました。

　モトケンこと矢部善朗弁護士（京都弁護士会）を名誉毀損で告訴するため相談に行ったのも2012年の3月の中頃で、移転する前の半月ほど前だったことになりますが、その前から大家警部補の姿はなく、年度替わりに移転したように電話で聞いていました。

　2010年か2011年の4月付での転勤ということになりそうですが、どちらの年であったのかも、現在の私の頭の記憶からは思い出すことも出来ません。

　中断していました。3月28日の時刻は18時37分です。いささか強引な舵取りですが、次に進めます。

2016-03-28　月曜日　18：38　＜＜ ［［　←これまでの記述範囲の終了時刻］］＜＜
**** 成仏理論と弁護士鉄道／被害者AAさんの父親AKさんの立場で考える、伝えたい、性と暴力：家族　親告罪の壁、泣き寝入り（京都新聞）、という記事について 

:CATEGORIES: 被害者AAさんの父親AKさん,金沢地方検察庁提出告訴状の下書き
:TAGS: 告訴状の下書き／2016年,深澤諭史弁護士

2016-03-28　月曜日　18：46　＞＞ ［［　←これからの記述範囲の開始時刻］］＞＞

　昨夜は電気とテレビをつけたまま眠ってしまい、今朝起きたのは5時半ぐらいでした。昼過ぎに家を出て、母親のいる病院に向かい、ラーメン屋で食事を済ませてから病院に行って戻りました。

　朝のうちは、深澤諭史弁護士とモトケンこと矢部善朗弁護士（京都弁護士会）のTwitterのタイムラインにほとんど更新がなかったこともあり、久しぶりに奥村徹弁護士のタイムラインを開いてかなり前まで遡り、いくつかの発見と本書で取り上げたい問題点がありました。

　出かける前だったように思いますが、モトケンこと矢部善朗弁護士（京都弁護士会）のTwitterのタイムラインにもいくつか更新があって、取り上げたいツイートが２つほどありました。それはのとほど掲載と多少の言及をしたいと思います。

　夕方はいったん家に戻って少ししてから、二つの町内会長の家を探して、土曜日の夜にあずかっていた封筒を渡しに行っていました。2件だけでしたが、それでも多少手間が掛かり、まだ日の明るいうちに探しに出かけたことは正解だったと思いました。

　用事を済ませて家に戻ってからも弁護士らのタイムラインのツイートを眺めていましたが、特に深澤諭史弁護士とモトケンこと矢部善朗弁護士（京都弁護士会）のツイートの更新は数が減った感があります。

　その中から、深澤諭史弁護士の気になったリツイートと取り上げてご紹介しておきたいと思います。さほど重要度が高くないこともあり、簡易版での掲載としておきます。

R：fukazawas（深澤諭史）＞2016/03/27 10:24＞ https://twitter.com/fukazawas/status/713899889940299776 ＞ keita_adachi （弁護士あだちけいた）＞ https://twitter.com/keita_adachi/status/713899550105178112 ＞ 要するに親告罪自体が壁なのではなく告訴期間制限が壁という記事内容だけど。非親告罪にしても詳しい説明を求められることは変わらないし、初犯実刑になるかも別だし。＜改行＞＜改行＞伝えたい、性と暴力：家族　親告罪の壁、泣き寝入り（京都新聞）  https://t.co/pCrOYU4xUg

R：fukazawas（深澤諭史）＞2016/03/26 23:12＞ https://twitter.com/fukazawas/status/713885025805033472 ＞ miyazakilove12 （ｼﾞｬｽﾃｨｽ）＞ https://twitter.com/miyazakilove12/status/713730454537437186 ＞ 司法修習給費制度復活＆少なくとも行政公務員様よりもメリットがないと、若者は成仏理論が妥当するとされる司法試験や法曹を目指しませんよ。司法官僚(主に裁判官)は、世間知らずの金持ちだから分からないのですかね。5月の司法試験の実受験者数や4月の法科大学院実入学者数発表が楽しみですね。

　まずは上記2件の深澤諭史弁護士のリツイートです。ツイートの時間も連続したツイートですが、＞2016/03/26 23:12のリツイートの方は、たまたま隣接していたというおまけのようなものです。

　メインは、R：fukazawas（深澤諭史）＞2016/03/27 10:24＞ https://twitter.com/fukazawas/status/713899889940299776 ＞ keita_adachi （弁護士あだちけいた）＞、のリツイートです。

　弁護士あだちけいた、というアカウントもだいぶん前から廣野秀樹＼さらば弁護士鉄道・泥棒神社の夜（@hirono_hideki）の私の3つのうちの1つのアカウントでブロックされていることを確認しています。

　いずれ言及したいと考えているのですが、弁護士あだちけいた、というアカウントについては、NHK連続テレビ小説まれ、についてずいぶんと酷評していたことでも、注目したことがある弁護士アカウントで、渋谷の桜丘法律事務所の所長弁護士の、あまちゃんのことでもつながる点があります。

　昨年つまり2015年放送だったNHK連続テレビ小説まれ、は同じ能登半島の輪島市が舞台のドラマでしたが、東京から小学生の頃に家族で移住してきた女性が主人公でした。連続テレビ小説が、女性の生涯や半生の生き様を描くドラマであるということも、あまちゃん以降に知ったように思います。

　その連続テレビ小説まれ、を観ながら頭に浮かんできたことの一つが、私の母親も子供の頃に京都市から能登の宇出津に移住してきたと子どもの頃から聞いていたことです。中学生の頃と聞いたような記憶もあるのですが、はっきりした時期はわかりません。

　母親は昭和4年の1月19日生まれなので、太平洋戦争の終戦前に宇出津に来たと考えられ、疎開を兼ねていたのかと考えていたこともありましたが、私の方から細かいことを話題にして尋ねたこともありませんでした。

　能登警察署の大家警部補から関係者の名前を出すな、匿名にしろと言われたことで、2009年（平成21年）の9月から、非公開のプライベートモードに設定していた、はてなダイアリーのブログを今年になって公開モードにしたのですが、その夜に母親の末の妹のおばさんから電話がありました。

　これは良い機会だと思って、愛知県に住むおばさんにいくつか質問をしたのですが、京都から来たのは5人兄弟のうちに3人までで、兵庫県のおじさんと自分は宇出津に来てから生まれたので、京都から引っ越してきた正確な時期はわかないと話していました。

　それらしいことは知っていましたが、この時のおばさんの話で初めて知ったことは、もともとは京都で西陣織の仕事をしていて、宇出津から出稼ぎ奉公を受け入れていて、奉公人のためにも宇出津で織物工場の仕事をしたことがよいという話になって、移住してきたとのことでした。

　宇出津には遠縁の親戚もあってその人の世話になったという話も聞きましたが、それとは別にずっと前に、宇出津の常椿寺の人の世話で宇出津に来ることになったと聞いていたことがありました。

　宇出津は小さい町の割に寺の数が多いです。同じ能登町で町の規模は小さくなる小木では、寺は一つしかないと聞いています。

　2009年の9月の10日ころに、母親が寝たきりの状態で珠洲の総合病院に入院したことで母親の兄弟が集まりました。その時だったと思いますが、宇出津の天徳寺に行って、祖父母の納骨を京都に移すような話をされ、5千円を渡されて寺に相談に行くように頼まれました。

　なんとなく行く気がしなかったので、そのままずっと放置していました。次に京都の親戚が能登に来たのは2,3年後だったと思いますが、長男のおじさんの位牌を持ってきた時でした。

　その時に3番目の兄弟の母親の妹のおばさんに、頼まれた寺には 行っていないと、小さい封筒に入っていた5千円をそのまま返しました。京都に住んでいるおばさんです。

　その兄弟3番目のおばさんも、数年前に体を悪くして大変な状態になっていると愛知県の末娘のおばさんから聞いていました。昨年中だったと思いますが、一度電話で連絡があり、いくらか持ち直して退院して家にいるけど、心臓が悪く普通に話すことが出来ない状態と聞いていました。

　2013年の8月13日になると思います、ずっと12日と勘違いしていたのですが、1年ぐらいに13日が正確だと確認しています。過去の記述でも読まない限り正確に思い出せなくなっていますが、その日の早い時間に珠洲警察署に電話を掛けて、今から相談に向かうと言って電話を切りました。

　珠洲警察署の担当者への電話を切った直後に電話が掛かり、掛けてきたのがその3番目の母親の妹のおばさんでした。その当時で年に2,3回の電話だったと思います。

　とても偶然とは思えないタイミングでの京都からの電話でしたが、ふと思いついて前から気になっていたことを、母親の兄弟の3番目のおばさんに尋ねました。

　平成4年に金沢刑務所の拘置所にいた頃、面会の時だっと考えられますが、母親の口から聞かされた話では、控訴審の私選弁護人となった被告訴人木梨松嗣弁護士は、その母親の兄弟の3番目のおばさんの旦那さんの紹介だと聞かされていたのです。

　より可能性の高いのは拘置所に移管される前の、金沢西警察署での面会の時で、初めの1,2回の京都の親戚が費用を工面してくれるので私選の弁護士をつけろという話が母親からあったときのことです。その1,2回の面会の時は断っていました。

　そのあと、私はよくよく考えて考え方を変え、それならば私選の弁護士に頼みたいと母親に言ったところ、その弁護士からの伝言ということで、国選弁護人が決まってしまっているので弁護士を変えると裁判官の印象を悪くするのでやめた方がよい、と聞かされました。

　この続きは、被告訴人に加えることを今年の年始の頃に決めている国選弁護人、岡田進弁護士（金沢弁護士会）を中心に取り上げる機会に記述したいと思います。深澤諭史弁護士のツイートに説明を戻します。

T：fukazawas（深澤諭史）：2016/03/28 17:30： https://twitter.com/fukazawas/status/714369117180919808 ： 読者が誤解をしないように，ちゃんと，記者は記事を作るべきだと思うのですけれどねぇ。

T：fukazawas（深澤諭史）：2016/03/28 17:13： https://twitter.com/fukazawas/status/714364712985579520 ： 伝えたい、性と暴力：家族　親告罪の壁、泣き寝入り（京都新聞） - Yahoo!ニュース https://t.co/tBAAOUz3RO #Yahooニュース＜改行＞＜改行＞「親告罪である限り、本人がつらさを乗り越えて証言できなければ訴えられない」＜改行＞いや，これは，関係が無いと思います。

　上記の2件が、夕方の早い時間に家に戻ってから目にした深澤諭史弁護士自身のツイートです。17時13分と17時30分の投稿時刻になっています。

　リンクの記事は深澤諭史弁護士のリツイートでの、あだちけいた弁護士のツイートを見てすぐに、リンクを開いて内容に目を通しました。まず違和感を感じたのは、親告罪の問題に結び付けられている点です。

　記事を読んだところ明らかに強制わいせつ罪の公訴時効の問題ではないかと思います。

　強姦罪と強制わいせつ罪は法定刑の上限もかなり違っていますが、強姦罪の場合でも平成10年代の半ばの頃までは、親告罪として犯人を知った時から6ヶ月以内という強制法規としての制限が掛けられていたはずです。法改正でその制限が綺麗さっぱり撤廃されたはずです。

　この親告罪の告訴期間の制限については、私自身、1,2年はほど前まで、同じ親告罪の名誉毀損と混同して不十分な理解をしていたため、よく憶えています。

　URLとして引用された元記事には、公訴時効と思われる7年について警察から連絡があったとか、強制わいせつ罪の初犯では執行猶予がつく可能性が高いという内容がありました。

　本当に警察官がそんなことを言ってきたのか疑問の記事です。強制わいせつ罪の初犯では執行猶予がつく可能性が高い、という話は本当なのかもしれませんが、実父による性犯罪となれば犯情も格段に重くなると考えられるからです。

　何日前になるのか正確に思い出せませんが、まだ半月は経っていないように思いますが、尊属殺人の違憲判断につながった栃木の事件についての記事を目にしました。直接の引用はなかったように思いますが、初めに見たのは落合洋司弁護士（東京弁護士会）のツイートだったように思います。

　落合洋司弁護士（東京弁護士会）はツイート数が比較的少ないので、探しだすのもそう時間がかからないと思うので、タイムラインを遡って今から探します。

ツイート：yjochi（落合洋司（オンラインチャット相談対応可））：2016/03/16 07:53： https://twitter.com/yjochi/status/709875079253864448 ： しみじみと読んだ。 https://t.co/KufNyWOf0l

　思ったよりタイムラインのツイートの数が多く、手間取りましたが、探しだすことが出来たのが上記の落合洋司弁護士（東京弁護士会）のツイートです。ちょうど140文字だったので、告発-金沢地方検察庁御中_ツイッター（@kk_hirono）にも投稿できました。

　しみじみと読んだ。、というだけで、リンクのURLがあるだけのツイートです。リンクは短縮URLだので、これだけの情報ではさっぱりわかりません。次に正確な記事のタイトルとURLを取得して掲載します。

日経ビジネスオンラインさんはTwitterを使っています: "【「父殺しの女性」を救った日本初の法令違憲判決】当時、尊属殺人は、《死刑又ハ無期懲役ニ処ス》と規定されていた。 https://t.co/3dU4qAEjFj #日経ビジネス https://t.co/ockA1bJyr2" https://twitter.com/nikkeibusiness/status/709872573488570369

　落合洋司弁護士（東京弁護士会）のリンクは記事本体のURLではなく、元の記事を紹介したツイートでした。アカウントは「日経ビジネスオンライン」です。これでは文字数オーバーになるので、記事本体のタイトルとURLを取得します。

「父殺しの女性」を救った日本初の法令違憲判決：日経ビジネスオンライン http://business.nikkeibp.co.jp/atcl/report/15/120100058/120200001/

　ツイートから開いたリンクはリクエストパラメータがついていて長すぎたので、それを削除しましたが、同じ記事の内容は表示できました。なかなか衝撃的なタイトルかと思います。

　私は平成6、7、8年頃の時点でこの最高裁判決のことは知っていました。佐木隆三氏の殺人百科か事件百景という文庫本の中で、読んだように思います。

　そういえば、金沢刑務所から福井刑務所に移送される前後に、佐木隆三氏の「勝ちを制するに至れり」という本と「新選組事件貼」というようなタイトルの本を購入か母親の差し入れとして読んだ憶えがあります。

　漢字が間違っているような気もしますが、「新選組事件貼」という本は、手紙で佐木隆三氏の作品として母親に差し入れを頼んでいたところ、郵送で差し入れがあったように思います。

　佐木隆三氏に関しては、まだ金沢刑務所の拘置所にいた頃に、購入で文庫本ではない大きな本として島根県だったと思いますが、えん罪をテーマにした「闇の中の光」というようなタイトルの本を読みました。特に印象に残っているのは弁護人の手弁当という言葉です。

　刑務所や拘置所で関心の分野の本を探すのは困難でした。新聞の広告欄でメモした本を私本購入で求めることも多くあったと思います。拘置所も刑務所も同じだったと思いますが、私本の購入は一度に6冊までで、それが月に1回か2回でした。どちらかも自信を持って思い出せなくなっています。

　私本購入の注文は一度に6冊でしたが、実際に入るのはそのうち1,2冊が多かったように思います。欲しい本が入るかどうかも楽しみでしたが、求める情報の価値というのは何段階もの障害があって、身にしみて思い知らされる体験でした。

　そういえば、今日の午前中はモトケンこと矢部善朗弁護士（京都弁護士会）のツイートがきっかけで、「弁護士倫理」とかいう専門書を福井刑務所にいるとき購入したことを思い出しました。購入か母親からの郵送の差し入れだったかは、正確に思い出せなくなっています。

　まず先に取り上げるつもりでいたのは、次のモトケンこと矢部善朗弁護士（京都弁護士会）の２つのツイートです。病院から帰ってきて、とりあえず深澤諭史弁護士のツイートに優先度を上げました。

T：motoken_tw（モトケン）：2016/03/28 13:00： https://twitter.com/motoken_tw/status/714301077210804224 ： 隣に座っている人間が、人を殺せば処罰されるけどばれなきゃ平気だ、と考える人間か、神様が見ているから人を殺したら地獄に堕ちると信じている人間か..「アメリカ人に信仰を持ってないというと「信じられない！」と驚かれた。しかし、宗..」 https://t.co/gGaZq62wLZ

T：motoken_tw（モトケン）：2016/03/28 12:46： https://twitter.com/motoken_tw/status/714297618529058817 ： @tyokorata 自分が信じている宗教と他人が信じている宗教の区別ができるからでは？

T：motoken_tw（モトケン）：2016/03/28 12:37： https://twitter.com/motoken_tw/status/714295377499856896 ： 倫理観の根底に絶対的価値観のない人は信頼できない、ということではないのかな。「アメリカ人に信仰を持ってないというと「信じられない！」と驚かれた。しかし、宗..」 https://t.co/5X1vlxAEgT

　２つだと思っていましたが、コピペのためにデータを取り出すと３つでした。上記３つのツイートのうち2件目だけ、ぎりぎり140文字でツイートできました。

　その2件目のツイートですが、意識に残っていないツイートで、メンションが入っていました。

　このメンションや他のアカウントのツイートのURLが入っていると、反応が来ることがあります。今日もそれがあって、「 また君か…」という内容のツイートでした。

　ちょっと気になったので、そのメンションを送ってきたアカウントのタイムラインを開き、いくらか遡ったところ、リツイートでしたが、ゲゲゲの鬼太郎のことで驚くツイートを発見しました。

　廣野秀樹＼さらば弁護士鉄道・泥棒神社の夜（@hirono_hideki）のアカウントとして本日リツイートしているツイートですが、確認のために「ゲゲゲの鬼太郎」との組み合わせで、「キンタマ」「金玉」でGoogle検索をしました。

　情報の正確性を確認することは出来なかったのですが、それとは別に「チンポ」という情報を発見し、バラエティ番組で取り上げられたYouTube動画も一通り視聴しました。

　近年「放送禁止用語」という言葉を見聞きする機会も少なくなっているだけに、本当なのかと驚きもしたのですが、そのあたりは連続テレビ小説まれ、の一場面がきっかけで知った「チャンペ饅頭」と一緒に後日取り上げて言及したいと予定しています。

　「巫女」というキーワードとも関連するのですが、平成10年の終わり頃、金沢市間明の野田専光寺線沿いの焼肉店で被告訴人KYNに言われた「たった一つのチャンペが忘れられん男や」という嘆息の発言とも、鉄工所と呼ばれていた被害者AAさんの父親AKさんとも関連します。

　そういえば「緊急告知　我が娘が鬼となる」というフレーズも思い出しました。「世界をとるの」というハチマキをつけた化物のようなタコの演出で、昼過ぎに出かける前は、輪島市の曽々木海岸のこととPC遠隔操作事件における佐藤博史弁護士のことを思い出してもいました。

　佐藤博史弁護士といえば、2,3日前にもモトケンこと矢部善朗弁護士（京都弁護士会）が尊敬する、というツイートを久しぶりに探しだして確認していたところです。

　ちょっとパソコンのシステム内を次のように探してみました。locateコマンドのデータベースは、ここ一月ぐらいは更新していないと思います。

NS:~
[1503]  % locate 尊敬
/home/a66/git/kk_hirono_2016/a_資料/a_スクリーンショット/2016-03-27-083127_モトケンさんはTwitterを使っています：　”佐藤弁護士を批判ないし非難するツイートも流れてくるが、私は佐藤弁護士を尊敬する。　佐藤弁護士.jpg
/home/a66/git/kk_hirono_2016/a_資料/a_スクリーンショット/2016-03-27-083158_モトケンさんはTwitterを使っています：　”佐藤弁護士を批判ないし非難するツイートも流れてくるが、私は佐藤弁護士を尊敬する。　佐藤弁護士.jpg
/home/a66/kk_hirono/告訴状の内容に関連したスクリーンショット/2014年5月分/2014-05-25-092147_佐藤弁護士を批判ないし非難するツイートも流れてくるが、私は佐藤弁護士を尊敬する.jpg
/home/a66/kk_hirono/告訴状の内容に関連したスクリーンショット/2015年1月分/2015-01-03-213103_佐藤弁護士を批判ないし非難するツイートも流れてくるが、私は佐藤弁護士を尊敬する。.jpg

　locateコマンドのデータベースは最近更新していないつもりでいたのですが、3月27日付というファイル名が出てきたので、どうかと思います。updatedbというコマンドを管理者権限で実行する必要があるはずなのですが、昨日中に実行した記憶はないからです。

　ともあれ、自分のパソコンのシステム内での検索は簡単で早いです。

　「参考資料扱いにした過去の告訴状の下書き」には何度か記述をしていると思いますが、被告訴人HTNの「お前、あの女の顔見て普通じゃないってわからんか？　きっかん顔しとるやろがい。わっしゃどうも好きになれん。」という言葉も関連しています。

2016-04-02　土曜日　05：34　＜＜ ［［　←これまでの記述範囲の終了時刻］］＜＜
**** 成仏理論と娑婆捨て峠／被害者AAさんの父親AKさんの立場で考える／平成４年４月１日の傷害・準強姦被告事件と弁護士業務の犯罪性・岡田進弁護士の被告訴人追加

:CATEGORIES: 被害者AAさんの父親AKさん,金沢地方検察庁提出告訴状の下書き
:TAGS: 告訴状の下書き／2016年,奥村徹弁護士,モトケンこと矢部善朗弁護士（京都弁護士会）,ジャーナリスト江川紹子さん

2016-04-02　土曜日　05：52　＞＞ ［［　←これからの記述範囲の開始時刻］］＞＞

　告発-金沢地方検察庁御中_ツイッター（@kk_hirono）の投稿を確認したところ、3月28日21時52分頃からの中断、再開ということになるようです。3月31日には午前中に、金沢地方検察庁と珠洲警察署にこれからのことについて電話をしました。

　いろいろと関心の高い事件報道や社会問題があったり、慌ただしさを感じる数日間でしたが、4月の前半は地元宇出津の曳き山祭りの祭礼に関わることもあり、不慣れなこともあってさらに慌ただしさを感じそうです。

　季節の変わり目の気温差で、睡眠時間が不規則になることが増えています。今日も夜中の2時半ころに目がさめてしまい、そのまま眠れずにいます。しばらくは二度寝を試みていたのですが、諦めてパソコンをつけたところで、目に入ったのが次の奥村徹弁護士のツイートです。

％okumuraosaka（TORU OKUMURA）のツイート％投稿日時％2016-04-01 22:54:00％ツイートのURL％ https://twitter.com/okumuraosaka/status/715900154952286208 ％
％okumuraosaka（TORU OKUMURA）のツイートの内容％
わいせつ行為とか姦淫を強要されたという強要罪で、実刑になったら、親告罪の告訴無しだという主張をしてくださいよ。公訴棄却を求めるわけで不利益主張にはならないから。
％データベースへの登録日時％2016-04-02 02:52:19％

　奥村徹弁護士についてはこれまで「参考資料扱いにした過去の告訴状の下書き」でも何度か取り上げて来たと思いますが、何をどの程度、言及したのかとなると正直よく憶えていません。「精神鑑定をするのはとっぽどおかしい」というのは比較的最近にも取り上げたような気がします。

　自分のパソコンのシステムを調べると、次のようなファイルが見つかりました。ここで思い出したことですが、奥村徹弁護士によってツイートが削除されたものと勘違いをした時期があって、確認を徹底して調べたところ削除されていないことがわかったという経緯もありました。

[1755]  % locate とっぽど
/home/a66/git/kk_hirono_2016/a_資料/a_スクリーンショット/2016-03-07-144817_％　grep　-r　-C　2　’とっぽどおかしい’　。／＊。org.jpg
/home/a66/kk_hirono/ブログ（wordpress）/c投稿済み/精神鑑定ってさあ、とっぽどおかしい場合じゃないと採用されない。（削除されたツイート）／奥村徹弁護士.html
/home/a66/kk_hirono/ブログ（wordpress）/hirono2014k/c投稿済み/精神鑑定ってさあ、とっぽどおかしい場合じゃないと採用されない。（削除されたツイート）／奥村徹弁護士.html
/home/a66/kk_hirono/告訴状の内容に関連したスクリーンショット/2015年8月分/2015-08-09-123520_このページは存在しません。→　精神鑑定ってさあ、とっぽどおかしい場合じゃないと採用されない。.jpg
/home/a66/kk_hirono/告訴状の内容に関連したスクリーンショット/2015年8月分/2015-08-09-124227_TORU　OKUMURAさんはTwitterを使っています：　”精神鑑定ってさあ、とっぽどおかしい場合じゃないと採用されない。”.jpg
/home/a66/kk_hirono/社会・世相・時代の参考情報/奥村徹弁護士/Twilog-精神鑑定ってさあ、とっぽどおかしい場合_2013年08月20日13時40分06秒.jpg
/home/a66/kk_hirono/社会・世相・時代の参考情報/奥村徹弁護士/精神鑑定ってさあ、とっぽどおかしい場合じゃないと採用・・・.jpeg
/home/a66/kk_hirono/社会・世相・時代の参考情報/弁護士/精神鑑定ってさあ、とっぽどおかしい場合じゃないと採用されない。_2.jpeg

　また、記憶が薄れていますが、周辺の事情として刑法学会のような場において投稿されたツイートで、落合洋司弁護士（東京弁護士会）ともやりとりがあった際のものであったようにも思います。手間もかかるので十分な確認作業はしない上での話です。

　この「とっぽどおかしい場合」というツイートの前後で、私が2010年4月にTwitterを始めてそれほど経っていない頃だったようにも思うのですが、性犯罪の被害者家族との示談について、人間とはそういうものだ、というような深くえぐられるようなツイートを目にしたということもありました。

　そのツイートは探し出せていないように思います。今確認したところ、奥村徹弁護士のツイートは94,235件で、2009年7月に登録、となっていました。キーワードで調べたこともあったのですが、これはと思えるものを見つけることが出来なかったように憶えています。

　奥村徹弁護士は弁護士として性犯罪という特定分野に特化したスペシャリストであり、弁護士としての経営にも大成功をしているのではということを余裕とともに感じることがしばしばです。まさに商売繁盛ではないかということで、いろいろと考えることも多いです。

　2時半ころに目が覚めるまではテレビと電気をつけたまま寝ていました。録画で再生していた朝の情報番組「スッキリ」を観ながらいつの間にか、寝落ちていました。まだ、起きているうちに注目したのが芸能人の離婚裁判で、代理人弁護士の姿を見たことです。

　時刻は10時25分になっています。二度寝をして9時40分ぐらいに起きていました。弁護士のタイムラインのツイートを少しみて、それからテレビでケンミンショーを見ていました。

　その前に新聞のテレビ欄に軽く目を通していて、4種類のお雑煮がある県という見出しがあって、鹿児島県だとその場で思い込みました。適当にチャンネルを変えて、そのケンミンショーの再放送を見たのですが、ちょうどお雑煮のことをやっていて、それは島根県でした。

　4種類の雑煮の初めのところから見ていたのですが、以前夜の放送で見たものだと気がつくのに時間がかかり、見覚えのないような内容の場面もいくつかありました。その後のコーナーでは山形県の、そばとゲソ天の紹介でした。

　それも視聴済みの番組内容であることを思い出しましたが、明らかに見落としていたのか頭に入っていなかった情報がありました。それは、もりそばの量のことで、東京で180グラムが一般的なのに対して、山形では400グラムが一般的で500グラムでも普通盛りの店があるとのことでした。

　この番組では他にも発見がありました。山形県が4つの地方にわかれているということを知ったのは、あとで調べてからのことです。ゲソ天の歴史的文化について最上地方と村上地方が地図入りで紹介され、どちらも内陸部で山形市のあるあたりが村上地方になっていました。

　長距離トラック運転手をしていた私の記憶では、村上といえば日本海沿いの地域で、よくよく考えると山形県ではなく新潟県村上市でした。置賜地方というのは置賜という言葉自体、初めて見たように思いましたが、小国町や南陽市という、山形県内で最も通行していた地区というのが意外でした。

　山形県には特異な地域性があって、それが山形マット死事件に影響したという話を比較的最近になって知りました。今年に入ってからだと思いますが、テレビのお天気姉さんが、生放送中に泣きだし、それが陰湿ないじめが原因ではないかと取り沙汰されたことがきっかけです。

　もう一つ押さえておきたい大きなポイントがあって、名誉毀損で刑事告訴を決めているモトケンこと矢部善朗弁護士（京都弁護士会）が、その山形マット死事件の担当検事であったということです。

　単発だったと思いますが、最近にもモトケンこと矢部善朗弁護士（京都弁護士会）自身が、その山型マット死事件に対する自己評価のようなツイートをやっていました。

％motoken_tw（モトケン）のツイート％投稿日時％2016-03-06 11:42:00％ツイートのURL％ https://twitter.com/motoken_tw/status/706308963000684545 ％
％motoken_tw（モトケン）のツイートの内容％
.@Hideo\_Ogura @toshi\_fujiwara そうだと思います。山形マット死事件は、高裁、最高裁で、捜査についての問題は（少なくとも検察捜査の問題は）何も指摘されていませんね。つまり、藤原監督の誹謗中署には何の根拠もないということです。
％データベースへの登録日時％2016-03-07 04:49:43％

　3月6日のツイートということで思っていたよりつい最近のツイートでした。ここでも藤原監督が絡んでいたことを思い出しました。小倉秀夫弁護士も絡んでいますが、そちらは記憶にあり、どちらかといえば小倉秀夫弁護士が山型マット死事件をネタにちょっかいを出してきた印象があります。

　ここ数日はモトケンこと矢部善朗弁護士（京都弁護士会）と藤原監督との間に、朝霞少女誘拐事件の父親のことを巡って、注目の応酬があって、私の傷害・準強姦被告事件の被害者AAさんの父親AKさんの立場とも同じく犯行時の私の立場とも共通点があると考えていたところです。

　昨日の4月1日は、私の被害者AAさんに対する傷害・準強姦被告事件の24周年でありました。エプリーフールと言いましたが、嘘が許される年に一度の日ともされていますが、私は誤解を避けるためにも、その日は活動を自粛する傾向があります。

　そう言えば子供の頃、母親に「地獄の釜も休む日」だと銭湯の休業日のことを何度か聞かされていたのですが、それが8月15日だったように記憶にあります。今はそんな話など全く耳にしなくなり、8月の15日も宇出津の銭湯は普通に営業しているかと思います。ちょっと調べてみます。

／ ********************（引用開始）********************
引用URL＞＞＞＞：http://dictionary.goo.ne.jp/jn/95741/meaning/m0u/ 地獄の釜の蓋もあくの意味 - goo国語辞書

正月や盆の16日は、地獄の鬼も罪人の呵責 (かしゃく) を休むというところから、この両日はこの世の者もみな仕事をやめて休もうということ。

 ********************（引用終了）********************／

　内容に記憶違いはなかったようですが、8月16日を8月15日と勘違いしていたようです。新たな発見としては年に2度あって、もう一つは1月16日ということを知りました。

　閻魔大王とどういう関係があるのか、もう少し調べてみようと、次のページを開きました。

よく8月16日は地獄の釜も開くといいますが、どんな意味でしょうか。この日は地... - Yahoo!知恵袋 http://detail.chiebukuro.yahoo.co.jp/qa/question_detail/q138985388

　旧暦だと7月になるようですが、16日というのは地獄の鬼の年に2回の休日が終わった後のことで、閻魔大王にお休みのお礼とこれからも地獄の仕事に励むと報告に行くと書いてありました。釜が開くというのは鬼の仕事の再開になるので、前日の15日がやはり休みだったということになりそうです。

　母親にそんな話を聞かされていた頃というのは、辺田の浜の家に住んでいた頃、歩いて母親と宇出津の新町の銭湯に行っていた頃のことで、母親と一緒に女湯に入っていた頃のことでした。小学生の低学年でしたが、何年生まで入っていたのかは記憶にありません。

　宇出津の仙人町付近の長楽寺の仁王像を通りがかるたびに見ていたのも同じ頃のことです。罰が当たるとか悪事と地獄という世界が現在よりは身近な時代でした。仁王像のことは刑裁サイ太のことで取り上げているかと思います。刑裁サイ太は鬼法曹という言葉も使っています。

　かなり長い中断になっていましたが、まもなく再開をしたいと思います。時刻は4月18日14時49分です。

　時刻は4月30日8時47分になっています。18日の日に再開をするつもりだったのですが、そのまま中断していたことを確認しました。この間、いたずらに過ごしていたわけではなく、ようやく告訴状の構想、フレームワークのようなものが定まり、展望が開けていました。

　これまで作成してきた本書も告訴状の本文からは除外し、参考資料扱いとすることも考えています。また、今後はWindowsパソコンの環境でワープロソフトWordを使って告訴状の体系と骨格を整えていくことを考えています。それではいきなりですが、その次の作業に取り掛かります。

2016-04-30　土曜日　08：53　＜＜ ［［　←これまでの記述範囲の終了時刻］］＜＜


