* GitHubを使った全資料の情報公開と、書面の参考資料という位置づけについて

:CATEGORIES: 告訴補充書としての提出も前提とした参考資料,参考資料及びパソコンやインターネットの技術の利用に関するご説明
:TAGS: 告訴状の下書き,インターネット,情報公開

2016-12-04　日曜日　09：40　＞＞ ［［　←これからの記述範囲の開始時刻］］＞＞

／ ********************（引用開始）********************
引用URL＞＞＞＞：https://ja.wikipedia.org/wiki/GitHub GitHub - Wikipedia

GitHub（ギットハブ）はソフトウェア開発プロジェクトのための共有ウェブサービスであり、Gitバージョン管理システムを使用する。

 ********************（引用終了）********************／

　上記はGitHubについて書いてあるWikipediaのページです。Gitが何かであることをしらないとサービス自体の意味もご理解いただけないと思います。普段、インターネットを使っていてもGitという用語を見ることはほとんどありません。

　唯一、見覚えがあったので調べてみました。次の野田弁護士のTwilogになります。

弁護士　野田隼人(@nodahayato)/「git」の検索結果 - Twilog http://twilog.org/nodahayato/search?word=git&ao=a

　2011年4月9日からgitをキーワードに含むツイートがあって、次のツイートが、ありがちな経験で、誰もがはまりそうなことなので参考になると思います。

ツイート：nodahayato（弁護士　野田隼人）：2011/04/09 23:13： https://twitter.com/nodahayato/status/56721368821141507 ：
引用→　 githubにプロジェクトを放り上げた。あちこちではまって，この作業に１０時間かかってるｗ

　私の場合、gitはコマンドから利用していますが、最近はWindowsパソコンの環境でもビジュアルにGitを操作するアプリが充実しているはずです。それでもUNIXのコマンド操作に馴染みがないと、仕組みや取り扱いは理解が難しいかもしれません。

　私もそれなりに苦労し時間も掛けて勉強しましたが、CVSやSVNという別の分散型バージョン管理システムの経験もあったので、Gitはわりと早く馴染むことができました。それでも落とし穴のような地雷が各所に散りばめられているという印象があります。

　それでもGitに関する情報はインターネット上に豊富であり、同じようなトラブルを経験した人の解決例が多いので、その点は他のLinuxのトラブルよりは深刻に手間取ったということもありません。そのLinuxも年々、トラブルは少なくなっています。

　正直、Gitは敷居が高いと思いますが、それはGitで管理をするという話であって、「Clone or download]というボタンをクリックすることで、ZIPの圧縮ファイルとして、プロジェクトのデータを丸ごとダウンロードすることが出来ます。

　今実際に、ログインしていない状態で、ダウンロードをやってみました。

hirono2016kk/kokuso2016 https://github.com/hirono2016kk/kokuso2016

　ZIPの圧縮ファイルを解凍すると、kokuso2016-masterというフォルダが出来ました。本来ここに、.gitというフォルダがあってそれがGitの管理情報なのですが、それは存在しませんでした。

　.directoryという見慣れないファイルがあったので、中身を確認すると、タイムスタンプとバージョン情報がありました。タイムスタンプはダウンロードの時点の時刻のようです。.gitが存在しないので、ただのダウンロードしたフォルダと同じはずです。

　「hirono2016kk/kokuso2016」というスラッシュで区切られたページ名になっていますが、前段が私のユーザ名、後段がリポジトリ名になります。リポジトリは情報倉庫という意味もあるGitのデータの取り扱い単位ですが、実質もプロジェクト名と同じかと思います。

　ファイルの内容や、変更履歴は先のGitHubのWebページから確認することができます。commitsというのが更新履歴です。gitはコミットという操作をすることで、その時点での変更点が記録されることになります。ディレクトリツリーのスナップショットと表現されることもあります。

　基本的に、書面は.orgという拡張子のあるファイルで作成しています。Emacsのorg-modeとして開くことで特別な操作が出来るようになりますが、実態はただのテキストファイルです。

　私はLinuxというUNIX環境で作業をしているので、文字コードはUTF-8、改行もUNIXのものになります。たぶん、バージョンの新しいWordで開けば、普通に表示されるかと思いますが、メモ帳で開けば、文字化けを起こし、改行も無効な状態になると思います。

　いずれWord形式の.docxという拡張のファイルも作っておきたいと思います。コンバートすることが出来ます。文字化けなどの問題を自動で解決してくれるには、Webページとしての閲覧がてっとりばやいとも考えます。あくまで資料なので、ダウンロードしたものはご自由にお使い下さい。

　書面の原本としての意味合いは、別にアップロードするブログの記事をご活用頂きたいと思います。私も参照として、記事のタイトル名とURLを使います。

　7月や11月の告訴状の中でもご説明をしてきたと思いますが、ブログへの記事の投稿は、.orgファイルの見出しを単位に投稿しています。投稿の内容はファイルとして保存されていることになり変更点はgitとして履歴に保存されることになります。万一の改ざん対策という意味もあるかと思います。

　GitHubを使うのは、ずいぶん久しぶりでした。以前使っていたアカウントは思い出すことも出来なかったので、新規にアカウントをさくせいしました。それがhirono2016kkというアカウントです。昨日12月3日の朝のことです。

　昨日は、4時50分ころに熱くなって目が覚めました。コタツで寝ていた暑かったのですが、眠った時間もたぶん2時に近い時間で、そのあとも眠れずにいたのですが、朝7時を過ぎてからだったと思います、ASKA氏の事件のことを考えているうちに、GitHubのことを使ってみようと思ったのです。

　たまたまテレビで見た場面でしたが、事件の注目度が際立って高いこともあるかと思いますが、そのままのタイトルの情報を見つけて、どの番組だったのかを確認することも出来ました。

／ ********************（引用開始）********************
引用URL＞＞＞＞：http://blog.livedoor.jp/ninji/archives/48969719.html ASKAを盗聴した悪の組織「ギフハブ」の正体が「GitHub」だという憶測 :にんじ報告

ネットでは、そんな彼の証言を元に色々と憶測が飛び交っており、一つの説として「ギフハブ」は「GitHub（ギットハブ）」のことではないか、という説も。


GitHubは、ソフトウェアを開発するときに、ソースコード（プログラムが書かれたもの）などを開発者間で共有し管理するサービスであり、世界的に有名でユーザーも多く、それだけにもちろん高度な技術が使われたソフトも存在します。


 ********************（引用終了）********************／

　今朝になってネットで調べてみたのですが、やはりGitはギットで、GitHubはギットハブ以外の発音は見当たりませんでした。Linuxはリナックス以外の発音がいくつか世界ではある、と聞いていました。

　GitがLinuxのソースコードの開発に使われてきたことはよく知っていましたが、今朝初めて知ったことは、GitもLinuxの開発者の命名によるもだということです。やはり英語単語では「馬鹿」「間抜け」という意味とのことです。翻訳を実行するとそのように変換されていました。

／ ********************（引用開始）********************
引用URL＞＞＞＞：http://p.jcc.jp/news/11641939/ 弁護士に会うまで話さない…ＡＳＫＡ容疑者送検 日本テレビ【スッキリ！！】｜ＪＣＣテレビすべて

2016/11/30
日本テレビ 【スッキリ！！】
弁護士に会うまで話さない…ＡＳＫＡ容疑者送検
湾岸署から車で出てきたＡＳＫＡ容疑者は東京地検に送検された。
容疑者はきのうの取り調べで、覚醒剤の使用などについて「弁護士に会うまでは一切しゃべりません」と話した。

 ********************（引用終了）********************／

　テレビの報道は上記の「弁護士に会うまでは一切しゃべりません」という話から、足並みをそろえたように続報がぴたりと止まっている印象を受けています。昨日の朝、GitHubのことを思い出した思考も、そのあたりから始まっていました。「弁護士病」という言葉に思いを巡らせていました。

　さきほどもテレビでサンジャボという情報番組を最初から見終えたところでしたが、ASKA容疑者の問題は、さほど大きくは扱われず、放送時間も短かったように思います。

／ ********************（引用開始）********************
引用URL＞＞＞＞：http://www.chunichi.co.jp/chuspo/article/entertainment/news/CK2016112902000182.html ＡＳＫＡまた覚せい剤　逮捕直前までブログで反論連発:芸能・社会:中日スポーツ(CHUNICHI Web)

ＡＳＫＡ容疑者は２５日午後７時ごろ、「盗撮されているから確認してほしい」などと自ら１１０番。駆け付けた警察官に意味不明な言動をしたため、任意の尿検査を要請すると「分かりました」と素直に応じ、陽性反応が出た。当時は妻と２人で自宅にいたという。

　２８日午後２時半ごろ、テレビニュースで「逮捕する方針」との速報が伝えられると、ＡＳＫＡ容疑者はブログを次々と更新、「間違いですよ」「何の、問題もありません」と報道を否定。テレビのワイドショーで報道されると、まるで見ているかのように「ミヤネ屋さんへ」「電話はしてませんよ」と、書き込みは午後５時半ごろまで続いた。

 ********************（引用終了）********************／

　一部引用した上記の記事に、事件の特異性がよく現れていると思いますが、28日のことだったのかと確認するとともに、報道の移り行きも、早く感じました。別の記事として取り上げる予定の、タクシーのドライブレコーダ映像の公開を弁護士が批判していることに関連し、守りに入ったようにも。

　被害妄想のリアリティを、テレビの映像を通してこれほど生々しく見たという機会もなかったと思います。タクシーの映像は、それにさらに踏み込んだ判断材料だったと思いますが、マスコミも思い切ったことをやったものだとは思っていました。

　社会的に影響の大きな有名人であり、さらに一度同じ覚醒剤事件で執行猶予付きの判決を受けて謝罪をしていた上での事件であったので、ドライブレコーダの映像公開に踏み切ったのかと思いましたが、よほど条件が揃わないとありえないような機会とも思いました。

　他にも取り上げてご紹介しておきたいことが沢山あります。これまでは控えることも多かったのですが、11月の告訴状で、あとになって探しだそうとすると時間がかかる上、内容が不正確になりかねないということを痛感しました。

　本件告訴事件における参考資料としての情報は、次のブログの記事を情報公開のメインにしています。11月の告訴状のあとのものとして、「告訴補充書としての提出も前提とした参考資料」というカテゴリーをご用意しました。

2016年告訴状＿金沢地方検察庁御中 | さらば弁護士鉄道＼泥棒神社の物語 https://hirono2016kk.wordpress.com/

　内容としては、告訴状の下書きとして作成しながら、珠洲警察署署長への上申書を書くつもりで中断し、参考資料扱いにした構成の再開になります。具体的には階層構造としたカテゴリー分類の再構成、再利用になります。

