* 埼玉県東松山市の河川敷少年殺害事件に対する弁護士の反応の乏しさと、光市母子殺害事件における加熱した刑事弁護活動との比較検討

2016-08-30　火曜日　15：54　＞＞ ［［　←これからの記述範囲の開始時刻］］＞＞

　まずは、事件の概要を次のNHKニュース記事からの部分引用でご紹介したいと思います。

／＊＊＊＊＊＊＊＊＊＊（引用開始）＊＊＊＊＊＊＊＊＊＊
引用URL＞＞＞＞：http://www3.nhk.or.jp/news/html/20160824/k10010652971000.html 河川敷で死亡の少年は溺死 殺人事件として捜査 | NHKニュース

２３日午前８時ごろ、埼玉県東松山市を流れる都幾川の河川敷で、埼玉県吉見町に住む、井上翼さん（１６）が死亡しているのが見つかりました。

井上さんは体の一部が砂利に埋もれ、衣服は身につけていない状態だったということで、警察が死因について詳しく調べていました。その結果、井上さんに目立った傷などはなく、死因は溺死だったことが分かりました。警察は現場や遺体の状況などから、井上さんが２２日、河川敷で何者かに殺害されたと判断し、２４日夜、東松山警察署に捜査本部を設置しました。

都幾川では、井上さんが殺害されたとされる２２日、台風９号の大雨で川の水位が急激に上昇し、一部の堤防からは水があふれ出す被害が出ていました。

これまでの調べで、２４日未明に警察署に出頭した１６歳の少年が事件への関与を認める供述を始めているということで、警察は井上さんが少年どうしのトラブルに巻き込まれて殺害されたとみて捜査しています。

＊＊＊＊＊＊＊＊＊＊（引用終了）＊＊＊＊＊＊＊＊＊＊／

　上記は8月24日 20時55分という配信時刻と思われるネットのニュース記事です。事件の端緒となった正確な時期を探して見つけたのがこのNHKのニュース記事です。

　NHKにこだわったのは、他に理由があって、ほぼ同時期の事件ニュースになっていた若手俳優の強姦致傷事件に関して、テレビのNHKのニュース番組で一度も報道を見かけなかったことが、報道のあり方として公正なものなのか、いささか疑問に感じたからです。

　強姦致傷事件で逮捕された被疑者の若手俳優は、昨年の連続テレビ小説まれ、で主人公の友達役でドラマを盛り上げブレイクするきっかけになったと言われています。同じ石川県でも同じ能登半島の奥能登に住むこともあり、輪島が舞台のドラマには注目していました。ドラマの内容もよく知っています。

　この強姦致傷事件は、逮捕直後から被疑者が曜日を認め「女性を見て欲求を抑えきれなかった」と供述していると繰り返し報道されていました。22歳という成年男性との違いはありますが、爆発的な性衝動によって引き起こされた性犯罪として最も衝撃的だったのが光市母子殺害事件です。

　少年犯罪のあるべき刑事弁護として、多くの弁護士から支持を受けたのも、テレビでの橋下弁護士の弁護士界に対する懲戒請求扇動で問題が波及したのもこの光市母子殺害事件でした。私が弁護士や刑事弁護に対して真剣に疑いの目を向けるきっかけになり、モトケンこと矢部善朗弁護士）との対立にも発展。

　少年犯罪における少年法の有用性というかありがたみの宣伝のようになったという印象が強いのは、昨年の3月頃だったように思いますが、神奈川県の川崎市の多摩川河川敷で発生した川崎中1殺害事件でした。この事件においては光市母子殺害事件の再来かと思うほど活発な弁護士の反応がありました。

　とりわけ活発だったのが、同じくツイッターでの小倉秀夫弁護士と高島章弁護士だったと記憶しています。もう少し早い時期には、1月の20日頃だったと思いますが、宮崎での強姦事件の示談交渉の問題がありました。その後懲戒請求もありましたが、不処分にもなり全く大きな問題にもなりませんでした。

　宮崎の強姦事件の示談交渉の問題も、今回の若手俳優の強姦致傷事件とは真逆で対照的な経過を辿り、それがツイッターにおける弁護士の反応にも際立って反映されていました。

　飴と鞭の関係で言えば、まさに宮崎の件が甘い期待としてのアメをちらつかせ、若手俳優の件が、ムチとして絶望的な不安感を世間に知らしめる弁護士らしさの二面性を強く印象づけるものです。もっとも救いようのなさを一般に感じさせるのは、無期懲役まで法定刑に含む強姦致傷ではあります。

　ただ、見方によれば強姦致傷といっても怪我の程度は軽く限界的な事例であるともテレビの弁護士が解説していたので、示談交渉や刑事弁護の余地はより大きいとも考えられる事案であって、それを初っ端から救いようのない印象づける弁護士が多かったのも彼らの本心を垣間見たような気持ちになりました。

　モトケンこと矢部善朗弁護士（京都弁護士会）と小倉秀夫弁護士、深澤諭史弁護士に関しては、次の「少年」をキーワードに含むツイートのまとめをブログの記事としてご用意しています。単純に二文字の語句を含むだけの検索なので、刑事事件とは無関係のものも含まれている可能性があります。

参考資料：「少年」をキーワードに含む「小倉秀夫弁護士（@Hideo_Ogura）」のツイート・リツイート（2010-03-25 08:26〜2016-07-18 01:05）「1-100／315」件,http://hirono2016k.blogspot.com/2016/08/hideoogura2010-03-25-08262016-07-18.html
参考資料：「少年」をキーワードに含む「小倉秀夫弁護士（@Hideo_Ogura）」のツイート・リツイート（2010-03-25 08:26〜2016-07-18 01:05）「101-200／315」件,http://hirono2016k.blogspot.com/2016/08/hideoogura2010-03-25-08262016-07-18_29.html
参考資料：「少年」をキーワードに含む「小倉秀夫弁護士（@Hideo_Ogura）」のツイート・リツイート（2010-03-25 08:26〜2016-07-18 01:05）「201-300／315」件,http://hirono2016k.blogspot.com/2016/08/hideoogura2010-03-25-08262016-07-18_79.html
参考資料：「少年」をキーワードに含む「小倉秀夫弁護士（@Hideo_Ogura）」のツイート・リツイート（2010-03-25 08:26〜2016-07-18 01:05）「301-315／315」件,http://hirono2016k.blogspot.com/2016/08/hideoogura2010-03-25-08262016-07-18_57.html
参考資料：「少年」をキーワードに含む「深澤諭史弁護士（@fukazawas）」のツイート・リツイート（2013-07-05 12:49〜2016-07-20 09:14）「32」件,http://hirono2016k.blogspot.com/2016/08/fukazawas2013-07-05-12492016-07-20.html
参考資料：「少年」をキーワードに含む「モトケンこと矢部善朗弁護士（京都弁護士会）（@motoken_tw）」のツイート・リツイート（2010-09-17 12:24〜2016-08-26 17:32）「79」件,http://hirono2016k.blogspot.com/2016/08/motokentw2010-09-17-12242016-08-26.html

　データベースから取得したデータです。ツイートの投稿時刻で古いものから順番になっています。最新のものから並べることもできるのですが、全体的な流れに重きをおいて、このようにしています。次が小倉秀夫弁護士のキーワードを含む最も最新のツイートの投稿時刻です。

％Hideo_Ogura（小倉秀夫）のツイート％投稿日時％2016-07-18 01:05:00％ツイートのURL％ https://twitter.com/Hideo_Ogura/status/754708549674991616 ％

　次がモトケンこと矢部善朗弁護士（京都弁護士会）のそれになります。

％motoken_tw（モトケン）のツイート％投稿日時％2016-08-26 17:32:00％ツイートのURL％ https://twitter.com/motoken_tw/status/769090074910793728 ％

　次が深澤諭史弁護士です。深澤諭史弁護士は32件しかないので全体も把握しやすいかと思いますが、モトケンこと矢部善朗弁護士（京都弁護士会）も思ったより少なく79件でした。

＞fukazawas（深澤諭史）のリツイート＞このリツイートの日時＞2016-07-20 09:14:00＞ URL＞ https://twitter.com/fukazawas/status/755556404962799616 ＞

　深澤諭史弁護士の最新のものは今年の7月20日ですが、モトケンこと矢部善朗弁護士（京都弁護士会）は8月26日、小倉秀夫弁護士は7月18日となっています。いずれも8月23日に報道された埼玉県東松山市の河川敷少年殺害事件に触れたようなものはありません。

　何度も繰り返し書いていると思いますが、ツイートのデーターベースへの全件登録をしているのは、この3人の弁護士だけです。京都の八坂神社の祗園祭のお神輿が3基で、それぞれ素戔嗚尊、櫛稲田姫命、八柱御子神であることを意識し、神様の目線で巫山戯た歴史的存在として格別に祭り上げています。

　高島章弁護士のツイートは、データーベースを利用せず、Twitterの高度な検索の結果から選別して、TwitterAPIからその場で取得したデータを使って次に掲載したいと思います。

　これは、別の項目、別の記事として作成し、ブログ記事のリンクを掲載にとどめたいと思います。全体としての整理をつけやすくするためでもあります。高島章弁護士も特別な存在の弁護士として、その社会的影響も重視し、特別枠の弁護士の一人として位置づけを行っています。

2016-08-30　火曜日　17：26　＜＜ ［［　←これまでの記述範囲の終了時刻］］＜＜



