**** 「母・高畑淳子　息子と2度目の面会　最新情報を敏腕芸能記者が生激白」という見出しのテレビの情報番組バイキング（2016年8月30日の放送）

2016-08-30　火曜日　12：10　＞＞ ［［　←これからの記述範囲の開始時刻］］＞＞

　2,3日前になるかと思いますが、同じ番組で同じ問題を取り上げた同じような討論があり、ジャーナリスト江川紹子さんと郷原信郎弁護士が参加していました。チャンネルを変えたので最初からみていないのですが、台風10号関係のニュースが多い中、冒頭からやっているようです。

　お昼の12時台はこれまで、NHKでニュースを見たり、ひるおび！という情報番組を見ることが多かったので、ほとんど見ることがなかった番組です。たまたまチャンネルを合わせたところ、ジャーナリスト江川紹子さんや郷原信郎弁護士の姿を見たので、それから注目するようになりました。

　この若手俳優の強姦致傷事件は、8月23日の未明に発生したとのことで、私は16時50分ころから10分間ほどのテレビ放送を、銭湯の脱衣場のテレビで風呂からあがったあと、さて帰ろうかという直是のタイミングで見ました。

　12時30分ですが、番組で初めて郷原信郎弁護士の姿を見ました。凶悪犯罪と決めつけてほしくない、などと口をはさんできました。

　郷原信郎弁護士は、母親が接見の時に事件のことを少しでも話したら接見禁止になるので何も言えなかった、という謝罪会見時の説明に疑問を投げかけていましたが、これはインターネットを含めの弁護士も触れなかった問題で、私も当初より疑問に感じていたところでした。

　平成4年や平成11年なので余り参考にならないかとも思いますが、私自身の経験として、金沢西警察署や金沢刑務所の拘置所の接見において、特に事件のことに触れるなという注意を受けた記憶はなく、少なくとも、その場で中断するとか、以降接見禁止になるという強い警告はなかったと思います。

　郷原信郎弁護士はトークのゲスト席からの、売店はあるんですか？、という質問に、「さあ、入ったことがないからわからない。」などと答えていました。面会についても頻繁には出来ないと言っていましたが、そのあとボードが出て女子アナの解説付きで一日一回と紹介していました。

　トークのゲスト席や司会の坂上忍さんまで、現金の差し入れが出来ることには、ずいぶんと意外そうに驚いていました。警察署の留置場では外部の食堂から出前をとれるのが普通だと思いますし、売店もあるのではと思います。

　郷原信郎弁護士は元検事で、他のヤメ検とは違って「広島地方検察庁の特別刑事部の部長や長崎地方検察庁の次席検事、東京地方検察庁の八王子支部の副部長を歴任」という経歴があります。定年退職してからだと検事総長や検事長で弁護士になる人は普通かと思いますが、次席でヤメ検は他に知りません。

郷原信郎 - Wikipedia http://bit.ly/1XlnzBd

　郷原信郎弁護士の経歴の情報は、確認のため調べた上記ページからの引用です。

　郷原信郎弁護士に関しては、前回同じバイキングという番組で姿を見たあとだったと思いますが、主任弁護人のような立場である藤井美濃加茂市長事件について、久しぶりにネットで調べたのですが、控訴審の判決は出ておらず、結審の見通しも出ていないようでした。

　若手俳優の事件で番組内では成人した子どもの事件に親の責任はあるか、というアンケートをやっていました。102人のうち52人が責任ありで50人が責任なし、になっていました。色々な考えや見方があるものだと参考になることの多い事件ですが、被害者の立場を尊重すべきという声も強いようです。

　この事件に付随した報道に対する批判や強姦罪に対する意見などは、注目の弁護士の具体的ツイートとして取り上げ、論考を進めたいと考えています。

　この事件が発生し、同日の逮捕として報道された8月23日は、4日間ある輪島大祭の2日目で重蔵神社大祭（河井町）の当日でした。河井町は有名は輪島の朝市を含む地区で、祭りの規模も輪島大祭では最大のはずです。

　この強姦致傷事件で逮捕された若手俳優は、報道の当初より、どの局も「昨年の連続テレビ小説まれ、でブレイクし」と紹介していました。ドラマでは輪島大祭の再現の場面もありましたが、私が見たところ3日目の住吉神社大祭（鳳至町）の場所での撮影のように見えました。

　いずれにせよ、輪島と縁の深い若手俳優が、一年に一度の輪島大祭の日に事件を起こし、その人の夕方前にはテレビで報道されたのですから一層感慨深いものがありました。後で知ったことですが、13時55分から15時50分まで放送の情報番組ミヤネ屋の放送中に逮捕の速報が入ったとのことでした。

　「参考資料扱いにした過去の告訴状の下書き」やその他の書面で書いてきたと思いますが、私が平成4年の事件で逮捕された時、母親は輪島のねぶた温泉で仲居の仕事をしていました。温泉地を想像するかと思いますが、ホテルのような旅館が一件あるだけです。

　22日には輪島大祭の初日でもある奥津比咩神社大祭（海士町）を見に行っていました。夕方遅くにガソリンスタンドに行き、店の人と話をしていたところ、ねぶた温泉は入浴のみで14時か15時以降は700円から800円になると聞きました。宿泊だと5万円から10万円の部屋もあると聞きました。

　強姦致傷事件の被疑者となった若手俳優の母親である女優の記者会見も、いろいろと昔のことを思い出しながら重ね合わせて見るところがありました。さてこれからというところで中断に入りましたが、再スタートの時期を遅らせたことで、データベースと連携した基盤を構築することも出来ました。

　以前より、強姦罪の罰則強化や非親告罪化には一抹の疑念があって、本書において取り上げておく必要を感じていたのですが、それがある種の社会実験をともなって問題性を顕在化する機会にもなったと思います。

　弁護士の反応として驚くほど対照的な事件もありました。当初は小さく報道されていた事件でしたが、早い段階で逮捕されたこともあり、各局の情報番組でもかなり時間を割いて詳しく報道された少年事件です。内容は酷似しているのに前の川崎の事件とはまるで違って、歩調を合わせたような沈黙状態です。

　これも別のところで取り上げたいと思います。面白いデータの参照をすることも出来ました。

2016-08-30　火曜日　15：20　＜＜ ［［　←これまでの記述範囲の終了時刻］］＜＜
**** 「無罪請負人」弘中弁護士率いる事務所が高畑裕太を担当 ― スポニチ（引用）

2016-09-11　日曜日　11：48　＞＞ ［［　←これからの記述範囲の開始時刻］］＞＞

／＊＊＊＊＊＊＊＊＊＊（引用開始）＊＊＊＊＊＊＊＊＊＊
引用URL＞＞＞＞：http://www.sponichi.co.jp/entertainment/news/2016/09/10/kiji/K20160910013327950.html 「無罪請負人」弘中弁護士率いる事務所が高畑裕太を担当 ― スポニチ Sponichi Annex 芸能

弘中氏はロス疑惑の故三浦和義氏、薬害エイズ事件の故安部英氏、陸山会事件の小沢一郎氏らの刑事訴訟で弁護人を務め、次々と無罪を勝ち取ってきた辣腕（らつわん）。最近では都知事選中に女性スキャンダルが報じられた鳥越俊太郎氏の代理人として、週刊誌の編集人に対して名誉毀損（きそん）と公職選挙法違反の疑いで東京地検に告訴状を提出した。事務所としてはゴーストライター問題で世間を騒がせた佐村河内守氏の代理人など著名人からの依頼も数多い。

＊＊＊＊＊＊＊＊＊＊（引用終了）＊＊＊＊＊＊＊＊＊＊／

2016-09-11　日曜日　11：48　＜＜ ［［　←これまでの記述範囲の終了時刻］］＜＜

2016-09-11　日曜日　11：50　＞＞ ［［　←これからの記述範囲の開始時刻］］＞＞

　「最近では都知事選中に女性スキャンダルが報じられた鳥越俊太郎氏の代理人として、週刊誌の編集人に対して名誉毀損（きそん）と公職選挙法違反の疑いで東京地検に告訴状を提出した。」というのは、知らなかった気がします。

　鳥越氏といえば、今は沈静化していますが都知事選に出たことで一躍注目を集め、いろいろと晩節を汚しまくったという感想がありますが、平成15年から18年ぐらいまでの時期、司法不信というテーマで社会的に大きな影響を与えた人物だと考えています。

　今となってはずいぶんと偏った報道ではなかったかとも思いますが、認知症の症状が疑われるとも報道されていたので、過去の報道の正当性を検証することも難しく、後の祭りという気もします。

　当時の報道として印象に強いのは、御殿場事件、岩手の事件、三井環氏の事件などがありましたが、私が鳥越氏を知るようになった頃は、「ザ・スクープ」という報道番組も、年数回の放送になっていました。

／＊＊＊＊＊＊＊＊＊＊（引用開始）＊＊＊＊＊＊＊＊＊＊
引用URL＞＞＞＞：https://ja.wikipedia.org/wiki/%E3%82%B6%E3%83%BB%E3%82%B9%E3%82%AF%E3%83%BC%E3%83%97 ザ・スクープ - Wikipedia

『ザ・スクープ』（英称:THE SCOOP）とは、テレビ朝日（ANN）系列で放送されている報道ドキュメンタリー番組である。

1989年から2002年までレギュラー放送され、2002年以降は単発スペシャル番組として放送されている。

＊＊＊＊＊＊＊＊＊＊（引用終了）＊＊＊＊＊＊＊＊＊＊／

　調べると、上記のページにあるように平成1年からの番組だったようです。似たようなタイトルの番組は他にもあったような気がしますが、当時は報道番組の番組名を頭に入れて、それを視聴するという習慣もなく、鳥越氏のことも平成15年以前は、見たという記憶もありません。

　岩手の事件では、元刑事のジャーナリストが岩手県庁で県知事と、岩手県警の捜査について直談判したという報道が特に印象的でしたが、「ザ・スクープ」の番組内であったのか記憶は定かでありません。その後、元刑事の人は自殺をしました。

　考えてみると、元刑事の人はTwitterをやっていて、2010年4月に私がTwitterを始めた後のことで、フォロー返しを受けていたということも、今日久しぶりに思い出しました。

　捜査資料のあった岩手県警察宮古署の庁舎が2011年の大津波で跡形もなく流されたということも、考えさせられるところがありました。

　大津波で流される前の宮古署の映像も、事件の報道の中で見ていた憶えがありますが、建物のかたちや古さなどの雰囲気が、羽咋警察署に似ていると感じることもあり、私が2回、羽咋警察署に相談に行った時と、時期も近かったように思います。

　羽咋警察署のことは、また別に書く機会もあるかと思いますし、経過として省けない事実とも考えています。羽咋警察署のことは、私の中で混沌とした理解の体験でしたが、ザ・スクープに代表された鳥越俊太郎氏が与えた社会的影響と、渾然一体の関係性があるように考えています。

　鳥越氏は、その後、ほとんど名前も見かけなくなっていたように思いますが、私の中でバトンタッチのように、ジャーナリズムに対する疑問と、不信感を熟成させていったのが、ジャーナリスト江川紹子さんでした。弘中弁護士が関与した陸山会事件も検察のありかたとして大きく考えさせられる問題でした。

　御殿場事件については、集団での強姦未遂事件だったと記憶していますが、無罪以外はありえないという報道が加速したものの、有罪判決が確定し、控訴審の裁判長が女性で、龍子という珍しい名前だったと思いますが、その後、最高裁判事になったことも、判決への痛烈な批判を受けながらのことでした。

　時刻は21時32分になっています。夕方に珠洲市に行き、蛸島のキリコ祭りを見てきました。昭和57年に一度見に行っているのですが、派手な着物の衣装以外に記憶はなく、今年になって能登のキリコ祭りで最も絢爛豪華だと知ったのですが、なるほどと納得しました。

　最近になってネットで調べた情報で、蛸島は昔、とんでもない悪さをする大ダコがいて、神様が成敗したところ飛んでいったタコの首がそのまま島になって、蛸島という地名になったということです。蛸島事件という冤罪事件もありますが、また別の機会に書くことがあると思います。

　珠洲市に行ったのも7月の飯田の燈籠山祭り以来でしたが、七尾市や輪島、富来と比べると近く感じました。「参考資料扱いにした過去の告訴状の下書き」などに書いてきましたが、珠洲市は羽咋市から戻った平成21年において、職業訓練とそのあとの母親の入院と立て続けに頻繁にいくことがありました。

　タコの怪物といえば、パチスロ「伝説の巫女」の「愛娘」なので、珠洲警察署に事実上の弁護士妖怪の化け物退治をお願いするモトケンこと矢部善朗弁護士（京都弁護士会）のことなど考えることも多かったのですが、帰ってくるとさらに大きな素材が転がっていました。どう料理するかです。

　出掛ける前になりますが、モトケンこと矢部善朗弁護士（京都弁護士会）のタイムラインで、本日取り上げた鳥越氏に関するツイートがあって、そこからジャーナリズムの問題性を考える新たな発見がありました。愛娘にも関連しますが、女性の人権問題にも関連しています。

　そろそろ情報番組が始まると思ってテレビをつけたところ、テレビドラマ「TBS日曜劇場「仰げば尊し」の最終回の終わりの場面でした。1,2回目ぐらいしか見ていなかったのですがその後、強姦致傷事件が起ってから被疑者だった俳優が出演していたと知りました。どんな役柄だったのかは知りません。

　今日の午前中のサンデージャポンという番組だったと思いますが、報道陣を睨みつけていたとも言われる釈放時の強姦致傷事件の俳優について、パニックを起こしているように思えたというコメントがあり、なるほどそういう可能性や視点もあったのかと思いました。

　郷原信郎弁護士のブログを読んだのも今日かあるいは昨夜だったと思いますが、モトケンこと矢部善朗弁護士（京都弁護士会）が批判のようなツイートをやっていました。軍配をあげればモトケンこと矢部善朗弁護士（京都弁護士会）がまともに見える論調であり、珍しい反応とも思いました。

　モトケンこと矢部善朗弁護士（京都弁護士会）の場合、まともに見える発言をすればするほど、私の刑事告訴の必要性が高まるのですが、モトケンこと矢部善朗弁護士（京都弁護士会）に自覚はないようで、次のようなツイートまでやっていました。私の刑事告訴事件の本質に関わる問題です。

ツイート：motoken_tw（モトケン）：2016/09/11 17:48： https://twitter.com/motoken_tw/status/774892291035045889 ：
引用→　 .@BigHopeClasic 「嫌よ嫌よも好きのうち」などという男にとってものすごく都合のいい言葉もありましてね。自惚れの強い男はどんなに拒絶されても拒絶とは考えないかも知れません。そんな自惚れ屋を許すほど法は甘くありませんけどね。

　モトケンこと矢部善朗弁護士（京都弁護士会）には３つのアカウントの全部をブロックされているので、現在のTwitterのブロックにおける仕様上、ログインした状態でツイートを開くことすら出来ないので、私の立場ではまったく処置無しです。

　他に、記録しておきたいツイートだけでも対応しきれないぐらい沢山あるので、この項目も締めくくりにしたいところですが、最後に、鳥越氏に関したモトケンこと矢部善朗弁護士（京都弁護士会）のツイートと、その関連記事をご紹介しておきます。

ツイート：motoken_tw（モトケン）：2016/09/11 14:09： https://twitter.com/motoken_tw/status/774837353210793984 ：
引用→　 つまり、鳥越氏は、自分が編集長をしていた週刊誌で嘘を書いたことがある、ということかな？ https://t.co/fLB9mHK970

／＊＊＊＊＊＊＊＊＊＊（引用開始）＊＊＊＊＊＊＊＊＊＊
引用URL＞＞＞＞：http://www.huffingtonpost.jp/2016/09/09/torigoe-argued-utsunomiya_n_11925390.html 鳥越俊太郎氏と宇都宮健児氏、生放送中に「女性問題」で激しく言い争う

7月の東京都知事選で落選したジャーナリストの鳥越俊太郎氏と、立候補を見送った元日弁連会長の宇都宮健児氏が、9月9日放送のTBS系列「ゴゴスマ～GOGO！Smile！～」で、生放送中に激しく言い争った。

宇都宮氏は、野党統一候補となった鳥越氏に譲る形で、都知事選への立候補を直前に見送った。宇都宮氏は、選挙期間中に週刊誌が報じた女性問題について、鳥越氏が記者会見を開かなかったことを理由に、鳥越氏の応援演説に立つことはなかった。

2人が話すのは、告示直前に会談して以来だったという。鳥越氏は、週刊誌報道を「事実無根」として宇都宮氏の支援見送りを批判。宇都宮氏は「そうであるなら都民に説明すべきだった」と応酬した。

女性問題を巡る、番組中の2人のやりとりは、以下の通り。

＊＊＊＊＊＊＊＊＊＊（引用終了）＊＊＊＊＊＊＊＊＊＊／

　他に取り上げたいツイートだけで対応しきれないぐらい沢山あるのですが、同じジャーナリストとして同じく疑問の大きい、ジャーナリスト江川紹子さんの俳優の強姦致傷事件の報道に関するツイートを、優先順位をあげてご紹介しておきたいと思います。

　事件や問題にアクセントをおくか、コメントを発した人物に重点をおくかで、いちいち悩ましくもあるのですが、どうでしょう。ジャーナリスト江川紹子さんのパーソナリティに重きをおいて、次の作業に移ることにします。

2016-09-11　日曜日　22：15　＜＜ ［［　←これまでの記述範囲の終了時刻］］＜＜
**** 高畑淳子 「メレンゲの気持ち」出演シーン大幅カット、発言も一切ナシ - リアルライブ（引用）

2016-09-12　月曜日　00：36　＞＞ ［［　←これからの記述範囲の開始時刻］］＞＞

／＊＊＊＊＊＊＊＊＊＊（引用開始）＊＊＊＊＊＊＊＊＊＊
引用URL＞＞＞＞：http://npn.co.jp/article/detail/84985011/ 高畑淳子 「メレンゲの気持ち」出演シーン大幅カット、発言も一切ナシ - リアルライブ

また、番組では高畑の発言するシーンが一切なく、他のゲスト出演者の話を聞いているだけの映像のみで、高畑一人でのアップシーンもなかった。

　高畑淳子の息子で俳優の高畑裕太容疑者は8月23日、群馬県前橋市内のビジネスホテルで、従業員の40代女性に性的暴行を加え、さらにケガを負わせたとして逮捕された。事件を受けて、高畑淳子は会見を行い、被害者女性と関係各所に謝罪した。今後の活動について、9月24日に初日を迎える主演舞台「雪まろげ」には出演すると明かしたが、それ以外のテレビや舞台などの出演は、今後状況を見て判断するという。

＊＊＊＊＊＊＊＊＊＊（引用終了）＊＊＊＊＊＊＊＊＊＊／

　やたらとマスコミを批判し、悪者仕立てし、天敵としての存在性をアピールする弁護士の言動が、当事者の立場を悪くしていると感じる一例です。社会の注目を集める大きな事件では、概ねその傾向が顕著だと考えてきましたが、とりわけわかりやすくなっており、その悪影響は想像以上に大きいと感じます。

　モトケンこと矢部善朗弁護士（京都弁護士会）個人のパーソナリティの問題性としても取り上げておきたいと考えていましたが、初っ端のモトケンこと矢部善朗弁護士（京都弁護士会）の次のツイートなど、いきなり横っ面を張り倒すような挑発感があります。

ツイート：motoken_tw（モトケン）：2016/08/23 17:15： https://twitter.com/motoken_tw/status/767998794763866112 ：
引用→　 この記事だが、なんで母親の写真を載っけてるんだ？＞女優、高畑淳子の息子で俳優の高畑裕太、４０代ホテル従業員強姦致傷容疑で逮捕 「欲求を抑えられなかった」 前橋のビジネスホテル https://t.co/maWhG4S0xe

　他にもっとインパクトの強いモトケンこと矢部善朗弁護士（京都弁護士会）のツイートがあったように思うのですが、8月23日の逮捕、報道当日のモトケンこと矢部善朗弁護士（京都弁護士会）のツイートでは、こんなものでした。

　8月25日になりますが、衝撃的だったのはモトケンこと矢部善朗弁護士（京都弁護士会）の次のツイートだったかもしれません。一般の感覚を逆なでし、母親の立場をより悪くする、挑発やけしかけとも思えるツイートです。

ツイート：motoken_tw（モトケン）：2016/08/25 23:02： https://twitter.com/motoken_tw/status/768810756884226049 ：
引用→　 何を根拠に「より重いものにはなると思う」と言うのだろう？＞高畑淳子の責任「重いものになる」とやくみつる氏 https://t.co/TiQm4hLIyj @nikkansportsさんから

　一見するともっともらしい反論に見えるような気がしますが、計算したうえで都合よく問題を利用しようというモトケンこと矢部善朗弁護士（京都弁護士会）ならではの強かさを感じます。彼は以前、フォロワー数の多いアカウントに絡めばご利益があるというようなツイートも何度か行っていました。

　ジャーナリスト江川紹子さんなどもその一人という印象を受けましたが、ＰＣ遠隔操作事件と佐藤博史弁護士のことで執拗にからみ、ジャーナリスト江川紹子さんもよほど辟易した様子でした。お構いなしの積極性もモトケンこと矢部善朗弁護士の特徴であり、損得勘定で行動していると見ています。

　もっともモトケンこと矢部善朗弁護士は、テレビも満足に見ていないと、比較的最近のツイートで語っていました。テレビを家に置いていないというような話だったと思います。満足に状況を把握もせずに、マスコミを批判的に見ているのだとも思いますが、すでに履き違えた異様と危険を感じます。

　時刻は9月12日11時14分になっています。さきほど、ふと考えたのですが、モトケンこと矢部善朗弁護士（京都弁護士会）がテレビを持っていない、というのも、あるいは事実ではなく、テレビの情報に無関心な依頼者を引き寄せるための、弁護士商売の手段なのかもしれないと考えました。

　今テレビで、ワイドスクランブルという情報番組を見ていますが、北朝鮮の核実験やロシアとの北方領土問題を取り上げていて、高畑裕太氏の示談、釈放のことは、まったく取り上げる気配がありません。何事もなかったかのように番組が進行しています。

　次に、モトケンこと矢部善朗弁護士（京都弁護士会）がツイートで言及していた、法学者のような弁護士のブログ記事を取り上げて、ご紹介しておきたいと思います。強姦事件は、私の本件告訴において中核となる問題でもあります。

2016-09-12　月曜日　11：23　＜＜ ［［　←これまでの記述範囲の終了時刻］］＜＜
**** 示談成立後に出された弁護人のコメントについて(園田寿) ←モトケンこと矢部善朗弁護士（京都弁護士会）のツイートで知った記事

2016-09-12　月曜日　11：26　＞＞ ［［　←これからの記述範囲の開始時刻］］＞＞

ツイート：motoken_tw（モトケン）：2016/09/12 10:13： https://twitter.com/motoken_tw/status/775140157750063104 ：
引用→　 「説明」としては一番わかりやすいかなと思いますが、当然のことながら多くの「推測」を含んでおり、しかもその「推測」の根拠となる「事実」が、ほぼ全面的に被疑者側からの情報（弁護人のコメント）に依存している点では、郷原弁護士の記事と同じ。 https://t.co/u5wx4ss0Ox

　上記のモトケンこと矢部善朗弁護士（京都弁護士会）のツイートに引用されているURLが次のツイートです。

ツイート：sonoda_hisashi（園田寿）：2016/09/11 23:58： https://twitter.com/sonoda_hisashi/status/774985515107954688 ：
引用→　 Yahoo!ニュースで記事を公開しました。＜改行＞【高畑事件】示談成立後に出された弁護人のコメントについて（園田寿）- Yahoo!ニュース＜改行＞https://t.co/97x0kXTBOk

　リンクの記事の紹介ツイートであり、その記事から次に一部を引用しました。私の事件との関連では、重要と考えている部分ではありませんが、被疑者、被告人の資力を前提条件にする示談のオプション性には疑問があり、それが本件告訴事件を構成する主要な部分となっていることをご指摘しておきます。

／＊＊＊＊＊＊＊＊＊＊（引用開始）＊＊＊＊＊＊＊＊＊＊
引用URL＞＞＞＞：http://bylines.news.yahoo.co.jp/sonodahisashi/20160911-00062095/ 【高畑事件】示談成立後に出された弁護人のコメントについて(園田寿) - 個人 - Yahoo!ニュース

■分かりにくい点（その１）―被害者はコメントの内容を承知しているのか？

コメントによれば、不起訴の背景には、被害者との示談（和解）の成立があり、これが考慮されたとのことです。

示談とは事実を否定することではありませんので、このようなコメントを発表することじたいが被害者に対して多大の苦痛を与え、いわゆるセカンドレイプではないのかという意見があります。

確かに、今回のように弁護人が示談成立後にこのようなコメントを公表することはかなり異例なことと思われます。しかし、通常この種の示談書には、被害者のプライバシーを考慮して、〈今後、事件や示談の内容については第三者に口外しない〉といった趣旨の条項が挿入されることが多いので、もしも示談書にそのような禁止項目があるにもかかわらず、弁護士がこのようなコメントを出したとすれば、重大な違反行為となります。示談そのものが取り消される可能性もあります。本件の弁護士がそのようなことをあえて行ったとすることは考えにくいことですので、私は、このようなコメントを公表することについても、おそらく示談の内容となっていたのではなかったのかと思います。つまり、このようなコメントが出されることについては、被害者の側でも承知されていたのではないでしょうか。 

＊＊＊＊＊＊＊＊＊＊（引用終了）＊＊＊＊＊＊＊＊＊＊／

＜2016年09月12日(月) 11時38分13秒にTwitterAPIで取得したsonoda_hisashi（園田寿）のプロフィール情報＞
甲南大学法科大学院教授・弁護士。元関西大学教授。ネットワーク犯罪や情報と法が今の研究テーマ。ジャズ、囲碁（4段と5段の間）、美術（印象派＆モディリアーニ）が趣味。乃南アサさんとの共著『犯意』は、特にロー生にはお薦め。最新刊は、『情報社会と刑法』（成文堂）。

　洋風の絵画をアイコンにされていますが、何年も前から見覚えのあるものです。ときたま忘れた頃に見かけてきたアカウントでした。肖像画のような独特の趣のある絵画ですが、これを見るたびに私は、ムンクの叫びや異常心理の世界のことを頭に浮かべてきました。

園田寿の記事一覧 - 個人 - Yahoo!ニュース http://bylines.news.yahoo.co.jp/sonodahisashi/

　上記のyahooのブログの方には顔写真がありまして、肖像画のようなアイコンとの不思議なギャップのようなものも感じてきました。余り注目してこなかった法科大学院教授・弁護士ですが、過去に見た記事の印象は、あまり記憶にないですが、当たり障りのないものであったように思います。

　記事の一覧の中で次のストーカーに関する記事を見つけました。記事にはサムネイルの画像があって、それがムンクの叫びと同じようなものになっていました。色使いが違って見え、縦縞のシャツが、まるで日本の病院の患者のパジャマに見えます。

情報化の進展とストーカー現象(園田寿) - 個人 - Yahoo!ニュース http://bylines.news.yahoo.co.jp/sonodahisashi/20160525-00058027/

　お昼の情報番組バイキングで、高畑裕太氏の示談、釈放を取り上げていましたが、12時10分には終わっていました。11時55分から始まる番組で、冒頭からやっていましたが、白とも黒ともわからない玉虫色で真相が今後わかることはない、という結論で締めくくられた感じでした。

　時刻は15時49分になっています。テレビのミヤネ屋とグッディで、高畑裕太氏の示談、釈放関係の報道をみていましたが、いくらか時間差があったので見ることの出来たグッディでは、司会者の安藤優子さんが、気になるというより気に触る、などと言っていました。

　どちらの番組も専門の弁護士を招いていました。裁判で無罪を争っても有罪になるリスクがあるという点は、いくらか納得しましたが、保釈の制度に触れなかったのはどうかという思いと、性犯罪で否認をすれば保釈が認められない可能性が高いのかとも考えました。

　グッディの司会者は他に「藪の中」という表現も使っていました。どちらの番組か記憶がはっきりしませんが、秘密保持条項なる示談の取り決めの専門用語があるとも知り、性犯罪というのは文字通り、地獄のさたも金次第、という契約性が強いのだという新たな印象を持ちました。

　性犯罪と似て非なるものにストーカー犯罪がありますが、今日は何時間か前に読み、既にご紹介済みの園田寿教授のブログ記事で、ストーカー犯罪の発祥を初めて知るということもありました。

／＊＊＊＊＊＊＊＊＊＊（引用開始）＊＊＊＊＊＊＊＊＊＊
引用URL＞＞＞＞：http://bylines.news.yahoo.co.jp/sonodahisashi/20160525-00058027/ 情報化の進展とストーカー現象(園田寿) - 個人 - Yahoo!ニュース

リンデン・グロスの『ストーカー／ゆがんだ愛のかたち』（秋岡史［訳］）（祥伝社）が1995年に出版されて、以来「ストーカー」という言葉が急速に広がり定着します。「ストーク（stalk）」とは、「忍び寄る」「（疫病や死が）まん延する」「いばって歩く」こと。意味的には矛盾する内容を含んでいますがが、「相手に不安を与える異常なつきまとい」として使用されます。

もちろん、95年に突如としてこの社会に「ストーカー」が出現したわけではありません。しつこく尾行し、無言電話をかけ続け、不可解な手紙を送り続ける事案は前からありました。しかし、「異常なつきまとい」が殺人にまでエスカレートしたケースが現実に起こり、闇の向こうに潜む恐怖の実態を「ストーカー」という言葉が照らし出して、ストーカー被害の深刻化が社会問題となり、2000年に異例の速さで「ストーカー規制法」が成立したのでした。 

＊＊＊＊＊＊＊＊＊＊（引用終了）＊＊＊＊＊＊＊＊＊＊／

　1995年といえば平成7年ですが、私がストーカーという言葉を知ったのは、福井刑務所を満期出所した直後の平成9年の初め頃のことでした。その辺りは「参考資料扱いにした過去の告訴状の下書き」などにも何度か詳しいことを書いてきたと思います。

　平成12年にストーカー規制法が成立したとなっていますが、記憶より古いような気はするものの特に印象に残っていることはありません。桶川ストーカー殺人事件というのがあって、ずいぶん社会問題になっていたことは憶えていますが、プログラムの勉強などに集中していたように思います。

　ともあれ、ストーカー問題というのも、弁護士の収入源となりながら、弁護士が関与するほど問題がこじれとんでもないことになる可能性が高いように前々から考えていました。

　甲南大学といえば、ということで気になったことを調べたところ、やはり次の事件と関係がありました。

／＊＊＊＊＊＊＊＊＊＊（引用開始）＊＊＊＊＊＊＊＊＊＊
引用URL＞＞＞＞：http://mamono.2ch.net/test/read.cgi/newsplus/1205241664/ 【事件】甲南大学4年の24歳男、交際女性と共謀しチカンをでっち上げ…示談金目的か★2[3/11]

示談金を目当てに、地下鉄の車内で乗り合わせた男性を痴漢として捕まえ警察につき出した疑いで、
甲南大学の男子大学生が逮捕されました。

虚偽告訴の疑いで逮捕されたのは、京都市に住む甲南大学４年生

＊＊＊＊＊＊＊＊＊＊（引用終了）＊＊＊＊＊＊＊＊＊＊／

　2chの記事ですが、2008年3月11日という日付がスレッドの開始となっているようです。考えてみると10年前の事件ということで、こういうのも知らない人が多そうです。こういう学生もそのまま弁護士になっていた可能性もあるのかと考えると、社会実習の一環だったのかとも思えてきます。

　以前は、示談と和解の違いなどという話題を見かけることもありましたが、示談の性質について、これほどクローズアップされたことはなかったと思いますし、世の中の人に広く知られる機会になったのが、やはり大物女優の息子である高畑裕太氏の今回の事件かと思います。

　とにかくこの事件報道を通じて、一気に視野も広がり、浮かび上がる反応も多々ありました。間接的になりますが、今日の朝にも気になるツイートがあって、リツイートとして目にしたようにも思いますが、弁護士という職業についても考えさせられるところが大きいので次に取り上げておきたいと思います。

2016-09-12　月曜日　16：31　＜＜ ［［　←これまでの記述範囲の終了時刻］］＜＜
**** 郷原信郎弁護士の「推定無罪」を無視した高畑裕太氏事件を巡る報道・放送、というブログ記事を、なかなかいい内容、とする同業者弁護士

2016-09-12　月曜日　16：38　＞＞ ［［　←これからの記述範囲の開始時刻］］＞＞

リツイート：harrier0516osk（弁護士法人向原・川上総合法律事務所　向原）＞2016/09/12 10:05／2016/09/12 06:22＞ https://twitter.com/harrier0516osk/status/775138196543852544 ＞
 kamatatylaw （高橋雄一郎）＞ https://twitter.com/kamatatylaw/status/775082218469199873 ＞
引用＞　 なかなかいい内容。マスコミ報道のみから勝手に犯罪成立を断定し，被害者のためにも検察は嫌疑の存在を公式発表すべきだなどと主張する法学系の教授（刑事立法についての論文も著されている）もいるぐらいだから魔女裁判と変わらないよね。　https://t.co/nn95uMpF9Y 

　リツイートとしてご紹介したのも少しわけがあります。ここ一月ほどの間かと思いますが、かなり注目するようになっていた弁護士アカウントで、きっかけは深澤諭史弁護士のリツイートとして感慨深いツイートをいくつか目にしていたことがきっかけだったと思いますが、それも記憶が曖昧になっています。

＜2016年09月12日(月) 16時46分00秒にTwitterAPIで取得したharrier0516osk（弁護士法人向原・川上総合法律事務所　向原）のプロフィール情報＞
地下鉄空港線天神駅徒歩０分！天神駅から最も近い法律事務所。北九州オフィスも小倉駅前に。
あなたの会社の法務部門を引き受けます！お気軽にご連絡下さい！
（取扱分野）
企業法務全般
民事再生・破産などの倒産処理
一般民事
家事（離婚・遺言・相続）
知財（著作権・商標・不正競争防止法）
IT法務
刑事

　実名にはなっていませんが、法律事務所の名称になっているので、調べればすぐに実名はわかりますし、最近、ブログの記事でテレビ出演をしたことも紹介していました。職業別対抗の知恵比べ選手権のような番組でした。

弁護士紹介 - 事務所概要 | 向原・川上総合法律事務所 http://www.mk-law.jp/information/lawyer.html

　向原栄大朗弁護士は、次のリツイートも行っています。数日前まで私が気にかけていた傾向性とは異なるものですが、本件告訴事件における弁護士らの犯行態様の意義としても、かなり参考になるないようで、その辺りを具体的にはっきりと書いてあるものは初めて見ました。

リツイート：harrier0516osk（弁護士法人向原・川上総合法律事務所　向原）＞2016/09/11 20:56／2016/09/11 20:09＞ https://twitter.com/harrier0516osk/status/774939704546369536 ＞
 Shingo_Nakao （中尾慎吾）＞ https://twitter.com/Shingo_Nakao/status/774927951770988544 ＞
引用＞　 強姦致傷被疑事件の起訴率が低いということぐらい、いくら低俗な媒体であっても理解しておいたほうが良いよな。 

リツイート：harrier0516osk（弁護士法人向原・川上総合法律事務所　向原）＞2016/09/11 20:56／2016/09/11 20:11＞ https://twitter.com/harrier0516osk/status/774939670979358720 ＞
 Shingo_Nakao （中尾慎吾）＞ https://twitter.com/Shingo_Nakao/status/774928317082329088 ＞
引用＞　 示談が成立してもなお起訴される事件なんて、多くないよ。なぜなら被害者供述無しで公判維持を出来ることは多くないから。供述調書が弁護側不同意で飛ばされた場合に、どのようにして検察側が立証活動を行うのか、という問題。 

　向原栄大朗弁護士のアメブロのブログは、羽咋市に住んでいた頃から何度か目にしていたように思います。リツイートの元のツイートの中尾慎吾という弁護士もリツイートなどでちょくちょく目にしてきましたが、なかなか強気で自信に満ちた弁護士活動をされているようです。

　自信満々で性犯罪の専門性をうりにしている弁護士といえば、奥村徹弁護士ですが、彼も今回の強姦致傷事件について活発なツイートをしていて、裁判員裁判が理由で強姦致傷事件の起訴率が低くなっているとか発言しています。

　奥村徹弁護士については性犯罪に特化していて独自の世界観をお持ちなので、立場も違いいまさらとやかく言う気も起きないのですが、さすがにこれはどうなのかと、刑事裁判という制度の基礎として考えさせられるものがありました。司法作用の妨害性を自ら露呈しているようであり、奇異に映りました。

ツイート：okumuraosaka（TORU OKUMURA）：2016/09/10 14:58： https://twitter.com/okumuraosaka/status/774487194132033536 ：
引用→　 奥村がAと言えば高裁はB　奥村がＢと言えば高裁はＡというので、Ｂという判例が欲しい場合はAを主張すると、Ｂの判例を量産できるんだ。説得力なんていらないよ。児童ポルノ・児童買春の刑事裁判。 https://t.co/BkRIwZ1akP

　奥村徹弁護士を見ていると、出張版のイタコのようなものを思い浮かべることがあります。恐山のイタコという霊媒師のことですが、イタコの存在が有名だった昭和40年代後半の頃というのは、評判のよい町医者に、あちこちから人が集まるという現象が田舎にありました。

　確信犯的な性犯罪者には頼りになる存在なのかとも考えますが、一般的な生活者の目線と立場で考えれば、大事な娘が性犯罪の被害に遭う可能性を飛躍的に高める存在であって、加害者という立場になってしまった場合も合理的な弁解の機会を奪うだけの邪悪な存在と思えてなりません。

　性犯罪の豊富なデータを持ち、情報の収集にも余念がないことは、Twitterのタイムラインをみれば一目瞭然ですが、量刑にしろ何にしろ、適切な当て嵌めがなされているのか疑問であって、それ以上に、検事や裁判官の印象を著しく害して、実際以上に重い刑罰となる確率が高いように思います。

　時刻は17時38分ですが、さきほど奥村徹弁護士のツイートを探しだそうとしたところ、テレビで強姦罪の重罰化が100年ぶりに実現する見通しなどとやっていました。強姦罪の非親告罪化も盛り込まれるらしく、以前から目にしていた原案がそのまま成立に向け通過中という感じでした。

　17時20分頃のニュースで、2,3分の内容だったと思います。テレビは日テレ系のテレビ金沢のままなので、everyという全国放送と思われるニュース番組です。

　強姦罪が重罰化することで、奥村徹弁護士のような存在にも日頃の備えとして、凄まじく厳しい目を一人でも多くの人が向けることが、不当な裁判を減らし、安全安心住み良い社会づくりに貢献するという見方も持っています。

　奥村徹弁護士のタイムラインを開いた時、次のツイートが目に止まりました。すっかり忘れていた事件でしたが、今、リンクを開いて記事を読むと、昨年3月の事件となっていて、割と最近の事件ということに驚きました。2,3年以上前とツイートを見た時に思っていました。

ツイート：okumuraosaka（TORU OKUMURA）：2016/09/12 14:51： https://twitter.com/okumuraosaka/status/775210305777315840 ：
引用→　 「（院生に）殺してください、もう無理ですと頼まれたので、首をしめました」と嘱託殺人を主張、起訴内容を否認した殺害元准教授と教え子は不倫関係　検察側が指摘、福井地裁初公判　社https://t.co/dk4SRrY6Gg

　時刻は20時56分になっています。この項目の本題である次のツイートについて、いくらか書いておきたいと思います。

ツイート：kamatatylaw（高橋雄一郎）：2016/09/12 06:22： https://twitter.com/kamatatylaw/status/775082218469199873 ：
引用→　 なかなかいい内容。マスコミ報道のみから勝手に犯罪成立を断定し，被害者のためにも検察は嫌疑の存在を公式発表すべきだなどと主張する法学系の教授（刑事立法についての論文も著されている）もいるぐらいだから魔女裁判と変わらないよね。　https://t.co/nn95uMpF9Y

　改めて見直すと魔女裁判という言葉が目を引きました。現代日本の刑事司法を「中世」と批判する向きは、2,3年ぐらい前には目にする機会が多かったという記憶がありますが、最近では見かけず、魔女裁判となるとさらに宗教的な偏波が強く未熟な社会の状態を印象づけます。

　時刻は9月13日9時10分になっています。この項目の本丸である郷原信郎弁護士のブログ記事については、今他のことが気になって集中できそうにないので、またの機会に別の項目として記述をしたいと思います。

　些細といえば些細な問題なのですが、頭から離れないのはモトケンこと矢部善朗弁護士（京都弁護士会）のツイートと、それに関連した関係者のツイートです。

2016-09-13　火曜日　09：14　＜＜ ［［　←これまでの記述範囲の終了時刻］］＜＜

