**** 大渕愛子弁護士が法テラスの報酬規定を巡り懲戒処分を受けた問題に対して、実名または匿名の弁護士アカウントが示した反応としてのツイートの記録

2016-09-02　金曜日　17：37　＞＞ ［［　←これからの記述範囲の開始時刻］］＞＞

　以下のツイートの記録は、自作のデータベースから同じく自作のプログラムを、次のような操作で実行した処理結果です。単純に「大渕」をキーワードに検索をしているので、同じ文字列を含む無関係のツイートも若干含まれています。

% tw_user_tweet-sql-search-make-text-html-blogger-style.rb  --full_sql_text="SELECT * FROM tw_user_tweet WHERE tw_date BETWEEN '2000-07-22 20:14' AND '3300-07-24 23:59' AND (tweet LIKE \"%大渕%\") ORDER BY tw_date ASC"    

％amneris84（Shoko Egawa）のツイート％投稿日時％2011-07-21 08:34:00％ツイートのURL％ https://twitter.com/amneris84/status/93826261511700480 ％
％引用％ ２）検察は、状況証拠の積み重ねで有罪を主張。これに対し一審の東京地裁（大渕敏和裁判長）は、慎重な審理と「疑わしきは被告人の利益に」の原則を貫いて無罪に。釈放された被告人を検察が再び身柄拘束したことについての最高裁の判断は分かれた。

％amneris84（Shoko Egawa）のツイート％投稿日時％2012-11-07 17:54:00％ツイートのURL％ https://twitter.com/amneris84/status/266101303095205888 ％
％引用％ 東電OL事件で無罪判決を出した１審裁判官のその後。▽大渕敏和裁判長＝大阪高裁部総括判事を最後に昨年依願退官、現在公証人　▽高山光明裁判官（右）＝岡山地家裁部総括判事などを経て現在前橋地家裁部総括判事　▽森健二裁判官（左）＝那覇地家裁沖縄支部判事などを経て、現在司法研修所教官

％kyoshimine（弁護士 吉峯耕平（カンママル撲滅委員会））のツイート％投稿日時％2014-11-02 11:23:00％ツイートのURL％ https://twitter.com/kyoshimine/status/528733998822862848 ％
％引用％ こんなやばいことやってんだ。＜改行＞@hayashimasaaki 大渕弁護士、法テラスが費用立替した母子家庭から追加で顧問料等を取り立て処分される　元依頼者側が懲戒請求⇒法テラスで認められる立替金以外の支払いを受けること自体がルール違反 http://t.co/EXj49C5CBO

％sakamotomasayuk（坂本正幸）のツイート％投稿日時％2015-06-22 17:17:00％ツイートのURL％ https://twitter.com/sakamotomasayuk/status/612897094928470016 ％
％引用％ 「無期懲役でも15年くらいで仮釈放」テレビでの大渕愛子弁護士の発言は正しいか？|弁護士ドットコムニュース http://t.co/iZ3GwByL6v #bengo4topics @bengo4topicsさんから

％okaguchik（岡口基一）のツイート％投稿日時％2015-12-13 21:33:00％ツイートのURL％ https://twitter.com/okaguchik/status/676017017128804352 ％
％引用％ 大渕愛子懲戒相当議決の概要＜改行＞https://t.co/IQBvPxFuPt

％un_co__yokohama（うの字）のツイート％投稿日時％2015-12-13 22:49:00％ツイートのURL％ https://twitter.com/un_co__yokohama/status/676036152290238464 ％
％引用％ 大渕愛子、ずいぶんがめついな。ぼ

％okaguchik（岡口基一）のツイート％投稿日時％2015-12-21 21:15:00％ツイートのURL％ https://twitter.com/okaguchik/status/678911648279584768 ％
％引用％ 大渕愛子弁護士が女性相談者と料金トラブル　東京弁護士会の懲戒委員会が審査へ＜改行＞女性の依頼で大渕氏の懲戒請求をした太田真也弁護士は、問題点を指摘。＜改行＞https://t.co/0nmqdo2zXT

％okumuraosaka（TORU OKUMURA）のツイート％投稿日時％2016-01-26 11:56:00％ツイートのURL％ https://twitter.com/okumuraosaka/status/691816984334434307 ％
％引用％ 大渕愛子弁護士の次にアクセスが多いと言われている法律家ブログいつの間にか表現の自由を失っていた日本弁護士連合会！当ブログ記事の削除を要求。 https://t.co/nWiF46zT11 @raymiyatakeさんから

＞okinawabengoshi（弁護士林朋寛）のリツイート＞このリツイートの日時＞2016-01-26 12:49:00＞ URL＞ https://twitter.com/okinawabengoshi/status/691830299794264064 ＞
＞okinawabengoshi（弁護士林朋寛）がリツイートしたokumuraosaka（TORU OKUMURA）のツイートの内容＞
＞引用＞ 大渕愛子弁護士の次にアクセスが多いと言われている法律家ブログいつの間にか表現の自由を失っていた日本弁護士連合会！当ブログ記事の削除を要求。 https://t.co/nWiF46zT11 @raymiyatakeさんから

％lawkus（ystk）のツイート％投稿日時％2016-08-02 18:00:00％ツイートのURL％ https://twitter.com/lawkus/status/760399825661681664 ％
％引用％ 「行列のできる法律相談所」で活躍　大渕愛子弁護士を懲戒処分　着手金不当受領 https://t.co/4kvllYy8Vd＜改行＞法テラス使っといて私選との差額を直接受領したのか。それはひどい。事実関係がこのとおりなら懲戒は当然であろう。

％nobusan1979（のぶさんぁちゃん）のツイート％投稿日時％2016-08-02 22:33:00％ツイートのURL％ https://twitter.com/nobusan1979/status/760468610934452224 ％
％引用％ 大渕愛子弁護士が謝罪会見、タレント活動も当面自粛 - 芸能 @nikkansportsさんから https://t.co/Sv2vUUe3TN＜改行＞＜改行＞ざまぁー＜改行＞＜改行＞なんて言ってはいけないのでしょうね＜改行＞＜改行＞私は言いませんよ

％kyoshimine（弁護士 吉峯耕平（カンママル撲滅委員会））のツイート％投稿日時％2016-08-03 00:49:00％ツイートのURL％ https://twitter.com/kyoshimine/status/760502815659745281 ％
％引用％ 「依頼人が１１年６月に返金を求め、同年７月には法テラスの担当者が制度を説明したが、大渕弁護士は拒絶。同年１０月、弁護士会の役員の説得に応じて返した」＜改行＞ということだから、法テラスからルール違反を指摘されても、応じなかったんでしょ。＜改行＞https://t.co/3wfKsRQEAa

％Hideo_Ogura（小倉秀夫）のツイート％投稿日時％2016-08-03 09:01:00％ツイートのURL％ https://twitter.com/Hideo_Ogura/status/760626634684628993 ％
％引用％ 大渕弁護士のようなミスをしないためには、法テラスを使わないのが一番。着手金１０万、日当、成功報酬なしって、欠席判決でなかったら、あとは手弁当でお願いって価格ですし。

＞fukazawas（深澤諭史）のリツイート＞このリツイートの日時＞2016-08-03 09:09:00＞ URL＞ https://twitter.com/fukazawas/status/760628585556160512 ＞
＞fukazawas（深澤諭史）がリツイートしたitotakeru（伊藤たける）のツイートの内容＞
＞引用＞ 大渕愛子弁護士も、法テラスなんかと契約しなきゃよかったんだよ。

％take___five（take-five）のツイート％投稿日時％2016-08-03 09:24:00％ツイートのURL％ https://twitter.com/take___five/status/760632404373450752 ％
％引用％ 今回の大渕弁護士の件は、「懲戒処分を受ける可能性があるので、法テラスで受任するのはやめましょう」というところで落ち着いた。

＞fukazawas（深澤諭史）のリツイート＞このリツイートの日時＞2016-08-03 20:12:00＞ URL＞ https://twitter.com/fukazawas/status/760795469219962882 ＞
＞fukazawas（深澤諭史）がリツイートしたHideo_Ogura（小倉秀夫）のツイートの内容＞
＞引用＞ 大渕弁護士のようなミスをしないためには、法テラスを使わないのが一番。着手金１０万、日当、成功報酬なしって、欠席判決でなかったら、あとは手弁当でお願いって価格ですし。

％motoken_tw（モトケン）のツイート％投稿日時％2016-08-04 09:07:00％ツイートのURL％ https://twitter.com/motoken_tw/status/760990429781209093 ％
％引用％ 膝上１０センチのミニスカートはどうでもいいが、５ヶ月間も「「法テラスの制度をよく知らなかった。」というのは通用しないだろうな。＞大渕愛子弁護士の“ミニスカ謝罪会見”が物議「ベッキーは、ロングスカートだったのに……」｜ニフティニュース https://t.co/6v0qQR0Nmi

％legalnews_jp（Legal News（リーガルニュース））のツイート％投稿日時％2016-08-04 20:33:00％ツイートのURL％ https://twitter.com/legalnews_jp/status/761163152683786240 ％
％引用％ 「目立ちすぎた」大渕愛子、不当報酬受領で「重すぎる処分」の怪…弁護士会を逆なでか https://t.co/5zfpAi05im 要するに、重鎮が集まる懲戒委員会が「品位を害した」と言えば、それが基準になってしまうわけです。

％motoken_tw（モトケン）のツイート％投稿日時％2016-08-05 12:38:00％ツイートのURL％ https://twitter.com/motoken_tw/status/761406105285120000 ％
％引用％ 本当に法テラスによる弱者救済を考えるなら、法テラスの運営そのものを問題にすべきだろうな。＞上西小百合氏　次期国会で大渕弁護士問題追及へ　依頼者被害の発生についての割合等を（デイリースポーツ） - https://t.co/5JwRX97IhR #Yahooニュース

2016-09-03　土曜日　07：32　＜＜ ［［　←これまでの記述範囲の終了時刻］］＜＜
