**** 「相模原での死体遺棄事件 法廷で弁護士が笑いだし裁判長が注意」というニュース記事に対する告訴するモトケンこと矢部善朗弁護士（京都弁護士会）のコメント

2016-09-08　木曜日　20：12　＞＞ ［［　←これからの記述範囲の開始時刻］］＞＞

ツイート：motoken_tw（モトケン）：2016/09/08 10:51： https://twitter.com/motoken_tw/status/773700202976862209 ：
引用→　 証拠は見てないけど、報道された表現を読む限り、「疑わしきは被告人の不利益に」、「被告人が無罪を証明しないと有罪」と考える裁判官みたいだな。＞相模原での死体遺棄事件 法廷で弁護士が笑いだし裁判長が注意 #ldnews  https://t.co/FsZyUz8YpK

　この項目の直近の上位、本件告訴状の見出しの3階層目に位置するのは「相模原死体遺棄」で、これが最初の同列レベルの見出し作成となります。本来ならば泉澤章弁護士から始める予定でしたが、偽善性と社会的有害性の顕著なモトケンこと矢部善朗弁護士（京都弁護士会）を筆頭に据えました。

　それとなく刑事裁判感への不満や不信感を盛り込む辺りに、このモトケンこと矢部善朗弁護士（京都弁護士会）という弁護士の欺瞞性と社会汚染を含む有害性を強く感じました。

　「証拠は見ていない」とありますが、報道は見ているということとも理解は出来ます。そもそも事件の関係者以外が「証拠」を見ることができるとは考えにくく、その「証拠」の定義自体がすこぶる曖昧です。

　事件のことは通常、マスコミの報道を介してしか知ることが出来ないはずであり、そのマスコミをこれでもかというぐらい罵倒してきたのもこのモトケンこと矢部善朗弁護士（京都弁護士会）であり、最近は見せなくなりましたが警察、検察からマスコミへの情報提供もリークと称して犯罪扱いしていました。

　このモトケンこと矢部善朗弁護士（京都弁護士会）のマスコミ批判に関しては、単に本人の過去のツイートをまとめただけのものですが、次の既に作成済みの本書項目と、デザイン的にも読みやすくした、次のブログ記事を読めば合理的にご理解いただけると思います。

告訴状の下書き）「マスコミ」をキーワードにしたモトケンこと矢部善朗弁護士（京都弁護士会）のツイートの記録（2016年9月3日のまとめ分）,http://hirono2016k.blogspot.com/2016/09/201693.html
告訴状の下書き）「実名報道」をキーワードにしたモトケンこと矢部善朗弁護士（京都弁護士会）のツイートの記録（2016年9月3日まとめ分）,http://hirono2016k.blogspot.com/2016/09/201693_3.html

参考資料：「マスコミ」をキーワードに含む「モトケンこと矢部善朗弁護士（京都弁護士会）（@motoken_tw）」のツイート・リツイート（2010-03-02 13:14〜2016-08-30 11:16）「1-100／487」件,http://hirono2016k.blogspot.com/2016/09/motokentw2010-03-02-13142016-08-30.html
参考資料：「マスコミ」をキーワードに含む「モトケンこと矢部善朗弁護士（京都弁護士会）（@motoken_tw）」のツイート・リツイート（2010-03-02 13:14〜2016-08-30 11:16）「101-200／487」件,http://hirono2016k.blogspot.com/2016/09/motokentw2010-03-02-13142016-08-30_3.html
参考資料：「マスコミ」をキーワードに含む「モトケンこと矢部善朗弁護士（京都弁護士会）（@motoken_tw）」のツイート・リツイート（2010-03-02 13:14〜2016-08-30 11:16）「201-300／487」件,http://hirono2016k.blogspot.com/2016/09/motokentw2010-03-02-13142016-08-30_29.html
参考資料：「マスコミ」をキーワードに含む「モトケンこと矢部善朗弁護士（京都弁護士会）（@motoken_tw）」のツイート・リツイート（2010-03-02 13:14〜2016-08-30 11:16）「301-400／487」件,http://hirono2016k.blogspot.com/2016/09/motokentw2010-03-02-13142016-08-30_41.html
参考資料：「マスコミ」をキーワードに含む「モトケンこと矢部善朗弁護士（京都弁護士会）（@motoken_tw）」のツイート・リツイート（2010-03-02 13:14〜2016-08-30 11:16）「401-487／487」件,http://hirono2016k.blogspot.com/2016/09/motokentw2010-03-02-13142016-08-30_81.html

　告訴状の下書き）という見出し２つについては、先ほどデータベースを含めて変更をしました。

　報道を前提になぜモトケンこと矢部善朗弁護士（京都弁護士会）のコメントの不合理性と、国民の目をあざむく欺瞞性を感じたかというと、その事案に即した理由は、先に記述を予定をしていた野田隼人弁護士の項目において具体的なご説明をします。

　この項目の締めくくりに、スクリーンショットを紹介しておきます。

投稿者：s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2016-09-08 20:57  ツイート： https://twitter.com/s_hirono/status/773852661166641152
2016-09-08-205701_モトケン　@motoken_tw　　10時間10時間前証拠は見てないけど、報道された表現を読む限り、「疑わしきは被告人の不利益に」、「被告.jpg https://t.co/DMZwXYvW6R

2016-09-08　木曜日　20：58　＜＜ ［［　←これまでの記述範囲の終了時刻］］＜＜
**** 「私だって「遺体が“人の可能性はない”と認識する特段の事情はない」と言われたら笑う気がします」（相模原死体遺棄事件）という野田隼人弁護士のツイートの疑問

2016-09-08　木曜日　21：03　＞＞ ［［　←これからの記述範囲の開始時刻］］＞＞

ツイート：nodahayato（弁護士　野田隼人）：2016/09/08 10:15： https://twitter.com/nodahayato/status/773691172145418241 ：
引用→　 判示からすると、特段の事情のない限り人の死体と認識していたとされる場面の経験則があることになるはずなんだけど、それがどんなものか気になる。

ツイート：nodahayato（弁護士　野田隼人）：2016/09/08 10:06： https://twitter.com/nodahayato/status/773689034845532160 ：
引用→　 教官には申し訳ないけど、私だって「遺体が“人の可能性はない”と認識する特段の事情はない」と言われたら笑う気がします。 https://t.co/Y0XoAefgY5

　上記2つの野田隼人弁護士のツイートは「相模原死体遺棄事件」の関連ツイートです。ニュース記事のURLの引用がありますが、そのタイトルをみただけでもだいたいのことは理解される内容だと思います。

　上記の訂正になりますが、正確にはURLの引用は次の岡口基一裁判官のツイートで、そちらのニュース記事のURLが引用されています。

ツイート：okaguchik（岡口基一）：2016/09/08 07:58： https://twitter.com/okaguchik/status/773656745302380544 ：
引用→　 弁護人が裁判長の読み上げる判決文を一笑に付す＜改行＞https://t.co/hfXWmL3QYW

相模原での死体遺棄事件 法廷で弁護士が笑いだし裁判長が注意 - ライブドアニュース http://news.livedoor.com/article/detail/11988034/

　なお、岡口基一裁判官には今のところブロックは確認していませんが、次の刑裁サイ太のツイートを見て、ずいぶんと印象が変わりました。表現の自由の尊重に少しばかり天秤が傾いていましたが、それが刑裁サイ太のことで社会的害悪と危険性への憂慮に針が跳ね上がりました。

ツイート：uwaaaa（サイ太）：2016/07/29 17:30： https://twitter.com/uwaaaa/status/758942737194332160 ：
引用→　 「卒業文集の公表が適法なら，ワシの適法なフンドシ姿も公表してクレオ！！」

　ブログの記事としても次のものとして記録を作成しております。

刑裁サイ太の最新ツイート100: ”「卒業文集の公表が適法なら，ワシの適法なフンドシ姿も公表してクレオ！！」”他,http://hirono2016k.blogspot.com/2016/07/100_30.html

　刑裁サイ太の狂人性を更新させたと言えますが、それも波及的な影響であって、その悪影響は各方面に渡るものであって、裁判官としての適正に初めて疑問を感じましたが、そういう指摘は他に見たことがありません。逆に励ましのような反応が大きいらしく、裁判官本人も正当性を強めたようです。

　ネット上の弁護士の評価として、岡口基一裁判官とは真逆の対照とも思えたのが、記事にある泉澤章弁護士に笑われた裁判官です。せせら笑う、という表現は他の記事で見たように思いますが、「嘲笑」とまでは見ていませんが、私は嘲笑こそが事案に即した表現だと考えています。

　泉澤章弁護士について、足利事件で活躍した弁護士ということも初めて知りましたが、それも前出の記事の内容がきっかけです。

奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「泉澤章弁護士」の検索結果 - Twilog http://bit.ly/2crItgU

　確認のため、上記の方法でTwilogで調べましたが、もっとも古いツイートが次のものとなっていました。

ツイート：hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）：2016/09/06 21:31： https://twitter.com/hirono_hideki/status/773136497629290497 ：
引用→　 泉澤章弁護士らが弁護人である覚せい剤密輸事件で無罪確定｜東京合同法律事務所 https://t.co/erjA7yzrAW

奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「泉沢 弁護士」の検索結果 - Twilog http://bit.ly/2bWk8Sy

　少し変更をして上記のように検索をすると、次のツイート一つが先ほどのものより古いものとして表示されました。

ツイート：hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）：2015/06/07 18:39： https://twitter.com/hirono_hideki/status/607481976493342720 ：
引用→　 （引用→）日弁連再審部会長の泉沢章弁護士は「証拠は捜査機関が税金で集めた公共物で、検察が独占するのは不当。弁護側にもアクセスする権利が平等に認められるべきだ」と訴えている。 http://t.co/mKA5qE9V74

　内容を読んでも思い出せないようなツイートです。「日弁連再審部会長」という肩書は、昨日か一昨日に泉澤章弁護士について調べた段階で目にしていた情報なので、それ自体に驚きはありませんが、再審という制度自体に重大な疑義をさらに深く、強く感じさせられました。

　野田隼人弁護士も「 判示からすると、特段の事情のない限り人の死体と認識していたとされる場面の経験則があることになるはずなんだけど、それがどんなものか気になる。」というツイートで疑問を呈しています。この経験則というのも、私はかねて重要なキーワードとして考えてきました。

　なぜなら、裁判官が自由な心証として証拠を評価し、独立して判決もしくは決定という法律判断をすることは憲法に保証されている職権でありながら、その例外として「経験則に反すること」というのを、ずっと前、多分平成9年より以前に、専門書で目にしたという記憶があるからです。

　今、私の頭の中にある認識の範囲でのみの指摘としますが、その判決には、一月以上高額な家賃のマンションに死体らしきものを置き、外に出て外泊を繰り返し、死体らしきものを運びだした翌日にはマンション全体に異臭が充満し、警察が駆けつける事態にも発展していたということ。

　さらには、芸能事務所の社長が違法に飼っていた虎の死骸と主犯格に説明を受けながら、本人は犬の死骸だと認識していたと弁護人も強調していることを挙げられます。

　主犯格の説明通りに受け止めて、虎の死骸だと認識していたとすれば、一般常識として虎は国際的にも商取引を厳しく規制される希少動物であるということ、その認識に従えば、異臭を放つまで放置してもなお秘密裏に処分する必要性を合理的に理解できるとこと、犬との認識であればその必要性もなし。

　マンションの一室から容易に運びだせなかったことで、一月以上が経過し、周辺に問題視される異臭を放つ事態に立ち至ったことによほど切羽詰まった状況であったと想像されるし、犬の死体の処分のような違法でない時代であれば、非力な女性に運搬を持ちかける必然性にも大きな疑問を感じます。

　素人の見立てではありますが、そのような状況判断も精神疾患等特段の事情のない一般人としての経験則であり、それを判断すべきなのも裁判官としての事実認定における期待される経験則なのではと考えました。

　素人といえば、モトケンこと矢部善朗弁護士（京都弁護士会）は直近で、性懲りもなく次のようなツイートもやっていました。

ツイート：motoken_tw（モトケン）：2016/09/08 12:15： https://twitter.com/motoken_tw/status/773721361344671744 ：
引用→　 .@Hideo_Ogura 小倉弁護士は何を議論してるのかな？揚げ足取りを繰り返してど素人に対して自分が優位だとおもわしめたいのかな？努力義務規定と二重国籍を議論してたのではないのかな？訂正、小倉弁護士はそもそも議論するつもりはなかったね。

　たまたま目についたところですが、モトケンこと矢部善朗弁護士（京都弁護士会）は裁判員制度に関連して、次のツイートもやっていました。

ツイート：motoken_tw（モトケン）：2016/09/07 18:09： https://twitter.com/motoken_tw/status/773448141022568448 ：
引用→　 裁判員にそれを求めるのはなかなか難しいのではないかな。 https://t.co/VLNXtOirS6

　上記のモトケンこと矢部善朗弁護士（京都弁護士会）のツイートに引用されているURLは、次の元裁判官のツイートです。

ツイート：1961kumachin（中村元弥）：2016/09/07 17:17： https://twitter.com/1961kumachin/status/773434929455702016 ：
引用→　 取調録画の実質証拠化に関する東京高裁平成28年8月10日判決は、広く知られるべきだな。「捜査機関の管理下において、弁護人の同席もない環境で行われる被疑者等の取調」と、公判廷における被告人質問との違いを明言し、録画の供述態度により「直感的で主観的な判断に陥る危険性」を指摘している

　この項目のメインに据えた野田隼人弁護士については、比較的最近になって@hirono_hidekiのアカウントでブロックされていたことに気が付きました。もともとそのアカウントでTwitterを初めて間もない頃に、フォロー返しとして印象的な記憶があったので、意外性も大きかったです。

　これも自分のパソコン内のシステムで検索による確認が可能かと思います。私の記憶としては2,3ヶ月まえなのですが、確認してみないとわかりません。

[6820]  % find /home/a66/git/kk_hirono_2016/a_資料/a_スクリーンショット  -name '*ブロック*nodahayato*.jpg'  -type f -printf '%f\n'
2016-06-10-235049_ブロックされているため、@nodahayatoさんのフォローや@nodahayatoさんのツイートの表示はできません。詳細はこちら.jpg
2016-09-08-165034_ブロックされているため、@nodahayatoさんのフォローや@nodahayatoさんのツイートの表示はできません。詳細はこちら.jpg
2016-07-29-213653_ブロックされているため、@nodahayatoさんのフォローや@nodahayatoさんのツイートの表示はできません。詳細はこちら.jpg

　並び順に疑問がありますが、パソコンのシステム内から３つのスクリーンショットのファイルが発見できました。これをみると6月10日が最初のブロックされいていたことの発見であったと確認できます。

　ファイル名の一部から次のように写真付きツイートとしての記録を探します。

非常上告-最高検察庁御中_ツイッター(@s_hirono)/「2016-06-10-235049_ブロックされて」の検索結果 - Twilog http://bit.ly/2bWrfKL

　上記の検索で見つかったのが次のツイートです。

ツイート：s_hirono（非常上告-最高検察庁御中_ツイッター）：2016/06/10 23:50： https://twitter.com/s_hirono/status/741281496053354496 ：
引用→　 2016-06-10-235049_ブロックされているため、@nodahayatoさんのフォローや@nodahayatoさんのツイートの表示はできません。詳細はこちら.jpg https://t.co/3Ma815JaOZ

　夕方に調べたのですが、野田隼人弁護士は、東電OL殺害事件で有名になった神山弁護士や、後藤貞人弁護士に尊崇の念を抱いているようです。いずれも検索結果は「神山先生」などとなっていました。

神山 from:nodahayato - Twitter検索 https://twitter.com/search?q=%E7%A5%9E%E5%B1%B1%20from%3Anodahayato&src=typd

後藤 from:nodahayato - Twitter検索 https://twitter.com/search?q=%E5%BE%8C%E8%97%A4%20from%3Anodahayato&src=typd

　どちらかの弁護士に対して私が否定的なツイートをしたことが、ブロックされた原因なのかとも考えますが、確かなことはブロックをした本人にしかわからないことです。

　東電OL殺害事件については、まだ無地だと思いますが、本書の項目としての洗い出しを終えています。いずれまた別の機会に取り上げることがあるかと思います。

　野田隼人弁護士に関しては、滋賀県の法律事務所の名称とともに実在性が確かと判断しうる弁護士です。過去の何度か返信のやりとりをした記憶もあったのですが、今日は上記の検索の過程で、次のツイートを一つ発見しました。これもなかなか考えさせられる内容のものです。

ツイート：nodahayato（弁護士　野田隼人）：2013/06/16 08:35： https://twitter.com/nodahayato/status/346048315026178049 ：
引用→　 @hirono_hideki 弁護士からみると明確なんですが、おおっぴらに指摘もできず…。高額報酬でも見合った価値があるかの問題ですし。弁護士が冤罪に巻き込まれたとして、後藤貞人先生に一千万払う人はそれなりにいると思います。

　冤罪の危険性つまりリスクを高めているのが、このような弁護士だという思いを日増しに強めている昨今ですが、基本的な認識は、泉澤章弁護士を知ったことでより地に足のついたものになったと考えています。実務の影響力として深澤諭史弁護士や刑裁サイ太とは格の違いも感じました。

2016-09-08　木曜日　22：51　＜＜ ［［　←これまでの記述範囲の終了時刻］］＜＜















