* 夕方のテレビニュースで詳細を知った「青森中2女子いじめ自殺事件」で考えたこと

2016-08-30　火曜日　19：51　＞＞ ［［　←これからの記述範囲の開始時刻］］＞＞

告訴状の下書き）「少年犯罪」「少年事件」「少年法」に関連した新潟の高島章弁護士の主なツイートの刑事弁護の歴史的資料、記録としてのまとめ,http://hirono2016k.blogspot.com/2016/08/blog-post_408.html

　上記の記事の本書における編集で、ちょうどTwitterへの投稿作業が終わりかけた頃、テレビで青森の中2女子自殺の詳細な報道を見ました。

　当初はありがちな自殺の一つかと思っていたのですが、詳細を知っていくつかとても気になる点があったので、本件告訴事件の参考として取り上げさせてもらうことにしました。

　一つは、次のネット記事から見つけることが出来たので、その部分を引用させて頂きます。

／＊＊＊＊＊＊＊＊＊＊（引用開始）＊＊＊＊＊＊＊＊＊＊
引用URL＞＞＞＞：http://blog.livedoor.jp/rbkyn844/archives/8562685.html 青森中2女子いじめ自殺事件の凄絶な内容が明らかに・・・:暇つぶしニュース

１、２年の時で●の噂流したりそれを信じたりいじめてきたやつら、自分でわかると思います。もう、二度といじめたりしないでください。 

＊＊＊＊＊＊＊＊＊＊（引用終了）＊＊＊＊＊＊＊＊＊＊／

　他にはネットで情報を見つけることが出来ないのですが、氣になった点として、教師にも相談にのってもらいとても感謝していると遺書に綴っていたこと、その遺書がスマホでの文面だったということも情報化社会の新たな変化を感じました。

　さらには両親にも感謝の言葉を書きながら、鉄道自殺することについて大きな賠償になるかも知れずごめんなさい、という趣旨のことを書いていたとのことです。「鉄道事故」と実際は書いていたようです。そういう迷惑が及ぶことを13歳が認識しながら感謝とともに認めていたことに考えさせられました。

　テレビでは自殺した少女の父親が顔出しで、無念の気持ちを吐露されていました。この自殺の問題も弁護士らがどういう反応をするか注目をしたいところで、少女のご冥福を祈りながら、微力でもその遺志に沿いたいと思いました。

　この自殺のニュースとは、まったく別の目的だったと思いますが、弁護士浜ちゃんのタイムラインを遡っていて、たまたま自殺に関連した気になるツイートを発見しました。テレビでその件の報道が終わったのは、ちょうど18時30分頃だったと思います。3分か長くて5分ほどの報道だったと思います。

投稿者：s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2016-08-30 20:19  ツイート： https://twitter.com/s_hirono/status/770581616334745600
2016-08-30-201903_弁護士　浜ちゃん　@satoshihamada　　5時間5時間前弁護士　浜ちゃんさんがたらればをリツイートしましたそのとおりだなと。.jpg https://t.co/qEC3xcE4OZ

投稿者：s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2016-08-30 19:26  ツイート： https://twitter.com/s_hirono/status/770568486280007680
2016-08-30-192653_弁護士　浜ちゃん　@satoshihamada　　2015年1月19日高野先生と言えば法廷弁護技術ワークショップの際、先生が翻訳された「弁.jpg https://t.co/bGOUXdi00s

　スクリーンショットを撮り忘れていたので、実行したのが20時19分のものです。弁護士浜ちゃんのツイートは、高野隆弁護士に関するツイートで記録の必要を感じたものがあったので、19時26分にスクリーンショットを作成していました。

　自殺に関連して気になったのは弁護士浜ちゃんこと濱田諭弁護士の次のツイートです。ツイートの発言だけでは意味がわからないでしょうが、次に続くツイートのURLを引用しており、それに対する言及というスタイルになっています。

ツイート：satoshihamada（弁護士　浜ちゃん）：2016/08/30 15:40： https://twitter.com/satoshihamada/status/770511574419124224 ：
引用→　 そのとおりだなと。 https://t.co/DHd6g4QXg7

ツイート：tarareba722（たられば）：2016/08/30 09:09： https://twitter.com/tarareba722/status/770413005662072832 ：
引用→　 「借金が膨らんでどうにもならなくなったら弁護士に」と「眠れなくて精神の失調がどうにもならなくなったら精神科医に」と「任された仕事が忙しすぎてどうにもならなくなったら労基署に」という社会のセーフティネット3点を中学校あたりで徹底的に教えておけば、自殺率はグッと減少するといつも思う。

　たられば、というプロフィールの名前のツイッターアカウントですが、これまでに何度か法クラのリツイートして見覚えのあるものです。たられば、という言葉を初めて知ったのも3年ほど前のことで、珠洲警察署の担当者に、たらればの話には答えられない、と言われたのが節目の一つにもなっています。

　含蓄の深そうなツイートなので全てを推し量る技量も私にはありませんが、「精神的な不調で眠れなくなった」というのは、私の平成4年の事件の動機として精神的に追いつめられていた状況を物語るもので、大型の長距離運転手として重大事故を起こして被害を与えてしまうことも強く危惧していました。

　自殺をするような中学生の救世主としての弁護士の弓状を訴えかける自信満々の発言かとも理解できますが、今日は深澤諭史弁護士も似たような趣旨のツイートやリツイートをしていたかと思うので、それもあわせてご紹介しておきたいと思います。

リツイート：fukazawas（深澤諭史）＞2016/08/30 18:07／2016/08/30 16:29＞ https://twitter.com/fukazawas/status/770548400513175552 ＞
 harrier0516osk （弁護士法人向原・川上総合法律事務所　向原）＞ https://twitter.com/harrier0516osk/status/770523794553221120 ＞
引用＞　 自由競争とか言ってるのに、こじんまりやってる事務所の横で、税金投入して不当廉価でサービス提供する奴らとどうやって競争しろってんだよｗ＜改行＞しかも、馬鹿高い弁護士会費を取ってる団体がそれを推奨。＜改行＞かつその会費で、泥棒弁護士のケツ拭きをするという不思議な制度を導入。強制加入廃止でよくね？

リツイート：fukazawas（深澤諭史）＞2016/08/30 14:13／2016/08/06 10:40＞ https://twitter.com/fukazawas/status/770489710074535936 ＞
 depon2010 （やっぱり猫が好き）＞ https://twitter.com/depon2010/status/761738565705314304 ＞
引用＞　 弁護士は自営業だ自助努力だ自然淘汰だと言われ続ける中、さらに連帯責任まで負わされるのか。ダメな弁護士を選んでしまった依頼者の自己責任は問われないのか。何故弁護士被害だけ手厚く補償されるべきなのか。その辺の議論が全く見えないままの観測気球だな。 

リツイート：fukazawas（深澤諭史）＞2016/08/30 13:51／2016/08/30 10:16＞ https://twitter.com/fukazawas/status/770484148238770176 ＞
 harrier0516osk （弁護士法人向原・川上総合法律事務所　向原）＞ https://twitter.com/harrier0516osk/status/770429918568210434 ＞
引用＞　 司法試験合格者が巷に溢れていて就職難だと言われているのに（そうか？というのが私の実感ですが。ある程度なんとかなっている感じもある。事務所に入るという点だけならば。）、司法試験合格者を登用せず、なぜ合格していない人を、検察官同様の職務をする立場に登用しつづけるのか。 

ツイート：fukazawas（深澤諭史）：2016/08/30 09:20： https://twitter.com/fukazawas/status/770415775274237952 ：
引用→　 「余裕があるからするのでは人権活動と呼ぶには値しない。」ｂｙ東京新聞 https://t.co/fHnSyY6Xa3

リツイート：fukazawas（深澤諭史）＞2016/08/30 09:09／2016/08/30 08:40＞ https://twitter.com/fukazawas/status/770413089069998080 ＞
 k_sawmen （泥濘大魔王サイケ）＞ https://twitter.com/k_sawmen/status/770405707392790528 ＞
引用＞　 学部時代俺「直接人の役に立てる弁護士になりたい。市民の生活上の不安を法律を使ってなんとかしてあげたい」＜改行＞現在俺「とりあえず登録後何年かはお金になる仕事しかできないぞこれ……」＜改行＞法科大学院・司法修習で豊かな人間性を養成☆ミ 

リツイート：fukazawas（深澤諭史）＞2016/08/30 09:08／2016/08/30 09:05＞ https://twitter.com/fukazawas/status/770412878180474880 ＞
 un_co_the2nd （うのじ）＞ https://twitter.com/un_co_the2nd/status/770411972495941632 ＞
引用＞　 人的なインフラには金をかけないというのよくないよ。熊本地震の時に、非正規雇用公務員ばかりだとやばいって学ばなかったっけ…。＜改行＞信玄公だって人は城人は石垣人は堀って言ってたじゃん。 

リツイート：fukazawas（深澤諭史）＞2016/08/30 07:35／2016/08/30 00:08＞ https://twitter.com/fukazawas/status/770389508361629696 ＞
 keita_adachi （弁護士あだちけいた㌠シン･ゴジラはいいぞ）＞ https://twitter.com/keita_adachi/status/770276850706751488 ＞
引用＞　 副検事が足りないなら正検事増やせばいいじゃんというのは正論だが、「修習生を採用するより内部で職員をたたき上げた方が忠誠心も高く使い勝手がいい。辞めて弁護士に転身することもないし」と本気で考えていそうだからな。 

ツイート：fukazawas（深澤諭史）：2016/08/30 07:16： https://twitter.com/fukazawas/status/770384651034566656 ：
引用→　 とにかく着手金は払いたくない、そのかわり成功報酬高くしてよいって人は、よっぽど自分自身の請求に自信がない、何か弁護士に隠していることがあるのではないかと思ってしまう。＜改行＞そして、実際、その通りのケースも多い。 https://t.co/R8LSEX4NHe

リツイート：fukazawas（深澤諭史）＞2016/08/30 06:40／2016/08/30 01:11＞ https://twitter.com/fukazawas/status/770375618835775489 ＞
 bengoshi_black （ＫＢブラック）＞ https://twitter.com/bengoshi_black/status/770292799375679489 ＞
 引用＞　 え、１０万円だけで済むの？（） https://t.co/wQmgDyQPRd 










