**** 「モトケンこと矢部善朗弁護士（京都弁護士会）と小倉秀夫弁護士（東京弁護士会）対する、名誉毀損の刑事告訴における具体的相談に先立ち、珠洲警察署に提出する準備書面」と題する書面

:CATEGORIES: 名誉毀損の刑事告訴における具体的相談に先立ち、珠洲警察署に提出する準備書面
:TAGS: モトケンこと矢部善朗弁護士（京都弁護士会）,小倉秀夫弁護士

2016-09-23　金曜日　16：21　＞＞ ［［　←これからの記述範囲の開始時刻］］＞＞

　この「モトケンこと矢部善朗弁護士（京都弁護士会）と小倉秀夫弁護士（東京弁護士会）対する、名誉毀損の刑事告訴における具体的相談に先立ち、珠洲警察署に提出する準備書面」と題する書面は、本書（金沢地方検察庁に提出する別件殺人未遂での告訴状）の一部分として、これから作成します。

　珠洲警察署に電話連絡したのは21日の午前中だったと思います。初めに掛けた時は担当者が不在だということで、要件を伝え、折り返し携帯電話に掛けてくれるようにお願いしました。

　12時50分ころに携帯電話に電話がなったので、すぐに出ようとしたのですが、ボタン操作の押し間違えでもあったのかすぐに切れてしまいました。着信を見ると珠洲警察署の電話番号だったので、すぐに警察署の方に電話をしました。

　次が当日のメモのようなツイートになります。

奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/2016年09月21日 - Twilog http://twilog.org/hirono_hideki/date-160921/asc

ツイート：hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）：2016/09/21 10:56： https://twitter.com/hirono_hideki/status/778412551205969920 ：
引用→　 珠洲警察署に電話。10時47分から55分ころまで。取次を含め。担当者は不在。 https://t.co/jgE1Va4eGh

ツイート：hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）：2016/09/21 12:58： https://twitter.com/hirono_hideki/status/778443319160377344 ：
引用→　 珠洲警察署にかけ直しの電話。

ツイート：hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）：2016/09/21 15:16： https://twitter.com/hirono_hideki/status/778477961502531584 ：
引用→　 再度、珠洲警察署に電話。2,3分前。書面で提出のお知らせ。

ツイート：hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）：2016/09/21 17:52： https://twitter.com/hirono_hideki/status/778517231927906304 ：
引用→　 .@Hideo_Ogura 本日、小倉秀夫弁護士とモトケンこと矢部善朗弁護士（京都弁護士会）@motoken_twを法律家として完全成仏、弁護士妖怪の退治とすべく、珠洲警察署に電話連絡をして、近日中に書面を提出する旨、お伝えしました。被害者の立場としてマスコミにもばらまくとお伝え

　自分なりの分析ですが、急に珠洲警察署に電話をしようと思ったのは、次のスクリーンショットにある深澤諭史弁護士のツイートがきっかけであり、動機につながったことになります。先ほど確認すると、同じ日の朝ではなく、前の晩に読んでいたツイートだったようです。

ツイート：s_hirono（非常上告-最高検察庁御中_ツイッター）：2016/09/20 19:05： https://twitter.com/s_hirono/status/778173127402676224 ：
引用→　 2016-09-20-190456_こんなことが横行していて、しかもおとがめ無しなのに、生まれてこの方、一度も罪証隠滅も逃亡もしたことの無い被疑者の勾留を安易に認めるなよって話.jpg https://t.co/Mkw4Yi3qZq

ツイート：s_hirono（非常上告-最高検察庁御中_ツイッター）：2016/09/20 19:07： https://twitter.com/s_hirono/status/778173788135579648 ：
引用→　 2016-09-20-190738_でゅーく（●―●）まんGO　@nan5o　1時間1時間前高畑裕太「強姦致傷」事件の示談金は1500万円だった！（週刊文春）　-　Yahoo.jpg https://t.co/OS6XkhlRYS

ツイート：s_hirono（非常上告-最高検察庁御中_ツイッター）：2016/09/20 20:33： https://twitter.com/s_hirono/status/778195249025855488 ：
引用→　 2016-09-20-203255_このページは存在しません。以下の検索ボックスを使ってTwitterを検索できます。ホームに戻る場合はこちら。.jpg https://t.co/jvrNinLa9v

　よく見ると19時5分というまだ夕方という時間帯でのスクリーンショットでした。寝る前に近い夜遅い時間と思っていたのですが、意外に早い時間で、それだけ長い間、深澤諭史弁護士のツイートのことを反芻し続け、珠洲警察署への電話連絡につながったということになりそうです。

　すでに本日作成の別の項目で触れたと思いますが、大きなきっかけになった深澤諭史弁護士のツイートの内容は、次になります。これも再掲になるはずかと思います。

ツイート：fukazawas（深澤諭史）：2016/09/20 18:10： https://twitter.com/fukazawas/status/778159315010121729 ：
引用→　 こんなことが横行していて、しかもおとがめ無しなのに、生まれてこの方、一度も罪証隠滅も逃亡もしたことの無い被疑者の勾留を安易に認めるなよって話ですな。＜改行＞（・∀・＃） https://t.co/5qclM9BWZS

　このツイートだけを読むと、何の話かわかりませんが、リンクになっているURLのツイートを見ると、高畑裕太氏の強姦致傷事件に関連したものだとわかります。

ツイート：takeshiful（こんたけ㌠）：2016/09/20 18:08： https://twitter.com/takeshiful/status/778159008309977088 ：
引用→　 ＞捜査関係者の証言や捜査資料を元に事件の全容を再現。＜改行＞＜改行＞これ捜査員の守秘義務は一体どうなっているんでしょう。性犯罪で、しかも示談の末に不起訴になった案件なのに…。

　今見ると、上記のツイートの直前のリツイートが消えていました。リツイートしていたツイートが削除された可能性もありますが、とりあえず次がスクリーンショットです。

投稿者：s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2016-09-23 18:17  ツイート： https://twitter.com/s_hirono/status/779248233239355392
2016-09-23-181706_これ捜査員の守秘義務は一体どうなっているんでしょう。性犯罪で、しかも示談の末に不起訴になった案件なのに…。.jpg https://t.co/Yp7Lyc0TIf

　やはり元のツイートが削除されていましたが、この、でゅーく（●―●）まんGO、という弁護士らしきアカウントは、短期間でそれまでのツイートを全て削除していることを思い出しました。次がスクリーンショットになりますが、読み込めているのは9月21日のツイートまでです。

投稿者：s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2016-09-23 18:27  ツイート： https://twitter.com/s_hirono/status/779250777369956352
2016-09-23-182712_でゅーく（●―●）まんGO　@nan5o　9月21日ふと思い出したこと】起訴状を弁護人に送達する規定はない.jpg https://t.co/cZtIV5LGCd

　深澤諭史弁護士のようにプロフィールに弁護士であることを明示しているわけでもないので、さほど問題視することではないような気もしますが、一週間も経たないうちに定期的に過去のツイートを全て削除しているというのは、一般人でも他に見たことがなく、社会人としての常識から疑いたくなります。

　次が削除されたツイートの内容です。データベースに保存されていたデータになります。

＞＞引用＞高畑裕太「強姦致傷」事件の示談金は1500万円だった！（週刊文春） - Yahoo!ニュース https://t.co/Lmn7ww9XyA スプリングセンテンスさまからこの取材手法は大いに学ぶべきかもしれないね

　あまりよく憶えていなかったのですが、「スプリングセンテンスさまからこの取材手法は大いに学ぶべきかもしれないね」というのが、削除したアカウントのリンクの記事に対するコメントだったようです。ずいぶんと皮肉を込めたような発言ですが、ほんの一部しか伝わっていません。

　マスコミに対する批判的な姿勢は、深澤諭史弁護士にも強く感じられてきたものですが、モトケンこと矢部善朗弁護士（京都弁護士会）をお手本にしてきたのではないかと考えることも多々ありました。部分的な継承とも言えます。

　マスコミに対する不信や批判は昔からごく身近な存在となっていて、ひところはマスゴミという言葉もよく見かけましたが、極端でわかりやすい傾向性のある深澤諭史弁護士などを見ていて、適切な判断に必要な情報をできるだけ与えない下心が、弁護士の泥棒根性の本質の一つだと考えるようになりました。

　深澤諭史弁護士は弁護士になったことで、特別な能力と特典が装備されたプレイヤーとして人間社会をゲームの世界観で見ているのではないかと考えることがあり、これまでもそれらしいツイートを目にしてきましたが、昨夜から今日の午前中の間に、より鮮明なかたちでのツイートを見ることが出来ました。

ツイート：fukazawas（深澤諭史）：2016/07/27 09:44： https://twitter.com/fukazawas/status/758100645551276032 ：
引用→　 異世界の勇者「うちの世界じゃ，『魔王を倒せ』と王様はいうのだけれども，５０ゴールドと最安装備しかもらえないんだ。酷いだろ。」＜改行＞＜改行＞法クラの勇者「先払いしてもらえるだけいいじゃないか。こっちの王様（冒険者テラス）じゃ，実費も後払で下手すりゃ踏み倒されるんだぞ」＜改行＞#法クラクエスト

ツイート：fukazawas（深澤諭史）：2016/07/27 09:50： https://twitter.com/fukazawas/status/758102303761047552 ：
引用→　 冒険者テラス「隣町に魔王軍が向かっている！隣町を救うため，直ちに急行して下さい！」＜改行＞（討伐後）＜改行＞冒険者テラス「魔王軍の到着後のため，報酬はゼロゴールドです。」＜改行＞#法クラクエスト

　今、上記のツイートを探すのみ深澤諭史弁護士のタイムラインをたどっていると、見覚えのあるツイートを深澤諭史弁護士のリツイートとして発見しました。確認の必要がありますが、深澤諭史弁護士のリツイートとしても前に見ているような気がします。

ツイート：hikini9_motu（ひきにく）：2016/06/07 21:44： https://twitter.com/hikini9_motu/status/740162391384588288 ：
引用→　 元始、司法修習生は太陽であった。真正の人であった。今、修習生は月である。貸与金に依って生き、法の光によって成仏する。病人のような蒼白い顔の月である。私共は隠されてしまった我が給費制をいまや取戻さねばならぬ

　データベースで調べると、やはり初めてのリツイートではなかったですが、想像したような複数回の繰り返しではなく、2件目になっていました。

リツイート：fukazawas（深澤諭史）＞2016/06/21 11:05／2016/06/07 21:44＞ https://twitter.com/fukazawas/status/745075114111205376 ＞
 hikini9_motu （ひきにく）＞ https://twitter.com/hikini9_motu/status/740162391384588288 ＞
引用＞　 元始、司法修習生は太陽であった。真正の人であった。今、修習生は月である。貸与金に依って生き、法の光によって成仏する。病人のような蒼白い顔の月である。私共は隠されてしまった我が給費制をいまや取戻さねばならぬ 

リツイート：fukazawas（深澤諭史）＞2016/09/23 14:35／2016/06/07 21:44＞ https://twitter.com/fukazawas/status/779192403508891648 ＞
 hikini9_motu （ひきにく）＞ https://twitter.com/hikini9_motu/status/740162391384588288 ＞
引用＞　 元始、司法修習生は太陽であった。真正の人であった。今、修習生は月である。貸与金に依って生き、法の光によって成仏する。病人のような蒼白い顔の月である。私共は隠されてしまった我が給費制をいまや取戻さねばならぬ 

　連続テレビ小説とと姉ちゃん、出てきたフレーズをもじったものと思いますが、彼らには弁護士業界の斜陽、衰退、不振が、すべて弁護士業界意外に原因があり、自分たちはそのとばっちりを受けた被害者であると声たかだかに訴え、不満をつのらせているふしがあります。

　同調性があるからのリツイートなのだと思いますが、このような手合は、深澤諭史弁護士の周りに主に深澤諭史弁護士のリツイートとして、湧いてくるように出てくる、「さまよえる弁護士人」とでも名付けたい人々です。

　「貧すれば鈍する」という言葉がありますが、「小人閑居して不善をなす」とも言いますが、時間が自由になることを差し引いて考えても、尋常でない数のツイートをやっているのも、多くの弁護士に見られる特徴で、他に調べることや考えることで、研鑽し信頼を増すという考えがないのかと思います。

　ツイッターで四六時中ツイートしているような弁護士もかなりの数いますが、実績と定評のある弁護士もいて、その代表格の一人と目されるのが、マスコミに「無罪請負人」などともてはやされた 弘中惇一郎であって、事務所が受任した案件として久々に社会の注目を集めた事件があります。

　広く社会に知られるところになったと思われる大物女優高畑淳子氏の息子の高畑裕太氏の強姦致傷事件ですが、示談成立から起訴猶予処分の釈放となり、その直後に出したコメントが、社会に疑問を巻き起こしたことでも、これまでの弁護士に対するイメージを大きく変えた問題です。

　もう一年以上の期間に渡るように思いますが、弁護士が全面に出て関わり、マスコミに取り上げられる事件というのは、ほとんど例外がないと思えるぐらい、想像を超えて惨憺たる結果になっていると見ています。

　その直近が、弘中惇一郎が関わる強姦致傷事件ですが、世間の見方が変わってきたことがより大きな要因とも感じます。魔法が通用しなくなったとも見えますが、積み重ねた国民の学習能力が奏功し始めた成果とも考えています。実質的な市民社会の熟成であり、大勢の風向きが変わったとも見ています。

　私も長い時間をかけて刑事事件や刑事裁判に関心を持って取り組んできましたが、まるで共通した問題点の集大成のようになったのが、高畑裕太氏の強姦致傷事件でした。

　そして、その高畑裕太氏の強姦致傷事件に対する深澤諭史弁護士の反応が、連鎖反応のようにモトケンこと矢部善朗弁護士（京都弁護士会）と小倉秀夫弁護士の刑事処分の実現に向け、大きな一歩を踏み出すきっかけともなったので、実に感慨深いものがあります。

　ネット上の情報として広く深く、一通りのことは理解したつもりでいた事件でしたが、本日、実際に読んだ週刊文春の当該記事は、私なりの分析に基づく予想や見立てを崩し、視野を広める、具体的な判断材料としての内容となっていました。

　本件告訴の事実関係の主要な部分は性犯罪でもありますし、とても参考になることが多く、自分が伝えるべき内容として、これまで以上に深く考えさせられるところがありました。

　この項目は、「モトケンこと矢部善朗弁護士（京都弁護士会）と小倉秀夫弁護士（東京弁護士会）対する、名誉毀損の刑事告訴における具体的相談に先立ち、珠洲警察署に提出する準備書面」の序章という位置づけになりますが、この名誉毀損での告訴を全容解明における露払いとも位置づけています。

　昨日は早朝の4時20分ぐらいに家を出て小木港の東一文字堤防にアジ釣りに行き、家に戻ったのが19時半に近い時間だったと思います。当然、日中はテレビなど見ていないことになるので、前日の21日になるのかと思いますが、テレビでたまたま気になる特集を２つ見ました。

奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/2016年09月21日 - Twilog http://twilog.org/hirono_hideki/date-160921/asc

リツイート：hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）＞2016/09/21 09:02／2016/09/21 07:22＞ https://twitter.com/hirono_hideki/status/778383947113779200 ＞
 vivit_tbs （TBS 白熱ライブ ビビット）＞ https://twitter.com/vivit_tbs/status/778358778026614784 ＞
引用＞　 9/21(水)ビビットは･･･＜改行＞★台風でどうなった？豊洲新市場地下の水は？＜改行＞★中田敦彦のFOCUS　横浜ゴミ屋敷を徹底調査＜改行＞★千原ジュニアさん直撃！　結婚後の秘話語る＜改行＞★夫に対する不満ある？街角大調査！＜改行＞★福原愛選手結婚きょう会見･･･＜改行＞国分太一／真矢ミキ／テリー伊藤#tbs 

ツイート：hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）：2016/09/21 08:46： https://twitter.com/hirono_hideki/status/778379761299001344 ：
引用→　 中央市場は全国に６４あって、そのうち都内に１１あるという。テレビのモニーングショーという番組。人形供養もやっていた。

　見落としていたので時間は前後になりますが、上記のメモ的なリツイートとツイートをみると、モーニングショーという番組で人形供養の特集を見た後、別のチャンネルのビビットという番組で、横浜のゴミ屋敷の特集を見たことになりそうです。

　導入部分としての説明という序章の目的は果たしたので、以下は独立して細分化した項目として、記述を進めます。これまで同様、項目は一つに対応したブログの記事となります。

2016-09-23　金曜日　20：21　＜＜ ［［　←これまでの記述範囲の終了時刻］］＜＜
**** テレビの情報番組で取り上げられた、神社に奉納された人形供養のテーマパークにおけるアトラクション問題と、神社にまで持ち込んだという横浜市のゴミ屋敷の社会問題

:CATEGORIES: 名誉毀損の刑事告訴における具体的相談に先立ち、珠洲警察署に提出する準備書面
:TAGS: テレビ

2016-09-23　金曜日　20：54　＞＞ ［［　←これからの記述範囲の開始時刻］］＞＞

　21日の朝の情報番組で、先に見たのが人形供養の問題ですが、ネットで調べると次のような情報が見つかりました。一部引用することで、どういう問題なのかご紹介します。

／＊＊＊＊＊＊＊＊＊＊（引用開始）＊＊＊＊＊＊＊＊＊＊
引用URL＞＞＞＞：https://www.lmaga.jp/news/2016/09/15067/ 人形供養の神社から800体、USJの祟り | ニュース | Lmaga.jp

『Ｊホラー・エリア』は、無数に立ち並ぶ赤い鳥居を入り口に、寂れた村へと続くルートを歩く恐怖体験ゾーン。そしてこのエリアの先には、小学生以下立ち入り禁止の『祟 TATARI ～生き人形の呪い～』が待ち構えている。ここは、人形供養で有名な和歌山の「淡島神社」の協力で、供養された約600～800体の人形に囲まれるアトラクション。同神社の前田光穂宮司は、「人形は人に見てもらい、遊んでもらうために生まれてきており、多くの方々に遊んでもらうことは、人形たちにとっても良い供養になる」とコメントしているが、一歩足を踏み入れると自分が呪われるんじゃないかという恐怖に襲われる。

＊＊＊＊＊＊＊＊＊＊（引用終了）＊＊＊＊＊＊＊＊＊＊／

／＊＊＊＊＊＊＊＊＊＊（引用開始）＊＊＊＊＊＊＊＊＊＊
引用URL＞＞＞＞：http://www.j-cast.com/tv/2016/09/21278606.html USJホラー企画「祟」展示の人形にクレーム！お炊き上げで神社奉納したはずなのに･･･ : J-CASTテレビウォッチ

 50代の女性は子供のために30年大事にしてきた人形だったが、娘が家を出て置く場所もなくなり、人形供養で知られる和歌山市の淡嶋神社に奉納した。USJが今月10日（2016年9月）から始めた「祟」には、約500体の人形が「呪いの生き人形」として並べられた。協力したのが淡嶋神社だった。USJによると、「どんな企画か理解してもらった上で」人形の提供を受けたという。
子どもの成長願った人形をお化け屋敷に!?

   展示はどう説明しても「お化け屋敷」だったから、これは騒ぎになった。客たちは「リアルに怖かった。お勧めはします。怖いのも見たければどうぞ」「怖すぎて目が開けられなかった」「子供と一緒に行った。本当に生きたものが出てくるから、恐怖は結構ある」と楽しんでいる。
宇賀：ちょっとねえ

   奉納した女性は5000円の祈祷料を納めていた。「腹たちますよね。子供の成長を願って大切にしていた人形を、怖がらせるために使うなんて。言語道断」と怒る。

＊＊＊＊＊＊＊＊＊＊（引用終了）＊＊＊＊＊＊＊＊＊＊／

／＊＊＊＊＊＊＊＊＊＊（引用開始）＊＊＊＊＊＊＊＊＊＊
引用URL＞＞＞＞：http://blog.goo.ne.jp/y-hne/e/46ccd8c90b4d2069f96b9c499791f938 驚き　供養に出した人形が神社からユニバーサルスタジオへ呪いの人形に - アイリス　あいりす　

この神社の考えには、とても賛成できません。いままでの神社の考えとは別物のようです。これらが、無料で貸し出したにしろ、有料で貸し出したにしろ、供養をしてほしくて神社に人形を預けた人が、呪いの人形として、アトラクションに飾られているのをみたら、どう思うでしょうか？

これが、神社の本質かもしれませんね。本当に残念です。

ハロウィーンは、悪質な悪魔崇拝者が作ったお祭りです。

日本では最近大流行のようですが、これらも注意が必要だと思います。

＊＊＊＊＊＊＊＊＊＊（引用終了）＊＊＊＊＊＊＊＊＊＊／

　かなり前になるので、探しだすのにいくらか手間がかかると思いますが、見逃した次の番組があり、数日後にたまたまYouTubeにアップロードされていた動画として視聴できたという経緯がありました。かなり異例の経緯を辿ったと考えています。

ツイート：hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）：2016/07/22 00:21： https://twitter.com/hirono_hideki/status/756147191815737344 ：
引用→　 所さんのニッポンの出番!2時間SP【京都の魔界スポットで最強ご利益！】2016年7月19日160719 https://t.co/0gYGeSP23p

　あまり細かいところまで踏み込んで調べませんが、番組は上記のツイートにあるものでした。放送日が7月19日だったと考えられますが、4,5日後にたまたま検索で見つかったYouTubeの動画で視聴をすることができたと記憶しています。動画は既に削除されている可能性もあるかと思います。

　その前から私は、京都の八坂神社や牛頭天王、祇園信仰、蘇民将来について、告訴状において取り上げてきたと思いますが、元を辿ると平成3年の8月のお盆休み明けに、被害者安藤文さんが連休に友達と京都に観光に行ってきたと、被告訴人池田宏美の問いかけに答えるかたちで話していたことがあります。

　直接奪うことになったのは私自身の行為であり、懲役4年の実刑判決、服役となった傷害・準強姦被告事件ですが、平成3年の8月の3,4日と思われる短いお盆休みから一年も経たない間に、健康な体を失った被害者安藤文さんに対する思いが、ベースとして強くあります。

　過ちは過ちとして受け止めているつもりですが、その傷害・準強姦被告事件に至った経緯、その後の幇助犯として金沢地方検察庁に告訴済みの被告訴人の対応、所業は、現世における有様としても、地獄絵図さながらの理不尽さがあり、これを逆転させることが、報いの奉納であると位置づけています。

　取り上げたテレビの番組では、特集の切り出しとして「子どもの成長願った人形」というようなナレーションでの説明がありました。最近は高畑裕太氏の強姦致傷事件の続報を期待して、頻繁にテレビのチャンネルを変えるということがあって、そのおかげのタイミングで見ることができたとも考えています。

　高畑裕太氏の強姦致傷事件における大きな批判も集めた、母親高畑淳子氏謝罪会見を思いを致すと、「鬼子母神」という言葉が頭に浮かんでくるので、ネットで調べてみると次の情報が見つかりました、時間的な余裕もないので、今ページを読んだ範囲で、次の引用します。

／＊＊＊＊＊＊＊＊＊＊（引用開始）＊＊＊＊＊＊＊＊＊＊
引用URL＞＞＞＞：https://ja.wikipedia.org/wiki/%E9%AC%BC%E5%AD%90%E6%AF%8D%E7%A5%9E 鬼子母神 - Wikipedia

夜叉毘沙門天（クベーラ）の部下の武将八大夜叉大将（パーンチカ、散支夜叉、半支迦薬叉王[1]）の妻で、500人（一説には千人[2]または1万人[3]）の子の母であったが、それらの子を育てるだけの栄養をつけるために人間の子を捕えて食べてしまっていた。そのため多くの人間から恐れ憎まれていた。

それを見かねた釈迦は、彼女が最も愛していた末子のピンガラ[4]（嬪伽羅、氷迦羅、畢哩孕迦[1]）を乞食（こつじき）に用いる鉢に隠した。彼女は半狂乱となって世界中を７日間探し回ったが発見するには至らず、助けを求めて釈迦に縋ることとなる。

そこで釈迦は、「多くの子を持ちながら一人を失っただけでお前はそれだけ嘆き悲しんでいる。それなら、ただ一人の子を失う親の苦しみはいかほどであろうか。」と諭し、鬼子母神が教えを請うと、「戒を受け、人々をおびやかすのをやめなさい、そうすればすぐにピンガラに会えるだろう」と言った。彼女が承諾し、三宝に帰依すると、釈迦は隠していた子を戻した。そして五戒を守り、施食によって飢えを満た

＊＊＊＊＊＊＊＊＊＊（引用終了）＊＊＊＊＊＊＊＊＊＊／

　のちほど別の項目として取り上げる、母親の高畑淳子氏の対応は息子の長期間の実刑を避けるために性急すぎたと思えるとともに、依頼者の最大限の利益を図るという弁護士らの言い古された主張の根拠に、大きな疑問を投げかける推移、当座の結果のみという杜撰すぎると思われる成り行きとなりました。

　子どもでの特に娘の健やかな成長を願い、神社に詣でる気持ちは、7月の告訴状において、大地主神社の「チャンペ饅頭」としてご紹介したと思いますし、そのきっかけとなったのが能登の輪島市が舞台となった連続テレビ小説まれ、で、ムードメーカーとなった高畑裕太氏の存在感も大きかったと思います。

　どういうわけか、高畑裕太氏の強姦致傷事件の報道をNHKのニュース番組では、何事も無いように一度も見たことがなく、この先事件がどう転ぶかにかかわらず、ずっと引っかかりがあるというのが、正直なところです。単なる切り捨てとも見えるのは、残念ことであり、ずっと気がかりになっています。

　ネット上の意見のようなコメントには、連続テレビ小説まれ、もこれでお蔵入りか、というものがあり、ドラマのために輪島市民が総出で輪島大祭の再現を影響力の大きさも真剣に考えさせられる事態でした。協力された他の関係者の利益を守るためのNHKの沈黙、というのも同時に考えはしました。

　そのようなことを含めたうえでも、高畑裕太氏の強姦致傷事件に対するモトケンこと矢部善朗弁護士（京都弁護士会）の反応には実に腹立たしいものがありましたし、同時期における小倉秀夫弁護士のツイートにも無神経以上の便乗性のようなものを感じている昨今です。

　小倉秀夫弁護士のツイートは、彼のタイムラインにおいて余り見てはいないのですが、ここ数日の間に、看過しがたいものをいくつか現認しています。

　東京の小倉秀夫弁護士は、京都のモトケンこと矢部善朗弁護士（京都弁護士会）に負けないぐらいのお祭り弁護士だと認めていますし、同じように処理、処罰をすることで社会防衛や多くの人が神社に願うようなご利益に資するような社会的効果を得るに相応しい好機だと捉えています。

　モトケンこと矢部善朗弁護士（京都弁護士会）と小倉秀夫弁護士は、東京と京都ぐらい性格的な違いもあると考えますが、どちらも有害過ぎる存在であって社会汚染の除去装置として処理することが必要だと考えています。直接こそかないませんが、深澤諭史弁護士もそれに近いと位置づけています。

　テレビの報道では、供養のための人形を、神社に奉納するという表現にもいくらか違和感を感じたのですが、一方通行の報道と思える一面もあるので、たまたま見た報道のご紹介というのが、あまり理解のできていないこの件の私の事実認識になります。

　次に横浜のゴミ屋敷の問題になりますが、21日の朝に見た情報番組の映像は、これまで度々テレビで見てきたゴミ屋敷の問題とは、遥かに程度の違いを感じさせる一回りスケールの大きなものでした。

　番組で取り上げられていたのは横浜の２つのゴミ屋敷の実状で、初めに見た方がゴミの問題としては深刻にも思えたのですが、次の確か金沢区のゴミ屋敷では、隣接する神社にまで主に本というゴミの集積で、神社が閉鎖になるという、想像にも及ばなかった問題の特異性がありました。

　21日の番組でも同じような映像の場面がありましたがTwitterの検索を見ていると、住民が神社でゴミの片付けをしているさなかにゴミを神社に持ち込んだ本人がカッターで豆腐を食べていたという指摘があって、ピンと来なかったのですが、今朝見た番組の場面ではカッターナイフとわかりました。

　21日の朝の情報番組では、何か隣のインド人や世話役のような立場など2,3人が顔出しでインタビューに応じていましたが、迷惑が深刻すぎると思える割に、包み込む笑顔のような対応も感じられて、これまでのゴミ屋敷の報道とはとはずいぶん違う印象を受けました。

　横浜市のゴミ屋敷の問題における条例が可決されたような報道も同時にあって、そこには精神的な疾患の問題を受け入れるような内容が盛り込まれていて、未来志向の対応のようなものを連続テレビ小説まれ、で能登の輪島と同じく舞台となった横浜市で感じました。

　横浜市や神奈川県というのは、「参考資料扱いにした過去の告訴状の下書き」でご紹介してきた、うの字というアカウントのこともあって、弁護士業界における汚染、ゴミの堆積場のような印象もあって、さらに刑事弁護のイメージを悪化させる大きな事件もいくつかあったので一層際立って感じられました。

　時間の使い方に限界もあるので、余り見ていないうの字のTwitterのタイムラインですが、そのうの字のツイートというのは、鹿児島大学で准教授から教授になったと最近になって知った坂本正幸弁護士のTwitterのタイムラインにおいて、リツイートとして見る機会が多く感じています。

　鹿児島大学のことは、平成15年の察羽咋警察署の対応とセットで本書で書いておかなければならないと予定していますが、本人訴訟などしているのは基本ブロックとまでツイートしていた坂本正幸弁護士についても、時間と紙面が許せば出来る限りのことを書いておきたい弁護士、法律家業界の問題児てす。

　ゴミ屋敷のことは精神疾患の問題として報道される傾向が強くなっていると感じますが、うの字や坂本正幸弁護士、深澤諭史弁護士にもそれに近い、精神疾患や感応性精神病の徴候があって、汚物のようなツイートを社会に垂れ流し、弁護士汚染の除去装置の必要性をかなり前から感じさせてくれています。

　記述するのは初めてになるかと思いますが半月から前の段階で、私の頭には「弁護士墓場の運動会」という言葉が去来し、騒々しく踊り続けておりますが、深澤諭史弁護士だけでなく、昨夜のモトケンこと矢部善朗弁護士（京都弁護士会）と小倉秀夫弁護士の一連のツイートは想像を絶するものがありました。

　たまたま隣接していただけなのかもしれないですが、神社の境内にゴミを持込み閉鎖という事態にまで至らせたというテレビのゴミ屋敷も問題も、想像を絶するとともに、深澤諭史弁護士ら気ままなツイートを見るにつけ、ゴミを神社に持ち込んだ人物が背負った人生の方が正当性があるようにも思えました。

　先日終わった能登町小木の袖ギリコの秋祭りは、かなり強い雨の中、宮上げがあったとネットのツイートでみていましたが、昨日小木港にアジ釣りに行って聞いた話では、翌日神輿は出さなかったと聞きました。話には聞いていましたが、袖ギリコの宮上げを見たのは、昨年の2015年が初めてでした。

　宮、という言葉を意識するようになったのは、その小木港の秋祭りの宮上げと、同じく昨年に初めて見に行った輪島大祭のキリコにのナカフクの上に、奥津宮、重蔵宮、住吉宮、天満宮という文字を見たのがきっかけで、ネットで調べると神主と宮司の違いについて知ることもありました。

　今年になって、宇出津のあばれ祭りの小棚木と音羽町のキリコのナカフクの文字が「蘇家宮」と読むと初めて知ったのですが、蘇民将来の信仰だということはわかったものの、神社を意味するとも思われる宮という文字が家とともに含まれていることは、届かない歴史に思いを馳せるところがありました。

　「届かない歴史」ということに、記録という必要性を強く感じ、昨年、日本遺産に認定された能登のキリコ祭りに関連したホームページで、「記録作成等の措置を講ずべき」という文言を見て、その歴史的価値と必要性を更に強く意識するようになり、今できる範囲で記録の保存を徹底するようになりました。

　小木港での袖ギリコという秋祭りでは、危険なので雨になると宮上げは行わないと聞いていたのですが、家にいてずいぶんな土砂降りと思いながら、お祭り自体の中止の可能性も考えていたのに、晴れていても困難を伴う宮上げが実行されたと聞き、励みにもなりました。

　昨日は、小木港の東一文字堤防でアジ釣りとアオリイカ釣りをやって、夕方には土砂降りの雨に見舞われることにもなりましたが、期待以上の型は揃ったアジの釣果で、これまでになく夜明けの薄暗い状況で全くあたりがなかっただけに、神という超在する力の働きを感じるところがありました。

　「参考資料扱いにした過去の告訴状の下書き」に何度か書いてきたと思いますが、3月の終わり頃に小木港の隣の九十九湾で、37センチのアジを手で捕まえた出来事が、超在した神のような存在を意識するきっかけになりました。

　食べて美味しくないと感じた大きなアジもそれが初めてでしたが、寿命として身を捧げてくれたとも思える大きなアジでした。

　宇出津のあばれ祭りの神輿を宮入りさせる前の、八坂神社境内での松明でも、置き松明の周りを神輿が何度も周りますが、そのアジも同じぐらいの大きさの円を何度もえがいてから、岩の裂け目の浅瀬に飛び込み、出て捕まえることが出来たのです。

　一匹の大きなアジがなぜそのような行動をしたのか不思議でしかありません。本来アジは回遊魚で集団で行動するとも言われています。それに近く、不思議に思えたのが、昨日小木港から家に戻った後に見た、モトケンこと矢部善朗弁護士（京都弁護士会）と小倉秀夫弁護士のツイートの内容でした。

　一言で言えば、どちらも人や世の中、社会を軽視し舐め腐ったとしか考えようもない、モトケンこと矢部善朗弁護士（京都弁護士会）と小倉秀夫弁護士のツイートの内容でした。大きなアジと同じく犠牲として神に魅入られ、狂わされているのかと思える言動でした。

　ともあれ、法律家であることに異常過ぎる自負心やプライドの慢心を持つ、モトケンこと矢部善朗弁護士（京都弁護士会）や小倉秀夫弁護士が、おとなしくお供え物になってくれたとは、考えられないことですし、その挑戦的姿勢こそが法律家としての完全破滅に向かわせるべき道理であると考えております。

　能登半島の漁業には定置網漁があって、宇出津では大敷網とも呼ばれていますが、小木港と姫は海底の地形が港から近いところから深くなりすぎていて定置網漁が出来ず、それで遠洋漁業が発達したとも聞いています。

　定置網漁がどんなものか私はやったこともないのでよくわかっていないのですが、それを参考にしてエサとして仕込んでおいたのが、次の固定にもしておいたツイートになります。

ツイート：hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）：2016/09/21 17:52： https://twitter.com/hirono_hideki/status/778517231927906304 ：
引用→　 .@Hideo_Ogura 本日、小倉秀夫弁護士とモトケンこと矢部善朗弁護士（京都弁護士会）@motoken_twを法律家として完全成仏、弁護士妖怪の退治とすべく、珠洲警察署に電話連絡をして、近日中に書面を提出する旨、お伝えしました。被害者の立場としてマスコミにもばらまくとお伝え

　化け物や極めてたちが悪い妖怪性が、モトケンこと矢部善朗弁護士（京都弁護士会）と小倉秀夫弁護士の異常性に認められ、それに追従しているとも思われる害悪性、汚物性であることを子孫の将来を慮る上でも、深刻な事態として考えさせるのが、深澤諭史弁護士の発言であり、ツイートです。

　時刻は9月24日の10時44分になっています。昨夜はゴミ屋敷のことで、書いておこうか迷うことがありました。それを書いておこうと思います。

　無関係ですが、今テレビで「一代で年商20億円の中卒社長」というのをやっていますが、その職業が足場組み立ての鳶職というのは驚きました。職業の紹介より前に、4千万円というロールスロイスが紹介されていました。

　鳶職人の稼ぎ頭が最高で月収230万円というのも驚きましたが、何か技術的に特別な工法を編み出したのかと思いきや、終身雇用制を取り入れたことで、優秀な職人が集まり好循環を生み出した、とのことでした。

　中卒、高卒の職人のほとんどが年収一千万近く、とのことで、弁護士業界との比較の上でもいろいろと考えさせられる話です。

　本題に戻ります。ゴミ屋敷のことで書くことを予定していたのは、2005年の12月に始めた次のブログのことです。

日暮れて途遠し http://d.hatena.ne.jp/hirono_hideki/

　通常のブログサービスとは違った特徴のあるブログで、その名前も「はてなダイヤリー」となっていて、日記風のスタイルとなっています。機能的に便利な面と不便な面もあるのですが、過去のデータを探るには、他にはない便利さがあります。

　ページのサイドバーにカレンダーがあって、現在の2016/09という年月がリンクになっていて、そのリンクを開くとURLが次のページに移動します。

記事一覧 - 日暮れて途遠し http://d.hatena.ne.jp/hirono_hideki/archive/201609

　このページではトップにカテゴリの一覧と年月日の一覧がリンクで表示されます。他のブログサービスでは出来ないようにも思いますが、このはてなダイヤリーのサービスでは、過去や未来の日付を指定して投稿することも出来ます。

　他に見たことはないですが、実際、落合洋司弁護士（東京弁護士会）は次のような日付でエントリーを投稿しています。常にページのトップに表示させるのが目的なのだろうと思います。

刑事事件全般に対応しつつ他の事件も積極的に手がける元検事です - 弁護士 落合洋司　（東京弁護士会）　の 日々是好日 http://d.hatena.ne.jp/yjochi/20640331

　URLをみればわかると思いますが、2064年3月31日という日付として上記のエントリーは投稿されています。

　はてな記法などの独自のルールも含め柔軟性が高いのも、はてなダイヤリーの特徴なのですが、以前、不用意な操作を外部のプログラムから行ったため、ざっと見たところ過去のエントリーの3分の1から4分の１ぐらいが、文字化けを起こしてしましました。

　EUC-JPというずいぶん古い文字コードを使っているのが要因ですが、他にも文字コードのからみで問題を起こす可能性があり、取り扱いに注意を要するところで、これも他のブログサービスではないことだと思います。

　同じ「はてな」という会社のサービスで、数年前に「はてなのブログ」という別のブログサービスが出来ているので、はてなダイヤリーの利用者を見かけることも少なくなっていますが、便利な反面、ずいぶんクセの強いもので、過去の手痛い経験をしたことも何度かありました。

　はてなダイヤリーを始めた時期を確認するため、記事の一覧ページを開いたところ、気になるタイトルのエントリーを見つけたので、ページを開いたところ、すっかり忘れていたことがいくつか書いてありました。

／＊＊＊＊＊＊＊＊＊＊（引用開始）＊＊＊＊＊＊＊＊＊＊
引用URL＞＞＞＞：http://d.hatena.ne.jp/hirono_hideki/20051223 *1135339280*警察署に相談に行ってきました。（２００５年１２月２３ - 日暮れて途遠し

一年でもっとも楽しい時期とも言えるクリスマスに、このような暗い話題を読んで頂くことには、私自身ためらいがあることを最初にお断りさせて頂きます。

　１２月２１日、長野智子blog（http://yaplog.jp/nagano/archive/132#ct）の方で、コメント投稿を繰り返し、一部の方からご意見や、ご指摘を頂きました。

　私に対する提言として、次のようなコメントを頂きました。

最後に廣野秀樹さんへの提言としては、

（もちろんここへの書き込みではなく自分のブログ・HPで）

長文で一度に説明(相手が理解できるよう)が難しいことはいくつかに分ける

・ブログやHPで述べたいテーマ・動機（何故に子供の写真を使っているのか等も）

・あなたが逮捕された事件の内容(簡潔に)

・裁判の経緯(要約し、あなたの意見は書き込まない)

・服役に至った経緯（同上）

・警察、検察、弁護士、裁判所、原告側等の行動

・特に意味のない前置きは使用を控え、全般に関してのあなたの見解・現在の経緯

これだけでもあなたの言いたいことに耳を傾けてくれる人が増えると思いますよ。

　このご提言に出来るだけ沿うかたちで、ご説明をしたいところですが、まずは現状について書いておきたいと思います。まず、１２月２０日火曜日の午前中に、金沢地方検察庁の方に電話をしました。これまで担当であったハラさんは不在で、もう一人の担当者と聞いていたミヤジマさんをお願いしました。

　そして、今度の告発状は警察の方に、相談の上、提出すると伝えました。かまわないという簡潔な返事でしたが、どのような判断をするかはわからないとも言っていました。

＊＊＊＊＊＊＊＊＊＊（引用終了）＊＊＊＊＊＊＊＊＊＊／

　余りに長いので３分の１ほど残して読むのをやめましたが、金沢地方検察庁の担当者の名前など、すっかり忘れていたことが書いてありました。長野智子さんのブログのコメント欄でアドバイスを受けたことが、引用として書いてありますが、そのコメント欄の状況は思い出すことができません。

びっくり - 長野智子blog http://yaplog.jp/nagano/archive/132#ct

　リンク切れと思ったものの、そうはなっておらず、昔見たのと同じようにページが表示されましたが、コメント欄は表示されず、そう言えば、ブログを見るようになって半年もするかしないうちにコメント欄が閉鎖されていたかもしれないと、思い出しましたが、それもあやふやな記憶になっています。

　寄り道になりますが、気になることが書いてあったので、一部引用でご紹介をしておきたいと思います。当時の検察、司法をとりまく世相の一面を垣間見るものです。

／＊＊＊＊＊＊＊＊＊＊（引用開始）＊＊＊＊＊＊＊＊＊＊
引用URL＞＞＞＞：http://yaplog.jp/nagano/archive/132#ct びっくり - 長野智子blog

昨日一日で、３万アクセス

びっくりしました。

たくさんのコメントもありがとう。

犯行日当日、合計４５ミリの雨だったにも関らず、少女が「衣服が濡れていなかった」と証言している矛盾などに全く触れていない判決理由など、あまりにも疑問の残る裁判は、今後、東京高裁に舞台を移します。

それにしても。。。。

客観的証拠も「口裏あわせ」として、一切無視する御殿場署。

自らの捜査ミスを隠すために、平気で真実をゆがめてしまう姫路署。

そして、一体となって真実隠しをしようとする検察、司法。

北海道警の捜査報償費の裏金流用問題を取材したときなど、本当に誠実で一生懸命がんばっている、現場の警察官の告発に触れたけど。。。。

だから、一握り、いや十握り、１００握りの、一部の警察官のひどい行動が許せないっす。

実はトラバのスパムがあまりにもひどくて、いくつかの対応をしたのだけど効果がなく大弱り。

しばらくトラバをお休みしたら、とのアドバイスで休止してたのだけど、昨日番組で取り上げた姫路の２女性殺人事件、御殿場事件について、他のブロガーの方も情報交換してほしい思い高まり、トラバ復活。


＊＊＊＊＊＊＊＊＊＊（引用終了）＊＊＊＊＊＊＊＊＊＊／

　記事のタイトル名の短さも、びっくりですが、当時は有名人のブログというのも多くはなかったので、関心のある人の貴重な情報源として、「びっくり」というだけの意味不明のタイトルでも、固定客のような特定層からもアクセスは多かったのだろうと思います。

　自分のはてなダイヤリーの話に戻しますが、コメント欄で、情報量が多すぎる上まとまりがないので、まるでゴミ屋敷だと指摘されたことがありました。

　過去のエントリーを読めば思い出すことも沢山あると思いますが、読むのも時間がかかるし、書いておきたい衝動にも駆られて、とりとめがなくなりそうなので、公開設定に戻してからも、はてなダイヤリーのエントリーはわずかにしか読んではいません。

　時刻は9月26日10時43分になっています。いろいろと考えることが多く、それもまとまらず、しばらく中断をしていました。すでにいくつか必ず取り上げておきたいことは決まっています。
**** 2016年17時52分付、モトケンこと矢部善朗弁護士（京都弁護士会）と小倉秀夫弁護士に向けた具体的告訴手続きに関する固定ツイート、その反応

:CATEGORIES: 名誉毀損の刑事告訴における具体的相談に先立ち、珠洲警察署に提出する準備書面
:TAGS: モトケンこと矢部善朗弁護士（京都弁護士会）,小倉秀夫弁護士

2016-09-26　月曜日　10：49　＞＞ ［［　←これからの記述範囲の開始時刻］］＞＞

ツイート：hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）：2016/09/21 17:52： https://twitter.com/hirono_hideki/status/778517231927906304 ：
引用→　 .@Hideo_Ogura 本日、小倉秀夫弁護士とモトケンこと矢部善朗弁護士（京都弁護士会）@motoken_twを法律家として完全成仏、弁護士妖怪の退治とすべく、珠洲警察署に電話連絡をして、近日中に書面を提出する旨、お伝えしました。被害者の立場としてマスコミにもばらまくとお伝え

　直近の確認はしていませんが、モトケンこと矢部善朗弁護士（京都弁護士会）には私の3つのTwitterアカウントのすべてをブロックされているので、上記のツイートも彼の目には触れていない可能性があり、既読であることを確認する術もありません。

　同じく名誉毀損で刑事告訴の手続きを進める小倉秀夫弁護士は、どのアカウントもブロックはしていないはずですが、だいぶん前になりますが、＠など通知が入ることを迷惑がるツイートを寄越してきていたので、ミュートなどをしていて、同じく目に触れていない可能性は否定できません。

　私は彼らの反応を見るために、ことさら刺激的な内容のツイートを行い、タイムラインに固定したのですが、確かな関連性は確認できないものの、私の存在や行動を意識したのではと考えられるツイートがあり、そうではなくても、余りに私の立場を無視した気ままで挑戦的なものと考えます。

　小倉秀夫弁護士のツイートには、告訴や告発に触れたものもあったと思いますが、正確な日時なども記憶にはとどめることが出来ないので、経過の記録として、ポイントを押さえておきたいと思います。

2016-09-26　月曜日　11：03　＜＜ ［［　←これまでの記述範囲の終了時刻］］＜＜
**** 名誉毀損の刑事告訴の手続きを具体的に告知した 2016年17時52分付ツイート、と前後した小倉秀夫弁護士のツイートの流れ

:CATEGORIES: 名誉毀損の刑事告訴における具体的相談に先立ち、珠洲警察署に提出する準備書面
:TAGS: 小倉秀夫弁護士

2016-09-26　月曜日　11：08　＞＞ ［［　←これからの記述範囲の開始時刻］］＞＞

　小倉秀夫弁護士の場合、未だにTwilogの登録がないので、過去のツイートを探しだすのはやっかいがともないますが、Twitterの通常のサービスにおける検索でも、効率的ではなく、漏れが出る可能性は経験的に高まるものの、ある程度のことはできます。

from:Hideo_Ogura since:2016-09-21 until:2016-09-22 - Twitter検索 https://twitter.com/search?q=from%3AHideo_Ogura%20since%3A2016-09-21%20until%3A2016-09-22&src=typd

　上記はTwitterの高度な検索とも呼ばれるサービスを利用したものですが、確認するとなぜか、結果のツイートが時間の順序で並んでいません。また、ログインしたアカウントの設定で日本時刻の確認をしないと、16時間遅れの米国時間として各ツイートの時刻が表示されるかと思います。

twitter 時刻 おかしい - Google 検索 https://www.google.co.jp/?gws_rd=ssl#q=twitter+%E6%99%82%E5%88%BB+%E3%81%8A%E3%81%8B%E3%81%97%E3%81%84

　この問題と対処法は、上記の検索方法で調べることができると思います。

投稿者：s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2016-09-26 11:23  ツイート： https://twitter.com/s_hirono/status/780231361395171329
2016-09-26-112341_小倉秀夫（@Hideo_Ogura）　-　Twilog.jpg https://t.co/OfWEk99tVV

　上記のスクリーンショットにあるように、小倉秀夫弁護士のツイートの頻度は比較的低調であったため、現時点では9月20日まで未登録のままTwilogで遡ることができる状態です。

　それでは小倉秀夫弁護士のTwilogのページを利用して、次に主なツイートをピックアップします。

ツイート：Hideo_Ogura（小倉秀夫）：2016/09/21 14:21： https://twitter.com/Hideo_Ogura/status/778464174821158912 ：
引用→　 高橋宏志先生と貧乏ロースクール生とが入れ替わる「君の名は─成仏編」を作ったら、受けるのではなかろうか。

ツイート：Hideo_Ogura（小倉秀夫）：2016/09/21 19:45： https://twitter.com/Hideo_Ogura/status/778545613352730624 ：
引用→　 この調子なら、他人の食器に尿をぶっかけておきながら、「尿をかけられた後に洗剤で洗った食器に盛られた食べ物を食べるとどんな問題が生ずるというのだ。文献を出せ」とか言ってくる人が出る可能性があるね。ほりぐち説だと、その程度では器物損壊にならないことになりそうな。

ツイート：Hideo_Ogura（小倉秀夫）：2016/09/21 21:49： https://twitter.com/Hideo_Ogura/status/778576792839860225 ：
引用→　 スマイリーキクチが綾瀬コンクリート詰め殺人事件の犯人と考えたテレビの人はいなかったが、ネット上では層でもなかった。RT @tomoakisas: いまだに「ネット上」という言葉を、あたかも架空の世界のように話すコメンテーターとかがいますが、それは大きな勘違いで、テレビよりリテラシ

ツイート：Hideo_Ogura（小倉秀夫）：2016/09/22 10:15： https://twitter.com/Hideo_Ogura/status/778764642688507904 ：
引用→　 私も、レッテル張りするまえに、著作権法コンメンタールくらい買って読めと思いますね。RT @kankimura: しかも彼、自分の著作を全く読まずに「ネットの評判」だけでそういったんだよねぇ（←後日確認した）。

ツイート：Hideo_Ogura（小倉秀夫）：2016/09/22 14:58： https://twitter.com/Hideo_Ogura/status/778835758375440384 ：
引用→　 池田さんも八幡さんも、自分では刑事告発しないのがミソですね。

ツイート：Hideo_Ogura（小倉秀夫）：2016/09/23 00:20： https://twitter.com/Hideo_Ogura/status/778977265774239748 ：
引用→　 SNSで得た不確かな知識でもって特定人を刑事告発してしまう人たちには一定の責任をとらせるべきではないかというキモするんだよね。そんないい加減な告発への対処で捜査機関が時間を取られて、真面目な刑事告訴・告発が後回しにされるのはかなわない。

ツイート：Hideo_Ogura（小倉秀夫）：2016/09/23 00:22： https://twitter.com/Hideo_Ogura/status/778977743706861568 ：
引用→　 刑事告発って、刑事告発したということをSNSで告白して、被告発者を憎む人たちどうして気勢を上げるための制度ではないからなあ。

ツイート：Hideo_Ogura（小倉秀夫）：2016/09/23 00:28： https://twitter.com/Hideo_Ogura/status/778979181174534144 ：
引用→　 弁護士って、基本的に予約制でクライアントと会うので、「行列ができる」というのは、事務処理が無茶苦茶遅くて。前の時間に処理すべき事を捌ききれずに、打ち合わせの予定が玉突き状態になっているとしか考えにくい。

ツイート：Hideo_Ogura（小倉秀夫）：2016/09/23 11:55： https://twitter.com/Hideo_Ogura/status/779152093965713408 ：
引用→　 日本の若者が無駄に戦死しないで済むように安保法に反対するとか、普通に愛国的だと思いますけどね。

ツイート：Hideo_Ogura（小倉秀夫）：2016/09/23 16:43： https://twitter.com/Hideo_Ogura/status/779224561774497796 ：
引用→　 他にやりようがあったかと言われると、そろそろ日本人から戦死者を出して感動したいという世論に立ち向かうすべもなかったようには思いますね。RT @massa27: ただ、現政権をまるで支持してないわしの目からみても、安保法制に対するああいう反対の仕方は戦略ミスに思え、

ツイート：Hideo_Ogura（小倉秀夫）：2016/09/23 17:04： https://twitter.com/Hideo_Ogura/status/779230016030674944 ：
引用→　 まずは、蓮舫代表が各新聞社の社長をお食事に招待するところからですね。RT @massa27: @Hideo_Ogura それにしても自民以外のメディア戦略、なんとかならんのですかね。ちゃんとしたPR戦略があるとは到底思えんのですよ。

ツイート：Hideo_Ogura（小倉秀夫）：2016/09/24 10:32： https://twitter.com/Hideo_Ogura/status/779493744475197441 ：
引用→　 宇奈月温泉と聞いて「権利濫用」都しか連想できない人たち。RT @lawkus: 志布志の特産品は冤罪で和歌山の特産品はカレーという乱暴な認識。

ツイート：Hideo_Ogura（小倉秀夫）：2016/09/24 11:31： https://twitter.com/Hideo_Ogura/status/779508462992535552 ：
引用→　 ネトウヨさんたちはいい加減自分たちこそがもっとも自国の対外的評価を貶めていることに気付けば良いのに。

ツイート：Hideo_Ogura（小倉秀夫）：2016/09/25 08:24： https://twitter.com/Hideo_Ogura/status/779823898145779712 ：
引用→　 SNSや右派論壇で目立つのは、「反・反権力こそカッコいい。大衆はみんなダマされている」と考えている人たちですね。「翼賛クール」とでも言いましょうか。RT @sasakitoshinao: 「反権力こそカッコいい、大衆はみんなダマされてる」と考えてる人たちの心象を「反逆クール」って

ツイート：Hideo_Ogura（小倉秀夫）：2016/09/25 08:49： https://twitter.com/Hideo_Ogura/status/779830217187561472 ：
引用→　 名誉毀損された側が真実性のないことを立証しなければいけないという寺澤さんの夢の世界をいち早く体現しているのが、アゴラだなあ。「俺様の推論が外れているのなら証拠を出せ」という論理だよね。蓮舫につきつけているのは。真っ当なメディアだと、裏取りしてから記事にするんだけど。

ツイート：Hideo_Ogura（小倉秀夫）：2016/09/25 10:53： https://twitter.com/Hideo_Ogura/status/779861238968819712 ：
引用→　 デタラメを書いて欲しくなければジャーナリストにお金をお支払いしないといけない時代の到来ですね。RT @Yu_TERASAWA: 『法学セミナー』１０月号のスラップ訴訟特集を読みましたか。弁護士が高額の名誉毀損訴訟を連発して高額の着手金を稼ぎまくるという小倉さんの夢の世界もそろそ

ツイート：Hideo_Ogura（小倉秀夫）：2016/09/25 11:00： https://twitter.com/Hideo_Ogura/status/779863015977910273 ：
引用→　 デタラメな記事を書かれて倒産に追い込まれたくはない企業のために、ジャーナリスト様にその企業の売上の何パーセントかをお配りする仕事はちょっと。RT @Yu_TERASAWA: 小倉さん @Hideo_Ogura は優秀な弁護士だから、スラップ訴訟で稼ぐ道が絶たれても、

ツイート：Hideo_Ogura（小倉秀夫）：2016/09/25 11:09： https://twitter.com/Hideo_Ogura/status/779865332890505216 ：
引用→　 あんなもの誰も信用するはずないということで負けるとは思いませんでした。RT @Yu_TERASAWA: てゆうか、小倉さん、ふつうに名誉毀損訴訟の原告の代理人を務めて敗訴するお仕事をされていますよね。

ツイート：Hideo_Ogura（小倉秀夫）：2016/09/25 11:31： https://twitter.com/Hideo_Ogura/status/779870963051601920 ：
引用→　 ですから、「スラップ訴訟」が禁止されると、ジャーナリストたちは何でもありのジャーナリスト天国がやってくるのだろうと思っているわけですよ。RT @Yu_TERASAWA: でも、その訴訟が「スラップ訴訟」と評されていることはご存じですよね。

ツイート：Hideo_Ogura（小倉秀夫）：2016/09/25 11:53： https://twitter.com/Hideo_Ogura/status/779876470852165632 ：
引用→　 ジャーナリスト様がデタラメな内容を書き立てることには目をつぶれと。RT @Yu_TERASAWA: 小倉さんは優秀な弁護士なんですから、スラップ訴訟以外の道で稼がれるよう強く推奨します。

ツイート：Hideo_Ogura（小倉秀夫）：2016/09/25 11:56： https://twitter.com/Hideo_Ogura/status/779877205316775936 ：
引用→　 「御社について今度こんな記事を書くことを予定しています」というメールを送ると、デマ記事に営業妨害されたくない企業が「あなたの口座番号を教えてください。○○円振り込んでおきますので、その記事を掲載するのだけは勘弁を」と言ってくる社会になれば、ジャーナリストの天国ですね。

ツイート：Hideo_Ogura（小倉秀夫）：2016/09/25 11:59： https://twitter.com/Hideo_Ogura/status/779877934026805248 ：
引用→　 デマ記事による営業妨害を防ぐために、ジャーナリストを裁判で訴えるのではなく、ジャーナリスト様にお金をお支払いして記事の掲載をおやめいただく社会が到来するのですね。RT @Yu_TERASAWA: スラッパー（スラップ訴訟を起こす原告や代理人）たちが何でもありのスラッパー天国は近々

ツイート：Hideo_Ogura（小倉秀夫）：2016/09/25 12:04： https://twitter.com/Hideo_Ogura/status/779879203940413440 ：
引用→　 ジャーナリスト様が仕掛けるデマに対処するのは正当な仕事ではないんですね。「デマには、訴訟ではなく、付け届けで対処するべき」と言うことなのですね。RT @Yu_TERASAWA: 正当な仕事で適正な対価を得るべきです。

ツイート：Hideo_Ogura（小倉秀夫）：2016/09/25 12:06： https://twitter.com/Hideo_Ogura/status/779879757789827072 ：
引用→　 今後、「今度こんな記事書くことにしたけどいいたいことあるなら聞くよ」というメールを送られた企業の中の人から相談を受けたら、「ジャーナリスト様相手に名誉毀損訴訟なんてとんでもない。『おいくらお支払いすればよろしいでしょうか』という返事を送るのだ」とアドバイスするのが正しいと。

ツイート：Hideo_Ogura（小倉秀夫）：2016/09/25 12:07： https://twitter.com/Hideo_Ogura/status/779879855466827776 ：
引用→　 これが本音ですかね。RT @Yu_TERASAWA: 弁護士にお金をお支払いするより、ジャーナリストに金を払ったほうが安そうですね（笑）。 RT @Hideo_Ogura デマ記事による営業妨害を防ぐために、ジャーナリストを裁判で訴えるのではなく、ジャーナリスト様にお金をお支払い

ツイート：Hideo_Ogura（小倉秀夫）：2016/09/25 12:08： https://twitter.com/Hideo_Ogura/status/779880216378298369 ：
引用→　 現状でどんな被害が生ずるというのか文献をもって示せみたいなことを言う（偽）弁護士もいますしね。RT @noiehoie: 「豊洲でヒ素が出たことに騒いどる連中は何がしたいんだ」ってそりゃ「ガバナンスの不在」を指摘したいに決まってるじゃないですか。

　小倉秀夫弁護士のツイートの引用は、これくらいにしておきますが、最近になって、小倉秀夫弁護士らしさが戻ってきたと感じられるところです。

　小倉秀夫弁護士のモトケンこと矢部善朗弁護士（京都弁護士会）との共通点ですが、独善的な理屈をこねた気ままな振る舞いであり、常識外のところから社会の各部や全体を狂わせる危険性を強く危惧します。

　小倉秀夫弁護士のツイートは、本件告訴事件と自治体との関わりとしても参考にしていただきたいところが大きく、石川県警察の役割と責任を事案に即し具体的に考えて頂く上で小倉秀夫弁護士の刑事処罰の必要性も常に念頭において、警察の信頼を含めた全体の利益を考えて下さい。

　ここでは見なかったように思いますが、小倉秀夫弁護士は弁護士の優位性、優秀性を強調するのみで、その反射的効果として、警察や検察の実際の業務というものを軽く扱いすぎていると指摘しておかなければなりません。

　上記に掲載してご紹介した9月21日以降の小倉秀夫弁護士のツイートをつらつらと読むにつけ、「えん罪」もしくは「冤罪」というキーワードでの小倉秀夫弁護士のツイートを次のブログ記事としてまとめました。

参考資料：「えん罪」をキーワードに含む「小倉秀夫弁護士（@Hideo_Ogura）」のツイート・リツイート（2010-11-18 09:07〜2016-08-02 13:05）「10」件,http://hirono2016k.blogspot.com/2016/09/hideoogura2010-11-18-09072016-08-02.html
参考資料：「冤罪」をキーワードに含む「小倉秀夫弁護士（@Hideo_Ogura）」のツイート・リツイート（2010-01-18 22:44〜2016-09-24 10:32）「1-100／142」件,http://hirono2016k.blogspot.com/2016/09/hideoogura2010-01-18-22442016-09-24.html
参考資料：「冤罪」をキーワードに含む「小倉秀夫弁護士（@Hideo_Ogura）」のツイート・リツイート（2010-01-18 22:44〜2016-09-24 10:32）「101-142／142」件,http://hirono2016k.blogspot.com/2016/09/hideoogura2010-01-18-22442016-09-24_25.html

　また、小倉秀夫弁護士が次のツイートをやっていました。いつまでも変わらない刑事司法、刑事裁判に対する見方をわかりやすく示していますが、そこに含まれる「遺族」などのキーワードで考えれば、黙ってはおれませんし、にわかに取り繕った印象操作には強い危機感を抱きます。

ツイート：Hideo_Ogura（小倉秀夫）：2016/09/26 11:17： https://twitter.com/Hideo_Ogura/status/780229862443409408 ：
引用→　 被害者の遺族がすっきりすることを重視すれば、こいつが真犯人であるとして検察官が起訴をした被告人は、たとえ無実であろうとも死刑に処するのが、被害者の人権に配慮した私法だという考え方もあるのでしょうね。RT @gotainmino: @Hideo_Ogura ：キミも提出賛成？

　冤罪をキーワードにしたまとめの記事からいくつかツイートをピックアップしてご紹介しておこうと考えていた矢先のツイートですが、よく見ると11時17分の投稿で、私が見たのが13時過ぎだったので、実際には1時間半以上のタイムラグがあったことになりそうです。

　犯罪被害者を愚弄しているとも思える毎度お馴染みの小倉秀夫弁護士のツイートです。本件告訴事件において重要なのは弁護士によって人権を踏みにじられた被害者安藤文さん及び家族の将来でもありますので、同じように軽い気持ちでけちをつけておいて問題そのものを無視している  と見做されます。

　その傾向はモトケンこと矢部善朗弁護士（京都弁護士会）においてより顕著であるとともに、格段に悪質です。小倉秀夫弁護士は、自分とモトケンさんを一緒にデスっているのも珍しい、というようなツイートもやっていましたが、同じように一方的に不当な評価を受けているという認識しかないようです。

　小倉秀夫弁護士とモトケンこと矢部善朗弁護士（京都弁護士会）は対立や反目をしあっているように見えがちですが、弁護士資格を最大限に利用して利益を得ようという動機や、その正当性に対する強固な確信は全く同じ価値観によるものと見ております。

　時刻は13時59分ですが、さきほどNHKのニュース番組で、東海道新幹線の車内で蛇が見つかり捕獲されたと報じられていました。初めヘビが乗車してきたのかと考えましたが、解説を聞いていると、ペットで飼われていた可能性が高そうだと考えが変わりました。種類もわかっていないとのことです。

　時刻は9月28日11時49分になっています。私の影響があるのかどうかは不明であるし、確認できないことですが、ここ数日の小倉秀夫弁護士とモトケンこと矢部善朗弁護士（京都弁護士会）のツイッターのタイムラインは、また控え目モードに戻っている感じで、取り立てたツイートも目に付きません。

　モトケンこと矢部善朗弁護士（京都弁護士会）の個人的な資質において問題性を感じさせる取り立てたツイートは、特に見られないということですが、一般的な意味で気になるツイートがあり、そこから新たな発見もありました。本件告訴事件の経緯と関連のあるテーマでもあります。

　予定外になりますが、それと予定している事実関係などを絡ませて記述をしたいと思います。別の新規項目になります。

2016-09-28　水曜日　11：59　＜＜ ［［　←これまでの記述範囲の終了時刻］］＜＜
**** モトケンこと矢部善朗弁護士（京都弁護士会）のタイムラインで見たクレーマー問題と、石川県警察の対応と責任

:CATEGORIES: 名誉毀損の刑事告訴における具体的相談に先立ち、珠洲警察署に提出する準備書面
:TAGS: モトケンこと矢部善朗弁護士（京都弁護士会）,クレーマー

2016-09-28　水曜日　12：03　＞＞ ［［　←これからの記述範囲の開始時刻］］＞＞

ツイート：motoken_tw（モトケン）：2016/09/28 11:04： https://twitter.com/motoken_tw/status/780951181539454976 ：
引用→　 「クレームを言うお客様に対して『お前は客じゃない！』と一喝することが美談」一般化して美談にしちゃいけないでしょうね。「クレームを言うお客様」にもいろいろあるわけだし。 https://t.co/HRpQ3wwm80

　上記のモトケンこと矢部善朗弁護士（京都弁護士会）のツイートは次のツイートのURLを引用しています。

ツイート：kamatatylaw（高橋雄一郎）：2016/09/27 14:31： https://twitter.com/kamatatylaw/status/780641060062060544 ：
引用→　 クレームを言うお客様に対して「お前は客じゃない！」と一喝することが美談になっているが，平成11年の「東芝クレーマー事件」を覚えている自分としてはとても手放しで称賛できないね。　https://t.co/EvKSkmQOnU

　頻度はそれほど高くないですが、ちょくちょくとリツイートで見かけている高橋雄一郎弁護士のツイートです。他に同じ問題でつながりのあると思われるツイートを、２，３ご紹介しておきます。

ツイート：kamatatylaw（高橋雄一郎）：2016/09/27 14:36： https://twitter.com/kamatatylaw/status/780642299579502592 ：
引用→　 お客様に対して「クレーマー」だと発言したのを録音されネットで配信されて大炎上した。わが国では「お客様は神様」であるはずなのにもかかわらずお客様に不適切な対応をしたということで，東芝製品不買運動まで発展し，副社長が直接面談の上で謝罪したよね。

ツイート：kamatatylaw（高橋雄一郎）：2016/09/27 14:44： https://twitter.com/kamatatylaw/status/780644147224993793 ：
引用→　 わが国では「お客様は神様」なので粘着質にクレームを言われても，応対者はひたすら謝罪しクレームを受け入れるしかない。東芝クレーマー事件の「お客様」は事件後にも病院にクレームをつけてパソコンを盗んだり取引先の会社からデジタルカメラを盗んだことで起訴されたと報道されている。

　次が高橋雄一郎弁護士のツイッターのタイムラインのスクリーンショットになります。

投稿者：s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2016-09-28 12:15  ツイート： https://twitter.com/s_hirono/status/780969062985629697
2016-09-28-121503_高橋雄一郎（@kamatatylaw）さん　｜　Twitterからの返信付きツイート.jpg https://t.co/IslU4fX3jU

　ありがちな都会の風景写真をカバー写真にされていますが、私はこのカバー写真を見るたびに、平成4年2月の東京の池袋駅周辺の風景を思い出します。そごう、ではなく三越だったように思いますが、展示会の仕事で、2週間ほど後の引き上げを含め2回、池袋に行きました。

　展示会の行きの荷物は、平成4年1月12日の日曜日に荷物を積み、夕方には出発して、翌日に池袋で荷物をおろし、引き上げの荷物を摘みに行ったのはその月の終わり頃でした。他の場所に待機していて、夜の遅い時間に池袋に行って荷物を積み込んだことを憶えています。

　展示会の仕事で2週間というのは長すぎるとも考えていたのですが、思い出したことがありました。

　それは引き上げの荷物を積みに行った時、デパートに屋根の低い部分があって、ウィング車の上のシートになっている部分を破ったらしく、それが原因で雨漏りがするようになったことに、数日後になって気が付きました。

　当時のことを思い出しながら記憶が薄れていることを実感しているところですが、1月22日の午前中の時点で、私は雨漏りに気が付き、大きなハサミを手に持ってシート部分の修理にとりかかったこと場面を思い出しました。前後のこともまた別の機会に続きを書くことにしたいと思います。

　「東芝クレーマー事件」というのは、そういえば目にしたことがあったかもしれないと思う程度の記憶だったのですが、調べると、確かに平成11年におきた問題らしく、そんな前にそんなことがあったのかと、まだブログもなかったインターネットの黎明期として、意外に感じるところがありました。

　クレーマーという言葉もいつのまにか社会に認知され浸透していますが、個人的には「ストーカー」のように、知るようになった時期やけっかけの記憶がありません。

　時刻は9月29日10時56分になっています。私が一部にせよ、不当な要求をするクレーマー視されてきたことは想像に固くないのですが、そこまで至らないにせよ、諦めきれずにえんえんと昔の裁判のことにこだわり続けている気の毒な人だという見方は、いっそう多く広まってきたと考えられます。

　私が自分のおかれた立場について十分な説明をすることが出来なかったという一面もあるかも知れず、なにより私自身がそのようなことにこだわり続け、出口の見えない模索を続けてきたとも言えます。

　この項目のタイトルには、クレーマーというモトケンこと矢部善朗弁護士（京都弁護士会）の関連ツイートに絡めて、石川県警察の対応と責任、ということをテーマに据えました。結論を言えば、警察の仕事や刑事裁判を国民の利益のために正しく理解、運用しない弁護士にこそ大きな問題があると考えます。

　私と石川県警察の関係の具体的な経緯など、ここで書く予定にしていたのですが、モトケンこと矢部善朗弁護士（京都弁護士会）と深澤諭史弁護士に気になるツイートがあって、そのことが頭から離れないので、そちらの記述を先に済ませたいと思います。

　そこには、私と石川県警察の関係性の正しい理解、に役立つ教訓のようなものが含まれていると思いますし、弁護士の害悪性と無責任体質こそ根本にある問題性、言葉を変えれば弁護士による社会汚染性をつまびらかにすることが出来、本件告訴事件の実態、真相に迫ることができると考えます。

　先に、ヒントのようなものを提示しておくと、警察の捜査や取り調べに多大の負担を掛け、付け目を狙って引っ掻き回すのが一部の弁護士に共通した泥棒根性であり、それ以外を含めた弁護士においても、儲けや利益にならないことには、全く目を向けようともしない拒絶体質が広く定着しています。

　本当は、昨日のうちにモトケンこと矢部善朗弁護士（京都弁護士会）の一つのツイートを中心に敷衍して取り上げる予定でいたのですが、それはモトケンこと矢部善朗弁護士（京都弁護士会）の個人的な資質に関連した部分の大きな問題でもあり、その前に深澤諭史弁護士からより広い問題点を拾い出します。

2016-09-29　木曜日　11：23　＜＜ ［［　←これまでの記述範囲の終了時刻］］＜＜
**** 深澤諭史弁護士@fukazawasのツイートやリツイートに見る、破滅に向かう弁護士業界の実態と問題性（2016年9月30日現在）

:CATEGORIES: 名誉毀損の刑事告訴における具体的相談に先立ち、珠洲警察署に提出する準備書面
:TAGS: 深澤諭史弁護士,弁護士業界

2016-09-30　金曜日　10：27　＞＞ ［［　←これからの記述範囲の開始時刻］］＞＞

深澤諭史(@fukazawas) - Twilog http://twilog.org/fukazawas

　あとになってじわじわと、なにかとっても気になる放置してはいけないと思える深澤諭史弁護士のツイートを数日前に見たことは頭の隅に引っかかっていたのですが、上記の未登録の深澤諭史弁護士のツイログを遡って、数ある中からこれはと思えるツイートを発見しました。

リツイート：fukazawas（深澤諭史）＞2016/09/26 20:16／2016/09/24 19:53＞ https://twitter.com/fukazawas/status/780365402224271361 ＞
 fukazawas （深澤諭史）＞ https://twitter.com/fukazawas/status/779634915784536065 ＞
引用＞　 弁護士法人の解散、清算結了の公告をみると、いろいろ想像させてくれるな。。。 

リツイート：fukazawas（深澤諭史）＞2016/09/26 20:17／2016/08/08 08:21＞ https://twitter.com/fukazawas/status/780365671410507776 ＞
 fukazawas （深澤諭史）＞ https://twitter.com/fukazawas/status/762428408600989696 ＞
引用＞　 「依頼者保護給付金制度」の件だけれども，この予算を非弁対策に充てた方が，市民の利益保護，信頼維持にずっと役に立つと思う・・・。 

　深澤諭史弁護士のタイムラインでは気が付かなかったのですが、APIからの読み込みで今気がついたことは、どちらのツイートも、深澤諭史弁護士本人の過去のツイートのリツイートだったということです。自分のリツイートがずいぶん目立つのも、他に見ない深澤諭史弁護士の特徴です。

　9月26日のリツイートは1分違いで連続しているのに、元のツイートは8月8日と9月24日というずいぶんな時間の開きがあります。タイムラインでツイートを見ていれば、注意して観察していても気が付かなかった可能性が高そうです。

　深澤諭史弁護士はなぜかTwilogに登録していないのに、過去の自分のツイートは自分でしっかりと管理ないし把握をしているようです。

投稿者：s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2016-09-30 08:36  ツイート： https://twitter.com/s_hirono/status/781638915195154432
2016-09-30-083649_このユーザーはTwilogに登録されていません.jpg https://t.co/TPe8SV9cp0

　上記が記録としてのスクリーンショットになりますが、本日確認したところにおいても深澤諭史弁護士はTwilogに登録していません。人の記憶に残るようなツイートを弁護士という立場で社会に発信しながら、本人以外に過去の発言をわかりづらく、辿りづらくするしておく目的も不思議にみています。

　私は、自分の法的利益を守るためにモトケンこと矢部善朗弁護士（京都弁護士会）と小倉秀夫弁護士の名誉毀損の刑事告訴を進めていますが、そこには社会の正統な理解を得るという公益性が多分にあって、その問題性を浮き彫りにする材料としても、深澤諭史弁護士はまたとない逸材です。

　上記の「「依頼者保護給付金制度」の件だけれども，この予算を非弁対策に充てた方が，市民の利益保護，信頼維持にずっと役に立つと思う・・・。」というツイートは、安藤文さん家族の弁護士によって奪われた保護利益を救済し、弁護士討伐によって社会正義を実現するために大きな意味を持ちます。

　深澤諭史弁護士は、弁護士あるいは法曹として新しい時代の担い手のような活躍もしており、同志のような同調者と思われる同業弁護士のツイートも、盛んにリツイートしています。次から次に泉のように湧いて出てくるのですが、弁護士業界の一翼を担う存在感を記録として辿りご紹介したいと思います。

　数が多くまともに取り上げていれば際限がなくなるので、今回は、先ほどの2016年9月26日20時16分頃のツイートとから本日9月30日までのツイート、リツイートを、冒頭の未登録のTwilogのページを眺めながらご紹介したいと思います。各方面に渡る参考資料になるかと思います。

リツイート：fukazawas（深澤諭史）＞2016/09/27 11:16／2016/09/27 08:15＞ https://twitter.com/fukazawas/status/780591976290717696 ＞
 okaguchik （岡口基一）＞ https://twitter.com/okaguchik/status/780546355890495488 ＞
引用＞　 最低評価のロースクール＜改行＞国立の金沢大と、私立の北海学園大、青山学院大、明治大、桐蔭横浜大、南山大、近畿大。＜改行＞https://t.co/DIoHZt8EYx 

リツイート：fukazawas（深澤諭史）＞2016/09/27 12:19／2016/09/25 23:40＞ https://twitter.com/fukazawas/status/780607824741052416 ＞
 GNKTR3000 （かめ鉄R-3000）＞ https://twitter.com/GNKTR3000/status/780054391193604097 ＞
引用＞　 時給千円にも満たないコンビニのバイトに接客態度が悪いだのたかだか数百円しか払ってない鉄道の駅員に罵声を浴びせ暴力を振るい、「ロゴのデザインに540万は高すぎだから30万でやらせろ」「月給手取り15万の夕張市長を見習え」って本当にこの島国の人間は根性が腐ってるとしか言いようがない 

リツイート：fukazawas（深澤諭史）＞2016/09/27 14:51／2016/09/27 01:08＞ https://twitter.com/fukazawas/status/780645940109508608 ＞
 tanakah （田中　宏）＞ https://twitter.com/tanakah/status/780438784861048832 ＞
引用＞　 「市営住宅退去者の滞納家賃回収のため，退去滞納者及びその連帯保証人に対する催告，滞納家賃等の収納，居所不明者の調査」「着手金，照会や文書取得費用，各種書類作成郵送費用等はすべて成功報酬に含める」＜改行＞なめてんのか？福山市。＜改行＞https://t.co/fHMdsA2xYv 

ツイート：fukazawas（深澤諭史）：2016/09/27 14:51： https://twitter.com/fukazawas/status/780646130400976896 ：
引用→　 福山市営住宅滞納家賃回収業務委託先事業者の募集について＜改行＞https://t.co/pBelMz2q7M＜改行＞「本業務は完全成功報酬制とし，着手金，公署に対する照会や文書取得に係る費用，各種書類作成や郵送に係る，費用等は，個別に算出せず，すべて成功報酬に含めるものとします。」

ツイート：fukazawas（深澤諭史）：2016/09/27 14:52： https://twitter.com/fukazawas/status/780646391483817984 ：
引用→　 弁護士からすると，「債権保全のために必要だけれども費用がかかる措置」はとらなくなっちゃいますね。短期的にはともかく，長期的には市の不利益になる方針を立てちゃうことになってしまう。＜改行＞そのあたりの想像も出来ないレベルだから，滞納を貯めちゃうんだよ（・∀・；）

ツイート：fukazawas（深澤諭史）：2016/09/27 15:03： https://twitter.com/fukazawas/status/780648930245685248 ：
引用→　 福山市は，こういう公募をする前に，まず，「滞納させないような回収業務のコツ」とか，そのあたりを弁護士に相談することが先決だと思いますね。＜改行＞この公募を見る限り，公募して弁護士を使うという域に達していないから，このままだといろいろ損害を被ることになると思う。

ツイート：fukazawas（深澤諭史）：2016/09/27 15:24： https://twitter.com/fukazawas/status/780654341896056832 ：
引用→　 ひたすら弁護士法７２条の裁判例や実務に詳しくなる日々・・・。

リツイート：fukazawas（深澤諭史）＞2016/09/27 15:43／2016/09/27 15:32＞ https://twitter.com/fukazawas/status/780659155749130241 ＞
 nakanori930 （弁護士 中村憲昭）＞ https://twitter.com/nakanori930/status/780656350464397312 ＞
引用＞　 警察官の汚職事件の被告人に対する裁判官の言葉。＜改行＞「これからは、令状審査の時に疑ってかからなければならないのか」。＜改行＞耳を疑った。何のための令状審査なのだろう。 

リツイート：fukazawas（深澤諭史）＞2016/09/27 17:48／2016/09/25 11:31＞ https://twitter.com/fukazawas/status/780690655446114305 ＞
 Hideo_Ogura （小倉秀夫）＞ https://twitter.com/Hideo_Ogura/status/779870963051601920 ＞
引用＞　 ですから、「スラップ訴訟」が禁止されると、ジャーナリストたちは何でもありのジャーナリスト天国がやってくるのだろうと思っているわけですよ。RT @Yu_TERASAWA: でも、その訴訟が「スラップ訴訟」と評されていることはご存じですよね。 

リツイート：fukazawas（深澤諭史）＞2016/09/27 17:48／2016/09/25 11:59＞ https://twitter.com/fukazawas/status/780690662861606912 ＞
 Hideo_Ogura （小倉秀夫）＞ https://twitter.com/Hideo_Ogura/status/779877934026805248 ＞
引用＞　 デマ記事による営業妨害を防ぐために、ジャーナリストを裁判で訴えるのではなく、ジャーナリスト様にお金をお支払いして記事の掲載をおやめいただく社会が到来するのですね。RT @Yu_TERASAWA: スラッパー（スラップ訴訟を起こす原告や代理人）たちが何でもありのスラッパー天国は近々 

リツイート：fukazawas（深澤諭史）＞2016/09/27 21:08／2016/09/27 20:54＞ https://twitter.com/fukazawas/status/780740880281985026 ＞
 sakanosi （坂野真一）＞ https://twitter.com/sakanosi/status/780737381179625473 ＞
引用＞　 依頼者保護給付金制度について、ある若手弁護士に聞くと、まわりの若手弁護士は、みんな反対しているとのこと。 

リツイート：fukazawas（深澤諭史）＞2016/09/27 21:08／2016/09/27 20:56＞ https://twitter.com/fukazawas/status/780740888158810112 ＞
 sakanosi （坂野真一）＞ https://twitter.com/sakanosi/status/780737907615145984 ＞
引用＞　 そこで対案。＜改行＞日弁連執行部は、導入賛成なんだから、まず執行部にいるえらい先生方でお金を出して、試行して頂く。 

リツイート：fukazawas（深澤諭史）＞2016/09/27 21:08／2016/09/27 20:59＞ https://twitter.com/fukazawas/status/780740895935049728 ＞
 sakanosi （坂野真一）＞ https://twitter.com/sakanosi/status/780738679144718336 ＞
引用＞　 被害者の方も、えらい先生のポケットマネーから、見舞金が出たと知れば、日弁連執行部への信頼を回復するかもしれない。＜改行＞まず＜改行＞隗より始めよとは、古今の名言。 

リツイート：fukazawas（深澤諭史）＞2016/09/27 21:08／2016/09/27 21:02＞ https://twitter.com/fukazawas/status/780740902264279040 ＞
 sakanosi （坂野真一）＞ https://twitter.com/sakanosi/status/780739265973989378 ＞
引用＞　 思いおこせば、弁護士過疎のときも、えらい先生方は、若手に過疎地に行け、行けというばかりで、自分から、出向いた方の話を、寡聞にして知らない。 

リツイート：fukazawas（深澤諭史）＞2016/09/27 21:08／2016/09/27 21:05＞ https://twitter.com/fukazawas/status/780740908836790272 ＞
 sakanosi （坂野真一）＞ https://twitter.com/sakanosi/status/780740157976653824 ＞
引用＞　 日弁連や弁護士の為に、日弁連執行部に入られた方ばかりのはずだから、まさか、自分で提案しておきながら、イヤとはいえまい。 

リツイート：fukazawas（深澤諭史）＞2016/09/27 21:08／2016/09/27 21:07＞ https://twitter.com/fukazawas/status/780740918680793088 ＞
 sakanosi （坂野真一）＞ https://twitter.com/sakanosi/status/780740622097326080 ＞
引用＞　 そこまで頑張る執行部を見れば、考え直す若手も出てくるかもしれないよ。＜改行＞悪い対案とは、思わないんだけどね〜。 

ツイート：fukazawas（深澤諭史）：2016/09/27 22:07： https://twitter.com/fukazawas/status/780755867641585665 ：
引用→　 https://t.co/xT2xxvDEZD＜改行＞昔、ロー生、修習生だった私は、「過疎地に赴任した弁護士の体験談」とやらで登壇してしゃべる人が、ことごとく若手であることに、思いっきり違和感を感じていた。

リツイート：fukazawas（深澤諭史）＞2016/09/27 22:16／2016/09/27 22:14＞ https://twitter.com/fukazawas/status/780757947727028227 ＞
 yasumasa218 （新谷泰真）＞ https://twitter.com/yasumasa218/status/780757494100406276 ＞
引用＞　 行かない重鎮より行く若手。 https://t.co/eEmsvY9aj1 

リツイート：fukazawas（深澤諭史）＞2016/09/28 07:30／2016/09/28 01:52＞ https://twitter.com/fukazawas/status/780897545299959808 ＞
 poorpartner （三毛猫B）＞ https://twitter.com/poorpartner/status/780812374970290176 ＞
引用＞　 公設も、採算のいい案件をやらないといけなくなり、ついには採算の悪い案件がやれなくなる。＜改行＞＜改行＞そしてなぜか一民間事業者が採算の悪い案件を細々と手分けして支える。＜改行＞これがどうかはわからない。＜改行＞破滅の道の感じもする。 

リツイート：fukazawas（深澤諭史）＞2016/09/28 07:31／2016/09/28 02:38＞ https://twitter.com/fukazawas/status/780897559493562368 ＞
 ekinan_lawyer （えきなんローヤー）＞ https://twitter.com/ekinan_lawyer/status/780823870559236097 ＞
引用＞　 手厚い経済的支援を受けて公益のために働いているとか過疎地のために働いているとか司法需要を掘り起こしているとか褒めてもらいたい人生であった。＜改行＞＜改行＞まあ、偽善よね。偽善を貫いても偽善でしかない。 

リツイート：fukazawas（深澤諭史）＞2016/09/28 07:31／2016/09/28 06:37＞ https://twitter.com/fukazawas/status/780897641576042496 ＞
 nakanori930 （弁護士 中村憲昭）＞ https://twitter.com/nakanori930/status/780884186374606848 ＞
引用＞　 【精神論】安倍総理「日本の高齢化社会は重荷ではなくボーナスだ」⇒ネット民。そのうち「原発事故は重荷ではなくボーナス」「不景気は重荷ではなくボーナス」とか言いだしそう https://t.co/t6g8QFlRlu 

リツイート：fukazawas（深澤諭史）＞2016/09/28 07:31／2016/09/28 01:49＞ https://twitter.com/fukazawas/status/780897682747338753 ＞
 poorpartner （三毛猫B）＞ https://twitter.com/poorpartner/status/780811508309630976 ＞
引用＞　 都市型公設といえども経営面の問題があることはあるのでしょうね。＜改行＞都市型公設の必要性とかわからないのですが、わたしの関心は東京の中にある、過疎地、分野過疎です。＜改行＞＜改行＞わたしは東京おりますが、独特な過疎地をなんとか支えている、というイメージです。 

リツイート：fukazawas（深澤諭史）＞2016/09/28 07:34／2016/09/27 21:46＞ https://twitter.com/fukazawas/status/780898497801228288 ＞
 okumuraosaka （児童ポルノ児童買春・強制わいせつ弁護人）＞ https://twitter.com/okumuraosaka/status/780750443102121984 ＞
引用＞　 青少年条例違反１回の被害者が弁護士に民事訴訟依頼して着手金５０万（訴額は300万）払っちゃったという相談。実害がないと認容額１０～３０万だと思うよって答えたら機嫌悪そうだった。　まあ頑張れ 

ツイート：fukazawas（深澤諭史）：2016/09/28 07:38： https://twitter.com/fukazawas/status/780899559765446656 ：
引用→　 完全成功報酬制でやってくれという人は、「自分自身、この事件では自分は勝てないと思ってる」ことが多いので、そういうのを見分けるヒントにはなりますね。 https://t.co/XOivayqVJN

リツイート：fukazawas（深澤諭史）＞2016/09/28 07:39／2016/09/28 00:23＞ https://twitter.com/fukazawas/status/780899626169741312 ＞
 tkbei （とりとくLv293）＞ https://twitter.com/tkbei/status/780790003349671937 ＞
引用＞　 「完全成功報酬でお願いします」　#地雷 

ツイート：fukazawas（深澤諭史）：2016/09/28 07:45： https://twitter.com/fukazawas/status/780901293896310784 ：
引用→　 実は，なんだかんだいって完全成功報酬制やそれに準ずる基準で事件を受けることは良くある。特に顧問先の事件で着手金をもらうことはめったにない。＜改行＞一方，初めての依頼者について完全成功報酬制で事件を受けるリスクもよく知っているつもり。

ツイート：fukazawas（深澤諭史）：2016/09/28 07:47： https://twitter.com/fukazawas/status/780901783790981120 ：
引用→　 弁護士の方からではなく，相談者から「完全成功報酬制で」と提案するケースでは，相談者の方に「弁護士に完全成功報酬制で受任してもらうために，自分の事件を真実よりも筋が良いと思ってもらうために，嘘をついたり粉飾したりするインセンティブ」が生じるのが一番大きな問題。

ツイート：fukazawas（深澤諭史）：2016/09/28 07:48： https://twitter.com/fukazawas/status/780902008681222148 ：
引用→　 「どうしても，こいつに嫌がらせしたいので，そのために訴えたい。応訴のコストを負担させることが出来ればそれでよいので，完全成功報酬制で依頼したい」みたいなケースだってあり得るわけで。

リツイート：fukazawas（深澤諭史）＞2016/09/28 09:34／2016/09/28 08:47＞ https://twitter.com/fukazawas/status/780928753522266112 ＞
 ssk_ryo （ささきりょう）＞ https://twitter.com/ssk_ryo/status/780916829413777409 ＞
引用＞　 残業代バブルなんてないよ。このバブルがあるという言説は、使用者側弁護士が業務拡大の狙いをもってしてるに違いないのだ（陰謀論）。 

リツイート：fukazawas（深澤諭史）＞2016/09/28 09:36／2016/09/28 08:54＞ https://twitter.com/fukazawas/status/780929189012656132 ＞
 lawkus （ystk）＞ https://twitter.com/lawkus/status/780918536235388928 ＞
引用＞　 大体、弁護士のくせに肩書付きの氏名は無しで雑誌の取材に答えるという無責任なことする時点で信用できなくねえ？なんだよ弁護士Bって。まあ実はSPA!がエア弁護士にエア取材しただけの可能性の方が高いと思ってるけど。 

リツイート：fukazawas（深澤諭史）＞2016/09/28 11:35／2016/09/28 11:23＞ https://twitter.com/fukazawas/status/780959112305586176 ＞
 Mstferries （ぱねーさん）＞ https://twitter.com/Mstferries/status/780956101890093056 ＞
引用＞　 それよか法テラス廃止 

リツイート：fukazawas（深澤諭史）＞2016/09/28 11:35／2016/09/28 11:25＞ https://twitter.com/fukazawas/status/780959131167367168 ＞
 IcyFumin （軍所総監督フミン）＞ https://twitter.com/IcyFumin/status/780956670490914816 ＞
引用＞　 そこまでやるなら、ロースクール廃止でいいよな。 

リツイート：fukazawas（深澤諭史）＞2016/09/28 11:41／2016/09/28 11:15＞ https://twitter.com/fukazawas/status/780960561919959041 ＞
 k_sawmen （泥濘大魔王サイケ）＞ https://twitter.com/k_sawmen/status/780953934135308288 ＞
引用＞　 ロースクールは人の役に立ってれば餓えて死にはしないし成仏できるからいいでしょ 

リツイート：fukazawas（深澤諭史）＞2016/09/28 12:26／2016/09/28 12:10＞ https://twitter.com/fukazawas/status/780971827254300672 ＞
 koukitei （弁護士中村晃基（福山））＞ https://twitter.com/koukitei/status/780967893848567809 ＞
引用＞　 当地（福山）の話です。 https://t.co/mTNlizLwXh 

ツイート：fukazawas（深澤諭史）：2016/09/28 12:30： https://twitter.com/fukazawas/status/780972853579554816 ：
引用→　 ほんとうにこれ。１０００や２０００で一人ってケースすらある。＜改行＞中傷等の違法投稿にまつわる事件で，投稿内容と人物像が一致しているケースはむしろ珍しい。 https://t.co/lfbtsmkg3O

リツイート：fukazawas（深澤諭史）＞2016/09/28 12:30／2016/09/27 12:34＞ https://twitter.com/fukazawas/status/780972983825203201 ＞
 uwaaaa （サイ太）＞ https://twitter.com/uwaaaa/status/780611659710672896 ＞
引用＞　 「民事の法廷において、素人みたいなトンチンカンな主張・立証をする若手弁護士とときどき会うようになりました。」ってあるんだけど，当職の経験では，素人みたいなトンチンカンな主張・立証をするのはベテランばかりなんですが・・・ 

リツイート：fukazawas（深澤諭史）＞2016/09/28 12:34／2016/09/26 17:16＞ https://twitter.com/fukazawas/status/780973859260379136 ＞
 harrier0516osk （向原総合法律事務所　弁護士向原）＞ https://twitter.com/harrier0516osk/status/780320201665499136 ＞
引用＞　 公共事業を正当化する役割としての産官学のつながりは、法曹養成制度でも見受けたので、まったく違和感がない https://t.co/Ha0uWqoAv3 

ツイート：fukazawas（深澤諭史）：2016/09/28 12:38： https://twitter.com/fukazawas/status/780975045803859968 ：
引用→　 （＾ω＾）お前らの借金と引換えになった補助金で食べる飯はうまいお！ https://t.co/PQfAdgWxHw

ツイート：fukazawas（深澤諭史）：2016/09/28 15:37： https://twitter.com/fukazawas/status/781020025884962816 ：
引用→　 @kotadon ＠総本山？

ツイート：fukazawas（深澤諭史）：2016/09/28 15:39： https://twitter.com/fukazawas/status/781020586994757632 ：
引用→　 @kotadon 出家なう(爆)

リツイート：fukazawas（深澤諭史）＞2016/09/28 15:47／2016/09/27 21:06＞ https://twitter.com/fukazawas/status/781022378566488064 ＞
 marumichi0316 （圓道至剛（まるみちむねたか））＞ https://twitter.com/marumichi0316/status/780740480090845184 ＞
引用＞　 高校生くらいの時に、自分が万が一交通事故で亡くなった場合の、予想される損害賠償の額と、典型的な過失相殺事由によりそれがどの程度減額されるかを知る機会があると良い。人の命が失われても金銭で解決されるという厳然たる事実と、ちょっとしたことでそれが大幅に減額されることを知っておきたい。 

リツイート：fukazawas（深澤諭史）＞2016/09/28 17:08／2016/09/27 13:29＞ https://twitter.com/fukazawas/status/781042904781451266 ＞
 take___five （take-five）＞ https://twitter.com/take___five/status/780625286492672000 ＞
引用＞　 弁護士をよくテレビで見るようになったのは、弁護士が身近になったってことでいいことなのかもしれないけど、刑事や家事事件等でトンチンカンな回答しているのをみると、「弁護士であっても信用できない」という評判が広まらないか心配。 

リツイート：fukazawas（深澤諭史）＞2016/09/28 17:16／2016/09/28 17:07＞ https://twitter.com/fukazawas/status/781044849428533248 ＞
 kotadon （こたんせ～君が落ち着け）＞ https://twitter.com/kotadon/status/781042627114336256 ＞
引用＞　 どことはいわないけど、まぁ、勉強してないし、依頼者の人形だなと 

リツイート：fukazawas（深澤諭史）＞2016/09/28 18:06／2016/09/28 16:13＞ https://twitter.com/fukazawas/status/781057507473043456 ＞
 taniyama （弁護士 谷山智光）＞ https://twitter.com/taniyama/status/781029072667377664 ＞
引用＞　 3月の高裁逆転無罪判決事件の無罪費用補償請求の決定が出た。決定金額が安い。被告人は国家権力により起訴され、せいいっぱい防御して、なんとか無罪判決を獲得しても、赤字になる。ひどい話。 

リツイート：fukazawas（深澤諭史）＞2016/09/28 18:06／2016/09/28 16:15＞ https://twitter.com/fukazawas/status/781057532982730753 ＞
 taniyama （弁護士 谷山智光）＞ https://twitter.com/taniyama/status/781029534657286144 ＞
引用＞　 無罪費用補償請求の場面でも法テラス基準が足をひっぱる。法テラスは弁護士の首をじわじわ絞めつける制度。 

リツイート：fukazawas（深澤諭史）＞2016/09/28 18:06／2016/09/28 16:19＞ https://twitter.com/fukazawas/status/781057542206087168 ＞
 taniyama （弁護士 谷山智光）＞ https://twitter.com/taniyama/status/781030447362998272 ＞
引用＞　 人件費も含めて捜査機関は有罪にするためにどれだけの費用を使っているのか。今回の無罪費用補償請求の決定金額はそれと比べて不均衡。お金気にすることなくどんどん捜査して起訴されるのに、無罪へ向けての防御活動はこれっぽちの金額でせよと？ 

リツイート：fukazawas（深澤諭史）＞2016/09/28 18:23／2016/09/28 11:12＞ https://twitter.com/fukazawas/status/781061851840860160 ＞
 okumuraosaka （児童ポルノ児童買春・強制わいせつ弁護人）＞ https://twitter.com/okumuraosaka/status/780953336413507584 ＞
引用＞　 今日も自首自首自首自首という電話とかメールの相談。だれか逮捕されると不安になるでしょうね、　弁護士に電話で聞いた知識で行っても自首にならんだろう。 

リツイート：fukazawas（深澤諭史）＞2016/09/28 20:49／2016/09/28 20:05＞ https://twitter.com/fukazawas/status/781098394194292737 ＞
 harukazechan （はるかぜちゃん໒꒱· ﾟ）＞ https://twitter.com/harukazechan/status/781087483006103552 ＞
引用＞　 たかが140 されど140文字にも＜改行＞はっきりと人柄がでている＜改行＞ツイートの素敵な人は生き方もかっこいいよね 

リツイート：fukazawas（深澤諭史）＞2016/09/28 20:53／2016/09/28 19:19＞ https://twitter.com/fukazawas/status/781099464354213889 ＞
 1961kumachin （中村元弥）＞ https://twitter.com/1961kumachin/status/781075914385821696 ＞
引用＞　 刑事の裁判官は、自白事件をどれくらいの割合で被告人質問先行でやったか、というノルマでも課されているのかね？ 

リツイート：fukazawas（深澤諭史）＞2016/09/29 09:25／2016/09/21 16:07＞ https://twitter.com/fukazawas/status/781288779617304576 ＞
 otakulawyer （山口貴士）＞ https://twitter.com/otakulawyer/status/778490799713419264 ＞
引用＞　 カルト問題に長年取り組んで来た弁護士として言わせてもらうと、クライアントに「前世」、「因縁」、「カルマ」や「オーラ」の話をするカウンセラーとは速やかに縁を切った方が良い。 

リツイート：fukazawas（深澤諭史）＞2016/09/29 09:46／2016/09/28 19:56＞ https://twitter.com/fukazawas/status/781294018131091456 ＞
 niwakananj （のーぱわー）＞ https://twitter.com/niwakananj/status/781085181104881665 ＞
引用＞　 中小企業診断士が非弁ぽいことやってると思ったら、案の定自称経営コンサル 

ツイート：fukazawas（深澤諭史）：2016/09/29 09:46： https://twitter.com/fukazawas/status/781294085487398912 ：
引用→　 ＞ＲＴ＜改行＞コンサルと言えば非弁をやっても良いという謎の風潮。＜改行＞（・∀・；）

リツイート：fukazawas（深澤諭史）＞2016/09/29 10:06／2016/09/29 09:55＞ https://twitter.com/fukazawas/status/781298970295410688 ＞
 Shingo_Nakao （中尾慎吾）＞ https://twitter.com/Shingo_Nakao/status/781296243054039040 ＞
引用＞　 弁護士がコンサルやるのがベストですね https://t.co/qxrYcaynsO 

ツイート：fukazawas（深澤諭史）：2016/09/29 10:07： https://twitter.com/fukazawas/status/781299257173221376 ：
引用→　 https://t.co/GHnhahkd3U＜改行＞本当にそう思います。＜改行＞法律という，事業等の目的達成のために最大の障害にも武器にもなり得る点についてアドバイスできない非弁護士のコンサルは，価値が限定されると思います。

リツイート：fukazawas（深澤諭史）＞2016/09/29 10:24／2016/09/29 10:20＞ https://twitter.com/fukazawas/status/781303480866770948 ＞
 Hideo_Ogura （小倉秀夫）＞ https://twitter.com/Hideo_Ogura/status/781302700197543936 ＞
引用＞　 ジャーナリスト様が裏付け取材抜きでデマ報道しても法的な責任をとらされない社会を作るために、与党と結託して、弁護士自治を剥奪するのですねRT @Yu_TERASAWA: 今後、そのような方向性で報道していくことになりそうです。 RT @k_brigeil 弁護士自治は剥奪しかないと 

ツイート：fukazawas（深澤諭史）：2016/09/29 10:46： https://twitter.com/fukazawas/status/781309171614507009 ：
引用→　 セカンドオピニオンを求められることも結構あって，その経験上の話なんですが，「美味しい事件」には，事件そのものが美味しいというだけではなくて，「上手いこと依頼者の不安を煽ったり，結果を請け負ったりして高額報酬を設定している」事案も少… https://t.co/sqaQZhH3G4

リツイート：fukazawas（深澤諭史）＞2016/09/29 11:02／2016/09/29 10:57＞ https://twitter.com/fukazawas/status/781313260238888960 ＞
 nkaoguo （Kay）＞ https://twitter.com/nkaoguo/status/781311917050691584 ＞
引用＞　 否認事件の謄写費用を「厘」の単位まで算出して根拠資料付けて請求した件、10日以上経つのに法テラスから全く回答がない。自分たちは報告書の期限にうるさいくせに、相変わらずクソみてえな奴らだ。 

リツイート：fukazawas（深澤諭史）＞2016/09/29 11:03／2016/09/29 10:59＞ https://twitter.com/fukazawas/status/781313329381998593 ＞
 nkaoguo （Kay）＞ https://twitter.com/nkaoguo/status/781312523639422976 ＞
引用＞　 法テラスor日弁連or法曹養成制度に言及すると口汚くなってしまって良くないですね。。。 

リツイート：fukazawas（深澤諭史）＞2016/09/29 11:54／2016/09/29 07:53＞ https://twitter.com/fukazawas/status/781326210970320896 ＞
 shima_chikara （嶋﨑量（弁護士））＞ https://twitter.com/shima_chikara/status/781265645413339136 ＞
引用＞　 現状の正社員は「特権」と呼べるような手厚い雇用とは思えません。＜改行＞正社員と非正規とを対立構造にしたてあげても、雇用全体のさらなる劣化を生むだけ。 https://t.co/uI3bEPqzAt 

リツイート：fukazawas（深澤諭史）＞2016/09/29 12:39／2016/09/29 12:33＞ https://twitter.com/fukazawas/status/781337693301026816 ＞
 Hideo_Ogura （小倉秀夫）＞ https://twitter.com/Hideo_Ogura/status/781336097104142336 ＞
引用＞　 「俺たちを被告とする訴訟を受任する弁護士は許せない」として懲戒していくことを認めていくと、強い奴らに踏みつけられる庶民の側に立つ弁護士はいなくなりますね。RT @Yu_TERASAWA: 小倉秀夫弁護士の言動を見ていたら、たいていの人は弁護士自治を剥奪すべきだと考えるはずです。 

リツイート：fukazawas（深澤諭史）＞2016/09/29 12:40／2016/09/29 11:59＞ https://twitter.com/fukazawas/status/781337822661791744 ＞
 Hideo_Ogura （小倉秀夫）＞ https://twitter.com/Hideo_Ogura/status/781327611691540480 ＞
引用＞　 私が2009年頃にエントリーを書いた頃と、あちら側は何も進歩していない。https://t.co/1MCmmWC0WJ https://t.co/sQbM5NppYM　RT @shima_chikara: 現状の正社員は「特権」と呼べるような手厚い雇用とは思えません。 

リツイート：fukazawas（深澤諭史）＞2016/09/29 13:07／2016/09/28 21:00＞ https://twitter.com/fukazawas/status/781344511515500544 ＞
 otakulawyer （山口貴士）＞ https://twitter.com/otakulawyer/status/781101371789422592 ＞
引用＞　 アムネスティ日本がこんなに圧力に弱い団体とは思わなかった。この体たらくでは、代用監獄、死刑等の問題で公権力に勝てる筈もない。 

ツイート：fukazawas（深澤諭史）：2016/09/29 13:09： https://twitter.com/fukazawas/status/781345108398444544 ：
引用→　 名誉毀損事件は，原告（発信）側も被告（被害）側も，団体側でも個人側でも，平均的な弁護士よりは，はるかに沢山やってきてつもりですが，弁護士自治がなくなったら，たぶん，スラップ訴訟（と呼ばれる）ものは増えることはあっても減る事は無いと思う。

リツイート：fukazawas（深澤諭史）＞2016/09/29 13:22／2016/09/29 13:18＞ https://twitter.com/fukazawas/status/781348355809042432 ＞
 6d745 （ろくでなし子一審一部無罪！）＞ https://twitter.com/6d745/status/781347382705344512 ＞
引用＞　 （´-`）.｡oO（明日のアムネスティー日本でのトークイベント、予定通り開催決まりました！＜改行＞言論弾圧に屈しない方に向いてくれたアムネスティー日本さん、ありがとうございます＼(^o^)／ 

ツイート：fukazawas（深澤諭史）：2016/09/29 13:38： https://twitter.com/fukazawas/status/781352471713107968 ：
引用→　 間違いなくあると思ってた（・∀・）＜改行＞も，もしや，金塊とか美術品で・・・。 https://t.co/YGPXrEQGXp

リツイート：fukazawas（深澤諭史）＞2016/09/29 15:43／2016/09/29 13:28＞ https://twitter.com/fukazawas/status/781383953273851904 ＞
 kaito_regend （たろう featuring TARO）＞ https://twitter.com/kaito_regend/status/781349877959659520 ＞
引用＞　 残業代をちゃんと払わせる、払ってない企業はちゃんと制裁する。しかも、民事罰に止めない。＜改行＞＜改行＞払ってる企業が損をする現状を変えないと、いつまでたっても不払いは無くならない。それを「民間の自助努力で」と言ってられる時期は過ぎたのではないかと思う。 

リツイート：fukazawas（深澤諭史）＞2016/09/29 17:18／2016/09/29 17:18＞ https://twitter.com/fukazawas/status/781407795945967616 ＞
 uwaaaa （サイ太）＞ https://twitter.com/uwaaaa/status/781407753239605252 ＞
引用＞　 法テラスは，主要取引先である弁護士に営業かけるのに「予算が余ってるから法テラスをどんどん使ってね＾＾」しか言わないんだけど，「手間を減らしてますます使いやすくなった法テラスをよろしくね＾＾」とか言うのが営業じゃないんですかね。 

ツイート：fukazawas（深澤諭史）：2016/09/29 17:55： https://twitter.com/fukazawas/status/781417177190584320 ：
引用→　 真実追求→誤解と無知に基づく誤報を垂れ流すこと＜改行＞（・∀・）？ https://t.co/Igi3czfGRl

リツイート：fukazawas（深澤諭史）＞2016/09/29 20:19／2016/09/29 19:56＞ https://twitter.com/fukazawas/status/781453381126586368 ＞
 nodahayato （弁護士　野田隼人）＞ https://twitter.com/nodahayato/status/781447553627938816 ＞
引用＞　 新人のイソ弁が、使えないやつだと分かったとき、ボス弁は辞めさせようとするのですか？どのような契約が交わされているかにもよるとは思いますが、実際… — 損害を拡大せずにそのイソ弁の経費分売り上げるにはどうするか考えることになります。 https://t.co/WUUnPsxHAh 

リツイート：fukazawas（深澤諭史）＞2016/09/29 20:20／2016/09/29 19:48＞ https://twitter.com/fukazawas/status/781453494083387393 ＞
 igaki （弁護士 井垣孝之）＞ https://twitter.com/igaki/status/781445484955234304 ＞
引用＞　 会務を積極的にやる(いろいろ提案したりする)人に会務が集中する構造、ほんとなんとかならんかね。どんどん提案しない方向になって不活性化していくんだが。正副委員長は会務を分散する方向に常に気を遣わないと、マジで会務やる人いなくなるよ。 

リツイート：fukazawas（深澤諭史）＞2016/09/29 21:25／2016/09/29 21:11＞ https://twitter.com/fukazawas/status/781469872014303232 ＞
 kamatatylaw （高橋雄一郎）＞ https://twitter.com/kamatatylaw/status/781466468655300608 ＞
引用＞　 飲食店で隣に座っている人に突然殺虫スプレーを噴霧する行為と，飲食店で非喫煙者の前で喫煙をする行為とは，健康に有害な物質を噴霧するという点でまったく同じだろうね。 

リツイート：fukazawas（深澤諭史）＞2016/09/29 22:20／2016/09/29 22:12＞ https://twitter.com/fukazawas/status/781483708268187652 ＞
 un_co_the2nd （うのじ）＞ https://twitter.com/un_co_the2nd/status/781481791542525953 ＞
引用＞　 日本って激烈貧しくなったんだな、と思いました。 

ツイート：fukazawas（深澤諭史）：2016/09/29 23:42： https://twitter.com/fukazawas/status/781504397784211456 ：
引用→　 (･∀･)＜改行＞#自分を倒したら落としそうなアイテムをフォロワーさんが引用RTで教えてくれる

　以上がお昼頃にTwilogで読み込んでいた分です。これからは先ほど、再読込したものになります。今日は13時半頃にパソコンの頼まれごとで出かけ、夕方はアオリイカ釣りのエギングに行っていました。家に戻ったのは19時過ぎだったように思います。

ツイート：fukazawas（深澤諭史）：2016/09/30 09:36： https://twitter.com/fukazawas/status/781653985404997632 ：
引用→　 残業代ゼロというのは誤解である。そのことを、どうか国民諸君に理解いただきたい。＜改行＞つまり、我々がその気になれば、残業代は全額払うが、残業という概念そのものを消し去ることで、事実上の残業代ゼロを達成できるだろうということ！＜改行＞#司法黙示録

リツイート：fukazawas（深澤諭史）＞2016/09/30 09:37／2016/04/19 09:55＞ https://twitter.com/fukazawas/status/781654236303994880 ＞
 fukazawas （深澤諭史）＞ https://twitter.com/fukazawas/status/722227108404039681 ＞
引用＞　 某機構・某所「あんた，マイナス（借金）１０００万円！！」＜改行＞ドーン！！＜改行＞＜改行＞「ああ，なんで・・，おれ達にばかり，こんな負担が・・。どうして，法曹に成りたいだけなのに，借金ばかりさせられるんだ・・・。なぜ・・・。」＜改行＞#司法黙示録 

リツイート：fukazawas（深澤諭史）＞2016/09/30 09:50／2016/09/30 00:58＞ https://twitter.com/fukazawas/status/781657513573744640 ＞
 jyunichidesita （順一）＞ https://twitter.com/jyunichidesita/status/781523480336412672 ＞
引用＞　 「社会に出てからも、分からない事はGoogleで調べれば済むから、勉強なんてそこまで重要じゃない」とか考えてたら大間違いだよ。ググって出てくる知識で働いてたら「スマホあればお前いらねぇじゃん」って感じで必要とされないからね。知識は自分の物にして初めて有効活用出来るんですよ。 

リツイート：fukazawas（深澤諭史）＞2016/09/30 09:50／2016/09/30 09:50＞ https://twitter.com/fukazawas/status/781657527490523137 ＞
 ysaksmz （Yoshi Shimizu）＞ https://twitter.com/ysaksmz/status/781657366307614720 ＞
引用＞　 ググった情報で訴訟をやったらどうなるか、多くの本人訴訟で実験している方がいっぱいいらっしゃる模様 

ツイート：fukazawas（深澤諭史）：2016/09/30 09:52： https://twitter.com/fukazawas/status/781658020698697732 ：
引用→　 さて、総本山の会議（WG）へ！

ツイート：fukazawas（深澤諭史）：2016/09/30 12:04： https://twitter.com/fukazawas/status/781691096636203008 ：
引用→　 毎度のことですが，日弁連ＷＧは白熱するなぁ・・・。勉強になる

ツイート：fukazawas（深澤諭史）：2016/09/30 12:22： https://twitter.com/fukazawas/status/781695588589076480 ：
引用→　 ＞ＲＴ＜改行＞学校の先生は，安易に「没収」とかやりすぎでしょうね。＜改行＞後で返せばいいとか，「カツアゲしても，後で返せばいい」とかいう不良少年とかわりませんよ。

ツイート：fukazawas（深澤諭史）：2016/09/30 12:25： https://twitter.com/fukazawas/status/781696473650135040 ：
引用→　 別に私は「子どもの人権を大事に！」と高潔な理想を持っているわけではないですが，小中高校の先生は，自分が正しくて生徒児童が間違っていると軽信したときの行動が，あまりに軽率すぎます。＜改行＞理不尽な扱いをされた子どもは，大人になってから同じことを自分より弱い人にするようになってしまう。

ツイート：fukazawas（深澤諭史）：2016/09/30 12:26： https://twitter.com/fukazawas/status/781696740701433856 ：
引用→　 「子どもの人権」以前に教育に悪いから，社会に危険な人物を育成することになるから，はっきりいって社会に迷惑だから，止めて下さい，と思っています。

ツイート：fukazawas（深澤諭史）：2016/09/30 12:28： https://twitter.com/fukazawas/status/781697239005659136 ：
引用→　 そういえば，中学だか，高校のときだったか，体育教師が，「昔，生徒に指導（暴行）したら怪我をさせてしまった。そうしたら，その後学校に診断書が出されて被害を訴えられた」という話を，「おかしな話」として，紹介していたのを思い出した。たしか授業時間の３分の１くらいつかってたな

ツイート：fukazawas（深澤諭史）：2016/09/30 12:29： https://twitter.com/fukazawas/status/781697574977802240 ：
引用→　 まあ，たしかに「（お前の頭が）おかしな話だな」と思いながら聞いていたが，必死に自己弁護する様をみて，「やっぱり不法行為には毅然と素早く対処するのが，特にこういうチンピラにはよく効くんだな」と，実に教育的な授業時間だったとおもいました。＜改行＞（・∀・）

ツイート：fukazawas（深澤諭史）：2016/09/30 12:31： https://twitter.com/fukazawas/status/781697898799046656 ：
引用→　 @okaguchik ＜改行＞先生，「第二東京弁護士会」です。お間違いなきよう！（・∀・＃）

ツイート：fukazawas（深澤諭史）：2016/09/30 12:38： https://twitter.com/fukazawas/status/781699596883984384 ：
引用→　 ネット系の会社にも結構多いな。＜改行＞「こちらは第三者なんで拘束されませんし，そもそも，法律上は使用者責任として会社に責任があるだけではなく，（国賠とは違って）担当者あなた個人も不法行為責任を負いかねないのですが，よろしいですね？」とい… https://t.co/2Y1R2o1LQ6

　上記の深澤諭史弁護士のツイートは次のツイートのURLを引用しています。

ツイート：stdaux（スドー）：2016/09/30 12:35： https://twitter.com/stdaux/status/781698915984822273 ：
引用→　 「社内の規則上こうなってるんです」と主張する人に「でもそれ御社が一方的に決めた規則に過ぎませんし、法律に照らすとどうなんです？」という話を振ると、虚をつかれたような表情をすることが少なくない

ツイート：fukazawas（深澤諭史）：2016/09/30 12:48： https://twitter.com/fukazawas/status/781702269943283712 ：
引用→　 と，ツイートして思ったが，「カツアゲしても，後で返せばいい」と考えるほど，非行傾向の進んだ不良少年には会ったことないですね。＜改行＞不良の皆様にお詫びして訂正します（・∀・）

リツイート：fukazawas（深澤諭史）＞2016/09/30 14:23／2016/09/30 12:49＞ https://twitter.com/fukazawas/status/781726106810404864 ＞
 un_co_the2nd （うのじ）＞ https://twitter.com/un_co_the2nd/status/781702373781757952 ＞
引用＞　 自治体のイベントに使うイラストやなんかに萌え絵や少女や若い女性を使うと不適切だと言われてしまうので、ヒゲ・筋肉・ジジイ・どうぶつで行きましょう。 

リツイート：fukazawas（深澤諭史）＞2016/09/30 14:23／2016/09/30 13:53＞ https://twitter.com/fukazawas/status/781726119019941888 ＞
 kmuramatsu （弁護士 村松 謙）＞ https://twitter.com/kmuramatsu/status/781718499118845952 ＞
引用＞　 蘇民祭は、むさ苦しい髭のおっさんでもダメだったからなぁ。。。 

リツイート：fukazawas（深澤諭史）＞2016/09/30 14:23／2016/09/30 11:40＞ https://twitter.com/fukazawas/status/781726161101426688 ＞
 kamatatylaw （高橋雄一郎）＞ https://twitter.com/kamatatylaw/status/781685150342062080 ＞
引用＞　 いうまでもないことであるが，「萌え」で村おこし・町おこしなんてものは全部禁止だろう。「少女を性的消費の対象にしている」というネット上での批判が予想されるからね。 

リツイート：fukazawas（深澤諭史）＞2016/09/30 14:23／2016/09/30 11:38＞ https://twitter.com/fukazawas/status/781726168915451905 ＞
 kamatatylaw （高橋雄一郎）＞ https://twitter.com/kamatatylaw/status/781684599181176832 ＞
引用＞　 新しいポリティカル・コレクトネスによれば，今後は，公共財としての電波を利用するテレビ番組でも未成年の女性や未成年に見える可能性のある３５歳未満の女性やキャラクターを出演させるべきではない。「少女を性的消費の対象にしている」というネット上での批判が予想されるからである。 

リツイート：fukazawas（深澤諭史）＞2016/09/30 14:23／2016/09/30 11:32＞ https://twitter.com/fukazawas/status/781726182865719297 ＞
 kamatatylaw （高橋雄一郎）＞ https://twitter.com/kamatatylaw/status/781683206059950080 ＞
引用＞　 公的・準公的な組織が行う事業企画において「少女」と関連性のある素材を利用することは絶対にやめたほうがいい。「少女を性的消費の対象にしている」とネット炎上を招く。これが新しいポリティカル・コレクトネス。 

リツイート：fukazawas（深澤諭史）＞2016/09/30 17:36／2016/09/30 09:35＞ https://twitter.com/fukazawas/status/781774764801003521 ＞
 rippy08 （りっぴぃ@長女２歳目前）＞ https://twitter.com/rippy08/status/781653727090388992 ＞
引用＞　 C型肝炎訴訟を手掛けられた先生に聞いたところによれば、国が原告団に対して「あなたこの街宣に出てましたよね、この集会にも来てましたよね、元気じゃないですか」といった内容の反対尋問をやって批判を浴び、そのような尋問はなくなっていった歴史があるとか。 

リツイート：fukazawas（深澤諭史）＞2016/09/30 19:01／2016/09/30 17:40＞ https://twitter.com/fukazawas/status/781795985886294017 ＞
 houterasu_4_10 （法テラス（広報））＞ https://twitter.com/houterasu_4_10/status/781775627280064512 ＞
引用＞　 【　＃10周年　】平成18年に設立された法テラスは、今年10月２日、業務開始から10年を迎えます。コールセンターの情報提供の累計利用件数は、300万件を超え、法律相談援助件数は、平成19年度と比較して平成27年度は約2倍になるなど業務実績が着実に伸びております。 

リツイート：fukazawas（深澤諭史）＞2016/09/30 19:01／2016/09/30 18:01＞ https://twitter.com/fukazawas/status/781796009030541313 ＞
 akira83583063 （akira(田舎弁護士)）＞ https://twitter.com/akira83583063/status/781780921909338112 ＞
引用＞　 ただし、報酬等がクッソ安いため、弁護士からの評価は悪く、弁護士から着実に避けられています。 https://t.co/uqbOTfwZUO 

リツイート：fukazawas（深澤諭史）＞2016/09/30 19:01／2016/09/30 18:07＞ https://twitter.com/fukazawas/status/781796024293531649 ＞
 un_co_the2nd （うのじ）＞ https://twitter.com/un_co_the2nd/status/781782387873161216 ＞
引用＞　 それだけ民業圧迫しているとも https://t.co/ebr2looq9e 

リツイート：fukazawas（深澤諭史）＞2016/09/30 19:27／2016/09/30 19:25＞ https://twitter.com/fukazawas/status/781802763483123712 ＞
 akira83583063 （akira(田舎弁護士)）＞ https://twitter.com/akira83583063/status/781802195922489344 ＞
引用＞　 @MaximolsDs @fukazawas 教師は、生徒を指導できる「資格」なんて全くありません。よって、弁護士と同列に論じる時点で、論理破綻しています。法解釈以前の問題ですよ。 

　時刻は20時26分です。先ほど深澤諭史弁護士の未登録のTwilogで、再読込した分は終わりました。

　掲載しないでおこうと思った深澤諭史弁護士のリツイートが4件連続であって、そのツイートに関連して他の匿名弁護士も気になるツイートをしていたので、正確な参考のため次に掲載します。直後の深澤諭史弁護士のツイートが、「学校の先生は，安易に「没収」とかやりすぎでしょうね」です。

リツイート：fukazawas（深澤諭史）＞2016/09/30 12:20／2016/09/30 12:08＞ https://twitter.com/fukazawas/status/781695124837371904 ＞
 harukazechan （はるかぜちゃん໒꒱· ﾟ）＞ https://twitter.com/harukazechan/status/781692126287437824 ＞
引用＞　 弟が学校の総合の読書の時間にロシア語の本を読んで本を没収されたらしくて＜改行＞「柊夜くんが納得いかないので謝りたくありませんって言ってて本が返せないのでご家庭で謝らせるように指導してください」＜改行＞って電話がさっき親にかかってきたんだけど＜改行＞親が「えっ 私も納得いきません」って言ってる 

リツイート：fukazawas（深澤諭史）＞2016/09/30 12:20／2016/09/30 12:12＞ https://twitter.com/fukazawas/status/781695139618156544 ＞
 harukazechan （はるかぜちゃん໒꒱· ﾟ）＞ https://twitter.com/harukazechan/status/781693134069649408 ＞
引用＞　 理由は、ロシア語の本だから没収されたのではなくて、勉強の本だからだそうです＜改行＞ぼくたちの中学の総合の時間は＜改行＞活字にふれるため読書の時間になってて、物語の本を読むことを推奨されています＜改行＞その時間はテスト勉強などは禁止です 

リツイート：fukazawas（深澤諭史）＞2016/09/30 12:20／2016/09/30 12:16＞ https://twitter.com/fukazawas/status/781695153627078656 ＞
 harukazechan （はるかぜちゃん໒꒱· ﾟ）＞ https://twitter.com/harukazechan/status/781694105348747264 ＞
引用＞　 勉強の本を読むことが禁止なのは、読書の時間にテスト勉強をする人がいるからです＜改行＞でもロシア語の本はテストに関係ないから問題ないんじゃないかとぼくも思います＜改行＞それに学校は学ぶために行くところなので＜改行＞勉強してるのに怒られたり、没収されたり、謝らされることではないような気がします 

リツイート：fukazawas（深澤諭史）＞2016/09/30 12:20／2016/09/30 12:19＞ https://twitter.com/fukazawas/status/781695184098750464 ＞
 harukazechan （はるかぜちゃん໒꒱· ﾟ）＞ https://twitter.com/harukazechan/status/781694868795957248 ＞
引用＞　 「ご家庭で謝らせるようにしてください」とのことなので＜改行＞父と母が電話で家族会議をしています＜改行＞いや、みんな納得いかないって感じでなんとなくまとまりつつあります＜改行＞ぼくも「出来れば物語の本を読んでもらうように・・・」とかなら分かるけど、先生に「謝らせる」ことではないような気がしています 

　時刻は10月2日9時55分になっています。その後、深澤諭史弁護士のタイムラインにおいては、記録の必要を強く感じさせられるようなツイート、リツイートは目にしていないように考えていますが、余りじっくりと読み込んでもいません。

　7月の告訴状だったようにも思いますが、紙面を割いて「弁護士ばびろん」というアカウントのご紹介をしたと思いますが、昨日あたりからこれは是非ご紹介しておきたいと思うツイートがあったので、次にそれを取り上げることにします。

2016-10-02　日曜日　10：01　＜＜ ［［　←これまでの記述範囲の終了時刻］］＜＜
**** その名を「弁護士ばびろん」のツイートにおける、弁護士によって受けた被害の回復と、弁護士に対する社会の信頼

:CATEGORIES: 名誉毀損の刑事告訴における具体的相談に先立ち、珠洲警察署に提出する準備書面
:TAGS: 弁護士ばびろん,被害者給付金制度,弁護士会

2016-10-02　日曜日　10：16　＞＞ ［［　←これからの記述範囲の開始時刻］］＞＞

ツイート：mackckckck（弁護士ばびろん）：2016/09/29 16:27： https://twitter.com/mackckckck/status/781394890752090112 ：
引用→　 被害者給付金制度は、弁護士に対する社会の信頼を回復するためには欠かせない。

ツイート：mackckckck（弁護士ばびろん）：2016/09/29 16:27： https://twitter.com/mackckckck/status/781394961279307780 ：
引用→　 @mackckckck んなわけないでしょ。

　APIからデータを読み込んで気がついたのですが、どちらも同一時刻のツイートになっています。2つ目のツイートは通常のタイムラインには表示されず、「ツイートと返信 」を開くことで表示されるツイートです。見ての通り、自分自身への返信というかたちになっています。

　かねがねミステリー性の高い弁護士アカウントだと思ってきましたが、これはいよいよ不思議な行動です。1分以内の連続ツイートですが、先のツイートの内容を否定するものを、余りに短い時間で投稿しており、わかってやっているのか、後のものは通常のタイムラインに表示されないものとなっています。

　ちょっと勘違いしたことがきっかけで、弁護士ばびろん、というアカウントのタイムラインを8月18日頃まで遡りました。定期的に過去のツイートを削除するのか、先日も9月21日あたりのツイートまでしかタイムラインで読み込めなかったのですが、そのアカウントと記憶が混同していました。

　実は、同じ頃、上記の弁護士ばびろん、の２つのツイートも本人のタイムラインから消えていて、削除されたのかと思っていたところ、検索ツイートのタイムラインで発見したのです。

投稿者：s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2016-10-02 11:01  ツイート： https://twitter.com/s_hirono/status/782399993902604288
2016-10-02-110104_でゅーく（●―●）まんGO（@nan5o）さん　｜　Twitterからの返信付きツイート.jpg https://t.co/Z6ki5EEGtN

　上記は9月21日のツイートまでしか読み込めない匿名弁護士アカウントのタイムラインのスクリーンショットです。これもミステリー性があって、不思議なことにツイート数は1264となっているのです。

　今、再確認をしていて気がついたのは、先日みていたのはツイートの通常のタイムラインで、そのことに気が付き「ツイートと返信」のタイムラインを開くと、＠の返信ツイートがとても多いということです。

投稿者：s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2016-10-02 11:14  ツイート： https://twitter.com/s_hirono/status/782403255728939010
2016-10-02-111401_でゅーく（●―●）まんGO（@nan5o）　-　Twilog.jpg https://t.co/wQQ4zFzZFY

　上記は登録されていないTwilogのスクリーンショット。未登録の200件のツイートは9月29日から本日10月2日までの4日分となっていて、それぞれ58、84、54、４というツイート数になっています。9月21日までしか遡れないのに、そこから千件以上とは考えられないところです。

　本人の意思や操作で、どこまでできるものなのか想像もつきませんが、Twitterにおける不可解な現象として興味深く観察していたところ、そこで目にしたのが冒頭の弁護士ばびろん、のツイートでした。ツイッターだけでなく、弁護士という業界の不可解さ、ミステリー性の高さも通底しています。

　先ほど勘違いから遡った弁護士ばびろん、のタイムラインで目にしたツイートとリツイートをいくつかご紹介したいと思います。目的の一つは弁護士業界のミステリー性に光を当てることです。そこには弁護士という人間に共通した人格的問題性、あるいは病理的な徴候があると考えます。

2016-10-02　日曜日　11：37　＜＜ ［［　←これまでの記述範囲の終了時刻］］＜＜
**** 2016年8月15日から遡る、その名を「弁護士ばびろん」のツイート、リツイートに見る弁護士業界の怪奇的ミステリー性と社会的影響

:CATEGORIES: 名誉毀損の刑事告訴における具体的相談に先立ち、珠洲警察署に提出する準備書面
:TAGS: 弁護士ばびろん,弁護士業界

2016-10-03　月曜日　07：19　＞＞ ［［　←これからの記述範囲の開始時刻］］＞＞

　昨日になりますが、久しぶりに使った自作のスクリプトで、弁護士ばびろん、のツイートをAPIで可能な限り取得しました。実行したコマンドは次になります。

% for x in {1..16};do h-api-twitter-user_timeline-format.rb mackckckck 200 $x >> t.txt; done

　ファイル名は次のように変更しました。

% mv t.txt mackckckck（弁護士ばびろん）_20151020-20161002.txt

　余り信頼のおけないやり方ですが、次のコマンド操作で確認したところ、3094件のツイートを取得できたようです。

% grep '投稿者：mackckckck（弁護士ばびろん） 日時' mackckckck（弁護士ばびろん）_20151020-20161002.txt |wc -l

　同じ作業は、同じく弁護士業界のミステリー性が高い、9月21日以降のツイートの匿名弁護士アカウントにおいても実行しました。取得できたのは、やはり9月21日以降のツイートで、余り信頼のおけない方法で確認したツイート数は672でした。

% for x in {1..16};do h-api-twitter-user_timeline-format.rb nan5o 200 $x >> t.txt; done

% mv t.txt nan5o（でゅーく●―●まんGO）_20160921-20161002.txt

% grep '投稿者：nan5o（でゅーく(●―●)まんGO） 日時：' nan5o（でゅーく●―●まんGO）_20160921-20161002.txt |wc -l

　コマンドの実行で生成したファイルを開いて気がついたことですが、catコマンドで表示したファイルの内容を端末のスクロールでざっと見たところ、リツイートというものが一つも見当たりませんでした。

　やたらとリツイートが多くて、本人のツイートを見つけづらいのが、次の「弁護士浜ちゃん」というアカウントです。こちらは匿名にはなっていますが、リンクを辿るか何かをするとすぐに本人の情報が見つかったことがあります。ローカスこと実質実名弁護士や足立啓太弁護士と同じです。

　完全匿名でミステリー性の高いのは、他に「うの字」という代表格もいますが、鹿児島大学の教授になっている坂本正幸弁護士が、よくリツイートしているので、実在性の高い弁護士で、深澤諭史弁護士もちょくちょくとリツイートしていますし、他の弁護士アカウントも同様です。

ツイート：satoshihamada（浜ちゃん？）：2016/10/02 20:59： https://twitter.com/satoshihamada/status/782550593747378176 ：
引用→　 確かに自分の本業の労力をカバーしてくれる勤務医とか勤務弁護士がいないと本当に大変だと思う。

　今見ると、いつの間にかプロフィールの名前を変更していたらしく、プロフィールにも弁護士という肩書は見当たらなくなっています。プロフィールの写真は以前のままで、スーツに弁護士バッチをつけた顔写真です。次にスクリーンショットを撮っておきます。

投稿者：s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2016-10-03 07:50  ツイート： https://twitter.com/s_hirono/status/782714373349388289
2016-10-03-075018_浜ちゃん？（@satoshihamada）さん　｜　Twitterからの返信付きツイート.jpg https://t.co/50sxv7WUmD

　今、スクリーンショットの実行をして気がついたのですが、タブに開いたページにテレビの番組情報があり、昨夜、20時過ぎの途中からになりましたが、世界法廷ミステリーという番組をみていたことを思い出しました。

　番組情報のページには「緊急SP!20世紀最も衝撃を受けた大逆転判決!封印20年間…英雄OJシンプソンの“殺人告白"本人インタビュー映像を日本で初公開!知られざる裁判の真実」と紹介されています。

　そういえば番宣をみていたことを思い出しましたが、今夜の放送であることは頭になく、確か、大河ドラマの録画に失敗したことで、気がついたのです。

　大河ドラマの真田丸は、ほとんど見ていませんが、終盤に差し掛かっていて、土曜日の再放送を少し見て、今夜はしっかり見るつもりになったところで、録画予約の進行が００：００のままになっていることに気が付きました。ディスク容量が一杯になっていたようで、これまでに何度か経験のあることです。

　大河ドラマが始まる前は、同じNHKでアメリカ大陸のビーバーの生態を興味深く見ていました。そのままNHKで大河ドラマをみるつもりでいたのですが、ふとしたハプニングで、世界法廷ミステリーを見ることとなりました。

　番組を見ている時も全く気が付かなかったのですが、さきほどのスクリーンショットがきっかけで気がついたことは、昨日あたりから弁護士ばびろん、のことで「弁護士業界のミステリー性」という言葉を使い始めたのと、重なっていたということです。

　時刻は９時48分になっています。それでは予定通り、2016年8月15日の弁護士ばびろん、のツイートからタイムラインを遡って、弁護士業界の歴史の一ページとなるようなツイートを記録とともにご紹介したいと思います。

ツイート：mackckckck（弁護士ばびろん）：2016/08/15 16:52： https://twitter.com/mackckckck/status/765093852164214784 ：
引用→　 高校で弁護士について話をするが、次の話をする予定＜改行＞1.6・7年大学に所属。学費の面倒は自分自身、金がなければ借金。＜改行＞2.司法試験合格後、金がなくても働けない。1年間借金。＜改行＞3.弁護士1年目の所得は300万円程度。ここから1.2.の借金を返す。＜改行＞4.金銭的には誰も助けてくれない。

リツイート：mackckckck（弁護士ばびろん）＞2016/08/15 22:40／2016/08/15 14:46＞ https://twitter.com/mackckckck/status/765181324827254784 ＞
 akira83583063 （akira(田舎弁護士)）＞ https://twitter.com/akira83583063/status/765062193108819968 ＞
引用＞　 あと、「弁護士は(経験等は全く関係なく)有能、万能だから、企業や自治体が採るでしょうしそうすべきだ。就職難も一気に解消。」という発想がある日弁連の一部も完全にバカだと思う。 https://t.co/sCDKYsF0xv 

ツイート：mackckckck（弁護士ばびろん）：2016/08/15 22:52： https://twitter.com/mackckckck/status/765184342612058112 ：
引用→　 情報を持っていない消費者は、質の良し悪しを判断できず、結局、ホームページなどで『見た目の良い』弁護士を選択することになる。＜改行＞＜改行＞一部の弁護士は、この情報の非対称性につけこんで広告をバンバン打ちまくり依頼を獲得する。弁護士のスキルなど二の次である。

リツイート：mackckckck（弁護士ばびろん）＞2016/08/16 12:06／2016/08/14 21:08＞ https://twitter.com/mackckckck/status/765384259091652610 ＞
 uwaaaa （サイ太）＞ https://twitter.com/uwaaaa/status/764795734004600832 ＞
引用＞　 今回はいつも以上に『Twitter見てます！』と申し出ていただく方が多かったです。最近は法テラスに対する愚痴ばかりでごめんなさい、もう少し読み手のことを考えます(&gt;_&lt;) 

ツイート：mackckckck（弁護士ばびろん）：2016/08/16 17:26： https://twitter.com/mackckckck/status/765464804148424705 ：
引用→　 刑事の否認事件は常に持っていたいですね。感覚が研ぎ澄まされます。

リツイート：mackckckck（弁護士ばびろん）＞2016/08/17 20:16／2016/08/17 19:19＞ https://twitter.com/mackckckck/status/765869859859116032 ＞
 uwaaaa （サイ太）＞ https://twitter.com/uwaaaa/status/765855483747966976 ＞
引用＞　 なにが「夢構想プロジェクトチーム」「夢実践部会」だよ。ベテランがさっさとハッピーリタイア（以下，「成仏」という。）して顧客を引き渡すのが若手弁護士の夢に決まってんだろ。さっさとクソベテランを成仏させろや。アホか。 

リツイート：mackckckck（弁護士ばびろん）＞2016/08/18 18:29／2016/08/18 12:59＞ https://twitter.com/mackckckck/status/766205398386745344 ＞
 uwaaaa （サイ太）＞ https://twitter.com/uwaaaa/status/766122385682477058 ＞
引用＞　 「企業法務やりたいです！」っていう新人に，弁護士の言うことすら聞かない顧問先のワンマン社長をあてがって発狂させたい 

リツイート：mackckckck（弁護士ばびろん）＞2016/08/18 22:40／2016/08/18 17:45＞ https://twitter.com/mackckckck/status/766268648004517889 ＞
 motoken_tw （モトケン）＞ https://twitter.com/motoken_tw/status/766194347289128960 ＞
引用＞　 弁護士や有識者たちは、虚偽自白による冤罪を防ぐために取調べの完全可視化、つまり、最初から最後までの全ての録音録画を要求しており、その要求自体は正しいと思うが、取調べに問題があるか否か、どんな問題が潜んでいるかを確認するためには、弁護士が全ての録音録画を確認する必要がある。 

リツイート：mackckckck（弁護士ばびろん）＞2016/08/19 11:01／2016/08/19 10:56＞ https://twitter.com/mackckckck/status/766455059915771904 ＞
 fukazawas （深澤諭史）＞ https://twitter.com/fukazawas/status/766453634292789248 ＞
引用＞　 弁護士が，特に経済の分野等で「規制緩和で●●すれば，みんな幸せ！」みたいな議論に反発するのは，政治的信条というよりも，＜改行＞「安易に無意識に都合の良い条件や前提，仮定を入れてはいけない」ということを，事実認定の基本中の基本として，教育課程等で徹底的にたたき込まれてきたからだと思う。 

ツイート：mackckckck（弁護士ばびろん）：2016/08/19 11:04： https://twitter.com/mackckckck/status/766455809706299392 ：
引用→　 海外の弁護士って日本の弁護士みたいに死ぬほど働いてるのかな？

ツイート：mackckckck（弁護士ばびろん）：2016/08/23 20:18： https://twitter.com/mackckckck/status/768044625869144064 ：
引用→　 背景には弁護士の所得の低下があるにもかかわらず、若手弁護士からも金を支払わせて見舞金制度を作りますです。＜改行＞＜改行＞弁護士着服被害に見舞金　不正相次ぎ日弁連が制度創設へ：朝日新聞デジタル https://t.co/lUS2fzxGCx

リツイート：mackckckck（弁護士ばびろん）＞2016/08/25 07:57／2016/08/24 10:27＞ https://twitter.com/mackckckck/status/768583073021566977 ＞
 fukazawas （深澤諭史）＞ https://twitter.com/fukazawas/status/768258444100968448 ＞
引用＞　 「（俺は高額な給与が保障されているが）大学は赤字だから利権じゃない」＜改行＞ってやつですか（汗）＜改行＞でも，気持ちも理解できて「法曹界の大惨事と引換えに自分はポストをゲット」した後ろめたさが，そういう逆ギレを引き起こすのではないでしょうか。＜改行＞https://t.co/0Bm33UBiGO 

リツイート：mackckckck（弁護士ばびろん）＞2016/08/25 13:21／2016/08/25 12:06＞ https://twitter.com/mackckckck/status/768664665110884352 ＞
 uwaaaa （サイ太）＞ https://twitter.com/uwaaaa/status/768645653866041346 ＞
引用＞　 法テラスは弁護士や被援助者への対応は「どうせコイツら悪いことするだろ」という性悪説でやりながら，同じ口で弁護士や被援助者に「安い報酬だけどちゃんとやるよね＾＾」「償還金は約束どおり払うでしょ＾＾」という性善説を求めるからマジでクソ 

ツイート：mackckckck（弁護士ばびろん）：2016/08/25 21:55： https://twitter.com/mackckckck/status/768793936924028928 ：
引用→　 24時間テレビという『チャリティー番組』ですら出演料が支払われるというのに、弁護士だけが成仏しろって？そりゃないぜー（無理矢理）。＜改行＞＜改行＞外国人も呆れる″エセチャリティ″『24時間テレビ』最大の過ちとは #ldnews https://t.co/akE1EqzpML

リツイート：mackckckck（弁護士ばびろん）＞2016/08/26 19:54／2016/08/26 07:06＞ https://twitter.com/mackckckck/status/769125987162259456 ＞
 hoshimasahide （弁護士　星　正秀@tokyo）＞ https://twitter.com/hoshimasahide/status/768932540363120641 ＞
引用＞　 しかし、強姦被疑者の母親の自宅を取材する必要があるのか。＜改行＞単なる公開リンチ。 

ツイート：mackckckck（弁護士ばびろん）：2016/08/28 16:45： https://twitter.com/mackckckck/status/769803189491146752 ：
引用→　 弁護士を増やせば弁護士間の競争が生まれ、その結果サービスの質が上がるという議論について、現状との関係でどのように考えますか？

リツイート：mackckckck（弁護士ばびろん）＞2016/08/29 20:40／2016/08/29 18:23＞ https://twitter.com/mackckckck/status/770224681962004480 ＞
 k_sawmen （泥濘大魔王サイケ）＞ https://twitter.com/k_sawmen/status/770190097065005056 ＞
引用＞　 司法修習生こんだけ虐げられてるんだし薬物濫用くらいは許されてしかるべき感ある 

リツイート：mackckckck（弁護士ばびろん）＞2016/08/29 22:24／2016/08/29 18:44＞ https://twitter.com/mackckckck/status/770250890728968192 ＞
 uwaaaa （サイ太）＞ https://twitter.com/uwaaaa/status/770195378268278784 ＞
引用＞　 おい，財務省さんよ，法テラスが裏技扱いされてるぞ。弁護士が国選報酬の抜け穴を指南するの以上に問題だろ。さっさと動け。ほら早く https://t.co/NYzetKxmpz 

ツイート：mackckckck（弁護士ばびろん）：2016/08/30 22:57： https://twitter.com/mackckckck/status/770621506111930369 ：
引用→　 3時間かけて刑事の打ち合わせ期日に行ったが、法テラスから数千円支払われるだけらしいです

　時刻は10時48分です。今しがた、告発-金沢地方検察庁御中_ツイッター（@kk_hirono）のアカウントにおいて、刑裁サイ太にブロックされていることを確認しました。一月近く前になるように思いますが、その時は刑裁サイ太の方から同じアカウントにフォローがありました。

　次がスクリーンショットになります。

投稿者：s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2016-10-03 10:47  ツイート： https://twitter.com/s_hirono/status/782759056398098432
2016-10-03-104751_ブロックされているため、@uwaaaaさんのフォローや@uwaaaaさんのツイートの表示はできません。詳細はこちら.jpg https://t.co/zklbmNzlzw

ツイート：mackckckck（弁護士ばびろん）：2016/08/31 14:35： https://twitter.com/mackckckck/status/770857613751750658 ：
引用→　 若手弁護士は土日も休まず忙しく働くものだよ。そうやって一人前になるんだよ。私も周りも皆そうやって育ったんだ。＜改行＞＜改行＞との理屈は『高収入である』という重大な前提条件が抜け落ちてしまうと、ただのブラック職業ですからね。

ツイート：mackckckck（弁護士ばびろん）：2016/09/02 23:16： https://twitter.com/mackckckck/status/771713332684349440 ：
引用→　 両親にお金がなければ、1000万円近くの借金をかかえることになるんだよ。＜改行＞ストレートで大学院を卒業するころには24・25歳。研修を経て仕事開始が27歳くらいかな。＜改行＞27歳から働き出して年300万円代の所得。夜遅い仕事、残業代はつかない。＜改行＞さーて、だれが弁護士になりますか？

リツイート：mackckckck（弁護士ばびろん）＞2016/09/02 23:16／2016/09/02 17:57＞ https://twitter.com/mackckckck/status/771713381145260032 ＞
 uwaaaa （サイ太）＞ https://twitter.com/uwaaaa/status/771633194126880769 ＞
引用＞　 日本司法足引っ張りセンターに改名しろ 

リツイート：mackckckck（弁護士ばびろん）＞2016/09/03 00:13／2016/09/02 23:23＞ https://twitter.com/mackckckck/status/771727709080735748 ＞
 kotadon （こたんせ～君が落ち着け）＞ https://twitter.com/kotadon/status/771715150814392320 ＞
引用＞　 しかし、当職にオファーするとは、このアカウントは某テラスにばれていないｗ 

リツイート：mackckckck（弁護士ばびろん）＞2016/09/03 11:52／2016/09/02 23:38＞ https://twitter.com/mackckckck/status/771903705981464576 ＞
 IcyFumin （軍所総監督フミン）＞ https://twitter.com/IcyFumin/status/771718885112291328 ＞
引用＞　 法科大学院発足当初は、法曹同士の市場における競争によって法曹の質が高まるとか言ってたよな。法科大学院制度の正当化根拠の一つである市場原理の帰結が今の現状ですよ？ 

ツイート：mackckckck（弁護士ばびろん）：2016/09/03 21:22： https://twitter.com/mackckckck/status/772047026125012992 ：
引用→　 将棋も人生も『損して得取れ』が重要。＜改行＞歩を突いて飛車や金をとることができればそれが良い。＜改行＞大学受験に時間とお金をかけて努力する人がいるのも、そのほとんどが将来待っている安心した生活（好待遇の仕事）があるから。＜改行＞＜改行＞『損して得なし』のロースクールや司法制度改革は失敗したといえるね。

ツイート：mackckckck（弁護士ばびろん）：2016/09/04 21:31： https://twitter.com/mackckckck/status/772411800339873793 ：
引用→　 弁護士って残業するの普通じゃん？＜改行＞それって単価が低いってことを意味するんじゃないのかな？

ツイート：mackckckck（弁護士ばびろん）：2016/09/06 23:27： https://twitter.com/mackckckck/status/773165700831522816 ：
引用→　 司法試験合格者のみなさん。おめでとうございます。＜改行＞成仏の階段上る君はまだシンデレラさ。＜改行＞＜改行＞ここからもっと法律は面白くなるよ(^o^)

リツイート：mackckckck（弁護士ばびろん）＞2016/09/07 01:34／2016/09/06 23:02＞ https://twitter.com/mackckckck/status/773197649239379968 ＞
 Route66_LP3 （ルート６６（元ルパン３世））＞ https://twitter.com/Route66_LP3/status/773159485397274628 ＞
引用＞　 日弁連という団体がなぜこんなにも無能かというと、弁護士の立場も活動家みたいな左の先生からビジネスロイヤーまで立場と利害が一致しないものだから、団体としてのコンセンサスがとれないんだよね。そして今後はますます多様化していくから、機能不全になって動かざること山のごとしになる総本山。

リツイート：mackckckck（弁護士ばびろん）＞2016/09/07 10:23／2016/09/07 08:12＞ https://twitter.com/mackckckck/status/773330839937495040 ＞
 okumuraosaka （児童ポルノ児童買春・強制わいせつ弁護人）＞ https://twitter.com/okumuraosaka/status/773297778931798017 ＞
引用＞　 裁判官の言うとおりにやるんなら、弁護人いらんやろ。　進行とか判決とかを無理言って被告人に有利な方に引っ張ってくるのが弁護人の仕事やから。 https://t.co/vl2zgaMCkZ 

リツイート：mackckckck（弁護士ばびろん）＞2016/09/07 12:40／2016/09/07 12:23＞ https://twitter.com/mackckckck/status/773365220655849472 ＞
 take___five （take-five）＞ https://twitter.com/take___five/status/773360957586153473 ＞
引用＞　 弁護士の法テラスへの怒りは弁護士以外にわかりづらいと思うけど、喩えると、売上に比例した歩合給の会社員で、顧客のクレーム対応したら「売上に貢献してないから歩合0な」とか、商品のプレゼンがうまくいって多く売り上げたら「プレゼンじゃなく商品が良かっただけだから歩合0な」と言われる感じ。 

リツイート：mackckckck（弁護士ばびろん）＞2016/09/07 21:01／2016/09/07 18:45＞ https://twitter.com/mackckckck/status/773491261562957825 ＞
 talo_kono （甲野太郎）＞ https://twitter.com/talo_kono/status/773457246433009666 ＞
引用＞　 このままでは、テラスの仕事は市場で食いはぐれた弁護士の掃き溜めになってしまう。＜改行＞安かろう悪かろうでも、自己破産の代理と国選の認め事件くらいなら回るのかも知れないけれど。＜改行＞そんなために制度設計したのかい。＜改行＞＜改行＞あとは依頼人の幸運を祈り、弁護士性善説に賭けるのだろうか、法テラス。 

リツイート：mackckckck（弁護士ばびろん）＞2016/09/07 21:01／2016/09/07 18:45＞ https://twitter.com/mackckckck/status/773491299416616960 ＞
 talo_kono （甲野太郎）＞ https://twitter.com/talo_kono/status/773457182838906880 ＞
引用＞　 法テラスが民事法律扶助や国選で有力な弁護士を確保し続けるためには、市場で多くの弁護士から＜改行＞「法テラスの仕事は割に合う」＜改行＞「ぜひ法テラスの仕事をやりたい」＜改行＞と評価される必要がある。＜改行＞＜改行＞だが、そんな声を聞いたことはただの一度もない。誰からもない。＜改行＞僕自身も感じたことはない。 

リツイート：mackckckck（弁護士ばびろん）＞2016/09/07 21:01／2016/09/07 12:26＞ https://twitter.com/mackckckck/status/773491372154249217 ＞
 kamatatylaw （高橋雄一郎）＞ https://twitter.com/kamatatylaw/status/773361765060968449 ＞
引用＞　 法テラス批判は（１）弁護士が利益を出しにくいほどの低額の料金体系で，（２）頑張って成果を出しても十分な報酬増額がなく，（３）報告や請求等で不必要と思われる過度な書類作業が要求される，という点に集約されるのだろうかな。 

リツイート：mackckckck（弁護士ばびろん）＞2016/09/07 21:01／2016/09/07 08:41＞ https://twitter.com/mackckckck/status/773491420657098752 ＞
 kamatatylaw （高橋雄一郎）＞ https://twitter.com/kamatatylaw/status/773305113985232896 ＞
引用＞　 被告人「先生、早くボクをここから出してください」＜改行＞弁護人「私は裁判官に怒られるのが怖いので、裁判官にはなにも要求できないんです。2週間ぐらい中で頑張ってもらえませんか？」 

リツイート：mackckckck（弁護士ばびろん）＞2016/09/07 21:47／2016/09/07 14:46＞ https://twitter.com/mackckckck/status/773502880816824320 ＞
 harrier0516osk （向原総合法律事務所　弁護士向原）＞ https://twitter.com/harrier0516osk/status/773397109177520128 ＞
引用＞　 法テラスのイメージ＜改行＞ある人が洋服屋を営んでいました。値段は1万円です。＜改行＞その隣に、税金＋洋服屋が毎月払ってる商店会費を用いた、デカイ洋服店ができました。商品は同じ、値段は3000円です。宣伝しまくり。＜改行＞そして、今まで売ってた1万円の洋服も、3000円で売るよう求められましたとさ。 

リツイート：mackckckck（弁護士ばびろん）＞2016/09/07 22:40／2016/09/07 22:09＞ https://twitter.com/mackckckck/status/773516311603220481 ＞
 mstk_Horiguchi （ほりぐち）＞ https://twitter.com/mstk_Horiguchi/status/773508473833213952 ＞
引用＞　 さすがに法テラスを受任するからいけないという人はいない。法テラスへの不満の一つには報酬が安すぎることがあるのは間違いない。＜改行＞でも同じ口で他の事務所の報酬が高いと不満言ってるのはいかがなものかのう 

リツイート：mackckckck（弁護士ばびろん）＞2016/09/07 22:42／2016/09/07 22:18＞ https://twitter.com/mackckckck/status/773516688964751362 ＞
 luckymangan （リーチ一発ツモ裏１）＞ https://twitter.com/luckymangan/status/773510862669688836 ＞
引用＞　 法科大学院の教育効果を、法科大学院の教授卒業生自体が否定してるのだから、法科大学院制度又は当該大学院を廃止すべきではないですかね？不存在の教育効果に対して、税金から補助金支払う正当性は、どこにあるのでしょうかね？ https://t.co/fpaWjJOxsq 

ツイート：mackckckck（弁護士ばびろん）：2016/09/07 22:47： https://twitter.com/mackckckck/status/773517994399977472 ：
引用→　 法科大学院は要らない。＜改行＞理念は素晴らしいが現場が理念を実現できない。＜改行＞＜改行＞学生の頭は司法試験合格でいっぱいであり法学の探求ではない。＜改行＞教授の頭は法学研究でいっぱいでありソクラティックメソッドなどできない。

リツイート：mackckckck（弁護士ばびろん）＞2016/09/07 23:17／2016/09/07 22:59＞ https://twitter.com/mackckckck/status/773525586668945408 ＞
 ekinan_lawyer （えきなんローヤー）＞ https://twitter.com/ekinan_lawyer/status/773521129306677248 ＞
引用＞　 チャリラーン、成仏廃業〜♫＜改行＞＜改行＞うそっ。75歳ぐらいまで細く長くやる。 

リツイート：mackckckck（弁護士ばびろん）＞2016/09/10 16:49／2016/09/10 15:56＞ https://twitter.com/mackckckck/status/774515011699945472 ＞
 sollamame （そらまめbot）＞ https://twitter.com/sollamame/status/774501728485904385 ＞
引用＞　 「法科大学院修了生は年齢の割に一般常識に欠ける人が多いという傾向がある」って、そりゃロースクール修了生の全員が当職のように品位や一般常識を備えた人物なわけありませんからね。うむ。 

リツイート：mackckckck（弁護士ばびろん）＞2016/09/10 17:26／2016/09/10 17:00＞ https://twitter.com/mackckckck/status/774524507578994688 ＞
 _hznf_ （hznf）＞ https://twitter.com/_hznf_/status/774517926141374464 ＞
引用＞　 法科大学院は「かけがえのない人生を生きる人々の喜びや悲しみに対して深く共感しうる豊かな人間性の涵養、向上を図る」というのが教育理念なので（司法制度改革審議会意見書58p)，「法科大学院修了生は年齢の割に一般常識に欠ける人が多いという傾向がある」と言われるのは極めて深刻な事態では 

リツイート：mackckckck（弁護士ばびろん）＞2016/09/12 23:22／2016/09/12 21:18＞ https://twitter.com/mackckckck/status/775338818568192001 ＞
 bengoshi_black （ＫＢブラック）＞ https://twitter.com/bengoshi_black/status/775307623126085632 ＞
引用＞　 お金無い人のために法テラスが弁護士費用を貸し付けるのは良い＜改行＞＜改行＞問題は、なぜ、そこで弁護士費用の金額を下げることになるのか、だ 

リツイート：mackckckck（弁護士ばびろん）＞2016/09/12 23:30／2016/09/12 22:09＞ https://twitter.com/mackckckck/status/775340749705519104 ＞
 uwaaaa （サイ太）＞ https://twitter.com/uwaaaa/status/775320504706015232 ＞
引用＞　 法テラス「弁護士費用を支払えない人のために費用を立て替えます」←わかる＜改行＞法テラス「一括で支払うのは大変なので，分割払いでの償還とします」←わかる＜改行＞法テラス「弁護士費用の基準は一般的な基準よりも安くします」←は？ 

リツイート：mackckckck（弁護士ばびろん）＞2016/09/13 13:48／2016/09/13 00:56＞ https://twitter.com/mackckckck/status/775556660408442880 ＞
 chopitarou （はよせな）＞ https://twitter.com/chopitarou/status/775362466112954371 ＞
引用＞　 京都大学ロースクールには、毎年司法試験終わって持ち帰った司法試験用六法に、セクシー女優の握手会行ってサインもらって自習室に奉納するという、笠井センセとかがバチ切れしそうな伝統行事が存在してるんやけど、今年は誰のサインやったんやろな。誰かエロい京大ロー生報告してけろ 

リツイート：mackckckck（弁護士ばびろん）＞2016/09/15 00:46／2016/09/14 23:10＞ https://twitter.com/mackckckck/status/776084650024275968 ＞
 sonoda_hisashi （園田寿）＞ https://twitter.com/sonoda_hisashi/status/776060493567885312 ＞
引用＞　 被疑者被告人の〈推定無罪〉を強調することは、決して被害者を疎かにすることではない。〈被疑者・被告人vs被害者〉といった二項対立で犯罪の問題を考えることは、問題解決の枠を狭めることになると思う。 

リツイート：mackckckck（弁護士ばびろん）＞2016/09/15 21:42／2016/09/15 20:25＞ https://twitter.com/mackckckck/status/776400733084131330 ＞
 1961kumachin （中村元弥）＞ https://twitter.com/1961kumachin/status/776381318116487168 ＞
引用＞　 法テラスから、旅費等請求書の書式変更のファックスが入っているが、宿泊費の請求に目的地滞在時間や打ち合わせ終了時間など細かい時間を分単位で書かせる書式になっているので、不評疑いなし 

リツイート：mackckckck（弁護士ばびろん）＞2016/09/16 07:49／2016/09/15 20:47＞ https://twitter.com/mackckckck/status/776553565783400448 ＞
 un_co_the2nd （うのじ）＞ https://twitter.com/un_co_the2nd/status/776387012735578113 ＞
引用＞　 法テラスは市場原理により淘汰されて成仏するがよろしい 

リツイート：mackckckck（弁護士ばびろん）＞2016/09/16 23:10／2016/09/16 16:49＞ https://twitter.com/mackckckck/status/776785339255881729 ＞
 fukazawas （深澤諭史）＞ https://twitter.com/fukazawas/status/776689459571990528 ＞
引用＞　 今の制度だと、＜改行＞ほぼいきなり実務修習→耕していない畑に種をそのままぶちまける＜改行＞集合修習→ろくに育つ時間を与えられていない作物をそのまま収穫＜改行＞ということになってしまっている。 

リツイート：mackckckck（弁護士ばびろん）＞2016/09/16 23:23／2016/09/16 16:23＞ https://twitter.com/mackckckck/status/776788502495191041 ＞
 pilori1616 （阿野寛之）＞ https://twitter.com/pilori1616/status/776682815152795648 ＞
引用＞　 ある重大事件の国選弁護人をしている知り合いの弁護士から、「裁判の初日、裁判所に停めていた自分の車に傷を付けられた」とのこと。わざとかどうかは不明ですが、弁護人だからという理由でそんな目に遭ったのだとしたら、本当に許せんことです。 

リツイート：mackckckck（弁護士ばびろん）＞2016/09/16 23:36／2016/09/16 19:06＞ https://twitter.com/mackckckck/status/776791942206140417 ＞
 motoken_tw （モトケン）＞ https://twitter.com/motoken_tw/status/776723959224033280 ＞
引用＞　 ツイッターの世界には、マスコミの記者より頭が良くて、記者より専門知識がある人がいっぱいいるから、マスコミが太刀打ちできない部分があることは当然といえば当然。 

リツイート：mackckckck（弁護士ばびろん）＞2016/09/18 17:48／2016/09/18 10:50＞ https://twitter.com/mackckckck/status/777428966508331009 ＞
 harrier0516osk （向原総合法律事務所　弁護士向原）＞ https://twitter.com/harrier0516osk/status/777323851466223616 ＞
引用＞　 法科大学院制度の功績はとても大きいと思います。＜改行＞国策というのはこうやって動くのだなということと、自治を誇る弁護士業界でさえも、国策によって、このようにいとも簡単にブッ壊されるのだなということがよくわかって、勉強になりま https://t.co/zK4BjFA76y 

リツイート：mackckckck（弁護士ばびろん）＞2016/09/18 17:48／2016/09/18 10:56＞ https://twitter.com/mackckckck/status/777428983684018176 ＞
 Route66_LP3 （ルート６６（元ルパン３世））＞ https://twitter.com/Route66_LP3/status/777325352313991168 ＞
引用＞　 あとは自治を名実ともに剥奪すれば完成 https://t.co/iakJKNiXKS 

リツイート：mackckckck（弁護士ばびろん）＞2016/09/18 19:01／2016/09/18 18:56＞ https://twitter.com/mackckckck/status/777447508159062016 ＞
 _hznf_ （hznf）＞ https://twitter.com/_hznf_/status/777446154288062464 ＞
引用＞　 弁護士自治不要論が内部でもそれなりに支持を得つつあるようなのを見ると，司法改革・弁護士大増員の真の目的は達成されつつあるのだろう 

リツイート：mackckckck（弁護士ばびろん）＞2016/09/19 10:15／2016/09/19 10:06＞ https://twitter.com/mackckckck/status/777677474805059584 ＞
 fukazawas （深澤諭史）＞ https://twitter.com/fukazawas/status/777675256462835712 ＞
引用＞　 法テラスが懲戒権を握るとか，悪夢としか思えないな。＜改行＞とりあえず，法クラはほぼ全員粛清されそうだ＜改行＞（・∀・；） https://t.co/bzfRirtgI2 

リツイート：mackckckck（弁護士ばびろん）＞2016/09/19 10:19／2016/09/19 10:15＞ https://twitter.com/mackckckck/status/777678571800104960 ＞
 sakamotomasayuk （坂本正幸）＞ https://twitter.com/sakamotomasayuk/status/777677533458288640 ＞
引用＞　 @mackckckck 弁護士ではない人に会費の話をするとたいてい「そのくらいの年会費ならやすいじゃないですか」「いや月なんで」という会話が必ず交わされいやでも思い出します 

リツイート：mackckckck（弁護士ばびろん）＞2016/09/19 20:49／2016/09/19 15:23＞ https://twitter.com/mackckckck/status/777837030143168512 ＞
 minami_kazuyuki （みなみかずゆき）＞ https://twitter.com/minami_kazuyuki/status/777754887857643520 ＞
引用＞　 日弁連の「人権大会」に行ったことが一度もない。興味ないし，時間ないし，交通宿泊費もったいないし。自営業者として売上げ増加に繋がるインセンティブもない。勤労者として休暇といえるほど癒やされるとも思えない。＜改行＞＜改行＞「法テラス廃止宣言」「法科大学院廃止宣言」するなら這ってでも行く。 

リツイート：mackckckck（弁護士ばびろん）＞2016/09/21 19:50／2016/09/21 14:21＞ https://twitter.com/mackckckck/status/778546987964641280 ＞
 Hideo_Ogura （小倉秀夫）＞ https://twitter.com/Hideo_Ogura/status/778464174821158912 ＞
引用＞　 高橋宏志先生と貧乏ロースクール生とが入れ替わる「君の名は─成仏編」を作ったら、受けるのではなかろうか。 

ツイート：mackckckck（弁護士ばびろん）：2016/09/29 16:27： https://twitter.com/mackckckck/status/781394890752090112 ：
引用→　 被害者給付金制度は、弁護士に対する社会の信頼を回復するためには欠かせない。

ツイート：mackckckck（弁護士ばびろん）：2016/09/29 16:27： https://twitter.com/mackckckck/status/781394961279307780 ：
引用→　 @mackckckck んなわけないでしょ。

ツイート：mackckckck（弁護士ばびろん）：2016/10/01 13:13： https://twitter.com/mackckckck/status/782070843631243265 ：
引用→　 弁護士も同じ。＜改行＞日本には知識や技能に対価を払う意識が欠如している気がいる。＜改行＞知ってるなら教えてよ、と。＜改行＞話しただけだから特に労力なかったでしょ、と。 https://t.co/8WDa6UEWDN

リツイート：mackckckck（弁護士ばびろん）＞2016/10/01 21:20／2016/09/29 10:57＞ https://twitter.com/mackckckck/status/782193431221108737 ＞
 nkaoguo （Kay）＞ https://twitter.com/nkaoguo/status/781311917050691584 ＞
引用＞　 否認事件の謄写費用を「厘」の単位まで算出して根拠資料付けて請求した件、10日以上経つのに法テラスから全く回答がない。自分たちは報告書の期限にうるさいくせに、相変わらずクソみてえな奴らだ。 

リツイート：mackckckck（弁護士ばびろん）＞2016/10/01 21:20／2016/09/28 16:15＞ https://twitter.com/mackckckck/status/782193495574405120 ＞
 taniyama （弁護士 谷山智光）＞ https://twitter.com/taniyama/status/781029534657286144 ＞
引用＞　 無罪費用補償請求の場面でも法テラス基準が足をひっぱる。法テラスは弁護士の首をじわじわ絞めつける制度。 

ツイート：mackckckck（弁護士ばびろん）：2016/10/02 21:22： https://twitter.com/mackckckck/status/782556485351944193 ：
引用→　 たしかに、考えてみればスタッフ弁護士が国選やるのってなんで許容されてるんだろ？ https://t.co/AnuACfrQE7

リツイート：mackckckck（弁護士ばびろん）＞2016/10/02 21:24／2016/09/07 21:29＞ https://twitter.com/mackckckck/status/782556806052589572 ＞
 harrier0516osk （向原総合法律事務所　弁護士向原）＞ https://twitter.com/harrier0516osk/status/773498509760667648 ＞
引用＞　 @take___five しかし、法テラスの弱点は「手足を持たない」こと。＜改行＞なので、法テラスは、各地のスタベンを増やそうとしており、これが完成すると、弁護士自治は名実ともに終焉します。＜改行＞つまり、我々は、「手足」にならないようにするべきだと思っています。 

ツイート：mackckckck（弁護士ばびろん）：2016/10/02 21:39： https://twitter.com/mackckckck/status/782560680956170240 ：
引用→　 スタッフ弁護士＝法務省＜改行＞検察官＝法務省＜改行＞＜改行＞法務省対法務省。 https://t.co/3ALTuerh06

2016-10-04　火曜日　20：37　＜＜ ［［　←これまでの記述範囲の終了時刻］］＜＜
**** 「光市母子殺害事件の時に弁護人に向けられた罵声を思い出します」という小倉秀夫弁護士のツイートと、死刑制度における冤罪問題

:CATEGORIES: 名誉毀損の刑事告訴における具体的相談に先立ち、珠洲警察署に提出する準備書面
:TAGS: 小倉秀夫弁護士,光市母子殺害事件,刑事弁護,再審

2016-10-06　木曜日　10：17　＞＞ ［［　←これからの記述範囲の開始時刻］］＞＞

ツイート：Hideo_Ogura（小倉秀夫）：2016/10/06 02:47： https://twitter.com/Hideo_Ogura/status/783725244766904320 ：
引用→　 それは平然と言えます。RT @K_masafumi: （続き）きっと死刑廃止派の人達は、小学生の娘を殺された母親に「あなたの娘は殺されたが、犯人には生きる権利があるのです」と言えるのだろう。私には、とても言えない。

ツイート：Hideo_Ogura（小倉秀夫）：2016/10/06 02:48： https://twitter.com/Hideo_Ogura/status/783725538460315648 ：
引用→　 光市母子殺害事件の時に弁護人に向けられた罵声を思い出します。RT @K_masafumi: 遺族が死刑を求めるのは当然。（私には）死刑廃止派は、こういう切実な遺族の想いを軽視するものとしか思えない。

ツイート：Hideo_Ogura（小倉秀夫）：2016/10/06 02:49： https://twitter.com/Hideo_Ogura/status/783725813329899521 ：
引用→　 死刑廃止論者に向けられた倫理的な糾弾は、死刑求刑事案の弁護人に対しても同じように向けられ得るんですよ。

ツイート：Hideo_Ogura（小倉秀夫）：2016/10/06 02:51： https://twitter.com/Hideo_Ogura/status/783726315153166336 ：
引用→　 右傾化した若手弁護士たちは、死刑求刑事案でもなお被告人を庇おうとする弁護人たちについて、「弁護士ってああいう奴らだと思われたら困る」と本気で思っているかもしれない。

　上記４つが一連つまり一続きの小倉秀夫弁護士のツイートになっています。

ツイート：Hideo_Ogura（小倉秀夫）：2016/10/06 09:24： https://twitter.com/Hideo_Ogura/status/783825172356747264 ：
引用→　 それまで、人権大会を使って自分たちの理想に沿った決議をさせてきた全ての人々がそうなんですかね。RT @shouwayoroyoro: 私は死刑存置論者だが死刑廃止論者がそれを求めること自体は当然だろうと思う。ただ自分の理想を世に訴えるなら、自分の信用とカネでやれと言いたいのだ。

ツイート：Hideo_Ogura（小倉秀夫）：2016/10/06 09:39： https://twitter.com/Hideo_Ogura/status/783828906142945280 ：
引用→　 法曹系の死刑反対論者の多くは、マジで冤罪の恐怖が死刑反対論の動機になっているんですよ。RT @bwpotato: 死刑に反対の人は、冤罪の場合に取り返しがつかないなんて言わずに、残虐なんだ、国際的に恥ずかしいんだ、自由と比べても命ははるかに重いんだ、と自らの信条で正面から主張した

　上記2つのツイートも連続していますが、10時25分現在において最新の小倉秀夫弁護士のツイートになっています。

　初めの4つのまとまりの小倉秀夫弁護士のツイートは、昨夜に見たように思っていたのですが、読み込んだデータによると本日未明の2時47分から51分の間に投稿されたツイートでした。私は今朝、5時20分ぐらいに目がさめ、それから起きています。昨夜寝た時間というのはほとんど憶えていません。

　昨夜は韓国に大きな被害をもたらした台風18号が、能登半島を通過するということで、能登町においても17箇所の避難所が用意されたとテレビに出ていました。20時から21時辺りが強風のピークだったと思いますが、そのあと風も弱まり、大丈夫そうだと安堵しているうちに眠っていました。

　予報でも20時頃に能登半島に最接近と出ていたように思いますが、18時ころはいったん風もやみ、不気味なぐらいの静けさでした。そんな時に目にしたのが次の深澤諭史弁護士のツイートであり、神様が運んできた宿題のように思えていました。

ツイート：fukazawas（深澤諭史）：2016/10/05 16:18： https://twitter.com/fukazawas/status/783566896368988160 ：
引用→　 強姦再審で無罪、男性が国提訴　公判の違法性訴え：朝日新聞デジタル https://t.co/V2xd9LOMUl＜改行＞「控訴審で弁護側が母娘の証人尋問を求めたが、裁判官は認めず、真相を見逃した」＜改行＞あるある。被告人の立証だけは無茶苦茶に制限されるから見かけ上問題ない事実認定が出来る。

　この大阪の強姦再審事件は、自分の事件や刑事裁判との共通点もあるので、いずれ取り上げておきたいと思っていたのですが、長い間続報もなく、探しだすのも手間が掛かりそうだとタイミングが図りづらかったのですが、深澤諭史弁護士からもたらされた情報として、風の便りのように考えていました。

　昨夜のテレビでは、ちょうど能登半島の辺りで、台風から温帯低気圧に変わりそうだと解説されていましたが、温帯低気圧になると台風の中心部の風速が弱まり強風域の範囲が広がる、ということを初めて知りました。

　この度の台風18号は進路の中心部が能登半島にあって、記憶にある限り、そのような台風の予想図は見たこともなかったのですが、能登半島が本州から飛び出ている分だけ、集中的な大災害になるのではとも、昨日は心配していて、愛知県のおばさんからも夕方に電話がありました。

　光市母子殺害事件といえば安田好弘弁護士ですが、小倉秀夫弁護士は以前、安田好弘弁護士のことを尊敬しているような趣旨のツイートもやっていました。以前まとめたものがあるかと思います。

参考資料：　「安田」と「弁護士」（目的は安田好弘弁護士）をキーワードに含む小倉秀夫弁護士（@Hideo_Ogura）のツイートのまとめ14件（2015年12月30日作成） http://hirono-hideki.cocolog-nifty.com/blog/2015/12/hideo_ogura1420.html

　次のツイートが先頭になっていました。記事の作成の時点で、投稿日時がもっとも新しいツイートのようですが、実行したSQL文が記載されていないので、確かなことはわかりません。

ツイート：Hideo_Ogura（小倉秀夫）：2015/03/01 02:06： https://twitter.com/Hideo_Ogura/status/571718172375568384 ：
引用→　 被疑者段階の氏名の公表で殺人事件が防げるなら、星人による殺人はとっくになくなっているんでしょうね。RT @7J14: 少年法は改正すべき。氏名、本名の公表も。でなきゃ再発防止なんてできない。また、安田とかいう自称人権派糞弁護士が騒ぐんだろうなぁ。

　上記の小倉秀夫弁護士のツイートでは、非公式RTによる引用部分に「安田」とあります。星人というのは成人の誤変換なのかとも思いますが、そのままにしているようですし、あるいは意図的に、そうしたのかもしれないとも考えます。

　Bloggerのブログでは、作成していなかったようです。今から作成しておこうと思います。

　次のようにコマンドを実行してブログの記事のHTMLコードを生成しました。

% tw_user_tweet-sql-search-make-text-html-blogger-style.rb  --full_sql="SELECT * FROM tw_user_tweet WHERE (tweet LIKE '%安田%' AND tweet LIKE '%弁護士%')  AND (user LIKE \"Hideo_Ogura\") ORDER BY tw_date ASC"|xsel -b

参考資料：「安田」と「弁護士」（目的は安田好弘弁護士）をキーワードに含む小倉秀夫弁護士（@Hideo_Ogura）のツイート（18件、 2010-01-19 09:46〜2016-02-24 21:15：2016-10-06の記録）,http://hirono2016k.blogspot.com/2016/10/hideoogura18-2010-01-19-09462016-02-24.html

ツイート：Hideo_Ogura（小倉秀夫）：2010/01/19 09:46： https://twitter.com/Hideo_Ogura/status/7925541640 ：
引用→　 @keroring 新聞等の報道では、安田弁護士が「知恵をつけ」て本人の記憶に反した主張をなさしめたのだとするものはなかったはずですが。

　上記がキーワードの出てくる最初のツイートのようです。他にもいくつかご紹介しておきます。

ツイート：Hideo_Ogura（小倉秀夫）：2010/01/19 11:31： https://twitter.com/Hideo_Ogura/status/7929109742 ：
引用→　 @keroring 安田弁護士を素人なりに評価することは法的には自由ですが、低く評価することを正当化するために虚偽の事実を摘示することは許されていません。

ツイート：Hideo_Ogura（小倉秀夫）：2010/01/24 04:30： https://twitter.com/Hideo_Ogura/status/8121082146 ：
引用→　 @tawashimikan 安田弁護士が「刑反対の思想を広めるために裁判を利用してやりたい方題し」た事実はないはずですが、名誉毀損は犯罪だと知った上でそのような発言をされているのですか？

ツイート：Hideo_Ogura（小倉秀夫）：2010/08/08 12:35： https://twitter.com/Hideo_Ogura/status/20599933399 ：
引用→　 懲戒覚悟で「弁護人としても、被告人を一日も早く死刑に処すべきと思料します」と言わなかった以上バッシングを受けても仕方がないということですね。RT @hirono_hideki: 光市母子殺害事件の安田弁護士らの活動が、与えた影響も大きいという気がします。

ツイート：Hideo_Ogura（小倉秀夫）：2010/08/08 12:46： https://twitter.com/Hideo_Ogura/status/20600619332 ：
引用→　 安田弁護士バッシングって結局そういうことでしょう？RT @hirono_hideki: そういう程度のこと言っていて、商売になるんですか？子供でも判断つきそうです。

ツイート：Hideo_Ogura（小倉秀夫）：2010/09/25 09:12： https://twitter.com/Hideo_Ogura/status/25451553084 ：
引用→　 マスメディアが極悪人と断定した被告人の弁護は手抜きをしなければいけないということですね。自浄作用。RT @terzoterzo: それは難しいかなァ・・・。何せ、あの悪名高き安田好弘が未だ弁護士やってる位だし。日弁連の自浄作用の無さも民主党並に異常だからねェ・・・。

ツイート：Hideo_Ogura（小倉秀夫）：2011/02/19 16:40： https://twitter.com/Hideo_Ogura/status/38865536796327936 ：
引用→　 安田先生を「わけのわからんの」と表現している人には理解されない気はするな。“@molyxyz: もちろん、実際はまともな弁護士がほとんどなんだろうけど、安田弁護士みたいなわけのわからんのがとかく目立ち勝ちだし。”

ツイート：Hideo_Ogura（小倉秀夫）：2011/06/26 17:47： https://twitter.com/Hideo_Ogura/status/84905607391494144 ：
引用→　 ラウドマイノリティであるネトウヨさんを相手に銭儲けをしている人が見当たらない。RT @dead_sengoku: 仙石、枝野、福島瑞穂、安田 好弘、菊田幸一と全ての労組専属弁護士から小倉秀夫まで。弁護士はラウドマイノリティを相手に銭儲けのキチガイと左翼ばかり。

ツイート：Hideo_Ogura（小倉秀夫）：2012/02/21 21:13： https://twitter.com/Hideo_Ogura/status/171930635869491202 ：
引用→　 根拠のない中傷だね。RT @Tube8Aniki: この安田好弘はじめ弁護士団のやつらはそんなことはどうでもよくて、自分たちの掲げる「死刑廃止」を実現するためにこの裁判を利用したんだよな

ツイート：Hideo_Ogura（小倉秀夫）：2012/02/21 21:38： https://twitter.com/Hideo_Ogura/status/171936868567482369 ：
引用→　 どんな迷惑がかかったというのだろう。RT @2seamtoshi: RT @realityofjapan: 安田弁護士って東大かよ。鳩山脱税総理も福島みずほ、東大って頭がいい大学なんじゃないの？なんでこんなに社会に迷惑掛けまくってる人が筆頭に出てくるんだろ。

ツイート：Hideo_Ogura（小倉秀夫）：2012/02/21 21:50： https://twitter.com/Hideo_Ogura/status/171939799312244737 ：
引用→　 被告人を弁護すると社会の敵になるというのなら刑事裁判制度自体を廃止すべきではないかなあ。RT @aniotahosyu: 涙を流し庇った弁護士今枝仁、福田君を絶対に守ると嘯いた弁護士安田好弘、…社会の敵である連中を絶対に忘れてはならない！

ツイート：Hideo_Ogura（小倉秀夫）：2012/03/14 15:56： https://twitter.com/Hideo_Ogura/status/179823257074139137 ：
引用→　 なぜか褒められている。RT @hirono_hideki: かって新宿バス放火事件で意中の判決を得た安田好弘弁護士みたいです。

　死刑制度のことは、かれこれ10日ぐらい経つのでしょうか、法クラや弁護士の間でちょくちょく話題になっていました。弁護士ばびろん、のツイートやリツイートの紹介でもあったように思いますが、日弁連が死刑制度廃止の決議をしたとかで、賛成派らが抗議のようなツイートをやっていました。

　確認のため少し調べておきますが、正式なニュースとしてはネットでも目にしておらず、口コミの話題としか見ていないと思います。

　一つ見つかりました。朝日新聞の記事のようです。会員向け以外の部分を次に引用します。2016年10月3日03時00分が記事の配信時刻のようです。

／＊＊＊＊＊＊＊＊＊＊（引用開始）＊＊＊＊＊＊＊＊＊＊
引用URL＞＞＞＞：http://www.asahi.com/articles/ASJB151MGJB1PTIL00V.html 日弁連、死刑廃止宣言を初提案へ　実現には険しい道のり：朝日新聞デジタル

日本弁護士連合会は７日の人権擁護大会（福井市）で、「２０２０年までの死刑制度廃止」を表明し、宣言案を初めて提出する。相次ぐ冤罪（えんざい）事件の発覚や、制度廃止に向かう世界的な潮流が背景にあるが、死刑容認論も根強く、廃止実現の道のりは険しい。

　日弁連では死刑廃止派が多数を占めるが、犯罪被害者の支援活動をする弁護士らを中心に「存置すべきだ」という容認意見もある。２０１１年の人権擁護大会では「廃止に向けて全社会的な議論を始める」という宣言を出す動きもあったが、被害者感情への配慮から表現を弱めた。

　しかし、これを機に死刑廃止検討委員会が発足。死刑の問題点について議論を深めるため、各地で会員や市民向けのシンポジウムを開催した。遺族らの集会で「自分の家族が殺されても同じことを言えますか」と迫られることもあったが、冤罪は取り返しがつかないなどとして「死刑のない社会」を訴えてきた。

　こうした中、袴田巌さんが死刑…

＊＊＊＊＊＊＊＊＊＊（引用終了）＊＊＊＊＊＊＊＊＊＊／

　引用した部分を見直すと、「日本弁護士連合会は７日の人権擁護大会（福井市）で」となっているので、明日の10月7日になるものと思われますが、明日は金曜日で平日、それで全国から弁護士が福井市に集まるのか疑問に思いました。既に前提条件として、一部の参加であることを見込んでいるようです。

　ともあれ、究極の刑罰である死刑制度と誤判の一種である冤罪を、日弁連が強固に結びつけ同じ問題としていることは、日弁連の最新の動向として確認することが出来ました。

　今、会員向けとなっている部分を開いて読んだところですが、「２０年に世界の刑事司法関係者が集う国連会議の日本開催が決定」と重要と思われることが書いてありました。こういうのもテレビや新聞では報道されないニュースなのかも知れないと思うと、弁護士がますます不思議な存在に想えます。

　記事の締めくくりには「死刑がありうる殺人罪で起訴される事件は減少傾向で、０６年の７３４人から１５年に３５７人になった。」と、これも重要と思われるデータですが、非会員だと見ることの出来ない記事の部分です。なお、私は無料会員登録をしています。

　死刑制度廃止といえば、安田好弘弁護士や光市母子殺害事件のことがマスコミに大々的に報道されていた時期のことを思い出しますが、今では安田好弘弁護士の名前を見ることもなく、午前中に死刑執行のニュースがあっても、夜のニュース番組では報道されていない、という現状も目にしています。

　記事の会員向けの冒頭は、8文字の重なりがありますが、「こうした中、袴田巌さんが死刑とされ、半世紀近く拘束された「袴田事件」の再審開始決定（１４年３月）もあり、日弁連内の風向きは変わっていった。」となっています。

　袴田事件といえば伝説的な冤罪事件ですが、私には、弁護士らが警察の落ち度を利用して捜査を混乱させ、恣意的な手抜き弁護で社会を欺いた黒歴史の悪魔性を象徴する、冤罪という名の事件と思えてなりません。

　死刑囚とされた袴田巌さんは、他の同僚数人と殺人現場の消火活動に従事していたとのことですが、数年前、弁護士らはそれを検察がひた隠しにしていた情報を開示請求で暴き立てた手柄のように報道させていました。

　被疑者段階や公判中に、袴田巌さんの言い分にしっかり耳を傾けていれば、消火活動をしていた同僚の証言なども、表沙汰となり、審理の対象になっていたものと考えられます。

　時刻は10月7日10時45分になっています。さきほど確認したばかりですが、弁護士ばびろん、のプロフィールの名前が弁護士クックなどに変更されていました。ちょっと気になるツイートも見つけたので、ご紹介しておきます。

ツイート：mackckckck（弁護士ワック）：2016/10/06 18:27： https://twitter.com/mackckckck/status/783961827306643456 ：
引用→　 昨日、同期と飲んだんだが、＜改行＞イソ弁「定額働かせ放題！」ノキ弁「明日行くところがないかも」即独「法テラス報告書地獄」だって。＜改行＞＜改行＞弁護士業界カオスモード突入。

　本来、掲載しようとしたツイートは、APIでの読み込みでエラーが出ました。タイムラインには残っているものの削除された可能性がありそうです。スクリーンショットを撮っておきました。ツイートの内容もご紹介します。

投稿者：s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2016-10-07 10:49  ツイート： https://twitter.com/s_hirono/status/784209011306405888
2016-10-07-104927_弁護士をダブルチェックさせればいいのにね。牽制的機能があればかなりの横領は防げると思う。　日弁連は被害者給付金で防げると思ってるのかな。.jpg https://t.co/Bnh5CX1uZs

弁護士ワック ‏@mackckckck 14時間14時間前弁護士ワックさんが時事ドットコムをリツイートしました弁護士をダブルチェックさせればいいのにね。牽制的機能があればかなりの横領は防げると思う。日弁連は被害者給付金で防げると思ってるのかな。

　改行を削除したので読みづらくなっています。なお、弁護士クックではなく弁護士ワックでした。上記の削除されたツイートは、次の記事のURLを含んでおり、その記事の内容を前提にしたものとなるはずです。

　引用されていたURLは、記事を直接示すものではなく、次のツイートとなっていました。これだと見出しのみを見ただけという可能性も出てきそうです。

ツイート：jijicom（時事ドットコム）：2016/10/06 19:52： https://twitter.com/jijicom/status/783983202012569600 ：
引用→　 成年後見人の弁護士逮捕＝１８００万円横領容疑−名古屋地検 https://t.co/sW142ZGjg9

　昨夜は、モトケンこと矢部善朗弁護士（京都弁護士会）や深澤諭史弁護士のツイート数がずいぶんと多くなっていましたが、まだしっかりとは確認していません。モトケンこと矢部善朗弁護士（京都弁護士会）はここ数日、死刑制度の話題が多いようです。独壇場の講義のような感じです。

2016-10-07　金曜日　11：09　＜＜ ［［　←これまでの記述範囲の終了時刻］］＜＜
**** ブロックされていたことを確認した法律クラスタのタイムラインから考えた弁護士業界の宇宙的空間性と本人訴訟の問題

:CATEGORIES: 名誉毀損の刑事告訴における具体的相談に先立ち、珠洲警察署に提出する準備書面
:TAGS: 本人訴訟,弁護士業界,法クラ,ブロック

2016-10-07　金曜日　13：04　＞＞ ［［　←これからの記述範囲の開始時刻］］＞＞

　昨日のことですが、探しだすのに時間がかかりました。ようやく端緒を見つけ出したところですが、きっかけは次の深澤諭史弁護士のツイートを、タイムラインから個別に開いたことでした。

ツイート：fukazawas（深澤諭史）：2016/10/06 13:17： https://twitter.com/fukazawas/status/783883965392224256 ：
引用→　 @agonoumi 呆れて論評する気にもなれませんね。＜改行＞（・∀・；）

　上記の深澤諭史弁護士のツイートは次のツイートへの返信となっていました。

ツイート：agonoumi（阿胡ノ海）：2016/10/06 13:16： https://twitter.com/agonoumi/status/783883672013332480 ：
引用→　 @fukazawas 被疑者弁護も不要と仰っていたような。

　上記の阿胡ノ海というプロフィールの名前のアカウントのツイートは、次の深澤諭史弁護士のツイートへの返信となっているようです。

ツイート：fukazawas（深澤諭史）：2016/10/06 10:31： https://twitter.com/fukazawas/status/783842031881695232 ：
引用→　 法制審特別部会牛耳る「御用学者」 https://t.co/xJYsCZ6y16＜改行＞「椎橋教授は人質司法について「正しい評価かどうか大きな疑問を持っている。身柄拘束するかどうか慎重に対応されている」（今年3月の第25回会議）とまで言った。」＜改行＞＜改行＞さぞ刑事弁護のご経験豊富なのでしょうね

　阿胡ノ海というプロフィールの名前のアカウントのプロフィールは次のようになっています。前に回数は少ないですが、何度か見た憶えのあるアカウントでした。

＜2016年10月07日(金) 13時14分16秒にTwitterAPIで取得したagonoumi（阿胡ノ海）のプロフィール情報＞
広島県呉市在住の弁護士です。事務所は本庁の近くにあります。修習は50期代半ばで合格者が増えて二回試験が気になり出した頃でした。気がつけば地元の同業者もかなり増えてきました。

　広島県呉市在住の弁護士、とあります。どんなツイートをしているのか、少なめでしたがタイムラインを遡っていたところ、見つけたのが次のツイートでした。

リツイート：agonoumi（阿胡ノ海）＞2016/09/30 23:27／2016/09/30 22:05＞ https://twitter.com/agonoumi/status/781863106498539520 ＞
 himaben1st （暇弁＠兼業主夫）＞ https://twitter.com/himaben1st/status/781842413635592192 ＞
引用＞　 これは日弁連と福岡県弁護士会から正式に抗議した方が良いと思う。 https://t.co/aOvZ2tMqV1 

　ツイートではなくリツイートでしたが、そこにある次のツイートのリンクを開いたところ、ブロックされていることに気がついたのです。@hirono_hidekiのアカウントですが、メンション付きでツイートをしたような覚えもなかったので、余計に気になりました。

ツイート：kasumi_shiro（霞 司郎㌥）：2016/09/30 21:20： https://twitter.com/kasumi_shiro/status/781831189636063232 ：
引用→　 福岡県行政書士会のパブ記事、よく見てみたら、「弁護士や司法書士など他士業との仕事の違いはどういうところですか。」の問いに「行政書士は出生届けから遺産相続まで手掛け、弁護士と同じ法律専門職なので、守備範囲が広い。」とある。 https://t.co/K7F4F3JJ3U

　ツイートの内容は数日前に、関連したツイートを多数、深澤諭史弁護士のタイムラインなどで見ていたものでした。霞司郎というプロフィールの名前になっていますが、私がツイッターを始めた2010年の頃から見覚えのあるものでしたが、特に関心もなくブックマークもしたことのないアカウントでした。

　何かよほど思うところがあってブロックをしてきたのだと思いますが、理由はわかりようもないことです。一応、確認ためTwilogで調べておこうと思います。

奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「kasumi_shiro」の検索結果 - Twilog http://twilog.org/hirono_hideki/search?word=kasumi_shiro&ao=a

　実際に調べてみると、＠のついたものがいくつかありました。

ツイート：hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）：2016/05/31 16:07： https://twitter.com/hirono_hideki/status/737541027595096065 ：
引用→　 奉納＼弁護士妖怪大泥棒神社・金沢地方検察庁御中: ＜法クラ！弁護士？＞霞 司郎@kasumi_shiro→　「加藤新太郎が岡口で本人訴訟」これは腹痛... https://t.co/FofWfOmed4

ツイート：hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）：2015/08/20 10:32： https://twitter.com/hirono_hideki/status/634176111191138304 ：
引用→　 ブログ更新： RT @kasumi_shiro: 仮に、当該ビデオが和姦の証拠になるものであり、被害者代理人弁護士との示談交渉において、当該ビデオの存在を告げた上で、和解提案したということだとすると、当該報道から受ける印象とは大... http://t.co/4xnUv5kY7G

ツイート：hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）：2015/07/26 14:31： https://twitter.com/hirono_hideki/status/625176543946534912 ：
引用→　 ブログ更新： 元ツイートを医療界へのパイプを持っている人が拡散すれば良いのでは RT @mayayatomomo: @okaguchik @kasumi_shiro そういうご意見を是非とも医師に届けてください。自分たちの狭い世... http://t.co/BGakoUwF28

リツイート：hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）＞2015/02/02 10:31／2015/01/19 21:38＞ https://twitter.com/hirono_hideki/status/562060721614106624 ＞
 kasumi_shiro （霞 司郎㌥）＞ https://twitter.com/kasumi_shiro/status/557155221357338624 ＞
引用＞　 仮に、当該ビデオが和姦の証拠になるものであり､被害者代理人弁護士との示談交渉において、当該ビデオの存在を告げた上で､和解提案したということだとすると、当該報道から受ける印象とは大分違ってくるなあ…　隠し撮りという問題はあるが、冤罪被害を防ぐための自衛手段だと言われると… 

リツイート：hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）＞2014/03/31 11:08／2014/03/30 21:13＞ https://twitter.com/hirono_hideki/status/450454488860479488 ＞
 kasumi_shiro （霞 司郎㌥）＞ https://twitter.com/kasumi_shiro/status/450244360907390976 ＞
引用＞　 明日、もし飯塚事件で再審請求棄却決定が出たら、担当裁判官にどんな罵声が浴びせられるのか… 

　2015/02/02 10:31のリツイートですが、ずいぶん印象的な内容であったものの、この霞司郎というアカウントのツイートとは記憶に残っていませんでした。名前から実在性が薄いという印象が強く、アニメの世界のキャラクターのようにも感じていました。

　法律家クラスタが何を意味するのか、正確なことはわかりようもないですが、よくよく考えてみると、法廷にあるような木槌のアイコンを見ても、現役の裁判官という可能性もありそうに思えてきました。

　他にも似たようなツイートをする弁護士アカウントはいたので、同様に疑問に思っていましたが、和姦の証拠とするためビデオカメラを用意し、性行為を相手の女性の同意を得ることなく撮影するという行為が、さほどの問題ではなく、被疑者の無罪性こそ優先されるべき、とは凄まじい思考と思いました。

　宮崎の強姦事件の示談交渉の問題ですが、1月17日頃の毎日新聞のネットニュースで一気に話題になったことはよく憶えていますが、割と最近のことに思え、今年のことかと思っていたのですが、どうやら昨年の2015年のことであったようです。

　強姦事件の刑事弁護として、常識での理解をはるかに超えた事例で、弁護士が懲戒請求を受けながら不処分になったことなど、参考になることが多く、告訴状で本格的に取り上げたいと考えてきたのですが、総合的な判断から優先度をさげ、そこには至っておりません。

　あまり細かいことを書いていられないので、霞司郎というアカウントのタイムラインで見た気になるツイートを次に掲載します。これがこの項目での本題になります。

リツイート：kasumi_shiro（霞 司郎㌥）＞2016/09/23 15:38／2016/09/23 15:07＞ https://twitter.com/kasumi_shiro/status/779208311061098496 ＞
 bubblinkace （lawawyer）＞ https://twitter.com/bubblinkace/status/779200481310584832 ＞
引用＞　 被告側が本人の訴訟で、法律論を唱えたところ「弁護士を使って法律論を振りかざすことは、国民の裁判の権利を侵害するもので、憲法違反だ。」と反論された。＜改行＞＜改行＞アンドロメダの帝王かと思った。 

リツイート：kasumi_shiro（霞 司郎㌥）＞2016/09/23 14:53／2016/09/23 11:00＞ https://twitter.com/kasumi_shiro/status/779196904483631108 ＞
 lawyerhotaro （君の名はほうたろう（戦力外））＞ https://twitter.com/lawyerhotaro/status/779138347906150400 ＞
引用＞　 本人訴訟の本人が書面で「憲法違反」を連呼する率は異常。素人は「憲法違反」といえば相手がひれ伏すと思っているのだろうか。 

　他に、深澤諭史弁護士やモトケンこと矢部善朗弁護士（京都弁護士会）、こたんせ、や刑裁サイ太のツイートのリツイートも散見されますが、間隔も近接した上記の２つのリツイートが特に印象的でした。

　本人訴訟といえば、まっさきに頭に浮かぶのは鹿児島大学の准教授から教授になった坂本正幸弁護士ですが、その本人訴訟の問題を憲法の問題ととらえたのが、私の非常上告の問題と重なるところもあって、看過出来ないと判断しました。長々と経緯を辿ったのもそのためです。

　時刻は20時41分になっています。今日は午後に母親のいる病院にゆき、戻ってから夕方に宇出津新港にアジ釣りに行っていました。

　家に戻ったのは18時30分から40分ぐらいかと思いますが、今までにないぐらい驚くようなツイートを小倉秀夫弁護士がやっていました。日弁連の死刑廃止宣言問題の関連かと思いますが、慣れてはいるつもりだったものの、また一つ想像の枠を広げるような内容でした。

　交わりは確認していませんが、モトケンこと矢部善朗弁護士（京都弁護士会）の方でも同じ日弁連の死刑廃止宣言問題に関連したツイートを畳み掛けるように繰り返していましたが、ここぞとばかりの意気込みが強く伝わりました。

　まず先に、この項目の締めくくりをしておきたいと思いますが、本人訴訟に関してはブログの記事として、次の２つのまとめを作成しています。今日の朝だったように思いますが、頭にいろいろと詰め込んでいるので、正確には思い出せません。

参考資料：「本人訴訟」をキーワードに含む「坂本正幸（@sakamotomasayuk）」のツイート・リツイート（2011-03-08 16:05〜2016-06-21 13:04）,http://hirono2016k.blogspot.com/2016/10/sakamotomasayuk2011-03-08-16052016-06.html
参考資料：「本人訴訟」をキーワードに含む「霞 司郎㌥（@kasumi_shiro）」のツイート・リツイート（2011-08-06 20:59〜2016-09-23 14:53）,http://hirono2016k.blogspot.com/2016/10/kasumishiro2011-08-06-20592016-09-23.html

　君の名はほうたろう（戦力外）、となっているアカウントのことですが、7月の告訴状にもご紹介していると思います。前は「ほうたろう」だけだったと思いますが、妖怪ウォッチのコマさんというキャラクターをプロフィールの画像に使っていました。

　7月の告訴状には書いたように思いますが、風呂敷を背負った泥棒猫の怪物のような不思議な画像だと思っていましたが、それが有名な妖怪ウォッチというアニメのキャラクターだと知ったのはだいぶん後のことだったと思います。

　昨年の連続テレビ小説まれ、に輪島市大沢の神社で狛犬にサングラスを掛けられるなどという、父親に対する逆恨みによる場面があって、同じく「ぺ」といういたずらもあって、それが気になって調べたところ、七尾の大地主神社のチャンペ饅頭に行き着いたのと、同じ頃だったとも思います。

　あとで調べて知ったことですが、妖怪ウォッチのコマさんというキャラクターも、元は神社の狛犬で、わけあって放浪の旅に出て都会に住むようになったという設定になっていたかと思います。

　本人訴訟と憲法のことで、霞司郎というアカウントのリツイートとして、ほうたろうのツイートを掲載したところでしたが、宇出津新港から家に戻ると、モトケンこと矢部善朗弁護士（京都弁護士会）のタイムラインにも、ほうたろうのツイートのリツイートがあり、初めて見たような気もしました。

　項目として取り上げたいことが沢山ありすぎて、選択と詰め合わせに迷うところですが、この項目の最後として、坂本正幸弁護士の本人訴訟に関したツイートをご紹介します。そういえば、モトケンこと矢部善朗弁護士（京都弁護士会）は坂本正幸弁護士のツイートもリツイートしていました。

ツイート：sakamotomasayuk（坂本正幸）：2011/08/02 14:08： https://twitter.com/sakamotomasayuk/status/98258958183170048 ：
引用→　 本人訴訟などで正義のためって言って戦っている人の法解釈は一種の信仰になっていると思うときがある。

ツイート：sakamotomasayuk（坂本正幸）：2014/11/11 08:47： https://twitter.com/sakamotomasayuk/status/531956451028111361 ：
引用→　 本人訴訟頑張ってます、や自分で異議申し立てなどをしています、という人は基本的にブロックする方針。

　予定では後のものの一つでしたが、先に目に入ったものを先に追加しておきました。本人訴訟の法解釈が一種の信仰などと言っていますが、そういう考えやスタンスが集まった束となって、私の弁護士妖怪大泥棒神社や、さらば弁護士鉄道、弁護士汚染除去装置というコンセプトに結実しています。

2016-10-07　金曜日　21：17　＜＜ ［［　←これまでの記述範囲の終了時刻］］＜＜
**** 日弁連の死刑廃止宣言に関連した小倉秀夫弁護士、モトケンこと矢部善朗弁護士（京都弁護士会）、深澤諭史弁護士のツイートのまとめ

:CATEGORIES: 名誉毀損の刑事告訴における具体的相談に先立ち、珠洲警察署に提出する準備書面
:TAGS: モトケンこと矢部善朗弁護士（京都弁護士会）,日弁連,人権集会,小倉秀夫弁護士,深澤諭史弁護士,死刑廃止

2016-10-07　金曜日　21：24　＞＞ ［［　←これからの記述範囲の開始時刻］］＞＞

　不定期で実行しているブログ記事としてのモトケンこと矢部善朗弁護士（京都弁護士会）、小倉秀夫弁護士、深澤諭史弁護士のツイートの完全版としてのまとめ、ですが、本日は2度これを行いました。次のブログ記事になります。

参考資料：モトケンこと矢部善朗弁護士（京都弁護士会）（@motoken_tw）のツイート（215件、 2016-10-02 18:50〜2016-10-07 09:59：2016-10-07の記録）「1-100／215」件,http://hirono2016k.blogspot.com/2016/10/motokentw215-2016-10-02-18502016-10-07.html
参考資料：モトケンこと矢部善朗弁護士（京都弁護士会）（@motoken_tw）のツイート（215件、 2016-10-02 18:50〜2016-10-07 09:59：2016-10-07の記録）「101-200／215」件,http://hirono2016k.blogspot.com/2016/10/motokentw215-2016-10-02-18502016-10-07_7.html
参考資料：モトケンこと矢部善朗弁護士（京都弁護士会）（@motoken_tw）のツイート（215件、 2016-10-02 18:50〜2016-10-07 09:59：2016-10-07の記録）「201-215／215」件,http://hirono2016k.blogspot.com/2016/10/motokentw215-2016-10-02-18502016-10-07_18.html
参考資料：小倉秀夫弁護士（@Hideo_Ogura）のツイート（114件、 2016-10-03 02:38〜2016-10-07 10:26：2016-10-07の記録）「1-100／114」件,http://hirono2016k.blogspot.com/2016/10/hideoogura114-2016-10-03-02382016-10-07.html
参考資料：小倉秀夫弁護士（@Hideo_Ogura）のツイート（114件、 2016-10-03 02:38〜2016-10-07 10:26：2016-10-07の記録）「101-114／114」件,http://hirono2016k.blogspot.com/2016/10/hideoogura114-2016-10-03-02382016-10-07_7.html
参考資料：深澤諭史弁護士（@fukazawas）のツイート（119件、 2016-10-03 09:14〜2016-10-06 22:45：2016-10-07の記録）「1-100／119」件,http://hirono2016k.blogspot.com/2016/10/fukazawas119-2016-10-03-09142016-10-06.html
参考資料：深澤諭史弁護士（@fukazawas）のツイート（119件、 2016-10-03 09:14〜2016-10-06 22:45：2016-10-07の記録）「101-119／119」件,http://hirono2016k.blogspot.com/2016/10/fukazawas119-2016-10-03-09142016-10-06_7.html

　上記の7件が本日の午前10時07分にスクリプトを実行してまとめたツイートの記録になります。10月2日の18時50分から翌3日の9時14分、そこから、6日22時45分から本日10月7日の10時26分前のツイートのまとめになります。個人差はありますが5日分弱になるかと思います。

参考資料：モトケンこと矢部善朗弁護士（京都弁護士会）（@motoken_tw）のツイート（23件、 2016-10-07 09:59〜2016-10-07 19:30：2016-10-07の記録）「23」件,http://hirono2016k.blogspot.com/2016/10/motokentw23-2016-10-07-09592016-10-07.html
参考資料：小倉秀夫弁護士（@Hideo_Ogura）のツイート（36件、 2016-10-07 10:26〜2016-10-07 20:10：2016-10-07の記録）「36」件,http://hirono2016k.blogspot.com/2016/10/hideoogura36-2016-10-07-10262016-10-07.html
参考資料：深澤諭史弁護士（@fukazawas）のツイート（26件、 2016-10-06 22:45〜2016-10-07 20:11：2016-10-07の記録）「26」件,http://hirono2016k.blogspot.com/2016/10/fukazawas26-2016-10-06-22452016-10-07.html

　上記3件が本日7日の夕方のまとめになりますが、さきほどの間違いに気が付きました。「本日の午前10時07分にスクリプトを実行してまとめたツイート」という部分ですが、これは10月7日であることを時刻と勘違いしたものでした。

　タイトル名が長くなりすぎるので、タイトル名にスクリプトの実行時刻は含めていません。

　数秒単位の誤差はあるかもしれませんが、スクリプトの実行時刻は記事の本文の「モトケン（motoken_tw）投稿ユーザのプロフィール情報（2016年10月07日10時29分12秒頃の取得）」というような部分で確認できます。

　前にもご紹介していると思いますが、スクリプトは次のようにワンライナーの一つのコマンドとして次のように実行しています。一連としての自動処理になります。

unset ARRAY1 && ARRAY1=("${ARRAY1[@]}" "mt") && ARRAY1=("${ARRAY1[@]}" "ohb") &&  ARRAY1=("${ARRAY1[@]}" "fsb") && for (( I = 0; I < ${#ARRAY1[@]}; ++I )); do k-make-sql-motoken_or_ogura_or_fukazawa.sh ${ARRAY1[$I]}; done|xsel -b

　夕方に実行したものは次になります。

モトケン（motoken_tw）投稿ユーザのプロフィール情報（2016年10月07日20時17分44秒頃の取得）：

小倉秀夫（Hideo_Ogura）投稿ユーザのプロフィール情報（2016年10月07日20時17分49秒頃の取得）：

深澤諭史（fukazawas）投稿ユーザのプロフィール情報（2016年10月07日20時17分50秒頃の取得）：

　取得するツイートの件数が多ければ、それだけ時間も掛かると思いますが、上記の記録を見ると1件のアカウント辺り、4,5秒で処理を完了していることになります。

　日弁連が死刑廃止宣言を採択したということは、20時15分頃だったと思いますが、録画を再生した本日の19時のNHKのニュース番組で確認をしました。冒頭に５つの見出しが出て、その最後にありました。

　今もテレビで報道ステーションを見ていますが、メインはオリンピックの「メダリスト凱旋パレード80万人が祝福」のニュースです。昼前には後見人弁護士の1億円横領裁判のニュースも一度だけ見ていましたが、他に取り上げたものは見ていません。

／＊＊＊＊＊＊＊＊＊＊（引用開始）＊＊＊＊＊＊＊＊＊＊
引用URL＞＞＞＞：http://www3.nhk.or.jp/news/html/20161007/k10010721891000.html 日弁連 死刑廃止目指す宣言採択 反対意見で紛糾も | NHKニュース

日弁連・日本弁護士連合会は福井市で開いた大会で、初めて死刑制度の廃止を目指すという宣言を採択しました。一方、反対意見が相次いだため大会は一時紛糾し、全会一致の採択には至りませんでした。

日弁連の執行部は福井市で開いた人権擁護大会で、「２０２０年までに死刑制度の廃止を目指し、代わりに終身刑などの導入を検討する」という宣言を提案しました。カメラ撮影が認められない中で行われた審議では、日弁連の委員が、えん罪によって死刑が執行されると取り返しがつかないことや世界では死刑を廃止する国が増えていることなどを提案の理由として説明しました。

これに対して犯罪被害者を支援する弁護士から「被害者や遺族の前で死刑はいらないと言えるのか」といった意見や、「日弁連は特定の正義感を押しつけるべきではない」といった意見が相次ぎ、大会は一時紛糾しました。

＊＊＊＊＊＊＊＊＊＊（引用終了）＊＊＊＊＊＊＊＊＊＊／

　上記がネット上のNHKのニュース記事のの一部引用になりますが、「カメラ撮影が認められない中で行われた審議」という部分は、19時と21時のNHKのニュース番組のいずれにも見ることはなかったと思うものです。

　テレビの報道ステーションですが、弁護士の横領事件を取り上げています。本当にひどすぎます、とかいう司会者の発言の後、ちょっとだけ映像を見せてCMにはいりました。昼前に見た時と同じ、物凄くふてぶてしく迷惑そうな弁護士の態度も印象的です。

　「余生を支える全財産を・・・”横領”元弁護士に懲役6年」という見出しが、テレビの画面の右上に表示されています。

　3人から1億2千万円を横領とも報道ステーションは報じています。キャバクラでシャンパンタワーなどの豪遊をしていたということは、以前何かで見ていましたが、ネットのニュースで、テレビではなかったように思います。

　報道ステーションでは、昨年の弁護士による後見人の横領が37件、総額で1億2千万円で過去最高とか下の方の字幕で紹介していましたが、数年前には岡山と福岡で10億円に近いような横領や詐欺の事件があったことを考えると、とても不思議に思える報道です。福岡の方はいくらか少なかったとも。

　明日の朝の各局の情報番組もオリンピックのメダリストの凱旋パレードがメインになるかと思いますが、それだけ弁護士の横領事件の報道の可能性も低くなり、周知の機会も乏しくなりそうです。凱旋パレードの幸福感が強いだけに、負の側面との関係性に複雑な気持ちになります。

　NHKのニュース番組では、19時も21時も女性の過労死の労災認定を取り上げていましたが、今のところ報道ステーションでは見ていないように思います。うつ病を発症していた可能性があるとかいう報道も、本件告訴事件との関係性で感慨深いものがありました。

　「電通　新入社員が自殺　残業105時間「過労死認定」という見出しで、報道ステーションで始まりましたが、この行を書いているうちに終わりました。とても短い報道で20秒から30秒はなかったように思います。うつ病のことも言及はなかったと思います。

　日弁連の死刑廃止宣言採択のことを中心に取り上げる予定でいますが、さきほど落合洋司弁護士（東京弁護士会）のツイートで過労死労災の関連ツイートを見たこともあり、こちらを先に取り上げたいと思います。

2016-10-07　金曜日　22：44　＜＜ ［［　←これまでの記述範囲の終了時刻］］＜＜
**** 「女性新入社員の自殺 長時間労働が原因として労災認定」というニュースと、落合洋司弁護士（東京弁護士会）のツイートの本件告訴事件の関連性

:CATEGORIES: 名誉毀損の刑事告訴における具体的相談に先立ち、珠洲警察署に提出する準備書面
:TAGS: 落合洋司弁護士（東京弁護士会）,自殺,労災認定,検察庁

2016-10-07　金曜日　23：16　＞＞ ［［　←これからの記述範囲の開始時刻］］＞＞

ツイート：yjochi（落合洋司（オンラインチャット相談対応可））：2016/10/07 21:26： https://twitter.com/yjochi/status/784369371795697664 ：
引用→　 検察庁にいた時、月に300時間残業した事務官の話を聞いたことがある。いつ寝ているのか不思議がられていたとのことだった。→「電通」の女性新入社員の自殺 長時間労働が原因として労災認定 #ldnews https://t.co/AtoSmYnRJ2

　労災認定のニュースのことは前回の項目である次のブログ記事の終わりの方でも取り上げています。

告訴状の下書き）日弁連の死刑廃止宣言に関連した小倉秀夫弁護士、モトケンこと矢部善朗弁護士（京都弁護士会）、深澤諭史弁護士のツイートのまとめ,http://hirono2016k.blogspot.com/2016/10/blog-post_53.html

　落合洋司弁護士（東京弁護士会）のツイートのタイムラインは、昨夜久しぶりに見たように思いますが、それからの更新は少なく、今のところ他の弁護士のタイムラインで盛り上がっている日弁連の死刑廃止宣言関連のツイートもないようです。

　時刻はちょうど10月8日の0時00分になったところです。パソコンの調子が悪く動作が重くなっていたので、再起動をしていました。

　項目の見出しとは直接の関係はありませんが、昨夜見た落合洋司弁護士（東京弁護士会）のタイムラインのツイートで、久しぶりに落合洋司弁護士（東京弁護士会）らしさを強く感じたツイートを、この機会にご紹介しておきます。小倉秀夫弁護士との変わらない共通性も強く感じました。

　順番は新しいものから過去のものへと遡っていくことになります。

ツイート：yjochi（落合洋司（オンラインチャット相談対応可））：2016/10/07 00:28： https://twitter.com/yjochi/status/784052644188790784 ：
引用→　 地方議会も、富山みたいな馬鹿ばかりだから廃止。

ツイート：yjochi（落合洋司（オンラインチャット相談対応可））：2016/10/07 00:27： https://twitter.com/yjochi/status/784052504686239744 ：
引用→　 馬鹿ばかり出てくる選挙は廃止。

ツイート：yjochi（落合洋司（オンラインチャット相談対応可））：2016/10/07 00:26： https://twitter.com/yjochi/status/784052334795952128 ：
引用→　 国民の主権を、すべて天皇陛下にお預けして治めていただく。

ツイート：yjochi（落合洋司（オンラインチャット相談対応可））：2016/10/07 00:24： https://twitter.com/yjochi/status/784051812743557120 ：
引用→　 大化の改新とまでは言わないが、建武の中興くらいまで戻って、天皇親政の美しい日本を取り戻すべきだろう。

ツイート：yjochi（落合洋司（オンラインチャット相談対応可））：2016/10/07 00:21： https://twitter.com/yjochi/status/784050982237843457 ：
引用→　 せっかくの大事な票を、自民とか自民の政治家に入れる輩の気が知れんわな。笑

ツイート：yjochi（落合洋司（オンラインチャット相談対応可））：2016/10/06 22:37： https://twitter.com/yjochi/status/784024684975140865 ：
引用→　 日本を守るためには、身を捨てて、先頭に立って戦うくらいの気概を持っていない人間を防衛大臣にしてはダメだろう。口先男、口先女なんて、防衛大臣としては最低。あ、これ、一般論なので。笑

ツイート：yjochi（落合洋司（オンラインチャット相談対応可））：2016/10/06 22:35： https://twitter.com/yjochi/status/784024177481125888 ：
引用→　 自衛隊が行くところに、防衛大臣がビビって行かないでは示しがつかんだろう。

ツイート：yjochi（落合洋司（オンラインチャット相談対応可））：2016/10/06 22:34： https://twitter.com/yjochi/status/784023922421280768 ：
引用→　 自分が防衛大臣なら、南スーダンに行って、現地を戦車に乗って走り回って治安状況を視察するがな。

ツイート：yjochi（落合洋司（オンラインチャット相談対応可））：2016/10/06 22:31： https://twitter.com/yjochi/status/784023361714200576 ：
引用→　 前に、一時、何度か国会の参考人とかで呼ばれて、国会議員と名刺交換すると、勝手に名簿に登録されてしまって、資金パーティーの勧誘が来たりするが、馬鹿らしいので全部捨てている。紙が無駄。もう呼ばれることもないので今後は減ると思うが。

ツイート：yjochi（落合洋司（オンラインチャット相談対応可））：2016/10/06 22:28： https://twitter.com/yjochi/status/784022527915937792 ：
引用→　 白紙の領収書を発行して良いことが、政権党の大臣によって公式に是認されたということだな。ヒトラーもびっくり。

ツイート：yjochi（落合洋司（オンラインチャット相談対応可））：2016/10/06 22:26： https://twitter.com/yjochi/status/784021967544299522 ：
引用→　 愛国心に満ち溢れているはずの自民党所属防衛大臣が、終戦記念日に靖国神社に参拝せずアフリカあたりをウロウロしているというのはまずくないか。泣いて済む問題ではなかろう。

ツイート：yjochi（落合洋司（オンラインチャット相談対応可））：2016/10/06 22:19： https://twitter.com/yjochi/status/784020282226855936 ：
引用→　 今は、警察内で捜査と留置が分離されているので、取調室でカツ丼、はない。古い警察署へ行くと、刑事部屋の奥に留置場があって、未分離の当時がしのばれることがある。

ツイート：yjochi（落合洋司（オンラインチャット相談対応可））：2016/10/06 22:13： https://twitter.com/yjochi/status/784018694129135616 ：
引用→　 弁護士って、攻めるのには慣れていても攻められるのには慣れていないのでは。自分の場合、検事の当時に散々攻められたのが良い経験になっている。笑→稲田氏の化けの皮が剥がれてきた #BLOGOS https://t.co/me0viC9Dln

ツイート：yjochi（落合洋司（オンラインチャット相談対応可））：2016/10/06 22:05： https://twitter.com/yjochi/status/784016621417304064 ：
引用→　 取調室といえばカツ丼。→取調室にカツ丼　名物店閉店へ　兵庫県警本部前（神戸新聞NEXT） - Yahoo!ニュース https://t.co/98FobSiDPd #Yahooニュース

ツイート：yjochi（落合洋司（オンラインチャット相談対応可））：2016/10/06 17:14： https://twitter.com/yjochi/status/783943610748153856 ：
引用→　 身売りって、発想が古すぎないか。→ツイッター：身売りへ、週内にも入札か　米紙報道 - 毎日新聞 https://t.co/pXNh9klAPG

ツイート：yjochi（落合洋司（オンラインチャット相談対応可））：2016/10/06 09:34： https://twitter.com/yjochi/status/783827855801131008 ：
引用→　 この事件を担当した検事と同じ地検で勤務したことがある。→11年間で22人を殺害した消防隊員・勝田清孝の知られざる素顔【大量殺人事件の系譜】 | 日刊SPA! https://t.co/hEupDlmZWp @weekly_SPAより

　唐突感もありましたが、最後にご紹介した連続殺人事件のことは、テレビの報道で見ていてしばらくしてから、重要な舞台の一つとなった名神高速の養老サービスエリアに、たぶん初めて入った時に奇妙なぐらい感慨深く感じた思い出があります。

　一月半か長くて2ヶ月ぐらい小林運送で長距離助手をやった昭和58年の4月頃のことです。

　ベテランの刑事弁護士で同じく元検察官でもある郷原信郎弁護士にも感じたことですが、落合洋司弁護士（東京弁護士会）は警察の留置場において、指定された食堂から自由に出前の注文ができることを知らないのではと思いました。

　自分の経験としても、平成11年にいた金沢中警察署の留置場で、出前で食べたカツ丼が忘れられないぐらい美味かったことを憶えているのですが、残念ながら店の名前の記憶がなく、同じ店のカツ丼を再び食べることが出来ないことをとても残念に思っています。数少ない出前の注文でもありました。

　落合洋司弁護士（東京弁護士会）は最近でも朝の情報番組とくダネ！で、コメントしているのを見ています。NHKを含め他の番組では姿を見ていません。どこまで本気なのかと真剣に考えさせられるところも小倉秀夫弁護士に似ていますが、どちらも社会的に成功し評価を受けている弁護士とも思います。

　独自に大きな存在感を持つ弁護士であるということでも共通していますが、落合洋司弁護士（東京弁護士会）と小倉秀夫弁護士に感じる違いは、落合洋司弁護士（東京弁護士会）の場合、不思議と酷評するツイートを見かけないことです。

　それも当然と思われるのは、落合洋司弁護士（東京弁護士会）の場合、田んぼの草刈り感覚、手が疲れる等とツイートしながらブロックをしまくってきたという事実があります。直近の確認はしていませんが、私も３つのアカウントを全てブロックされています。坂本正幸弁護士と同じです。

　落合洋司弁護士（東京弁護士会）のフォロワー数は0時41分現在で、34,259という数になっていますが、いつみても大きな変動はないように思えるのも、実に不思議な社会現象であり、経歴や肩書の威力の大きさを考えさせられるところでもあります。

　「過労死ゼロへ　初の白書　働く側でできること」という見出しで、放送中のニュースZEROを見たところですが、そういえば、この項目のテーマに取り上げた過労自殺労災認定の報道をニュースZEROでは見ていないように思い、パソコンに集中していて油断していたことに気が付きました。

　0時49分です。今のCMに入る前、小沢一郎の正当が「自由党」に党名変更か、という短いニュースをやっていましたが、こんなもの報道の価値があるのかと疑問に思いましたし、他で見たことのない報道でした。

　政治家小沢一郎氏の印象をすこぶる悪いものにしたのは、本人のテレビでの発言、態度もありますが、弁護士らの取り上げ、取り扱いに目に余るものがあり、落合洋司弁護士（東京弁護士会）にもその傾向があったように思います。

　「ジンベエザメ搬出　モモベエ海へ」という石川県内ニュースをニュースZEROでやっていますが、これは他のニュースでも見ていました。数年前にも同じ海に返したというニュースがありましたが、そのジンベエザメはすぐに死んでしまったというのも忘れられない記憶です。

　ジンベエザメのニュースは、のとじま水族館のことで、石川県内には他に水族館はないはずかと思います。3,4年前になりますか、のとじま水族館にバイクで行って、ジンベエザメを見ています。のとじま水族館に行ったのは2度目のことで、初回は平成3年のことで、6月中であったように思います。

　大きな水槽でしたが、水族館でのジンベエザメの姿は、同じ所をぐるぐると周り続け、拘置所での独房生活を思い起こさせ、連想させるものでした。

　さきほどのニュースZEROを見ていても強く感じたことですが、オリンピックの凱旋パレードの規模の大きさと祝福の大きさを映像として目の当たりにしたことです。昼の番組では今世紀最大という表現もあったかと思います。

　とりわけて今回の南米大陸初というリオオリンピックでは、治安の悪さなどが大きな前評判となりながら、あえてそこで開催することが人類の平和への貢献であるという実行委員会のようなところの発言をテレビで見たのも、すごく印象的でした。

　個人的にスポーツ全般には関心も薄いのですが、人類の歴史における競争心の平和利用という意味だけでもオリンピックの存在意義は大きいと考えているのですが、最近は見なくなった落合洋司弁護士（東京弁護士会）のオリンピックに対する苛烈な酷評があったこともテレビを見ながら思い出しました。

　あるかないかはわかりませんが、Twitterの高度な検索から、あれば追加という作業をして、「オリンピック」をキーワードに落合洋司弁護士（東京弁護士会）のツイートをブログの記事としてまとめておきたいと思います。

参考資料：「オリンピック」をキーワードに含む「落合洋司弁護士（東京弁護士会）（@yjochi）」のツイート・リツイート（2009-08-08 20:07〜2016-09-23 09:04）「82」件,http://hirono2016k.blogspot.com/2016/10/yjochi2009-08-08-20072016-09-23-090482.html

　思うところがあって、「小夜嵐」という言葉で検索をしたのですが、次のような物足りなさを感じる意味しか見つけることが出来ませんでした。

／＊＊＊＊＊＊＊＊＊＊（引用開始）＊＊＊＊＊＊＊＊＊＊
引用URL＞＞＞＞：http://dictionary.goo.ne.jp/jn/89460/meaning/m0u/ さよあらし【小夜嵐】の意味 - goo国語辞書

夜の嵐。よあらし。

＊＊＊＊＊＊＊＊＊＊（引用終了）＊＊＊＊＊＊＊＊＊＊／

　能登島での思い出から「伊夜比咩神社」のことを思い出しました。残念ながらネット上の情報では見つけることが出来なかったですが、宇出津祭礼委員として頼まれて購入をした能登のキリコ祭りの本には、次のように紹介されていました。

「伊夜」という言葉には「素晴らしい」との意味があり、伊夜比咩神社とは「素晴らしい女性の神」ということなのでしょう。

【楽天市場】北國新聞社出版局 能登のキリコ祭り 日本遺産 | 価格比較 - 商品価格ナビ http://bit.ly/2cXibpw

　これを読んだことが行動につながったように思いますが、今年は、初めて羽咋郡志賀町富来の西海祭りと八朔祭礼を見に行くことにもなりました。同じ富来で似ているキリコ祭りですが、八朔祭礼は、くじり祭りとも呼ばれ、能登でよく言われるのは「チャンペ祭り」です。

　七尾市の大地主神社の「チャンペ饅頭」とも共通性があるので、是非一度はこの目で見ておきたいお祭りでしたが天候にも恵まれ、どちらも納得のできる体験として自分の目で見ることが出来ました。なお、趣向も異なるらしい八朔祭礼の二日目は見に行っていません。多数のお神輿がメインになるそうです。

　能登島向田の火祭りは、稲田と強く意識させるお祭りでしたが、海の側の住宅のすぐ前で、真っ赤なヘビを見たのもすごく印象的でした。ヘビは神様のお使いとも言われますが、宇出津の春祭りの後に初めて行った遠島山公園でも、待ち構えていたようなヘビを見ています。その蛇は撮影もしています。

　能登のお祭りが、神社の神事であることを、50年を超えて生きてきて初めて意識したのも今年のことでしたが、弁護士が現世の疫病神であることを更に強く意識し、神様の目線でふざけたやつ、であることを、さらに深く考えることになったのも、今年になっての大きな転機です。

　報道されていた過労自殺で労災認定のニュースの若い女性のお名前が、「まつり」であったことも、深く広く考える契機となりました。家族がなぜ「まつり」という名前にしたのかという理由にも思いを馳せ、それが神事や神の意思につながるような気持ちにもなりました。蛇との出会いにも似ています。

／＊＊＊＊＊＊＊＊＊＊（引用開始）＊＊＊＊＊＊＊＊＊＊
引用URL＞＞＞＞：http://www.sankei.com/affairs/news/161007/afr1610070012-n1.html ２４歳東大卒女性社員が過労死　電通勤務「１日２時間しか寝れない」　クリスマスに投身自殺　労基署が認定 - 産経ニュース

最長月１３０時間の残業などで元電通社員の高橋まつりさん＝当時（２４）＝が自殺し、三田労働基準監督署（東京）が過労死として認定していたことを７日、遺族側弁護士が会見で明らかにした。

　弁護士によると、高橋さんは平成２７年３月、東京大文学部を卒業後、同年４月に電通に入社。インターネットの広告部門を担当し、同年１０月から証券会社の広告業務も入った。

　弁護士側が入退館記録を基に集計した残業は、１０月が１３０時間、１１月が９９時間となっていた。休日や深夜の勤務も連続し、１２月２５日に、住んでいた寮から投身自殺した。

＊＊＊＊＊＊＊＊＊＊（引用終了）＊＊＊＊＊＊＊＊＊＊／

　上記はネットで調べた記事の部分引用になりますが、テレビの報道では見ることのなかったことがいくつか書かれています。テレビでは弁護士のことは出ていなかったように思います。当然にその可能性は考えていました。

　冒頭の落合洋司弁護士（東京弁護士会）のツイートで、私が考えたことは、ニュースの本筋からは外れますが、弁護士が掛ける、警察、検察への気ままで過大な負担のことです。かねがね思い続けてきたことですが、それを具体的な数値として考える機会となりました。

　「 検察庁にいた時、月に300時間残業した事務官の話を聞いたことがある」という部分がそれです。私の本件告訴事件も、将来的に、泥棒神社の弁護士が黙っちゃない、という事態の招来が想定されるところであり、万全の準備の必要性を勁く感じてきました。

　「参考資料扱いにした過去の告訴状の下書き」などで記述をしてきたと思いますが、私は福井刑務所に服役していた時点で、安藤文さんの労災認定の妥当性を強く考えており、出所後の早い段階で、金沢市新神田の合同庁舎の労働基準監督署に直接出向いて、直談判のようなこともやっています。

　落合洋司弁護士（東京弁護士会）と小倉秀夫弁護士に共通して強く感じることは、歴史観を含め、その救いようのなさです。選ばれた人にのみ救いの手を差し伸べる神様気取りの異常性も強く感じますが、それは弁護士全般にありがちな特徴を、色濃くわかりやすくしている特異性として理解しています。

　さきほどの落合洋司弁護士（東京弁護士会）のオリンピックをキーワードにしたツイートのまとめですが、記録したブログ記事によると、次のものが最新となっています。

ツイート：yjochi（落合洋司（オンラインチャット相談対応可））：2016/09/23 09:04： https://twitter.com/yjochi/status/779109058804457472 ：
引用→　 東京オリンピックまでは警備畑主導だろう。→【登場】警視総監　沖田芳樹氏（59）：日本経済新聞 https://t.co/3snWO1kIXs

　継続性のある本来のオリンピックに対する落合洋司弁護士（東京弁護士会）らしさを感じさせるものとしては、次のツイートが最新ではないかと思います。

ツイート：yjochi（落合洋司（オンラインチャット相談対応可））：2016/06/15 10:56： https://twitter.com/yjochi/status/742898508005416961 ：
引用→　 これで東京オリンピックもなくなれば、ハッピーエンドでは。笑

　6月15日のツイートとなっているので、ずいぶんと前のことです。あれからオリンピックや東京都知事をめぐる情勢も、想像のつかなかった変遷がありました。

　最近は、警察、検察批判が富に見られなくなった落合洋司弁護士（東京弁護士会）のツイートですが、数年前の批判ツイートの影響を受けて、金沢地方検察庁との対応を誤ったことは、取り返しのつかない損失であるとともに、やりきれない痛恨事であります。

2016-10-08　土曜日　02：39　＜＜ ［［　←これまでの記述範囲の終了時刻］］＜＜
**** 探しだした「刑事訴訟愛好会」という小倉秀夫弁護士もメンバーになっていたFacebookページのスクリーンショット

:CATEGORIES: 名誉毀損の刑事告訴における具体的相談に先立ち、珠洲警察署に提出する準備書面
:TAGS: 刑事訴訟愛好会,小倉秀夫弁護士,高島章弁護士,Facebook

2016-10-08　土曜日　11：16　＞＞ ［［　←これからの記述範囲の開始時刻］］＞＞

　小倉秀夫弁護士やモトケンこと矢部善朗弁護士（京都弁護士会）が日弁連の死刑廃止宣言に触発され、犯罪被害者について活発なツイートをやっているので、それを取り上げて本件告訴との関係性を書きたいところですが、その前提として調べだした過去の記録です。

　正解は「刑事訴訟愛好会」だったのですが、正確に一部の言葉を思い出すことが出来ず、探しだすのに時間がかかりました。取っ掛かりを見つけることが出来たのは、Twilogでの「申請」というキーワードでの検索でした。次のページになります。

奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「申請」の検索結果 - Twilog http://twilog.org/hirono_hideki/search?word=%E7%94%B3%E8%AB%8B&ao=a

　上記のページで見つけたのが、次の高島章弁護士のツイートです。高島章弁護士も7月の告訴状などで何度か取り上げご紹介してきたと思いますが、新潟市内で活動する弁護士で、新潟での司法修習では小倉秀夫弁護士と同期であったということです。個性が強い刑事弁護に熱心で、公害訴訟も手がけて。

リツイート：hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）＞2015/11/07 23:43／2012/05/31 19:32＞ https://twitter.com/hirono_hideki/status/663003824483766272 ＞
 BarlKarth （高島章（弁護士））＞ https://twitter.com/BarlKarth/status/208143983212371968 ＞
引用＞　 　刑事訴訟愛好会（フェイスブック）に入会申請者数名。厳格な身元調査の上入会の可否を判断しています。弁護士・学者限定の会議室。 

　刑事訴訟愛好会というFacebookページは、初めに開いて見てから、確か10分から20分ぐらいの間にネット上から消滅してしまい、跡形もない幻となったのですが、他にGoogleで検索をして、唯一それらしい痕跡の情報を見つけたのが、上記の高島章弁護士のツイートでした。

　私のリツイートの時刻が2015/11/07 23:43となっていますが、この時間の前に、ページは消えていましたし、あとでご紹介するページのスクリーンショットの時点では、初めにページを開いてから間もない状況でした。記録の必要という即座の判断が功を奏した経験でした。

　一連の近接した時間のツイートであることは記憶があるので、次のようにページ内のリンクから同日のページを開きました。

奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/2015年11月07日 - Twilog http://twilog.org/hirono_hideki/date-151107

　そこで見つけたのが、次のスクリーンショット付きのツイートのURLを含むツイートです。URLを見たところ、Facebookでの投稿でTwitterへ同時投稿されたものだとわかります。

ツイート：hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）：2015/11/07 23:47： https://twitter.com/hirono_hideki/status/663004900255731712 ：
引用→　 おすすめ的にFacebookに出てきたので申し込みをしたのですが、即座にページが開けなくなりました。メンバーらしい一覧に小倉秀夫弁護士のアイコンがあったのも興味深く思いました。... https://t.co/GpfOcIvWs9

　スクリーンショットの画像は一つしかなくページトップのカバー写真が写っていましたが、小倉秀夫弁護士のアイコンは見当たりませんでした。日付が変わる13分前の投稿になっているので、翌日にまたがっているのかと、ページ内のリンクから翌日のページを開きました。それが次です。

奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/2015年11月08日 - Twilog http://twilog.org/hirono_hideki/date-151108

　一通りページ内のツイートに目を通したのですが、それらしいものは見つからず。そのままスクリーンショットを専用で投稿しているs_hironoのアカウントに、URLの一部を変換して開きました。それが次のページです。

非常上告-最高検察庁御中_ツイッター(@s_hirono)/2015年11月08日 - Twilog http://twilog.org/s_hirono/date-151108

　このページで目に止まったのが、次のモトケンこと矢部善朗弁護士（京都弁護士会）のツイートのスクリーンショットでした。

ツイート：s_hirono（非常上告-最高検察庁御中_ツイッター）：2015/11/08 10:37： https://twitter.com/s_hirono/status/663168548336852992 ：
引用→　 2015-11-08-103753_モトケンさんはTwitterを使っています：　”被害妄想の人に絡まれるとかなり大変。まあ、経緯を知っている人が大勢いるので、分が悪いのは彼の.jpg https://t.co/XaGpEvypNm

　12時5分ですが、NHKの全国ニュースで石川県の死亡事故が報道されていました。チャンネルを変える前の民放のニュースでも見ていましたが、珠洲市緑丘中学校の野球部2人の中学生が死亡したとのことです。以前は能登有料道路だった自動車専用道路で、七尾市内とのことです。

　羽咋市の公立病院に運ばれたとのことです。2人の死亡の他、21人の全員がケガをしたとのことですが全員ケガの程度は軽いとのことです。大きくないマイクロバスに23人も乗っていたので、他の重傷者とか意識不明の重体の可能性も高そうだと考えましたが、大破した状況で不思議に思える事故でした。

　野球の大会で金沢市に向かっていたとのことです。私が中学生の頃は相撲部で、能登の各地で大会がありましたが、金沢市の大会に能登から参加というのは、聞いたこともありませんでした。

　特に印象に残っているのは中学1年生のときの、9月の初め頃にあった富来での新人戦でした。旅館に宿泊したのですが、記憶にある限り、そういう宿泊というのも生まれて初めての経験でした。当時は羽咋郡富来町でしたが、現在は羽咋郡志賀町の一部となっています。

　7月の終わり頃だったと思いますが、西海祭りを見に行った時、八朔祭礼の下見として富来の町中で神社を探していたところ、たまたま、宿泊した旅館と思われる町並みを発見しました。昭和52年のことと思いますが、当時の宇出津の音羽町と似た一角の町並みでした。

　のと里山海道での死亡事故は、小型マイクロバスとワゴン車との正面衝突で、ワゴン車には45歳の父親と子どもの2人が乗っていたというのも、印象的で考えさせられることの多い事故です。弁護士や裁判が関わってくることになるのか、とも考えました。

／＊＊＊＊＊＊＊＊＊＊（引用開始）＊＊＊＊＊＊＊＊＊＊
引用URL＞＞＞＞：http://mainichi.jp/articles/20161008/k00/00e/040/201000c 石川・正面衝突：ワゴン車とバス、男子中学生２人死亡　 - 毎日新聞

バスは野球部員ら２３人乗る

　８日午前６時４０分ごろ、石川県七尾市中島町笠師の自動車専用道路「のと里山海道（かいどう）」で、同県珠洲（すず）市立緑丘中の野球部員ら２３人が乗ったマイクロバスと、対向の２人乗りのワゴン車が衝突した。県警七尾署や消防によると、双方の車両の計２３人が救急搬送され、バスの男子中学生２人の死亡が確認された。同署はワゴン車を運転していた男性（４５）から自動車運転処罰法違反（過失致死傷）容疑で事情を聴く方針。

＊＊＊＊＊＊＊＊＊＊（引用終了）＊＊＊＊＊＊＊＊＊＊／

　”同署はワゴン車を運転していた男性（４５）から自動車運転処罰法違反（過失致死傷）容疑で事情を聴く方針”という部分は、テレビニュースでは報道がなかったように思います。いずれも、事故の原因を調べている、というような表現だったように思います。

　毎日新聞というのは石川県でほとんど見ることのない新聞ですが、ずいぶん詳細な報道になっていて、「同大会の開会式と８日の試合は中止になった。 」、「ワゴン車には、男性と息子（１１）が乗車していた。」とも書いてありました。

　テレビのニュースでは正面衝突となっていましたが、車体の右前方の角付近から側面に大破した事故の状況で、これは居眠りか何かで反対車線側からぶつかってこられたもらい事故の可能性が高そうだとは考えていました。ワゴン車も大破していましたが、息子にケガがなかったというのも不思議でした。

　時刻は10月13日10時57分になります。しばらく中断をしていました。

ツイート：kk_hirono（告発-金沢地方検察庁御中_ツイッター）：2016/10/08 12:49： https://twitter.com/kk_hirono/status/784601650082222080 ：
引用→　 テレビのニュースでは正面衝突となっていましたが、車体の右前方の角付近から側面に大破した事故の状況で、これは居眠りか何かで反対車線側からぶつかってこられたもらい事故の可能性が高そうだとは考えていました。ワゴン車も大破していましたが、息子にケガがなかったというのも不思議でした。

　Twitterでは上記ツイートからの再開になります。思っていたより長い中断で8日の昼過ぎからとなっていました。

　この間いろいろとありましたが、昨日は明け方の4時に目がさめたということもあって、その場の思いつきとなりゆきで新規にFacebookページを作成しました。

　他に死刑制度と被害者感情に関連して考えこまさせられるモトケンこと矢部善朗弁護士（京都弁護士会）と小倉秀夫弁護士のツイートが沢山あって、記録をする作業もあわただしくやっていました。

　中断前に書いていた部分に目を向けると、のと里山海道での死亡事故のことを書いていました。そういえばこの事故で、自動車運転過失致死傷という法律が出来ていたことを知りました。危険運転致死傷罪ばかりがクローズアップされ、その影に隠れていた感もあります。

　細かいことは省いて書いていくことにしますが、Twilogで日付を翌日に進めたまま非常上告-最高検察庁御中_ツイッター（@s_hirono）のアカウントに切り替えたところ、思わぬ発見があったのですが、当初は翌日に進めていたことに気が付かず、同じ日だったかと思いました。

　時刻は11時41分です。のちほど新規項目で取り上げることを予定していますが、昨日発見したTwitterのモーメントという新機能で、前でのTwilogのページで見つけたツイートをまとめました。次になります。

ツイート：hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）：2016/10/13 11:35： https://twitter.com/hirono_hideki/status/786394982965837824 ：
引用→　 ⚡️ “モトケンこと矢部善朗弁護士（京都弁護士会）に被害妄想やストーカー扱いされた2015年11月8日のツイートの記録・スクリーンショット”＜改行＞＜改行＞https://t.co/34YOr1yKX1

奉納＼さらば弁護士鉄道・泥棒神社の物語さんのツイート: "⚡️... - 殺人未遂事件を隠蔽した弁護士、元裁判官を刑事告訴／金沢地方検察庁御中 https://www.facebook.com/kanazawa2016/posts/1373284302696835

　2つ目は、これも昨日作成した先ほどご紹介のFacebookページの投稿として、ツイートのリンクを掲載したものです。ツイートの本文の部分がまるまるカットされていますが、自動で文字数の調整をやってくれているようです。

　この項目のメインは、小倉秀夫弁護士と「刑事訴訟愛好会」というFacebookページのことです。その締めくくりに取り掛かりたいところですが、確か昨日、小倉秀夫弁護士のタイムラインで気になるツイートを見かけました。

ツイート：Hideo_Ogura（小倉秀夫）：2016/10/12 02:23： https://twitter.com/Hideo_Ogura/status/785893571538726912 ：
引用→　 刑法のある一論点に関する論文を書いてジュリストに載せていただく程度には刑法には造詣が深いのだよ。学部時代刑法ゼミにいたし。

　次がスクリーンショットになります。気がついたのは2,3ヶ月ほど前になりますか、いつの間にかPicasaウェブアルバムが完全になくなり、Googleフォトというサービスに一本化していますが、クセが強いものの慣れるととても使い勝手がよいサービスです。

「告訴状の内容に関連したスクリーンショット　2016年10月分」の写真 - Google フォト http://bit.ly/2d8G0un

　Googleへのログイン無しで普通に閲覧しファイルのダウンロードまで出来ることを確認しましたが、ヘタをすると永遠にわからないクセがあります。それはマウスポインタを近づけないとボタンが表示されないことで、左上に左向きの矢印ボタンが出れば、そこからアルバムの全体表示に出来ます。

　右上にはiというようなボタンがあって、これは常時表示のようですが、これをクリックするとファイル名などの情報が表示されます。インフォメーションの意味なのだろうと思います。

　左右の矢印ボタンも中断の左右で、マウスポインタを近づけると表示され、それで前後の画像や写真に移動できますが、ボタンのない場所をクリックすることでも、次の画像や写真へと進んで行けるようです。

　Twitterの写真付きツイートでは、パソコンの画面の大きさの違いもありますが、画像が縮小され、細かい文字の部分が読みづらいということもあるかと思います。Googleフォトの方がサイズも大きく、ダウンロードすれば画像ビューのソフトで、部分的な拡大表示もできるかと思います。

　時刻は13時37分です。Aコープ能都店で大根が一本198円だったので買ってきて、味噌汁を作っているのですが、それだけでも調理に時間がかかりました。サンマは珍しく調理済みで2匹パック入りを買ってきたのですが、まだ焼いておらず、昼食を食べるのは14時を過ぎそうです。

　忘れそうになっていたのですが、Twilogで探しだしたのが、次の2つのスクリーンショットです。何故かパソコンからファイルは見つかりませんでした。当時メインで使っていたパソコンの方にファイルがあるかもしれません。

奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/2015年11月07日 - Twilog http://twilog.org/hirono_hideki/date-151107

ツイート：hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）：2015/11/07 23:47： https://twitter.com/hirono_hideki/status/663004900255731712 ：
引用→　 おすすめ的にFacebookに出てきたので申し込みをしたのですが、即座にページが開けなくなりました。メンバーらしい一覧に小倉秀夫弁護士のアイコンがあったのも興味深く思いました。... https://t.co/GpfOcIvWs9

非常上告-最高検察庁御中_ツイッター(@s_hirono)/2015年11月07日 - Twilog http://twilog.org/s_hirono/date-151107

ツイート：s_hirono（非常上告-最高検察庁御中_ツイッター）：2015/11/07 23:37： https://twitter.com/s_hirono/status/663002259366645760 ：
引用→　 2015-11-07-233707_刑事訴訟愛好会.jpg https://t.co/C7CIEyBvc3

ツイート：s_hirono（非常上告-最高検察庁御中_ツイッター）：2015/11/07 23:36： https://twitter.com/s_hirono/status/663002153439465474 ：
引用→　 2015-11-07-233642_刑事訴訟愛好会.jpg https://t.co/ld9pG52Izk

　先日、2015-11-07-233642_刑事訴訟愛好会.jpgを見て初めて気がついたのですが、数名による管理者というものがあって、その中に落合洋司弁護士（東京弁護士会）が含まれていました。同じ管理者として中村元弥弁護士、高島章弁護士の顔写真のアイコンもあります。

　小倉秀夫弁護士のアイコンは、2015-11-07-233707_刑事訴訟愛好会.jpgのスクリーンショットにあります。見覚えのあるのは小倉秀夫弁護士の隣の伊藤という人物の写真のアイコンで、小倉秀夫弁護士と同じくTwitterと同じかと思います。

　昨夜は、深澤諭史弁護士のタイムラインも活発な動きがありましたし、本来取り上げてご紹介しておきたいことが山積でした。内容を完結に短くして、できるだけ多く、リアルタイムにご紹介しておいたほうがよいとも考えが変わるようになりました。

　この項目の最後になりますが、「刑事訴訟愛好会」というのもなんとも考えさせられる名前でありながら、何かを象徴的に物語っているようにも思えました。

刑事訴訟愛好会 - Facebook検索 http://bit.ly/2dxNeEo

　刑事訴訟愛好会そのものはメンバー以外の非公開設定になっている可能性が考えられますが、現在も閲覧できず存在の確認すら出来ない状況です。ただ、上記の検索ページのタイムラインには、その痕跡の投稿がいくつかあり、モトケンこと矢部善朗弁護士（京都弁護士会）の投稿もありました。

　どうやら、高島章弁護士が主体となって半ば強引に他の弁護士などを登録して行ったような感じです。小倉秀夫弁護士の目的は、高島章弁護士の批判をするための登録であったらしく、その旨の高島章弁護士の投稿もありました。

　Facebookではブロックされてしまうとログアウトしても全く投稿を目にすることが出来ない可能性があるので、おいそれとは接触も出来ません。もしかすると、私のアカウントが刑事訴訟愛好会にブロックされていて目にすることが出来ない状態になっているのかもしれないとも考えました。

　確認のため調べたところ、高島章弁護士の次のツイートが見つかりました。

ツイート：BarlKarth（高島章（弁護士））：2016/05/28 02:50： https://twitter.com/BarlKarth/status/736253296810172416 ：
引用→　 【広告】＜改行＞刑事訴訟愛好会（非公開グループ）＜改行＞https://t.co/tr6ZrGW0VO＜改行＞刑事訴訟法・刑法・刑事政策等に興味のある学者・実務家の会議室です。司法試験合格者・大学院博士課程後期在学中の入会を歓迎します。決して怖い会議室ではありません。

　リンクを開こうとすると「このリンクは有効期限切れとなっているか、ページの設定により閲覧できなくなっている可能性があります。」というエラーが出ました。Facebookでは、非公開となると外部から存在の確認すら出来ない仕組みになっているのか、と思いました。

　高島章弁護士のタイムラインも、もう一月近く、一度も見ていないように思います。何かのきっかけでタイムラインを開くと、暫くの間はブラウザのタブでページを開いたままにすることも多かったのですが、最近そいうことも少なくなったいるのは、深澤諭史弁護士らの活性が高いこともあります。

　高島章弁護士のことも、新発田市の連続強姦致死事件のことで本格的に取り上げておきたいとは、ずっと前から考えにあるのですが、時間と手間をかけてそこまで踏み込む気持ちにもなれず、もやもや感がありますが、それだけ注目すべき、理解の及ばない存在感のある弁護士の一人です。

2016-10-13　木曜日　15：24　＜＜ ［［　←これまでの記述範囲の終了時刻］］＜＜
**** 「目的はあの弁護士を攻撃」という爆破予告犯に、「実刑でいいんじゃない。相手が弁護士でなくても同じ。」というモトケンこと矢部善朗弁護士（京都弁護士会）
**** 2016年10月13日以来の本書告訴状の編集再開と、その間に作成した2つの専用ブログと、一つのFacebookページのご紹介

:CATEGORIES: 名誉毀損の刑事告訴における具体的相談に先立ち、珠洲警察署に提出する準備書面
:TAGS: 法科大学院,弁護士ブログ,報道

2016-10-22　土曜日　18：42　＞＞ ［［　←これからの記述範囲の開始時刻］］＞＞

　先ほどEmacsからF9キーでTwitterに投稿しようとしたところ、スクリプトファイルがないとエラーが出ました。すぐに所定の場所にバックアップしておいたファイルをコピーしたのですが、どうも思っていたよりずいぶんと長い中断があったようです。

　それに気がついたのは、かなり前にパソコンのシステムをアップグレードしているからです。Ubuntuのバージョンを14.10にクリーンインストールしたのですが、珍しくリリースからすぐの段階で、アップグレードをしました。データは移行していますが、全く新しいパソコンのシステムです。

ツイート：kk_hirono（告発-金沢地方検察庁御中_ツイッター）：2016/10/13 15:24： https://twitter.com/kk_hirono/status/786452531673051136 ：
引用→　 2016-10-13　木曜日　15：24　＜＜ ［［　←これまでの記述範囲の終了時刻］］＜＜

　上記が実質的な中断直前の更新になるかと思います。確認はしていませんが、Ubuntuをアップグレードしたのは10月14日の作業であったように思います。比較的すっきりとトラブルも少なく新しいシステムへの以降が出来ました。

　解決できない問題というか不具合になっているのは、なぜかEmacsでツールバーのアイコンが表示されなくなったことです。表示の枠だけそのままあってのっぺらぼうの状態なので、今は: (tool-bar-mode 0)という操作で、表示自体を無効にしています。

　以前のバージョンである14.04から比べると動作が安定しており、作業も捗っています。それに伴い、インターネット上における環境整備もさらなる強化をしました。

　当面の環境構築の最終段階とも考えていますが、本日10月22日の午前中には、本件告訴状と連動した新規ブログをwordpress.comに追加しました。

　次のブログサイトになりますが、これで作業分担による付加の軽減と効率化を図っていきたいと考えています。実際の運用は、まだこれからの段階ですが、この項目がその試行錯誤の手始めとなります。

2016年告訴状＿金沢地方検察庁御中 | さらば弁護士鉄道＼泥棒神社の物語 https://hirono2016kk.wordpress.com/

　コマンドの実行でページタイトルを取得して気がついたのですが、wordpress.comのブログ名には、サブタイトルが含まれているようです。

　この他、10月13日の中断以降になると思いますが、Facebookページを一つ新規開設し、2013年のレンタルサーバのWordPressを復活活用させ、そのエクスポート処理で同期させたwordpress.comのブログも、先に一つ開設させています。

　新規作成したFacebookページは次になります。思うところがあって作成してみたのですが、思った以上に過去の投稿の表示や管理が難しく、近況としてのお知らせののみ向いたネットサービスという感じです。

殺人未遂事件を隠蔽した弁護士、元裁判官を刑事告訴／金沢地方検察庁御中 https://www.facebook.com/kanazawa2016/

金沢地方検察庁御中＿2016 | 記録作成等の措置を講ずるべき弁護士ツイート他 https://hirono2016s.wordpress.com/

　試験的に、上記の新規wordpress.comのブログと連携させていますが、投稿が連携されていないこともいくつか確認をしていて、Facebookページは緻密で柔軟な対応が、未だできていないか、容易ではないという印象を持ちました。リアルタイムなお知らせには向いているとは思います。

　復活させたレンタルサーバのWordPressのブログは次になります。新規に作成することも考えましたが、wordpress.comのようにブログの追加は簡単ではなく、全てサーバ管理の手作業にもなり、ディスク容量を含めた負担も大きくなるので、過去のものを再利用することにしました。

　そして、廉価のレンタルサーバのサービスでは、サーバの負荷でページの読み込みが著しく悪化することも、あらためて実感しました。アクセス数の増加を見込めば、実用性が極めて低下することになるかと思います。

　レンタルサーバでは、WordPressを自前で構築しています。そのメリットは大きいのですが、まずプラグインという機能の追加が自由に出来、データベースの管理も直接行うことが出来ます。

　必要不可欠と思うWordPressのプラグインとしては、拡張したバックアップがあり、月単位で期間を指定したバックアップが可能となります。ここでバックアップしたものは、wordpress.comにおいてもインポートでデータの取り込みが出来ます。

　以前は５MBだったようにも思うのですが、現在WordPressではインポートのデータサイズの上限が15MBとなっています。xmlファイルとなっているので、これを分割できれば問題はなくなるのですが、私が調べたところ、そのような乗法は見つかりませんでした。

　xmlファイルの内容を解析すれば、実態がテキストファイルなだけになんとかなりそうとは考えていますが、そこまで本腰を入れて取り組む気力もなく、無料のwordpress.comでは使えないプラグインに頼っているのが現状です。

　金沢地方検察庁御中＿2016 | 記録作成等の措置を講ずるべき弁護士ツイート他 https://hirono2016s.wordpress.com/ 、にインポートしたのは10月分だけですが、それでも11.5MBというデータサイズになっていました。

　本格的な記録作成としては、月に15MBのデータサイズの上限というのは満足のいけるものではありません。完全なる同期には不安が残るので、独自の使い分けを模索しています。

　WordPressの良い点は、APIからHTMLを反映させた投稿ができることと、APIでの投稿の返り値に、投稿した記事のIDを取得できることです。これは実に大きなメリットと言えますし、Bloggerに比較して大幅な作業の負荷軽減になります。

　APIでの投稿と同時に、投稿した記事のIDが取得できるので、その場で記事のリンクのURLを取得してデータベースに保存することができています。具体的には次のような記事のタイトルの取得と、IDでのURLの取得になります。

「光市母子殺害事件の時に弁護人に向けられた罵声を思い出します」という小倉秀夫弁護士のツイートと、死刑制度における冤罪問題,https://hirono2016kk.wordpress.com/?p=80
ブロックされていたことを確認した法律クラスタのタイムラインから考えた弁護士業界の宇宙的空間性と本人訴訟の問題,https://hirono2016kk.wordpress.com/?p=82
日弁連の死刑廃止宣言に関連した小倉秀夫弁護士、モトケンこと矢部善朗弁護士（京都弁護士会）、深澤諭史弁護士のツイートのまとめ,https://hirono2016kk.wordpress.com/?p=84
「女性新入社員の自殺 長時間労働が原因として労災認定」というニュースと、落合洋司弁護士（東京弁護士会）のツイートの本件告訴事件の関連性,https://hirono2016kk.wordpress.com/?p=86
探しだした「刑事訴訟愛好会」という小倉秀夫弁護士もメンバーになっていたFacebookページのスクリーンショット,https://hirono2016kk.wordpress.com/?p=88

　URLのｐというリクエストパラメータに渡した数値が記事のIDになります。これだとURLの長さもずいぶんと短く出来ますが、通常のwordpress.comの記事のURLだと、日本語のタイトルの一部がエンコードされ、とても長い意味不明のURLとなります。

　具体的には次のようなURLになります。

https://hirono2016kk.wordpress.com/2016/10/22/%e6%8e%a2%e3%81%97%e3%81%a0%e3%81%97%e3%81%9f%e3%80%8c%e5%88%91%e4%ba%8b%e8%a8%b4%e8%a8%9f%e6%84%9b%e5%a5%bd%e4%bc%9a%e3%80%8d%e3%81%a8%e3%81%84%e3%81%86%e5%b0%8f%e5%80%89%e7%a7%80%e5%a4%ab%e5%bc%81/

　URLだけで245文字となっています。ドメインより下のエンコードされた文字列は、「2016/10/22/探しだした「刑事訴訟愛好会」という小倉秀夫弁/」というものです。記事を特定できる情報とはなっていますが、IDの指定だと?p=88で終わります。

　とにかく、APIでの投稿時に返り値としてIDを取得できるメリットは大きいです。スクリプトにおいては、次の文字列の連結でURLを特定し、それをデータベースに登録しています。こういうのも試行錯誤で、自分で見つけ出し方法です。

entry_url = 'https://hirono2016kk.wordpress.com/?p=' + id

　意味不明の短縮URLを使わずに、URLの文字数を少なく出来るというのは、とくに文字数制限の大きいTwitterでは、とても役立つことです。ブラウザからの投稿だとそうでもないですが、TwitterAPIからの投稿だと、文字数のチェックはより大きな関門となっています。

　wordpress.comは、自分でサーバ管理を必要としないブログサービスです。普通に考えてのことですが、レンタルサーバのような割り当てられた範囲での通信負荷の問題も発生しにくく、帯域制限のようなものもないように思われますし、そのような負荷や制限は聞いたことがありません。

　サーバ管理の経験がないと理解の難しいことかとも思いますが、wordpress.comの活用は、画期的ともいえるメリットがあると考えています。無料での制限やデメリットもありますが、データベースの活用などで主要な部分はカバーできるものと見込んでいます。

　他に、WordPressの他のブログには余りない機能として、カテゴリの階層管理というものがあります。控え目に余りないと書きましたが、私は他に出来るサービスを知りません。

　2016年告訴状＿金沢地方検察庁御中 | さらば弁護士鉄道＼泥棒神社の物語 https://hirono2016kk.wordpress.com/ では、このカテゴリの階層管理を利用して、本件告訴状の項目の階層構造と対応させました。

　日々蓄積するデータの管理を容易にするためですが、これで項目間のブログ記事のリンクを介在させた連携を最大限強化し、本件告訴状の全体像の把握や無駄のない効率化に役立てたいと考えています。何かと限界を感じていたところで、突破口を開けた気分でもあります。

　WordPressのカテゴリの階層で管理するのは、項目の3階層までです。実際は3階層目のカテゴリ名が、管理の実態としてまとめ役を果たすことになるかと思います。また、無理のある細分化が適さない場合は、柔軟に2階層目でのまとめも考えています。

　項目間の連携の強化は、この項目が系列に属する珠洲警察署へ提出する書面の分量の削減と、負担の軽減を目的としています。裏を返せば、社会に全面公開されているインターネット上の情報の優先化にもなりますが、公開された情報を大前提としての作業をこれから進めることになります。

　個々の連携について、余り細かなご説明も紙面の都合上しないようにしていきたいと思います。つながりを全て書き出すことには無理もあり、非効率が大きいと考えるからです。有機的な関連ということは、個々の部分より全体像の意味内容を優先する基本方針の策定ということになります。

2016-10-22　土曜日　20：52　＜＜ ［［　←これまでの記述範囲の終了時刻］］＜＜
**** 「法科大学院は、新聞社にとっては大事な広告主だから、と勘ぐらざるを得ない」というブログ記事を紹介する深澤諭史弁護士と、その関連ツイートでの発見

:CATEGORIES: 名誉毀損の刑事告訴における具体的相談に先立ち、珠洲警察署に提出する準備書面
:TAGS: 深澤諭史弁護士,モトケンこと矢部善朗弁護士（京都弁護士会）

2016-10-22　土曜日　20：54　＞＞ ［［　←これからの記述範囲の開始時刻］］＞＞

／＊＊＊＊＊＊＊＊＊＊（引用開始）＊＊＊＊＊＊＊＊＊＊
引用URL＞＞＞＞：http://t-m-lawyer.cocolog-nifty.com/blog/2013/02/post-53be.html 朝日新聞の窓「憲法の使い方」（渡辺雅昭論説委員）にあきれる。: 弁護士のため息

税金の無駄遣いを言いたいのなら、なぜ法科大学院に対する補助金のことには触れないのか。

　法科大学院に行かないで司法試験に合格した予備試験合格組の方が就職では引き手数多ということは、市場が法科大学院の教育を評価していないことの証ではないか。

　なぜ、朝日新聞は、法科大学院制度こそ、税金の無駄遣いとして批判しないのか。

　法科大学院は、新聞社にとっては大事な広告主だから、と勘ぐらざるを得ない。

　朝日新聞は記事のデジタル版の殆どを有料とし、「新聞は公器である、新聞による言論は自由競争から守られるべきである」として再販制度の維持を訴えている。

　そこまで言うなら、法科大学院制度についても、国民に対して正確で公平な情報をきちんと提供して頂きたい。

＊＊＊＊＊＊＊＊＊＊（引用終了）＊＊＊＊＊＊＊＊＊＊／

　まずこの項目の冒頭に、上記ブログ記事の部分引用をご紹介しました。記録作成の意味合いがあるので、記事を読んだ時に近接した時間に作成した関連情報をスクリーンショットとして、次に掲載します。

投稿者：s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2016-10-22 18:35  ツイート： https://twitter.com/s_hirono/status/789762163367776256
2016-10-22-183542_朝日新聞の窓「憲法の使い方」（渡辺雅昭論説委員）にあきれる。：　弁護士のため息.jpg https://t.co/iOOwzcBCSK

投稿者：s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2016-10-22 18:35  ツイート： https://twitter.com/s_hirono/status/789762037425373185
2016-10-22-183512_朝日新聞の窓「憲法の使い方」（渡辺雅昭論説委員）にあきれる。：　弁護士のため息.jpg https://t.co/dZK0kygKeZ

投稿者：s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2016-10-22 18:34  ツイート： https://twitter.com/s_hirono/status/789761940746674176
2016-10-22-183449_朝日新聞の窓「憲法の使い方」（渡辺雅昭論説委員）にあきれる。：　弁護士のため息.jpg https://t.co/XtHDGJmP6s

投稿者：s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2016-10-22 18:14  ツイート： https://twitter.com/s_hirono/status/789756886367076354
2016-10-22-181444_makoto。a（@makotoakishige）さん　｜　Twitter.jpg https://t.co/BjB2vGQJ10

投稿者：s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2016-10-22 18:12  ツイート： https://twitter.com/s_hirono/status/789756385932169216
2016-10-22-181245_makoto。a　@makotoakishige　10月20日makoto。aさんが岡口基一をリツイートしましたただでさえ業務の割に報酬低.jpg https://t.co/RxYhdl0v5x

投稿者：s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2016-10-22 18:11  ツイート： https://twitter.com/s_hirono/status/789755941264642048
2016-10-22-181059_行政が、わずかなクレーマーのために結論をころころ変える例を嫌になる程見ているので、クレーマーに負けないことこそが政治家（行政のトップ）に求め.jpg https://t.co/LiYENWRv0p

投稿者：s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2016-10-22 18:09  ツイート： https://twitter.com/s_hirono/status/789755658107105280
2016-10-22-180951_先進国が日本の刑事司法をどう見ているか、中国と一緒、くらいの認識だろうなあ…。全事件可視化されてないし、立会い権もないし。保釈もだいぶ先だし.jpg https://t.co/2FB0PKE6Yb

投稿者：s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2016-10-22 18:03  ツイート： https://twitter.com/s_hirono/status/789753935363842048
2016-10-22-180300_深澤諭史さんがリツイート丙弁　@heibenn　6時間6時間前丙弁さんが深澤諭史をリツイートしました訴訟になったときに，弁護士付けずに本人.jpg https://t.co/guhNWLd4br

　上記のツイートの並びは上から見ると時間の順序が逆になっています。上のものほど最新のツイートになりますが、一連のスクリーンショットの記録は18時03分から始まり18時35分に終わっています。

　このスクリーンショットの作業の流れにあるように、深澤諭史弁護士がツイートで紹介していたリンクのブログ記事を開いて読んだのは、一連の最終工程となりました。

　初めの方に見たもので、ブログへのリンクを開くのが最終工程となったのは、深澤諭史弁護士の次のツイートが始まりです。

ツイート：fukazawas（深澤諭史）：2016/02/01 12:31： https://twitter.com/fukazawas/status/694000018747846656 ：
引用→　 朝日新聞の窓「憲法の使い方」＜改行＞https://t.co/eeW6Rg9qKr ＜改行＞「自衛官として危険をかえりみず事にあたることを求められる防衛大学校生と、司法修習生とを同列に論じるセンスもいかがなものか。」＜改行＞「渡辺論説委員の頭の中は、自衛官＞裁判官、検察官、弁護士　ということらしい」

 　上記の深澤諭史弁護士のツイートは、深澤諭史弁護士のツイートのスタイルの一つとして、誤解を与えやすいものと前々から考えてきたもので、自身のコメントのようなスタイルで、引用した記事の一部を部分引用したもののようです。

　むしろ初めに着目したのはその次の深澤諭史弁護士のタイムラインにおけるリツイートで、そのリツイートでは、上記の深澤諭史弁護士のツイートのURLを引用していて、深澤諭史弁護士のタイムラインにはサムネイルが表示されています。

リツイート：fukazawas（深澤諭史）＞2016/10/22 11:58／2016/10/22 11:49＞ https://twitter.com/fukazawas/status/789662074863439872 ＞
 heibenn （丙弁）＞ https://twitter.com/heibenn/status/789659998649405440 ＞
引用＞　 訴訟になったときに，弁護士付けずに本人訴訟でやってみたらいいと思われます。 https://t.co/8P9fZPGpNL 

　憲法問題と本人訴訟を絡めているところに目を引かれましたが、深澤諭史弁護士のリツイートされたアカウントは、たぶん初めて見るものでした。丙弁というプロフィールの名前になっています。

　丙弁というアカウントのタイムラインを開いて眺めていくと、よくよく見覚えのあるアカウントのツイートが多くリツイートされていました。色々と発見もあり、私の視野も広がったので、その辺りも記録としてのスクリーンショットを作成しました。

　クレーマーと行政を絡めて言及したモトケンこと矢部善朗弁護士（京都弁護士会）のツイートもリツイートされていましたが、これなどもモトケンこと矢部善朗弁護士（京都弁護士会）のタイムラインでは、見落としのあったツイートの発見です。

　モトケンこと矢部善朗弁護士（京都弁護士会）は私のことをクレーマーの一種だと思い込み、扱いをしてきたようですが、私は、石川県警察だけではなくそれを管理する立場である自治体の責務として、モトケンこと矢部善朗弁護士（京都弁護士会）の責任追及を記録とともに具体化する方針です。

　似たように、私が国の機関として金沢地方検察庁に促す対応は、非常上告という手続きでありますが、これも弁護士による憲法違反による権利侵害すなわち憲法問題ととらえており、私の主張の基本方針としての骨格をなすものであります。

　時刻は10月24日10時26分になっています。連鎖的関連として取り上げたい事柄が沢山出てきたので、中途半端になると思いますが、この項目は打ち切りにしたいと思います。

2016-10-24　月曜日　10：30　＜＜ ［［　←これまでの記述範囲の終了時刻］］＜＜

