**** 法曹は「社会の医師」だ　外国に馬鹿にされないために「質」高める法曹教育を　神戸大学特命教授・西村和雄

2016-09-03　土曜日　08：11　＞＞ ［［　←これからの記述範囲の開始時刻］］＞＞

　昨日読んだ記事です。深澤諭史弁護士や刑裁サイ太が法律家になっている現実との対比の上でもとても参考になる記事だったので、何箇所か引用してご紹介しておきたいと思います。まず、次の弁護士のツイートで記事を知りました。

リツイート：hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）＞2016/09/02 23:11／2016/09/02 09:39＞ https://twitter.com/hirono_hideki/status/771712170388258816 ＞
 masahirosogabe （曽我部真裕）＞ https://twitter.com/masahirosogabe/status/771507758050922496 ＞
引用＞　 「少なくとも、これ以上法曹の質を低下させる施策を打たないこと、良い取り組みはやめないことが重要」 西村先生は適性試験管理委員会委員ですね。／【正論】法曹は「社会の医師」だ　神戸大学特命教授・西村和雄  https://t.co/8jIKSDyxyS 

　弁護士と思われるアカウントですが、Twitterのプロフィールは次のようになっています。

＜2016年09月03日(土) 08時24分33秒にTwitterAPIで取得したmasahirosogabe（曽我部真裕）のプロフィール情報＞
憲法・メディア法。実務家としてはペーパードライバー（54期大阪４班）。学生さんのフォローも歓迎します（むやみにフォロー返ししたりしませんのでご安心を）。Professeur de droit constitutionnel à Kyoto http://t.co/uakMIi8b6u

　最後に行き着いたのが上記のアカウントだったと思うのですが、昨夜は初めて見ると思われた法律関係者と思われるアカウントが３つほどあり、そのうちリストに入れてなかったのは１つだけでした。つまり初見は１つだけだったことになります。

　いずれもブロックされていないアカウントです。私はFirefoxというブラウザでTwitterは@hirono_hidekiでログインした状態で使っています。ブロックされているアカウントのツイートは表示されませんが、Twilogなら見れるということを再確認しました。

　Twilogは検索の精度も不満がなく便利なのですが、最新過ぎるツイートが反映されなかったり、深澤諭史弁護士のように未登録だと最新の200件のツイートまでしか見ることが出来ないという制約があります。

　上記の法律家のアカウントは、その前にいくつかの法律家と思われるアカウントのタイムラインを辿っていました。こういう場合、リツイートでリンクを開くことが多いです。その3つ前だったように思いますが、次の気になるツイートがありました。

ツイート：lit_soc（とろろ）：2016/08/18 21:42： https://twitter.com/lit_soc/status/766254001729904640 ：
引用→　 茨城県警の性犯罪被害相談のページに性犯罪被害に遭った場合のQ&amp;Aが載ってる。＜改行＞オブラートに包まずかなり踏み込んでる感があるけど、重大な問題なのでこうやって情報提供することは大事だと思う。＜改行＞＜改行＞https://t.co/J6EcIMZENN

　初めて見たアカウントだと思いましたが、プロフィールの名前やアイコンは簡単に変更できるので、変更されてしまえばわからなくなることのほうが多いと思います。例外として@uwaaaaというような見慣れたユーザ名だと変更はすぐに気が付きました。

　意外に思ったのはツイートの内容より、そのリツイートの数の多さでした。9月3日8時40分現在、1455件となっています。「とろろ」という余り特徴のない名前が、気軽なツイートにつながった可能性もあるかと思いますが、それでも法律関係では多い数です。

　ともあれ、知らなかったより広い世界を覗いたような気持ちにもなりました。類友性の法則もあるのか、普段見ている深澤諭史弁護士や刑裁サイ太とは異なる法律家の世界をしばし巡り歩いた感覚で、行き着いた先が冒頭の記事でした。これから引用します。

／＊＊＊＊＊＊＊＊＊＊（引用開始）＊＊＊＊＊＊＊＊＊＊
引用URL＞＞＞＞：http://www.sankei.com/column/news/160901/clm1609010006-n1.html 【正論】法曹は「社会の医師」だ　外国に馬鹿にされないために「質」高める法曹教育を　神戸大学特命教授・西村和雄（1/4ページ） - 産経ニュース

≪型にはまった思考が障害に≫

　司法制度改革審議会が平成１３年に出した意見書では、「弁護士が、国際化時代の法的需要を十分満たすことのできる質の高い法律サービスを提供できるようにすべきである」と述べられている。そのための法科大学院の設置であったが、認可した法科大学院の数が多すぎ、必然的に法科大学院の修了者における司法試験合格者の割合は予定していた数値を大きく下回った。

　それに、司法試験合格者数の引き上げ目標が見直されたことが輪をかけた。法科大学院を経ないで司法試験の受験資格を得ることができる制度を予備試験制度として残したことが事態をさらに複雑にしている。そんな中で、文部科学省と中央教育審議会は法科大学院の受験者の適性を測るために実施している適性試験の任意化を検討し始めた。

＊＊＊＊＊＊＊＊＊＊（引用終了）＊＊＊＊＊＊＊＊＊＊／

／＊＊＊＊＊＊＊＊＊＊（引用開始）＊＊＊＊＊＊＊＊＊＊
引用URL＞＞＞＞：http://www.sankei.com/column/news/160901/clm1609010006-n2.html 【正論】法曹は「社会の医師」だ　外国に馬鹿にされないために「質」高める法曹教育を　神戸大学特命教授・西村和雄（2/4ページ） - 産経ニュース

法曹として海外に通用するかしないかは、司法試験の成績とは必ずしも比例しない。広く学んでいるかどうか、すなわち法律以外の分野、また法律なら司法試験科目以外の科目を理解しているかが深い洞察力と関連してくる。それゆえに、少数精鋭の教育で、より広く、本質的かつ実践的に学べる、法科大学院制度が始まったはずである。

＊＊＊＊＊＊＊＊＊＊（引用終了）＊＊＊＊＊＊＊＊＊＊／

／＊＊＊＊＊＊＊＊＊＊（引用開始）＊＊＊＊＊＊＊＊＊＊
引用URL＞＞＞＞：http://www.sankei.com/column/news/160901/clm1609010006-n2.html 【正論】法曹は「社会の医師」だ　外国に馬鹿にされないために「質」高める法曹教育を　神戸大学特命教授・西村和雄（2/4ページ） - 産経ニュース

法曹は「国民の社会生活上の医師」にも例えられる。医学部に無試験で入学できたり、医学部を修了しなくても資格試験さえ通れば医師になれるという状況を想像してみれば、法科大学院が存在すること、その入学に適性試験を課すことの意味が理解できよう。

＊＊＊＊＊＊＊＊＊＊（引用終了）＊＊＊＊＊＊＊＊＊＊／

／＊＊＊＊＊＊＊＊＊＊（引用開始）＊＊＊＊＊＊＊＊＊＊
引用URL＞＞＞＞：http://www.sankei.com/column/news/160901/clm1609010006-n3.html 【正論】法曹は「社会の医師」だ　外国に馬鹿にされないために「質」高める法曹教育を　神戸大学特命教授・西村和雄（3/4ページ） - 産経ニュース

法科大学院全国統一適性試験は、法律家としての適性として要求される論理的思考力を試す試験であり、知識ではなく、論理的判断力、分析的判断力、読解力などを測る基礎的問題から成る。作問には、理系・文系のこれはという優秀な研究者や実務家が関わっている。平成２３年度に、それまでの大学入試センターの適性試験と日弁連の適性試験が一本化したために、作問者はより一層充実した布陣になっている。

　適性試験の問題は、アメリカで、ロースクール志望者を対象に行われているＬＳＡＴをモデルとして作られている。法律の知識を必要とするわけでもなく、数学を使うわけでもない。一般常識の範囲の知識のみを前提として論理的思考力を測る試験という点で、他にないものである。クイズのような問題と誤解している人も多いようだが、思い付きを必要とする問題ではない。

＊＊＊＊＊＊＊＊＊＊（引用終了）＊＊＊＊＊＊＊＊＊＊／

／＊＊＊＊＊＊＊＊＊＊（引用開始）＊＊＊＊＊＊＊＊＊＊
引用URL＞＞＞＞：http://www.sankei.com/column/news/160901/clm1609010006-n4.html 【正論】法曹は「社会の医師」だ　外国に馬鹿にされないために「質」高める法曹教育を　神戸大学特命教授・西村和雄（4/4ページ） - 産経ニュース

適性試験があるから受験しない人もいると思うが、その多くは適性のない人たちである。適性試験を任意化するなら、課すのをやめることで、定員を満たす法科大学院も出てこよう。しかし先に述べた深い洞察力を持つ法曹養成改革の趣旨に逆行する。

　過去に、文科省は、大学院重点化の名の下に大学院生の数を増やした結果、大学院は受験科目を減らして無理やり定員を埋めざるを得なかった。学力が伴わない学生を大学院に受け入れ、博士号を持っていても就職先がない大量のポスドクが生まれた。そして、基礎学力に欠ける多くの技術者の存在が日本の競争力を危機に陥れている。同じことが法科大学院、そして法曹界で起きるであろう。

＊＊＊＊＊＊＊＊＊＊（引用終了）＊＊＊＊＊＊＊＊＊＊／

／＊＊＊＊＊＊＊＊＊＊（引用開始）＊＊＊＊＊＊＊＊＊＊
引用URL＞＞＞＞：http://www.sankei.com/column/news/160901/clm1609010006-n4.html 【正論】法曹は「社会の医師」だ　外国に馬鹿にされないために「質」高める法曹教育を　神戸大学特命教授・西村和雄（4/4ページ） - 産経ニュース

少なくとも、これ以上法曹の質を低下させる施策を打たないこと、良い取り組みはやめないことが重要である。そして、時間をかけて、法科大学院の総定員数と法曹への需要が均衡するのを待つべきであろう。神戸大学特命教授・西村和雄（にしむら　かずお）

＊＊＊＊＊＊＊＊＊＊（引用終了）＊＊＊＊＊＊＊＊＊＊／

2016-09-03　土曜日　09：43　＜＜ ［［　←これまでの記述範囲の終了時刻］］＜＜

