**** 「高畑ナニガシの事件については、その真相も、被害者の状況も、示談の内容も」についてはわかる必要も権利もない、というジャーナリスト江川紹子さんのツイート

:CATEGORIES: ジャーナリスト江川紹子さん
:TAGS: 示談交渉,ジャーナリスト江川紹子さん,高畑裕太氏の強姦致傷示談釈放事件


2016-09-11　日曜日　23：41　＞＞ ［［　←これからの記述範囲の開始時刻］］＞＞

ツイート：amneris84（Shoko Egawa）：2016/09/09 22:50： https://twitter.com/amneris84/status/774243522085990400 ：
引用→　 高畑ナニガシの事件については、その真相も、被害者の状況も、示談の内容も（今回の弁護士コメントを公表することが含まれていたのか否かさえも）、外部の私たちは分からないし、分かる必要も権利もないわけで、被害者側から格別の訴えがない限り、静かにしておくのがよいのではないか、と

　まず、なによりどうかと思われるのは、強姦致傷罪が無期懲役を含み5年以上の懲役という点を、ジャーナリストであるジャーナリスト江川紹子さんはどのように考えているのかという点です。親の立場であれば最悪、事件を起こした息子が一生刑務所の中ということも法律上はありうることになっています。

　冤罪問題や再審問題を、とりわけ裁判官の責任を厳しく追求してきたジャーナリスト江川紹子さんです。

　性犯罪には犯行を意図的に誘発し、賠償金をせしめる目的のいわゆる美人局も現に存在してきたわけで、その見極めを警察や検察にのみ押し付ける姿勢も、痛烈な批判を繰り返してきたジャーナリスト江川紹子さんだけに疑問も極めて大きい発言です。

　今回の事件でのジャーナリスト江川紹子さんは、被害者の立場を何より優先し、できるだけそっとしておくのが良いという判断のようです。このことはたまたまテレビで見たバイキングという情報番組で、生の発言を目にしました。

　事件が起きるまで24時間テレビのパーソナリティまで決まっているとは知らなかったですが、他のドラマや映画の撮り直しやお蔵入り、という問題をテレビで見ただけでも、ものすごい影響が社会的だと思いました。ジャーナリスト江川紹子さんの社会的認識には、それだけ疑問を大きくしました。

　この件に関してジャーナリスト江川紹子さんは、次のようなツイートをしてきたことがタイムラインから確認できます。

ツイート：amneris84（Shoko Egawa）：2016/09/09 17:03： https://twitter.com/amneris84/status/774156322199605249 ：
引用→　 被害者の方に、代理人弁護士はついていないのだろうか…？

ツイート：amneris84（Shoko Egawa）：2016/09/09 16:56： https://twitter.com/amneris84/status/774154568464670720 ：
引用→　 報道されたような事実ではなかった、との弁護士コメント全文 → 高畑裕太　顧問弁護士がコメント発表「悪質な事件ではなかった」 ― スポニチ Sponichi Annex 芸能 https://t.co/odlzwDIJfP

ツイート：amneris84（Shoko Egawa）：2016/09/09 14:17： https://twitter.com/amneris84/status/774114370599002112 ：
引用→　 グッディが「保釈」と打ってたから、いつ起訴されたのかと思ったら、不起訴で釈放とのこと →高畑裕太、不起訴処分が決定　被害者側と示談成立　９日中に釈放へ ― スポニチ Sponichi Annex 芸能 https://t.co/k64LjeNACH

　最新のツイートは次のもので、岡口基一裁判官に対するご意見とも受け止められるものです。

ツイート：amneris84（Shoko Egawa）：2016/09/11 22:28： https://twitter.com/amneris84/status/774962808349872128 ：
引用→　 @bilderberg54 @okaguchik 弁護人としては不可欠、なんてことはないでせう。

ツイート：okaguchik（岡口基一）：2016/09/11 18:40： https://twitter.com/okaguchik/status/774905493483458560 ：
引用→　 高畑側の弁護人としてはあの声明は不可欠だった。この示談は高畑側だけでなく、被害者側も望んでいたというのが大きなポイント。しかし「示談成立」だけで何の説明もなかったら、母親が高額の示談金で息子の罪をひねりつぶしたと思われかねなかった＜改行＞https://t.co/iKkCxe8LuD

　何度かタイムラインのツイートを確認しなおしましたが、郷原信郎弁護士のブログやツイートに対する反応というのはないようです。

　私はかねて強姦罪の厳罰化が、弁護士商売の威嚇力として利用されているのではないかという抱いてきました。そのうちと思いながら機会を逸し、本格的に取り上げることはなかったように思いますが、そんな折りに輪島大祭重蔵神社大祭の当日に事件は起こりました。

　ジャーナリスト江川紹子さんに対してもかねて根深い疑問と不信感を抱いてきました。ジャーナリスト江川紹子さんという立場を利用した私利の追求が優先され、後追いのようにもっともらしい理屈がこじつけられている、という思いがあったからです。

　弁護士に対して無批判、無問題という姿勢も、この俳優の強姦致傷事件に色濃く反映されたと感じています。「高畑ナニガシの事件」というのは、もともと余り知らない存在を意味するのかとも考えますが、あえてカタカナを使っているところに奇異を感じます。

　ジャーナリスト江川紹子さんはこれまで、郷原信郎弁護士や落合洋司弁護士（東京弁護士会）に好意的でリスペクトしたような態度をとってきたという印象があります。その郷原信郎弁護士は、モトケンこと矢部善朗弁護士（京都弁護士会）にツッコミを受けるほどの問題を提起しています。

　ＰＣ遠隔操作事件の真犯人が自供したあとにも、佐藤博史弁護士を弁護士として尊敬すると臆面もなくツイートしていたモトケンこと矢部善朗弁護士（京都弁護士会）ですら、疑問を感じた郷原信郎弁護士のツイートは、すさまじく異様なものと考えています。

　ジャーナリスト江川紹子さんに関しては、ＰＣ遠隔操作事件において真犯人の母親の立場をなんら慮らなかった、と判断される態度、姿勢にも異常なものを感じていて、高畑某というのは、母親を含むのかは別にして、母親の立場に無頓着な様が際立って感じられます。

　他にもいろいろありますので、今回、ジャーナリスト江川紹子さんに関してはこれくらいにしておきます。

2016-09-12　月曜日　00：28　＜＜ ［［　←これまでの記述範囲の終了時刻］］＜＜







