**** 「マスコミ」をキーワードにしたモトケンこと矢部善朗弁護士（京都弁護士会）のツイートの記録（2016年9月3日のまとめ分）

:CATEGORIES: モトケンこと矢部善朗弁護士（京都弁護士会）＜名誉毀損で刑事告訴予定＞
:TAGS: モトケンこと矢部善朗弁護士（京都弁護士会）,マスコミ

ツイート：motoken_tw（モトケン）：2016/08/29 18:44： https://twitter.com/motoken_tw/status/770195318025572352 ：
引用→　 芸能人というのは大変だな。芸能マスコミというのはこういうことをするのが当たり前なのね。＞ゲス川谷絵音　20代美女のお持ち帰り真っ最中に直撃取材《一問一答》（週刊女性PRIME） - Yahoo!ニュース https://t.co/ZTzbERZSkN #Yahooニュース

ツイート：motoken_tw（モトケン）：2016/08/27 20:42： https://twitter.com/motoken_tw/status/769500267192590336 ：
引用→　 マスコミの連中の思い上がりしか感じられない文章だな。＞高畑淳子さんにあの場で「息子の性癖について」。僕であったら聞くと思います。その理由です。 - 長谷川豊　公式ブログ　『本気論 本音論』 https://t.co/iMfQWl2env

ツイート：motoken_tw（モトケン）：2016/08/14 11:02： https://twitter.com/motoken_tw/status/764643326494511104 ：
引用→　 日本のマスコミ（海外は知らん）の連中の質問とかインタビューを聞いてると、あいつら絶対冤罪事件の取調べを批判する資格がない、といつも思う。

ツイート：motoken_tw（モトケン）：2016/07/28 20:20： https://twitter.com/motoken_tw/status/758623168282054657 ：
引用→　 .@jomaruyan マスコミが実名報道しなければ被害者の生きた証がなくなるとでも言うのか？思い上がりも甚だしい。

ツイート：motoken_tw（モトケン）：2016/07/28 09:28： https://twitter.com/motoken_tw/status/758459198287941633 ：
引用→　 .@shiho_watanabe 「議論が深まればと思います。」などと何を他人事みたいに言ってるんですか。マスコミが、あなたが議論を深めなければいけないんじゃないですか？あなたたちは報道被害の加害者なんですよ。

ツイート：motoken_tw（モトケン）：2016/07/27 18:10： https://twitter.com/motoken_tw/status/758227963699564544 ：
引用→　 .@wataitakeharu @yasuomisawa 遺族にとっては被害者の死後に残るのは被害者の名前だけではない。共に生きてきた思い出が残る。マスコミの取材攻勢によってその思い出を汚された人が数多くいると思えてならない。

ツイート：motoken_tw（モトケン）：2016/07/21 17:53： https://twitter.com/motoken_tw/status/756049337444995072 ：
引用→　 @kanenooto7248 マスコミの誤報は刑事裁判の冤罪に匹敵する深刻な被害を生じさせますよ。事実確認は全ての前提。「文春の鳥越さん誹謗中傷記事に対する岩上安身さんの連ツイ」 https://t.co/zD18DHLxJ8

ツイート：motoken_tw（モトケン）：2016/07/21 00:19： https://twitter.com/motoken_tw/status/755784136095248389 ：
引用→　 私は鳥越候補にかなり批判的ですが、粗探しに血道を上げるマスコミは大嫌いです。

ツイート：motoken_tw（モトケン）：2016/07/11 10:22： https://twitter.com/motoken_tw/status/752311969244295168 ：
引用→　 マスコミがもっときちんと野党を批判すれば、野党も軌道修正してもっとまともな選挙戦を戦えたかも知れない。与党に対する的はずれな批判は与党を利するだけだったみたい。

ツイート：motoken_tw（モトケン）：2016/07/11 19:18： https://twitter.com/motoken_tw/status/752446920702906368 ：
引用→　 マスコミは、３分の２がどうのこうの言ってる暇があったら、この自民党の憲法改正草案がいかに酷い改悪草案であるかをきちんと解説するべきではないのか。自分でできないならできる人を探せ。 https://t.co/2BCnIYUeXv

ツイート：motoken_tw（モトケン）：2016/07/11 10:19： https://twitter.com/motoken_tw/status/752311234653884416 ：
引用→　 一番バカなのは、改憲手続も知らず「改憲勢力」の改憲案の比較にも思いいたらなかったマスコミだろうな。

ツイート：motoken_tw（モトケン）：2016/07/11 08:57： https://twitter.com/motoken_tw/status/752290796452270080 ：
引用→　 野党もマスコミも有権者をバカにしすぎだと思う。

ツイート：motoken_tw（モトケン）：2016/07/03 22:20： https://twitter.com/motoken_tw/status/749593560291258372 ：
引用→　 マスコミの命にかかわる無責任さ。 .@kintoki_naruto さんの「週刊誌の「飲んではいけない薬」等の特集が医療の現場にもたらす弊害」をお気に入りにしました。 https://t.co/qGAr16b7El

ツイート：motoken_tw（モトケン）：2016/06/01 20:35： https://twitter.com/motoken_tw/status/737970711713587201 ：
引用→　 マスコミや国民の皆さんは彼の更生にどれだけ力を貸してくれるのだろう？＞尾木ママ、清原被告の“わびなし”を心配「変わる自分励ます機会逃したよう」（サンケイスポーツ） - Yahoo!ニュース https://t.co/pvjfrVJ61t #Yahooニュース

　上記のモトケンこと矢部善朗弁護士（京都弁護士会）のツイートを読んで、「泥棒風」を実質「泥棒風邪」と勘違いしていたことに気が付きました。弁護士の吹かす風の薄ら寒さを感じます。

ツイート：motoken_tw（モトケン）：2016/04/22 12:53： https://twitter.com/motoken_tw/status/723359033139195910 ：
引用→　 日本に関する限り、半分以上マスコミの問題だと思う。多分100%近く。 https://t.co/GdEXjc01cs

　上記のモトケンこと矢部善朗弁護士（京都弁護士会）のツイートは、次の櫻井光政弁護士のツイートのURLを引用しております。

ツイート：okinahimeji（櫻井光政）：2016/04/22 09:45： https://twitter.com/okinahimeji/status/723311671964364800 ：
引用→　 半分は政権のせいだが、もう半分は、命の危険もないのに政権のご機嫌をを伺うマスコミ自身のせいだと思う。"@SEALDs_jpn: なんで安倍政権になってから、報道の自由度はこんなに下がってるのか。11位→72位 https://t.co/7B2DwJWVvh"

ツイート：motoken_tw（モトケン）：2016/04/19 21:59： https://twitter.com/motoken_tw/status/722409309405978625 ：
引用→　 マスコミが現地で有意義な活動をしていると思われていたら、たいした問題ではないと思うのだが。＞“被災地で弁当調達”に批判、山中真アナが謝罪（日刊スポーツ） - Yahoo!ニュース https://t.co/VNUxvC0dvp #Yahooニュース

　上記のモトケンこと矢部善朗弁護士（京都弁護士会）のツイートは、熊本地震に関するものかと思います。同じ頃、深澤諭史弁護士も似たような趣旨で、ツイートやリツイートをやっていました。どちらも全く容赦のない厳しさを他人に向けると感じたものです。

ツイート：motoken_tw（モトケン）：2016/04/19 14:54： https://twitter.com/motoken_tw/status/722302344747098113 ：
引用→　 マスコミ関係者って、特権意識を持ってる人が多いと思う。自覚してない人が多そうだけど。

ツイート：motoken_tw（モトケン）：2016/04/11 19:08： https://twitter.com/motoken_tw/status/719467172997701633 ：
引用→　 マスコミって、こういう事件の冤罪の可能性というものを全く考えないのね。自分が書いた記事を読み直して疑問を感じないのかな？＜痴漢容疑＞「女性に触っていない」４３歳医師逮捕　福岡（毎日新聞） https://t.co/f108kcGsRa #Yahooニュース

ツイート：motoken_tw（モトケン）：2016/04/05 10:02： https://twitter.com/motoken_tw/status/717155533082402816 ：
引用→　 マスコミの犯罪報道にもいい加減な報道が多いし、弊害も大きいのだが、ネットにおけるど素人の知ったか犯罪解説にも困ったものだ。特に、藤原監督 @toshi_fujiwara のは害悪を垂れ流していると言っていい。

　上記のモトケンこと矢部善朗弁護士（京都弁護士会）のツイートについて、「いい加減な報道が多い」「弊害も大きい」とありますが、具体例をいくつ示せるのか疑問です。本人の基準では光市母子殺害事件の報道なども「刑事弁護に対する無理解」として範疇に含まれるのかもしれません。

ツイート：motoken_tw（モトケン）：2016/03/12 14:18： https://twitter.com/motoken_tw/status/708522515598024704 ：
引用→　 子供の甲状腺癌のこともそうだし、福一事故の放射線被曝の影響を強調する人たちは、強調することによって何がどうなると考えているのだろう？少なくとも、ツイッターやマスコミで流れている根拠で、東電に対する損害賠償請求訴訟の原告に有利になるとは思えない。他に何かいいことがあるのかな？

　上記のモトケンこと矢部善朗弁護士（京都弁護士会）のツイートについて。原発事故に対するモトケンこと矢部善朗弁護士（京都弁護士会）のスタンスは、各方面に批判を投げかけるものでしたが、本人の持論の根拠というのも不明瞭なものでした。あるあるパターンの一つかと思います。

ツイート：motoken_tw（モトケン）：2016/03/11 06:31： https://twitter.com/motoken_tw/status/708042585919647744 ：
引用→　 マスコミは、捜査段階で被疑者が否認したりすると「警察は容疑者を厳しく取り調べる考えだ」とか言って厳しい取調べを求め、または期待するような記事を書く。しかし、公判で被告人が厳しく取調べられて虚偽自白をしたと言うと厳しい取調べを批判的に報じる。マスコミは（国民も）何を求めている？

　上記のモトケンこと矢部善朗弁護士（京都弁護士会）のツイートについて。天上界の住人を思わせる実に弁護士らしいスタンスです。とてもわかりやすく顕在化しているので、弁護士業界におけるご神体のご威光を感じさせるものです。小倉秀夫弁護士にもよく似た傾向性があります。

ツイート：motoken_tw（モトケン）：2016/02/18 16:15： https://twitter.com/motoken_tw/status/700216991257337858 ：
引用→　 お医者さんは、マスコミに対する認識について、一般の人以上にかなり強いバイアスがかかっている場合が多いからな。

　上記のモトケンこと矢部善朗弁護士（京都弁護士会）のツイートについて。バイアスというのは圧力をかけるという意味かと思っていましたが、確認のため少し調べると「偏見」という意味合いがあるようでした。本人が理想とする刑事弁護の理解が基準になっているのでしょう。

ツイート：motoken_tw（モトケン）：2016/02/18 16:12： https://twitter.com/motoken_tw/status/700216396517511168 ：
引用→　 マスコミが、自浄作用を発揮しないで信頼を失って崩壊していくのは残念ですけど、崩壊すべきだと思います。大衆の信頼を失ったマスコミに存在意義はありません。一部の人は信頼し続けるかも知れませんが、それはもはやマスコミではないでしょう。 https://t.co/L3l0fSyqm8

　上記のモトケンこと矢部善朗弁護士（京都弁護士会）のツイートについて。前後のツイートの流れが気になるところですが、弁護士業界の不祥事、事件については、滅多に言及しないのも本人特徴です。最近は他の弁護士もおしなべてその傾向性が強くなったという印象があります。

ツイート：motoken_tw（モトケン）：2016/02/18 15:23： https://twitter.com/motoken_tw/status/700204041624662016 ：
引用→　 自分たちではマスコミの悪意に対して無力なのでお上がなんとかしてほしい、というお気持ちなのでしょうけど（その気持ちは理解できますが）、法律家はお上を信用しないんです。正確には、信用には限界があります。 https://t.co/9pa5q2sElS

ツイート：motoken_tw（モトケン）：2016/02/11 13:25： https://twitter.com/motoken_tw/status/697637448096985088 ：
引用→　 私のツイートが「過激」に見えるというのは、えらく楽観的なお人なのですね。最近、自民党の連中がマスコミ関係者を呼びつけているのを目の当たりにすると、現実的危機感を感じますけどね。 https://t.co/3645phzHOg

ツイート：motoken_tw（モトケン）：2016/02/09 18:37： https://twitter.com/motoken_tw/status/696991227460202496 ：
引用→　 そもそも、マスコミって偏向報道をするもんでしょ、という認識を持つべきなんじゃないかな。「モトケン氏、放送法の濫用に危惧する」 https://t.co/veos0h2U2d

ツイート：motoken_tw（モトケン）：2016/02/09 17:16： https://twitter.com/motoken_tw/status/696970935585255428 ：
引用→　 国家権力による報道の自由侵害の危険性（これは重大な憲法問題）に対する懸念より、マスコミの偏向報道姿勢に対する批判のほうが強いという風潮があるとすると、これは二重の意味で深刻な事態だと思う。「モトケン氏、放送法の濫用に危惧する」 https://t.co/HsljDV7EC5

ツイート：motoken_tw（モトケン）：2016/02/02 23:23： https://twitter.com/motoken_tw/status/694526669235712001 ：
引用→　 マスコミは判決前から有罪だと決めつけてるのではないか？「有罪ありきの報道」でしょ。それも実名で。 https://t.co/2zXWSb0tIn

ツイート：motoken_tw（モトケン）：2016/01/16 09:13： https://twitter.com/motoken_tw/status/688152137616896000 ：
引用→　 消費者の怒りは誰に向けられているのだろう？壱番屋に向けられている怒りがあるとすれば、それはマスコミの責任が大きい。＞廃棄カツ横流し　客、驚きと怒りの声 : 読売新聞＜改行＞ https://t.co/0tkF0OaUag

ツイート：motoken_tw（モトケン）：2015/12/01 10:53： https://twitter.com/motoken_tw/status/671507371659821056 ：
引用→　 マスコミ関係者から何度も取材を受けてきたが、刑事訴訟というものに対する無理解に辟易したことが多い。長谷川豊氏もそのようなマスコミ人の一人だな。野々村氏が被告人の立場にあることを全く理解していない。見出しでは被告と言ってるけど。 https://t.co/jivJFgsISg

ツイート：motoken_tw（モトケン）：2015/12/01 10:35： https://twitter.com/motoken_tw/status/671502749016571904 ：
引用→　 マスコミというのは大きな社会的権力だから、当然のこととして謙虚さや謙抑性が求められるはずだけど、この人には全く感じられないな。＞長谷川豊氏が苦言 野々村竜太郎被告への取材行動は「当然のこと」 #ldnews https://t.co/Jm2RytefEV

ツイート：motoken_tw（モトケン）：2015/12/01 10:21： https://twitter.com/motoken_tw/status/671499350460243968 ：
引用→　 「そんな連中が平然と生活しているのなら、我々マスコミはそれらを追いますし、なぜそんなことになったのか、当然報道します。その為に我らは存在しています。」 https://t.co/fVqoCu3ktv 犯罪者に対する私的制裁がマスコミの使命だ、と言いたいのか？そもそも平然じゃないし

ツイート：motoken_tw（モトケン）：2015/10/28 09:42： https://twitter.com/motoken_tw/status/659168401898663936 ：
引用→　 法律家の常識が、何十年たってもマスコミの常識にはならないのが不思議。

ツイート：motoken_tw（モトケン）：2015/09/20 09:35： https://twitter.com/motoken_tw/status/645395931794268160 ：
引用→　 いろんな点でマスコミの信頼性に疑問を生じさせた安保法案問題。＞高須クリニックのスポンサー撤退宣言に顔面真っ青になった報道ステーションが急に安保法案賛成派に転身  http://t.co/irYZcDKVEa

ツイート：motoken_tw（モトケン）：2015/08/22 08:53： https://twitter.com/motoken_tw/status/634876037726359552 ：
引用→　 マスコミというのは、昔から無神経の塊だ。

ツイート：motoken_tw（モトケン）：2015/06/28 13:47： https://twitter.com/motoken_tw/status/615018564597125120 ：
引用→　 こんなことを繰り返していると、マスコミは嘘つきの代名詞と言われることになるだろう。

ツイート：motoken_tw（モトケン）：2015/06/28 13:42： https://twitter.com/motoken_tw/status/615017363033866240 ：
引用→　 マスコミの自殺。そろそろネット時代では嘘はすぐバレて拡散するということに気づけ。＞池上彰氏の番組で韓国人のコメント捏造か 「日本嫌いですよ」実際は何と言った？ http://t.co/EX9uBwzV8U @HuffPostJapanさんから

ツイート：motoken_tw（モトケン）：2015/04/20 12:49： https://twitter.com/motoken_tw/status/589999240769773568 ：
引用→　 マスコミの政府批判に対し、政府が反論した場合に、マスコミが政府の反論を報道しなかったら問題だと思うけど、政府がマスコミに対して政府を批判するなとか言い出したら、そんな政府が民主主義を名乗るわけにはいきませんよ。そう思わないかな、安倍総理は？

ツイート：motoken_tw（モトケン）：2015/04/11 11:27： https://twitter.com/motoken_tw/status/586717298427351040 ：
引用→　 選挙の際に、現政権が選挙までの実績に基づいて批判されるのは当然でしょ。つまり、実績に基づいて批判するのがマスコミの仕事でしょ。それをしないマスコミなんかいらない。潰れた方がまし。実績に基づかないで印象操作をするマスコミも潰れるべき。民主主義にとって有害。

ツイート：motoken_tw（モトケン）：2015/04/05 14:22： https://twitter.com/motoken_tw/status/584586980945592321 ：
引用→　 このツイートのように、当事者やその家族知人が感情的になるのは理解できるが、マスコミにはもっと冷静な視点が求められる。RT @tcry3006: @motoken_tw 悪いのはトラックだよ。何も知らねーくせに語るな

ツイート：motoken_tw（モトケン）：2015/04/05 11:27： https://twitter.com/motoken_tw/status/584542775737212928 ：
引用→　 服役して責任を果たし、更生を誓って出所した人が、マスコミの実名報道によって就職することができなくなって、また犯罪の世界に舞い戻る人がたくさんいることをマスコミ人は知っているのか？そのような犯罪についてはマスコミは共犯者と言っていい。

ツイート：motoken_tw（モトケン）：2015/04/05 11:19： https://twitter.com/motoken_tw/status/584540960576708608 ：
引用→　 マスコミは、冤罪事件が発覚したときに、警察や検察を口を極めて非難するけど、実名被害者を犯人と決めつけて実名報道した自分たちのことは何も反省しない。

ツイート：motoken_tw（モトケン）：2015/04/05 10:05： https://twitter.com/motoken_tw/status/584522312038375425 ：
引用→　 日本に真っ当なジャーナリズムというものがあるのだろうか？思考停止のマスコミの記者か、偏りまくった運動家まがいの自称ジャーナリストしか目につかない。たぶん、私の視野が狭いだけだと思うが。

ツイート：motoken_tw（モトケン）：2015/04/05 09:57： https://twitter.com/motoken_tw/status/584520211145056257 ：
引用→　 記者というのは、自分の頭で物事を考えるということを忘れているのか禁止されているのか？日本のマスコミのレベルが垣間見える記事だ。

ツイート：motoken_tw（モトケン）：2015/03/07 21:42： https://twitter.com/motoken_tw/status/574188379824246784 ：
引用→　 .@roukoroshiya_k 被害者の尊厳を一番蹂躙してるのはマスコミだと思う。そして、それに追随するネット民。

ツイート：motoken_tw（モトケン）：2015/03/01 21:18： https://twitter.com/motoken_tw/status/572007977290469377 ：
引用→　 普段マスコミを批判している人も、凶悪事件報道の場合は簡単にマスコミ報道に乗っかって真犯人扱いする場合が多いのではなかろうか？８割以上は真犯人かも知れないが、起訴されない場合も真犯人でない場合もあるんだよ。

ツイート：motoken_tw（モトケン）：2015/01/15 21:09： https://twitter.com/motoken_tw/status/555698311555211264 ：
引用→　 マスコミの基本的な価値観というのは、権力と金だな。週刊誌レベルになると、それに性欲を加えて３大価値観になる。人間は、その三つで動いているという認識で記事を書く。

ツイート：motoken_tw（モトケン）：2014/08/13 20:51： https://twitter.com/motoken_tw/status/499523743996059648 ：
引用→　 マスコミが裁判の後の被告人の生活や人生を考えていることは絶対にない。＞RT

　上記のモトケンこと矢部善朗弁護士（京都弁護士会）のツイートについて。事件を起こした被疑者について極端に厳しいことをいうのも本人の特徴です。ケースバイケースといっても、他に類を見ない極端さがあって、それも熟慮など伴わない表面的なものです。。

ツイート：motoken_tw（モトケン）：2014/05/20 09:13： https://twitter.com/motoken_tw/status/468544995520049152 ：
引用→　 弁護士の事務所も24時間監視されてるみたいだな、マスコミに。

　上記のモトケンこと矢部善朗弁護士（京都弁護士会）のツイートについて。これも前後の発言の流れが気になるところです。Twilogを使えば簡単に調べることは出来ます。本人は深澤諭史弁護士と違いTwilogに登録していたので。

ツイート：motoken_tw（モトケン）：2014/05/20 00:13： https://twitter.com/motoken_tw/status/468409203535917058 ：
引用→　 @thermalpaper00 同感。そして、それをマスコミが無批判に報道しているようです。

　上記のモトケンこと矢部善朗弁護士（京都弁護士会）のツイートについて。北九州の現職警察官という感熱紙への返信が出てきました。必要性が高じたのでTwilogで調べます。

モトケン(@motoken_tw)/2014年05月20日 - Twilog http://twilog.org/motoken_tw/date-140520

＞＞＞＞＞以下、2014年5月20日のモトケンこと矢部善朗弁護士（京都弁護士会）のツイートあるいはリツイートをいくつかピックアップします。＞＞＞＞＞

ツイート：motoken_tw（モトケン）：2014/05/20 20:29： https://twitter.com/motoken_tw/status/468715105686159360 ：
引用→　 裁判員裁判事件では可視化してるんだから、遠隔操作事件でも可視化できないはずはなかったと思うが、それをしなかったのは、技術論で煙に巻かれることを恐れたのではないかと憶測している。検事の能力不足を自認しているようなものだ。

ツイート：motoken_tw（モトケン）：2014/05/20 20:08： https://twitter.com/motoken_tw/status/468709854790840320 ：
引用→　 後悔先に立たずというが、これまでの経緯について反省すべきなのは弁護団だけではないだろう。検察の捜査の下手くそさは、結果オーライで目立たないかも知れないが、本当に真剣に検証すべきだと思う。

ツイート：motoken_tw（モトケン）：2014/05/20 19:59： https://twitter.com/motoken_tw/status/468707491094986752 ：
引用→　 私も、可視化して、まっとうな取調べをすれば、彼は嘘を突き通せなかったのではないかと思う。以前にも書いた記憶があるが。

ツイート：motoken_tw（モトケン）：2014/05/20 19:56： https://twitter.com/motoken_tw/status/468706900612112384 ：
引用→　 読み応えがあった。誤字が多いけど。＞詳報・遠隔操作事件・佐藤弁護士会見その3：iesysを作るくらいのC#スキルはあった　「取り調べ可視化されていればもっと早く解決したのではないか」 (1/3) - ITmedia ニュース http://t.co/raGiDrRN3e

リツイート：motoken_tw（モトケン）＞2014/05/20 17:41／2014/05/20 17:37＞ https://twitter.com/motoken_tw/status/468672772873277440 ＞
 syuu_chan （しゅうちゃん＠そろそろなんか動き始め）＞ https://twitter.com/syuu_chan/status/468671817658286081 ＞
引用＞　 ゆうちゃん事件で弁護士が犯罪者を弁護していたから資格剥奪だの叫んでいる奴らがちらほらと見受けられる。弁護士の仕事がなんなのかまるで分かっていない、以前に法治システムの否定になっちゃっている。せめて自分が冤罪なのに捕まった時のことくらい想像すればそんなこと言えないと思うんだが… 

リツイート：motoken_tw（モトケン）＞2014/05/20 15:44／2014/05/20 15:26＞ https://twitter.com/motoken_tw/status/468643431707717632 ＞
 1961kumachin （中村元弥）＞ https://twitter.com/1961kumachin/status/468638796158754816 ＞
引用＞　 国選弁護人は、そんなに簡単に解任してくれません。被疑者・被告人が「実はやってました」と言ったときにも、被疑者・被告人の前で怒り狂うなど下の下。虚偽自白の可能性がないか確認した上で、「そうか、残念だが、君もウソをついていて辛かったろう」と言えるくらいでないと、やっていけません

リツイート：motoken_tw（モトケン）＞2014/05/20 15:43／2014/05/20 15:26＞ https://twitter.com/motoken_tw/status/468643244616593409 ＞
 terayasan （てらやさん☆）＞ https://twitter.com/terayasan/status/468638963343716354 ＞
引用＞　 マスコミが警察のリークを垂れ流すだけの拡声器になっている一方で，そういったマスコミの在り方を疑問視して立ち上がった人達が，結局，マスコミ対ミニコミ，捜査側対弁護側の二項対立に囚われて，反対側から弁護側の発信する情報を垂れ流すだけの存在になってしまったら，「どっちもどっち」だよね。 

リツイート：motoken_tw（モトケン）＞2014/05/20 15:42／2014/05/20 11:44＞ https://twitter.com/motoken_tw/status/468643007881703426 ＞
 okinahimeji （櫻井光政）＞ https://twitter.com/okinahimeji/status/468583105268166656 ＞
引用＞　 凶悪犯罪の被告人から、「真実の犯人は自分だが無罪を主張してくれ」と言われたときに、無罪主張に最善を尽くさなければならないのが刑事弁護の倫理です。有罪主張したら懲戒を受けます。その場合に残された道は辞任しかないけれど、いずれにせよ誰かがこの被告人を弁護しなければなりません。 

ツイート：motoken_tw（モトケン）：2014/05/20 15:40： https://twitter.com/motoken_tw/status/468642525163425792 ：
引用→　 無実の人を真犯人だと信じる心理と真犯人を無実だと信じる心理に違いがあるか思案中。ただし、刑事弁護人を除く。

　上記のモトケンこと矢部善朗弁護士（京都弁護士会）のツイートについて。刑事弁護士としての万能感を感じさせる発言です。ＰＣ遠隔操作事件については専用の項目をすでに用意していますが、これほど刑事弁護のお粗末さと恣意性を感じさせた事件はなかったという感想です。

リツイート：motoken_tw（モトケン）＞2014/05/20 13:38／2014/05/20 11:57＞ https://twitter.com/motoken_tw/status/468611681208127489 ＞
 montagekijyo （れもんた）＞ https://twitter.com/montagekijyo/status/468586200182558720 ＞
引用＞　 警察や検察が「クロ」と言い切ったとき、すべてのメディアがそれに無批判に乗っかってしまえば「権力の監視」ができない。捜査の強引さや立証の甘さを指摘できない。日本中を敵に回しても全力で守ってくれる弁護士がいてはじめて法治国家。自分が冤罪で逮捕されたら、ほんと怖いよ。 

リツイート：motoken_tw（モトケン）＞2014/05/20 13:05／2014/05/20 11:55＞ https://twitter.com/motoken_tw/status/468603511148519424 ＞
 okinahimeji （櫻井光政）＞ https://twitter.com/okinahimeji/status/468585688976207874 ＞
引用＞　 だから、自分は無実と言われた佐藤弁護士が被告人の無罪獲得のために全力を尽したことは、刑事弁護人として「見込み違い」「軽率」等と批判や揶揄されたりする理由は何もありません。的外れな批判・非難や嘲笑をする人は、刑事裁判のルールを知らない人です。もちろんそういう人でも批評は自由ですが。 

　上記のモトケンこと矢部善朗弁護士（京都弁護士会）のリツイートについて。先ほどから櫻井光政弁護士のツイートをいくつか扱っていますが、いずれも末尾に半角のスペースが一文字含まれているようです。

ツイート：motoken_tw（モトケン）：2014/05/20 12:50： https://twitter.com/motoken_tw/status/468599506125070336 ：
引用→　 陰謀的犯罪が陰謀的証拠隠滅行為によってばれたということで、彼の行動はすごく一貫している印象がある。

ツイート：motoken_tw（モトケン）：2014/05/20 10:12： https://twitter.com/motoken_tw/status/468559951548276736 ：
引用→　 弁護団が熱心で自信満々だと、かなり言い出しにくいだろうなと。弁護団を非難してるんじゃないですよ。犯人の心理の問題。RT @nobuyoyagi: それは思う RT @ogochan そもそも、彼が真犯人だったら、もっと早く楽になっておけば良かっただろう。

　上記のモトケンこと矢部善朗弁護士（京都弁護士会）のツイートについて。本人がどこまで本気で行っているのかわかりませんが、同じような裏目の顛末に対する同業者である弁護士と、マスコミ、警察、検察、裁判所への批評の格差の大きさやスタンスの違いを感じさせます。

ツイート：motoken_tw（モトケン）：2014/05/20 10:03： https://twitter.com/motoken_tw/status/468557527810985984 ：
引用→　 片山氏自認のニュースについてだけど、こういう重大な情報の出所が明確でないというのは、弁護団に大きな問題があると言うべきではないかな？

　上記のモトケンこと矢部善朗弁護士（京都弁護士会）のツイートについて。趣旨が不鮮明ですが、世間の反応をうかがうための、あたりとも感じられるツイートです。

ツイート：motoken_tw（モトケン）：2014/05/20 09:51： https://twitter.com/motoken_tw/status/468554481567682560 ：
引用→　 たしかに、漏らすタイミングとか漏らし方がね。RT @nyanmayu: NHK速報、出ましたねー。弁護団の先生方の気持ちを思うとなんとも。しかし漏らすの早すぎるような気も。

ツイート：motoken_tw（モトケン）：2014/05/20 09:46： https://twitter.com/motoken_tw/status/468553209993125889 ：
引用→　 弁護人に対して認めて、それが公になった以上、外野が何を言おうとこの裁判は終わりだが、こういう状況でも、被告人は闇の勢力によって認めさせられただけで真犯人は別にいる、と言う人が出てくるんだろうな。

　上記のモトケンこと矢部善朗弁護士（京都弁護士会）のツイートについて。迷走への誘導と期待が感じられるツイートです。水面下でみえにく本人の傾向性の一つかと思いますが、潜水艦が浮上した姿のようなものを感じました。

ツイート：motoken_tw（モトケン）：2014/05/20 09:31： https://twitter.com/motoken_tw/status/468549595492909056 ：
引用→　 弁護人は記者会見をするのかな？RT @ld_blogos: 【速報】遠隔操作事件 片山被告「私が真犯人」と認める（NHK）＜改行＞http://t.co/ANOGVwPDyB

リツイート：motoken_tw（モトケン）＞2014/05/20 09:29／2014/05/20 00:35＞ https://twitter.com/motoken_tw/status/468549118692847617 ＞
 yjochi （落合洋司（オンラインチャット相談対応可））＞ https://twitter.com/yjochi/status/468414623859740674 ＞
引用＞　 警察は、自称真犯人メールの件名の中で、脅迫の被害者をピックアップし、立件して、ガサ入れしたのだろう。ただ、本文でいきなり否定していて、せいぜい、ガサ入れが限度とは思うが。なんだか公安事件みたいだな。 

　上記のモトケンこと矢部善朗弁護士（京都弁護士会）のリツイートについて。落合洋司弁護士（東京弁護士会）は片山被告が犯行に関するメールを送った弁護士で、私見として、日頃のブログなどでの発言からＰＣ遠隔操作事件の誘因の一つになったとも考えています。

リツイート：motoken_tw（モトケン）＞2014/05/20 09:10／2014/05/20 08:54＞ https://twitter.com/motoken_tw/status/468544212447682560 ＞
 bilderberg54 （アルルの男・ヒロシ）＞ https://twitter.com/bilderberg54/status/468540115514437632 ＞
引用＞　 【速報】行方不明の片山祐輔被告が佐藤弁護士の事務所に現れる : すぽにゅー速 http://t.co/GZ7lAAllEi 

　上記のモトケンこと矢部善朗弁護士（京都弁護士会）のリツイートについて。このツイートの紹介記事で、モトケンこと矢部善朗弁護士（京都弁護士会）は、弁護士事務所もマスコミに24時間監視している可能性があるとツイートしたようです。

リツイート：motoken_tw（モトケン）＞2014/05/20 09:09／2014/05/20 08:59＞ https://twitter.com/motoken_tw/status/468543961854783488 ＞
 thermalpaper00 （感熱紙(リフレクターインコム)）＞ https://twitter.com/thermalpaper00/status/468541375797932032 ＞
引用＞　 泥縄的に法律ばかりが強化されて、現場では立件ポイントの変更で混乱が続くパターンですよねえ。 RT @ora3298: 自動車運転死傷行為処罰法ねえ、、、 

ツイート：motoken_tw（モトケン）：2014/05/20 09:03： https://twitter.com/motoken_tw/status/468542482788016128 ：
引用→　 何か片山情報があったのかな？

リツイート：motoken_tw（モトケン）＞2014/05/20 09:01／2014/05/20 08:52＞ https://twitter.com/motoken_tw/status/468541967714897921 ＞
 thermalpaper00 （感熱紙(リフレクターインコム)）＞ https://twitter.com/thermalpaper00/status/468539662303125505 ＞
引用＞　 ある手続きを批判するのにその手続きの仕組みを知らない、ってのはもはやテンプレだよなあ。 

ツイート：motoken_tw（モトケン）：2014/05/20 08:25： https://twitter.com/motoken_tw/status/468533008853901312 ：
引用→　 いずれにしても、弁護人としてはやるせない気持ちだろう。RT @massa27: 片山容疑者と連絡が取れないというニュースに対しては、やはり真犯人だから姿をくらませたと考える人と、そうまでして自分を追い込もうとしているのかという恐怖で……と考える人とに分かれそうだ。…

ツイート：motoken_tw（モトケン）：2014/05/20 00:20： https://twitter.com/motoken_tw/status/468410810209816577 ：
引用→　 @surgeonmizutani 私自身が告訴してますが。

ツイート：motoken_tw（モトケン）：2014/05/20 00:13： https://twitter.com/motoken_tw/status/468409203535917058 ：
引用→　 @thermalpaper00 同感。そして、それをマスコミが無批判に報道しているようです。

ツイート：motoken_tw（モトケン）：2014/05/20 00:02： https://twitter.com/motoken_tw/status/468406465854967809 ：
引用→　 @ktgohan 保釈取消請求をしたということは、それなりの証拠はあるんでしょうね。もちろん、捜査は現在進行形でしょうけど。

＞＞＞＞＞以上＞＞＞＞＞

ツイート：motoken_tw（モトケン）：2014/05/19 13:22： https://twitter.com/motoken_tw/status/468245240449871872 ：
引用→　 誰からの電話連絡が取れないと言うのだろう？マスコミからの電話なら、真犯人でなくても取らないよ。RT @47news: 速報:ＰＣ操作事件の片山祐輔被告、胃の検査を受ける予定の病院に姿を見せず、電話連絡が取れない状態。 http://t.co/XlnjDfhwH1

ツイート：motoken_tw（モトケン）：2014/05/14 08:25： https://twitter.com/motoken_tw/status/466358563775205377 ：
引用→　 しかし、実名報道する事件とは思えない。マスコミにはバランス感覚というものがないのか？実名報道の弊害を何も考えていないのだろう。つまり、マスコミは人権無視集団。

ツイート：motoken_tw（モトケン）：2014/05/14 08:08： https://twitter.com/motoken_tw/status/466354218828582913 ：
引用→　 マスコミには、逮捕の当否を批判的に検討するという意思も能力も感じられない。事実関係をもう少し確認しようと言う基本的観点がない。こんな簡単な権力批判さえできずに正義の味方の顔をするなと言いたい。

ツイート：motoken_tw（モトケン）：2014/05/10 11:05： https://twitter.com/motoken_tw/status/464949317447733248 ：
引用→　 ツイッター以前は、マスコミがいい加減なこと（ときには大嘘）を言っても、その検証結果が多くの人の目に触れることはなかった。情報流通をマスコミが握っていたのだから。しかし、今は違う。公の場で多角的に批判することが可能であり、マスコミもそれを無視できなくなっている。

ツイート：motoken_tw（モトケン）：2014/03/23 10:18： https://twitter.com/motoken_tw/status/447542782627164160 ：
引用→　 マスコミのレベルが上がるためには読者のレベルが上がるしかないんだろうな。そのためには小学校のときから批判精神とか論理的な議論の仕方をきちんと教える必要があると思うが、教師の中にもトンデモがいるので前途多難。

ツイート：motoken_tw（モトケン）：2013/12/07 21:02： https://twitter.com/motoken_tw/status/409291889565659136 ：
引用→　 まあ、マスコミは、秘密保護法については最も利害関係の強い当事者だから、客観的になれという方が無理かな。客観的になれないということは、一流じゃないと理解するけど。

ツイート：motoken_tw（モトケン）：2013/10/10 23:24： https://twitter.com/motoken_tw/status/388308938409930752 ：
引用→　 弁護士は、判決は正しいとは考えない。RT @horatio2chsi: @motoken_tw 元検事で弁護士でﾛｰｽｸｰﾙの教員のくせに、｢きっこのﾌﾞﾛｸﾞ｣やﾏｽｺﾐ報道をﾈﾀに(いくら断言していないと言い訳しても)｢冤罪の匂いがぷんぷんと｣とか言っているんですからね…

ツイート：motoken_tw（モトケン）：2013/07/10 12:47： https://twitter.com/motoken_tw/status/354809044311080960 ：
引用→　 この事件、示談で不起訴の可能性があるけど、ここまで実名報道されると人生オワタになるな。マスコミにそこまでの制裁権限を与えていいのかな？＞「裸の写真、撮ったから」２０歳女性に脅迫容疑、小学教諭逮捕 - MSN産経ニュース http://t.co/c8MKJZvJpw

ツイート：motoken_tw（モトケン）：2013/07/06 10:43： https://twitter.com/motoken_tw/status/353328326267502592 ：
引用→　 ネット以前は、電話にしろ手紙にしろ、マスコミを批判する方法は結構面倒臭かったからかなり憤りを感じてる人しか批判しなかったし、批判されたという事実をマスコミが握り潰すことも容易だった。しかし今は、多くの、ちょっと変じゃない、程度の疑問をもった人が直ちに批判を公にできる。

　上記のモトケンこと矢部善朗弁護士（京都弁護士会）のツイートについて。2013年7月の投稿になっていますが、当時も今も、弁護士が同じような批判の対照になるとは考えていないのか、と考えさせられる。今日もブロックされていることを確認。

ツイート：motoken_tw（モトケン）：2013/06/26 10:00： https://twitter.com/motoken_tw/status/349693579381309441 ：
引用→　 何の責任もない人の商売の邪魔をしてもいい、という理屈は通用しないだろう。マスコミだって。

ツイート：motoken_tw（モトケン）：2013/06/26 21:10： https://twitter.com/motoken_tw/status/349862160836460544 ：
引用→　 報道に従えば（それが真相みたいだけど）、この男の脳にはしわがないのではないか、と思えるほど超短絡的犯行だけど、現実に起こるんだな。RT @nhk_news: 男性殺害 妻の同僚の男を起訴 http://t.co/e3amRM7Mpj #nhk_news

　上記のモトケンこと矢部善朗弁護士（京都弁護士会）のツイートについて。Twilogで2013年6月26日を調べていて見つけたツイートです。今のところ「マスコミ」のみをキーワードに検索したものからピックアップしているので、「報道」だけでは出てきません。

　上記のモトケンこと矢部善朗弁護士（京都弁護士会）のツイートについて。本人の刑事罰に対して厳しい面があらわれているツイートですが、残念ながら引用しているNHKのニュース記事はリンク切れなので、内容はさっぱりわかりません。それほど大きな事件ではなさそうな感じです。

＃　さきほどの「何の責任もない人の商売の邪魔をしてもいい、という理屈は通用しないだろう。マスコミだって。」というモトケンこと矢部善朗弁護士（京都弁護士会）のツイートがどのような事実を指しているのかわかりました。

＃　一つ前とこれ以降は行頭に＃という記号をつけることで、私の言及として他のツイートの引用との区別をつけやすくしたいと思います。一つ最後におまけがありますが、直前の４つのツイートを次に引用というか掲載します。

ツイート：motoken_tw（モトケン）：2013/06/26 09:43： https://twitter.com/motoken_tw/status/349689305716895745 ：
引用→　 子供がグレるのは親の責任と言われても止むを得ないが、子供が親の悪行のとばっちりを食らうのはやりきれないな。とばっちりの最大の原因はマスコミなんだけど自覚はあるのかな？

ツイート：motoken_tw（モトケン）：2013/06/26 09:22： https://twitter.com/motoken_tw/status/349684000492756993 ：
引用→　 どこがです？無関係なものを関係づけてませんか？RT @dmburg: @motoken_tw なんと皮肉な話だ、と思いました。

ツイート：motoken_tw（モトケン）：2013/06/26 09:22： https://twitter.com/motoken_tw/status/349684000492756993 ：
引用→　 どこがです？無関係なものを関係づけてませんか？RT @dmburg: @motoken_tw なんと皮肉な話だ、と思いました。

ツイート：motoken_tw（モトケン）：2013/06/26 09:12： https://twitter.com/motoken_tw/status/349681503606800385 ：
引用→　 それがなにか？RT @dmburg: これは。。。父親が一千万円も詐欺してる一方で、子が「保険料納付してね」と広告に出演していたというわけ？！ http://t.co/3A4uVLcNOG

ツイート：motoken_tw（モトケン）：2013/06/26 03:22： https://twitter.com/motoken_tw/status/349593377446182912 ：
引用→　 .@sore50 さんの「烏賀陽弘道氏「福島県南相馬市の津波被災地（海岸部）に行くたびに、身の危険を感じます。そこで囲まれ、殴られ、つばをかけられる。レンタカーがボコボコにされる。」」をお気に入りにしました。なんなん.. http://t.co/tXzgkrxOtx

＃　最後のものがおまけになりますが、取り沙汰されている人物はジャーナリストで、かなりボロカスに言われた挙句ブロックされたという経緯がありました。当り屋か悪質なでっちあげという話もあったかと思いますが、そういえばと思い出しました。

　ほかの３つは同じ問題を指していると思いますが、最後の3つ目のツイートにある写真付きツイートを見て、やはりあの問題かと確認できました。親子の問題は別ということですっかり沈静化しましたが、そういえば、いくらか間をおいてから全くテレビで姿を見なくなっていたことに気が付きました。

モトケン(@motoken_tw)/2013年06月26日 - Twilog http://twilog.org/motoken_tw/date-130626

＃　なんかいつの間にかTwilogのページタイトルで指定した日付が日本語表記になっていたので驚きました。この日には他にも気になるツイートを見つけて、それもマスコミと関連付けられているので、それも掲載したいと思います。

ツイート：motoken_tw（モトケン）：2013/06/26 10:14： https://twitter.com/motoken_tw/status/349697112495226881 ：
引用→　 たしかに走り書きかな。＞ネット炎上で岩手県議が自殺との報に触れて http://t.co/StFybbyVky @cnet_japanさんから

リツイート：motoken_tw（モトケン）＞2013/06/26 10:16／2013/06/25 12:52＞ https://twitter.com/motoken_tw/status/349697752256614400 ＞
 nana_cchi7 （nanacchi）＞ https://twitter.com/nana_cchi7/status/349374629837680641 ＞
引用＞　 ネットで騒がれてるものをわざわざワイドショー番組が拾ってブログの意味すら分からない地元市議会議員に閉鎖したブログのコピーを読ませて地元で着火させて、テレビ番組きっかけで謝罪会見を新聞各社が報道して、自殺したら、ネットで炎上が原因かって言う報道になるんだね。 

ツイート：motoken_tw（モトケン）：2013/06/26 11:12： https://twitter.com/motoken_tw/status/349711767015923715 ：
引用→　 いや、もっとひどい。RT @Tanaka_Kei: マスコミが小泉議員のブログを炎上させた人たちがーネットの怖さがーって言ってるけど、お前らが多数で囲んで記者会見したことも同じようなもんだろうに

ツイート：motoken_tw（モトケン）：2013/06/26 13:00： https://twitter.com/motoken_tw/status/349738834646409216 ：
引用→　 ブログの炎上という現象は、既に数年前から頻繁に起こっていたことで、それをことさら取り上げて自殺の原因と考えるのは、問題の本質を見誤るのではなかろうか。

ツイート：motoken_tw（モトケン）：2013/06/26 13:03： https://twitter.com/motoken_tw/status/349739772715081728 ：
引用→　 ブログ炎上県議と言うよりワイドショーつるし上げ県議と言うべきでは？＞ブログ炎上の岩手県議自殺！TVワイドショーの一斉報道が引き金？ : J-CASTテレビウォッチ http://t.co/cc4aAgtXXr @jcast_newsさんから

ツイート：motoken_tw（モトケン）：2013/06/26 13:07： https://twitter.com/motoken_tw/status/349740734452207616 ：
引用→　 自分の発言を客観視できない人、つまり、批判的な他人の目に晒されたときに何を言われるか予想ができない人は、ブログとかツイッターをしないほうがいいのかも。

ツイート：motoken_tw（モトケン）：2013/06/26 13:12： https://twitter.com/motoken_tw/status/349742059890016257 ：
引用→　 特に政治家ならば、炎上を逆手にとって知名度を上げる、くらいの厚かましさが必要だろう。例の県議さんも、謝罪の仕方によっては大きく見方を変えることも可能だったろうに。

ツイート：motoken_tw（モトケン）：2013/06/26 13:22： https://twitter.com/motoken_tw/status/349744336151388160 ：
引用→　 無法地帯と考えたほうがよさそう。実力勝負ですね。RT @gartheimer: @motoken_tw そうすると現状匿名性が高いネットでの炎上騒ぎは、加害者の特定が困難なので…人権侵害があったとしても救済は難しいのですね…メディアスクラム（ネットも含めて）とか恐ろしいです…。

＃　「マスコミ」の検索結果からのピックアップに戻りたいと思います。今回はデータベースのデータを使っていません。一般的なTwitterの検索として実行した次のページの内容を使っています。なお、この検索は「高度な検索」とも呼ばれていますが、精度にはかねて疑問があります。

"マスコミ" from:motoken_tw - Twitter検索 http://bit.ly/2bGZKVi

＃　改めて「何の責任もない人の商売の邪魔をしてもいい、という理屈は通用しないだろう。マスコミだって。」というツイートを目にして思ったのですが、これがタレントの擁護とは思えず、世間の人の神経を逆なでした上での炎上狙いの燃料投下に思えます。弁護士にありがちな手法とも。

ツイート：motoken_tw（モトケン）：2013/06/23 12:21： https://twitter.com/motoken_tw/status/348641886870843393 ：
引用→　 仮にそうならフリーの人が公表すればいいでしょ。匿名だってかまわない。公になってることを記事にすることが怖いというのは理解できませんけどね。RT @igabin: @motoken_tw @ken_kataoka 激怒するからマスコミが公表を控えるんですよ。　担当記者の恐怖感は…

ツイート：motoken_tw（モトケン）：2013/06/20 09:38： https://twitter.com/motoken_tw/status/347513762246434817 ：
引用→　 マスコミを批判する論調はほとんど聞いたことがないですね。RT @yukokutaro: @motoken_tw そこの「マスコミの犯罪報道の問題」は問題です。何故そのような報道をすることになったのか。以前何処かの新聞社が「配慮」という言葉を使っていましたが、そのような報道が罷り通

ツイート：motoken_tw（モトケン）：2013/06/18 13:00： https://twitter.com/motoken_tw/status/346839810436116481 ：
引用→　 ツイッターをやっててマスコミ報道に不信感を強めた人は多いと思うが、だからと言って，ネットの情報が信頼できる保証もない。

ツイート：motoken_tw（モトケン）：2013/04/12 03:57： https://twitter.com/motoken_tw/status/322423166716739584 ：
引用→　 あのね、規範的評価と現状認識は別なんですよ。現状を無視した理論倒れイデオロギー弁護士は依頼者を不利にしますよ。RT @amneris84: @buvery でも、マスコミも弁護士までも（弁護人じゃないですよ）、再逮捕は当たり前という前提ですからね。@Kuria314

ツイート：motoken_tw（モトケン）：2013/03/08 00:09： https://twitter.com/motoken_tw/status/309682212654182400 ：
引用→　 医師に対する偏見はブログを書いてた当時と比較して大して変わってないみたいだ。やはりマスコミが変わらなきゃいけないんだろうけど、マスコミもステレオタイプが多いからな。

ツイート：motoken_tw（モトケン）：2013/03/04 02:07： https://twitter.com/motoken_tw/status/308262443799425026 ：
引用→　 情報提供側のバランスが取れても、受け手にバランス感覚がなければダメですよね。RT @amneris84: @motoken_tw マスコミと警察・検察双方の問題です。それが解消されない以上、弁護人や被疑者の言い分は、むしろ…、積極的に伝えていって、やっとこさっとこバランスが

ツイート：motoken_tw（モトケン）：2013/03/04 02:03： https://twitter.com/motoken_tw/status/308261410310352896 ：
引用→　 じゃ、記者会見に一本化すればいいと思いますけど、マスコミがそれでは満足しないでしょう。RT @amneris84: 匿名だと、何を言っても責任問われません。松本サリン事件で河野さんについてあれこれ言った警察官、何も責任問われていません。だからこそ、気楽にペラペラ言うんじゃ…

ツイート：motoken_tw（モトケン）：2013/03/01 22:18： https://twitter.com/motoken_tw/status/307479893782978560 ：
引用→　 マスコミって、、、無慈悲だな…

ツイート：motoken_tw（モトケン）：2013/03/01 11:33： https://twitter.com/motoken_tw/status/307317548599357440 ：
引用→　 マスコミや世論が変わらなきゃ有罪率を下げるわけにはいかないでしょう。RT @mash19jp: @motoken_tw やはり検察じゃなくて裁判所が判断する方が良いような気がします。でも、逮捕起訴されただけで犯人扱いだし生活メチャクチャだ( ；´Д｀)。それはマスコミ世論のせい？

ツイート：motoken_tw（モトケン）：2013/02/21 09:50： https://twitter.com/motoken_tw/status/304392571306770433 ：
引用→　 昨日の江川さんのインタビュー記事に関する私のツイートを、江川さんに対する批判またはマスコミ擁護と読む人がいるようだが、発信側のマスコミや江川さんではなく、受信側の読み手の受けとめ方の問題を指摘したものだったんだけどな。

ツイート：motoken_tw（モトケン）：2013/02/20 13:58： https://twitter.com/motoken_tw/status/304092641606369280 ：
引用→　 これも一つの情報操作。片面的かつ部分的な情報で全てを理解したような発言が多いな。RT @egg_rice: 【ＰＣ遠隔操作事件】片山祐輔さん無罪の可能性・・・警察「決定的な証拠があるというような情報はマスコミが勝手に」:ハムスター速報 http://t.co/Ls284PKe

ツイート：motoken_tw（モトケン）：2013/02/11 23:44： https://twitter.com/motoken_tw/status/300978609357742083 ：
引用→　 警察は、犯人をマスコミに教えて、犯人が逃げないようにマスコミに見張ってもらっていたのかな？

ツイート：motoken_tw（モトケン）：2013/02/11 12:09： https://twitter.com/motoken_tw/status/300803755140595713 ：
引用→　 端緒を得たマスコミが突っ込んだら言わんでもいいことまでべらべらと、という感じでは。RT @thermalpaper00: @motoken_tw 産経の報道を見ると、どうも「意図的なリーク」というより、「抜かれた結果」というのが正しいみたいですねえ。ただ、早い段階で「捜査が進展…

ツイート：motoken_tw（モトケン）：2013/02/11 08:45： https://twitter.com/motoken_tw/status/300752403760828416 ：
引用→　 これはもう、フライングと言うより暴走だな。 / “NHKが猫カフェで「盗撮」！遠隔操作犯逮捕の報道でマスコミへ批判集まる #nhk @nhk_tokuho - NAVER …” http://t.co/9p3AYtsZ

ツイート：motoken_tw（モトケン）：2013/01/25 13:40： https://twitter.com/motoken_tw/status/294665997883957250 ：
引用→　 マスコミには、事件関係者に当たり前のことを言わせてそれを報道することによって自分が安心する、というところがあるように思える。簡単に言うと、自己満足。

ツイート：motoken_tw（モトケン）：2013/01/25 10:20： https://twitter.com/motoken_tw/status/294615656404488192 ：
引用→　 被害者の実名だけが報道されるのであれば、被害者を知っている人がその事実を確認するにとどまるかも知れないが、多くのマスコミが自宅に押し寄せ外出すれば追いかけ、カメラを向けてマイクを突きつけるのは全く別の話。それによって顔とコメントが全国の何を考えてるのかわからない連中にも知られる。

ツイート：motoken_tw（モトケン）：2013/01/24 09:36： https://twitter.com/motoken_tw/status/294242343463292928 ：
引用→　 要するに、マスコミの中でも最も信用できる（私の勝手な妄想かも知れないが）と思われている大新聞の記者でも、その約束は全く信用できないことが明白になったわけであり、他のマスコミはさらに推して知るべし。

ツイート：motoken_tw（モトケン）：2013/01/24 08:39： https://twitter.com/motoken_tw/status/294228013187485696 ：
引用→　 マスコミは、誰であれマスコミが要求する取材に応じるのが当然の義務だ、と考えているようだ。

ツイート：motoken_tw（モトケン）：2013/01/23 13:09： https://twitter.com/motoken_tw/status/293933412409020416 ：
引用→　 マスコミとしては、刺激的な言葉が得られて満足なんだろうな。RT @livedoornews: 「殺してやりたい」遺族の無念 http://t.co/fsnGTLMq - ライブドアニュース

ツイート：motoken_tw（モトケン）：2013/01/22 22:01： https://twitter.com/motoken_tw/status/293704906492227585 ：
引用→　 しつこいけどさらに一言。マスコミが報道することによって人生の重みが増す、と言ってるように読めるのは曲解か？RT @pinpinkiri: …お名前は発表すべきた。それが何よりの弔いになる。人が人として生きた証しは、その名前にある。人生の重さとプライバシーを勘違いしてはいけない。

ツイート：motoken_tw（モトケン）：2013/01/18 08:54： https://twitter.com/motoken_tw/status/292057351471648768 ：
引用→　 ある！RT @sakamotomasayuk: 体罰をした教師ではなく受験生を罰してどうするんだろうね、この市長。マスコミが利用価値なしと判断したら叩き潰すのかもね。まあ、マスコミに捨てられないように必死なんだろうけど、マスコミも責任あるんじゃない？

ツイート：motoken_tw（モトケン）：2012/11/14 22:30： https://twitter.com/motoken_tw/status/268707429636784128 ：
引用→　 いまさらだけど、小沢氏の強制起訴に最も貢献したのはマスコミだと思う。

ツイート：motoken_tw（モトケン）：2012/11/14 12:49： https://twitter.com/motoken_tw/status/268561326425640960 ：
引用→　 検察が起訴したんだから犯人に決まってるじゃん、とか思ってる人間が、有罪率99%以上は高過ぎるとか言ってないかな。例えば、そこのマスコミ関係者の人。

ツイート：motoken_tw（モトケン）：2012/10/20 23:07： https://twitter.com/motoken_tw/status/259657001569759232 ：
引用→　 そういう面は否定できない。劇かどうかは別にして。RT @saintarrow: 裁判は被害者遺族や世間やマスコミの為に演じている劇か？ＲＴ @motoken_tw 被害者遺族や世間やマスコミじゃないのかな。

ツイート：motoken_tw（モトケン）：2012/10/20 23:03： https://twitter.com/motoken_tw/status/259656026314395648 ：
引用→　 一番自白を欲しがっているのは、被害者遺族や世間やマスコミじゃないのかな。RT @saintarrow: 君に当たっているわけではないが、簡単に捏造可能な自白を重要視するこれほど阿呆な事を許していては、法律関係者として当たられても仕方が無良いのでは？ＲＴ @motoken_tw

ツイート：motoken_tw（モトケン）：2012/10/12 12:30： https://twitter.com/motoken_tw/status/256597579821887488 ：
引用→　 マスコミは警察の誤認逮捕は批判するが、自らの誤認報道を反省しているように見えない。ん？よく思い出してみるとあんまり厳しく批判してないかな？きっと共犯だからだな。

ツイート：motoken_tw（モトケン）：2012/09/04 14:24： https://twitter.com/motoken_tw/status/242855580111351809 ：
引用→　 今の段階で憶測を述べても意味がないと思うが、商業マスコミとしては仕方がないか。＞目黒住宅街「三男ポリ袋殺人未遂」母親の異様…きょうだいの前で犯行 #ldnews http://t.co/DIj0Pw2F

ツイート：motoken_tw（モトケン）：2012/08/13 14:02： https://twitter.com/motoken_tw/status/234877482006876160 ：
引用→　 自分の知らない世界のことをどうしてあそこまで断言できるのだろう？　と、疑問に思うツイートは多い。きっと何かを鵜呑みにしているのだろうけど、その何かはマスコミかも知れない。そういう人がマスコミをdisっているのもよく見るのだが。

ツイート：motoken_tw（モトケン）：2012/07/19 20:23： https://twitter.com/motoken_tw/status/225913782231265286 ：
引用→　 マスコミが騒いだから。 RT @_nakim_: @motoken_tw 壁|･ω･`)…大津市のいじめで被害者の父親の告訴が受理されたのはどうしてでつか？＜改行＞自殺じゃなくて殺人かもしれないという噂が本当かもしれないからでつか？

ツイート：motoken_tw（モトケン）：2012/07/14 22:36： https://twitter.com/motoken_tw/status/224135226425753600 ：
引用→　 下衆どもが！ RT @jmr_er: テレビ番組の制作者も大津の中学校の在校生にマイクを向ける事がどういう事か理解できないかね？教育委員会も教師も最低ならマスコミの大人も最低だね。番組変えよう…(´-ω-`)

ツイート：motoken_tw（モトケン）：2012/07/11 16:55： https://twitter.com/motoken_tw/status/222962231569154049 ：
引用→　 ニュースバリューが理解できないと思います。ほんとに酷い事件なんですけど。RT @mabow: @motoken_tw @o2441 大阪弁護士会会長声明をマスコミは取り上げないのでしょうか？素人がみてお怖い事態い思えるのですが。

ツイート：motoken_tw（モトケン）：2012/06/28 11:15： https://twitter.com/motoken_tw/status/218165786106281984 ：
引用→　 ど素人が安田弁護士を批判するのはまあ仕方がないとして、マスコミはもうちっと刑事弁護を勉強したほうがいいんでないかな。プロから見ればそれなりに批判はあるけど、マスコミの批判の殆どは的外れというか刑事弁護制度に対する攻撃と言うべきものがある。

ツイート：motoken_tw（モトケン）：2012/06/28 10:59： https://twitter.com/motoken_tw/status/218161637889282050 ：
引用→　 “悪魔の弁護人”て初めて聞いた。マスコミがそう呼んでいるなら、ほんとにマスコミって無知無理解だ。＞毒カレー、オウム真理教、光市母子殺害……“悪魔の弁護人”と呼ばれる男の素顔『死刑弁護人』 http://t.co/Hcynqlby @cyzo #cyzoさんから

ツイート：motoken_tw（モトケン）：2012/06/16 18:39： https://twitter.com/motoken_tw/status/213928702361346050 ：
引用→　 マスコミの政治関連報道がかなり恣意的だということは、また、裏付けられたみたいだな。

ツイート：motoken_tw（モトケン）：2012/06/08 11:33： https://twitter.com/motoken_tw/status/210922474005733376 ：
引用→　 ですね。同時にマスコミ批判も。 RT @1961kumachin: @motoken_tw @thermalpaper00 結局は、法教育との同時進行で進めるしかないと思いますが。

ツイート：motoken_tw（モトケン）：2012/04/18 15:42： https://twitter.com/motoken_tw/status/192503448456003584 ：
引用→　 秋になったら、マスコミは企業がどのようにして乗り切ったのかをきちんと取材して報道してほしい。そうでないと、足りてるのか足りてないのか分からない。停電しなけりゃいいってもんじゃないから。RT @kazu1961omi: 夏を乗り切り、RT @GON_jpn @hazuma

ツイート：motoken_tw（モトケン）：2012/02/07 23:24： https://twitter.com/motoken_tw/status/166890057024811009 ：
引用→　 一部マスコミのニュースバリューというのは、つまり、金になるということなんだな。

ツイート：motoken_tw（モトケン）：2011/12/28 17:53： https://twitter.com/motoken_tw/status/151948907042181120 ：
引用→　 マスコミ関係者って、本当に法律に無知な人が多い。東電会長をめぐるツイートを見るとそれを再確認。

ツイート：motoken_tw（モトケン）：2011/10/15 22:25： https://twitter.com/motoken_tw/status/125200715407831040 ：
引用→　 一部のマスコミで石川知裕氏の取調べ時の録音が流れたようだ。それを聞いた弁護士の感想では、あれで任意性に問題が生じるのだろうか？という意見だった。裁判所の判断が興味深く待たれるところ。

ツイート：motoken_tw（モトケン）：2011/09/13 11:24： https://twitter.com/motoken_tw/status/113437816033259520 ：
引用→　 事実認定が証拠の評価である、ということは極めて重要です。評価というのは人間のつまり検事や記者、編集者の主観的判断であるということ。そこには常に誤りや恣意性が入る危険がある。検事や裁判官が事実誤認をすれば冤罪であり、マスコミがすれば誤報になる。つまり誤報は冤罪と本質的に同じ。

ツイート：motoken_tw（モトケン）：2011/09/13 10:31： https://twitter.com/motoken_tw/status/113424605548527616 ：
引用→　 さっきのツイートは健全な場合を言ったものであるが、検察もマスコミも、自分に都合のいい事実の証拠となる供述を集めようとする場合がある。そういう傾向はマスコミのほうがはるかに強いと感じられるが、たぶんその不健全性を自覚している記者やレポーターは少ないだろう。

ツイート：motoken_tw（モトケン）：2011/09/13 09:42： https://twitter.com/motoken_tw/status/113412246725603328 ：
引用→　 検察もマスコミも、その本来的目的は事実を明らかにすることだけど、両方ともしばしば自分に都合のいい事実を提示しようとする。（続く）。RT @ernanchan: @motoken_tw もう少し具体的におしえてほしいです。その類似点。

ツイート：motoken_tw（モトケン）：2011/09/10 22:43： https://twitter.com/motoken_tw/status/112521608811380736 ：
引用→　 自らの権力性に最も無自覚なのは、マスコミと裁判官だろうな。民主党の議員も似たようなものかも知れないけど。

ツイート：motoken_tw（モトケン）：2011/09/02 20:57： https://twitter.com/motoken_tw/status/109595911541370880 ：
引用→　 捜査情報をいくらマスコミにリークしても問題にならないけどな。＞捜査資料漏えい事件、捜査１課警部懲戒免職 : 社会 : YOMIURI ONLINE（読売新聞） http://t.co/dKtlsqi via @yomiuri_online

ツイート：motoken_tw（モトケン）：2011/09/01 00:58： https://twitter.com/motoken_tw/status/108931766752002049 ：
引用→　 マスコミは無反省。RT @yjochi: あの人は灰色なんだ、真っ白じゃないんだ、というレッテルが貼られることで、いかに、その後に深刻な影響が出るか、とううことも考えないと。軽々しく、あれは灰色だ、などと言うべきではないと思う。

ツイート：motoken_tw（モトケン）：2011/06/22 20:37： https://twitter.com/motoken_tw/status/83498967907840002 ：
引用→　 公知の事実と思ってたけど。RT @NakamuraTetsuji: 今日の民主党「検察のあり方ＷＴ」で法務省の幹部に占める検事（検察官・裁判官出身者）の状態を公開。多くの議員が実態を知らなかったようだ。こういう情報をマスコミは伝えない。６４人の幹部のうち４６人が検事。

ツイート：motoken_tw（モトケン）：2011/05/26 12:00： https://twitter.com/motoken_tw/status/73584333545418755 ：
引用→　 たしかにRT @yjochi: ただ、そういった捜査の問題点を、起訴不起訴の処分決定前に、マスコミが報道するということは、従来は極めて少なかったと思う。マスコミと警察、検察庁の、持ちつ持たれつの蜜月に変化が生じつつあるのかも。

ツイート：motoken_tw（モトケン）：2011/05/15 21:12： https://twitter.com/motoken_tw/status/69736880706551808 ：
引用→　 マスコミの法律音痴には以前から辟易していたが、原発音痴の程度はその100倍から1000倍くらいだろうな。

ツイート：motoken_tw（モトケン）：2011/03/16 08:22： https://twitter.com/motoken_tw/status/47799979900809216 ：
引用→　 マスコミは東電の下っ端社員を苛めても仕方がない。経営トップを引きずり出して徹底的に糾弾すべき。どうせトップの連中は事故対策には何の役にも立っていないのだから、すぐにでもやるべき。

ツイート：motoken_tw（モトケン）：2011/03/12 15:35： https://twitter.com/motoken_tw/status/46459207385493504 ：
引用→　 マスコミ各社は、記事の中の言葉が読者にどう受け取られるか冷静に考えているのか？目立つ言葉を使いたがっているのではないか？もしそうなら、視聴率稼ぎのテレビと同じだ。

ツイート：motoken_tw（モトケン）：2011/03/04 09:18： https://twitter.com/motoken_tw/status/43465194957062144 ：
引用→　 【例の事件】受験生が自らの行為によって将来の人生を含めて受けているペナルティの大部分は、マスコミによって与えられている。ペナルティが過大だというなら、その非難はマスコミに向けられるべき。

ツイート：motoken_tw（モトケン）：2011/03/03 17:43： https://twitter.com/motoken_tw/status/43230049788366848 ：
引用→　 予備校生の行為のどこかが何らかの犯罪になるか？RT @washer: では僕は素人目線です。マスコミがなぜこんなに騒いでいるのかわからないのです。刑法の玄人からみて、この事件には何か重要な問題があるのですか？ “@motoken_tw: 刑法。

ツイート：motoken_tw（モトケン）：2011/03/03 15:30： https://twitter.com/motoken_tw/status/43196462624030720 ：
引用→　 マスコミの辞書に「節度」の文字はない。

ツイート：motoken_tw（モトケン）：2011/02/25 11:43： https://twitter.com/motoken_tw/status/40965055398936576 ：
引用→　 取調べが可視化された後の問題として、どんな取調べが許容範囲でどんな取調べが違法なのか、任意性や信用性を損なうのか、という問題がある。多分、マスコミや殆どのジャーナリストはその判断基準を持っていないのではないか？

ツイート：motoken_tw（モトケン）：2011/02/23 01:43： https://twitter.com/motoken_tw/status/40089318978490368 ：
引用→　 警察や検察などの国家権力から不当な扱いを受けたと認められる人を、マスコミやジャーナリストは正義の象徴として祭り上げる傾向があるように感じられる。問題分析の放棄ではないのか？

ツイート：motoken_tw（モトケン）：2011/01/13 00:57： https://twitter.com/motoken_tw/status/25219921415770112 ：
引用→　 マスコミも検察と同じ道を歩む予感。RT @news_0: "なんで民意で選ばれてもいないマスコミに権威なんか持たせなきゃいけないんだよ ただ職業として選んだ人の集まりってだけじゃん" http://goo.gl/fb/Hdd1v

ツイート：motoken_tw（モトケン）：2010/12/29 23:49： https://twitter.com/motoken_tw/status/20129232453632000 ：
引用→　 現状の市民感覚やマスコミの報道姿勢を前提にすれば、逮捕によって生活が破壊される場合が大量に起こると思います。RT @Ichy_Numa: 推定無罪原則の徹底が前提になりますが、犯罪の構成要件に該当すると認められる事実が十分ある場合には、逮捕を義務付けることも一つの方法では？

ツイート：motoken_tw（モトケン）：2010/12/17 07:31： https://twitter.com/motoken_tw/status/15534633311535104 ：
引用→　 小沢氏の説明責任を強調するだけで、自ら疑惑に関する取材をしないマスコミは、供述依存の特捜部と全く同じだ。

ツイート：motoken_tw（モトケン）：2010/12/12 20:09： https://twitter.com/motoken_tw/status/13913242166362112 ：
引用→　 取材能力の限界かな。RT @ESQ_JPN: 私なんかはただマスコミてとその受け手のレベルが低く日本全体が未熟なのだと思ってしまいます。“@momozou: むしろその頃おこった検察／警察にまつわる様々な話題を消散させるために海老蔵の話題を積極的に拡げているようにも思いますね～。

ツイート：motoken_tw（モトケン）：2010/12/06 09:43： https://twitter.com/motoken_tw/status/11581349961924608 ：
引用→　 要するに、マスコミは感情で動いているということですね。RT @yokoyamamasato: スーパーモーニングの鳥越俊太郎。竹原前阿久根市長に対して「マスコミを敵に回したからこういう状況になった・・・」つい、本音が出てしまった。 #TVasahi

ツイート：motoken_tw（モトケン）：2010/11/14 12:18： https://twitter.com/motoken_tw/status/3647858276311040 ：
引用→　 そうですね。ただし、違いがあると言えば、警察や検察は上層部がリークを容認してるんですよね。RT @saorititi: @motoken_tw 航海士の件も合わせ、素人的には警察や検察がマスコミに情報を流すのと同じ様にしか思えない・・・法を学ぶ方にはかなり違うのかも知れないが。

ツイート：motoken_tw（モトケン）：2010/11/06 17:33： https://twitter.com/motoken_tw/status/827992032940032 ：
引用→　 国民というよりはマスコミじゃないのかな？マスコミがそう言えばそうかなと思う国民は多い。それも国民の罪かも知れないけど。RT @Koettbullar: 首相が短期間に変わるのはおかしい、そうやって民主党の路線をねじまげた国民の罪は重い。

ツイート：motoken_tw（モトケン）：2010/11/02 08:25： https://twitter.com/motoken_tw/status/29416572432 ：
引用→　 耳かき事件についてのテレビの報道を見ているが、どうしてマスコミは感情しか問題にしないのか？たぶん、感情以外の死刑のファクターを知らないか、知っていても考えるだけの能力がないのだろうと思う。

ツイート：motoken_tw（モトケン）：2010/10/27 01:04： https://twitter.com/motoken_tw/status/28804232061 ：
引用→　 取調べというものを取調べ経験者以外で最もよく理解できるのは取材のプロのマスコミ関係者だと思うのだが、自分のことを棚に上げる批判が多すぎやしないか？いや別に棚に上げてもいいんだが(^^;;

ツイート：motoken_tw（モトケン）：2010/10/25 20:59： https://twitter.com/motoken_tw/status/28683610600 ：
引用→　 最も責任の重いマスコミの中の人としては、どうすれば定着すると考えますか？RT @kazu1961omi: 大切なのは匿名報道よりも、逮捕=犯人ではない、起訴=有罪ではない、という当たり前のコンセンサスを定着させることだと考えます。

ツイート：motoken_tw（モトケン）：2010/10/25 16:43： https://twitter.com/motoken_tw/status/28669751296 ：
引用→　 ごく大雑把に言うと、自分がやっている事の意味が分からない状態を心神喪失というが、貸与制にした政治家たちは正にそれだ。賛成したマスコミも同じ。

ツイート：motoken_tw（モトケン）：2010/10/20 16:04： https://twitter.com/motoken_tw/status/27908971117 ：
引用→　 @thermalpaper00 全面可視化が実施された場合、その録画を見た弁護人が取調官の一挙手一投足、片言隻句をあげつらう事態が予想されます。そしてマスコミがそれに便乗してワイドショーで取り上げることでしょう。そうなると現場はやってられないでしょうね。

ツイート：motoken_tw（モトケン）：2010/10/16 10:36： https://twitter.com/motoken_tw/status/27497995938 ：
引用→　 検察も一緒かもRT @kmuramatsu: 最近、行き着くところまで行けば良いのではと思うようになりました。 RT こういうことを言うからマスコミ不信が増幅するんだ。ステレオタイプのマスコミは有害だ。＞ http://ow.ly/2UmWY (via @motoken_tw)

ツイート：motoken_tw（モトケン）：2010/10/16 09:59： https://twitter.com/motoken_tw/status/27495073350 ：
引用→　 こういうことを言うからマスコミ不信が増幅するんだ。ステレオタイプのマスコミは有害だ。＞産経【主張】「提訴の背景には検審不信があるのだろう。それは国民不信と言い換えていい。」 http://ow.ly/2UmWY

ツイート：motoken_tw（モトケン）：2010/10/12 21:31： https://twitter.com/motoken_tw/status/27133604703 ：
引用→　 彼女にとっては迷惑な話だと思うけどな。RT @onoda_oyanz: 既に週刊朝日では告発した女性検事の実名も顔写真も公開している。何故マスコミはモザイク匿名で隠すのか。 #shinso  #muraki

ツイート：motoken_tw（モトケン）：2010/10/09 23:55： https://twitter.com/motoken_tw/status/26849313211 ：
引用→　 マスコミの人にはせめて憲法の教科書を３回くらい読んで欲しいな。日本という国の仕組みに含まれている緊張関係をもっと理解してほしいと思う今日この頃。

ツイート：motoken_tw（モトケン）：2010/10/09 11:14： https://twitter.com/motoken_tw/status/26806241158 ：
引用→　 例外を無視して敢えて言うが、マスコミの連中は刑事司法の厳しさを何も分かっていない。

ツイート：motoken_tw（モトケン）：2010/10/09 10:14： https://twitter.com/motoken_tw/status/26802074329 ：
引用→　 取調べの可視化は不可避だと思うし、近い将来立法化によって実施されると思う。つまり、国民の選択として実施されることになるはずだけど、私のTLやマスコミを見る限り、どうも十分な情報が国民に提供されていると思えないな～。法務省の責任が一番大きいかも。説明がなさ過ぎる。

ツイート：motoken_tw（モトケン）：2010/10/08 17:30： https://twitter.com/motoken_tw/status/26729920769 ：
引用→　 やっぱり特捜部とマスコミは、よく似ているな。

ツイート：motoken_tw（モトケン）：2010/10/03 16:51： https://twitter.com/motoken_tw/status/26248389488 ：
引用→　 その一次情報を正確に理解できた医療者がどれくらいいるだろうか？RT @ERnanchan: おそらく、大野、大淀の裁判は、そういうマスコミ編集やスルーをいっさい許さない一次情報がネット経由で日本全国の医療者に配信され続けた最初の医療裁判ではなかろうか？

ツイート：motoken_tw（モトケン）：2010/10/02 13:25： https://twitter.com/motoken_tw/status/26146181785 ：
引用→　 公務員経験者としては、当時の生活実感とあまりに違う報道にうんざり。RT @oogami_sr: もうひとつ、マスコミは過剰に公務員を叩きたがります。マスコミが公務員叩きをしている時は要注意です。個人的な感情とは別に正しい事を知るべきです。

ツイート：motoken_tw（モトケン）：2010/09/25 18:27： https://twitter.com/motoken_tw/status/25484947867 ：
引用→　 私が、特捜部の検事と本質的な類似性を見出すのは、日々特ダネを追いかけているマスコミの記者の皆さんです。検事の証拠の捏造と記者の記事の捏造は同じものだと思います。記者の皆さんは、自分たちが官僚的だと言われたらどう思うでしょうか？多分、違うと思うのではないでしょうか。

ツイート：motoken_tw（モトケン）：2010/09/25 18:16： https://twitter.com/motoken_tw/status/25484471818 ：
引用→　 小沢氏に対する「政治とカネ」をマジックワードするマスコミの集団バッシングのときの山口一臣さん（ @kazu1961omi ）の反論はまったくそのとおりという感じで、マスコミの中にもこういう人がいるんだと救われる思いがしたのですが、検事のねつ造事件に関する認識はちょっと疑問。

ツイート：motoken_tw（モトケン）：2010/09/24 14:07： https://twitter.com/motoken_tw/status/25377236451 ：
引用→　 マスコミによって悲劇のヒーローに仕立て上げられた人がいる。私には必ずしもそうではないように見えるんだが。

ツイート：motoken_tw（モトケン）：2010/09/18 11:40： https://twitter.com/motoken_tw/status/24814187605 ：
引用→　 でっち上げと言うのは簡単ですが、でっち上げの中身を具体的に検討しないと、「政治とカネ」というレッテルを貼りまくったマスコミと同じです。

ツイート：motoken_tw（モトケン）：2010/09/18 10:46： https://twitter.com/motoken_tw/status/24810285876 ：
引用→　 @LedLine では、どうせ言うなら、でっち上げようとしたがそれに失敗した、と言うべきでしょう。これ以上は平行線ですね。しかし、あなたの言うでっち上げに加担した、というか実行したのはマスコミですよ。事実関係が明瞭になったあとも「政治とカネ」ではしゃいでいたのはマスコミです。

ツイート：motoken_tw（モトケン）：2010/09/18 09:38： https://twitter.com/motoken_tw/status/24805479463 ：
引用→　 @LedLine 小沢氏関連の事件で検察の政治的意図を協調するマスコミ関係者がいますけど、その根拠は薄弱と思います。検察は単に大きな魚を釣り上げたかっただけだと思いますけどね。それに失敗しただけであって、でっち上げとはちょっと違うかと。十分批判に値しますけどね。

ツイート：motoken_tw（モトケン）：2010/09/17 21:55： https://twitter.com/motoken_tw/status/24755181747 ：
引用→　 @ESQ_JPN マスコミは刑事事件というものも刑事弁護というものも、全然わかっていない、ということを思い知らされた事件でした。同時に、マスコミとして最も冷静さを求められるときに完全に冷静さを忘れてしまっているということも感じました。少しは反省しているのかしら？

ツイート：motoken_tw（モトケン）：2010/09/14 23:11： https://twitter.com/motoken_tw/status/24478543617 ：
引用→　 マスコミに取材力がないのなら、存在意義ゼロです。RT @masayukitakada: 過日、神保町でのシンポジウムにおいて「今のマスコミは取材力の劣化が最大の問題」と発言したら、岩波・世界の岡本編集長さんが「劣化なのか、元々なかったのがバレてきたのか」と鋭く反問。たぶん後者。

ツイート：motoken_tw（モトケン）：2010/09/14 19:16： https://twitter.com/motoken_tw/status/24463666066 ：
引用→　 これも検察と一緒。但し、検察に対しては証拠開示請求が強化されたが、マスコミにはなにもなし。RT @ERnanchan: メディアにとって強みのひとつは、都合の悪いデータであれば、報道しない　という黙殺が可能であることもかもしれない。

ツイート：motoken_tw（モトケン）：2010/09/14 18:38： https://twitter.com/motoken_tw/status/24461988803 ：
引用→　 祭は終わった、という感じですが、祭じゃすまないんですよね。どちらも積極的に支持していたわけではないのでどっちがよかったかはこれからの話ですが、それにしもてマスコミがこれほど個人攻撃をするとは少々驚きました。責任取れるんでしょうね、と言いたいところですが、取らないですよね。

ツイート：motoken_tw（モトケン）：2010/08/22 13:20： https://twitter.com/motoken_tw/status/21802963647 ：
引用→　 @motoyuki その意味では、有罪率以前の問題の方が大きいと思われます。起訴されて無罪になれば、マスコミも取り上げるし、刑事補償などが可能ですが、不起訴事例の殆どは泣き寝入りです。有罪率が高いということは、不起訴率が高いということです。

ツイート：motoken_tw（モトケン）：2010/06/16 22:27： https://twitter.com/motoken_tw/status/16305933110 ：
引用→　 そういう声はマスコミ関係者からも聞きます。法曹界でも同じような声が聞こえるのですが。しかし、「いまどきの若い者は」という相対論では済まされない問題があるように思います。RT @kjo091223: 記者の質も低くなったのでは？

ツイート：motoken_tw（モトケン）：2010/05/31 00:09： https://twitter.com/motoken_tw/status/15046897708 ：
引用→　 @bn2islander 本質部分は報道統制じゃないですけどね。マスコミが問題意識をもって主体的に判断して警察の顔色をうかがうようなことをしなければ、自浄作用を促すことはできると思うんですけど、現状では無理そうですね。

ツイート：motoken_tw（モトケン）：2010/05/16 19:33： https://twitter.com/motoken_tw/status/14091527727 ：
引用→　 @motoken_tw 第一に、マスコミには、「疑わしきは被疑者の利益に」の原則がない。

ツイート：motoken_tw（モトケン）：2010/04/29 07:58： https://twitter.com/motoken_tw/status/13033308826 ：
引用→　 まずマスコミに備わってほしいですね。RT @orz20100110 @ESQ_JPN　@motoken_tw 健全な市民感覚により強制起訴が出来る前提として推定無罪原則が市民に健全に備わっている必要がありますよね。

ツイート：motoken_tw（モトケン）：2010/04/17 14:48： https://twitter.com/motoken_tw/status/12327282140 ：
引用→　 @Ohmura_LAW 私は、弁護士のマスコミ対応の必要性を感じていますが、それは主としてマスコミによる被疑者・被告人及びその家族に対する権利侵害（つまり報道被害）を最小限度にしたいという考えによるものです。必ずしも裏返しの問題ではないと考えています。

ツイート：motoken_tw（モトケン）：2010/04/17 10:42： https://twitter.com/motoken_tw/status/12316693017 ：
引用→　 @ken_kataoka @amneris84 裁判官に対するマスコミ報道の直接的影響はあまり心配していません。何故なら、マスコミより裁判官のほうがはるかに多くの事件に関する情報を持っているから。より大きな問題は裁判官の情報処理能力の程度と基本的な姿勢ではないかと。

ツイート：motoken_tw（モトケン）：2010/04/02 10:16： https://twitter.com/motoken_tw/status/11454663150 ：
引用→　 マスコミは権威に弱い。言い換えると批判精神がない。つまりマスコミにはジャーナリズムがない。皮肉なことだ。RT @amneris84: もちろんです。ただマスコミや世間の目は、なかなか裁判所の責任に向かないので、あえて極論してみました

ツイート：motoken_tw（モトケン）：2010/03/22 21:52： https://twitter.com/motoken_tw/status/10870194836 ：
引用→　 @junichi_suzuki ブログを読んでくださってありがとうございます。弁護手法としては私も同意しかねるところが多かったです。但し、マスコミの論調とは全く別の観点からの意見ですが。ブログを読んでくださっていた皆さんはお分かりだと思いますが。

ツイート：motoken_tw（モトケン）：2010/03/22 17:39： https://twitter.com/motoken_tw/status/10863248246 ：
引用→　 @kohsak @fab4wings @crusing21 犯罪について、マスコミは必ずしも十分な情報を持っていないにもかかわらず、その自覚もなく、しかも比較的情報が多く得られる被害者側に偏った報道をする傾向があると思います。しかも自分たちが偏っているという自覚もない。

ツイート：motoken_tw（モトケン）：2010/03/16 12:47： https://twitter.com/motoken_tw/status/10552304843 ：
引用→　 @yoshirok @mmune @yoshirok 日本のマスコミはすごく権威に弱い。評価される側と評価する側を比べる時に、無条件で評価する側を信用する傾向があるように思います。評価が間違っている可能性をもっと考えろと言いたい。

ツイート：motoken_tw（モトケン）：2010/03/12 13:55： https://twitter.com/motoken_tw/status/10357505818 ：
引用→　 これには同意なんですけど、、、RT @NATROM: 「医療崩壊」がまだ世間に認知されていなかった昔は、医師の過重労働の話をしても、「いやなら辞めれば？」という反応が大多数。小松秀樹先生などが声をあげ、一部のマスコミの方々が伝えてくれたおかげで、非医療従事者のみなさんに現状を理解

ツイート：motoken_tw（モトケン）：2010/03/02 20:24： https://twitter.com/motoken_tw/status/9870265507 ：
引用→　 ことの本質が見えるマスコミ人というのは本当に数少ないのかも知れない。まあ当然のことなのだが、だったらわかっている人間に聞くという努力をもう少しするべきではないのだろうか。自分の感覚が正義だと思われたらたまらん。

ツイート：motoken_tw（モトケン）：2010/03/02 13:14： https://twitter.com/motoken_tw/status/9859077130 ：
引用→　 マスコミというのは、逮捕されたことは報道するが釈放されたことは報道しない。情報が警察に依存しているということは結果的に警察の肩を持つことになる。

2016-09-03　土曜日　18：44　＜＜ ［［　←これまでの記述範囲の終了時刻］］＜＜
**** 「実名報道」をキーワードにしたモトケンこと矢部善朗弁護士（京都弁護士会）のツイートの記録（2016年9月3日まとめ分）

:CATEGORIES: モトケンこと矢部善朗弁護士（京都弁護士会）＜名誉毀損で刑事告訴予定＞
:TAGS: モトケンこと矢部善朗弁護士（京都弁護士会）,実名報道

ツイート：motoken_tw（モトケン）：2016/07/28 09:27： https://twitter.com/motoken_tw/status/758458891000619008 ：
引用→　 .@shiho_watanabe 実名報道の問題は、犯罪の被疑者実名報道についてかなり以前から議論があるが、それが深まったという印象は何もない。マスコミは実名報道の弊害を無視し続け、ネット検索が一般化したことにより、その弊害は極大化している。その点の自覚はありますか？

ツイート：motoken_tw（モトケン）：2014/10/26 22:26： https://twitter.com/motoken_tw/status/526364124997906434 ：
引用→　 実名報道の必要性について、マスコミの皆さんは検証のためとか綺麗事を言うのだが、ほとんど社会的制裁以外の意味はないと思う。社会的制裁も犯罪抑止力の一つだけど、問題は、マスコミが冤罪つまり誤報と罪と罰のバランスを何も考慮しないことだ。

　上記のモトケンこと矢部善朗弁護士（京都弁護士会）について。このツイートは2014年10月になっていますが、本人は3ヶ月ほど前のツイートでテレビは持っておらず見ていないなどと語っていました。ろくに報道も見ていないのだと思います。

ツイート：motoken_tw（モトケン）：2013/03/25 11:46： https://twitter.com/motoken_tw/status/316018127425126401 ：
引用→　 軽微な犯罪で逮捕された人の実名を報道してその人の生活基盤を破壊すると、その後、その人がより悪質な犯罪を起す危険が増大する。より悪質な犯罪というのは、被害者の被害がより深刻であるということ。社会的に見れば、マスコミはその犯罪の共犯者と言うことができる。

ツイート：motoken_tw（モトケン）：2013/03/25 10:56： https://twitter.com/motoken_tw/status/316005749618794497 ：
引用→　 ネット時代の実名報道は、いつまでたっても名前で検索されたら事件の内容が分かられてしまう。これがどれだけ就職の障害になるか。これから真面目に生きよう、まっとうな生活をしたいと思っている元犯罪者の心を折るに十分な障害になることをマスコミの人達は少しでも考えたか？

＃　本当に更生の意欲や見込みがあるのか判断に必要な情報も全く与えようともせず、独善的な要求を突きつけるあたりも実に弁護士らしさがあります。清原被告の保釈時の映像は、そのことを特に強く感じました。彼もまたテレビで話題も耳にしなくなり、記憶から消えつつある存在となっています。

ツイート：motoken_tw（モトケン）：2013/03/08 00:09： https://twitter.com/motoken_tw/status/309682212654182400 ：
引用→　 医師に対する偏見はブログを書いてた当時と比較して大して変わってないみたいだ。やはりマスコミが変わらなきゃいけないんだろうけど、マスコミもステレオタイプが多いからな。

＃　そういえば、3週間ほど前になるかと思いますが、初めて「ステレオタイプ」という言葉の意味を調べてみました。拡声器のように吹聴、増幅というイメージでいたのですが、さにあらず、思い込みや偏見、差別という意味が並んでいました。モトケンこと矢部善朗弁護士で目にしてきた言葉の一つです。

＃　医師や医療問題というのもモトケンこと矢部善朗弁護士（京都弁護士会）が好んで取り上げる問題です。最近も大野病院事件のことを麻酔医のわいせつ事件と一緒くたにして取り上げていたかと思います。医師に対する不信や憎悪を煽っているのも弁護士に思えてなりません。

＃　そういえば、先ほど気になる記事を見つけて、気になる部分のスクリーンショットを作成しました。弁護士浜ちゃんこと濱田諭弁護士のタイムラインでリツイートとして目にしたものですが、当該弁護士は顔写真だったアイコンを、実が3つついた椰子の木の絵に変更していました。

＃　弁護士浜ちゃんのリツイートは、次のツイートになります。ちょくちょく見かけてきた弁護士アカウントですが、深澤諭史弁護士のタイムラインでは見かけていないように思います。

ツイート：ekinan_lawyer（えきなんローヤー）：2016/09/02 08:17： https://twitter.com/ekinan_lawyer/status/771487199208484864 ：
引用→　 2位の弁護士はやめておけ。特に若手。手取り収入が会社員未満のことも多々ある。今時医師ほどの難関でもないぞ。＜改行＞＜改行＞私の主人○○なんです♪　自慢したくなる夫の職業ランキングベスト3（マイナビウーマン） - goo ニュース  https://t.co/FH3No8EQXu

＃　次がスクリーンショットになります。ポイントの部分のテキストを、そのままファイル名に使っています。

[6419]  % h-api-twitter-user_timeline-format.rb s_hirono 5
投稿者：s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2016-09-02 14:14  ツイート： https://twitter.com/s_hirono/status/771577122603143169
2016-09-02-141451_結婚相手の理想として、回答者のうち７割以上の女性が選んだ職業が「医師」「医師または弁護士」でした。.jpg https://t.co/mo5HyBoSh1

投稿者：s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2016-09-02 14:11  ツイート： https://twitter.com/s_hirono/status/771576316323737600
2016-09-02-141138_「医師や弁護士」という回答が非常に多く、この二大職種が理想の最高峰と言えるでしょう。.jpg https://t.co/pIluBJORDZ

投稿者：s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2016-09-02 14:09  ツイート： https://twitter.com/s_hirono/status/771575830430388225
2016-09-02-140943_浜ちゃん（@satoshihamada）さん　｜　Twitterからの返信付きツイート.jpg https://t.co/fvO2uSdVg2

投稿者：s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2016-09-02 13:18  ツイート： https://twitter.com/s_hirono/status/771562809385553925
2016-09-02-131758_深澤諭史さんがリツイート￼深澤諭史　@fukazawas　　2014年6月12日医療に対する国民の信頼と理解を増進するため，一定規模以上の.jpg https://t.co/OR9AhD5FDJ

投稿者：s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2016-09-02 10:35  ツイート： https://twitter.com/s_hirono/status/771522009847115776
2016-09-02-103547_深澤諭史　@fukazawas　　30分30分前＞ＲＴ司法制度改革の歴史はポジショントークの歴史（・∀・）.jpg https://t.co/9wTjvwpX2w

＃　コマンド（自作のスクリプト）の実行で取得したのは最新のツイート5件です。告訴状に関連したTwitterアカウントは３つありますが、こちらは長い間、スクリーンショットやその他の写真など、写真付きツイートだけで使っているかと思います。

＃　深澤諭史弁護士も2,3日ほど前にTwitterのアイコンを変えて、今は怪獣映画のゴジラを模したものにして「非弁対ゴシラ　ベン・ゴシラ」という文字を入れています。なにか吹っ切れたような勢いも感じられ、自分を弁護士界を救う気概とパワーの持ち主と位置づけているようです。

＃　そういえば、本人の過去のツイートのリツイートになりますが（深澤諭史弁護士はよくやっています。）、医療問題と司法問題を同列において皮肉る意思表示をやっていました。少なくとも自身においてマイナスに働くという意識はないのでしょう。弁護士業界の印象はともかく。

＃　モトケンこと矢部善朗弁護士（京都弁護士会）によるマスコミ評がテーマであるこの項目の趣旨から外れますが、モトケンこと矢部善朗弁護士の医療問題に対する認識にも通じる認知の歪みが感がられるので、その参考としても２つ深澤諭史弁護士のツイートを取り上げます。

リツイート：fukazawas（深澤諭史）＞2016/09/02 12:54／2014/06/13 15:17＞ https://twitter.com/fukazawas/status/771556942648967168 ＞
 fukazawas （深澤諭史）＞ https://twitter.com/fukazawas/status/477333920715776000 ＞
引用＞　 医療に対する国民の信頼と理解を増進するため，一定規模以上の手術については，市民からくじ引きで選ばれた「医療員」を手術に参加させる。＜改行＞＜改行＞素人でも手術できるように「執刀前整理手続」をする。手術本体の数倍の時間をかける。＜改行＞＜改行＞#パラレル司法改革 

リツイート：fukazawas（深澤諭史）＞2016/09/02 12:54／2014/06/13 15:14＞ https://twitter.com/fukazawas/status/771556928874962944 ＞
 fukazawas （深澤諭史）＞ https://twitter.com/fukazawas/status/477333261417336832 ＞
引用＞　 医師国家試験の合格者数を３倍に増やす。＜改行＞自由競争で，腕の悪い医師は淘汰されて，良い医師だけが残る。＜改行＞苦しい医師は，必死になることで新たな何かが開かれてくる。＜改行＞破綻した医師？知ったことか！＜改行＞都市部で就職できない医師は，きっと無医村に行く。無医村問題も解決！＜改行＞#パラレル司法改革 

＃　いずれ本格的に取り上げる予定でいますが、モトケンこと矢部善朗弁護士（京都弁護士会）は過去のブログ運営において、ロースクール生であった深澤諭史弁護士に影響を与えた可能性もあるかと考えています。どちらも社会に害悪を撒き散らしているとしか思えず。除去装置の必要を考えます。

＃　よくテレビで経済効果の算出というのを目にしますが、弁護士による経済的なマイナス効果こそ計り知れず大きなものがあるのではと考えています。若手俳優の強姦致傷事件は今日もテレビの各局の番組で取り上げられていましたが、示談などしにくい状況にもされていると思いました。

＃　独立した項目として取り上げておく必要も感じているのですが、昨日は北陸中日新聞に気になる裁判の記事があって、夜に「懲役23年」として検索をすると、懲役30年の求刑の時とは違いけっこうな数の記事が見つかりました。ただ、同じ石川県でもテレビでは全く見ていないニュースです。

準強姦の５１歳男に懲役２３年　親族女性４人被害　「尊厳を無視」と金沢地裁 - 産経WEST http://www.sankei.com/west/news/160831/wst1608310068-n1.html

＃　今のところ、弁護士のツイートとしては情報をみていません。ここ数日間みていない奥村徹弁護士のタイムラインであれば、関連したツイートが見つかる可能性はあるかと思います。

＃　しっかり確認しておきたかったので8月30日までさかのぼりましたが、今日は9月2日なのにずいぶんな数のツイート数でタイムラインを遡るのもかなり時間がかかりました。諦めかけた頃、次の２つのツイートを見つけました。他に言及らしいものは見当たりませんでした。

ツイート：okumuraosaka（TORU OKUMURA）：2016/08/31 16:45： https://twitter.com/okumuraosaka/status/770890141397233665 ：
引用→　 検察側は準強姦罪で７件、児童福祉法違反罪で１件、暴行罪で３件起訴。併合罪の適用により準強姦罪の法定上限２０年の１・５倍に当たる量刑 https://t.co/9ntOh3vLxH

ツイート：okumuraosaka（TORU OKUMURA）：2016/08/31 16:43： https://twitter.com/okumuraosaka/status/770889765541470208 ：
引用→　 ・準強姦の５１歳男に懲役２３年　親族女性４人被害　「尊厳を無視」と金沢…＜改行＞［産経ニュース］＜改行＞ https://t.co/xEpX8ro2cL

＃　他に取り上げた弁護士アカウントはいないように思いましたが、念の為、次のようにTwitterの検索を実行しました。全体としてもツイートの数が少なく、ほとんど知られていないという感じです。

準強姦　懲役23年 - Twitter検索 http://bit.ly/2c9vlgb

[6413]  % h-api-twitter-user_timeline-format.rb s_hirono 5
投稿者：s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2016-09-02 16:32  ツイート： https://twitter.com/s_hirono/status/771611866262966272
2016-09-02-163254_準強姦　懲役23年　-　Twitter検索.jpg https://t.co/6TvUtEG3Uf

投稿者：s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2016-09-02 16:32  ツイート： https://twitter.com/s_hirono/status/771611796712980480
2016-09-02-163238_準強姦　懲役23年　-　Twitter検索.jpg https://t.co/o4lCK7IdqA

投稿者：s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2016-09-02 16:32  ツイート： https://twitter.com/s_hirono/status/771611716912164864
2016-09-02-163218_準強姦　懲役23年　-　Twitter検索.jpg https://t.co/0udc9qDeht

投稿者：s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2016-09-02 16:32  ツイート： https://twitter.com/s_hirono/status/771611654329032704
2016-09-02-163204_準強姦　懲役23年　-　Twitter検索.jpg https://t.co/sqJ33obhHG

投稿者：s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2016-09-02 16:09  ツイート： https://twitter.com/s_hirono/status/771606017872310272
2016-09-02-160940_TORU　OKUMURA　@okumuraosaka　　5時間5時間前広く弁護士一般の信頼も失わせたのはどうするんだ　「信頼頂ける弁護士へ.jpg https://t.co/8QE6sLl2gO

＃　スクリーンショットは、１つがおまけのようになっていますが、次の奥村徹弁護士のツイートのものです。リンクの記事の方はまだ開いていないですが、法テラス絡みの懲戒処分で話題になったタレントの女性弁護士の顔写真があり、ずいぶんとやつれていると感じました。

ツイート：okumuraosaka（TORU OKUMURA）：2016/09/02 10:41： https://twitter.com/okumuraosaka/status/771523350770294785 ：
引用→　 広く弁護士一般の信頼も失わせたのはどうするんだ　「信頼頂ける弁護士へ成長するため」テレビ出演当面見合わせ（デイリースポーツ） - Yahoo!ニュース https://t.co/baot4qwOj2 #Yahooニュース

／＊＊＊＊＊＊＊＊＊＊（引用開始）＊＊＊＊＊＊＊＊＊＊
引用URL＞＞＞＞：http://headlines.yahoo.co.jp/hl?a=20160902-00000030-dal-ent 大渕弁護士　テレビ出演当面見合わせを発表「ご信頼頂ける弁護士へ成長するため」 （デイリースポーツ） - Yahoo!ニュース

８月２日に東京弁護士会から業務停止１カ月の懲戒処分を受けた大渕愛子弁護士（３９）が業務停止期間が明けた２日、１カ月ぶりにブログを更新。「皆様からご信頼頂ける弁護士へ成長するために」と説明し、改めて当分の間テレビなどのメディア出演を控える意向を明かした。

　大渕弁護士は、依頼人から着手金を不当に受け取ったとして、８月２日に東京弁護士会から１カ月の懲戒処分を受け、以降、日本テレビ系「行列のできる法律相談所」（日曜、後９・００）出演などのタレント活動も休止していた。

＊＊＊＊＊＊＊＊＊＊（引用終了）＊＊＊＊＊＊＊＊＊＊／

＃　一部記事の引用をしましたが、8月2日だとちょうど一月前ということになりそうです。あえて本書で取り上げる必要はないと考えていたのですが、この懲戒処分になった問題は数年前にネットで複数の詳細な情報を見て知っていました。

＃　中には大渕愛子弁護士の父親が元検事長なので処分になるようなことはないという情報もみていました。検事長は余り見かけないので知らない人の方が多そうですが、全国に８つという高等検察庁のトップなので、相当の社会的立場なのだと思いました。

＃　他にも、被害を受けたという女性の方が、嘘がばれ窮地に立たされているというような情報を見かけた記憶もあります。そのうちテレビで大渕愛子弁護士の姿を見ても思い出すことがなく、すっかり忘れていた中での懲戒処分の報道でした。

／＊＊＊＊＊＊＊＊＊＊（引用開始）＊＊＊＊＊＊＊＊＊＊
引用URL＞＞＞＞：http://news.livedoor.com/article/detail/11858843/ 大渕愛子弁護士の不正発覚「この程度で済んで良かった」との声も - ライブドアニュース

問題の案件では、離婚後に元夫からの月5万円の養育費が滞って困窮していた経済的弱者に対し、不当な着手金だけでなく、月々2万1,000円の顧問料まで取っていた大渕弁護士。これには同業者からも「法に疎い相手の弱みにつけ込んだ悪質な詐欺」との批判まで聞かれる。

　そもそも大渕弁護士をめぐっては、過去にもトラブルが何度も伝えられていた。2年前、「週刊新潮」（新潮社）では「立て続けに依頼者に訴えられた行列のできる美人弁護士『大渕愛子』」という記事が載り、「着手金や顧問料を払ったのに、仕事に着手しなかった」という顧客の苦情が掲載。大渕弁護士はクレームに対し、警察に「ネットで中傷された」と事実無根の被害届を出し、警察に顧客のパソコンを押さえさせた――など、あまりにひどい行状が伝えられていた。

　これに対しては「被害者の会」までが発足したが、ほかにも相談者に美容サロンなどの勧誘をしていたなどという話も出ている。

＊＊＊＊＊＊＊＊＊＊（引用終了）＊＊＊＊＊＊＊＊＊＊／

＃　上記の引用にある「大渕弁護士はクレームに対し、警察に「ネットで中傷された」と事実無根の被害届を出し、警察に顧客のパソコンを押さえさせた」という部分は、信用がおけそうですが、何を仕掛けてくるかわからないというのも、弁護士の傾向性として参考になりました。

＃　大渕愛子弁護士の懲戒処分の件は、法クラや弁護士の間でツイートも比較的多かったと記憶しています。

＃　データベースで検索をしたら思っていた以上の数のツイートが出てきたので、法テラスか弁護士の懲戒処分の問題として新規項目を作っておきたいと思います。

ツイート：motoken_tw（モトケン）：2012/10/25 22:54： https://twitter.com/motoken_tw/status/261465853181169664 ：
引用→　 これは実名報道じゃないんだね。逮捕されてないからだと思うけど、逮捕するかどうかが警察の恣意的な判断なのに、逮捕かどうかで実名報道の基準にするマスコミはおかしくないか？＞事件隠蔽:前署長に罰金２０万円の略式命令　静岡簡裁 http://t.co/EwIeZSaa

ツイート：motoken_tw（モトケン）：2012/10/07 09:04： https://twitter.com/motoken_tw/status/254734015268024320 ：
引用→　 マスコミも、いい加減に逮捕段階での実名報道を考え直したらどうかな。

2016-09-03　土曜日　18：47　＜＜ ［［　←これまでの記述範囲の終了時刻］］＜＜

**** 「自然派」などという言葉にはとてもご都合主義の臭がする、というモトケンこと矢部善朗弁護士のツイートにみる弁護士世界の独善性

:CATEGORIES: モトケンこと矢部善朗弁護士（京都弁護士会）＜名誉毀損で刑事告訴予定＞
:TAGS: モトケンこと矢部善朗弁護士（京都弁護士会）

ツイート：motoken_tw（モトケン）：2016/09/12 10:22： https://twitter.com/motoken_tw/status/775142472557088768 ：
引用→　 「自然派」などといった言葉の「自然」には、とてもご都合主義の臭いがする。自分の生活全体を振り返って見れば、どこに自然があるのか（ほとんどない）わかると思うが、そういうところは無視。

　上記のモトケンこと矢部善朗弁護士（京都弁護士会）のツイートを出発点にしたいと思いますが、昨日から特に気になっていることがあり、それがずっと前から続くもやもやで、なかなか先に進むことが出来なかった要因の一つであるとも思いました。

　「自然派」が何を意味する言葉なのか、私は他に知識がありませんが、それらしいことは、さらに数日前のモトケンこと矢部善朗弁護士（京都弁護士会）のツイートで見ていました。

リツイート：motoken_tw（モトケン）＞2016/09/10 23:43／2016/09/08 21:03＞ https://twitter.com/motoken_tw/status/774619294428647424 ＞
 NonbeeKumasan （林　智裕）＞ https://twitter.com/NonbeeKumasan/status/773854240787697664 ＞
引用＞　 「自然派」を名乗る人達に限って都会に暮らしてるのってなんなの？＜改行＞過疎地に生きて自然の雑草の侵食に抗い、無農薬野菜を作ろうとして害虫に畑を滅ぼされ、外を歩けば虻に狙われブユに刺され、家の屋根裏はスズメバチに占領され、玄関先には蛇とムカデ、最寄りの買い物に10キロ歩いてこそ本懐では。 

ツイート：motoken_tw（モトケン）：2016/09/10 13:54： https://twitter.com/motoken_tw/status/774471147471540224 ：
引用→　 .@motoken_tw こういう子供に育てたいというのであれば、365日24時間干渉し続ける必要があるかも知れない。 https://t.co/uQwreVXBQD ＜改行＞人生最大の悲劇は、子供は親を選べないということだな。

　上記のモトケンこと矢部善朗弁護士（京都弁護士会）のツイートは次のツイートのURLを引用しています。

ツイート：sweetkitten0707（自然派ママ☆ココ）：2016/09/10 13:37： https://twitter.com/sweetkitten0707/status/774466705493942276 ：
引用→　 子供に個性があるように、家庭にも個性はあり、その家庭によって育児の方針は違い、「良い子」の基準は変わりますよね。うちでの良い子の基準は、大人の言うことを何でも聞いて、絶対に口答えせず、大人の期待に応える子のことです。よそは違うかもしれませんが、うちはうちです。@mozuku929

ツイート：motoken_tw（モトケン）：2016/09/10 13:37： https://twitter.com/motoken_tw/status/774466741090988032 ：
引用→　 自然派ママさんたちは、どうして服を着てるんだろう？

リツイート：motoken_tw（モトケン）＞2016/09/10 13:30／2016/09/09 23:22＞ https://twitter.com/motoken_tw/status/774465068222124032 ＞
 danjishihou （都 行志 Miyako Koji）＞ https://twitter.com/danjishihou/status/774251653591478272 ＞
引用＞　 マスコミにいた弁護士として思うのは、事件のことをマスコミに話しても一銭の得にもならないどころか有害だということ。彼らは最初からストーリーを決めていて、都合の良いコメントを使おうとするから、意図しない報道がされることが多い。功名心からかマスコミにベラベラ話す弁護士は、信用できない。 

リツイート：motoken_tw（モトケン）＞2016/09/10 13:30／2016/09/10 12:18＞ https://twitter.com/motoken_tw/status/774464990505947137 ＞
 tangeganbaru222 （パパ小児科医）＞ https://twitter.com/tangeganbaru222/status/774446879832612865 ＞
引用＞　 いわゆる自然派ママでワクチン全く打ってない人に、ワクチンを勧めた時の反論で一番驚いたのが、＜改行＞＜改行＞「この水晶球の力で免疫力を上げる」でした。＜改行＞＜改行＞（イラスト：https://t.co/LcMmOPRCab） https://t.co/Zt4dPzjdeo 

ツイート：motoken_tw（モトケン）：2016/09/10 13:28： https://twitter.com/motoken_tw/status/774464432642457600 ：
引用→　 生後間もなくはともかく、365日24時間親に干渉され続けたらどんな子供に育つことやら。 https://t.co/ODIsLHk9iD

　上記のモトケンこと矢部善朗弁護士（京都弁護士会）のツイートは次のツイートのURLを引用しています。

ツイート：sweetkitten0707（自然派ママ☆ココ）：2016/09/10 00:18： https://twitter.com/sweetkitten0707/status/774265812043431938 ：
引用→　 @kaoru13375786 私たち保護者は365日24時間、親という仕事をしています。休みという概念なんてありません。心臓が休んだら体は死んでしまうのと同じことです。貴方は甘いのではありませんか？教育を何だと思っているのですか？

リツイート：motoken_tw（モトケン）＞2016/09/10 13:23／2016/09/09 22:50＞ https://twitter.com/motoken_tw/status/774463264876965888 ＞
 amneris84 （Shoko Egawa）＞ https://twitter.com/amneris84/status/774243522085990400 ＞
引用＞　 高畑ナニガシの事件については、その真相も、被害者の状況も、示談の内容も（今回の弁護士コメントを公表することが含まれていたのか否かさえも）、外部の私たちは分からないし、分かる必要も権利もないわけで、被害者側から格別の訴えがない限り、静かにしておくのがよいのではないか、と 

ツイート：motoken_tw（モトケン）：2016/09/10 11:55： https://twitter.com/motoken_tw/status/774441177680449537 ：
引用→　 強姦事件において、相手が嫌がっているのに合意があったと誤解した場合、理論的には故意を欠くとして無罪になるが（異論があるかも知れない）、それは加害者が処罰されないだけで、被害者は厳然と存在する。なお、同じ言い訳が何度も通用すると思ったら大間違い。

ツイート：motoken_tw（モトケン）：2016/09/10 09:13： https://twitter.com/motoken_tw/status/774400289164054528 ：
引用→　 .@T_akagi この赤木智弘という人のお仕事はフリーライターらしいけど、この人から取材を受けたら、話したことと真逆の内容の記事を書かれると思ったほうがいいな。もし、意図的な曲解でないなら、小学校に入り直して国語の勉強をする必要がある。

ツイート：motoken_tw（モトケン）：2016/09/10 01:04： https://twitter.com/motoken_tw/status/774277293766082561 ：
引用→　 .@T_akagi この人の日本語の読み方はかなり特異だな。個人的な好き嫌いがツイートに反映するタイプの一人なのだろう。

ツイート：motoken_tw（モトケン）：2016/09/10 00:10： https://twitter.com/motoken_tw/status/774263742611591170 ：
引用→　 @kawai_shintaro @thermalpaper00 ああいうコメントを公にすることも示談内容になっていたのかどうかが気になります。

ツイート：motoken_tw（モトケン）：2016/09/09 19:18： https://twitter.com/motoken_tw/status/774190307286003712 ：
引用→　 被害者が納得しているのであれば何の問題もないが。

リツイート：motoken_tw（モトケン）＞2016/09/09 18:58／2016/09/09 17:03＞ https://twitter.com/motoken_tw/status/774185174619688960 ＞
 amneris84 （Shoko Egawa）＞ https://twitter.com/amneris84/status/774156322199605249 ＞
引用＞　 被害者の方に、代理人弁護士はついていないのだろうか…？ 

リツイート：motoken_tw（モトケン）＞2016/09/09 18:45／2016/09/09 17:41＞ https://twitter.com/motoken_tw/status/774182007676948481 ＞
 uwaaaa （サイ太）＞ https://twitter.com/uwaaaa/status/774165713661464577 ＞
引用＞　 このおねーちゃん弁護士がコメント考えたの？ 

リツイート：motoken_tw（モトケン）＞2016/09/09 18:45／2016/09/09 17:37＞ https://twitter.com/motoken_tw/status/774181986822873088 ＞
 fukazawas （深澤諭史）＞ https://twitter.com/fukazawas/status/774164769259401216 ＞
引用＞　 某事件の弁護人のコメントって，ほんと・・・？？？＜改行＞デマだと信じたい・・・・。 

ツイート：motoken_tw（モトケン）：2016/09/09 17:09： https://twitter.com/motoken_tw/status/774157812888850432 ：
引用→　 このコメントは被害者の認識と一致してるのだろうか？どんな示談交渉が行われたのかとても興味がある。このようなコメントを公にすることの当否も問題になりそう。＞高畑裕太氏釈放、弁護人のコメント全文：朝日新聞デジタル https://t.co/5cDQNshxnr

ツイート：motoken_tw（モトケン）：2016/09/09 15:19： https://twitter.com/motoken_tw/status/774130053298794497 ：
引用→　 .@jcast_news  「検察官の中に、有罪にできる事件だけを起訴しようというものがあるなら、反省すべきだと思いますね」これはどういうことだろう？私は（多くの検事も）有罪にできる事件というか有罪にできると確信できた事件だけを起訴してきた。もちろん、捜査を尽くした上での話だが。

ツイート：motoken_tw（モトケン）：2016/09/09 15:07： https://twitter.com/motoken_tw/status/774126998545272832 ：
引用→　 @binbo_cb1300st 示談交渉をするのは、被疑者（依頼者）が自供している場合ですので、自供しているのに嫌疑不十分という処分は普通はしないと思います。

ツイート：motoken_tw（モトケン）：2016/09/08 19:50： https://twitter.com/motoken_tw/status/773835803407454208 ：
引用→　 こんな話を信じる人はいないだろうというのは残念ながら甘い考え なのだが、信じた本人が痛い目を見るのは自業自得としても、子供に被害が及ぶから無視できない。「自然派ママの新常識　「火傷はあたためる☆」」＜改行＞ ⇒ https://t.co/uAoodiXA6i #アメブロ

ツイート：motoken_tw（モトケン）：2016/09/08 19:05： https://twitter.com/motoken_tw/status/773824467281731584 ：
引用→　 誰かに殴られて怪我をした場合は、同じところをさらに殴ってもらうと怪我が治るということかな？＞ 「自然派ママの新常識　「火傷はあたためる☆」」＜改行＞ ⇒ https://t.co/uAoodiXA6i #アメブロ @ameba_officialさんから

　ようやく目的のツイートにたどり着くことが出来ましたが、ずいぶんと沢山のツイートを遡り、何かの手違いで削除されたのかと考え始めたところでした。9月8日のツイートになっています。これが、「自然派ママ」を見た最初でした。

　確かに問題のある非常識な発言を指摘したのかもしれませんが、それにしてもモトケンこと矢部善朗弁護士（京都弁護士会）の独善的な攻撃性が如実にあらわれており、他に言いようがないものかとも思うし、強烈な毒性を伴った不快臭を放ちます。

　このようなモトケンこと矢部善朗弁護士（京都弁護士会）の態度、姿勢はいまに始まったことではなく、自分がいったん正しいと思えば、見境のない攻撃性を発揮してくるのがモトケンこと矢部善朗弁護士（京都弁護士会）の人格反応であって、私もその被害者です。

　昨日は、「自然派」がなにを意味するのかモトケンこと矢部善朗弁護士（京都弁護士会）のタイムラインだけではわからなかったので、他にいくつか調べました。初めに調べたのが、こたんせ、のツイートでした。

　モトケンこと矢部善朗弁護士（京都弁護士会）は次の、こたんせ、のツイートをリツイートしています。

ツイート：kotadon（こたんせ～君が落ち着け）：2016/09/12 09:56： https://twitter.com/kotadon/status/775135865702010880 ：
引用→　 自然派という言葉ほど怖い物はない…＞RT

　リツイートの情報は次になります。

リツイート：motoken_tw（モトケン）＞2016/09/12 10:17／2016/09/12 09:56＞ https://twitter.com/motoken_tw/status/775141199829098496 ＞
 kotadon （こたんせ～君が落ち着け）＞ https://twitter.com/kotadon/status/775135865702010880 ＞
引用＞　 自然派という言葉ほど怖い物はない…＞RT 

　モトケンこと矢部善朗弁護士（京都弁護士会）のリツイートの時刻が9月12日9時56分になっていますが、その次に投稿したツイートが次になります。

ツイート：motoken_tw（モトケン）：2016/09/12 10:19： https://twitter.com/motoken_tw/status/775141771743404032 ：
引用→　 @nobusan1979 気がする？控えめな表現ですね。

　一見すると直前の、こたんせ、のツイートにコメントしたようにみえましたが、ツイートを単体で開くと、次のツイートへの返信だとわかりました。たまたまなのかもしれませんが、ややこしくなっています。

ツイート：nobusan1979（のぶさんぁちゃん）：2016/09/12 09:53： https://twitter.com/nobusan1979/status/775135300142059520 ：
引用→　 内容についてとやかく言うつもりは、私もないのよねぇ＜改行＞＜改行＞専門的な知識や経験の部分について、虚偽の内容を用いるのは、禁じ手ではないかということよねぇ＜改行＞＜改行＞それも、意図的にやってるんじゃないかという気がするのよねぇ

のぶさんぁちゃんさんのツイートの記録：”専門的な知識や経験の部分について、虚偽の内容を用いるのは、禁じ手ではないかということよねぇ”の前後の流れ,http://hirono2016k.blogspot.com/2016/09/blog-post_13.html

　モトケンこと矢部善朗弁護士（京都弁護士会）がレスをつけた元のツイートですが、タイムラインで前後の流れを見ても、脈絡がつかめませんでした。不可解さもあるので、上記のブログ記事として記録しました。

　モトケンこと矢部善朗弁護士（京都弁護士会）が以前ちょくちょく使っていた「エアリプ」というようなものではないかと思いました。空砲のようなものかと思いますが、誰に向けたものでもない独り言で、それも返信を期待しない前後につながりのないもの。

　その前にあった、こたんせ、のツイートは直前のツイートを「RT ＞」などと指し示す、深澤諭史弁護士がよく使うタイプの引用スタイルでしたが、これをリツイートする場合、セットでリツイートすることがほとんどかと思います。

　こたんせ、のタイムラインで確認すると直前のリツイートは次のツイートでしたが、同じツイートのリツイートはモトケンこと矢部善朗弁護士（京都弁護士会）のタイムラインで見ていません。ブロックされていて出来ないという可能性はあります。

リツイート：kotadon（こたんせ～君が落ち着け）＞2016/09/12 09:55／2016/09/10 14:13＞ https://twitter.com/kotadon/status/775135769182638085 ＞
 yaiba35 （刃@しばらく別垢にいきます）＞ https://twitter.com/yaiba35/status/774475818948890624 ＞
引用＞　 それ、子供の精神ズタズタだぞ https://t.co/Jbiz5FHcqC 

　自然派が何を意味するのか、正当性の根拠を含め、それを調べて確認する時間的な余裕もないのでひと括りにはできないのですが、ほぼ同時進行になっていた高畑裕太氏の示談、釈放の件の方こそ、不可解な弁護士のご都合主義を強く印象づけるものです。

　昨日は、こたんせ、のタイムラインのツイートを眺めても、モトケンこと矢部善朗弁護士（京都弁護士会）が批判的に評価する「自然派」がなにを意味するのか理解が出来なかったのですが、別のタイムラインでいくらか理解が深まりました。

　そういえば、モトケンこと矢部善朗弁護士（京都弁護士会）は田舎での生活について極端な内容のツイートをリツイートしていましたが、玄関先に蛇が出るというのは、どんな田舎でもまず聞いたことのない話です。

　ムカデは、ここ最近は見かけないですが、年に数回家の中で見ることがあり、玄関先の靴の中にムカデが入っていて刺されたという話も聞いたことがあります。

　私が家の中で初めてムカデを見たのは平成14年に羽咋市のアパートで住み始めてからでした。宇出津よりはるかに都市化の進んだ住宅地でしたが、横に雑木林があるためか、よくムカデが出ました。壁を這っているムカデを見たのも生まれて初めてでした。

　子どもの頃も家の中でムカデを見た記憶はなかったですが、昭和50年代の頃までは、近所でもちょくちょく蛇やマムシを見ていました。以前は田んぼがありましたが、それもなくなり、野良犬の姿と同じように蛇を見ることはなくなりました。

　能登の里山里海ということで世界農業遺産にもなった奥能登で生活し、自然を感じているだけに、モトケンこと矢部善朗弁護士（京都弁護士会）の極端な自然派の取り上げ方には、異様な違和感を感じました。

　モトケンこと矢部善朗弁護士（京都弁護士会）は次のツイートもしていました。

ツイート：motoken_tw（モトケン）：2016/09/12 10:41： https://twitter.com/motoken_tw/status/775147302046445568 ：
引用→　 @hironobutnk @takayatoru 三代住んでもよそ者と言われるようで。

　上記のモトケンこと矢部善朗弁護士（京都弁護士会）のツイートは、次のツイートに対する返信となっています。

ツイート：hironobutnk（田中泰延）：2016/08/20 22:39： https://twitter.com/hironobutnk/status/766993121620074496 ：
引用→　 埼玉から引っ越してきて京都に20年ほど住んでる知人女性が京都人たちの前で「わたし、地元の京都では…」と口を滑らした。大阪人のわたしは生きた心地がしなかった。京都人たちは全員一斉に聞こえるか聞こえないぐらいの空気を漏らしながら読唇術ならわかる程度に（ 地元。 ) と口を動かした

　モトケンこと矢部善朗弁護士（京都弁護士会）が京都市内の八坂神社の近くで法律事務所をやっていることは、7月に提出した告訴状にも書いたと思います。住まいは不明ですが、京都市内に住んでいる可能性の方が高いと思います。

　先日、蛸島のキリコ祭りを見に、久しぶりに珠洲市に行きましたが、平成21年の9月の10日頃、珠洲市総合病院に京都の親戚が集まった時、駐車場で、病院の能登の人はすごく親切と言いながら、京都ではとんでもない性悪がぎょうさんおる、などと聞かされました。

　珠洲市でも中心部から外れた大谷というところになりますが、歴史的に京都とは縁があって、「平家にあらずんば人にあらず」と言ったという平時忠の流刑地となっています。

　平時忠は、京都での華やかな生活を懐かしみ、珠洲の海の音に侘びしさを募らせたという話もありますが、京都という土地で生まれ育った人は、現在でも物の見方、考え方に根本的な違いがあるのかもしれないと考えました。もちろん個人差も大きいはずです。

　モトケンこと矢部善朗弁護士（京都弁護士会）が京都という土地に執着したような発言は、見た記憶がないのですが、その点、同じく名誉毀損で刑事告訴する小倉秀夫弁護士は、東京の生まれ育ちであることに特別な優越感を持つ、とうかがわれるツイートが散見されます。

　小倉秀夫弁護士の場合、鳥取県や島根県を名指しにして、心底罵倒するようなツイートも繰り返しており、何度かツイートのまとめ記事も作成しています。私はモトケンこと矢部善朗弁護士（京都弁護士会）と小倉秀夫弁護士をセットで捉えています。

　モトケンこと矢部善朗弁護士（京都弁護士会）と小倉秀夫弁護士は、対立することがほとんどですが、似通った部分と、それ以上に、弁護士という立場で争いのタネを撒き散らし、利潤追求するさまは、まさに同志という関係性であると見てきました。

　モトケンこと矢部善朗弁護士（京都弁護士会）がその本領を発揮したのは、SNSが普及する前の、平成17年から19年ぐらいのことで、主に「元検弁護士のつぶやき」というレンタルサーバに設置した管理運営のブログをその舞台としていました。

　「元検弁護士のつぶやき」というブログは、記事のコメント欄が賑わうブログで、8割ぐらいが一定の常連コメンテータのコメントで占められていたかと思います。

　現在、Twitterで当時の常連コメンテーターとして確認できるのは、これからツイートを引用する２つのアカウントです。基本は感熱紙と惰眠というハンドル名で、元検弁護士のつぶやき、の時代から続いています。

ツイート：thermalpaper00（感熱紙(リフレクターインコム)）：2016/09/13 10:06： https://twitter.com/thermalpaper00/status/775500890258051073 ：
引用→　 マンションに児童相談所が！　住民説明会で怒号（毎日放送） - Yahoo!ニュース https://t.co/89I2BvL1bJ　児童相談所まで迷惑施設扱いかよ。利己主義も甚だしいなあ。

リツイート：thermalpaper00（感熱紙(リフレクターインコム)）＞2016/09/09 17:20／2016/09/09 17:09＞ https://twitter.com/thermalpaper00/status/774160636028694529 ＞
 motoken_tw （モトケン）＞ https://twitter.com/motoken_tw/status/774157812888850432 ＞
引用＞　 このコメントは被害者の認識と一致してるのだろうか？どんな示談交渉が行われたのかとても興味がある。このようなコメントを公にすることの当否も問題になりそう。＞高畑裕太氏釈放、弁護人のコメント全文：朝日新聞デジタル https://t.co/5cDQNshxnr 

ツイート：thermalpaper00（感熱紙(リフレクターインコム)）：2016/09/09 17:18： https://twitter.com/thermalpaper00/status/774159993020882944 ：
引用→　 んー、この弁護人示談で不起訴もらって浮かれてるのか、要らんこと言ってるよなあ。どう見ても「不起訴取るために反省も納得もしてないけど、してるフリして示談持ちかけました」ってばらしてるし。

ツイート：thermalpaper00（感熱紙(リフレクターインコム)）：2016/09/09 17:13： https://twitter.com/thermalpaper00/status/774158750579953664 ：
引用→　 強姦致傷容疑で逮捕の高畑裕太さんを不起訴処分で釈放　頭下げ「申し訳ありませんでした」　弁護人は「合意があると思っていた可能性高い」 https://t.co/DXnCRxnAvw @Sankei_newsから

ツイート：thermalpaper00（感熱紙(リフレクターインコム)）：2016/09/09 16:26： https://twitter.com/thermalpaper00/status/774146959133114368 ：
引用→　 自然派だの何だの喚いている連中ほど自然に対する畏敬の念も知識も欠如しているからなあ。

リツイート：thermalpaper00（感熱紙(リフレクターインコム)）＞2016/09/09 16:19／2016/09/08 17:52＞ https://twitter.com/thermalpaper00/status/774145244333875200 ＞
 senjuin1010 （千手院）＞ https://twitter.com/senjuin1010/status/773806109882585088 ＞
引用＞　 ほんとコレ。ご位牌やお墓のお戒名を見ても、子供の仏様の方が有意に多い。いかに「子どもが元気に成長し、成人を迎える」のが有り難い（字面通り）ことだったか…。有り難い事だったからこそ子供に関する行事も多いのだと思う（七五三・節句等）。 https://t.co/MrZ8C6r5fu 

リツイート：thermalpaper00（感熱紙(リフレクターインコム)）＞2016/09/08 12:43／2016/09/08 10:32＞ https://twitter.com/thermalpaper00/status/773728457683369986 ＞
 Sto_kra2 （すとくら（新規アカウント））＞ https://twitter.com/Sto_kra2/status/773695519277223938 ＞
引用＞　 暴走族を珍走団と呼び換え撲滅を図ったように、自然派ママも蛮族系ママとか呼んで恥ずかしさに居たたまれないようにした方が良いと思う。＜改行＞＜改行＞『蛮族ママ、大自然の掟知ってる。火で火傷したら水で冷やすダメ。火の属性は火で癒す良い。ワクチンダメ。あれ病魔を身体に入れる悪魔の技。弱い子死ぬ当然』 

ツイート：thermalpaper00（感熱紙(リフレクターインコム)）：2016/09/08 12:39： https://twitter.com/thermalpaper00/status/773727382590984192 ：
引用→　 「自然派ママの新常識　「火傷はあたためる☆」」＜改行＞ ⇒ https://t.co/dh9cboy086 自分自身ならまだしも子供にこれをやるのは虐待でしかないので、もし病院を受診してきたら警察に通報するべきだよなあ。

リツイート：thermalpaper00（感熱紙(リフレクターインコム)）＞2016/09/07 21:35／2016/09/07 20:11＞ https://twitter.com/thermalpaper00/status/773500023342444545 ＞
 Damin_EN500 （惰眠）＞ https://twitter.com/Damin_EN500/status/773478734816878592 ＞
引用＞　 https://t.co/PVdl3kQ4eA 回路の容量が足りなくてアイドリングストップからの再始動時に生じる突入電流で焼けちゃうってこと？ちょっと、お粗末すぎないか、それ。 @Damin_EN500 

ツイート：thermalpaper00（感熱紙(リフレクターインコム)）：2016/09/04 21:47： https://twitter.com/thermalpaper00/status/772415814746058753 ：
引用→　 これを信じた母親がワクチン接種を拒否し、子供をウイルス感染症に罹患させ、死亡させてしまった場合、母親はこのブログ主に対して何らかの法的責任を問うことは出来るか否か。 https://t.co/9WotMr5bU2

　他に、元検弁護士のつぶやき、では「みみみ」というハンドル名の常連コメンテーターがいて、それに特に批判的な評価をされたという印象が残っています。それと思われるアカウントがあって、久しぶりにタイムラインを開いたのですが名前が変わっていました。

　次が今撮りたてのスクリーンショットです。

投稿者：s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2016-09-13 11:59  ツイート： https://twitter.com/s_hirono/status/775529373105434624
2016-09-13-115940_真知子巻き（@KTets）さん　｜　Twitter.jpg https://t.co/uDYjSqlZJ8

真知子巻き(@KTets)さん | Twitter https://twitter.com/KTets

　ブックマークに登録している以前のプロフィールの名前は、「（:]ミ（:]ミ（:]ミ (@KTets)さん | Twitter」となっています。これで「みみみ」と特定するのはどうかと思いましたが、少しリツイートするとすぐにブロックしてきたので可能性は高いと考えます。

　時刻は9月15日12時35分になっています。元検弁護士のつぶやき、の常連コメンテーター、感熱紙とミミミ、そして惰眠について書くつもりでいたまま、しばらく中断をしていました。深澤諭史弁護士のことで頭から離れないことがあるので、そちらを優先したいと思います。

2016-09-15　木曜日　12：38　＜＜ ［［　←これまでの記述範囲の終了時刻］］＜＜












**** 「高畑裕太強姦致傷事件 「示談交渉を仕切った 暴力団関係者」」という記事に対するモトケンこと矢部善朗弁護士（京都弁護士会）のツイート

:CATEGORIES: モトケンこと矢部善朗弁護士（京都弁護士会）＜名誉毀損で刑事告訴予定＞
:TAGS: モトケンこと矢部善朗弁護士（京都弁護士会）,示談交渉

2016-09-20　火曜日　16：16　＞＞ ［［　←これからの記述範囲の開始時刻］］＞＞

ツイート：hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）：2016/09/16 22:21： https://twitter.com/hirono_hideki/status/776773126134923264 ：
引用→　 フライデー「被害女性の知人男性は暴力団員でヤクザ」記事が酷すぎると炎上！黙秘する被害者を攻撃、高畑裕太の異常な擁護が気持ち悪いと非難殺到ｗｗ（画像）:エンタメ思考　芸能人の噂 https://t.co/59mIaaxXAG

　Twilogで「フライデー」をキーワードに検索すると、上記のツイートが高畑裕太氏の事件に関連したものとして最初に出てきました。16日発売という情報を見かけていたように思うのですが、発売前にも同じ情報を見ていた気もします。

奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/2016年09月15日 - Twilog http://twilog.org/hirono_hideki/date-160915

　念の為、前日の15日のツイートを上記のTwilogで調べましたが、それらしいものは見当たりませんでした。やはり16日以降の情報であったと考えられます。

　16日といえば金曜日ですが、高畑裕太氏の示談交渉を暴力団員が仕切っていたという話は、テレビでは全く見かけておらず、日曜日の2つの情報番組における週刊の注目度ニュースランキングにも、高畑裕太氏の関連は見当たりませんでした。

　土曜日の情報番組も同じだったと思います。釈放されたのが9日で、その後、しばらくするとぴたりと報道がなくなりました。あとで考えると、釈放と同時に芸能事務所を解雇されていて、もう芸能人でもないので報道の正当性も必要性もない、ということなのかもしれません。

　そんな折りに見かけたのが、次のモトケンこと矢部善朗弁護士（京都弁護士会）のツイートです。「暴力団」をキーワードに登録したアカウントのツイートをAPIで機械的に検索した結果になります。

〜モトケン（motoken_tw）のツイート〜投稿日時〜2016/09/16 11:16〜ツイートのURL〜 https://twitter.com/motoken_tw/status/776605694619295744 〜
#〜引用〜 この事件、全然終わらないな。なんのために示談をしたんだか。＞独走スクープ！　高畑裕太強姦致傷事件 「示談交渉を仕切った 暴力団関係者」（FRIDAY） - Yahoo!ニュース https://t.co/7yxv1Sk0NN #Yahooニュース

〜弁護士大西洋一（o2441）のツイート〜投稿日時〜2016/09/16 17:06〜ツイートのURL〜 https://twitter.com/o2441/status/776693723728076800 〜
#〜引用〜 こ、これは・・。＼＼独走スクープ！　高畑裕太強姦致傷事件 「示談交渉を仕切った 暴力団関係者」（FRIDAY） - Yahoo!ニュース https://t.co/KgJgmdFJzm #Yahooニュース

〜弁護士奥村徹（児童ポルノ児童買春）（okumuraosaka）のツイート〜投稿日時〜2016/09/16 08:33〜ツイートのURL〜 https://twitter.com/okumuraosaka/status/776564578377281536 〜
#〜引用〜 独走スクープ！　高畑裕太強姦致傷事件 「示談交渉を仕切った 暴力団関係者」（FRIDAY） - Yahoo!ニュース https://t.co/HxkwWQaKXi #Yahooニュース

〜郷原信郎（nobuogohara）のツイート〜投稿日時〜2016/09/16 21:12〜ツイートのURL〜 https://twitter.com/nobuogohara/status/776755558678302720 〜
#〜引用〜 今日発売のフライデー【高畑祐太強姦致傷事件、示談交渉を取り仕切った暴力団関係者】https://t.co/7mFXgrdeqJ　私もコメントしていますが、「暴力団関係者」のことは全く知らされていませんでした。フライデーの担当記者によると「十分な取材に基づく記事」だとのことです。

　TwitterAPIのsearchという検索用のメソッドを使ったものですが、比較的最近のツイートしか取得できない仕様になっているはずです。対象にしたアカウントは129で、ほとんどが弁護士関係のTwitterアカウントです。

　このスクリプトは高畑裕太氏の強姦致傷事件が発生した先月つまり8月の23日の午前中か、前日の22日の朝に作ったように思います。

　今日になってスクリプトのファイルの編集をしてテキスト出力の書式を変更したのですが、後になって前回の最終更新日時を確認できなくなったことに気が付きました。Linuxではファイル作成時の時刻情報を保持せず、取得できるのは最終更新か最終アクセスの時刻情報のみと聞いています。

　「暴力団」というキーワードのみでの検索となっていますが、結果の全てが高畑裕太氏の事件のことで、4つの弁護士アカウントがそれぞれ１つずつというツイートです。それも9月16日に限られています。

　個人的には疑問の大きい示談交渉ですが、関係者が恐喝罪などで逮捕されない限り、再びテレビで取り上げられることのない事件であって、それが母親の高畑淳子氏が記者会見で口にしていた「知らなかったルール」の一つということになるのだろうと考えています。

　フライデーが記事にしたという情報では、300万円の示談金と8000万円の慰謝料の計8300万円の支払い、ということになっており、ネットでは他に3000万円の示談金というような情報も見かけていますが、いずれも正式な発表による正確な情報とは思えず確かなことはわかりそうにありません。

　ネット上の情報では、犯行の一時間後の深夜に医師の診断書が出来上がっていたとか、被害者の女性が10日後のパーティにおいて笑顔のピースサインで写真に写っていたとか、計画性を強く感じさせる報道があって、美人局という見方がネットでは主流になっているという印象を受けます。

　8000万円という金額も確認できるものではないので、前提が不確かになりますが、弁護士が立ち会っていて、そこまで高額の慰謝料になったというのも、社会的相当性として疑問が大きいですし、そのことに疑問を呈することなく、「なんのために示談をしたんだか」というのは違和感も大きいです。

　モトケンこと矢部善朗弁護士（京都弁護士会）においては、他にも疑問に感じるツイートが多く、それがもはや主流にもなっていますが、一般的な感覚のある依頼者を除外し、特定のターゲットにのみ的を絞って、弁護士としての商売の営業に、断片的な情報を利用しているように思えてなりません。

　高畑裕太氏の強姦致傷事件においては、その報道の当初においても、印象的なモトケンこと矢部善朗弁護士（京都弁護士会）のツイートを目にしており、それは社会の一般の心情を逆なでし、母親である高畑淳子氏の立場を悪くするものとしか思えないものでした。

モトケン(@motoken_tw)/2016年08月23日 - Twilog http://twilog.org/motoken_tw/date-160823/asc

　上記のモトケンこと矢部善朗弁護士（京都弁護士会）のTwilogで、調べています。ASCを指定しているので、通常とは異なり、ツイートの順番は朝〜夜という流れになっています。そういえばと思い出すものがありますが、先に痴漢冤罪に関する独自の理屈のツイートをやっていました。

ツイート：motoken_tw（モトケン）：2016/08/23 09:29： https://twitter.com/motoken_tw/status/767881364926451712 ：
引用→　 「警察官が現行犯逮捕」と言うけど、警察官は何も現認してないじゃないか。こんな思い込み逮捕で人生を狂わされたのか？＞痴漢事件：大阪地裁支部、無罪判決…警察が誤認現行犯逮捕 - 毎日新聞 https://t.co/pDaM1cCbQV

ツイート：motoken_tw（モトケン）：2016/08/23 09:41： https://twitter.com/motoken_tw/status/767884498486919168 ：
引用→　 痴漢事件の現行犯逮捕ほどあてにならならないものはない。いっそのこと、容疑者の身元が明らかでない場合を除き、現行犯逮捕を禁止すべきじゃないかな。

ツイート：motoken_tw（モトケン）：2016/08/23 09:56： https://twitter.com/motoken_tw/status/767888250732019712 ：
引用→　 痴漢事件て、どうしてあんなに簡単に逮捕しちゃうんだろう？万引とか暴行・傷害事件でもあんなに簡単には逮捕しないんだけど。

ツイート：motoken_tw（モトケン）：2016/08/23 10:22： https://twitter.com/motoken_tw/status/767894626506186752 ：
引用→　 基本的に証拠が薄いパターンだから、逮捕しちゃって、「認めれば家に帰れるぞ」などと自白を強要するための逮捕だと思ってます。罪証隠滅つまり虚偽証拠作出の可能性は他の事件と比較して特に高いとは思いません。 https://t.co/9TBc34CAlx

ツイート：motoken_tw（モトケン）：2016/08/23 10:37： https://twitter.com/motoken_tw/status/767898591176167424 ：
引用→　 この事件、仮に外形的には女性の下半身に触れているとしても「厚手のコートの上からで、ごく短時間」触れた程度の事案で逮捕すべきなのか大いに疑問。女性の被害と男性の不利益のバランスが明らかに狂ってる。＞痴漢事件：大阪地裁支部、無罪判決…  https://t.co/pDaM1cCbQV

ツイート：motoken_tw（モトケン）：2016/08/23 14:54： https://twitter.com/motoken_tw/status/767963164063338496 ：
引用→　 氷山の一角である疑いがある。＞供述調書改ざんの疑い、巡査部長立件へ　神奈川県警：朝日新聞デジタル https://t.co/jAY8jccg6l

ツイート：motoken_tw（モトケン）：2016/08/23 14:59： https://twitter.com/motoken_tw/status/767964546392653825 ：
引用→　 この見出しは、この程度では逮捕されないというミスリードになりかねない。本文を読めば同種の別件で逮捕されていることがわかるけど。＞「県庁を爆破する」新潟県にメール送信した疑いで書類送検　埼玉の男 -  https://t.co/9Sblvkrd9K @Sankei_newsさんから

　前座のようになりましたが、冤罪や警察の取り調べに関して、モトケンこと矢部善朗弁護士（京都弁護士会）らしさがよく現れているツイート群です。警察に対してはとても厳しい目を向けていますが、同業者である弁護士に批判の目を向かることは、実質無いに等しく、著しいバランスの悪さを感じます。

　さきほどの「この事件、全然終わらないな。なんのために示談をしたんだか。＞独走スクープ！　高畑裕太強姦致傷事件 「示談交渉を仕切った 暴力団関係者」」という内容のツイートと比較しても、示談について多くの人が疑問の目を向けているのに、それを全く無視した言い草です。

　これまでは、警察のリークに対して刑事罰の必要性さえちらつかせて批判してきたモトケンこと矢部善朗弁護士（京都弁護士会）ですが、逮捕されてすぐ容疑を認めた高畑裕太氏が、示談成立後に弁護士を通じて公表した無罪主張を盛り込む対応との不整合にも、疑問を向ける目はありません。

　テレビを見ていると、逮捕当初の「欲求を抑えきれなかった」というような供述も、出処のはっきりしない情報で、警察の話ではないという指摘もなかにはあったぐらいです。

　痴漢というのも性犯罪の一つかと思いますが、強姦致傷は最高で無期懲役まである重罪で比較にならないほどの違いがあって、それこそ人生を狂わされる、ということになりますし、示談で不起訴となっても高畑裕太氏高畑淳子氏親子が失った代償は計り知れず大きなものがあり、その無頓着さも際立ちます。

　モトケンこと矢部善朗弁護士（京都弁護士会）本人に自覚がどの程度あるのかわかりませんが、高畑裕太氏の強姦致傷事件においては、強姦致傷の不利益の大きさにウェイトをおいて、当初からアピールしたという印象です。

　マスコミ対応として弁護士の有用性をアピールしたとも見えますが、依頼者となる可能性のある本人、この場合は母親の高畑淳子氏になりますが、その社会的な評価を大きく損ねたとしか思えません。判断に必要な情報を与えず、強引に主導権を握り舵取りをする弁護士の傲慢性、というのも強く感じました。

　ここ最近は、弁護士を頼り対応を任せることでの、取り返しのつかない不利益の大きさというのを印象づける事件や問題ばかりが、目についております。

　高畑裕太氏の強姦致傷事件においても、怪我の程度は当初より全治一週間程度の怪我と報道されており、他の強盗事件における致傷罪においても微妙となる怪我の程度であって、寡聞にして知りませんが、全治一週間の怪我で致傷罪が成立が認められた判例あるのかも疑問です。

　時刻は18時20分です。今次の記事を読んだところです。自分にはなかった視点で気になるところがあったので、次に一部を引用してご紹介します。

／＊＊＊＊＊＊＊＊＊＊（引用開始）＊＊＊＊＊＊＊＊＊＊
引用URL＞＞＞＞：http://news.livedoor.com/article/detail/12042119/ 高畑裕太さんの芸能界復帰に「絶望的」 暴力団関係者からクレーム入る？ - ライブドアニュース

「一部報道で、示談交渉の背後に暴力団関係者が絡んでいることがすっぱ抜かれてしまった。そのため、裕太を起用したところに、その関係者からのクレームが入ることが危惧されるので、そういうリスクを犯してまで仕事で使うところはないだろう。もはや芸能界復帰は絶望的」(芸能記者)

　高畑の“親バカ”ぶりにはつける薬がなさそうだ。 

＊＊＊＊＊＊＊＊＊＊（引用終了）＊＊＊＊＊＊＊＊＊＊／

　記事は「女優の高畑淳子の息子・高畑裕太の現状と今後について、発売中の「女性自身」(光文社)と「週刊女性」(主婦と生活社)がそれぞれ報じている。」として紹介されています。母親という立場で関心の高い事件であることを想像しましたが、ネットで見てきのは男目線が多かったように思いました。

　「男目線」と書きましたが、同時に「弁護士目線」という言葉が頭に浮かびました。弁護士目線として特にわかり易く、記録作成の価値と必要性があると判断しているのが、モトケンこと矢部善朗弁護士（京都弁護士会）、小倉秀夫弁護士、深澤諭史弁護士の目線でもあります。

　高畑裕太氏の強姦致傷事件では、小倉秀夫弁護士や深澤諭史弁護士の言及ツイートは確認していません。小倉秀夫弁護士に関しては数が多いこともあり、ツイートはタイムラインでたまたま目についたものを、わずかに読んでいるという程度です。

　深澤諭史弁護士についてよく思うのは、自分の利益になりそうにない問題には無関心を徹底するか、いくらか強引に関連付ける傾向性があるということです。7月の告訴状ではご紹介したように思いますが、「脳機能障害の少女」のニュースが、なにより印象的で忘れることはありません。

　脳機能障害の少女の損害賠償金を弁護士が食い物にしたというニュースですが、深澤諭史弁護士はそれも司法制度改革で弁護士を食い詰めさせたことが悪いと位置づけていました。このことは本書においても独立した項目として取り上げたいと考えていますが、情報の収集がしづらくなっています。

　深澤諭史弁護士とモトケンこと矢部善朗弁護士（京都弁護士会）の共通性として、自分が手に入れた弁護士という資格を最大限に利用して利益を得るという意気込みと、正当化にいささかの疑問も持たないという狂信性が挙げられます。小倉秀夫弁護士もいくらか似ていますが、まだ余裕も感じられます。

　余裕と言いましたが、その違いは小倉秀夫弁護士が法律家として最も成功し、安定した収入につながっていると推察されることになります。法律の専門書の監修者となり中央大学、明治大学、首都大学で法学部の講師をやっているので、それも頷ける話ですが、私はその点を彼の責任として重く捉えています。

　もっともここ最近の小倉秀夫弁護士は、ツイッターのタイムラインのツイートの数も尋常でない多さになっていて、これまで通りに仕事をされているのかも、疑いがもたげて来ました。Twilogに記憶はないですが、2,3日前もTwilogでは一日のツイート数が130件を超えていたかと思います。

　非公式RTが多いもののリツイートが少ないのも小倉秀夫弁護士のタイムラインの特徴です。リツイートならスマホでもボタン操作でいくらでも数を増やせますが、ツイートとなれば書く手間もありますし、非公式RTでの返信となると、他のツイートを読んでいる時間も多いということになります。

　モトケンこと矢部善朗弁護士（京都弁護士会）は、元検事であることや、ロースクールの教官をしていた経歴を、Twitterのプロフィールで強調しています。それはそれで正統性を裏付ける情報だと思いますが、それだけに発言の責任も重いというのが、私の見方であり考えです。

　それでは、次がモトケンこと矢部善朗弁護士（京都弁護士会）の高畑裕太氏の強姦致傷事件の発生、報道当日の関連ツイートになります。8月23日は輪島大祭の重蔵神社大祭の当日だったので日付をよく憶えています。私は銭湯で17時10分ほど前に、テレビのニュースを見て事件を初めて知りました。

ツイート：motoken_tw（モトケン）：2016/08/23 16:38： https://twitter.com/motoken_tw/status/767989443416367104 ：
引用→　 そこそこ売れている俳優がこんなわかりやすい強姦事件を起こすことにちょっと驚いた。＞俳優の高畑裕太容疑者　女性への強姦致傷容疑で逮捕「欲求を抑えきれなかった」（スポニチアネックス） - Yahoo!ニュース https://t.co/kl1xkmUX64 #Yahooニュース

ツイート：motoken_tw（モトケン）：2016/08/23 17:15： https://twitter.com/motoken_tw/status/767998794763866112 ：
引用→　 この記事だが、なんで母親の写真を載っけてるんだ？＞女優、高畑淳子の息子で俳優の高畑裕太、４０代ホテル従業員強姦致傷容疑で逮捕 「欲求を抑えられなかった」 前橋のビジネスホテル https://t.co/maWhG4S0xe

ツイート：motoken_tw（モトケン）：2016/08/23 17:57： https://twitter.com/motoken_tw/status/768009143105880064 ：
引用→　 @motoken_tw 今見たら本人の写真と差し替えられていたが、「このニュースの写真」のところに同じ母親の写真が掲載されている。

ツイート：motoken_tw（モトケン）：2016/08/23 23:42： https://twitter.com/motoken_tw/status/768096154714251268 ：
引用→　 PCデポは自分たちが批判を受けやすい商売をしているという自覚がゼロだったのかな？かなり控えめな表現のツイートです。

　最後の23時42分のツイートは、高畑裕太氏の強姦致傷事件とは無関係ですが、モトケンこと矢部善朗弁護士（京都弁護士会）の当日の最後のツイートであり、そのまま弁護士商売の自覚として、モトケンこと矢部善朗弁護士（京都弁護士会）や深澤諭史弁護士に投げ返したいものがあります。

　時刻は20時33分です。深澤諭史弁護士のタイムラインに高畑裕太氏の事件に関連した気になるツイートがあり、取り上げることを考えていましたが、そういえば最近タイムラインを見ていないノースライムという総称の弁護士アカウントのページを開いたところ、削除されたらしいことがわかりました。

Twitter / ? https://twitter.com/Noooooooorth/with_replies

　深澤諭史弁護士もそのうち消えてなくなるかも知れないとは、ずっと頭の片隅にあったことですが、ある程度自重性のある弁護士アカウントとしては、アカウントのいきなりの削除は意外でした。総合的に不利益が大きいという判断で削除したものとは考えられます。

ノース先生、ご結婚おめでとうございます。 - Togetterまとめ http://togetter.com/li/903823

　ノース先生で検索したところみつけたのが上記のTogetterですが、アカウントが削除され、リンクが存在しなくなっても、Togetterのツイートは残るらしいと発見しました。プロフィールの名前が頻繁に変更されていましたが、ノース先生と呼ばれることが多いと思いつきました。

　同じく深澤諭史弁護士も深澤先生と呼ばれることが多く、不思議な現象だと思ってきました。深澤諭史弁護士を先生と評価するグループが一定数弁護士業界に存在することは間違いなさそうです。

ツイート：o2441（弁護士大西洋一）：2016/09/04 13:58： https://twitter.com/o2441/status/772297797068611584 ：
引用→　 ノース先生、フェイスブックとかで、ツイッターをやめた理由に触れたりしているのでしょうか。復活するように伝えておいてください。おながいします。 — 前から時々停止してたし、今度は完全匿名垢にするなどして復活されるのでは？ https://t.co/oG2y3VYbPy

　調べると、上記のツイートが見つかりました。9月4日の投稿になっているので半月ほど前になりそうです。Twitterの停止というのは聞いたことがなく、非公開設定というのはありますが、いったん削除したアカウントを以前のように復活できるとは、考えにくい気がします。

　数時間、更新が止まっていたモトケンこと矢部善朗弁護士（京都弁護士会）は、次のツイートなどで何事も無いようにすぐに再開していました。たまたま更新がなかっただけの様子です。

ツイート：motoken_tw（モトケン）：2016/09/20 20:28： https://twitter.com/motoken_tw/status/778194107927711744 ：
引用→　 接見終わった。今日はトンカツ。

2016-09-20　火曜日　20：51　＜＜ ［［　←これまでの記述範囲の終了時刻］］＜＜

