**** マスコミ・報道関係に関するローカスこと実質実名弁護士のツイート

:CATEGORIES: ローカスこと実質実名弁護士
:TAGS: ローカスこと実質実名弁護士,マスコミ,報道

ツイート：lawkus（ystk）：2016/09/01 23:40： https://twitter.com/lawkus/status/771356949027753984 ：
引用→　 小林麻央さんが病気のことを自ら発信することにしたのは尊敬に値する決断だと思う。もっとも今そうなったからといって、当事者が発信を望まなかった過去にマスコミが追い回したことまで遡って正当化されるわけではないわな。でもマスコミはこれで正当化されたと思ってそうなところが何ともアレ。

ツイート：lawkus（ystk）：2015/08/19 18:15： https://twitter.com/lawkus/status/633930399656243200 ：
引用→　 マスコミ「容疑を報道しただけでも事実上犯人との印象を与えるのは、有罪率が99%以上という手前ら司法の問題だろうが」という反論もあり得るなと思ったりw

ツイート：lawkus（ystk）：2015/08/19 17:58： https://twitter.com/lawkus/status/633925874459344896 ：
引用→　 @ebiben2008 捜査機関リークを「軽信」して真実かのように報道するマスコミの態度こそが、捜査機関は結構嘘つきだということを知る我々弁護士の不興を買う真の原因なのではないかと思ったりします。

ツイート：lawkus（ystk）：2015/01/18 11:15： https://twitter.com/lawkus/status/556635855507714048 ：
引用→　 大したことない犯罪でもyoutubeに上げたりして誇示すればマスコミまで騒いでくれるというわけで、少年の思ったとおりになっただけという気がしますね。黙殺すればよかったのに。

ツイート：lawkus（ystk）：2014/08/02 18:01： https://twitter.com/lawkus/status/495494594700664832 ：
引用→　 http://t.co/d2qsQw9oK1 これなあ。マスコミが出した情報からネット民が特定するパターンが多いでしょ。「父が弁護士」とか、宮崎の弁護士の人数考えたらもう特定して下さいというレベルの情報だよ。ネット民の暴露を戒めるのもいいが、マスコミも改めるべきことがあるのでは。

ツイート：lawkus（ystk）：2014/04/13 16:26： https://twitter.com/lawkus/status/455245642391355392 ：
引用→　 加藤智大の弟氏の自殺についてマスコミばかり非難するのはおかしいというのはそうなんだけど、犯罪者の家族を責めるような世間の悪弊に乗っかり助長さえしていることについてマスコミ人はどう考えるのか、というのは思うよね。欲しがるもの与えるだけじゃなくて、そこを啓蒙してこそ社会の公器だろと。

ツイート：lawkus（ystk）：2014/03/11 00:10： https://twitter.com/lawkus/status/443041301253337089 ：
引用→　 結局，先ほども書いたように小保方さんの罪状は「世間を騒がせた罪」なので，「マスコミが飛びついて大々的に取り上げなければ俺たちも騒がないで済んだのに！」というところから奇妙なマスコミ叩きも発生するわけである。

ツイート：lawkus（ystk）：2013/07/20 09:28： https://twitter.com/lawkus/status/358382887642480642 ：
引用→　 そしたら裁判関係の記事もマシになりますしね！ RT @yinoue1975: 【主張】法科大学院の改革　弁護士の活躍の場拡大を - MSN産経ニュース http://t.co/kgKgUzVTtU 新聞社を含めたマスコミが社内弁護士の採用を加速して問題の先送りを避けてほしい

ツイート：lawkus（ystk）：2013/04/22 17:35： https://twitter.com/lawkus/status/326252991042686976 ：
引用→　 @rawhead おお，そういう経緯だったんすか。やはりマスコミ人はしっかりTwitterあたりにもアンテナ伸ばしてるんですな。

ツイート：lawkus（ystk）：2011/03/20 15:22： https://twitter.com/lawkus/status/49355162157989888 ：
引用→　 言論の自由を「何を言っても放っておいてもらえる権利」だと勘違いしている人の多いこと多いこと。RT @tamai1961:大マスコミによる扇動を批判するのは、言論の自由の、最も大事な要素…RT @ponderin5555:AERA叩かれてるけど…いつから日本は言論の自由のない国に

ツイート：lawkus（ystk）：2011/01/24 22:26： https://twitter.com/lawkus/status/29530521553870848 ：
引用→　 こと犯罪に関していえばマスコミは、独自取材に基づき真犯人か否かの判断をなした上での報道など未来永劫しないのだから、いっそ「当局の言ったとおりに報道するため不可避的に(当局と連動的に)間違う」ことを前提に、刑事補償制度類似の報道補償基金を設けては。偽善的な検証報道よりずっと有益。

ツイート：lawkus（ystk）：2010/10/06 01:34： https://twitter.com/lawkus/status/26471874957 ：
引用→　 @kyodogenso ただ日本のマスコミは、一方では検察情報に依拠し、刑事責任を問われる可能性が生じたことのみを根拠に政治責任とやらを追及していたくせに、他方で「政治責任と刑事責任は違うから推定無罪も関係ない」という、ご都合主義的矛盾挙動を示しているのが許しがたいと思います。
**** 実名報道に関するローカスこと実質実名弁護士のツイート

:CATEGORIES: ローカスこと実質実名弁護士
:TAGS: ローカスこと実質実名弁護士,実名報道

ツイート：lawkus（ystk）：2013/01/24 00:16： https://twitter.com/lawkus/status/294101341796696064 ：
引用→　 下記RTは被疑者被告人の実名報道に関し、少し前にたまたま書いていたものだが、被害者の実名報道についても基本的な考えに変更はないので再掲。実名報道には利がなく害しかないからお上が禁止しろ（マスコミが自重しろではなく）とか言う人の、利害を判断できる自信は、独裁者目線なのではないか等。
**** 警察・検察・裁判所（刑事司法）関係のローカスこと実質実名弁護士のツイート

:CATEGORIES: ローカスこと実質実名弁護士
:TAGS: ローカスこと実質実名弁護士,検察

ツイート：lawkus（ystk）：2014/12/11 23:41： https://twitter.com/lawkus/status/543052847903154176 ：
引用→　 検察の公訴権濫用がウザイので、裁判官の予断とか関係なく起訴状に証拠とかバンバン載せちゃってもいいと思いませ... — まず、ネットやマスコミで騒がれる事件というのはほんの一握りなので、あなたのロジックは弱いと思います。その点... http://t.co/rdLzl4UCIG

ツイート：lawkus（ystk）：2014/03/27 23:59： https://twitter.com/lawkus/status/449198915519127553 ：
引用→　 検察の闇司法の闇を指弾するのも結構だが、当時おそらく多くの大衆やその代弁者としてのマスコミが、袴田氏逮捕に快哉を叫び彼を吊るせと後押ししたはずで。「我々は安心して罪人を吊るせと叫びたいから検察や司法は無謬でなければならないのに実際無謬でないのは許せん」では済まないとの自覚も必要。

ツイート：lawkus（ystk）：2010/09/26 22:06： https://twitter.com/lawkus/status/25588095349 ：
引用→　 同感。でも無理でしょう。過去の被疑者叩き検察万歳と今の検察叩き、多分動力は同じですから。  RT @mofjd 正義の味方と思われてきた特捜とか言ってるけど、そのイメージを人々に植え付けたのはマスコミなんだから、マスコミの過去の事件の扱い方も検証してほしいな。無理な気がするけど
