**** マスコミ・報道関係

ツイート：uwaaaa（サイ太）：2016/08/05 09:22： https://twitter.com/uwaaaa/status/761356724322217984 ：
引用→　 『報道されて人生が狂った！』って言ってマスコミ関係者が殺される事件でもなければ意識は変わらないんでしょうね

ツイート：uwaaaa（サイ太）：2016/07/31 19:54： https://twitter.com/uwaaaa/status/759703870096363521 ：
引用→　 刑事裁判ではおよそ自然的関連性すらないとして証拠能力が否定されるであろう「卒業文集」や「近所の人の話」をマスコミが垂れ流して，それで十分に心証形成した時点で一般市民が裁判員に選任されて被告人を裁く制度

ツイート：uwaaaa（サイ太）：2016/07/30 13:25： https://twitter.com/uwaaaa/status/759243445097656321 ：
引用→　 マスコミと卒業文集問題、誰かまとめちくり～

ツイート：uwaaaa（サイ太）：2016/07/29 17:06： https://twitter.com/uwaaaa/status/758936621508997124 ：
引用→　 「卒業文集を読めばその人の人となりがよく分かる」というのなら，マスコミ各社は入社試験に卒業文集を提出させればいいんですよ。

ツイート：uwaaaa（サイ太）：2016/07/28 11:05： https://twitter.com/uwaaaa/status/758483461703278592 ：
引用→　 小倉秀夫先生が出題した期末試験がマスコミの事件報道に一石を投じていて，いい問題すぎる＜改行＞＜改行＞benli: 首都大での期末試験＜改行＞https://t.co/KrcSiDGwQC

ツイート：uwaaaa（サイ太）：2015/08/27 09:12： https://twitter.com/uwaaaa/status/636692775103127552 ：
引用→　 普段は弁護士に対してはプライバシーを理由として防犯カメラの映像の提供を拒絶されているけど、捜査機関はマスコミにいとも簡単に提供するんですね。マスコミは構造的に弁護士よりもプライバシー侵害する蓋然性高いのに。

ツイート：uwaaaa（サイ太）：2014/10/05 23:48： https://twitter.com/uwaaaa/status/518774639514767360 ：
引用→　 加害者家族にも委員会派遣とかしてもいいのかもね。まあマスコミから追い込まれてる状況で弁護士を信用してくれるか分からないけど。

ツイート：uwaaaa（サイ太）：2014/08/19 13:41： https://twitter.com/uwaaaa/status/501589846834438144 ：
引用→　 数十年後に「えっ、数十年前はマスコミを監視する委員会なかったの！？」とか言われている未来が見える。

ツイート：uwaaaa（サイ太）：2014/03/06 11:48： https://twitter.com/uwaaaa/status/441404898530172928 ：
引用→　 公権力を監視するのがマスコミの役割だというのであれば（そしてその矜恃が残っているのなら），むしろ，「実質的逮捕です。この手続は違法の可能性があります。」と表現すべきなのでは。

ツイート：uwaaaa（サイ太）：2013/08/06 16:25： https://twitter.com/uwaaaa/status/364648310851645441 ：
引用→　 「マスコミ取材受忍義務」なんて、知る権利をどれだけ敷衍したって出てこねーよ

ツイート：uwaaaa（サイ太）：2013/01/22 08:51： https://twitter.com/uwaaaa/status/293506125503029248 ：
引用→　 故人をどのように弔うかは、マスコミの恣意によるべきではなく、遺族の意思にゆだねられるべきなのでは・・・？＞RT

ツイート：uwaaaa（サイ太）：2012/10/15 12:43： https://twitter.com/uwaaaa/status/257688064263086080 ：
引用→　 日本人の「出る杭はボコボコに叩いて社会的に抹殺する」っていう気質、マスコミ様のこういう野次馬根性が自己増幅させてるんじゃねーの？

ツイート：uwaaaa（サイ太）：2012/07/01 10:45： https://twitter.com/uwaaaa/status/219245429399879682 ：
引用→　 逮捕された段階で「犯人の心の闇を追う」などと称してプライバシー侵害をしまくるのが社会復帰の妨げになっているわけで。同じ論法でいけば無罪判決が出た時点で「捜査機関の発表を鵜呑みにして無罪推定の原則を理解しようとしない大手マスコミの闇」とかいう特集を実名出してやるべきだよね。

ツイート：uwaaaa（サイ太）：2010/09/21 21:05： https://twitter.com/uwaaaa/status/25111491906 ：
引用→　 ええ。無罪になったことで検察が揺らいだのと同様，こんなではマスコミも揺らいでると評価できますね。 RT @yutastm: @uwaaaa 結局、村木裁判からは、何も学んでいないのですね。また冤罪を生もうとしている自覚が全くないですね。RT @uwaaaa

ツイート：uwaaaa（サイ太）：2010/04/02 09:36： https://twitter.com/uwaaaa/status/11452937731 ：
引用→　 マスコミや一般人が「状況証拠」という言葉を使うときに念頭にあるのは，たとえば殺人事件の犯人性について，「被告人が被害者に恨みを募らせていたこと」とか，動機レベルの事実であることが多いように思われる。あとはせいぜい「犯行可能であったこと」くらいか。





