**** 「理解できないレイプ犯罪を「庇う」弁護士の「論理」(藤井誠二) 」に対する市川寛弁護士のツイート

:CATEGORIES: 市川寛弁護士
:TAGS: 市川寛弁護士,性犯罪,刑事弁護,検察庁,不起訴

2016-09-11　日曜日　11：26　＞＞ ［［　←これからの記述範囲の開始時刻］］＞＞

ツイート：imarockcaster42（弁護士 市川 寛）：2016/09/10 22:42： https://twitter.com/imarockcaster42/status/774603905053302784 ：
引用→　 理解できないレイプ犯罪を「庇う」弁護士の「論理」(藤井誠二) - Y!ニュース https://t.co/WB2sKycdyI … 仮にこの方の理屈どおりだとしても、不起訴にした検察庁に一言も文句を言わないのがさっぱりわからない。

　以下、市川寛弁護士がコメントしている記事からの一部引用。

／＊＊＊＊＊＊＊＊＊＊（引用開始）＊＊＊＊＊＊＊＊＊＊
引用URL＞＞＞＞：http://bylines.news.yahoo.co.jp/fujiiseiji/20160910-00062053/ 理解できないレイプ犯罪を「庇う」弁護士の「論理」(藤井誠二) - 個人 - Yahoo!ニュース

高畑本人だけの言い分を聞いただけで、釈放と同時にこれまで報道された事実関係を公に真っ向から否定するとは開いた口がふさがらない。推定無罪の原則を考慮しても、さらに被疑者の利益を守る弁護士という立場──被疑者の言い分だけ百パーセント信じるのが当たり前なのかもしれないが──裁判で事実を争ってもいないのに、こう表現してしまうメンタリティを疑う。

被害者は示談には応じたが、それは高畑氏がシロになったこととは違う。私の取材経験でも、性犯罪の場合、刑事裁判で被害を受けたことを法廷であれこれ聞かれることが嫌で──いまはビデオリンク方式等、法廷に顔をさらさないで証言する方法も導入されているが──被害者が示談に応じやすいという傾向が以前からある。そうした「事情」を利用してか、性犯罪の示談のプロをうたう弁護士事務所もあり、かつて私は問題にしたことがある。

また、性犯罪の被害者が裁判員裁判で裁判員に顔を知られるのを恐れて、性犯罪の起訴率が明確に低下しているという現実も生じている。

2012年5月23日の朝日新聞は、裁判員裁判の対象となる強姦致死傷、強制わいせつ致死傷、集団強姦致死傷の起訴率は、2005年と2010年を比較すると、72％から43％へ大きく落ち込んだことを報じていた。

皮肉なことに、裁判員裁判により性犯罪がさらに刑事罰等から逃れるような現象が起きており、こういう背景からも示談に持ち込む作戦を取る弁護士が増えた。性犯罪の示談の背景には、こうしたことがあるのを私たちは知らねばならないだろう。 

＊＊＊＊＊＊＊＊＊＊（引用終了）＊＊＊＊＊＊＊＊＊＊／

　なんか閉じていなかったみたいです。

2016-09-12　月曜日　00：32　＜＜ ［［　←これまでの記述範囲の終了時刻］］＜＜
