* 元自衛官、ツイッターに家裁批判を書き込み（毎日新聞） - Yahoo!ニュースを引用した足立啓太弁護士のツイートから考えること

:CATEGORIES: 弁護士あだちけいた
:TAGS: 足立啓太弁護士,宇都宮連続爆発自殺事件

2016-10-24　月曜日　10：44　＞＞ ［［　←これからの記述範囲の開始時刻］］＞＞

ツイート：keita_adachi（弁護士あだちけいた㌠シン･ゴジラはいいぞ）：2016/10/24 08:11： https://twitter.com/keita_adachi/status/790329766066782208 ：
引用→　 誤審かどうかは分からないけど、この攻撃性は語るに落ちるのような・・・＜改行＞＜改行＞＜宇都宮爆発＞元自衛官、ツイッターに家裁批判を書き込み（毎日新聞） - Yahoo!ニュース https://t.co/FuTyGzetmJ #Yahooニュース

　この足立啓太弁護士のツイートと引用されたネットニュース記事のことは、次のブログ記事として先にまとめてあります。

足立啓太弁護士のツイートから→　＜宇都宮爆発＞元自衛官、ツイッターに家裁批判を書き込み （毎日新聞） - Yahoo!ニュース,https://hirono2016s.wordpress.com/?p=42085

　この宇都宮の爆発事件のことを知ったのは昨日の午後、深澤諭史弁護士のタイムラインで次のリツイートを見たのが最初でした。

＞fukazawas（深澤諭史）のリツイート＞このリツイートの日時＞2016/10/23 14:58／2016/10/23 14:53＞ URL＞ https://twitter.com/fukazawas/status/790069783844663296 ＞
＞fukazawas（深澤諭史）がリツイートしたluckymangan（リーチ一発ツモ裏１）のツイートの内容＞
引用→　宇都宮の爆発に関する憶測や偏見ツイート、リツイートは、救助や捜査を混乱させるだけなんで、この段階ではしない方がよいかと思いますがね。また、特定団体に作業させる類のデマツイートは、偽計業務妨害罪に当たり得るし、それで逮捕された実例もあることは忘れない方がよいでしょうね。
＞元のツイートの投稿日時＞2016/10/23 14:53＞元のツイートのURL＞ https://twitter.com/luckymangan/status/790068706525184000

　上記の深澤諭史弁護士のリツイートを見たのは15時ぐらいだったように思いますが、テレビのチャンネルを回しても何もやっておらず、ネットで調べた情報では、テロの可能性が示唆されていました。

　夜になってからテレビのニュースで、元自衛官による自殺だと知りましたが、今朝のテレビの報道を見ていると、計画的に城址祭りの行列がさしかかる場所と時間を狙い、殺傷能力を高めるために金属片を混ぜていたという話もあります。

　今のところテレビでは繰り返し同じような内容の報道をしていますが、足立啓太弁護士がツイートで引用した記事には、テレビでは見たことのない情報がありました。

　11時07分になっていますが、ちょうどテレビのワイドスクランブルという情報番組で、ネットのニュース記事と同じような内容が、一部より詳しく紹介されました。娘が3人いて、自衛官を退官した頃に同居していた3女が精神疾患を患い、家庭内のトラブルが増えたということです。

　時刻は10月27日9時59分になっています。また2,3日の中断をしていたことはわかっていたのですが、中断前の項目が足立啓太弁護士の特集であったとは、まったく意外ですっかりと忘れていました。

　昨日も一昨日も新規の項目として取り上げたいことがいくつかあって、その下準備としてツイートのまとめは作成していました。昨日主に手がけたのが、福岡市天神の向原栄大朗弁護士、一昨日が神奈川県小田原市の村松謙弁護士でした。

　特に村松謙弁護士に関しては取り上げたい事柄が多すぎて、どの程度にまとめ紙面と時間の割り振りをすべきか、実に悩ましく考えていました。村松謙弁護士の場合は、問題点が多岐に渡るので、他との関連という調整も事前にしっかりした設計が必要だと考えていました。

　村松謙弁護士のツイートは、その後になるかとも思いますが、ジャーナリスト江川紹子さんと同じように輪島大祭の8月22日までタイムラインを遡り、これはと思うツイートを記録し、そのまとめも作成してあります。

　なぜ輪島大祭を一つの区切りとして遡ったのかというと、輪島大祭2日目の重蔵神社大祭の当日に、大物女優を母つ持つ若手俳優高畑裕太氏の強姦致傷事件があったからです。その事件は早期に示談成立による不起訴となりましたが、弁護士や江川紹子さんの反応に、大きな発見を見出す契機となりました。

　この作成中だった項目では、足立啓太弁護士のツイートを切り口に、宇都宮の連続爆発自殺事件のことを取り上げましたが、この宇都宮の事件のことは、輪島大祭を目指して村松謙弁護士のタイムラインを遡ったことで、大きな発見がいくつもありました。

　宇都宮の爆発事件のことは、村松謙弁護士のツイートを軸に取り上げていく方向で考えています。この宇都宮の事件に関してもモトケンこと矢部善朗弁護士（京都弁護士会）のタイムラインでは言及したようなツイートを確認していません。

　深澤諭史弁護士のタイムラインにおいては、いくつかリツイートとして取り上げたものを確認しています。間接的なかたちですが、深澤諭史弁護士にはこれまでもよく見てきたスタイルで、他に全く取り上げないスタイルもあって、そちらが主流とも見ています。

　次に項目として取り上げる、昨日午後3時過ぎの大川小学校の東日本大震災災害の損害賠償判決も、言及するツイートを見かけることがなかったもので、スクリプトを使ったことで見つかったのが数件で、そのうち項目として取り上げようと決めたのが、足立啓太弁護士のツイートでした。

2016-10-27　木曜日　10：40　＜＜ ［［　←これまでの記述範囲の終了時刻］］＜＜
* 「津波を予測できた」大川小学校めぐる裁判で遺族勝訴　14億円の賠償命令、に対する足立啓太弁護士のツイートで改めて考えた弁護士の社会責任

:CATEGORIES: 弁護士あだちけいた
:TAGS: 足立啓太弁護士,損害賠償,東日本大震災,地方自治体,行政

2016-10-27　木曜日　19：28　＞＞ ［［　←これからの記述範囲の開始時刻］］＞＞

　午前中に書く予定でいたのですが、本日は午後に用事があったこともあり、後のばしになっていました。用事というのは母親が入院する病院で半年に1回のカンファレンスがあったことです。幸い気温は寒かったものの天気は良かったのですがバイクが経験したことのないガス欠ぎりぎりでヒヤヒヤしました。

　本日はなにかと考えさせられることの多い一日です。一昨日の25日だったと思いますが、冬の準備としてこたつを用意しました。たぶん今までで一番遅かったと思います。昨日までは暑苦しくも感じていたのですが、今日の朝は電気を入れていても寒さを感じました。いよいよ冬が近づいています。

　病院からバイクで戻るとまだ明るい時間でしたがすっかり夕方の時間で、18時近くまで宇出津図書館にいて、スマホでフリック入力をいつものアプリで練習をしていました。それからAコープ能都店で買い物をして家に戻りましたが、晩ごはんはまだです。

　半額になっていた焼肉用の牛肉とサンチェという野菜を買ってきました。サンチェという野菜ははるか以前、何度か焼肉屋で食べたことはあるのですが、スーパーで買ってきたのは初めてのことです。今日は弁護士のことで考えるうち、韓国野菜を食べたい気分になりました。

　今、テレビでは「あのニュースで得する人損する人」の2時間スペシャル番組を番組開始の19時から見ていますが、食生活の家庭料理の情報ばかりです。坂上忍という芸能人が司会ということでも、興味深く見ているところです。

　このところお昼に見ることが多くなっているバイキングという番組も、同じ坂上忍さんが司会者ですが、今日の昼も見ていて実に考えさせられることがありました。芸能人が大麻所持で逮捕された問題で、どうせ大麻も覚せい剤も初犯ならば執行猶予と、嘆くように言っていたことです。

　このバイキングという番組は、終わりに次の「グッディ」という情報番組へのバトンタッチもしっかりしているのですが、今日はNHK連続テレビ小説べっぴんさん、を見た後、チャンネルを変え情報番組を見ていたのですが、ほどんど昨日の大川小学校の裁判の報道を見た覚えがありません。

　午前中の10時半からは北陸朝日舗装でワイドスクランブルという情報番組を見ていたのですが、これ以降は、たぶんはっきりと大川小学校の裁判の報道は見ていなかったように思います。見ていたとしても短い時間で印象に残らないものだったと思います。

　前置きがいくらか長くなったかも知れませんが、次にこの項目のメインテーマである足立啓太弁護士のツイートをご紹介します。

ツイート：keita_adachi（弁護士あだちけいた㌠シン･ゴジラはいいぞ）：2016/10/26 23:44： https://twitter.com/keita_adachi/status/791289387552157696 ：
引用→　 色々な思いがあるのだろうが、「断罪」はいらないんじゃないかな？＜改行＞＜改行＞「津波を予測できた」大川小学校めぐる裁判で遺族勝訴　14億円の賠償命令 https://t.co/CbkMfeOBT4 @HuffPostJapanさんから



／＊＊＊＊＊＊＊＊＊＊（引用開始）＊＊＊＊＊＊＊＊＊＊
引用URL＞＞＞＞：http://www3.nhk.or.jp/news/html/20161026/k10010744931000.html 大川小学校の津波訴訟 石巻市などに１４億円余の賠償命令 | NHKニュース

東日本大震災の津波で犠牲になった宮城県石巻市の大川小学校の児童の遺族が訴えた裁判で、仙台地方裁判所は「市の広報車が避難を呼びかけたのを教員らが聞いた時点で、津波が到達する危険を予測できた」と指摘して、石巻市などに対し原告全員に１４億円余りの賠償を支払うよう命じました。

石巻市の大川小学校は、学校の管理下としては震災で最も多い７４人の児童が津波の犠牲になり、このうち２３人の児童の遺族は石巻市と宮城県に対し１人当たり１億円、合わせて２３億円の賠償を求める訴えを起こしました。
裁判では海岸からおよそ４キロ離れた小学校まで津波が来ることを学校側が予測できたかどうかなどが大きな争点となりました。

２６日の判決で、仙台地方裁判所の高宮健二裁判長は、石巻市と宮城県に対し原告全員に合わせて１４億２６００万円余りの賠償を支払うよう命じました。
判決では「津波が襲ってくる７分前の遅くとも午後３時半ごろまでには、石巻市の広報車が津波が松林を越えてきていることを告げながら避難を呼びかけたのを、教員らが聞いていたと認められ、この時点で小学校に津波が到達する危険を予測できた」と指摘しました。そのうえで、「教員らが校庭からの移動先として目指した川沿いの交差点の標高は７メートル余りしかなく、避難場所としては不適当だった。一方で、近くの裏山には小走りで１分程度で移動できたうえ、過去に学習の場などで児童も登っていた場所で、避難するのに具体的支障はなく、避難についての過失があった」と指摘しました。

また、裁判所は「教員らはみずからの判断で自主的に避難することができない児童らを可能なかぎり避難させるべき義務を負い、多少の混乱をいとわずに児童らをせかし、小走りで移動させてでも早期の避難を最優先すべきだった」という判断を示しました。

大川小学校は当時、津波の避難場所に指定されていて、宮城、岩手、福島の３県の教育委員会によりますと、震災をめぐる裁判で、避難場所に指定された学校からさらに避難することについて過失が認められたのは初めてです。
「二度と悲劇起こさないで」

判決の言い渡しが行われた仙台地方裁判所では、午後３時１５分ごろ、原告の遺族が硬い表情で裁判所の玄関前に姿を現しました。そして、「勝訴」とか「子どもたちの声が届いた」などと書かれた旗を掲げ、外で待ち受けた関係者に判決を報告しました。

小学３年生の長男を亡くした原告団副団長の佐藤美広さんは、判決のあと「よい結果をもらい、正直ほっとしています。亡くなった子どもたちはこの場に来て、結果を聞いていると思います。息子は『おっとう、僕たちの分も頑張ってくれたな』と言っていると思います」と話していました。
また、原告の１人で小学５年生の次女を亡くした紫桃隆洋さんは「学校に責任があったことをようやく認めてもらい、亡くなった娘に報告したい。市と県、学校には命を預かる学校、先生の責任の重さを受け止め、二度と同じ悲劇を起こしてほしくない」と時折涙を浮かべながら話していました。

原告団長で、小学６年生の長男を亡くした今野浩行さんは、判決のあとの記者会見で、「皆さんは想像できるでしょうか。５１分間もの長い時間、自分が死ぬかもしれないという恐怖の中、死んでいった未来ある子どもたちのことを」と述べたうえで、「学校は津波を予見して子どもの命を守らなければならないという判決が下されたことに一定の評価をしたい」と話しました。
原告の１人で、小学６年生の三男を亡くした佐藤和隆さんは「震災から５年以上、『なぜ、なぜ、なぜ』でした。なぜ息子たちは死ななければいけなかったのか。裁判では、その部分が明らかになっていません。息子はどれだけ怖かったのか、石巻市と宮城県の教育関係者にわかってもらいたい」と涙ぐみながら話しました。そのうえで、「きょう判決は出ましたが、『なぜ』の部分の真実が明らかにされないかぎり、今後も同じことが繰り返されるという思いも強くなりました」と話しました。
原告の１人で小学３年生の長女を亡くした只野英昭さんは「判決が勝訴となり、新たな検証や話し合いの部分でも一歩進んだ内容になった」と判決に一定の評価をしました。そのうえで、「同じ悲劇を繰り返してほしくないと、大川小学校に足を運んだ人に語りかける『語り部』を続けていて、きょうの判決の内容も広く多くの人に語っていく必要がある」と話しました。
石巻市長「大変重く受け止めている」

判決のあと石巻市の亀山紘市長は会見し、「東日本大震災の際に、大川小学校の多くの児童が犠牲になったことについて、改めてご冥福を申し上げます」と述べたうえで、「ご遺族の思いや心の痛みに真摯（しんし）に対応してきたつもりでしたが、石巻市の主張が認められなかったという結果については大変重く受け止めています」と話しました。さらに、亀山市長は「判決の結果にかかわらず、学校の防災教育を含めて安心安全なまちづくりを進めていくことが課題であり、この悲劇をしっかりと伝承していかなければならないと考えています」と述べました。そのうえで、控訴するかどうかについては、「判決の内容をしっかりと精査したうえで、宮城県とも話し合いを進め、できるだけ早い段階で判断したい」と述べました。

判決について宮城県の村井知事は記者団に対し、「改めて亡くなった児童の皆さんのご冥福を心からお祈りします」と述べました。そして、控訴するかどうかについては、「宮城県の主張が認められなかったことは受け止めなければならないが、判決文を精査し石巻市とよく協議をして判断したい」と述べました。
傍聴の抽選 倍率は５．６倍

＊＊＊＊＊＊＊＊＊＊（引用終了）＊＊＊＊＊＊＊＊＊＊／

