**** 深澤諭史弁護士の「需要の開拓」、小倉秀夫弁護士の「新人弁護士を世に送り出す法科大学院の先生の役目」に対する返信ツイート

:CATEGORIES: 深澤諭史弁護士
:TAGS: 深澤諭史弁護士,小倉秀夫弁護士,法科大学院

2016-09-05　月曜日　10：02　＞＞ ［［　←これからの記述範囲の開始時刻］］＞＞

ツイート：Hideo_Ogura（小倉秀夫）：2012/11/26 18:56： https://twitter.com/Hideo_Ogura/status/273002208784699393 ：
引用→　 新人弁護士の職域を開拓するのは、日弁連でも、既存の弁護士でもなく、新人弁護士を世に送り出す法科大学院の先生の役目だということに、あの人たちはいつ気付くのだろう。

ツイート：fukazawas（深澤諭史）：2012/11/26 19:05： https://twitter.com/fukazawas/status/273004497381494785 ：
引用→　 @Hideo_Ogura 仰るとおりだと思います。そもそも「需要の開拓」にだって，調査や広報など，それなりのコストがかかります。法科大学院の学費や法科大学院協会も賛成した修習貸与制の「おかげ様」で，多くの新人にはそんなお金はありません。

　昨夜の遅い時間から深澤諭史弁護士のツイートを深澤諭史弁護士のTwitterの利用開始から遡って、問題性が高いと判断したものをデータベースに登録するという作業を始めました。

　深澤諭史弁護士のTwitterへの登録は2012年9月となっています。弁護士関連のアカウントとしては比較的遅い医療開始だと思いますが、2012年11月26日の時点で上記の小倉秀夫弁護士に関係したツイートを発見しました。

　深澤諭史弁護士の個人的な弁護士としての需要の開拓であれば理解できるのですが、弁護士業界全体としては逆効果としか思えないのが、今も変わらぬ深澤諭史弁護士の発言を見ていて感じるところです。

　ロースクール（法科大学院）の先生の教えを最大限に皮肉ったものに「成仏理論」があります。その辺りも踏まえて、小倉秀夫弁護士のツイートを読むと深澤諭史弁護士らの理想郷というのは、全く社会の常識や公益から乖離したものであり、そこをしっかりおさえておく必要があります。

　時刻は16時58分です。午前中、能登町役場にいるときに形態に電話があったのですが、その用事に13時過ぎから15時40分ぐらいまで出かけていました。

　実は数日前から深澤諭史弁護士と刑裁サイ太の取り扱いで悩むところがあり、それもあって初めからの深澤諭史弁護士のツイートを確認しておきたいという動機になったのかとも思います。そちらの作業は進んでいませんが、本人は次から次に悩ましい問題を連発してくれています。

　ストレートに言って、深澤諭史弁護士や刑裁サイ太を狂人扱いにすべきものか、病人扱いにすべきものなのか思い悩んでいました。不用意にそのような扱いにすることで誤解を招くことも考えましたが、弁護士であればこそ理解されるという部分もあるかと思います。

　深澤諭史弁護士を精神的な疾患のある病人として考察することは、彼の安易なストーカーの病人扱いとセットになっているので、社会防衛という意味での必要性も考えてきました。深澤諭史弁護士のタイムラインには彼のリツイートとしてよくよく考えるべき内容も多いです。

　正直、これまでは対応しきれないと諦めムードだったのですが、抜本的な解決や理解のためには、弁護士の新の意味での異常性、狂人性の世界に立ち入り、踏み込まなければならないと思うようになりました。それに対応するパソコンの技術的な環境も最近になって整えることが出来ました。

　順不同になるかと思いますが、深澤諭史弁護士に関して気になる点を、しっかりと押さえ、問題点の洗い出しをしていきたいと思います。

2016-09-05　月曜日　17：12　＜＜ ［［　←これまでの記述範囲の終了時刻］］＜＜
**** 深澤諭史弁護士がリツートした「法科大学院制度を推進する学者は、なぜ既存法曹をリスペクトしないのか 」というツイートから考える社会環境としてのの法曹養成問題

:CATEGORIES: 深澤諭史弁護士
:TAGS: 深澤諭史弁護士,法科大学院,法曹養成

2016-09-05　月曜日　17：16　＞＞ ［［　←これからの記述範囲の開始時刻］］＞＞

リツイート：fukazawas（深澤諭史）＞2016/09/05 12:53／2016/09/04 23:52＞ https://twitter.com/fukazawas/status/772643914041831425 ＞
 depon2010 （やっぱり猫が好き）＞ https://twitter.com/depon2010/status/772447259522834433 ＞
引用＞　 法科大学院制度を推進する学者は、なぜ既存法曹をリスペクトしないのか : Schulze　BLOG https://t.co/HyJkGYq7ME 

　 （やっぱり猫が好き）というプロフィールの名前ですが、Twitterのプロフィールは次のようになっています。

＜2016年09月05日(月) 17時20分53秒にTwitterAPIで取得したdepon2010（やっぱり猫が好き）のプロフィール情報＞
うんこレベル27

　このプロフィールでの「うんこレベル」というのは見覚えがあるのですが、プロフィールの名前に見覚えはなく、昨夜、深澤諭史弁護士の2012年年末当時のツイートを調べていて、初めて見たアカウントのような気がしていました。

　まだ正確に調べて確認はしていないのですが、深澤諭史弁護士のツイートをもれなくデータベースに登録するようになって、まだ一年は経過していないように思います。つまり不完全な状態のデータベースですが、今できる段階でできることをやっておこうと思います。

　昨夜は0時を過ぎた辺りに電気を消して眠りに入ったように思いますが、久しぶりに全身汗だくになって疲労も蓄積していたので、普段以上に頭がすっきりしない状態でした。ですので、（やっぱり猫が好き）という記録したツイートあるいはリツイートの内容も思い出すことが出来ません。

　まずは次のようにデータベースを操作する自作のコマンドを実行してみました。やはりプロフィールの名前には変更があったようです。ずいぶんと沢山の変更があります。

[6554]  % tw_user_tweet-sql-search-make-text-html-blogger-style.rb  --full_sql_text="SELECT * FROM tw_user_tweet WHERE tw_date BETWEEN '2000-07-22 20:14' AND '3300-07-24 23:59' AND (user LIKE \"depon2010\") ORDER BY tw_date ASC
"
％depon2010（スライム大王）のツイート％投稿日時％2012-10-23 21:38:00％ツイートのURL％ https://twitter.com/depon2010/status/260721862097653760 ％
％引用％ 刑事訴訟愛好会・・・(； ･`д･´)…ｺﾞｸﾘ…(`･д´･ ；)

％depon2010（やっぱり猫が好き）のツイート％投稿日時％2012-12-26 22:55:00％ツイートのURL％ https://twitter.com/depon2010/status/283934091911499778 ％
％引用％ 「法曹を増やす必要がある！」＜改行＞→（PもJも採用増やさない）＜改行＞→「弁護士を増やす必要がある！」＜改行＞→（弁護士の需要ない）＜改行＞→世界にあまねく法の光を！＜改行＞＼(^o^)／

％depon2010（やっぱり猫が好き）のツイート％投稿日時％2012-12-26 23:29:00％ツイートのURL％ https://twitter.com/depon2010/status/283942691337805824 ％
％引用％ @fukazawas どんどん現実から目を背けて宗教じみてきてるのがウケます。自分の業界でなければ…

％depon2010（デポースライム）のツイート％投稿日時％2015-09-22 10:27:00％ツイートのURL％ https://twitter.com/depon2010/status/646133590825152512 ％
％引用％ 総本山はあるかどうか分からないオアシスを求めて新人をしばくよりも、人の畑を土足で荒らす隣人をしばけよと思う。

％depon2010（ネコリーマン）のツイート％投稿日時％2015-10-05 12:29:00％ツイートのURL％ https://twitter.com/depon2010/status/650875502853419010 ％
％引用％ バッシングの酷さに公務員を進路の選択肢から外したのは20年前のことだったが、まだこのテーマがウケるのなら進歩がない。

％depon2010（ネコリーマン）のツイート％投稿日時％2015-10-05 12:33:00％ツイートのURL％ https://twitter.com/depon2010/status/650876387058827264 ％
％引用％ 司法試験は不人気、公務員は今もバッシングとなると後輩たちはどこに行ってるのだろうか。

％depon2010（ネコリーマン）のツイート％投稿日時％2015-10-05 22:59:00％ツイートのURL％ https://twitter.com/depon2010/status/651034093195366400 ％
％引用％ 相手の名前を明言せずに非難するツイートを見かけると「俺じゃないよな」と過去のツイートを振り返る気弱な私。大抵おっぱいとか呟いてるだけなので安心する。

％depon2010（ネコリーマン）のツイート％投稿日時％2015-10-07 21:31:00％ツイートのURL％ https://twitter.com/depon2010/status/651736614029299712 ％
％引用％ 近所の神社で不審者を見かけたと思ったらやはり緑の手の者だった。

％depon2010（ネコリーマン）のツイート％投稿日時％2015-10-15 22:26:00％ツイートのURL％ https://twitter.com/depon2010/status/654649537299021824 ％
％引用％ 業界として実質的な補助金獲得に向けて動くのは当然なんだけど「新聞は民主主義の大前提で〜」とか一段高みから補助されて当然みたいに言われるとムカつくよね。

％depon2010（ネコリーマン）のツイート％投稿日時％2015-10-23 21:49:00％ツイートのURL％ https://twitter.com/depon2010/status/657539411505053697 ％
％引用％ 検察官の捜査能力って警察の強制力・調査力と起訴権限（生殺与奪権）に裏打ちされたものだと思っているので、ただの人になったヤメ検にそこまで期待できないと思うのだが。

％depon2010（ネコリーマン）のツイート％投稿日時％2015-10-23 21:51:00％ツイートのURL％ https://twitter.com/depon2010/status/657539861528752128 ％
％引用％ @yasumasa218 「ヤメ検は夢を売る仕事」

％depon2010（ネコリーマン）のツイート％投稿日時％2015-10-26 22:10:00％ツイートのURL％ https://twitter.com/depon2010/status/658631727145877504 ％
％引用％ 儲かる商品ならとっくに大手保険会社が参入しているのでは… https://t.co/YYxoiM02yn

％depon2010（もっさりねこ）のツイート％投稿日時％2015-11-17 09:14:00％ツイートのURL％ https://twitter.com/depon2010/status/666408979354882048 ％
％引用％ 今ビギナー作ったら、借金にあえぐ主人公とか就職難に悩むおっさんとか非弁で懲戒食らう指導担当とかシャレにならないエピソードが連続しそう。

％depon2010（もっさりぬこ）のツイート％投稿日時％2015-11-23 09:19:00％ツイートのURL％ https://twitter.com/depon2010/status/668584539753594880 ％
％引用％ 総本山は「テレビ局は非弁を助長するような番組を作るな」と声明を出すべきでは。

％depon2010（もっこりぬこ）のツイート％投稿日時％2015-11-28 21:54:00％ツイートのURL％ https://twitter.com/depon2010/status/670586567950360576 ％
％引用％ ＞限りなく、司法書士による訴訟代理に近く、「司法書士訴訟」と呼ばれることもあります。＜改行＞＞法的には違法ではないですが、微妙なラインとのことです。＜改行＞＜改行＞また深澤先生が怒りそうなことを…

％depon2010（ぬこぬこニャース）のツイート％投稿日時％2015-12-02 09:22:00％ツイートのURL％ https://twitter.com/depon2010/status/671846803042529280 ％
％引用％ 司法改革の話かと思いました。 https://t.co/XJouxSbf3X

％depon2010（ぬこぬこニャース）のツイート％投稿日時％2015-12-02 12:27:00％ツイートのURL％ https://twitter.com/depon2010/status/671893330024763394 ％
％引用％ 私、修習は楽しい思い出しかない（異性関係除く）のだが、今の人はアウシュビッツとかシベリア抑留とか感じちゃうのね。司法制度改革はほんと罪作りだな。

％depon2010（ぬこぬこニャース）のツイート％投稿日時％2015-12-05 00:55:00％ツイートのURL％ https://twitter.com/depon2010/status/672806553775243265 ％
％引用％ 若手の業務開拓のために嘱託で非弁取締させれば、①若手の定期収入②職域の確保③適正手続の実現、と一粒で三度おいしいよね。誰かが言ってたけど。

％depon2010（ぬこぬこニャース）のツイート％投稿日時％2015-12-10 17:15:00％ツイートのURL％ https://twitter.com/depon2010/status/674864984019484672 ％
％引用％ 裏切り者に厳しい法曹界

％depon2010（可愛い猫ちゃんbot）のツイート％投稿日時％2015-12-14 08:44:00％ツイートのURL％ https://twitter.com/depon2010/status/676185922338066432 ％
％引用％ やっぱ弁護士報酬も軽減税率にすべきじゃね？民主主義でとりこぼされる少数者・弱者の人権保障という観点からすると新聞よりよほど痛税感を軽減すべきじゃね？

％depon2010（可愛い猫ちゃんbot）のツイート％投稿日時％2015-12-14 08:57:00％ツイートのURL％ https://twitter.com/depon2010/status/676189124101935104 ％
％引用％ 深澤先生が昔のツイートを掘り返してらっしゃる…俺はどんだけ軽減税率嫌いなんだ。

％depon2010（可愛い猫ちゃんbot）のツイート％投稿日時％2015-12-14 12:19:00％ツイートのURL％ https://twitter.com/depon2010/status/676240162565677056 ％
％引用％ 流石稼いでる弁護士は違う https://t.co/6xfWBTvhYp

％depon2010（鯖bot）のツイート％投稿日時％2015-12-14 23:20:00％ツイートのURL％ https://twitter.com/depon2010/status/676406474164207616 ％
％引用％ ふわもこと浜木綿は腐れ縁で素直になれない幼馴染かなんかなの？

％depon2010（鯖bot）のツイート％投稿日時％2015-12-17 08:39:00％ツイートのURL％ https://twitter.com/depon2010/status/677271920497307651 ％
％引用％ くまちん先生とかあだち先生とか道民の方が東京を満喫しているように見えるよな

％depon2010（鯖bot）のツイート％投稿日時％2015-12-21 13:21:00％ツイートのURL％ https://twitter.com/depon2010/status/678792412639051780 ％
％引用％ 「弁護士の信頼を守るため」というマジックワードに頼って安易に他人の金を注ぎ込まないようにして欲しいね。

％depon2010（鯖bot）のツイート％投稿日時％2015-12-22 12:03:00％ツイートのURL％ https://twitter.com/depon2010/status/679135146524602368 ％
％引用％ たまに刑事弁護に復帰したい気が起きるが、大抵法テラスへの不満が吹き荒れてるのを見て意欲がなくなる。まあ、人手は足りてそうだしな。

％depon2010（鯖bot）のツイート％投稿日時％2015-12-24 23:08:00％ツイートのURL％ https://twitter.com/depon2010/status/680027336654204932 ％
％引用％ 大体男だけ落ちて別れるか、男が修習地で浮気して別れるか、男が弁護士になってから浮気して別れるから気にすんな。 https://t.co/S3HL5fqu8G

％depon2010（不良猫）のツイート％投稿日時％2016-01-11 00:42:00％ツイートのURL％ https://twitter.com/depon2010/status/686211539309707265 ％
％引用％ 毎度毎度嬉々として地雷原を踏み抜いて走り抜けるこたんせ

％depon2010（ねこもん）のツイート％投稿日時％2016-01-30 13:45:00％ツイートのURL％ https://twitter.com/depon2010/status/693293964464492545 ％
％引用％ 貸与制で育った世代が「社会が俺たちに何をしてくれた。俺は金儲けを優先するぞ」と思うのは無理もないと思う。自分の労働に適正な対価が支払われなかったという怨みはなかなか忘れられない。

％depon2010（ねこもん）のツイート％投稿日時％2016-01-30 14:12:00％ツイートのURL％ https://twitter.com/depon2010/status/693300761845862400 ％
％引用％ 「弁護士が儲けるための研修に国が金を出す必要はない」というのが貸与制シフトの理由の１つなら、「我々は社会のために自己を犠牲にして尽くさねばならない」という弁護士側の思いは美しい片思いにも見える。

％depon2010（ねこもん）のツイート％投稿日時％2016-01-30 14:26:00％ツイートのURL％ https://twitter.com/depon2010/status/693304231294406657 ％
％引用％ なお私は社会に恋して弁護士になったわけではない。美女にモテモテになるために弁護士になったのだ。弁護士は儲からない的な流言蜚語は私の合コンにおける市場価値を著しく下げる言説であり容認しがたい。

％depon2010（こねこをこねこねしたい）のツイート％投稿日時％2016-03-11 19:02:00％ツイートのURL％ https://twitter.com/depon2010/status/708231721175527424 ％
％引用％ これ裏返すと、事件を選り好みできないくらい立場が弱くなったということでは。 https://t.co/97ytZuV4gm

％depon2010（社畜 Lv 1）のツイート％投稿日時％2016-04-02 03:58:00％ツイートのURL％ https://twitter.com/depon2010/status/716112442242142209 ％
％引用％ どこまでカミングアウトしてよいのかギリギリの判断が求められる。#ノース春の椿事

％depon2010（社畜 Lv 1）のツイート％投稿日時％2016-04-02 04:12:00％ツイートのURL％ https://twitter.com/depon2010/status/716115986152185857 ％
％引用％ 自己紹介から滲み出るネタ臭＜改行＞#ノース春の椿事

％depon2010（社畜 Lv 1）のツイート％投稿日時％2016-04-02 10:30:00％ツイートのURL％ https://twitter.com/depon2010/status/716211238921834496 ％
％引用％ おめでとうございます❤︎＜改行＞#ノース春の椿事 https://t.co/EQS4DHNMhg

％depon2010（社畜 Lv 1）のツイート％投稿日時％2016-04-03 02:11:00％ツイートのURL％ https://twitter.com/depon2010/status/716447966085537792 ％
％引用％ 初対面の人の第一声は「ああ、女子校の…」＜改行＞#ノース春の椿事

％depon2010（社畜 Lv 1）のツイート％投稿日時％2016-04-03 14:46:00％ツイートのURL％ https://twitter.com/depon2010/status/716637937912315904 ％
％引用％ 弁護士を組織の中で調整役に育てようとする企業は弁護士という人種を分かっていない。そういうことができない社会不適合者の集まりなんだぞ、我々は。

％depon2010（社畜 Lv 16）のツイート％投稿日時％2016-04-13 15:12:00％ツイートのURL％ https://twitter.com/depon2010/status/720268305865400320 ％
％引用％ やはり職業的魅力をアピールするには金ですよ金。金が嫌いな奴はまずいない。弁護士会は弁護士がいかに儲かるか激しくアピールすべき。

％depon2010（社畜 Lv 17）のツイート％投稿日時％2016-04-22 03:00:00％ツイートのURL％ https://twitter.com/depon2010/status/723345701795561473 ％
％引用％ @fukazawas 一発試験のお蔭で選ばれた旧試験世代が司法試験改革に口を出したのもけしからんというわけですね、分かります。

％depon2010（猫Lv1）のツイート％投稿日時％2016-06-23 12:51:00％ツイートのURL％ https://twitter.com/depon2010/status/745826573052428288 ％
％引用％ 弁護士がイノシ士となった今、我々は森の法律家を名乗るべきではないか

％depon2010（ウンコ製造機Lv15）のツイート％投稿日時％2016-07-14 09:20:00％ツイートのURL％ https://twitter.com/depon2010/status/753383715980521472 ％
％引用％ 弁護士の仕事ってミクロの積み重ねだからマクロな政策判断には向いてないと思うんだ…

％depon2010（シン・ウンコ製造機Lv22）のツイート％投稿日時％2016-08-06 10:40:00％ツイートのURL％ https://twitter.com/depon2010/status/761738565705314304 ％
％引用％ 弁護士は自営業だ自助努力だ自然淘汰だと言われ続ける中、さらに連帯責任まで負わされるのか。ダメな弁護士を選んでしまった依頼者の自己責任は問われないのか。何故弁護士被害だけ手厚く補償されるべきなのか。その辺の議論が全く見えないままの観測気球だな。

％depon2010（シン・ウンコ製造機Lv22）のツイート％投稿日時％2016-08-06 10:41:00％ツイートのURL％ https://twitter.com/depon2010/status/761739001443123201 ％
％引用％ まあ好きにしたらいいんじゃないかね。こんな不合理な負担を会員に課すような組織に所属しない法曹有資格者は増えそうだけどな。

％depon2010（シン・ウンコ製造機Lv22）のツイート％投稿日時％2016-08-06 10:45:00％ツイートのURL％ https://twitter.com/depon2010/status/761740047481573376 ％
％引用％ 報道される横領事件て500万じゃきかない事件ばかりだよね…信頼回復に役に立つのか？

％depon2010（やっぱり猫が好き）のツイート％投稿日時％2016-09-04 23:52:00％ツイートのURL％ https://twitter.com/depon2010/status/772447259522834433 ％
％引用％ 法科大学院制度を推進する学者は、なぜ既存法曹をリスペクトしないのか : Schulze　BLOG https://t.co/HyJkGYq7ME

　（スライム大王）から始まっていましたが、私の記憶に会ったのは「ウンコ製造機」を含むプロフィールの名前です。これは深澤諭史弁護士などのリツイートとは違うので自動収集での登録ではなく、私がツイートを見て、その場の判断として登録したものと考えられます。その割に多い数なのは意外でした。

　個人的には神意を感じるデータの抽出でした。問題を考える上で実に内容の濃い質の高いデータであると考えます。これも深澤諭史弁護士のおかげと言えばおかげです。とにかく参考にしていただくには期待をはるかに超えた資料になりました。

　「ウンコ製造機」とプロフィールに書きながら法律や法制度を語るのもどうかと思いましたが、深澤諭史弁護士や刑裁サイ太の日頃のツイートを見ていると何ら違和感なく受け入れることが出来ました。うんこにこだわるあたり、うの字とも関係があるのかと初めに目にした時に考えた記憶もあります。

　次は深澤諭史弁護士のリツイートとしてウンコ製造機とプロフィールに書いていた弁護士と思しきアカウントのツイートを洗い出しておきたいと思います。

　深澤諭史弁護士に限定しようかと思ったのですが、より幅広くデータベースに登録した弁護士関係者のアカウントのリツイートとして、その現段階における全部を次に掲載したいと思います。深澤諭史弁護士が多く目に付きますが、坂本正幸弁護士や小倉秀夫弁護士なども目についています。

（ウンコ製造機とプロフィールに書いていた弁護士と思しきアカウントのツイートをリツイートした法律関係者と思しき人々の記録）

＞yukimasashibata（弁護士 柴田幸正）のリツイート＞このリツイートの日時＞2015-05-14 22:21:00＞ URL＞ https://twitter.com/yukimasashibata/status/598840638600138752 ＞
＞yukimasashibata（弁護士 柴田幸正）がリツイートしたdepon2010（こねこをこねこねしたい）のツイートの内容＞
＞引用＞ 弁護士会の法律相談は歴史的使命を終えたのではないか。

＞keita_adachi（弁護士あだちけいた）のリツイート＞このリツイートの日時＞2015-09-21 16:29:00＞ URL＞ https://twitter.com/keita_adachi/status/645862318836838401 ＞
＞keita_adachi（弁護士あだちけいた）がリツイートしたdepon2010（デポースライム）のツイートの内容＞
＞引用＞ 中日が落ちぶれた分だけ強くなった球団もあるわけで、司法試験が落ちぶれた分だけ行政書士試験の格が上がったと思えば（違

＞keita_adachi（弁護士あだちけいた）のリツイート＞このリツイートの日時＞2015-09-22 10:27:00＞ URL＞ https://twitter.com/keita_adachi/status/646133703886827520 ＞
＞keita_adachi（弁護士あだちけいた）がリツイートしたdepon2010（デポースライム）のツイートの内容＞
＞引用＞ 総本山はあるかどうか分からないオアシスを求めて新人をしばくよりも、人の畑を土足で荒らす隣人をしばけよと思う。

＞fukazawas（深澤諭史）のリツイート＞このリツイートの日時＞2015-09-23 20:29:00＞ URL＞ https://twitter.com/fukazawas/status/646647556789800964 ＞
＞fukazawas（深澤諭史）がリツイートしたdepon2010（デポースライム）のツイートの内容＞
＞引用＞ 総本山はあるかどうか分からないオアシスを求めて新人をしばくよりも、人の畑を土足で荒らす隣人をしばけよと思う。

＞satoshihamada（弁護士　浜ちゃん）のリツイート＞このリツイートの日時＞2015-10-19 21:43:00＞ URL＞ https://twitter.com/satoshihamada/status/656088259311767552 ＞
＞satoshihamada（弁護士　浜ちゃん）がリツイートしたdepon2010（こねこをこねこねしたい）のツイートの内容＞
＞引用＞ 女医さんは知らんがとりあえずTLを印刷して見せれば女性弁護士については何も言わなくなるのではうわなんだやめろ

＞fukazawas（深澤諭史）のリツイート＞このリツイートの日時＞2015-10-23 21:52:00＞ URL＞ https://twitter.com/fukazawas/status/657540214055809026 ＞
＞fukazawas（深澤諭史）がリツイートしたdepon2010（ネコリーマン）のツイートの内容＞
＞引用＞ 検察官の捜査能力って警察の強制力・調査力と起訴権限（生殺与奪権）に裏打ちされたものだと思っているので、ただの人になったヤメ検にそこまで期待できないと思うのだが。

＞fukazawas（深澤諭史）のリツイート＞このリツイートの日時＞2015-10-23 21:53:00＞ URL＞ https://twitter.com/fukazawas/status/657540231554404352 ＞
＞fukazawas（深澤諭史）がリツイートしたdepon2010（ネコリーマン）のツイートの内容＞
＞引用＞ @yasumasa218 「ヤメ検は夢を売る仕事」

＞satoshihamada（弁護士　浜ちゃん）のリツイート＞このリツイートの日時＞2015-11-12 08:40:00＞ URL＞ https://twitter.com/satoshihamada/status/664588624755687424 ＞
＞satoshihamada（弁護士　浜ちゃん）がリツイートしたdepon2010（もっさりねこ）のツイートの内容＞
＞引用＞ 一人称が当職→ネタツイートだとよくやる＜改行＞新司法試験やロースクールを執拗に批判する→むしろ旧試合格者に多い＜改行＞司法書士を非弁扱いし毛嫌いする→むしろ弁護士に多い＜改行＞＜改行＞はっ！？もしや私も偽弁護士。。。

＞fukazawas（深澤諭史）のリツイート＞このリツイートの日時＞2015-11-12 18:11:00＞ URL＞ https://twitter.com/fukazawas/status/664732192614977537 ＞
＞fukazawas（深澤諭史）がリツイートしたdepon2010（もっさりねこ）のツイートの内容＞
＞引用＞ 一人称が当職→ネタツイートだとよくやる＜改行＞新司法試験やロースクールを執拗に批判する→むしろ旧試合格者に多い＜改行＞司法書士を非弁扱いし毛嫌いする→むしろ弁護士に多い＜改行＞＜改行＞はっ！？もしや私も偽弁護士。。。

＞uwaaaa（サイ太）のリツイート＞このリツイートの日時＞2015-11-17 09:23:00＞ URL＞ https://twitter.com/uwaaaa/status/666411356032098305 ＞
＞uwaaaa（サイ太）がリツイートしたdepon2010（もっさりねこ）のツイートの内容＞
＞引用＞ 今ビギナー作ったら、借金にあえぐ主人公とか就職難に悩むおっさんとか非弁で懲戒食らう指導担当とかシャレにならないエピソードが連続しそう。

＞satoshihamada（弁護士　浜ちゃん）のリツイート＞このリツイートの日時＞2015-11-17 09:26:00＞ URL＞ https://twitter.com/satoshihamada/status/666411996905009152 ＞
＞satoshihamada（弁護士　浜ちゃん）がリツイートしたdepon2010（もっさりねこ）のツイートの内容＞
＞引用＞ 今ビギナー作ったら、借金にあえぐ主人公とか就職難に悩むおっさんとか非弁で懲戒食らう指導担当とかシャレにならないエピソードが連続しそう。

＞keita_adachi（弁護士あだちけいた）のリツイート＞このリツイートの日時＞2015-11-17 11:29:00＞ URL＞ https://twitter.com/keita_adachi/status/666442979716915200 ＞
＞keita_adachi（弁護士あだちけいた）がリツイートしたdepon2010（もっさりねこ）のツイートの内容＞
＞引用＞ 今ビギナー作ったら、借金にあえぐ主人公とか就職難に悩むおっさんとか非弁で懲戒食らう指導担当とかシャレにならないエピソードが連続しそう。

＞mackckckck（弁護士ばびろん）のリツイート＞このリツイートの日時＞2015-11-17 20:28:00＞ URL＞ https://twitter.com/mackckckck/status/666578587441500160 ＞
＞mackckckck（弁護士ばびろん）がリツイートしたdepon2010（もっさりねこ）のツイートの内容＞
＞引用＞ 今ビギナー作ったら、借金にあえぐ主人公とか就職難に悩むおっさんとか非弁で懲戒食らう指導担当とかシャレにならないエピソードが連続しそう。

＞fukazawas（深澤諭史）のリツイート＞このリツイートの日時＞2015-11-17 22:49:00＞ URL＞ https://twitter.com/fukazawas/status/666614117319315457 ＞
＞fukazawas（深澤諭史）がリツイートしたdepon2010（もっさりねこ）のツイートの内容＞
＞引用＞ 今ビギナー作ったら、借金にあえぐ主人公とか就職難に悩むおっさんとか非弁で懲戒食らう指導担当とかシャレにならないエピソードが連続しそう。

＞fukazawas（深澤諭史）のリツイート＞このリツイートの日時＞2015-11-27 00:16:00＞ URL＞ https://twitter.com/fukazawas/status/669897441743757313 ＞
＞fukazawas（深澤諭史）がリツイートしたdepon2010（もっさりぬこ）のツイートの内容＞
＞引用＞ 裁判官が非常識だから一般人の視点をという意見も聞くが、一般人と一括りにするから常識的な判断がなされるように錯覚するだけで、非常識な人間が裁判員になることなんて幾らでもありうる。そもそも属性の数だけ常識はあって、八百屋には八百屋の、無職には無職の、裁判官には裁判官の常識があるだけ。

＞fukazawas（深澤諭史）のリツイート＞このリツイートの日時＞2015-12-02 09:22:00＞ URL＞ https://twitter.com/fukazawas/status/671846985184317440 ＞
＞fukazawas（深澤諭史）がリツイートしたdepon2010（ぬこぬこニャース）のツイートの内容＞
＞引用＞ 司法改革の話かと思いました。 https://t.co/XJouxSbf3X

＞fukazawas（深澤諭史）のリツイート＞このリツイートの日時＞2015-12-02 12:32:00＞ URL＞ https://twitter.com/fukazawas/status/671894734063845376 ＞
＞fukazawas（深澤諭史）がリツイートしたdepon2010（ぬこぬこニャース）のツイートの内容＞
＞引用＞ 給費・貸与、旧試・新試、ロー・予備と様々な対立軸があって弁護士会がますますまとまりづらくなりそうですな。 https://t.co/7FZWuX6nUB

＞fukazawas（深澤諭史）のリツイート＞このリツイートの日時＞2015-12-02 12:36:00＞ URL＞ https://twitter.com/fukazawas/status/671895728558501888 ＞
＞fukazawas（深澤諭史）がリツイートしたdepon2010（ぬこぬこニャース）のツイートの内容＞
＞引用＞ @fukazawas 弁護士って元々個性が強くて意思統一しづらい人種なので煽るまでもなく勝手に対立すると思います。

＞fukazawas（深澤諭史）のリツイート＞このリツイートの日時＞2015-12-09 13:20:00＞ URL＞ https://twitter.com/fukazawas/status/674443459231531008 ＞
＞fukazawas（深澤諭史）がリツイートしたdepon2010（ぬこぬこニャース）のツイートの内容＞
＞引用＞ 非弁取締の鬼 https://t.co/hAUHd6zeeT

＞fukazawas（深澤諭史）のリツイート＞このリツイートの日時＞2015-12-22 12:22:00＞ URL＞ https://twitter.com/fukazawas/status/679139822292701185 ＞
＞fukazawas（深澤諭史）がリツイートしたdepon2010（ねこもん）のツイートの内容＞
＞引用＞ たまに刑事弁護に復帰したい気が起きるが、大抵法テラスへの不満が吹き荒れてるのを見て意欲がなくなる。まあ、人手は足りてそうだしな。

＞fukazawas（深澤諭史）のリツイート＞このリツイートの日時＞2016-01-15 18:17:00＞ URL＞ https://twitter.com/fukazawas/status/687926572335165440 ＞
＞fukazawas（深澤諭史）がリツイートしたdepon2010（不良猫）のツイートの内容＞
＞引用＞ 政党や政治家の支持というのはシングルイシューで決める必要はないので、安保法制に反対だからといって自民党政治家に献金していたらおかしいということにはならないんじゃないだろうか。

＞keita_adachi（弁護士あだちけいた）のリツイート＞このリツイートの日時＞2016-01-16 21:57:00＞ URL＞ https://twitter.com/keita_adachi/status/688344428067438592 ＞
＞keita_adachi（弁護士あだちけいた）がリツイートしたdepon2010（スイーツbot）のツイートの内容＞
＞引用＞ 修習時代はフリーセルばかりやってて裁判官に怒鳴られたな。飲んでばかりだったし。あのころの自堕落な生活態度が今のパッとしない現実に繋がってる気がする。はぁ…もてまくりたい。

＞fukazawas（深澤諭史）のリツイート＞このリツイートの日時＞2016-01-20 23:28:00＞ URL＞ https://twitter.com/fukazawas/status/689816750272024581 ＞
＞fukazawas（深澤諭史）がリツイートしたdepon2010（ねこもん）のツイートの内容＞
＞引用＞ 最近ノース先生の意識がグイグイ高くなってて結婚てマジすごい

＞sakamotomasayuk（坂本正幸）のリツイート＞このリツイートの日時＞2016-01-30 17:20:00＞ URL＞ https://twitter.com/sakamotomasayuk/status/693348123603705856 ＞
＞sakamotomasayuk（坂本正幸）がリツイートしたdepon2010（ねこもん）のツイートの内容＞
＞引用＞ なお私は社会に恋して弁護士になったわけではない。美女にモテモテになるために弁護士になったのだ。弁護士は儲からない的な流言蜚語は私の合コンにおける市場価値を著しく下げる言説であり容認しがたい。

＞sakamotomasayuk（坂本正幸）のリツイート＞このリツイートの日時＞2016-01-30 17:22:00＞ URL＞ https://twitter.com/sakamotomasayuk/status/693348537082339328 ＞
＞sakamotomasayuk（坂本正幸）がリツイートしたdepon2010（ねこもん）のツイートの内容＞
＞引用＞ しかし昔は企業と比べてどうだとかいう話が出たことはあまりなかったと思うが…それだけ業界が自信を失っているのだろう

＞sakamotomasayuk（坂本正幸）のリツイート＞このリツイートの日時＞2016-01-30 17:22:00＞ URL＞ https://twitter.com/sakamotomasayuk/status/693348518790967296 ＞
＞sakamotomasayuk（坂本正幸）がリツイートしたdepon2010（ねこもん）のツイートの内容＞
＞引用＞ 法曹の仕事はやりがいを感じる要素は沢山あるし自由だし一般論としては魅力が多い仕事だと思うが、反面色んなタフさが要求される万人に勧められる仕事ではないとも思う。今までは金銭的魅力という万人ウケする要素でアドバンテージがあったが…

＞sakamotomasayuk（坂本正幸）のリツイート＞このリツイートの日時＞2016-01-30 17:22:00＞ URL＞ https://twitter.com/sakamotomasayuk/status/693348499069366272 ＞
＞sakamotomasayuk（坂本正幸）がリツイートしたdepon2010（ねこもん）のツイートの内容＞
＞引用＞ えらいさんがやりがいを持ち出す時、その人はやりがいを感じられたからこそ長い間この業界でやってきたわけであって、バイアスがかかってると思う。

＞sakamotomasayuk（坂本正幸）のリツイート＞このリツイートの日時＞2016-01-30 17:22:00＞ URL＞ https://twitter.com/sakamotomasayuk/status/693348490059976706 ＞
＞sakamotomasayuk（坂本正幸）がリツイートしたdepon2010（ねこもん）のツイートの内容＞
＞引用＞ 商社には商社の、弁護士には弁護士のやりがいがあるだけだと思うが…

＞fukazawas（深澤諭史）のリツイート＞このリツイートの日時＞2016-01-30 18:14:00＞ URL＞ https://twitter.com/fukazawas/status/693361541257699328 ＞
＞fukazawas（深澤諭史）がリツイートしたdepon2010（ねこもん）のツイートの内容＞
＞引用＞ 貸与制で育った世代が「社会が俺たちに何をしてくれた。俺は金儲けを優先するぞ」と思うのは無理もないと思う。自分の労働に適正な対価が支払われなかったという怨みはなかなか忘れられない。

＞mackckckck（弁護士じゃみろん）のリツイート＞このリツイートの日時＞2016-01-31 18:19:00＞ URL＞ https://twitter.com/mackckckck/status/693725340766605314 ＞
＞mackckckck（弁護士じゃみろん）がリツイートしたdepon2010（ねこもん）のツイートの内容＞
＞引用＞ 「弁護士が儲けるための研修に国が金を出す必要はない」というのが貸与制シフトの理由の１つなら、「我々は社会のために自己を犠牲にして尽くさねばならない」という弁護士側の思いは美しい片思いにも見える。

＞yiwapon（岩田 圭只）のリツイート＞このリツイートの日時＞2016-02-03 08:31:00＞ URL＞ https://twitter.com/yiwapon/status/694664588877369344 ＞
＞yiwapon（岩田 圭只）がリツイートしたdepon2010（ねこもん）のツイートの内容＞
＞引用＞ 意思が弱いので覚せい剤は絶対に近づかないぞ

＞uwaaaa（サイ太）のリツイート＞このリツイートの日時＞2016-02-04 12:37:00＞ URL＞ https://twitter.com/uwaaaa/status/695088647540908032 ＞
＞uwaaaa（サイ太）がリツイートしたdepon2010（ねこもん）のツイートの内容＞
＞引用＞ 某事務所は、刑事弁護に大枚はたける優良顧客層を宣伝でごっそり持って行っておいて、金にならない層は法テラス経由で他の弁護士に押し付けるという構図になってるから余計叩かれるのかな？

＞fukazawas（深澤諭史）のリツイート＞このリツイートの日時＞2016-02-20 09:31:00＞ URL＞ https://twitter.com/fukazawas/status/700840260293365761 ＞
＞fukazawas（深澤諭史）がリツイートしたdepon2010（ねこもん）のツイートの内容＞
＞引用＞ マスゲームを見て悦に入ってる独裁者みたいなもんか

＞fukazawas（深澤諭史）のリツイート＞このリツイートの日時＞2016-02-22 16:39:00＞ URL＞ https://twitter.com/fukazawas/status/701672614482161666 ＞
＞fukazawas（深澤諭史）がリツイートしたdepon2010（こねこをこねこねしたい）のツイートの内容＞
＞引用＞ ＞法科大学院制度は、そもそも、法曹志願者のうち、経済的・時間的に法科大学院に通えない人を切り捨てる制度なので、そもそも「多様性の確保」というのは自己矛盾なのです。

＞fukazawas（深澤諭史）のリツイート＞このリツイートの日時＞2016-02-27 11:19:00＞ URL＞ https://twitter.com/fukazawas/status/703404121739538433 ＞
＞fukazawas（深澤諭史）がリツイートしたdepon2010（こねこをこねこねしたい）のツイートの内容＞
＞引用＞ 社業に関係ある法律しか見ないし、先輩の指導を受ける機会も少ないですしねえ…最近はインハウス辞めて法律事務所に転身される人も多いようですが。 https://t.co/BmkFH4JiKG

＞fukazawas（深澤諭史）のリツイート＞このリツイートの日時＞2016-03-02 20:07:00＞ URL＞ https://twitter.com/fukazawas/status/704986589995270144 ＞
＞fukazawas（深澤諭史）がリツイートしたdepon2010（こねこをこねこねしたい）のツイートの内容＞
＞引用＞ 最近まともに法律問題調べてないし、ひたすら組織の調整ばっかやってるわ。法務部員が弁護士であることが有用ではない、とまでは言わんけど、弁護士である必要はないんじゃないかね。

＞fukazawas（深澤諭史）のリツイート＞このリツイートの日時＞2016-03-02 20:07:00＞ URL＞ https://twitter.com/fukazawas/status/704986552967954432 ＞
＞fukazawas（深澤諭史）がリツイートしたdepon2010（こねこをこねこねしたい）のツイートの内容＞
＞引用＞ 「ただ、「インハウスに需要があるか」といわれると、確かにあるのですが、この10年で1500人しか聞かないことからそこまで需要があるのか、という疑問、そして、また、インハウス弁護士登録を必要とするのか、という点については疑問が残ります。」

＞fukazawas（深澤諭史）のリツイート＞このリツイートの日時＞2016-03-02 20:07:00＞ URL＞ https://twitter.com/fukazawas/status/704986516112551936 ＞
＞fukazawas（深澤諭史）がリツイートしたdepon2010（こねこをこねこねしたい）のツイートの内容＞
＞引用＞ 「日弁連の提唱する「新しい分野」を見る限り、弁護士は増やす必要がない（修正）」＜改行＞⇒ https://t.co/tIMN87dzts

＞fukazawas（深澤諭史）のリツイート＞このリツイートの日時＞2016-03-02 20:31:00＞ URL＞ https://twitter.com/fukazawas/status/704992440218812416 ＞
＞fukazawas（深澤諭史）がリツイートしたdepon2010（こねこをこねこねしたい）のツイートの内容＞
＞引用＞ 言葉遊びに見えるかもしれないが、自分のアイデンティティをどこに置くかというのは存外重要なことだ思う。インハウスを検討しているおっさんたちは移籍ではなく全く違う職種に転職するつもりで考えて欲しい。俺はそろそろプリキュアに転生したい。

＞fukazawas（深澤諭史）のリツイート＞このリツイートの日時＞2016-03-02 20:35:00＞ URL＞ https://twitter.com/fukazawas/status/704993447959113729 ＞
＞fukazawas（深澤諭史）がリツイートしたdepon2010（こねこをこねこねしたい）のツイートの内容＞
＞引用＞ 少なくとも我が社が欲しいのは会社に属する弁護士ではなく法律に少し詳しい会社員だと思う。そういう観点からはインハウスを新しい弁護士像と称するのには違和感はある。新しい会社員像の間違いじゃね？

＞fukazawas（深澤諭史）のリツイート＞このリツイートの日時＞2016-03-02 22:55:00＞ URL＞ https://twitter.com/fukazawas/status/705028849042493440 ＞
＞fukazawas（深澤諭史）がリツイートしたdepon2010（こねこをこねこねしたい）のツイートの内容＞
＞引用＞ まあ無理っすね。いざという時に信念を貫けるのはいつ辞めても問題ない実力もってる人だけですよ。資格だけでは足りない。 https://t.co/ruZnh2TgTr

＞fukazawas（深澤諭史）のリツイート＞このリツイートの日時＞2016-03-03 08:37:00＞ URL＞ https://twitter.com/fukazawas/status/705175219464343552 ＞
＞fukazawas（深澤諭史）がリツイートしたdepon2010（こねこをこねこねしたい）のツイートの内容＞
＞引用＞ インハウスを讃える連中が総じて胡散臭いのはそうした当事者の心の機微を理解せず増員政策の失敗を糊塗するための便利なはめ込み先くらいにしか考えてなさそうなところが垣間見えるからだ。お前ら決裁の根回しとか役員の思いつきを有耶無耶にするテクとか身に付けたいかと膝詰めで問い詰めたい。

＞fukazawas（深澤諭史）のリツイート＞このリツイートの日時＞2016-03-03 08:37:00＞ URL＞ https://twitter.com/fukazawas/status/705175209825808384 ＞
＞fukazawas（深澤諭史）がリツイートしたdepon2010（こねこをこねこねしたい）のツイートの内容＞
＞引用＞ 言葉遊びに見えるかもしれないが、自分のアイデンティティをどこに置くかというのは存外重要なことだ思う。インハウスを検討しているおっさんたちは移籍ではなく全く違う職種に転職するつもりで考えて欲しい。俺はそろそろプリキュアに転生したい。

＞fukazawas（深澤諭史）のリツイート＞このリツイートの日時＞2016-03-03 08:37:00＞ URL＞ https://twitter.com/fukazawas/status/705175124706594816 ＞
＞fukazawas（深澤諭史）がリツイートしたdepon2010（こねこをこねこねしたい）のツイートの内容＞
＞引用＞ 結局執行部もLAW未来の会も自分の主張に都合がいいからインハウスインハウス言ってるだけで、本当の意味で我々の側に立ってるとは思えない。本来ならJILAがその役割を担うべきなのだろうが、あそこはあそこでなあ…

＞fukazawas（深澤諭史）のリツイート＞このリツイートの日時＞2016-03-03 08:37:00＞ URL＞ https://twitter.com/fukazawas/status/705175106826346496 ＞
＞fukazawas（深澤諭史）がリツイートしたdepon2010（こねこをこねこねしたい）のツイートの内容＞
＞引用＞ 昔「インハウスが増えればこれまで埋没していた法的問題が掘り起こされて需要は増える」とかいう主張を見かけた気がするが、インハウス入れるまでもなく法務部は経営層から存在意義の証明を絶え間なく求められて需要の掘り起こしを続けているのであって、それはインハウスとは関係なく進んでるな。

＞fukazawas（深澤諭史）のリツイート＞このリツイートの日時＞2016-03-08 12:55:00＞ URL＞ https://twitter.com/fukazawas/status/707052028359364608 ＞
＞fukazawas（深澤諭史）がリツイートしたdepon2010（こねこをこねこねしたい）のツイートの内容＞
＞引用＞ この手の調査って質問がよく練られてなくて回答しづらいものが多かった気がする。今回はどうかな。

＞Hideo_Ogura（小倉秀夫）のリツイート＞このリツイートの日時＞2016-03-13 19:31:00＞ URL＞ https://twitter.com/Hideo_Ogura/status/708963772698796034 ＞
＞Hideo_Ogura（小倉秀夫）がリツイートしたdepon2010（こねこをこねこねしたい）のツイートの内容＞
＞引用＞ 資格は好待遇を保障しないというのは正しいが、それは「100\%は保障しない」という意味であって、ある程度好待遇が期待できなきゃ誰がわざわざコストかけて資格とるかね。

＞fukazawas（深澤諭史）のリツイート＞このリツイートの日時＞2016-03-13 20:58:00＞ URL＞ https://twitter.com/fukazawas/status/708985465521643520 ＞
＞fukazawas（深澤諭史）がリツイートしたdepon2010（こねこをこねこねしたい）のツイートの内容＞
＞引用＞ 資格は好待遇を保障しないというのは正しいが、それは「100\%は保障しない」という意味であって、ある程度好待遇が期待できなきゃ誰がわざわざコストかけて資格とるかね。

＞fukazawas（深澤諭史）のリツイート＞このリツイートの日時＞2016-03-14 18:24:00＞ URL＞ https://twitter.com/fukazawas/status/709309290679443456 ＞
＞fukazawas（深澤諭史）がリツイートしたdepon2010（こねこをこねこねしたい）のツイートの内容＞
＞引用＞ RT 鍵：年収３００万円で働いている人いるんだから，弁護士も甘えるなとかあるけど，だったら，弁護士ならないで，上場企業に就職するわ。それが出来る人が大半じゃん。

＞fukazawas（深澤諭史）のリツイート＞このリツイートの日時＞2016-03-20 09:38:00＞ URL＞ https://twitter.com/fukazawas/status/711351220082855936 ＞
＞fukazawas（深澤諭史）がリツイートしたdepon2010（石油王の飼い猫）のツイートの内容＞
＞引用＞ 「弁護士以外に法律事務を依頼しませんでしたか？」＜改行＞「その依頼、違法です！」＜改行＞「既払い金返還請求なら○○法務！」（←お前もかよ） https://t.co/eAXoWSBiGU

＞fukazawas（深澤諭史）のリツイート＞このリツイートの日時＞2016-03-21 12:23:00＞ URL＞ https://twitter.com/fukazawas/status/711755108476846081 ＞
＞fukazawas（深澤諭史）がリツイートしたdepon2010（石油王の飼い猫）のツイートの内容＞
＞引用＞ 修習生が「最近人生めっちゃ楽しい」などと言いだしたら、原因は彼女ができたか現地妻ができたかマジックマッシュルームをキメたかだな。

＞fukazawas（深澤諭史）のリツイート＞このリツイートの日時＞2016-04-18 10:32:00＞ URL＞ https://twitter.com/fukazawas/status/722010016954253312 ＞
＞fukazawas（深澤諭史）がリツイートしたdepon2010（社畜 Lv 16）のツイートの内容＞
＞引用＞ やはり職業的魅力をアピールするには金ですよ金。金が嫌いな奴はまずいない。弁護士会は弁護士がいかに儲かるか激しくアピールすべき。

＞fukazawas（深澤諭史）のリツイート＞このリツイートの日時＞2016-04-22 03:00:00＞ URL＞ https://twitter.com/fukazawas/status/723345816157474817 ＞
＞fukazawas（深澤諭史）がリツイートしたdepon2010（社畜 Lv 17）のツイートの内容＞
＞引用＞ @fukazawas 一発試験のお蔭で選ばれた旧試験世代が司法試験改革に口を出したのもけしからんというわけですね、分かります。

＞fukazawas（深澤諭史）のリツイート＞このリツイートの日時＞2016-05-12 12:51:00＞ URL＞ https://twitter.com/fukazawas/status/730606341924888576 ＞
＞fukazawas（深澤諭史）がリツイートしたdepon2010（社畜 Lv 20）のツイートの内容＞
＞引用＞ 総本山が「もっとこの仕事のやりがいを若い人にアピールしなければ」というたびに「金とモテが目当ての俺みたいな人間は業界に要らないということか」と何となく面白くない。

＞fukazawas（深澤諭史）のリツイート＞このリツイートの日時＞2016-05-12 12:53:00＞ URL＞ https://twitter.com/fukazawas/status/730606769370583042 ＞
＞fukazawas（深澤諭史）がリツイートしたdepon2010（社畜 Lv 20）のツイートの内容＞
＞引用＞ @fukazawas 「やりがいアピールは結構だが同じ口で多様な人材が欲しいとか口走るなよ」とも思う。

＞satoshihamada（弁護士　浜ちゃん）のリツイート＞このリツイートの日時＞2016-05-13 09:02:00＞ URL＞ https://twitter.com/satoshihamada/status/730911083532193797 ＞
＞satoshihamada（弁護士　浜ちゃん）がリツイートしたdepon2010（猫Lv1）のツイートの内容＞
＞引用＞ 自営業なんだから失敗すれば資格も維持できずハイスペ無職になっても自己責任、職能団体はそんなことに配慮する必要はない、というのは一つのスタンスではあるけど、それなら今いる会員が失敗する確率を下げる方に全力投球すべきだと思う。法の光とか公益とかは余裕がある時にやれ。

＞fukazawas（深澤諭史）のリツイート＞このリツイートの日時＞2016-05-15 19:22:00＞ URL＞ https://twitter.com/fukazawas/status/731791807403565057 ＞
＞fukazawas（深澤諭史）がリツイートしたdepon2010（社畜 Lv 20）のツイートの内容＞
＞引用＞ 今日某所で法科大学院関係者が「このまま受験者が減り続けると旧試験で良かったのではないかという声が出てきかねない」「予備試験をなくさなきゃ法科大学院は立ち行かなくなる」と口走るのを聞いたが、5年くらい認識が遅れてるのではないだろうか。

＞fukazawas（深澤諭史）のリツイート＞このリツイートの日時＞2016-05-20 07:42:00＞ URL＞ https://twitter.com/fukazawas/status/733427564866207746 ＞
＞fukazawas（深澤諭史）がリツイートしたdepon2010（社畜 Lv 20）のツイートの内容＞
＞引用＞ 年を取るにつれて電車やエレベーターでの他人の邪魔な所作にイライラすることが多くなる。 https://t.co/WQp99E3GAN

＞fukazawas（深澤諭史）のリツイート＞このリツイートの日時＞2016-06-02 11:23:00＞ URL＞ https://twitter.com/fukazawas/status/738194361431662592 ＞
＞fukazawas（深澤諭史）がリツイートしたdepon2010（猫Lv1）のツイートの内容＞
＞引用＞ 「紺屋の白袴」「医者の不養生」に続き「法律事務所の人権侵害」という慣用句の普及が待たれる。

＞fukazawas（深澤諭史）のリツイート＞このリツイートの日時＞2016-06-02 12:23:00＞ URL＞ https://twitter.com/fukazawas/status/738209287227351042 ＞
＞fukazawas（深澤諭史）がリツイートしたdepon2010（猫Lv1）のツイートの内容＞
＞引用＞ 法律事務所の育成スタイルって基本これだよな

＞fukazawas（深澤諭史）のリツイート＞このリツイートの日時＞2016-06-02 22:28:00＞ URL＞ https://twitter.com/fukazawas/status/738361574776152064 ＞
＞fukazawas（深澤諭史）がリツイートしたdepon2010（猫Lv1）のツイートの内容＞
＞引用＞ 「学生ローン」で行きましょう！ https://t.co/bTQJ1tZA6h

＞Noooooooorth（ノース㌠）のリツイート＞このリツイートの日時＞2016-06-07 08:25:00＞ URL＞ https://twitter.com/Noooooooorth/status/739961330698850304 ＞
＞Noooooooorth（ノース㌠）がリツイートしたdepon2010（猫Lv1）のツイートの内容＞
＞引用＞ 肩書きだけJKになることに意味はない。私はJKという危うくも眩しい一筋の光そのものになりたいのだ。

＞fukazawas（深澤諭史）のリツイート＞このリツイートの日時＞2016-06-11 11:37:00＞ URL＞ https://twitter.com/fukazawas/status/741459186081370112 ＞
＞fukazawas（深澤諭史）がリツイートしたdepon2010（猫Lv1）のツイートの内容＞
＞引用＞ 非弁委員会、気になるのだが、気になるのだが、どう見ても地雷だ。。。

＞fukazawas（深澤諭史）のリツイート＞このリツイートの日時＞2016-06-25 10:04:00＞ URL＞ https://twitter.com/fukazawas/status/746509227686928384 ＞
＞fukazawas（深澤諭史）がリツイートしたdepon2010（猫Lv1）のツイートの内容＞
＞引用＞ イソ弁の待遇の悪さを嘆くよりボス弁になってイソ弁を安くこき使える良さを喜ぼう

＞fukazawas（深澤諭史）のリツイート＞このリツイートの日時＞2016-06-25 11:37:00＞ URL＞ https://twitter.com/fukazawas/status/746532746139340800 ＞
＞fukazawas（深澤諭史）がリツイートしたdepon2010（猫Lv1）のツイートの内容＞
＞引用＞ こういう時に「よし！儲けるチャンス！」と色々仕込もうとする人は儲かって「めんどくさいことしやがってイギリス許さん」とか不平を述べてるだけの人は時流から取り残されてジリ貧になるのだろうな。

＞fukazawas（深澤諭史）のリツイート＞このリツイートの日時＞2016-07-02 10:22:00＞ URL＞ https://twitter.com/fukazawas/status/749050506169888769 ＞
＞fukazawas（深澤諭史）がリツイートしたdepon2010（猫Lv1）のツイートの内容＞
＞引用＞ @fukazawas 「かけがえのない人生を生きる人々の喜びや悲しみに対して深く共感しうる豊かな人間性」…

＞fukazawas（深澤諭史）のリツイート＞このリツイートの日時＞2016-07-02 11:56:00＞ URL＞ https://twitter.com/fukazawas/status/749074230088654849 ＞
＞fukazawas（深澤諭史）がリツイートしたdepon2010（猫Lv1）のツイートの内容＞
＞引用＞ 金は無いけど弁護士なら助けてくれるはずだという図々しい思考の人が多いからですかね。

＞fukazawas（深澤諭史）のリツイート＞このリツイートの日時＞2016-07-15 14:04:00＞ URL＞ https://twitter.com/fukazawas/status/753817451356311553 ＞
＞fukazawas（深澤諭史）がリツイートしたdepon2010（ウンコ製造機Lv15）のツイートの内容＞
＞引用＞ 管理部門が毎年念仏のように業務効率化だのなんだの言い続けてるせいで現場レベルでやれる業務改善って大体この数年でやりつくされてるんだよな。結局残りかすみたいな無駄を省いたふりをして毎年やり過ごしてる。抜本的な改革をするには現場に相当豪腕な管理職が必要。

＞fukazawas（深澤諭史）のリツイート＞このリツイートの日時＞2016-07-17 11:37:00＞ URL＞ https://twitter.com/fukazawas/status/754505385126481920 ＞
＞fukazawas（深澤諭史）がリツイートしたdepon2010（ウンコ製造機Lv16）のツイートの内容＞
＞引用＞ 【再掲】修習中のシンポジウムで、裁判員制度の旗振り役だった学者出身の弁護士が「この制度は新しい民主主義の形なんです！」とはしゃいでるのに対し、他のパネリスト（JPB）が苦虫噛み潰した顔で歯切れの悪いコメントしてたのが笑えた。

＞fukazawas（深澤諭史）のリツイート＞このリツイートの日時＞2016-07-17 11:38:00＞ URL＞ https://twitter.com/fukazawas/status/754505528185720832 ＞
＞fukazawas（深澤諭史）がリツイートしたdepon2010（ウンコ製造機Lv16）のツイートの内容＞
＞引用＞ 裁判員裁判については、証拠の内容が分かりやすくなった等一定の肯定的な評価もあるようだけど、人が人を裁くという重責を特定の組織に集中して社会全体の効率化を図っていたのを逆行させる制度であって、労多くして益が少なく弊害も多い取組だったと思う。

＞fukazawas（深澤諭史）のリツイート＞このリツイートの日時＞2016-07-31 17:57:00＞ URL＞ https://twitter.com/fukazawas/status/759674240140398592 ＞
＞fukazawas（深澤諭史）がリツイートしたdepon2010（ウンコ製造機Lv20）のツイートの内容＞
＞引用＞ 吉田沙保里の話は、無料サービスで甘やかした客は優良（有料）顧客たりえないということを示してるな

＞fukazawas（深澤諭史）のリツイート＞このリツイートの日時＞2016-08-06 12:57:00＞ URL＞ https://twitter.com/fukazawas/status/761773268923617282 ＞
＞fukazawas（深澤諭史）がリツイートしたdepon2010（シン・ウンコ製造機Lv22）のツイートの内容＞
＞引用＞ 某委員会で予算策定時に効果の薄そうな事務を今年も実施するか問題になった時に、ベテランが「我々の金じゃないからジャンジャンやったらいい」と笑ってたのに対し50期台後半の先生が「原資は我々の会費なんだから我々の金です！そんな意識では困る！」と激怒したのは象徴的だった。

＞fukazawas（深澤諭史）のリツイート＞このリツイートの日時＞2016-08-06 12:57:00＞ URL＞ https://twitter.com/fukazawas/status/761773260123942914 ＞
＞fukazawas（深澤諭史）がリツイートしたdepon2010（シン・ウンコ製造機Lv22）のツイートの内容＞
＞引用＞ 弁護士会の問題点は、構成員が皆一国一城の主であって、会の仕事について当事者意識をもちにくいことだと思う。委員会とかも２年で交代だし、政策の効果測定や（失敗時の）事後的な責任追及という歯止めがかかりにくい。更に今の主導層は幸運な時代を過ごしたブル弁が中心なので支出増大にも甘くなる。

＞fukazawas（深澤諭史）のリツイート＞このリツイートの日時＞2016-08-26 12:30:00＞ URL＞ https://twitter.com/fukazawas/status/769014071131770882 ＞
＞fukazawas（深澤諭史）がリツイートしたdepon2010（やっぱり猫が好き）のツイートの内容＞
＞引用＞ 「自営業者も大変だしインハウスなろうかな」などと考えている若者は自分がそもそも弁護士目指すような変人だという自覚を持つべき。

＞fukazawas（深澤諭史）のリツイート＞このリツイートの日時＞2016-08-30 14:13:00＞ URL＞ https://twitter.com/fukazawas/status/770489710074535936 ＞
＞fukazawas（深澤諭史）がリツイートしたdepon2010（やっぱり猫が好き）のツイートの内容＞
＞引用＞ 弁護士は自営業だ自助努力だ自然淘汰だと言われ続ける中、さらに連帯責任まで負わされるのか。ダメな弁護士を選んでしまった依頼者の自己責任は問われないのか。何故弁護士被害だけ手厚く補償されるべきなのか。その辺の議論が全く見えないままの観測気球だな。

＞fukazawas（深澤諭史）のリツイート＞このリツイートの日時＞2016-09-05 12:53:00＞ URL＞ https://twitter.com/fukazawas/status/772643914041831425 ＞
＞fukazawas（深澤諭史）がリツイートしたdepon2010（やっぱり猫が好き）のツイートの内容＞
＞引用＞ 法科大学院制度を推進する学者は、なぜ既存法曹をリスペクトしないのか : Schulze　BLOG https://t.co/HyJkGYq7ME

　時刻は19時20分です。TwitterAPIのリミット制限に掛かるのかとひやひやしながら告発-金沢地方検察庁御中_ツイッター（@kk_hirono）に投稿していましたが、不測の送信エラーは別にして、とりあえずは無事に投稿が出来たようです。

　告発-金沢地方検察庁御中_ツイッター（@kk_hirono）には文字数超過で投稿できませんが、リツイートの記録は次のコマンドの実行で取得したデータです。ほんの数秒間の処理ですが、ずいぶんと沢山の該当データがあるものだと思いました。

[6556]  % tw_user_tweet-sql-search-make-text-html-blogger-style.rb  --full_sql_text="SELECT * FROM tw_user_tweet WHERE tw_date BETWEEN '2000-07-22 20:14' AND '3300-07-24 23:59' AND (rt_user LIKE \"depon2010\") ORDER BY tw_date ASC" | xsel -b

　深澤諭史弁護士や刑裁サイ太が特別なのだという思いがありましたが、そういう私の見立てや洞察もまったく不十分であることを思い知らされました。類友感満載ですが、モトケンこと矢部善朗弁護士（京都弁護士会）のリツイートはなかったように思います。

　他にも業務、業界として不利益と判断した同業者はいそうです。弁護士やそれらしいアカウントは私としても日々新たな発見があるぐらいなので、モトケンこと矢部善朗弁護士がウンコ製造機の存在すらしらないという可能性も十分にあるかと思いますが、リツイートするのも同調性の現れなのだと思います。

　ウンコ製造機とプロフィールに書いていた弁護士の存在も、私自身、昨夜から本日にかけて注視するようになったところで、疲労感からずいぶんと思考力も低下していたのですが、特別な印象として残っていたのは、次のツイートを目にしていたからだと納得しました。

　それにしても本日深澤諭史弁護士がウンコ製造機とプロフィールに書いていたアカウントのツイートをリツイートしていなければ、ここまで踏み込むことも出来なかったように思います。「弁護士深澤まつり」の不快と危機感の伴うものですが、その有用性をあらためて感じた次第です。

　以前、牛頭天王やスサノオについて調べた時、どちらかあるいは両方に見たように思うのですが、「人を狂わせてメッセージを伝えることがある」と言った趣旨の解説を目にした記憶があります。同じWikipediaのページだったようにも思うのですが、最近に見たものではその記載が見当たりません。

　ここ最近の弁護士界隈の傾向としては、小倉秀夫弁護士がずいぶんとおとなしくなったという印象もあります。さほど人間としての異常性も感じない日々が続いています。

　小倉秀夫弁護士に関しては、2回ほど、かなりきついメンションを送ったことははっきり憶えていますが、その影響というのも確認できるものではなく、反応のない状況が続いています。

　いよいよ本項目の本題に入りたいと思いますが、ウンコ製造機とプロフィールに書いていた弁護士と思しきアカウントのツイートの内容は次のようになっています。

ツイート：depon2010（やっぱり猫が好き）：2016/09/04 23:52： https://twitter.com/depon2010/status/772447259522834433 ：
引用→　 法科大学院制度を推進する学者は、なぜ既存法曹をリスペクトしないのか : Schulze　BLOG https://t.co/HyJkGYq7ME

　インターネットの利用に慣れていないと気づかない人のほうが多いと思いますが、なにかのコメントではなく、URLを紹介したブログ記事のページタイトルのみの紹介だと思います。ページタイトルの取得にはいくつかの方法がありますが、ブラウザのアドンを利用する方法が最も簡単かと思います。

Schulze　BLOG:法科大学院制度を推進する学者は、なぜ既存法曹をリスペクトしないのか http://blog.livedoor.jp/schulze/archives/52166248.html

　開いたページで実際にページタイトルを取得したのが上記のものになります。ウンコ製造機とプロフィールに書いていた弁護士と思しきアカウントのものとは、若干違いが認められます。

　ずい分前、多分羽咋市で生活していた頃から時たま目にしていたブログだと思います。初めに見た頃からかわりなくブルトーザーでの宅地造成工事を思われる画像が使われています。今回、今までとは違って注意深く観察したところページ内の目立たない場所で次の情報を見つけました。

／＊＊＊＊＊＊＊＊＊＊（引用開始）＊＊＊＊＊＊＊＊＊＊
引用URL＞＞＞＞：http://blog.livedoor.jp/schulze/archives/52166248.html Schulze　BLOG:法科大学院制度を推進する学者は、なぜ既存法曹をリスペクトしないのか

訪問者数(uu)

    今日：
        1606

    昨日：
        1452

    累計：
        2808808

アクセスカウンター(pv)

    9/5
        訪問者数
        5367

    9/4
        訪問者数
        5581

    9/3
        訪問者数
        5747

    9/2
        訪問者数
        6910

    9/1
        訪問者数
        7085

    8/31
        訪問者数
        4510

    8/30
        訪問者数
        4545

    8/29
        訪問者数
        5370

    8/28
        訪問者数
        4161

    8/27
        訪問者数
        2975

訪問者数はユニークユーザー数(uu)を表示。アクセスカウンターはページビュー(pv)の回数。
※訪問者数の累計は、2007年11月19日より。
Profile
管理人 schulze（シュルジー）

某上場企業で企業内弁護士をしています。
平成18年旧司法試験合格
平成20年司法研修所入所
平成21年9月弁護士登録（現行62期）

ハンドルネームの由来は、オリックスの元ピッチャーであるシュルジーから。
大学時代からミニコミのペンネームとして使ってましたが、シュルジーを選んだ理由は、塩瀬盛道（元東急フライヤーズのピッチャーで、プロ野球での生涯打撃成績が1打数1安打1本塁打、打率10割、長打率40割という選手。）の引退後の人生を描いた「ヒーロー伝説」という本に感銘を受けたのだが、生涯打撃成績が1打数1安打1本塁打といえばシュルジーもそうだということに気付いたため・・・って理由になってませんね、ハイ。
http://www.youtube.com/watch?v=iUwPLcz5QeI&feature=player_detailpage#t=205s

（※管理人へのメールは、管理人が運営しているサイトの掲示板一番下の「管理者へメール」ボタンをクリックし、投稿フォームを利用してください。）

コメントを投稿する際には、いわゆる捨てハンドルではなく、他人と識別できるお名前を名乗るようにしてください。なお「名無し」や「通りすがり」はＮＧワードに設定していますので投稿できません。捨てハンドルの投稿には原則として管理人は応答しません。また、予告なく削除する場合があります。


＊＊＊＊＊＊＊＊＊＊（引用終了）＊＊＊＊＊＊＊＊＊＊／

　平均的に一日あたり4千から6千あたりのPV数があるブログのようです。ウンコ製造機とプロフィールに書いていた弁護士と思しきアカウントが、本人で運営するブログという可能性もあるかと考えましたが、確認の術はありません。

　ブログの記事で対象にしているのは、私が数日前に独立した項目として取り上げていたインターネット上の情報でした。それに対する反論が動機であり、問題の提起なのだと思います。

告訴状の下書き）法曹は「社会の医師」だ　外国に馬鹿にされないために「質」高める法曹教育を　神戸大学特命教授・西村和雄,http://hirono2016k.blogspot.com/2016/09/blog-post_51.html

　ブルトーザーのブログは、既に書いたように数年前から頻度は低いですが、何度か目にする機会がありました。余り踏み込んで調べるという気力にはならなかったのですが、司法制度改革や現状の弁護士環境にはずいぶんと不満があるのだなと、という印象を受けていました。

　時期的に重なるとも思うのですが、似たように感じる法律関係者と思われるブログは他にもありました。最近は見かけなくなっているので、私の記憶が曖昧になっていることと相まって、探しだすのは無理かとも思いますが、できる範囲でやってみたいと思います。

奉納＼さらば弁護士鉄道・泥棒神社の物語(@hirono_hideki)/「黒猫」の検索結果 - Twilog http://twilog.org/hirono_hideki/search?word=%E9%BB%92%E7%8C%AB&ao=a

　上記のTwilogを利用した検索で結果がありました。かすかに「黒猫」というキーワードが頭に残っていたのですが、羽咋市に住んでいた頃より、モトケンこと矢部善朗弁護士（京都弁護士会）の「元検弁護士のつぶやき」というブログ名とは、通じるところがありそうだと考えていた記憶があります。

ツイート：hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）：2015/08/22 12:55： https://twitter.com/hirono_hideki/status/634937030686867456 ：
引用→　 弁護士人口の「頭打ち」が意味するもの - 黒猫のつぶやき http://t.co/ojEo1zyzmG

ツイート：hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）：2015/02/06 18:40： https://twitter.com/hirono_hideki/status/563633296589221889 ：
引用→　 ついに出た！　偏見丸出しの「裁判員判決」 - 黒猫のつぶやき http://t.co/8Zy5pgKJFS 被告人も「自分はアスペルガー症候群だからという理由で重く処罰されたのだ」と認識して国家権力を逆恨みするだけで，結論として社会秩序の維持には全く寄与しないでしょう。

ツイート：hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）：2013/04/17 21:46： https://twitter.com/hirono_hideki/status/324504086017875968 ：
引用→　 本当の「反省」とは何か - 黒猫のつぶやき http://t.co/IiESmfnn3l＜改行＞法科大学院問題その他の司法制度，資格，時事問題などについて日々つぶやいています。ちなみに，かなりの辛口ブログです。＜改行＞＜改行＞プロフィール＜改行＞性別＜改行＞非公開＜改行＞都道府県＜改行＞非公開＜改行＞自己紹介＜改行＞非公開

ツイート：hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）：2013/04/17 21:26： https://twitter.com/hirono_hideki/status/324499176048189440 ：
引用→　 本当の「反省」とは何か - 黒猫のつぶやき http://t.co/icyDcTvadi 弁護士の不祥事というのも若手よりベテランの方が、圧倒的に多いはずだけど。

ツイート：hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）：2013/04/17 21:16： https://twitter.com/hirono_hideki/status/324496658094239744 ：
引用→　 （引用→）かねてから司法改革に批判的だった論者からは概ね好意的に評価されているようですが，黒猫としてはあまり高く評価する気にはなれません。なぜなら，政府の政策決定に関わってきた「御用学者」を痛烈に批判する一方で，郷原弁護士自身の言い分 http://t.co/GuXWiM3bCD

ツイート：hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）：2013/04/17 21:14： https://twitter.com/hirono_hideki/status/324496017129095168 ：
引用→　 本当の「反省」とは何か - 黒猫のつぶやき http://t.co/95VbEn56Dz

　今初めて気がついたのですが、「黒猫のつぶやき」というブログはFC２のブログのものとgooのブログのものがあるようです。FC２のブログのプロフィールに少し目を通しましたが、記憶にもない内容でした

　gooのブログのプロフィールには東京弁護士会所属の弁護士ということと、55期と書いてありました。司法修習生としての期のことだと思いますが、私はいまだに期の数字を見ても、何時頃の登録なのかさっぱり意味がわかりません。前に調べてそこそこ理解したこともあったのですがすぐに忘れました。

　本項目のメインであるウンコ製造機とプロフィールに書いていた弁護士と思しきアカウントのツイートで、紹介されていたブルトーザーのブログ記事ですが、あえて言及しようという気持ちにもなりません。はるかにそれ以前のレベルの内容です。

　リスペクトというのは尊敬というような意味だったと思いますが、「法科大学院制度を推進する学者は、なぜ既存法曹をリスペクトしないのか」どころの問題ではなく、弁護士の狂人性と社会的危険性・有害性を深刻に考えさせてくれるだけのものです。

　リスペクトせよという暗黙の要求は、モトケンこと矢部善朗弁護士にも度々感じてきたものです。ド素人言う決め付けを含め余りにもバランスの悪いマスコミや警察、検察、裁判所批判に、やはり病的な異常性を強く感じますし、それを前提にしないと正しい理解と対処には辿りつけないと思います。

告訴状の下書き）マスコミ・報道関係ｚ（2016年9月3日のまとめ分）,http://hirono2016k.blogspot.com/2016/09/201693.html
告訴状の下書き）実名報道（2016年9月3日まとめ分）,http://hirono2016k.blogspot.com/2016/09/201693_3.html

　ｚというのはミスで、思いがけずわかりにくいタイトル名にもなっていることに気が付きましたが、上記はいずれもモトケンこと矢部善朗弁護士（京都弁護士会）のツイートをまとめたものです。

　ずいぶん手間を掛けましたが、情報を整理できたことで、思いがけない発見があったり、理解を深めることが出来ました。

　時刻は9月6日7時37分になっています。昨夜はずいぶん久しぶりにテレビの2時間ドラマを見ました。半年ぶりに近いかも知れず、前回見たものも記憶にはありません。それほど興味深い事前情報でもなかったのですが、ヤメ判という言葉にひかれたように思います。

ツイート：hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）：2016/09/05 22:18： https://twitter.com/hirono_hideki/status/772785892004159488 ：
引用→　 月曜名作劇場「ヤメ判　新堂謙介　殺しの事件簿4」＜改行＞2016年9月5日（月）  21時00分～22時54分  の放送内容 https://t.co/rn0e6ji0PR

ツイート：hirono_hideki（奉納＼さらば弁護士鉄道・泥棒神社の物語）：2016/09/05 22:18： https://twitter.com/hirono_hideki/status/772786035927441409 ：
引用→　 伊豆国で連続復讐劇！！駿河湾に浮かぶ愛の炎・・・15年前の死体が蘇生！？元判事が連続殺人犯と語る11分間の衝撃的真相！「私は愛していました・・・」 https://t.co/uvb4YRFM56

　15年前に刑事裁判を担当した元裁判長が、清掃員をしながら15年前の事件の関係者らの間で起った2件の殺人事件を解決していくというドラマでした。この手のドラマの定石ですが、主人公は優秀で機微や変化を見ぬいて問題を解決へと導いていきます。

Schulze　BLOG:法科大学院制度を推進する学者は、なぜ既存法曹をリスペクトしないのか http://blog.livedoor.jp/schulze/archives/52166248.html

　昨日、ご紹介した上記のブログ記事では、「型にはまった思考しか出来ない」という法科大学院関係者のダメ出しに対する反論のようなものが書いてありました。型にはめるのが法律家の職分とも私は考えるのですが、パターン化した思考プロセスしかたどることが出来ないという意味で納得です。

　ブログのページを見直すと、プロフィールが次のように書いてありました。昨日理解できていない、と書いていた司法修習生の期のこともわかりやすい具体例として書いてありました。

／＊＊＊＊＊＊＊＊＊＊（引用開始）＊＊＊＊＊＊＊＊＊＊
引用URL＞＞＞＞：http://blog.livedoor.jp/schulze/archives/52166248.html Schulze　BLOG:法科大学院制度を推進する学者は、なぜ既存法曹をリスペクトしないのか

Profile
管理人 schulze（シュルジー）

某上場企業で企業内弁護士をしています。
平成18年旧司法試験合格
平成20年司法研修所入所
平成21年9月弁護士登録（現行62期）

＊＊＊＊＊＊＊＊＊＊（引用終了）＊＊＊＊＊＊＊＊＊＊／

　平成21年の司法修習を終えてその年の9月に弁護士登録したのが62期ということになるようです。

2016-09-06　火曜日　08：03　＜＜ ［［　←これまでの記述範囲の終了時刻］］＜＜
**** 時間の経過で辿りようもなくなる深澤諭史弁護士の「あるある＞ＲＴ」ツイートに見る弁護士の異常性（狂人性？）と欺瞞性

:CATEGORIES: 深澤諭史弁護士
:TAGS: 深澤諭史弁護士

2016-09-06　火曜日　08：09　＞＞ ［［　←これからの記述範囲の開始時刻］］＞＞

ツイート：fukazawas（深澤諭史）：2016/09/03 10:51： https://twitter.com/fukazawas/status/771888204005859328 ：
引用→　 ＞ＲＴ＜改行＞あるあるすぎてあれ

ツイート：okumuraosaka（TORU OKUMURA）：2016/09/03 10:50： https://twitter.com/okumuraosaka/status/771888073571307520 ：
引用→　 「だから相談料はタダにしてくれ」という趣旨のことが多い。「他人の名前を挙げれば無料」という発想なのか https://t.co/N6CGg49xsG

ツイート：fukazawas（深澤諭史）：2016/09/03 10:50： https://twitter.com/fukazawas/status/771888135978430464 ：
引用→　 ＞ＲＴ＜改行＞あるあるすぎる（・∀・）

ツイート：okumuraosaka（TORU OKUMURA）：2016/09/03 10:48： https://twitter.com/okumuraosaka/status/771887603238903809 ：
引用→　 「（こっちは知らない）○○弁護士　××教授からお名前をうかがいまして・・・」とかいう前置きは　こちらにはなんの意味もない。ネットで見たというのと同じ。わからないのは奥村に投げる

　上記のツイートは直近でみかけた深澤諭史弁護士の「あるある＞ＲＴ」ツイートです。直前のリツイートに言及したというスタイルかと思いますが、完全に独立したツイートになっているので関連性はなく、彼はTwilogの登録もしていないので、200件を超えると辿ることもできなくなります。

非常上告-最高検察庁御中_ツイッター(@s_hirono)/「あるある」の検索結果 - Twilog http://twilog.org/s_hirono/search?word=%E3%81%82%E3%82%8B%E3%81%82%E3%82%8B&ao=a

　スクリーンショットなども記録するようにしているので、ある程度は上記の私のTwilogから辿れるのですが、それにしても嫌がらせのような困難さが伴います。上記のページで、#弁護士あるある というハッシュタグを発見しました。

#弁護士あるある from:fukazawas - Twitter検索 http://bit.ly/2bPfaH7

　上記のページからいくつか深澤諭史弁護士のハッシュタグのツイートを拾ってみたいと思います。

ツイート：fukazawas（深澤諭史）：2016/02/18 10:27： https://twitter.com/fukazawas/status/700129538110394369 ：
引用→　 「私が持ってきたこの資料をみれば，全部わかるはずである。だから，見通しや方針，費用を教えろ」といわれて，分かったためしがない。＜改行＞＜改行＞（・∀・）病院に電話やメールをして，症状だけ伝えて，全治日数と治療方針を聞いても教えてもらえない（できない）のと同じですね。＜改行＞#弁護士あるある

ツイート：fukazawas（深澤諭史）：2016/02/11 10:33： https://twitter.com/fukazawas/status/697594195804946432 ：
引用→　 「法律相談に行ったら，この事件では示談金ＸＸ万円はとれると聞いた！」＜改行＞私はそうは考えませんでしたが，何故，その先生に依頼しなかったのですか？＜改行＞「・・・」＜改行＞#弁護士あるある

ツイート：fukazawas（深澤諭史）：2016/02/06 09:50： https://twitter.com/fukazawas/status/695771409138601984 ：
引用→　 １．「期限内に返事しないと提訴します。」という。＜改行＞２．返事がない。＜改行＞３．提訴する。＜改行＞４．「なんでいきなり訴えるんだ！？」と怒られる（笑）＜改行＞#弁護士あるある

ツイート：fukazawas（深澤諭史）：2015/10/13 10:19： https://twitter.com/fukazawas/status/653741855281057792 ：
引用→　 「Ａ弁護士は甲といっていた。Ｂ弁護士は乙と，Ｃ弁護士は丙といっていた。」＜改行＞「だから，この事件は，甲乙丙だから，私の請求は全部認められるべきだ」＜改行＞＜改行＞#弁護士あるある

ツイート：fukazawas（深澤諭史）：2015/10/12 09:42： https://twitter.com/fukazawas/status/653370023273086976 ：
引用→　 すぐに手を打たないと取り返しの付かないことになる人に限って，音信不通になったりしてどうしようもなくなる。＜改行＞＜改行＞#弁護士あるある

ツイート：fukazawas（深澤諭史）：2015/07/30 12:57： https://twitter.com/fukazawas/status/626602602709454848 ：
引用→　 「相談するだけでお金がかかるんですか？！」＜改行＞＜改行＞初対面の見ず知らずの人に，話し始めて数分で，自分の仕事の価値の大部分を否定されるお仕事・・・。＜改行＞＜改行＞#弁護士あるある

ツイート：fukazawas（深澤諭史）：2015/04/17 07:33： https://twitter.com/fukazawas/status/588832499502944257 ：
引用→　 「着手金を払いたくない，成功報酬は高くてもいいから，完全成功報酬で」＜改行＞といわれて，その通りにして，いざ，事件が終結すると＜改行＞「もともとは自分のお金なのに，成功報酬をそんなに取られるのは納得いかない」といわれる。＜改行＞＜改行＞#弁護士あるある

ツイート：fukazawas（深澤諭史）：2015/04/12 11:10： https://twitter.com/fukazawas/status/587075282655322112 ：
引用→　 ＞ＲＴ＜改行＞１．ネットに●●と書いてありました！＜改行＞２．だから●●したんですが、上手くいきませんでした！＜改行＞３．（もう取り返しがつかない状態ですが）●●をして下さい！＜改行＞４．どうして出来ないんですか！ネットには●●って書いてあったのに！＜改行＞#弁護士あるある

ツイート：fukazawas（深澤諭史）：2015/03/21 10:21： https://twitter.com/fukazawas/status/579090467297435648 ：
引用→　 「絶対勝てるんで着手金なしで！」＜改行＞（断られると）「泣き寝入りしろっていうんですか！」＜改行＞＜改行＞といわれることがあるが，絶対勝てるとはいえないし，多分，泣き寝入りするのは受任した弁護士。＜改行＞＜改行＞#弁護士あるある

ツイート：fukazawas（深澤諭史）：2014/09/23 13:36： https://twitter.com/fukazawas/status/514271999057596416 ：
引用→　 「難しい決断しないといけないとき」と「不都合な事実が明らかになったとき」には，連絡先のパソコンや携帯は故障したり，風邪を引いて寝込んだりする。＜改行＞＜改行＞#弁護士あるある

　上記のハッシュタグでは、深澤諭史弁護士らしさが際立ったツイートというのは見当たらず、控えめにとどめているようにも感じました。もう少しきちんと調べる必要を感じました。

[6565]  % find . /home/a66/kk_hirono/ -name '*あるある*.jpg'  -type f -printf '%f\n'
2014-06-20-022955_報酬の払いの悪い人ほど細かい要求が多く進捗も急かしてくる　＃弁護士あるある.jpg
2016-06-08-012129_深澤諭史@fukazawas　深澤諭史さんが弁護士野田隼人を　あるあるすぎて困る.jpg
2016-06-08-140304_深澤諭史　@fukazawas　　11分11分前＞RTいわれてみれば，あるある過ぎるね。.jpg
2016-03-18-003626_あるある。ほんとにあるあるある。.jpg
2016-03-13-202048_あるあるすぎてこまる。.jpg
2016-05-06-163322_深澤諭史　@fukazawas　　5時間5時間前＞ＲＴあるあるある（・∀・）.jpg
2016-04-21-121239_深澤諭史さんはTwitterを使っています：　”https：／／t。co／NCLZeQp8fM　あるあるある。　そういう思いこみをする人だか.jpg
2016-07-06-135221_深澤諭史　@fukazawas　　3時間3時間前＞ＲＴあるある過ぎて怖い（・∀・；）.jpg
2016-08-11-001208_深澤諭史　@fukazawas　　6時間6時間前深澤諭史さんがオタ弁さんをリツイートしましたあるあるある.jpg
2016-09-03-145755_深澤諭史　@fukazawas　　4時間4時間前＞ＲＴあるあるすぎてあれ.jpg
2014-06-20-022955_報酬の払いの悪い人ほど細かい要求が多く進捗も急かしてくる　＃弁護士あるある.jpg

　いざ調べてみると思ったより数は多くなく、思ったよりひどい内容のものもなかったのですが、これはと思うものを一つ発見することが出来ました。スクリーンショットは次のTwilogにあります。

非常上告-最高検察庁御中_ツイッター(@s_hirono)/「2016-03-18-003626_あるある。ほんとにあるあるある」の検索結果 - Twilog http://bit.ly/2ciLnEs

　次のようにデータベースからツイートの内容を探し出しました。

[6558]  % tw_user_tweet-sql-search-make-text-html-blogger-style.rb  --full_sql_text="SELECT * FROM tw_user_tweet WHERE tw_date BETWEEN '2000-07-22 20:14' AND '3300-07-24 23:59' AND (tweet LIKE \"%被告人段階から%\") ORDER BY tw_date ASC"
％ora3298（やぎ）のツイート％投稿日時％2016-03-17 16:47:00％ツイートのURL％ https://twitter.com/ora3298/status/710372036959272961 ％
％引用％ 被告人段階からついた事件だったが、こんな事件被疑者からついてたらそこで潰せたのに

＞fukazawas（深澤諭史）のリツイート＞このリツイートの日時＞2016-03-17 16:48:00＞ URL＞ https://twitter.com/fukazawas/status/710372244791255040 ＞
＞fukazawas（深澤諭史）がリツイートしたora3298（やぎ）のツイートの内容＞
＞引用＞ 被告人段階からついた事件だったが、こんな事件被疑者からついてたらそこで潰せたのに

　時刻は9月8日7時33分です。昨日は丸一日中断をしていたと思います。一昨日に大きなニュースが舞い込んできたので、様子見と頭の整理も必要になりました。これまでの弁護士に対する認識を根底から揺さぶるほどの衝撃があり、社会に向けた挑戦とも受け止めました。

　中断前に「ora3298（やぎ）」というTwitterアカウントが深澤諭史弁護士のリツイートとから出てきましたが、「被告人段階からついた事件だったが、こんな事件被疑者からついてたらそこで潰せたのに」という内容のツイートです。

　今年の3月17日の時点でデータベースに登録している元のツイートなので、その後になりそうですが、この弁護士の可能性の高いアカウントはTwitterを非公開設定にしました。

　先日、このora3298というユーザ名が、私に関係したツイートに含まれていることに気が付き、久しぶりに思い出していた弁護士アカウントでもありました。

ツイート：uwaaaa（サイ太）：2016/08/31 17:18： https://twitter.com/uwaaaa/status/770898506588360704 ：
引用→　 @nanunoo @ora3298 コレ，ほぼ毎日来てますよ。スパム報告を何度もしてます

　上記は次のツイートの返信になっています。

ツイート：nanunoo（┌（┌ ＾o＾）┐ぬのォ...）：2016/08/31 17:12： https://twitter.com/nanunoo/status/770897062577643520 ：
引用→　 @ora3298 前にも飛んできたことがあったんですよね。告訴だか「非常上告」だかの資料にされる模様です。ほら鍵を開ければあなたも！

　今、読みなおして気がついたのですが、もともと@nanunooというアカウントが@ora3298 にメンションとして送ったツイートに対して、刑裁サイ太が横から返信ツイートをしていたようです。つまり、やぎ、というアカウントの方が直接の名宛人だったということです。

　刑裁サイ太はそのツイートを見て、たまたま反応したことになりますが、ツイートの内容を見ても私に対してたまりかねた不満があって、それが外部の触発で吹き出したということになりそうです。

　私の記憶ではnanunooというユーザのツイートの中に、やぎ、の＠ユーザ名が含まれていた記憶だったのですが、刑裁サイ太のタイムラインから探したほうが早いと思い探したところ、刑裁サイ太のタイムラインを遡るだけでずいぶんと時間が掛かりました。

　刑裁サイ太や、やぎ、についてはまた別のところで取り上げたいと思います。なお、翌朝に確認したところ、私の３つのTwitterアカウントはすべて刑裁サイ太にブロックされていました。スクリーンショットも作成しています。

　仲間内に向け、私のアカウントに対するスパム報告を促し、煽ったとも考えられる刑裁サイ太の反応です。

ツイート：s_hirono（非常上告-最高検察庁御中_ツイッター）：2016/03/18 00:36： https://twitter.com/s_hirono/status/710490000136269825 ：
引用→　 2016-03-18-003626_あるある。ほんとにあるあるある。.jpg https://t.co/kaN2EJChVj

　上記のスクリーンショットが、やぎ、の「 被告人段階からついた事件だったが、こんな事件被疑者からついてたらそこで潰せたのに」というツイートに対する深澤諭史弁護士の反応です。

　本当にあるあるなのか疑問が大きいですが、その疑問以上に深澤諭史弁護士の人間性や弁護士としての適格性に疑問を持つのが当然かと思います。元のツイートは、検察や社会に対して挑戦的とも感じさせるものでした。

ツイート：kk_hirono（告発-金沢地方検察庁御中_ツイッター）：2016/09/06 09:24： https://twitter.com/kk_hirono/status/772953556362014721 ：
引用→　 ＞引用＞ 被告人段階からついた事件だったが、こんな事件被疑者からついてたらそこで潰せたのに

　上記が本項目での中断直前のツイートになります。何日前だったのか正確に思い出せなくなっていたのですが、一昨日の6日の午前9時24分となっています。どうもこの中断の数時間後に、私は泉澤章という弁護士の存在をテレビで初めて知ったことになりそうです。

　データーベースで、やぎ、のツイートを調べたら非公開設定にされたにもかかわらず、思いの外沢山のツイートが登録されていて、いくつか眺めているうちに、これは弁護士被害から自分の権利を守るためにも、記録と公開の必要性を感じました。実務的な内容が多いとも感じました。

　データベースの検索結果は、次の３つブログ記事としてまとめました。

参考資料：やぎ（@ora3298）のツイート（228件、 2012-11-30 13:48〜2016-03-23 18:08：2016-09-08の記録）「1-100／228」件,http://hirono2016k.blogspot.com/2016/09/ora3298228-2012-11-30-13482016-03-23.html
参考資料：やぎ（@ora3298）のツイート（228件、 2012-11-30 13:48〜2016-03-23 18:08：2016-09-08の記録）「101-200／228」件,http://hirono2016k.blogspot.com/2016/09/ora3298228-2012-11-30-13482016-03-23_8.html
参考資料：やぎ（@ora3298）のツイート（228件、 2012-11-30 13:48〜2016-03-23 18:08：2016-09-08の記録）「201-228／228」件,http://hirono2016k.blogspot.com/2016/09/ora3298228-2012-11-30-13482016-03-23_4.html

　非公開設定のアカウントのツイートをブログの記事にまとめたのも初めてだったので、どのように表示されているのか確認したところ、リツイートの元のツイートは普通にデザインが適用されて表示されていました。

　開いたのは3つ目のページです。「201-228／228」件のついーとのまとめです。この中に気になるツイートを一つ発見しました。

［ora3298__20160908_0916_205／228のツイート］
％ora3298（やぎ）のツイート％投稿日時％2016-03-03 14:00:00％ツイートのURL％ https://twitter.com/ora3298/status/705256425014964226 ％
％ora3298（やぎ）のツイートの内容％
#％引用％ ああ、再審開始はこいつの関係か https://t.co/d8sskvLy04
％データベースへの登録日時％2016-03-05 11:09:22％

　「こいつの関係」が何を意味するのかわかりませんが、指し示すように引用されているのは次のページです。見覚えのあるページで、見覚えのある写真がサイドバーにありました。

　その前にちょっと訂正ですが、か https://t.co/d8sskvLy04 のリンクは、ブログへのリンクではなく、次のツイートへのリンクで、そのツイートにgooのブログのURLがあって、そのブログ記事のサムネイル画像付きのリンクが、やぎ、のリツイートに表示されていました。

ツイート：raymiyatake（宮武嶺）：2016/03/03 19:22： https://twitter.com/raymiyatake/status/705337447828160512 ：
引用→　 「やる気にさせます！」北海道警がおとり捜査で有罪判決を取ったが、札幌地裁が違法性認め再審決定。 https://t.co/i7U9siw7Rj @raymiyatakeさんから https://t.co/a5QUE79cdN

／＊＊＊＊＊＊＊＊＊＊（引用開始）＊＊＊＊＊＊＊＊＊＊
引用URL＞＞＞＞：http://blog.goo.ne.jp/raymiyatake/e/bedc66a035921169a6e379f078ba4e18 「やる気にさせます！」北海道警がおとり捜査で有罪判決を取ったが、札幌地裁が違法性認め再審決定。 - Everyone says I love you !

恐ろしいのは、このおとり捜査が、担当していた元警部が覚せい剤取締法違反で検挙されたことをきっかけに「自白」したからわかったことで、本来であれば闇に葬られていてもおかしくなかったということです。

　私たちは、「犯人」が「逮捕」されたというと、完全に捜査機関のことを信じ切ってしまいますし、職業裁判官でさえそういう傾向が著しいため、９９・９％の有罪率が維持されているのですが、やはり、推定無罪が常識とならないといけないことがわかります。

　特に市民が刑事訴訟に参加する裁判員制度を続けていくなら、裁判員もこの推定無罪を必ず頭に叩き込んでから裁判を始めるということが絶対に必要です。

　また、私たちも捜査機関がマスコミに垂れ流す情報を疑ってかかる必要があります。

＊＊＊＊＊＊＊＊＊＊（引用終了）＊＊＊＊＊＊＊＊＊＊／

　ブログ記事の内容を一部引用しました。ブログ内の写真とTwitterのアカウントのプロフィールの写真は同じものでした。ずいぶん久しぶりに見たような気がしましたが、これまでに何度か目にしてきた弁護士アカウントで、たぶんブックマークもしていなかったと思います。

＜2016年09月08日(木) 09時57分16秒にTwitterAPIで取得したraymiyatake（宮武嶺）のプロフィール情報＞
弁護士。元ロースクール教授。護憲・平和。脱原発 。反貧困・差別・TPP。 BLOGOSブロガー。池田信夫氏と百田尚樹氏にはブロックされてます（笑）。ブログ Everyone says I love you！はおかげさまで3000万アクセスを超えました。

　モトケンこと矢部善朗弁護士（京都弁護士会）のプロフィールと似たようなところがあると思いました。

＜2016年09月08日(木) 09時58分42秒にTwitterAPIで取得したmotoken_tw（モトケン）のプロフィール情報＞
矢部善朗。元検事の弁護士（京都弁護士会）です。H２５．３までLSの教員もしてました。
アイコン（作者は Y_Coronaさん）は単なる趣味(^^;
ツイッターがまともな議論の場になりますように。
ブログ http://t.co/ArcLkPtRxr
FaceBookアカウントは、Yoshirou Yabe

　モトケンこと矢部善朗弁護士（京都弁護士会）のプロフィールは、ご丁寧に改行が入れてあるようです。「矢部善朗。元検事の弁護士（京都弁護士会）です。H２５．３までLSの教員もしてました。」という部分が似ていると思いました。

　ついでにご紹介しておいた意味が大きいのですが、北海道警のおとり捜査で再審決定となった事件は、私の非常上告との関係で法律的な関係性が大きいと考えていました。ここでは簡単なご紹介にしておきますが、実体法ではなく手続法の瑕疵で、再審を認めた画期性があるとのことです。

　項目の本旨から外れだしたのは、再掲する次のツイートの内容が大きく、その補足説明や周辺の状況との関連性のご紹介に紙面を費やしました。

ツイート：nanunoo（┌（┌ ＾o＾）┐ぬのォ...）：2016/08/31 17:12： https://twitter.com/nanunoo/status/770897062577643520 ：
引用→　 @ora3298 前にも飛んできたことがあったんですよね。告訴だか「非常上告」だかの資料にされる模様です。ほら鍵を開ければあなたも！

　これに似たようなことは、他にも経験していました。これもいずれ取り上げる予定でいましたが、ここでは告知の予告編としてご紹介をしておきたいと思います。

ツイート：un_co_the2nd（うのじ）：2016/05/29 22:23： https://twitter.com/un_co_the2nd/status/736910730495025152 ：
引用→　 @nan5o あんな****気にしないっす。モノホンのp庁の調査も知らねえでなにやってんだか…

　どうももう一つのツイートは削除されていたようです。データベースのデータになりますが、次の内容になります。

％un_co_the2nd（うの字）のツイート％投稿日時％2016-05-29 22:20:00％ツイートのURL％ https://twitter.com/un_co_the2nd/status/736910031799484417 ％
％引用％ 敢えてブロッコしないけど、金澤p庁御中うっとおしいわ…p庁がそんなもんに目をかけると思ってんのか

　自分のデーターベースから探し出すことが出来ましたが、ネット上の検索だとかなり難しかったと思います。あえて検索しづらくするために「金澤p庁御中」などと金沢地方検察庁御中であることに細工を施していたようです。これも別の弁護士アカウントが一つ絡んでいたことを思い出しました。

　調査要請を交えた参考資料として、これもブログの記事としてまとめておきます。

参考資料：うのじ（@un_co_the2nd）のツイート（296件、 2016-01-08 15:46〜2016-09-08 10:12：2016-09-08の記録）「1-100／296」件,http://hirono2016k.blogspot.com/2016/09/uncothe2nd296-2016-01-08-15462016-09-08.html
参考資料：うのじ（@un_co_the2nd）のツイート（296件、 2016-01-08 15:46〜2016-09-08 10:12：2016-09-08の記録）「101-200／296」件,http://hirono2016k.blogspot.com/2016/09/uncothe2nd296-2016-01-08-15462016-09-08_8.html
参考資料：うのじ（@un_co_the2nd）のツイート（296件、 2016-01-08 15:46〜2016-09-08 10:12：2016-09-08の記録）「201-296／296」件,http://hirono2016k.blogspot.com/2016/09/uncothe2nd296-2016-01-08-15462016-09-08_3.html

　ブログの記事としてまとめる前に、そういえば長い間、うの字のタイムラインを開いていなかったので、タイムラインを遡りながら追加の登録をしていたのですが、8月31日のツイートの辺りで過去のツイートの読み込みができなくなりました。

　タイムラインの読み込みが止まったのははじめての経験です。あるいはJavaScriptのエラーだったのかもしれませんが、TwitterAPIでも3200件辺りまでは読み込める仕様になっているはずです。

　忘れかけていたのですが、うの字の前の、やぎ、のツイートでは、次のスクリーンショットがあって、ツイートの内容の一部から検索をしたのですが、一致するものはなく、データーベースの登録はないようでした。

ツイート：s_hirono（非常上告-最高検察庁御中_ツイッター）：2015/07/18 21:30： https://twitter.com/s_hirono/status/622382833152061442 ：
引用→　 2015-07-18-213000_@ora3298　あなたが弁護士やっているわけですか？.jpg http://t.co/pm8lYgNjmJ

　上記のスクリーンショットは、私の、やぎ、に対する返信が投稿されたことを記録したスクリーンショットになっています。私が返信を送ったツイートの内容は次のとおりになっています。誤字脱字のないように気をつけて掲載します。

（2015年7月15日１４：００の、やぎ、のツイートの内容）→　警察から、「そういうのは弁護士さんに相談したらどうか、と言われたから来たのにここでもダメってどういうことですか」と言われてもな。最初から病院誘導しとこうぜ、頼むわ

　うの字のツイートのスクリーンショットも掲載しておこうと思ったのですが、これもすんなりとは見つけることが出来ませんでした。日付の情報があったので、そこから次のようにTwilogで調べました。

非常上告-最高検察庁御中_ツイッター(@s_hirono)/2016年05月 - Twilog http://twilog.org/s_hirono/month-1605

ツイート：s_hirono（非常上告-最高検察庁御中_ツイッター）：2016/05/30 09:03： https://twitter.com/s_hirono/status/737071988015960064 ：
引用→　 2016-05-30-090346_うの字@un_co_the2nd@nan5o　奴が捕捉した気になってるツイートを見るにつけセンスがない.jpg https://t.co/P1a2eQt6F2

　類友性の問題もあるので、うの字と絡んでいた弁護士らしきアカウントのツイートもブログの記事としてまとめる作業に入りましたが、次のツイートで読み込み中のマークが出たまま、先に進まなくなっています。

ツイート：nan5o（でゅーく(●―●)まんGO）：2016/09/06 09:39： https://twitter.com/nan5o/status/772957348579069952 ：
引用→　 いい歳したおっさんが発表の掲示板から立ち去りつつ大泣きしてからが司法試験の本番が始まると思ってた

　時刻は13時58分になっています。過去のツイートは全て消去されていたようです。パソコンの調子が悪くなっているのかとも思い再起動もやっていました。

　2016/09/06 09:39より前のツイートが全て削除されたと思われますが、過去のものはデータベースに登録されているので、これからまとめを作成します。

　うの字との会話の流れで、私に関連していると思われるのは次の２つのツイートです。

［nan5o__20160908_1401_13／40のツイート］
％nan5o（でゅーく(●―●)まんごう）のツイート％投稿日時％2016-05-29 22:21:00％ツイートのURL％ https://twitter.com/nan5o/status/736910236166946816 ％
％nan5o（でゅーく(●―●)まんごう）のツイートの内容％
#％引用％ @un_co_the2nd 二つほど速攻でブロックしてます(-_-)
％データベースへの登録日時％2016-05-30 09:38:38％

［nan5o__20160908_1401_14／40のツイート］
％nan5o（でゅーく(●―●)まんごう）のツイート％投稿日時％2016-05-29 22:23:00％ツイートのURL％ https://twitter.com/nan5o/status/736910879787126784 ％
％nan5o（でゅーく(●―●)まんごう）のツイートの内容％
#％引用％ @un_co_the2nd TLに流しても人生の無駄使い
％データベースへの登録日時％2016-05-30 09:38:30％

　再掲になりますが、次が実際のツイートのスクリーンショットです。関連ツイートとして表示されています。

ツイート：s_hirono（非常上告-最高検察庁御中_ツイッター）：2016/05/30 09:03： https://twitter.com/s_hirono/status/737071988015960064 ：
引用→　 2016-05-30-090346_うの字@un_co_the2nd@nan5o　奴が捕捉した気になってるツイートを見るにつけセンスがない.jpg https://t.co/P1a2eQt6F2

　他に取り上げたいことは沢山ありすぎて、とても追いつけないぐらいなのですが、この項目の締めくくりにふさわしい、深澤諭史弁護士のツイートを掲載します。本人のツイートの前に、他の弁護士のリツイートで見ていました。スクリーンショットもつけておきます。

ツイート：fukazawas（深澤諭史）：2016/09/08 00:04： https://twitter.com/fukazawas/status/773537418263736320 ：
引用→　 弁護士「事件の見通しは●●です。費用は●●です」＜改行＞相談者「自分でやってみます。」＜改行＞（その後）＜改行＞相談者「上手くいかなかったので、依頼したい。」＜改行＞弁護士「現状の見通しは●●（さっきより悪い）です。費用は●●（さっきより高い）です。」＜改行＞相談者「何故自分で半分やったのにそうなるんだ！？」

投稿者：s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2016-09-08 12:27  ツイート： https://twitter.com/s_hirono/status/773724456795549696
2016-09-08-122735_弁護士あだちけいた㌠シン･ゴジラはいいぞさんがリツイート￼深澤諭史　@fukazawas　　12時間12時間前弁護士「事件の見通しは●●で.jpg https://t.co/n8csIigjmz

投稿者：s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2016-09-08 13:55  ツイート： https://twitter.com/s_hirono/status/773746439251857408
2016-09-08-135456_深澤諭史さんがリツイート￼深澤諭史　@fukazawas　　14時間14時間前弁護士「事件の見通しは●●です。費用は●●です」相談者「自分.jpg https://t.co/vBQLzoMVDF

　このツイートは特別な意味があると考えるので、現時点で64となっているリツイートのうち、情報が取得できた範囲で、弁護士と思われるリツイートのスクリーンショットも、そのアカウントのタイムラインとともに記録しておきたいと思います。

投稿者：s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2016-09-08 14:44  ツイート： https://twitter.com/s_hirono/status/773758937229209600
2016-09-08-144436_シリウスＡさんがリツイート￼深澤諭史　@fukazawas　　15時間15時間前弁護士「事件の見通しは●●です。費用は●●です」相談者「自.jpg https://t.co/ZDQOWUKNOb

投稿者：s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2016-09-08 14:44  ツイート： https://twitter.com/s_hirono/status/773758821097361409
2016-09-08-144408_シリウスＡさんがリツイート￼TORU　OKUMURA　@okumuraosaka　　5時間5時間前弁護団は７日、足利事件弁護団の一員だった.jpg https://t.co/f6KU7K8jvK

投稿者：s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2016-09-08 14:43  ツイート： https://twitter.com/s_hirono/status/773758553517531138
2016-09-08-144304_シリウスＡ（@eeyy888777）さん　｜　Twitter.jpg https://t.co/OcfrSJFyWW

投稿者：s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2016-09-08 14:39  ツイート： https://twitter.com/s_hirono/status/773757519499960320
2016-09-08-143858_浜ちゃんさんがリツイート￼深澤諭史　@fukazawas　　15時間15時間前弁護士「事件の見通しは●●です。費用は●●です」相談者「自分.jpg https://t.co/ESaimbQfOo

投稿者：s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2016-09-08 14:38  ツイート： https://twitter.com/s_hirono/status/773757385869447169
2016-09-08-143826_浜ちゃん（@satoshihamada）さん　｜　Twitter.jpg https://t.co/ZOqMe954xN

投稿者：s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2016-09-08 14:37  ツイート： https://twitter.com/s_hirono/status/773757205451386880
2016-09-08-143743_シン・のぐーたん・ガルパンはいいぞ。さんがリツイート￼深澤諭史　@fukazawas　　15時間15時間前弁護士「事件の見通しは●●です。.jpg https://t.co/TCUH2YkAx1

投稿者：s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2016-09-08 14:35  ツイート： https://twitter.com/s_hirono/status/773756620870254592
2016-09-08-143523_シン・のぐーたん・ガルパンはいいぞ。（@tommy_nogtan）さん　｜　Twitter.jpg https://t.co/ejbkTuwTl4

投稿者：s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2016-09-08 14:34  ツイート： https://twitter.com/s_hirono/status/773756421515075584
2016-09-08-143436_くまえもんさんがリツイート￼深澤諭史　@fukazawas　　14時間14時間前弁護士「事件の見通しは●●です。費用は●●です」相談者「自.jpg https://t.co/lBllcwjRpu

投稿者：s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2016-09-08 14:34  ツイート： https://twitter.com/s_hirono/status/773756271337967617
2016-09-08-143400_くまえもん（@kumaemon9）さん　｜　Twitter.jpg https://t.co/7pVPWJiubq

投稿者：s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2016-09-08 14:32  ツイート： https://twitter.com/s_hirono/status/773755846337581056
2016-09-08-143219_ぽぽひと@内閣総辞職ビームさんがリツイート￼深澤諭史　@fukazawas　　14時間14時間前弁護士「事件の見通しは●●です。費用は●●.jpg https://t.co/lM1nFpPnnm

投稿者：s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2016-09-08 14:31  ツイート： https://twitter.com/s_hirono/status/773755609623638016
2016-09-08-143122_ぽぽひと@内閣総辞職ビーム（@popohito）さん　｜　Twitter.jpg https://t.co/FtlUkCtDfQ

投稿者：s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2016-09-08 14:30  ツイート： https://twitter.com/s_hirono/status/773755305180008448
2016-09-08-143010_らめーんさんがリツイート￼深澤諭史　@fukazawas　　14時間14時間前弁護士「事件の見通しは●●です。費用は●●です」相談者「自分.jpg https://t.co/YTQ6AJXogY

投稿者：s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2016-09-08 14:29  ツイート： https://twitter.com/s_hirono/status/773755053626712064
2016-09-08-142910_らめーん（@shouwayoroyoro）さん　｜　Twitter.jpg https://t.co/xqr2yX2M0q

投稿者：s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2016-09-08 14:26  ツイート： https://twitter.com/s_hirono/status/773754414548983808
2016-09-08-142637_toujinさんがリツイート￼深澤諭史　@fukazawas　　14時間14時間前弁護士「事件の見通しは●●です。費用は●●です」相談者「.jpg https://t.co/BOamJkUwDL

投稿者：s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2016-09-08 14:26  ツイート： https://twitter.com/s_hirono/status/773754285985103872
2016-09-08-142607_toujin（@tou_jin）さん　｜　Twitter.jpg https://t.co/NVX2VJpng0

　リツイートのリストにありながらタイムラインに、リツイートしたはずの深澤諭史弁護士のツイートが見当たらないアカウントが３つほどありました。リツイートの取り消しかと思いましたが、64の総数は変わらず、更新していると65になっていました。

2016-09-08　木曜日　15：02　＜＜ ［［　←これまでの記述範囲の終了時刻］］＜＜
**** 「あるある系弁護士」と名付けたい、性犯罪を専門にする奥村徹弁護士と深澤諭史弁護士の浅薄性

:CATEGORIES: 深澤諭史弁護士
:TAGS: 深澤諭史弁護士,奥村徹弁護士,性犯罪

2016-09-15　木曜日　12：43　＞＞ ［［　←これからの記述範囲の開始時刻］］＞＞

　記述に取り掛かろうとしたところ、見出し第3レベルの深澤諭史弁護士特集では、前回も「あるある＞RT」を見出しに取り上げていたことに気が付きました。ブログの記事として公開済みのものは、次になります。

告訴状の下書き）時間の経過で辿りようもなくなる深澤諭史弁護士の「あるある＞ＲＴ」ツイートに見る弁護士の異常性（狂人性？）と欺瞞性,http://hirono2016k.blogspot.com/2016/09/blog-post_61.html

　4,5日前になるかと思いますが、まる一日ぐらい深澤諭史弁護士のタイムラインの更新が僅かにしかないことがありました。何か心境の変化があったのか、とも、この時も考えましたが、再開された深澤諭史弁護士のツイートの内容は、以前にもまして強力なパワーを感じさせるものとなっていました。

　これまで深澤諭史弁護士に関しては「弁護士深沢まつり」というインスピレーションによる表現を使ってきましたが、パワーアップされたツイートを見た時、次に頭に浮かんできたのは、「弁護士狂人深澤モード」という表現です。

　深澤諭史弁護士は以前、「私が通りますよ」というようなツイートもやっていましたが、まさに社会常識を無視した暴走モードです。また、最近になってアイコンにシンゴジラを模したものを使うようになりましたが、彼の価値観が社会に向けて不満の火を吹く様が重なって見えました。

　「シンゴジラ」と「君の名は」という映画は、現在上映中の大ヒット作品のようですが、「君の名は」はテレビの情報番組で紹介されているのを見ているものの、シンゴジラの方は、ツイッターのタイムラインでのみ見かける断片的な情報です。それでも一部の弁護士には受けが良いようです。

　足立啓太という北海道の弁護士は、Twitterのプロフィールの名前に、シンゴジラの絶賛的な評価を加えています。

2016年09月15日(木) 13時02分36秒にTwitterAPIで取得したkeita_adachi（弁護士あだちけいた㌠シン･ゴジラはいいぞ）のプロフィール情報＞
北海道の弁護士です。農家や農作物関係（含む競走馬・牛）の事件を複数取り扱っています。【主な経歴】名古屋出身。早稲田政経・家電・ラーメン・焼肉。社台。一口・馬主。オルフェーヴルなど出資。競馬・GAME・グルメ・アニメネタが多いのは仕事の話がしにくいからです。【写真は東京優駿2011@JRAカレンダー】

　次の漫画家弁護士も同じようなことをやっていました。名前の方が今開いて気がついたところですが、アイコンの方を深澤諭史弁護士と同じようにシンゴジラを模したものとしていました。

＜2016年09月15日(木) 13時05分27秒にTwitterAPIで取得したRedips00（赤ネコ＠シンゴジラかわいい）のプロフィール情報＞
赤ネコ法律事務所弁護士漫画家。『司法修習QUEST』http://t.co/pkQmt4m3SH『萌え憲法』http://t.co/mpipSbZARG『法律擬人化』『法窓夜話』各種電子書籍ｽﾄｱ。予備陸１尉。LINEスタンプhttps://t.co/z859YrOEIO https://t.co/79WL5Mlxj7

　次がスクリーンショットになります。

投稿者：s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2016-09-15 13:10  ツイート： https://twitter.com/s_hirono/status/776271921428115459
2016-09-15-131017_赤ネコ＠シンゴジラかわいい（@Redips00）さん　｜　Twitterからの返信付きツイート.jpg https://t.co/rDkfJ9quss

投稿者：s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2016-09-15 13:09  ツイート： https://twitter.com/s_hirono/status/776271686060519424
2016-09-15-130921_弁護士あだちけいた㌠シン･ゴジラはいいぞ（@keita_adachi）さん　｜　Twitterからの返信付きツイート.jpg https://t.co/t0wdjG1fqc

　本日見かけた、深澤諭史弁護士による奥村徹弁護士のツイートのリツイートは、次の２つになります。またか、というような内容のものですが、なぜか斬新に思えました。高畑裕太氏の示談・釈放のことがあっただけに、私の方で弁護士業界の闇の部分から新天地が開けたように感じたのかと思います。

リツイート：fukazawas（深澤諭史）＞2016/09/15 10:02／2016/09/15 08:34＞ https://twitter.com/fukazawas/status/776224574643974144 ＞
 okumuraosaka （TORU OKUMURA）＞ https://twitter.com/okumuraosaka/status/776202410523897856 ＞
引用＞　 刑事事件の被疑者になって困ってるんだからただで弁護しろという電話とメールが数件きた 

リツイート：fukazawas（深澤諭史）＞2016/09/15 10:02／2016/09/15 09:37＞ https://twitter.com/fukazawas/status/776224599654604800 ＞
 okumuraosaka （TORU OKUMURA）＞ https://twitter.com/okumuraosaka/status/776218337256714240 ＞
引用＞　 「いま逮捕勾留されている被疑者について　釈放されたら分割で３０万円払う」みたいな話で、「奥村が受けないのなら　他の弁護士を紹介してください」という展開になっていきた。だれの名前を挙げようかな＜改行＞ https://t.co/D2mHisAitA 

　性犯罪に関しては、都市伝説や神話のような話が昔からあって、多くの人がそれに刷り込まれた部分があるように考えます。日常ではない問題であるだけに時には自覚のないままになんとなく思い込んでいる部分が大きいということで、宗教的な伝道師の布教活動に近いものを感じます。

　私は、実際の性犯罪の裁判がどういうものであったか経験していることもあるので、一面的で独善的なご都合主義が蔓延しているように見えています。時に加害者のためとか、被害者の立場を尊重という言葉を耳にしますが、弁護士の手抜きと利益の追求が、性犯罪を画一的な集金装置にしていると考えます。

　どの番組だったか忘れましたが、チャンネルを変えながら見ていた朝の情報番組で、「ニセ僧侶」なるものを取り上げていました。主に観光地での外国人相手の行為とのことで、組織的な背景がうかがえるものの中国から世界に向けたものとして番組で紹介されていました。

　日本の性犯罪に歴史があるとすれば、奥村徹弁護士は正統な性犯罪における刑事弁護の実践者であって、そこには、「慈悲や施し」という宗教的な要素も強く感じさせるものであり、深澤諭史弁護士がリツイートをした上掲のツイートには、その思想的な哲学がよく現れているように思いました。

　なかにはそういう犯罪者もいるのかと思いますが、福井刑務所と金沢刑務所で服役をした経験を考慮にしても、そういうタイプはごく少数だと思いますし、そういう点でも、犯罪者の社会的評価を不当に貶め、社会の人の踏み込んだ理解から弁護士が遠ざけていると感じます。

　時刻は9月20日14時41分になっています。記述の内容は次のツイートからの再開になります。5日ぶりの再開ということになりそうです。

ツイート：kk_hirono（告発-金沢地方検察庁御中_ツイッター）：2016/09/15 14:19： https://twitter.com/kk_hirono/status/776289370009509888 ：
引用→　 なかにはそういう犯罪者もいるのかと思いますが、福井刑務所と金沢刑務所で服役をした経験を考慮にしても、そういうタイプはごく少数だと思いますし、そういう点でも、犯罪者の社会的評価を不当に貶め、社会の人の踏み込んだ理解から弁護士が遠ざけていると感じます。

　ここ数日、モトケンこと矢部善朗弁護士（京都弁護士会）、小倉秀夫弁護士、深澤諭史弁護士ともにツイートの数が増加傾向にあり、内容的にも自由で活発なものとなっているという印象があります。

　気になる内容のものをいちいち取り上げていてもきりがないのですが、特にこれはというものがあったので、のちほどそれを取り上げ、問題性について言及をしたいと予定します。その前に、既にデータを取得してある深澤諭史弁護士の５つのツイートを独立した項目として取り上げておきます。

2016-09-20　火曜日　14：48　＜＜ ［［　←これまでの記述範囲の終了時刻］］＜＜
**** 「弁護士狂人深澤モード      」という着想に至った深澤諭史弁護士（@fukazawas）の５つのツイート（2016年9月13日のもの）

:CATEGORIES: 深澤諭史弁護士
:TAGS: 深澤諭史弁護士,医療問題

2016-09-20　火曜日　14：56　＞＞ ［［　←これからの記述範囲の開始時刻］］＞＞

　次の5つのツイートは中断前の9月14日ぐらいにTwitterAPIでデータを取得していたものです。

ツイート：fukazawas（深澤諭史）：2016/09/13 12:47： https://twitter.com/fukazawas/status/775541283116896256 ：
引用→　 某医師のブログ「医療テラスで稼ぐ方法。癌はⅢ期になるまで放置してから手術すること，かならず合併症・術後感染は一つはさせること，そうしないと赤字になるのできをつけましょう＾＾」＜改行＞#もし医療で平成の司法改革をやったら

ツイート：fukazawas（深澤諭史）：2016/09/13 12:44： https://twitter.com/fukazawas/status/775540735370141696 ：
引用→　 医師「この手術は時間がかかるな，たくさん麻酔しないと」＜改行＞医療テラス「一定時間以上の麻酔には代金払いません」＜改行＞医師Ａ「自腹を切るか・・。」＜改行＞医師Ｂ「じゃあやめた！」＜改行＞患者「あｚうぇｓｘｇｙｔんふじこｌｐ；＠」＜改行＞#もし医療で平成の司法改革をやったら

ツイート：fukazawas（深澤諭史）：2016/09/13 12:42： https://twitter.com/fukazawas/status/775540241495040000 ：
引用→　 盲腸の手術をやるのでくじ引きで選ばれた医療員が執刀に参加＜改行＞医療員「うーん，間違ったかな？」＜改行＞#もし医療で平成の司法改革をやったら

ツイート：fukazawas（深澤諭史）：2016/09/13 12:42： https://twitter.com/fukazawas/status/775540085076832256 ：
引用→　 医師「風邪の人を診察して，お薬を処方して，完治させました！」＜改行＞医療テラス「風邪なんか治療しなくても治るでしょ？あなたの成果じゃないので，診療報酬は０円です。」＜改行＞#もし医療で平成の司法改革をやったら

リツイート：fukazawas（深澤諭史）＞2016/09/13 12:38／2016/09/12 23:31＞ https://twitter.com/fukazawas/status/775539006394159105 ＞
 take___five （take-five）＞ https://twitter.com/take___five/status/775341039582183424 ＞
引用＞　 法テラスの報酬基準の不合理性が話題だけど、民事じゃないが、自分が一番頭に来たのは、勾留4日目で検事自ら釈放させた事案で「釈放の結果が弁護人の活動の成果か不明だから加算なし」と言われたとき。＜改行＞弁護人が何もしなくても勾留4日目で釈放する検事がいたら教えて欲しいわ。相当特殊でしょ。 

　小倉秀夫弁護士も以前、刑事事件の国選弁護を医療保険と同じく国の経費による社会保障とすべき、といった趣旨のツイートをしていましたが、法律問題と医療問題を同列に置き、弁護士としての権威や有用性を社会に認知させようという傾向性が、深澤諭史弁護士にも強くうかがえます。

　似たようなツイートはこれまでにも何度か見てきましたが、弁護士を信頼し、厚遇とともに重用しないことによる  害悪の告知をより鮮明にした内容と感じました。時節柄ということもあるのですが、この時節柄ということを強く意識させるのが、俳優高畑裕太氏の強姦致傷事件、 不起訴釈放の件です。

　法律問題をこじらせることで、利益を貪るという弁護士の態度、姿勢は、本件の被告訴人である弁護士らに共通してみられる構成要素であり、人格、見当識という点においても極めて異常な有害性をうかがわせるものです。深澤諭史弁護士の場合、無邪気で正直にも見えるのですが、強い共通性を感じます。

　独立した項目として予定しているのは、次の深澤諭史弁護士のツイートのモトケンこと矢部善朗弁護士（京都弁護士会）のリツイートです。これはリツイートとして初めて気がついたツイートで、深澤諭史弁護士のタイムラインでは見落としていたようです。

リツイート：motoken_tw（モトケン）＞2016/09/20 10:48／2016/09/20 10:41＞ https://twitter.com/motoken_tw/status/778048266445271040 ＞
 fukazawas （深澤諭史）＞ https://twitter.com/fukazawas/status/778046303464927232 ＞
引用＞　 法律問題で，自分でやってみて，上手くいかなかったらその後で頼もう，というのは，＜改行＞「温泉卵を作ろうとしたら，ゆで卵になっちゃったから，コックに頼んで，そのゆで卵を温泉卵にしてもらおう」＜改行＞というくらいの発想。 

ツイート：fukazawas（深澤諭史）：2016/09/20 10:41： https://twitter.com/fukazawas/status/778046303464927232 ：
引用→　 法律問題で，自分でやってみて，上手くいかなかったらその後で頼もう，というのは，＜改行＞「温泉卵を作ろうとしたら，ゆで卵になっちゃったから，コックに頼んで，そのゆで卵を温泉卵にしてもらおう」＜改行＞というくらいの発想。

　別々にデータを取得すると、9月20日10時41分の深澤諭史弁護士のツイートを、モトケンこと矢部善朗弁護士（京都弁護士会）が7分後の10時48分にリツイートしていたことがわかりました。

　書いているうちに気がついたのですが、「2016/09/20 10:48／2016/09/20 10:41」というかたちで、リツイートの時刻と元のツイートの時刻を併記していたことに気が付きました。自分でそのように作ったのですが、しばらくしてからすっかり忘れていたようです。

　たまたま卵のことが書いてありますが、今日の昼頃、卵のことで大きな発見がありました。結論をいつと卵は冷凍保存が出来、普通の卵とは違った美味しさがあるという話を初めて知ったことです。

　きっかけは一昨日の18日に賞味期限切れになった卵が冷蔵庫にあって、どうしたものかと調べたところ冷凍保存のことが同じ検索で見つけたページに書いてありました。

　賞味期限切れの卵のことは、2ヶ月ほど前になりますか、NHKの「ためしてガッテン」という番組で詳しい話を見聞きしていたのですが、実際に食べるとなると抵抗がありました。

　生食できるのが賞味期限という話は、羽咋市の鋳物工場で一緒に仕事をしていた七尾の人に聞いたのが初めてでしたが、それでも抵抗がありました。

　とにかく卵が冷凍保存できるという話は、今日になって初めてしったことであり、今まで知らずにいたことがとても不思議でした。それとともに、常に驚きのツイートを繰り返してくれているのが、深澤諭史弁護士やモトケンこと矢部善朗弁護士（京都弁護士会）であって、その奥深さは果てしない、と。

　卵を例にしたモトケンこと矢部善朗弁護士（京都弁護士会）がリツイートをした深澤諭史弁護士のツイートは、法律のプロ、専門家としての弁護士のありがたみ、有効性を強く訴えかけるものですが、次に取り上げる高畑裕太氏の問題では、初めと終わりに矢部善朗弁護士の疑問のツイートがありました。

2016-09-20　火曜日　16：00　＜＜ ［［　←これまでの記述範囲の終了時刻］］＜＜
**** 「こんなことが横行していて、しかもおとがめ無しなのに、」という高畑裕太氏の強姦致傷事件に関連した深澤諭史弁護士のツイート

:CATEGORIES: 深澤諭史弁護士
:TAGS: 深澤諭史弁護士,高畑裕太氏の強姦致傷示談釈放事件,示談交渉,守秘義務,報道

2016-09-21　水曜日　09：53　＞＞ ［［　←これからの記述範囲の開始時刻］］＞＞

ツイート：fukazawas（深澤諭史）：2016/09/20 18:10： https://twitter.com/fukazawas/status/778159315010121729 ：
引用→　 こんなことが横行していて、しかもおとがめ無しなのに、生まれてこの方、一度も罪証隠滅も逃亡もしたことの無い被疑者の勾留を安易に認めるなよって話ですな。＜改行＞（・∀・＃） https://t.co/5qclM9BWZS

　この項目のメインとして取り上げる上記の深澤諭史弁護士のツイートは、次のツイートのURLを引用しています。

ツイート：takeshiful（こんたけ㌠）：2016/09/20 18:08： https://twitter.com/takeshiful/status/778159008309977088 ：
引用→　 ＞捜査関係者の証言や捜査資料を元に事件の全容を再現。＜改行＞＜改行＞これ捜査員の守秘義務は一体どうなっているんでしょう。性犯罪で、しかも示談の末に不起訴になった案件なのに…。

　上記の深澤諭史弁護士がツイートでURLを引用した、こんたけ㌠、のツイートは、直前に次の、でゅーく(●―●)まんGO、ツイートをリツイートしており、その言及と思われる内容となっています。

リツイート：takeshiful（こんたけ㌠）＞2016/09/20 18:08／2016/09/20 18:06＞ https://twitter.com/takeshiful/status/778158841460559873 ＞
 nan5o （でゅーく(●―●)まんGO）＞ https://twitter.com/nan5o/status/778158360290070528 ＞
引用＞　 高畑裕太「強姦致傷」事件の示談金は1500万円だった！（週刊文春） - Yahoo!ニュース https://t.co/Lmn7ww9XyA スプリングセンテンスさまからこの取材手法は大いに学ぶべきかもしれないね 

　上記の３つのツイートは一連のつながりのあるセットとして意味のあるものですが、Twitterのタイムライン上では関連性がわかりづらく、意図的にわかりづらく、将来的に関連を辿れないものにしたと考えられます。作為的な陰湿さを感じる弁護士らしい特徴が現れているので、その点も注目です。

　昨夜になりますが、上記の深澤諭史弁護士のツイートを目にした状況を記録したのが次のスクリーンショットになります。いくらか関連のある前後のスクリーンショットもあわせて掲載します。

2016-09-20-114011_いつの間にか，二弁と日弁連の両方の国際委員会に入っていた当職・・・。.jpg https://t.co/2R2DQhgJdo
投稿者：s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2016-09-20 11:40  ツイート： https://twitter.com/s_hirono/status/778061195186089984

2016-09-20-175128_深澤諭史　@fukazawas　2時間2時間前深澤諭史さんが泥濘大魔王サイケをリツイートしました（・∀・）（・∀・）（・∀・）（・∀・）（.jpg https://t.co/qATdKabT1C
投稿者：s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2016-09-20 17:51  ツイート： https://twitter.com/s_hirono/status/778154625467871233

2016-09-20-190456_こんなことが横行していて、しかもおとがめ無しなのに、生まれてこの方、一度も罪証隠滅も逃亡もしたことの無い被疑者の勾留を安易に認めるなよって話.jpg https://t.co/Mkw4Yi3qZq
投稿者：s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2016-09-20 19:05  ツイート： https://twitter.com/s_hirono/status/778173127402676224

2016-09-20-190738_でゅーく（●―●）まんGO　@nan5o　1時間1時間前高畑裕太「強姦致傷」事件の示談金は1500万円だった！（週刊文春）　-　Yahoo.jpg https://t.co/OS6XkhlRYS
投稿者：s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2016-09-20 19:07  ツイート： https://twitter.com/s_hirono/status/778173788135579648

2016-09-20-203255_このページは存在しません。以下の検索ボックスを使ってTwitterを検索できます。ホームに戻る場合はこちら。.jpg https://t.co/jvrNinLa9v
投稿者：s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2016-09-20 20:33  ツイート： https://twitter.com/s_hirono/status/778195249025855488

　「2016-09-20-203255_このページは存在しません」とあるスクリーンショットは、ノース先生とも、きたんせ、とも法クラの間で呼ばれてきたノースライムという弁護士のTwitterアカウントが、削除されていたことを記録したものです。

　ノースライムという弁護士アカウントも、こたんせ、と同じく頻繁にTwitterのプロフィールの名前を変更していましたが、最近のものでは末尾に㌠という特殊記号のようなものをふくめていました。

　こんたけ㌠、というプロフィールの名前を見て思い出し、久しぶりにタイムラインのページを開いたところで削除されていることに気が付きました。㌠をプロフィールの名前に含めたアカウントを見たのはこれが３つ目だと思いましたが、いずれも弁護士らしいもので、法クラという属性が感じられます。

　法クラという言葉は、法律クラスタとも法学クラスタとも見たことがありますが、あまり正確な定義というものはないと思われます。イメージとして法学となれば、大学の法学部の学生や法科大学院の学生なども含まれるような気はします。

　時折、法クラと自称するアカウントも見られますが、特別な仲間意識があるというイメージもあります。私がその代表格と見ているのが、深澤諭史弁護士や、こたんせ、などですが、同じく代表格と目していたノースライムが、早々とTwitterから退場したというのは、一つの変化を感じました。

　法クラ界隈などと表現したほうが、個人的には実態に近い気がするのですが、先日、深澤諭史弁護士が次のアンケートのツイートをやっていて、思いの外、回答者が多かったので、その界隈の同調者や勢力も、思いの外、根深く広い、という発見がありました。

ツイート：fukazawas（深澤諭史）：2016/09/18 11:01： https://twitter.com/fukazawas/status/777326598571778048 ：
引用→　 弁護士・弁護士志望司法修習生向け＜改行＞弁護自治について，これを失うと引換えに月額会費が１万円になるとしたら。

　次が直近の記録としてのスクリーンショットになります。

投稿者：s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2016-09-21 10:24  ツイート： https://twitter.com/s_hirono/status/778404535769313280
2016-09-21-102433_弁護士・弁護士志望司法修習生向け　弁護自治について，これを失うと引換えに月額会費が１万円になるとしたら。.jpg https://t.co/pkhSCWeAj9
　
　48%自治権喪失＋会費月額１万円に賛成、52%自治権維持＋現状会費維持に賛成、というアンケートの集計結果になっています。深澤諭史弁護士はちょくちょくとこのようなアンケートを実施していますが、４択がほとんどで、このような２択というのは初めて見たかもしれません。

　なお、「682票•最終結果」という集計結果になっていて、これまで見てきた深澤諭史弁護士のアンケートでは、回答者数が最多であったと思っています。

　参考として、弁護士会の会費について調べると次の情報が見つかりました。一部の引用です。

／＊＊＊＊＊＊＊＊＊＊（引用開始）＊＊＊＊＊＊＊＊＊＊
引用URL＞＞＞＞：http://www.danna-salary.com/about-money/lawyer-fee-compare/ 弁護士会の会費が鬼高い！税理士会の会費などその他士業の会費と比較してみた | 【節約投資のススメ〆】

最高年会費：1,178,400円(山口県岩国市部)
最低年会費：498,000円(愛知県)

弁護士会の会費を見て一番ビックリするのが、所属する弁護士会毎に会費が大きく違っている所です。確かに、他の士業でもある程度地域毎に会費の差は有りますが、年間70万円近くも負担額が変わるのは弁護士会だけでしょう。

＊＊＊＊＊＊＊＊＊＊（引用終了）＊＊＊＊＊＊＊＊＊＊／

　深澤諭史弁護士の設問だと年間12万円ということになります。上記の最高年会費が1,178,400円(山口県岩国市部)となっているので、約10分の1。設問自体が実態との落差が大きく弁護士として壊れているように思いますが、それでも682人が回答したというのも現実です。

　時刻は9月23日10時11分になっています。

ツイート：kk_hirono（告発-金沢地方検察庁御中_ツイッター）：2016/09/21 10:46： https://twitter.com/kk_hirono/status/778410158799986689 ：
引用→　 深澤諭史弁護士の設問だと年間12万円ということになります。上記の最高年会費が1,178,400円(山口県岩国市部)となっているので、約10分の1。設問自体が実態との落差が大きく弁護士として壊れているように思いますが、それでも682人が回答したというのも現実です。

　上記のツイートからの再開になりますが、その21日は、珠洲警察署に電話連絡をして、書面を提出することになりました。昨日の22日は、夜中の2時半頃に起きて早朝から夕方遅くまで、久しぶりに行った小木港の東一文字堤防でアジとアオリイカ釣りをやっていました。

　本当は、すぐに珠洲警察署に提出する書面の作成に取り掛かるつもりだったのですが、この項目と似たような形態で、深澤諭史弁護士が脈絡のはっきりしないツイートをしていたので、次にそれを取り上げておきたいと思います。

2016-09-23　金曜日　10：22　＜＜ ［［　←これまでの記述範囲の終了時刻］］＜＜
**** 「こういう事件こそ裁判員にしろよって話ですね(･∀･#)」という深澤諭史弁護士の脈絡の不明なツイート

:CATEGORIES: 深澤諭史弁護士
:TAGS: 深澤諭史弁護士

2016-09-23　金曜日　10：24　＞＞ ［［　←これからの記述範囲の開始時刻］］＞＞

投稿者：s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2016-09-23 09:59  ツイート： https://twitter.com/s_hirono/status/779122979451973632
2016-09-23-095923_警察も裁判官も職務としてやってるのに、なんで後者は違法不当な目的がないと不法行為にならないのか理解できない。.jpg https://t.co/3narEDYmO1

投稿者：s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2016-09-23 09:59  ツイート： https://twitter.com/s_hirono/status/779122874338545664
2016-09-23-095857_警察も裁判官も職務としてやってるのに、なんで後者は違法不当な目的がないと不法行為にならないのか理解できない。.jpg https://t.co/aR5NHmHZEJ

投稿者：s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2016-09-23 09:55  ツイート： https://twitter.com/s_hirono/status/779122091048079360
2016-09-23-095551_こういう事件こそ裁判員にしろよって話ですね（･∀･＃）.jpg https://t.co/u4ljRyaT8w

　３つのスクリーンショットからご紹介しましたが、関連が認められるのは次の二つのツイートだけでした。二つ目のツイートが、一つ目の深澤諭史弁護士のツイートにURLを引用されたツイートになります。

ツイート：fukazawas（深澤諭史）：2016/09/23 08:58： https://twitter.com/fukazawas/status/779107692728033284 ：
引用→　 こういう事件こそ裁判員にしろよって話ですね(･∀･#) https://t.co/UfQhTwCjDT

ツイート：mental_poverty（心の貧困）：2016/09/23 08:40： https://twitter.com/mental_poverty/status/779102996269379584 ：
引用→　 警察も裁判官も職務としてやってるのに、なんで後者は違法不当な目的がないと不法行為にならないのか理解できない。「当時警察から提出された証拠から嫌疑の相当性は認めざるを得なかった」て理屈なら分かるけど。

　初め、袴田事件に言及したツイートかと思ったのですが、心の貧困、というアカウントのタイムラインでは、一つ前のツイートが9月18日、その前のツイートが9月13日となっていたので、昨夜目にした袴田事件関係のツイートとは関係なさそうです。

投稿者：s_hirono（非常上告-最高検察庁御中_ツイッター） 日時：2016-09-23 10:32  ツイート： https://twitter.com/s_hirono/status/779131233934594049
2016-09-23-103211_2時間前警察も裁判官も職務としてやってるのに、なんで後者は違法不当な目的がないと不法行為にならないのか理解できない。「当時警察から提出された.jpg https://t.co/Inm30LfVui

　上記は、タイムラインのスクリーンショットの撮り直しをしたものです。前回は「ツイート」になっていたので、「ツイートと返信」に切り替えました。前者だと＠付きの返信ツイートが含まれないことになっているので、全てのツイートを見るには後者を開く必要があります。うっかり忘れがちです。

　確か昨夜見た袴田事件関係のツイートというのは、次になります。まだブラウザのタブでページを開いたままになっていましたが、誰のタイムラインのリツイートとして見つけたものであったのかは、すぐに思い出せません。昨夜は寝不足で特に思考力が低下していました。

ツイート：cho_seiho（CHO Seiho／趙誠峰）：2016/09/21 09:35： https://twitter.com/cho_seiho/status/778392232713785344 ：
引用→　 こういう検察のコメントをマスコミは声を大にして批判して、目的外使用規定をつぶすべき。＜改行＞誤った死刑が執行されようとしていた事件の原因の取調べテープが目的外使用もへったくれもあるか！＜改行＞このテープはおまえらのもんちゃうわ。 https://t.co/jzNFtPj8Vx

　上記のツイートは次のツイートのURLを引用しています。

ツイート：hayato821（Fukuda Hayato）：2016/09/20 23:05： https://twitter.com/hayato821/status/778233537275101185 ：
引用→　 袴田事件の三者協議。検察は、袴田さんの取調べテープの音声がテレビ番組で流されたことを「証拠の目的外使用だ」と弁護団を追及。だから「証拠リストは開示できません」とも言ってるらしい。でもこの規定、再審請求段階で検察が任意に開示した証拠は対象外って法務省の解説書に書いてありますけど。

　昨夜は寝不足に加え、モトケンこと矢部善朗弁護士（京都弁護士会）と小倉秀夫弁護士のタイムラインのツイートがお祭り状態だったので、その記録にも労力を費やし思考力が低下していたので、はっきりとは思い出せないのですが、やはり次のジャーナリスト江川紹子さんのリツイートだと思います。

リツイート：amneris84（Shoko Egawa）＞2016/09/21 13:09／2016/09/21 09:35＞ https://twitter.com/amneris84/status/778446022607450112 ＞
 cho_seiho （CHO Seiho／趙誠峰）＞ https://twitter.com/cho_seiho/status/778392232713785344 ＞
引用＞　 こういう検察のコメントをマスコミは声を大にして批判して、目的外使用規定をつぶすべき。＜改行＞誤った死刑が執行されようとしていた事件の原因の取調べテープが目的外使用もへったくれもあるか！＜改行＞このテープはおまえらのもんちゃうわ。 https://t.co/jzNFtPj8Vx 

　深澤諭史弁護士というのは、本当に判断に必要な情報を与えよとはしない、自分の都合の良い情報を自分の都合の良いかたちで与えようとする、弁護士にありがちな傾向性をわかりやすく例示してくれています。同時に、誤解を拡散されかねない危機感も感じています。

　他にも最近気になる反応だと思ったのは、テレビで大々的に報道されていた東大生による性犯罪事件の判決でした。被害者との間で示談が不成立ということになっていたように思いますが、その辺りが、弁護士らの不活性な反応になったのかとも考えました。

% for i in `cat ~/law_list.txt`; do m_search_tweet.rb "東大 判決" $i; done
〜弁護士奥村徹（児童ポルノ児童買春）（okumuraosaka）のツイート〜投稿日時〜2016/09/20 20:45〜ツイートのURL〜 https://twitter.com/okumuraosaka/status/778198478681886720 〜
#〜引用〜 なぜ、このような判決になったのだろうか。＼＼詳しい内容は動画をご覧ください。“わいせつ東大生”執行猶予４年のワケ #日テレNEWS24 #日テレ #ntv https://t.co/F2GA0T6cT5

〜弁護士奥村徹（児童ポルノ児童買春）（okumuraosaka）のツイート〜投稿日時〜2016/09/20 17:26〜ツイートのURL〜 https://twitter.com/okumuraosaka/status/778148382401519620 〜
#〜引用〜 量刑相場ですよね。　集団わいせつ事件、主犯格の東大生に有罪判決（TBS系（JNN）） - Yahoo!ニュース https://t.co/OHbx4JDUNT #Yahooニュース

〜弁護士奥村徹（児童ポルノ児童買春）（okumuraosaka）のツイート〜投稿日時〜2016/09/20 11:18〜ツイートのURL〜 https://twitter.com/okumuraosaka/status/778055633132068864 〜
#〜引用〜 懲役１年６カ月執行猶予３年（求刑懲役１年６カ月）「女子学生は頭悪い」とわいせつ行為　東大生に有罪判決：朝日新聞デジタル https://t.co/ta4b3BwfkJ

〜弁護士篠田奈保子（yorisoibengoshi）のツイート〜投稿日時〜2016/09/21 09:20〜ツイートのURL〜 https://twitter.com/yorisoibengoshi/status/778388362298138624 〜
#〜引用〜 性犯罪は性欲ではなく，支配欲からということが良くわかる。＼「自分より頭悪い」とわいせつ行為　東大生に有罪判決：朝日新聞デジタル https://t.co/9GNncQa460

〜寺町東子（teramachi_toko）のツイート〜投稿日時〜2016/09/20 17:50〜ツイートのURL〜 https://twitter.com/teramachi_toko/status/778154348664717312 〜
#〜引用〜 東京大学に行ってても、学歴でしか人を見られない人のほうが、頭悪いよなぁ。自分より頭が悪いと認定したら、人権蹂躙しても良いと思う、ってのも頭悪いよなぁ。｜「自分より頭悪い」とわいせつ行為　東大生に有罪判決：朝日新聞デジタル https://t.co/uixUknQ5UE

〜Kay（nkaoguo）のツイート〜投稿日時〜2016/09/21 09:13〜ツイートのURL〜 https://twitter.com/nkaoguo/status/778386539927576576 〜
#〜引用〜 わいせつ東大生、東大退学で示談できて不起訴取れる可能性があるんだったら、退学しとくべきだったなあ。自主退学して不起訴になれば海外の大学や大学院に入り直せる可能性もあったろうけど、判決出てしまうと渡航すら難しくなる国もあるんじゃないかしら。

　先日、本書でご紹介した検索のスクリプトを実行して出たデータですが、登録アカウントは現在100件です。前回129件としてご紹介しましたが、その後、4,5件の追加があったものの空白行を含めてカウントしていました。訂正します。

　埼玉県東松山市の河川敷であった複数の少年による殺害事件も、川崎の少年事件との対比もありますが、弁護士らの反応が奇妙なほど乏しいものでした。

告訴状の下書き）「こんなことが横行していて、しかもおとがめ無しなのに、」という高畑裕太氏の強姦致傷事件に関連した深澤諭史弁護士のツイート,http://hirono2016k.blogspot.com/2016/09/blog-post_23.html

　21日の中断から本日、強引に仕上げたのが上記のブログ記事にした項目ですが、そこで取り上げた深澤諭史弁護士の脈絡のはっきりさせないツイートは、深く考えさせられるところがあって、それが珠洲警察署への電話連絡の動機になりました。

　for i in `cat ~/law_list.txt`; do m_search_tweet.rb "高畑 文春" $i; done、の検索結果はゼロでした。

　ただし、上記のスクリプトで利用しているTwitterAPIの検索機能には、疑問があります。いくつか試して見たのですが、「専門家」をキーワードにしても結果がゼロで、「専門」にすると「専門家」を含むツイートが出てきました。

　半角のスペースがキーワードを挟めばANDの絞り込み検索になるはずです。「専門家」では該当しなかったものが、「専門家 家」だとぞろぞろとヒットしました。

% m_search_tweet.rb "専門家" motoken_tw

　上記のコマンドの実行は結果がゼロです。

% m_search_tweet.rb "専門 家" motoken_tw

　上記のコマンドで、キーワードに半角スペースを加えると、結果は次のようになりました。

〜モトケン（motoken_tw）のツイート〜投稿日時〜2016/09/22 21:55〜ツイートのURL〜 https://twitter.com/motoken_tw/status/778940708128378880 〜
#〜引用〜 @drhiromi 「専門家のツイート」を自分のツイートと読むんですねw

〜モトケン（motoken_tw）のツイート〜投稿日時〜2016/09/22 18:13〜ツイートのURL〜 https://twitter.com/motoken_tw/status/778884871607377922 〜
#〜引用〜 専門家のツイートというものが超上から目線であることがよく分かるw＼私のツイートもそう見えるんだろうな (^^;;;

〜モトケン（motoken_tw）のツイート〜投稿日時〜2016/09/22 17:30〜ツイートのURL〜 https://twitter.com/motoken_tw/status/778874221585833984 〜
#〜引用〜 .@drhiromi 専門家同士の議論の場合は双方が根拠をもって議論しますので、見ている人も諸説があると理解してくれる場合が多いと思いますが、最近、法律素人のナントカ博士（法学博士ではない）とか国会議員が、国籍法のデタラメな解釈を垂れ流しましたので黙っていられなかったわけです。

〜モトケン（motoken_tw）のツイート〜投稿日時〜2016/09/22 17:15〜ツイートのURL〜 https://twitter.com/motoken_tw/status/778870322409959424 〜
#〜引用〜 .@drhiromi あなたに対する私の最初のツイートはこれ。 https://t.co/EJFHTHdMOJ ネットの誤情報に対して専門家としてどう対応するか、の問題。分野は違うけど専門家の一人としての意見でした。医療限定の話ではなかったつもり。

〜モトケン（motoken_tw）のツイート〜投稿日時〜2016/09/22 17:04〜ツイートのURL〜 https://twitter.com/motoken_tw/status/778867521961066496 〜
#〜引用〜 私は法律家ですので「運動が体にいい，というこのフレーズの正誤って断定できますか？」というフレーズの医学的な専門的意見は述べられません。あなたは医師として、「二重国籍は違法だ。」というフレーズの評価ができますか？私が飛び交っている話… https://t.co/DLnvKfAtJE

〜モトケン（motoken_tw）のツイート〜投稿日時〜2016/09/22 16:59〜ツイートのURL〜 https://twitter.com/motoken_tw/status/778866381559259137 〜
#〜引用〜 この人は病院での患者の診断（弁護士で言えば、個別事件の訴訟）とネットでの誤情報対応を同視してるのかな？ネットの発言なら、わかる範囲でしかコメントしないのは専門家として当然だと私も思いますよ。しかし、読んだだけで明らかに間違いと分か… https://t.co/WYyQ0Z9P24

〜モトケン（motoken_tw）のツイート〜投稿日時〜2016/09/22 16:44〜ツイートのURL〜 https://twitter.com/motoken_tw/status/778862615854325760 〜
#〜引用〜 私は法律の専門家の端くれとして、ネットで、特に発信力や拡散力が強い人が間違った法律知識を書いていたら我慢ができずに訂正コメントをしてしまう人間ですけど、医師の中にも、間違った医学知識によって健康被害が生じないように訂正コメントをす… https://t.co/i3VESpzt2y

〜モトケン（motoken_tw）のツイート〜投稿日時〜2016/09/19 13:01〜ツイートのURL〜 https://twitter.com/motoken_tw/status/777719268116877312 〜
#〜引用〜 .@ikedanob 匿名の情報など専門家の話でもなんでもない。

〜モトケン（motoken_tw）のツイート〜投稿日時〜2016/09/19 12:46〜ツイートのURL〜 https://twitter.com/motoken_tw/status/777715458157883392 〜
#〜引用〜 .@ikedanob 全く普通ではない。そのような解釈をしている専門家がいますか？

〜モトケン（motoken_tw）のツイート〜投稿日時〜2016/09/19 12:25〜ツイートのURL〜 https://twitter.com/motoken_tw/status/777710120801214464 〜
#〜引用〜 .@ikedanob もともとは国籍法の解釈問題でしょ。そもそもあなたが「しかし14条違反（重国籍状態）だという結論は、」という誤った解釈に基づいて「今まで聞いた専門家は100％一致。」などと言うから話が混乱するんです。

　上記のTwitterAPIを利用した検索だと、一番古いものが2016/09/19 12:25のツイートになっています。同じような検索はWebのTwitterのページでも実行でき、これだと遡る件数の制限などもない、というかなくなったという情報を見たことがあります。

"専門 家" from:motoken_tw - Twitter検索 https://twitter.com/search?q=%22%E5%B0%82%E9%96%80%20%E5%AE%B6%22%20from%3Amotoken_tw&src=typd

　APIの検索で最も古かった検索結果のツイートの、上記のページの検索結果における一つ前のツイートは、次になります。意外に思ったのですが、同日のツイートでした。思っていた以上にAPIでの検索は結果の対象範囲が狭いようです。

ツイート：motoken_tw（モトケン）：2016/09/19 12:20： https://twitter.com/motoken_tw/status/777709037026619392 ：
引用→　 私は、残念なことではあるが、国会議員（の多くは）は法律解釈の専門家であるとは認められない。その帰結として、さらに残念なことではあるが、立法府の構成員である国会議員（の多く）は立法の専門家であるとは認められない。

　このような不備を補うためにも、私はデータベースにツイートを記録するようになりました。以前Twitterは勝手にフォローが外れるという問題もあったので、不測の事態による誤解を回避する対応策でもあります。

　さっそくですが、データベースのデータを利用して、「専門家」をキーワードに含むモトケンこと矢部善朗弁護士（京都弁護士会）のツイートをまとめ、ブログ記事にしました。100件単位の処理にしているので、次の３つの記事になります。

参考資料：「専門家」をキーワードに含む「モトケンこと矢部善朗弁護士（京都弁護士会）（@motoken_tw）」のツイート・リツイート（2010-03-15 19:00〜2016-09-22 21:55）「1-100／204」件,http://hirono2016k.blogspot.com/2016/09/motokentw2010-03-15-19002016-09-22_23.html
参考資料：「専門家」をキーワードに含む「モトケンこと矢部善朗弁護士（京都弁護士会）（@motoken_tw）」のツイート・リツイート（2010-03-15 19:00〜2016-09-22 21:55）「101-200／204」件,http://hirono2016k.blogspot.com/2016/09/motokentw2010-03-15-19002016-09-22_47.html
参考資料：「専門家」をキーワードに含む「モトケンこと矢部善朗弁護士（京都弁護士会）（@motoken_tw）」のツイート・リツイート（2010-03-15 19:00〜2016-09-22 21:55）「201-204／204」件,http://hirono2016k.blogspot.com/2016/09/motokentw2010-03-15-19002016-09-22_44.html

　上記のまとめ記事は、次の項目において活用する準備でもあります。

　自分の考えを全て文章として記述することは出来ないのですが、この項目で書いたように、深澤諭史弁護士のタイムラインにおけるツイートやリツイートは、小倉秀夫弁護士やモトケンこと矢部善朗弁護士（京都弁護士会）に対する処置にも大きな影響を与えており、過程の記録の必要を感じました。

　次は、いよいよ珠洲警察署に提出する書面の作成に取り掛かります。当初、別の書面として作成し、本書の参考資料とすることを考えていたのですが、昨夜の遅い時間にツイートやリツイートを読んでいて考えが変わり、本書の一部という構成で作成することにしました。

2016-09-23　金曜日　12：51　＜＜ ［［　←これまでの記述範囲の終了時刻］］＜＜
