* 「少年犯罪」「少年事件」「少年法」に関連した新潟の高島章弁護士の主なツイートの刑事弁護の歴史的資料、記録としてのまとめ

:CATEGORIES: 高島章弁護士
:TAGS: 高島章弁護士,少年犯罪

2016-08-30　火曜日　17：38　＞＞ ［［　←これからの記述範囲の開始時刻］］＞＞

ツイート：BarlKarth（高島章（弁護士））：2016/08/10 16:59： https://twitter.com/BarlKarth/status/763283600779255808 ：
引用→　 俺は、いまだに刑事訴訟の訴訟物が何か分からない。特に控訴審と少年審判。悩みぬいて頭の毛がなくなってしまった。「訴訟物だよ！」 https://t.co/Y7kWZZkG9Q

ツイート：BarlKarth（高島章（弁護士））：2016/07/21 21:28： https://twitter.com/BarlKarth/status/756103575063760896 ：
引用→　 @Tainyan_collins https://t.co/buX3vZIgsP人権派＜改行＞人権派弁護士は積極的に少年事件の担当や国選弁護人を務めるが、得る報酬は少なく、大半の事件では赤字となる。一部の利益の出る事件で得た収入を、人権問題の解決に回しており、その生活は豊かではない。

ツイート：BarlKarth（高島章（弁護士））：2015/05/28 23:15： https://twitter.com/BarlKarth/status/603927472636174336 ：
引用→　 悪がきが「今度の成人式、特攻服決めていくぜ」と告知したら、少年を逮捕するためにその辺をパトロールしたり、警備を強化したり（主催者にそのようにしてもらったり）すれば、「妨害」という構成要件てきけっかを作出できる。まさに犯罪のでっち上げと言ってよい。

ツイート：BarlKarth（高島章（弁護士））：2015/05/23 00:10： https://twitter.com/BarlKarth/status/601767038441234432 ：
引用→　 ドローン少年，勾留がついたのか？　予想は外れた。私が弁護人なら定石どおり勾留理由開示請求と準抗告だわな。まぁ，どう考えても起訴（公判請求）はなく，虞犯・あるいは威力業務妨害で家裁送致→観護措置決定（鑑別所送致）だろう。私が弁護人として付き合うとしても付添人は辞退する。

ツイート：BarlKarth（高島章（弁護士））：2015/05/21 17:19： https://twitter.com/BarlKarth/status/601301271123886081 ：
引用→　 ドローン少年に関連して，「少年法廃止」と言っている人が多いのだが，少年法を廃止したら，ドローン少年を野放しにすることになると言うことが分からないのだろうな。彼は恐らく，鑑別所収容になる。少年院送致の可能性も強い。少年法がなければ，勾留・起訴もなく野放し。

ツイート：BarlKarth（高島章（弁護士））：2015/03/11 00:58： https://twitter.com/BarlKarth/status/575324971121045504 ：
引用→　 @reddo1890 さんは少年（１９歳）でありながら袴田事件等の冤罪関係の集会に出席している。これは実に立派なことだろう。そういう冤罪に対する問題意識・憤りの気持ちは，素直な少年であれば必ず，社会全体にはびこる不条理や悪，矛盾と言ったものに目を向けていく方向に育っていくはずだ。

ツイート：BarlKarth（高島章（弁護士））：2015/03/06 12:56： https://twitter.com/BarlKarth/status/573693547250999296 ：
引用→　 川崎の事件に伴う少年法改正のツイートは，犯罪社会学会向けの良い話題になる。私が研究報告しようか。

ツイート：BarlKarth（高島章（弁護士））：2015/03/05 22:25： https://twitter.com/BarlKarth/status/573474456078692352 ：
引用→　 少年の場合は，少年法の適用により，成人の刑事事件よりずっと厳しくなると言ってよい。逮捕・勾留後は少年鑑別所に数週間身柄拘束される。その上で保護観察・少年院となる。どちらが厳しいか？　またどちらが更生に寄与するか？

ツイート：BarlKarth（高島章（弁護士））：2015/03/05 02:34： https://twitter.com/BarlKarth/status/573174811041529856 ：
引用→　 「少年法を振り回し，犯罪少年の刑を軽くするのは犯罪被害者警視もはなはだしい」という批判があるかもしれない。しかし，「法律を振り回し犯罪者の刑を軽くする」ことが少年事件に限らず刑事弁護人の役割なので，そういう批判をされるたら「それが私の職責です」というしかない。

ツイート：BarlKarth（高島章（弁護士））：2015/03/05 02:24： https://twitter.com/BarlKarth/status/573172202259935232 ：
引用→　 「少年法廃止」や「少年犯罪の厳罰化」という人は，その価値判断以前のレベルで，論理的混濁，分析不足が多い。

ツイート：BarlKarth（高島章（弁護士））：2015/03/04 18:27： https://twitter.com/BarlKarth/status/573052251612192768 ：
引用→　 @ns5zrakum5338w1 @tom10616 ご賛同ありがとうございます。少年法６１条が限定的でしかも罰則規定がないことから，ネット上では加害少年への人権侵害がやりたい放題ですね。一日も早く少年法６１条を改正し，違反者への厳罰規定を稲田総務会長にお願いしよう。

ツイート：BarlKarth（高島章（弁護士））：2015/03/04 17:04： https://twitter.com/BarlKarth/status/573031189902053376 ：
引用→　 このたびの川崎少年事件でお怒りの皆さん。諸悪の根源は，少年法６１条です。違反者には厳罰を！　賛成の方はRTを！

ツイート：BarlKarth（高島章（弁護士））：2015/03/04 16:55： https://twitter.com/BarlKarth/status/573028877460627457 ：
引用→　 「少年法６１条の改正を！」　皆さん！　少年法６１条は余りにも甘い規定です。今回の事件を機に稲田政調会長はじめ与党に改正を働きかけよう。賛成の方はRTを！

ツイート：BarlKarth（高島章（弁護士））：2015/03/04 16:11： https://twitter.com/BarlKarth/status/573017895673843712 ：
引用→　 出版物に限定しているのもだめ。＜改行＞違反者には刑事罰を科すべきだろう。＜改行＞＜改行＞今回の事件を機に，少年法を改正すべきだ。稲田政調会長もそう言っている様子。

ツイート：BarlKarth（高島章（弁護士））：2015/03/04 16:06： https://twitter.com/BarlKarth/status/573016665333493760 ：
引用→　 第六十一条 　家庭裁判所の審判に付された少年又は少年のとき犯した罪により公訴を提起された者については、氏名、年齢、職業、住居、容ぼう等によりその者が当該事件の本人であることを推知することができるような記事又は写真を新聞紙その他の出版物に掲載してはならない。

ツイート：BarlKarth（高島章（弁護士））：2015/03/04 16:03： https://twitter.com/BarlKarth/status/573015798043680769 ：
引用→　 確かに少年法は改正すべきだと，今回の事件で思った。

ツイート：BarlKarth（高島章（弁護士））：2012/08/02 11:36： https://twitter.com/BarlKarth/status/230854495381377024 ：
引用→　 　つい最近の新潟地裁（少年の殺人事件）は，やはり被告人に発達障害があり，弁護人は責任能力を争った。専門家証人３名が証言をしている。

ツイート：BarlKarth（高島章（弁護士））：2012/04/25 16:19： https://twitter.com/BarlKarth/status/195049422571319297 ：
引用→　 　後は，法廷が終わった後，プロ市民を集めて報告集会を開き人権派弁護士が「少年の人権は被害者より大事だ」みたいな報告をして「団結がんばろー」「インター斉唱」という感じ。

ツイート：BarlKarth（高島章（弁護士））：2012/04/25 15:46： https://twitter.com/BarlKarth/status/195041105824329728 ：
引用→　 「人権派弁護士」がどこかにアジトを設営していて，売名になりそうな事件がないか嗅ぎ周り，事件を見つけると呼んでもないのに警察署付近に現れて，マスメディアに「少年にも人権がー」とアジ演説をするというイメージ。

ツイート：BarlKarth（高島章（弁護士））：2012/04/24 13:47： https://twitter.com/BarlKarth/status/194648795634601984 ：
引用→　 京都弁護士会も大変だろう。被疑者の少年に当番弁護士（委員会派遣），被害者には被害者保護弁護士。ちょうど，池田小学校事件の速報の際，大阪の著名刑事弁護士と同宿していて，携帯電話書けまくっていたもんな。「いやぁ，大阪にいなくて良かった」とか述べていた。

2016-08-30　火曜日　18：15　＜＜ ［［　←これまでの記述範囲の終了時刻］］＜＜
